### ISSUE TITLE
Extent default request

### ISSUE THREAD

**Issue by mdsumner** [rspatial/terra#1]
I'd really like to see the default extent of a raster type be `xmin = 0, xmax = ncols, ymin = 0, ymax = nrows`, when generating a raster from a non-georeferenced source, i.e. a matrix or array. 

This is the equivalent in raster of applying the "index extent": 

```R
setExtent(r, extent(0, ncol(r), 0, nrow(r))) 
```

It's also a sensible default for when there's no regular coordinate axes for a source, i.e. a rectilinear (xs or ys are not regularly spaced) - rather than as now with `stopIfNotEqualSpaced` in raster. 

I'd be very happy to provide PRs for this in terra if it's agreeable. The real advantage comes from a very natural "index referencing", that we can easily conceive and use - and any cropped subset has a simple record of its placement in the original grid that is very neat.  

I use this for various tricks in coordinate systems, especially for working with curvilinear grids (where the locations of cells are 2D data, not affine or rectlinear axes) - but it's also handy for relating various index grids to each other, without requiring messy geographic values. I think if this was the default for matrix/array it would make these tricks more accessible and useful. 

Another advantage is that the aspect ratio of a non-referenced grid (matrix) is completely straightforward for `image()`, whereas now the "iso" case requires the ratio of ncol to nrow. 

Thanks!  (Looking foward to some interesting conversations and work with this package)

**Comment by rhijmans** [comment]
OK, done. Thanks for the suggestion.
