### ISSUE TITLE
how to rotate with terra?

### ISSUE THREAD

**Issue by ibarraespinosa** [rspatial/terra#10]
Hello,

How can I rotate with terra?

Thanks

![Captura de tela_2019-05-22_13-45-15](https://user-images.githubusercontent.com/27447280/58150066-0ad33d80-7c98-11e9-8217-95a7e10a382b.png)

**Comment by rhijmans** [comment]
I added a `rotate` method, please try it.

**Comment by ibarraespinosa** [comment]
Hi @rhijmans  Thanks. However, it gives me an error

![Captura de tela_2019-05-25_22-25-45](https://user-images.githubusercontent.com/27447280/58370767-f5327200-7f3c-11e9-80b7-9477a2d089d6.png)

**Comment by rhijmans** [comment]
Thanks for letting me know. Can you send me the properties of the raster,
that is, `show(qv)`

> show(x)
class       : SpatRaster
dimensions  : 9, 18, 1  (nrow, ncol, nlyr)
resolution  : 20, 20  (x, y)
extent      : 0, 360, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84
data source : memory
names       : lyr.1
min values  :     1
max values  :   162

**Comment by ibarraespinosa** [comment]
Hello and thanks again

I think it is not reading the CRS

```
show(qv)
class       : SpatRaster 
dimensions  : 1280, 2560, 38  (nrow, ncol, nlyr)
resolution  : 0.140625, 0.140625  (x, y)
extent      : 0, 360, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. :  
data source : /home/sergio/Downloads/cape/ms_qv_200801010000.nc 
names       : ms_qv_2008010100001, ms_qv_2008010100002, ms_qv_2008010100003, ms_qv_2008010100004, ms_qv_2008010100005, ms_qv_2008010100006, ms_qv_2008010100007, ms_qv_2008010100008, ms_qv_2008010100009, ms_qv_20080101000010, ms_qv_20080101000011, ms_qv_20080101000012, ms_qv_20080101000013, ms_qv_20080101000014, ms_qv_20080101000015, ... 

```

**Comment by rhijmans** [comment]
Thanks. I can now do this:

```
library(terra)
x <- rast(nrow=1280, ncol=2560, nlyr=38, xmin=0, xmax=360, ymin=-90, ymax=90)
values(x) <- rep(as.vector(t(matrix(1:ncell(x), nrow=nrow(x), ncol=ncol(x)))), nlyr(x))

r <- rotate(x)
crs(r) <- "+proj=longlat +datum=WGS84"
r

plot(x[[1]])
plot(r[[1]])
```

So I assume you can now use rotate on your data as well.
