### ISSUE TITLE
corLocal in terra?

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#100]
Is there a terra function doing the equivalent to raster::corLocal()?

**Comment by aloboa** [comment]
When implementing corLocal(), please include:
1. step or jump argument to move the slicing window to increase the speed of the processing (at the expense of final resolution)
2.  The following optional outputs:
- intercept and slope of the linear fit
- slope of the linear fit forcing intercept=0

Also, would it be possible a "generalized slicing window" function in which the use would actually define what function to apply within each window?

**Comment by rhijmans** [comment]
added to https://github.com/rspatial/terra/wiki

**Comment by rhijmans** [comment]
This has now been implemented as `focalCor` 

See: https://rspatial.github.io/terra/reference/focalCor.html

Sorry for the wait.
