### ISSUE TITLE
Undocumented behavior of setValues when dim(values) == dim(raster)

### ISSUE THREAD

**Issue by srfall** [rspatial/terra#1000]
I stumbled upon an undocumented functionality of `setValues`. When you want to replace values in a raster with values from a matrix of the same size, the current behavior makes much sense:
````
f <- system.file("ex/elev.tif", package = "terra")
r <- rast(f)
set.values(r)
r_matrix_wide <-terra::as.matrix(r, wide = TRUE)

all(nlyr(r) == 1 & dim(r_matrix_wide) == dim(r)[1:2])
# TRUE

x_empty <- rast(r)
x_replaced  <- setValues(x_empty, r_matrix_wide) 

terra::all.equal(r, x_replaced)
# basically the same
````

But the documentation says: `values: [....] The number of columns of the matrix or data.frame must match the number of layers of x, and the number of rows must match the number of cells of x` 
https://rspatial.github.io/terra/reference/setValues.html

So since this is not officially documented: Is this functionality meant to stay and the doc is just missing or is it recommended to directly use
https://github.com/rspatial/terra/blob/0ee7230ef6d3617a7213077227d126618d2a31b8/R/values.R#L143

to assure that the values end up in the right place?

**Comment by rhijmans** [comment]
This is now documented. Thanks for pointing out the omission.

**Comment by srfall** [comment]
Thanks for the clarification :)
But could it be that there is a typo? ->  #1001
