### ISSUE TITLE
terra::merge & NA handling

### ISSUE THREAD

**Issue by jmmonnet** [rspatial/terra#1002]
Hello,
I noticed that in the latest versions of the terra package (1.7.3 and 1.7.6) the NA values are not handled by terra::merge. A reproducible example can be found from a previous issue on the same topic. [https://github.com/rspatial/terra/issues/160](https://github.com/rspatial/terra/issues/160).
Thank you for this great package !

**Comment by rhijmans** [comment]
Thanks very much for reporting. I believe it is fixed again. I think I tried to speed up the algorithm and re-introduced this bug. Very annoying; I have now added a test that should detect this.
