### ISSUE TITLE
documentation for spatial subsetting

### ISSUE THREAD

**Issue by plantarum** [rspatial/terra#1003]
I need to subset a polygon SpatVector object, selecting the individual polygons in which one or more points in another SpatVector object occur.

I think this can be accomplished with the following:

```r
library(terra)
f <- system.file("ex/lux.shp", package="terra")
p <- vect(f)
pts <- matrix(c(6, 6.1, 5.9, 5.7, 6.4, 50, 49.9, 49.8, 49.7, 49.5), ncol=2)
spts <- vect(pts, crs=crs(p))

selectedPolygons <- p[spts, ]

plot(p)
plot(selectedPolygons, col = 2, add = TRUE)
points(spts, pch = 16, cex = 2)
```

![terra](https://user-images.githubusercontent.com/5727138/217090246-b2b72d01-7526-4aa1-8793-dac37d45a62d.jpg)

However, I couldn't find this in the `terra` documentation or tutorials. After a search, I found the same approach in `sf`, and then thought to try it in `terra` and indeed it works.

If I haven't just overlooked this in the existing docs (and I'm sorry if I have) , it would be a good thing to add. 

The existing docs are quite amazing otherwise, thanks for all your work!

Tyler

**Comment by rhijmans** [comment]
Thanks, I have added a link in `intersect`.  This is now documented under   ?`[`  but I do not think it is easy to find there.

A less direct approach is 

```
i <- is.related(p, spts, "intersects")
x  <- p[i, ]
```

**Comment by plantarum** [comment]
Thanks! I thought that `is.related` looked like a possible solution to my issue, but I wasn't sure of the details. 

Best,

Tyler
