### ISSUE TITLE
expected behavior of `is.lonlat()`

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#1006]
I noticed that the `is.lonlat()` warning-related arguments might not be working as intended per the documentation.

The following work as expected:
``` r
library(terra)
#> terra 1.7.7

# as expected
x <- rast(system.file("ex", "elev.tif", package="terra"))
is.lonlat(x)
#> [1] TRUE

# as expected
x2 <- project(x, "+proj=igh")
is.lonlat(x2)
#> [1] FALSE
```

But when the CRS of an object is not known, and default `warn=TRUE` argument is set, it seems there is no warning for missing CRS (docs say there should be one). 

```r
# CRS not known: no warning; returns a missing value
crs(x) <- ""
is.lonlat(x)
#> [1] NA

# but perhaps=TRUE works as expected
is.lonlat(x, perhaps = TRUE)
#> [1] TRUE
#> Warning message:
#> [is.lonlat] assuming lon/lat crs
```

Also no warning if the CRS has been set to long/lat but coordinates are IGH (in this example), with or without `perhaps`

```r
# CRS inconsistent: no warning; CRS is longitude/latitude but the coordinates do not match 
crs(x2) <- "OGC:CRS84"

is.lonlat(x2)
#> [1] TRUE

# same when perhaps=TRUE
is.lonlat(x2, perhaps=TRUE)
#> [1] TRUE

head(crds(x2))
#>            x       y
#> [1,] 1518911 5555715
#> [2,] 1519594 5555715
#> [3,] 1520277 5555715
#> [4,] 1520961 5555715
#> [5,] 1518911 5555032
#> [6,] 1519594 5555032
```

---

I don't feel particularly strongly about whether these should be warnings. I would understand requiring `perhaps=TRUE` for warnings to be generated.

**Comment by rhijmans** [comment]
That was a mess. I now get 

```
library(terra)
terra 1.7.7

x <- rast(system.file("ex", "elev.tif", package="terra"))
#x <- as.polygons(aggregate(x,10))
is.lonlat(x)
#[1] TRUE
 
x2 <- project(x, "+proj=igh")
is.lonlat(x2)
#[1] FALSE
 
crs(x) <- ""
is.lonlat(x)
#[1] NA
#Warning message:
#[is.lonlat] unknown crs 
 
is.lonlat(x, perhaps = TRUE)
#[1] TRUE
#Warning message:
#[is.lonlat] assuming lon/lat crs 
 
crs(x2) <- "OGC:CRS84"
is.lonlat(x2)
#[1] TRUE
#Warning message:
#[is.lonlat] coordinates are suspect for lon/lat 
 
is.lonlat(x2, perhaps=TRUE)
#[1] TRUE
#Warning message:
#[is.lonlat] coordinates are suspect for lon/lat 
``` 
 
So if `warn=TRUE & perhaps=TRUE` a warning is given when the crs is not specified but assumed to be lon/lat. 
Other warnings are given irrespective of the value of `warn`; but it would also be possible to suppress all warnings with `warn=FALSE`.

**Comment by brownag** [comment]
That works for me! Thanks for the fix.  

Having a warning in the case where I stumbled across this would have alerted me to the issue (missing CRS) a bit quicker.
