### ISSUE TITLE
roadmap for terra development?

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#101]
Is there a roadmap for terra development (i.e., when terra will be leveling raster)?

**Comment by rhijmans** [comment]
Nothing formal. In some ways terra has overtaken raster (faster, simpler, but also new functions such as `rapp`, `sds`). There are very few raster operations left to be implemented (mosaic is perhaps the main one). The main area where terra still lags is vector handling. The best way to get things done is keeping doing what you do: ask for it.

**Comment by rhijmans** [comment]
I started a list here: https://github.com/rspatial/terra/wiki
