### ISSUE TITLE
Why does Windows build require additional libraries?

### ISSUE THREAD

**Issue by mfansler** [rspatial/terra#1010]
I am trying to understand why the Windows build links against so many additional libraries. That is, when looking at build logs on all other platforms, I only ever see `-lgdal -lgeos -lgeos_c -lproj`. In contrast, the `Makevars.win` includes more than a dozen extra libraries:

https://github.com/rspatial/terra/blob/7cc6ed81287c0f447801b262c0cf300df134608b/src/Makevars.win#L9-L20

Why is this? Is this really a necessary set, or is it just including everything provided by [`rwinlib/gdal3`](https://github.com/rwinlib/gdal3) simply because it is in there?

**Comment by rhijmans** [comment]
Most of these are there to support the use of GDAL plugins for reading and writing different file formats. Some seem obscure (mariadb, jasper), but others, such as geotiff netcdf sqlite3 and hdf5, are essential. 

On most platforms an installation from source would include the same libraries but you may not realize it. For example on OSX you could use "brew" to install GDAL and these libraries would be included (perhaps not exactly the same but close enough). Likewise with the Ubuntu GDAL package.

**Comment by mfansler** [comment]
Thanks for the reply. However, I'm still confused because the other platforms never explicitly link those other libraries during the package build. That is, GDAL, etc. libraries will already be linked against their dependent libraries. So, I still don't understand why this package needs to explicitly link against such dependencies of dependencies. Shouldn't the `-lgdal` etc. be sufficient? Is there something about these static libraries that requires the additional specifications?

**Comment by rhijmans** [comment]
I do not know.  I suppose it is related to how linking works on windows vs linux.  A person to ask would be Tomas Kalibera, the maintainer of Rtools (Jeroen would also know as it worked the same with his GDAL install).

But it may be more similar on other platforms that it seems. The terra `configure` script uses `gdal-config` to set PKG_LIBS

On my Ubuntu that shows 

```
$gdal-config --dep-libs
-lheif -lcrypto -larmadillo -lpoppler -ljson-c -L/usr/lib -lfreexl -lqhull -lqhull -lgeos_c -lwebp -lodbc -lodbcinst -lkmlbase -lkmldom -lkmlengine -lkmlxsd -lkmlregionator -lexpat -lxerces-c -lpthread -lopenjp2 -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -lhdf5 -lmfhdfalt -ldfalt -logdi -lgif -lCharLS -lgeotiff -lpng -lcfitsio -lpq -llz4 -lblosc -lzstd -llzma -lsqlite3 -lproj -lsqlite3 -ltiff -ljpeg -ldeflate -lz -lpthread -lm -lrt -ldl -L/usr/lib -lspatialite -lpcre -lcurl -lfyba -lfygm -lfyut -lxml2 -lmysqlclient -lpthread -ldl -lz -lssl -lcrypto -lresolv -lm -lrt
```

**Comment by rhijmans** [comment]
Reopening since I understand that you are asking this in the context of building the package on Anaconda.

**Comment by edzer** [comment]
The makefile you're looking at is used by CRAN to build a binary package. R binary packages built by CRAN for Windows or MacOS use static linking, other platforms typically use dynamic linking. Static linking requires all libraries involved to be listed during the build step; they all end up in the resulting terra.dll which is huge, but doesn't need any of the other .dll's. 

On my linux system, the `terra.so` links dynamically to another 122 libraries:
```bash
$ ldd /home/edzer/R/x86_64-pc-linux-gnu-library/4.0/terra/libs/terra.so | wc
    122     484    9227
```
If any of these are updated, I may have to reinstall `terra` to keep things working.

You can of course build binaries for any platform using dynamic linking, but you'd have to use your own makefile, and manage the dynamically linked libraries in addition to the terra R package. CRAN doesn't do that for binary packages.

**Comment by rhijmans** [comment]
Thanks @edzer

**Comment by mfansler** [comment]
@edzer thanks - that very much clarifies the distinction.
