### ISSUE TITLE
Minor grammar fix in documentation

### ISSUE THREAD

**Issue by idblr** [rspatial/terra#1025]
While reviewing the documentation for the `project()` function I noticed a minor grammatical error ("the the") in the Note section. A quick search in the repo shows five other instances in the following files:

[man/which.Rd](https://github.com/rspatial/terra/blob/7895beb503827a71a9654a17802bb3f59ac9ec8f/man/which.Rd)
[man/shard.Rd](https://github.com/rspatial/terra/blob/c133566a5ca2b723f9316924bef94698544b1efa/man/shade.Rd)
[man/rapp.Rd](https://github.com/rspatial/terra/blob/615cf602c605b2de8df19136382127c010907396/man/rapp.Rd)
[man/project.Rd](https://github.com/rspatial/terra/blob/201a0a9bb12094a9a0ac66d1ad1248979474c3e0/man/project.Rd)
[man/plot.Rd](https://github.com/rspatial/terra/blob/776e05ad5f2123c8d824f72ea1ee3aec310bc7e1/man/plot.Rd)
[misc/SimpleIni.h](https://github.com/rspatial/terra/blob/331cdf5323d5a67cc03e04cfa5aa27d88a06d4d0/misc/SimpleIni.h)

Not urgent

**Comment by rhijmans** [comment]
Thanks!
