### ISSUE TITLE
strange memory issues in different PCs

### ISSUE THREAD

**Issue by strevisani** [rspatial/terra#1026]
Hi all

 I tried the code below with different PCs (versions of terra terra 1.6.53) and the strange thing is that with a I5 processor with 8Gb of memory, windows 10 it works ( and it works also with windows 8 with 4gb of RAM!) but with a I7 processor with 16gb of memory, windows 11 it doesn't.
 
I got messages of "bad alloc" or "cannot allocate vector of size ..."
Then I notice that I need to call gc() to free memory from the system after the error message.

I changed also memfrac, but nothing changes.

Interesting thing: if I reboot the system, it works the first time I try it (but not the second, even calling gc() before...)

I'm not able to figure out the possible reasons.

```
#a test for the issue 
theTest=rast(nrows=5000, ncols=5000, nlyrs=18, xmin=0, ymin=0, vals=3333.333)
mem_info(theTest)
theDataFrame=as.data.frame(theTest)
```

_Originally posted by @strevisani in https://github.com/rspatial/terra/issues/996#issuecomment-1435025520_

**Comment by kadyb** [comment]
It is a bit strange that this doesn't work for 16 GB as this raster takes up ~3.6 GB. Maybe it will work if you initialize the file on disk (not in memory) and then convert? In this way:

```r
r = rast(nrows=5000, ncols=5000, nlyrs=16, xmin=0, ymin=0)
r = init(r, fun = 3333.333, filename = "test.tif")
df = as.data.frame(r)
```

And maybe returning matrix will work better than data frame: `matrix = values(r)`?

**Comment by strevisani** [comment]
Hi, 

thank you!
 The point is that I'm not able to understand why it works on other systems with less resources. It seems something related to memory management or garbage collectors. I tried also to reinstall R and R studio. So I'm wondering if others noticed this kind of problems.  Maybe it is my machine that has some issues; but few months ago I did not observed this behavior.

**Comment by rhijmans** [comment]
Can you show *exactly* what you see. That is, include the output of `mem_info` and the error message where it occurs (after the code that causes it.)

**Comment by strevisani** [comment]
Hi, thank you for the quick reply! I'm not in a hurry so please enjoy the weekend!
I'm already grateful for having developed "terra".

Anyway, I made other tests and it seems that this issue happens randomly (some time the code below works and sometime not, I was not able to find a relationship with other factors)

Here the complete session not working:

------------------------------------------------------------------
> library(terra)
terra 1.6.53
> #a test for the issue
> theTest=rast(nrows=5000, ncols=5000, nlyrs=18, xmin=0, ymin=0, vals=3333.333)
> mem_info(theTest)                       

------------------------
Memory (GB) 
------------------------
check threshold : 1  (memmin)
available       : 10.7
allowed (60%)   : 6.42
needed (n=1)    : 3.35
------------------------
proc in memory  : TRUE
nr chunks       : 1
------------------------
> theDataFrame=as.data.frame(theTest)
Error: cannot allocate vector of size 1.7 Gb
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
---------------------------------------------------------------------


I also tried to experiment with large object not related to terra.
These work, even if the size of the object is bigger.

> ######################
> theTest=matrix(333333.333,nrow=25000000,ncol=25)
> print(object.size(theTest),units="auto")
4.7 Gb
> theDataFrame=as.data.frame(theTest)
> print(object.size(theTest),units="auto")
4.7 Gb

**Comment by rhijmans** [comment]
You seem to have sufficient memory, but there may not be sufficient contiguous memory. 
Using `init` and conservative `terraOptions` may provide a work-around. Still a bit mysterious why this happens.

**Comment by strevisani** [comment]
Yes, it is mysterious indeed. I can only suppose that is a problem of this specific PC, because I tried it in other five different machines and it worked. At this point I would close the issue, likely it is not at all related to terra.
S
