### ISSUE TITLE
classify value mistake

### ISSUE THREAD

**Issue by TianyaImpression** [rspatial/terra#1027]
R 4.22
terra 1.6.41

I try to use the terra package classification function to simplify the classification of ESA LUCC. After running the code that is reclassified according to the following results, the result is not the value I want? Is it a bug of the classify function?

Code:
```
library(terra)

#read Roi
MProi = vect("./ROI.gpkg", query = 'SELECT * FROM MongoliaTuLatest')
plot(MProi)

#read ESA LUCC data, data downloaded from: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-land-cover?tab=form
esalucc2001 = rast("G:/Geodata/ESACCILUCC/ESACCI-LC-L4-LCCS-Map-300m-P1Y-2001-v2.0.7cds.nc", "lccs_class")
esalucc2001_mp = trim(mask(esalucc2001, MProi))
plot(esalucc2001_mp)
writeRaster(esalucc2001_mp, "./ESALUCC/esalucc2001.tif")

#reclassify
m = c(10,  40,  1,    #Agriculture
      50,  100, 2,   #Forest
      110, 119, 3,   #Grassland
      120, 122, 7,   #Shrubland
      130, 139, 3,   #Grassland
      140, 153, 8,   #Sparse vegetation
      160, 170, 2,   #Forest
      180, 189, 4,   #Wetland
      190, 199, 5,   #Settlement
      200, 202, 9,   #Bare areas
      210, 219, 10,  #Water
      220, 229, 11)  #Snow

rclmat = matrix(m, ncol = 3, byrow = T)
esalucc2001_mp_ipcc = classify(esalucc2001_mp, rclmat, include.lowest=T, right=T)
plot(esalucc2001_mp_ipcc)
```

esalucc2001_mp_ipcc  drawed in QGIS:

These values are obviously inconsistent with the values specified for classify

![image](https://user-images.githubusercontent.com/22004043/219957977-9606681e-a3e3-4efe-9812-378c0e29a0f6.png)

Thank you for your help!

**Comment by Rapsodia86** [comment]
Looks like when right=TRUE, then setting include.lowest=TRUE or include.lowest=FALSE gives the same result. 
But right=NA, which is equivalent to include.lowest=TRUE & right=TRUE works as it should.

**Comment by rhijmans** [comment]
As @Rapsodia86  points out, with your reclassification matrix you should use `right=NA`

Illustrated here 

```
library(terra)
r <- rast(ncol=5, nrow=5)
values(r) <- 0:24 

m = c( 0,  10,  1,
	  11,  25,  2)
m = matrix(m, ncol=3, byrow=TRUE)

x <- classify(r, m)
unique(x)
#  lyr.1
#1     0
#2     1
#3     2
#4    11

## use right = NA
x <- classify(r, m, right=NA)
unique(x)
#  lyr.1
#1     1
#2     2
``` 

You can also change the classification matrix

```
## with include.lowest
m = c( 0,  10,  1,
	  10.5,  25,  2)
m = matrix(m, ncol=3, byrow=TRUE)

x <- classify(r, m, include.lowest=TRUE)
unique(x)
#  lyr.1
#1     1
#2     2

## without include.lowest

m = c( -0.5,  10,  1,
	  10.5,  25,  2)
m = matrix(m, ncol=3, byrow=TRUE)

x <- classify(r, m)
unique(x)
#  lyr.1
#1     1
#2     2
```

**Comment by Rapsodia86** [comment]
But then according to documentation: 
"You can also close both sides with `right=NA`, that is only meaningful if you "from-to-becomes" classification with integers. For example to classify 1-5 -> 1, 6-10 -> 2, 11-15 -> 3. That may be easier to read and write than the equivalent 1-5 -> 1, 5-10 -> 2, 10-15 -> 3 with` right=TRUE` and` include.lowest=TRUE`"
Setting `right=NA` or (` right=TRUE` and` include.lowest=TRUE`) 
```
esalucc2001_mp_ipcc1 = classify(esalucc2001_mp, rclmat, right=NA)
esalucc2001_mp_ipcc2 = classify(esalucc2001_mp, rclmat, include.lowest=T, right=T)
```
shouldn't we get the same results? Or in this instance it due to the classification matrix?

**Comment by rhijmans** [comment]
I think you misinterpret `include.lowest`. It only applies to the lowest number in the matrix. That is 1 in this example. Not to the lowest number in each row. Am I right?

**Comment by Rapsodia86** [comment]
Aaaa, indeed! Ok! Thank you very much for the clarification!:)
