### ISSUE TITLE
Cpp issues

### ISSUE THREAD

**Issue by athammad** [rspatial/terra#1028]
I have recently put my hands back on a project started a few months ago and while rerunning all my code I noticed the following two issues that I did not have before:

# Warning
```
r <- rast(ncols=10, nrows=10)
values(r) <- 1:ncell(r)
s <- c(r, r, r, r, r, r)
s <- s * 1:6
b1 <- tapp(s, index=c(1,1,1,2,2,2), fun=mean)
writeCDF(b1, "xxx.nc", overwrite=TRUE)

Warning message:
In new_CppObject_xp(fields$.module, fields$.pointer, ...) :
  GDAL Message 1: dimension #0 (time) is not a Time or Vertical dimension.

```
# Error
What worries me is the following error that I cannot yet reproduce in a simple way. 
The error pops up after a very long loop where I am doing some sliding window calculations. Please note that I am not saving any files locally in the loop. 
```
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>, : NULL value passed as symbol address
```

I am running my code on a server with docker on ubuntu20.04. I have tried to use both the stable and dev version of `terra` but the error still persists.

**Comment by rhijmans** [comment]
I do not see that warning with the current (dev) version on Ubuntu 18 nor 20. The error I cannot respond to. I would need to see the `traceback()`.   But these errors are odd, and I would think that they are related to peculiarities of your installation.

**Comment by athammad** [comment]
Indeed I do not get any warning when running the examples in `?writeCDF`. This is strange. 

Regarding the error, I will need 2 days to run the code to then run `traceback()` as you requested. I am wondering if this is an error that appears only on very long computations and it might be related to the way R is dealing with the garbage collection. 

I just would like to add that these issues were not present at the time of #890.

**Comment by kadyb** [comment]
I also don't see this warning on Ubuntu 22.04, but I noticed strange behavior in `{stars}`. If I directly save this object using `write_stars()` everything is ok. But if I use the `write_mdim()` function first (it returns 5 warnings) and then the `write_stars()` function, I get similar warning as @athammad.

```r
library("stars")
x = st_as_stars(b1)
write_stars(x, "xxx.nc") # no warning

write_mdim(x, "xxx.nc") # 5 warnings
write_stars(x, "xxx.nc")
#> Warning message:
#> In CPL_write_gdal(mat, file, driver, options, type, dims, from,  :
#>   GDAL Message 1: dimension #0 (band) is not a Time or Vertical dimension.

sf::sf_extSoftVersion()
#>          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
#>       "3.9.3"        "3.5.2"        "8.2.1"         "true"         "true"        "8.2.1" 
```

**Comment by rhijmans** [comment]
The _error_ you get seems related to not having a valid C++ pointer. That happens if you use `save` and `load`. But you state you do not do that, so this is very puzzling.

**Comment by athammad** [comment]
Yes, @rhijmans. I know about the pointer issue during `save` and `load` , but I am not saving or loading anything.

**Comment by rhijmans** [comment]
Closing for a lack of follow-up
