### ISSUE TITLE
Incorporar operaciones entre 2 o más pilas SpatRaster

### ISSUE THREAD

**Issue by djwillichile** [rspatial/terra#1029]
Estoy intentando realizar operaciones cómo correlación o regresión entre dos series de tiempo (pilas SpatRaster). En este caso, 16 capas de NDVI y 16 capas de Precipitación. Para el caso de la correlación el resultado esperado son dos capas SpatRaster (coeficiente de correlación y valor p), mientras que, para la regresión, el resultado esperado son tres capas SpatRaster (intercepto, pendiente y coeficiente de determinación). ¿Hay alguna forma de implementar estas operaciones?

**Comment by djwillichile** [comment]
entoendo que antes para esto se utilizaba la función overlay, pero ya no encuentro esta función

# S4 method for SpatRaster,SpatRaster
overlay(x, y, fun, ..., filename="", overwrite=FALSE, wopt=list())

**Comment by rhijmans** [comment]
This site is to report bugs and request new functionality. For general questoins I suggest you use [stackoverflow](https://stackoverflow.com/). 

You can do something like this:

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
set.seed(1)
r <- setValues(s, runif(size(s), 100, 200))

xcor = app(c(s, r), fun=\(x)cor(x[1:3], x[4:6]))
xreg = app(c(s, r), fun=\(x) coefficients(lm(x[4:6] ~ x[1:3])))
```

But seeing this, I think I will add a new method `capp` that would allow for 

```
capp(s, r, fun=cor)
capp(s, r, fun=\(x,y) coefficients(lm(y~x)))
```

**Comment by djwillichile** [comment]
Muchas gracias!
Saluda cordialmente
Guillermo S. Fuentes Jaque

Ing. en Recursos Naturales Ren.
Ms. Gestión Territorial de Rec. Nat.
UNIVERSIDAD DE CHILE

**Comment by rhijmans** [comment]
This can now be done more elegantly with `lapp` and a SpatRasterDataset.

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
set.seed(1)
r <- setValues(s, runif(size(s), 100, 200))

# make a SpatRasterDataset
d <- sds(s,r)

xc <- lapp(d, cor)
xr <- lapp(d, fun=\(x, y) coefficients(y ~ x))

# the latter can now also be done with 
rr <- regress(r, s)
```
