### ISSUE TITLE
crop() with mask=TRUE does not save to the file 

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1030]
I am using dev version 1.7-12

I have two rasters, one used as a template to which I want to crop and mask.
If `crop(rast1,rast2, mask=FALSE, filename="test.tif")` then the result is saved to the file 
if `crop(rast1,rast2, mask=TRUE, filename="test2.tif")` then the result does not show in the directory

**Comment by rhijmans** [comment]
Thank you, I now get: 
```
library(terra)
#terra 1.7.12
r <- rast(system.file("ex/elev.tif", package="terra"))
v <- vect(system.file("ex/lux.shp", package="terra"))
x <- mask(r, v[9:12,])
 
z <- crop(r, x, mask=TRUE, filename="test.tif", overwrite=TRUE)
z
#class       : SpatRaster 
#dimensions  : 46, 60, 1  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 5.808333, 6.308333, 49.45, 49.83333  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : test.tif 
#name        : elevation 
#min value   :       212 
#max value   :       432 
```

**Comment by Rapsodia86** [comment]
After reinstalling the package, I am getting: "Warning message:
PROJ: proj_create_from_name: Cannot find proj.db (GDAL error 1) " when do crop & mask to the file or just regular writeRaster().
Nothing changed since yesterday, except the reinstallation of terra dev. GDAl version "3.5.2"
