### ISSUE TITLE
In .getSpatDF(x@ptr$df) : NAs introduced by coercion to integer range

### ISSUE THREAD

**Issue by plantarum** [rspatial/terra#1031]
Hi,

I encountered a warning message that made me a bit anxious when dealing with integer data in a SpatVector, rather than numeric. Maybe it's expected behaviour, but in case I want to check with you.

Here's an example. With numeric values no warnings:

```R
library(terra)

mydataNum <- data.frame(decimalLongitude = c(-117.44605, -111.833333, 
                                                 -100.90306, 1.86),
                            decimalLatitude = c(33.27299, 34.8486939991149,
                                                21.41167, 41.59),
                            year = c(2019, 2019, NA, NA))

mydataNum <- vect(mydataNum, geom = c("decimalLongitude",
                                      "decimalLatitude"))
mydataNum$year
```

> [1] 2019 2019   NA   NA

With the same data, but coded as integers I get warnings:

```R
mydataInt <- data.frame(decimalLongitude = c(-117.44605, -111.833333, 
                                                 -100.90306, 1.86),
                            decimalLatitude = c(33.27299, 34.8486939991149,
                                                21.41167, 41.59),
                            year = c(2019L, 2019L, NA, NA))
mydataInt <- vect(mydataInt, geom = c("decimalLongitude",
                                      "decimalLatitude"))
mydataInt$year
```

> [1] 2019 2019   NA   NA
> Warning message:
> In .getSpatDF(x@ptr$df) : NAs introduced by coercion to integer range

It looks like the actual data is correct, but on a large object I worry I might miss some errors if I'm doing something wrong. I'm not sure how I ended up with integer data in the first place, the source data was initially downloaded from GBIF via rgbif.

This is with Terra 1.7.6.

Thanks,

Tyler

**Comment by rhijmans** [comment]
Thanks, I did not see that warning on windows, but I did see it on Ubuntu.  It was indeed a false alarm, but I revised the code a bit (https://github.com/rspatial/terra/commit/670872271fcaa4c80313873d0f7f4ba8ce7b4fd0) and now I do not get warnings with your example or with the below where I test more data types.

```
library(terra)
d <- data.frame(lon = c(-117.44, -111.83, -100.90306, 1.86),
                lat = c(33.27, 34.84, 21.41, 41.59),
                year = c(2019L, 2019L, NA, NA),
				name = c("A", "汉字", "Côte d'Ivoire", NA),
				bool = c(T,T,F,NA),
				val = c((1:3)/2,NA),
				dat = c(as.Date("2001-01-01") + 1:3, NA),
				fac = as.factor(c("A", "汉字", "Côte d'Ivoire", NA)))
				
m <- vect(d, geom = c("lon", "lat"))
as.data.frame(m)

#  year          name  bool val        dat           fac
#1 2019             A  TRUE 0.5 2001-01-02             A
#2 2019           汉字  TRUE 1.0 2001-01-03           汉字
#3   NA Côte d'Ivoire FALSE 1.5 2001-01-04 Côte d'Ivoire
#4   NA          <NA>    NA  NA       <NA>          <NA>
```
