### ISSUE TITLE
Unable to read extent from netCDF-4 input file

### ISSUE THREAD

**Issue by vvirkki** [rspatial/terra#1033]
Hi, I'm finding some weird behaviour with reading netCDF-4 files with terra. terra::rast() doesn't recognise the extent of the data, which raster::stack() is able to do. This also depends on if the ".nc" file extension is present in the file name that is read. I can do a workaround in my application via by reading in data <- terra::rast(file_in) and setting terra::ext(data) <- terra::ext(raster::stack(data)). I'm wondering, however, if this behaviour is due to terra or perhaps GDAL?

Here's a reproducible example:

    # use nc extension in target filename explicitly
    target_file_nc <- paste0(tempfile(), ".nc")
    download.file(url = "https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc",
                  destfile = target_file_nc)
    
    terra_rast_nc <- terra::rast(target_file_nc)
    raster_stack_nc <- raster::stack(target_file_nc)
    
    terra::ext(terra_rast_nc)
    terra::ext(raster_stack_nc)
    raster::extent(raster_stack_nc)
    
    terra::ext(terra_rast_nc) <- terra::ext(raster_stack_nc) # workaround
    terra::ext(terra_rast_nc)
    
    # not using .nc extension in target filename
    target_file <- tempfile()
    download.file(url = "https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc",
                  destfile = target_file)
    
    terra_rast <- terra::rast(target_file)
    raster_stack <- raster::stack(target_file)
    
    terra::ext(terra_rast)
    terra::ext(raster_stack)
    raster::extent(raster_stack)

Here's my output:

    > # use nc extension in target filename explicitly
    > target_file_nc <- paste0(tempfile(), ".nc")
    > download.file(url = "https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc",
    +               destfile = target_file_nc)
    trying URL 'https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc'
    Content type 'application/x-netcdf' length 120716798 bytes (115.1 MB)
    ==================================================
    downloaded 115.1 MB
    
    > 
    > terra_rast_nc <- terra::rast(target_file_nc)
    Warning message:
    [rast] unknown extent 
    > raster_stack_nc <- raster::stack(target_file_nc)
    Loading required namespace: ncdf4
    Warning messages:
    1: In .varName(nc, varname, warn = warn) : varname used is: aclcac
    If that is not correct, you can set it to one of: aclcac, ao3, q, relhum, sd, st, svo, tpot, xi, xl
    2: In .rasterObjectFromCDF(x, type = objecttype, band = band, ...) :
      "level" set to 1 (there are 47 levels)
    > 
    > terra::ext(terra_rast_nc)
    SpatExtent : 0, 2, 0, 2080 (xmin, xmax, ymin, ymax)
    > terra::ext(raster_stack_nc)
    SpatExtent : -0.9375, 359.0625, -89.5045071299442, 89.5045071299442 (xmin, xmax, ymin, ymax)
    > raster::extent(raster_stack_nc)
    class      : Extent 
    xmin       : -0.9375 
    xmax       : 359.0625 
    ymin       : -89.50451 
    ymax       : 89.50451 
    > 
    > terra::ext(terra_rast_nc) <- terra::ext(raster_stack_nc) # workaround
    > terra::ext(terra_rast_nc)
    SpatExtent : -0.9375, 359.0625, -89.5045071299442, 89.5045071299442 (xmin, xmax, ymin, ymax)
    > # not using .nc extension in target filename
    > target_file <- tempfile()
    > download.file(url = "https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc",
    +               destfile = target_file)
    trying URL 'https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc'
    Content type 'application/x-netcdf' length 120716798 bytes (115.1 MB)
    ==================================================
    downloaded 115.1 MB
    
    > 
    > terra_rast <- terra::rast(target_file)
    Warning message:
    [rast] unknown extent 
    > raster_stack <- raster::stack(target_file)
    Warning message:
    [rast] unknown extent 
    > 
    > terra::ext(terra_rast)
    SpatExtent : 0, 2, 0, 2080 (xmin, xmax, ymin, ymax)
    > terra::ext(raster_stack)
    SpatExtent : 0, 2, 0, 2080 (xmin, xmax, ymin, ymax)
    > raster::extent(raster_stack)
    class      : Extent 
    xmin       : 0 
    xmax       : 2 
    ymin       : 0 
    ymax       : 2080 

And sessionInfo() output:

    sessionInfo()
    R version 4.2.2 (2022-10-31)
    Platform: x86_64-apple-darwin17.0 (64-bit)
    Running under: macOS Ventura 13.2.1
    
    Matrix products: default
    LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    loaded via a namespace (and not attached):
     [1] compiler_4.2.2   tools_4.2.2      sp_1.6-0         Rcpp_1.0.10      raster_3.6-14    codetools_0.2-18
     [7] ncdf4_1.21       grid_4.2.2       lattice_0.20-45  terra_1.7-3

**Comment by rhijmans** [comment]
You need to specify the sub-dataset (variable) of interest. Otherwise, terra tries to combine all variables with the highest number of observations (those are typically the rasters), but in this case that is not working because some variables do not have lon/lat dimensions.  "raster" picks the first variable for you and that works in this case.

Get the data 
```
library(terra)
url = "https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc"
f <- basename(url)
if (!file.exists(f)) download.file(url, f, mode="wb")
```

With terra 

```
r <- terra::rast(f, "aclcac")
r
#class       : SpatRaster 
#dimensions  : 96, 192, 376  (nrow, ncol, nlyr)
#resolution  : 1.875, 1.864677  (x, y)
#extent      : -0.9375, 359.0625, -89.50451, 89.50451  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : test_echam_spectral-deflated.nc:aclcac 
#varname     : aclcac (cloud cover) 
#names       : aclca~v=1_1, aclca~v=2_1, aclca~v=3_1, aclca~v=4_1, aclca~v=5_1, aclca~v=6_1, ... 
#time (days) : 2003-12-01 
```

Similar with raster, but note that "raster" picks one level, while terra collapses that dimension (you get subset them with the layer names.

```
library(raster)
b <- raster::brick(f, varname="aclcac")
#Warning message:
#In .rasterObjectFromCDF(x, type = objecttype, band = band, ...) :
#  "level" set to 1 (there are 47 levels)
b
#class      : RasterBrick 
#dimensions : 96, 192, 18432, 8  (nrow, ncol, ncell, nlayers)
#resolution : 1.875, 1.864677  (x, y)
#extent     : -0.9375, 359.0625, -89.50451, 89.50451  (xmin, xmax, ymin, ymax)
#crs        : +proj=longlat +datum=WGS84 
#source     : test_echam_spectral-deflated.nc 
#names      : X2003.12.01.1, X2003.12.01.2, X2003.12.01.3, X2003.12.01.4, X2003.12.01.5, X2003.12.01.6, X2003.12.01.7, X2003.12.01.8 
#Date       : 2003-12-01, 2003-12-01, 2003-12-01, 2003-12-01, 2003-12-01, 2003-12-01, 2003-12-01, 2003-12-01 
varname    : aclcac 
#level      : 1 
```

Another option with "terra" is to create a SpatRasterDataset

```
s <- sds(f)
#Warning message:
#[sds] extents do not match (lsp)
#extents do not match (sd)
#extents do not match (st)
#extents do not match (svo) 
s
#class       : SpatRasterDataset 
#subdatasets : 123 
#dimensions  : 96, 192 (nrow, ncol)
#nlyr        : 8, 376, 8, 8, 8, 8, 8, 8, 8 
#resolution  : 1.875, 1.864677  (x, y)
#extent      : -0.9375, 359.0625, -89.50451, 89.50451  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source(s)   : test_echam_spectral-deflated.nc 
#names       : abso4, aclcac, aclcov, ahfcon, ahfice, ahfl, ... 
```

You can then extract a sub-dataset with   `s["aclcac"]`, `s$aclcac`, or `s[2]`

**Comment by vvirkki** [comment]
Hi, thanks for your guidance with this. Unfortunately, I am not seeing similar output in my environment as in your example. For some reason, variable aclcac is not found at all, and if I switch the variable name to something else as per your example, extent and CRS remain missing. Same applies to using sds, but without the need for prepending layer names with "//":

    url = "https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc"
    f <- basename(url)
    if (!file.exists(f)) download.file(url, f, mode="wb")
    
    terra::rast(f, "aclcac")
    terra::rast(f, "//aclcac")
    terra::rast(f, "//aclcov")
    
    s <- terra::sds(f)
    s["aclcov"]
    s$aclcov

Here's the output. I can't spot what I'm doing differently here?

    > url = "https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc"
    > f <- basename(url)
    > if (!file.exists(f)) download.file(url, f, mode="wb")
    trying URL 'https://www.unidata.ucar.edu/software/netcdf/examples/test_echam_spectral-deflated.nc'
    Content type 'application/x-netcdf' length 120716798 bytes (115.1 MB)
    ==================================================
    downloaded 115.1 MB
    
    > terra::rast(f, "aclcac")
    Error: [rast] aclcac not found. Choose one of:
    //abso4, //aclcov, //ahfcon, //ahfice, //ahfl, //ahfliac, //ahfllac, //ahflwac, //ahfres, //ahfs, //ahfsiac, //ahfslac, //ahfswac, //albedo, //albedo_nir, //albedo_nir_dif, //albedo_nir_dir, //albedo_vis, //albedo_vis_dif, //albedo_vis_dir, //alsobs, //alsoi, //alsol, //alsom, //alsow, //ameltdepth, //ameltfrac, //amlcorac, //apmeb, //apmegl, //aprc, //aprl, //aprs, //aps, //az0i, //az0l, //az0w, //barefrac, //dew2, //drain, //evap, //evapiac, //evaplac, //evapwac, //fage, //friac, //geosp, //glac, //gld, //lsp, //qres, //qvi, //runoff, //seaice, //siced, //sicepdi, //sicepdw, //sicepres, //slm, //sn, //snacl, //snc, //sni, //snifrac, //snmel, //sofliac, //sofllac, //soflwac, //srad0, //srad0d, //srad0u, //sradl, //srads, //sradsu, //sraf0, //srafl, //srafs, //t2max, //t2min, //temp2, //thvsig, //topmax, //trad0, //tradl, //trads, //tradsu, //traf0, //trafl, //trafs, //trfliac, //trfllac, //trflwac, //tropo, //tsi, //tsicepdi, //tslm1, //t
    > terra::rast(f, "//aclcac")
    Error: [rast] //aclcac not found. Choose one of:
    //abso4, //aclcov, //ahfcon, //ahfice, //ahfl, //ahfliac, //ahfllac, //ahflwac, //ahfres, //ahfs, //ahfsiac, //ahfslac, //ahfswac, //albedo, //albedo_nir, //albedo_nir_dif, //albedo_nir_dir, //albedo_vis, //albedo_vis_dif, //albedo_vis_dir, //alsobs, //alsoi, //alsol, //alsom, //alsow, //ameltdepth, //ameltfrac, //amlcorac, //apmeb, //apmegl, //aprc, //aprl, //aprs, //aps, //az0i, //az0l, //az0w, //barefrac, //dew2, //drain, //evap, //evapiac, //evaplac, //evapwac, //fage, //friac, //geosp, //glac, //gld, //lsp, //qres, //qvi, //runoff, //seaice, //siced, //sicepdi, //sicepdw, //sicepres, //slm, //sn, //snacl, //snc, //sni, //snifrac, //snmel, //sofliac, //sofllac, //soflwac, //srad0, //srad0d, //srad0u, //sradl, //srads, //sradsu, //sraf0, //srafl, //srafs, //t2max, //t2min, //temp2, //thvsig, //topmax, //trad0, //tradl, //trads, //tradsu, //traf0, //trafl, //trafs, //trfliac, //trfllac, //trflwac, //tropo, //tsi, //tsicepdi, //tslm1, /
    > terra::rast(f, "//aclcov")
    class       : SpatRaster 
    dimensions  : 96, 192, 8  (nrow, ncol, nlyr)
    resolution  : 1, 1  (x, y)
    extent      : 0, 192, 0, 96  (xmin, xmax, ymin, ymax)
    coord. ref. :  
    source      : test_echam_spectral-deflated.nc://aclcov 
    varname     : aclcov 
    names       : aclcov_1, aclcov_2, aclcov_3, aclcov_4, aclcov_5, aclcov_6, ... 
    Warning message:
    [rast] unknown extent 
    > s <- terra::sds(f)
    Warning message:
    [sds] unknown extent
    extents do not match (lsp) 
    > s["aclcov"]
    class       : SpatRaster 
    dimensions  : 96, 192, 8  (nrow, ncol, nlyr)
    resolution  : 1, 1  (x, y)
    extent      : 0, 192, 0, 96  (xmin, xmax, ymin, ymax)
    coord. ref. :  
    source      : test_echam_spectral-deflated.nc://aclcov 
    varname     : aclcov 
    names       : aclcov_1, aclcov_2, aclcov_3, aclcov_4, aclcov_5, aclcov_6, ... 
    Warning message:
    [`[`] unknown extent 
    > s$aclcov
    class       : SpatRaster 
    dimensions  : 96, 192, 8  (nrow, ncol, nlyr)
    resolution  : 1, 1  (x, y)
    extent      : 0, 192, 0, 96  (xmin, xmax, ymin, ymax)
    coord. ref. :  
    source      : test_echam_spectral-deflated.nc://aclcov 
    varname     : aclcov 
    names       : aclcov_1, aclcov_2, aclcov_3, aclcov_4, aclcov_5, aclcov_6, ... 
    Warning message:
    [`[`] unknown extent

**Comment by rhijmans** [comment]
Perhaps the different results are because I am using the development version of terra. It could also be due to a different version of GDAL. I have:

```
gdal()
[1] "3.6.2"
```

**Comment by vvirkki** [comment]
That did the trick; I had gdal 3.4.2 and CRAN binary of terra 1.7-3. Reinstalled GDAL 3.6.2 using homebrew and CRAN terra 1.7-3 from source. Thanks!
