### ISSUE TITLE
installing from R with install.packages() fails due to downloaded length being < reported length

### ISSUE THREAD

**Issue by plorch** [rspatial/terra#1035]
Install.packages fails.  Using devtools and install_github("rspatial/terra") also fails. Not sure if this is an Rstudio, R or terra problem.

install.packages("terra")
Installing package into ‘C:/Users/PatrickLorch/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/terra_1.7-3.zip'
Content type 'application/zip' length 28083287 bytes (26.8 MB)
downloaded 13.6 MB

Warning in install.packages :
  downloaded length 14262393 != reported length 28083287
Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/terra_1.7-3.zip': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/windows/contrib/4.2/terra_1.7-3.zip' failed
Warning in install.packages :
  download of package ‘terra’ failed

C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lblosc
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lkea
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lsz
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'terra'

**Comment by rhijmans** [comment]
Your download failed. That is not something I can help you with

**Comment by rhijmans** [comment]
Failure to install the development version can have other reasons. But if you want to try the development version then installing from R-Universe is the easiest. 

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
```

**Comment by plorch** [comment]
Thanks.  The weather we are having may be reducing internet speeds.  Thanks for the alternative install method.
