### ISSUE TITLE
`SpatRaster` conversion to integers

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#1036]
From the discussion at https://github.com/rspatial/terra/issues/763, I understand that internally everything is a double in **terra**. However, would it be possible to provide an automatic conversion to integers (e.g., in matrices or in vectors) for integer rasters (those for which `is.int(r)` returns `TRUE`)? (I am hoping for reduced memory imprint for this conversion for large rasters...)

``` r
library(terra)
#> terra 1.7.3
f = system.file("ex/elev.tif", package="terra")
r = rast(f)
is.int(r)
#> [1] TRUE

m = as.matrix(r)
str(m)
#>  num [1:8550, 1] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : NULL
#>   ..$ : chr "elevation"
typeof(m)
#> [1] "double"

v = values(r)
str(v)
#>  num [1:8550, 1] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : NULL
#>   ..$ : chr "elevation"
typeof(v)
#> [1] "double"

a = as.vector(r)
str(a)
#>  num [1:8550] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
typeof(a)
#> [1] "double"
```

**Comment by rhijmans** [comment]
I now get

```
library(terra)
#terra 1.7.14
f = system.file("ex/elev.tif", package="terra")
r = rast(f)
 
m = as.matrix(r)
typeof(m)
#[1] "integer"
 
v = values(r)
typeof(v)
#[1] "integer"
 
a = as.vector(r)
typeof(a)
#[1] "integer"
```

The downside of this may be that a number that is too large for to R represent as integer would become NA. That may not happen in real life, or at least not frequently.

As for memory use. It could be avoided to generate doubles in the first place. Some day I may build that in, but it is a big effort. Not a priority yet.

**Comment by Nowosad** [comment]
Thank you @rhijmans for the changes and the explanation.
