### ISSUE TITLE
Plet to allow ‘2.1.1’ leaflet version

### ISSUE THREAD

**Issue by lime-n** [rspatial/terra#1037]
The example provided in the R documentation for [Terra:::plet](https://rdrr.io/cran/terra/man/plet.html) only works for leaflet greater than version 2.1.1, could you perhaps have meant >= 2.1.1 rather than > 2.1.1?

**Comment by rhijmans** [comment]
That is not a mistake. It only works with leaflet > 2.1.1. That is, it does not work with the current CRAN version. That is why  `?plet` suggests that you install the development version of leaflet with `remotes::install_github("rstudio/leaflet").`
