### ISSUE TITLE
app() function with a condition gives an error

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1042]
Hi @rhijmans,
I am not sure if that should go to [StackOverflow](https://stackoverflow.com/), if so please close it.

I have a function (called `convert_date()`) that converts pixel values based on some conditions. 
When I apply it using app() it gives me `Error in if (is.na(band_data)) { : the condition has length > 1`
I thought that `app()` works pixel-wise and has an internal vectorization. However, looks like I am wrong because it works if I do  `Vectorize()` on the function (`convert_date_vect <- Vectorize(convert_date)`). 
However, a much simpler version of the function **without any conditioning** works properly without `Vectorize()`.
So, why does the condition throw the error?

Here is an example:

terra 1.7.15
```
convert_date <- function(band_data,yy){

  lyd1 <- ifelse(leap_year(yy-1),366,365)
  lyd2 <- ifelse(leap_year(yy),366,365)
  
  if (is.na(band_data)){
    new_doy <- NA
  }else{
    dx <- as_date(band_data,origin="1970-01-01")
    dy_raw <- lubridate::yday(dx)
    if(dx < ymd(paste0(yy,"01-01"))){
      new_doy <- dy_raw - lyd1 - 1
    } else if(dx > ymd(paste0(yy,"12-31"))){
      new_doy <- dy_raw + lyd2
    }else{
      new_doy <- dy_raw
    }
  }
  return(new_doy)
}
```
```
convert_date2 <- function(band_data,yy){
  dx <- as_date(band_data,origin="1970-01-01")
  dy_raw <- lubridate::yday(dx)
  return(dy_raw)
}
```

`convert_date_vect <- Vectorize(convert_date)`

```
r10 <- rast(nrow = 10, ncol = 10,vals=seq(11875,12073,2)) #input raster 
yy <- 2003
```

```
new_doy_convert <- terra::app(r10, fun=function(x){convert_date(x,yy)}) #Function with condition, FAILS, no vectorization
new_doy_convert <- terra::app(r10, fun=function(x){convert_date_vect(x,yy)}) #Function with condition, WORKS, vectorized
new_doy_convert2 <- terra::app(r10, fun=function(x){convert_date2(x,yy)}) #Function without condition, WORKS, no vectorization
```

Thanks!

**Comment by rhijmans** [comment]
The function needs to be vectorized.  It is not: 

```
x <- as.matrix(r10[1:5])
convert_date(x, yy=2003)
#Error in if (is.na(band_data)) { : the condition has length > 1 
``` 
Whereas this one is

```
convert_date(x, yy=2003)
#Error in if (is.na(band_data)) { : the condition has length > 1
``` 

Your first function could need be rewritten like this:

```
vconvert_date <- function(band_data,yy){
  lyd1 <- ifelse(leap_year(yy-1), 366, 365)
  lyd2 <- ifelse(leap_year(yy), 366, 365)
  i <- !is.na(band_data)
  dx <- as_date(band_data[i], origin="1970-01-01")
  new_doy <- lubridate::yday(dx)
  j <- dx < ymd(paste0(yy,"01-01"))  
  new_doy[j] <- new_doy[j] - lyd1 - 1
  j <- dx > ymd(paste0(yy,"12-31"))
  new_doy[j] <- new_doy[j] + lyd2
  out <- rep(NA, length(i))
  out[i] <- new_doy
  out
}
```

(on SO I would ask what your goal is as this seems unnecessarily complicated)

**Comment by Rapsodia86** [comment]
That is a teachable moment! 
Indeed, I do not need those conditions at all, it can go by indexing! Thank you! 
So, to have an "if condition" when using app(), I need to vectorize the function first since it reads in data as a matrix/array?
Ok, next time this kind of stuff goes to StackOverflow with more explanation. 

Thank you again and sorry for taking your time!
