### ISSUE TITLE
typo in some "SRS not defined" error messages

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1043]
Hello,
There seems to be a (inconsistent) typo in some error messages. For example:
```
A <- vect(cbind(839769, 4199443))
B <- vect(cbind(1038608, 4100024))
distance(A, B)  # Error: [distance] SRS not defined
```
I assume "SRS" should be "CRS", right? Oddly, though, if I instead provide a matrix of 3 points:
```
locs <- terra::vect(matrix(c(839769, 4199443, 1038608, 4100024, 1017819, 4206255), ncol = 2, byrow = TRUE))
distance(locs)  # Error: [distance] crs not defined
```
i.e. the same function gives a differently spelled error message under different circumstances.
I've spotted this "SRS" typo other times, though I can't remember if it was with 'distance' or other function(s).
Cheers!

**Comment by rhijmans** [comment]
Thanks, fixed. This was more an inconsistency than a spelling mistake (srs = spatial reference system). And these are different functions (one for a matrix, the other for a SpatVector).

**Comment by AMBarbosa** [comment]
Thanks for the explanation!
