### ISSUE TITLE
add 'crop=FALSE' option to 'plot' with 'ext' argument

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1044]
I think this didn't happen in earlier versions, but now when we plot a SpatVector and use the 'ext' argument, the map is cropped to that extent instead of filling the remaining space available in the plotting window:
```
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
d <- subset(v, v$NAME_2 == "Diekirch")
plot(v, ext = ext(d), col = "tan", background = "lightblue")
```
![image](https://user-images.githubusercontent.com/12085508/222705834-0f181a8d-b405-4cf0-8d40-3098a74b26fe.png)

There can be great advantages to this behaviour, but it is not always desirable and it makes some maps look weird. So, I'd suggest adding a 'crop=TRUE' argument to 'terra::plot'. Thanks!

**Comment by rhijmans** [comment]
Thanks, that crept in yesterday and was not intentiional. I have restored it to what it was. Still thinking about the `crop = TRUE` argument.  Currently, you could get the result you would get with `crop=TRUE` by 

```
plot(v, border="white")
lines(crop(v, ext(d)))
```
 or 

``` 
plot(v, ext=ext(d), xlim=ext(v)[1:2], ylim=ext(v)[3:4])
```
