### ISSUE TITLE
sel(), draw() and zoom() get shifted locations

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1046]
They used to work as expected back in the day, but with relatively recent versions of terra and RStudio, `sel()`, `draw()` and `zoom()` get very different locations than the ones where the map is clicked, making it impossible to use them with any precision. Tried with the help file examples on both Linux and Windows. Cheers

**Comment by kadyb** [comment]
This is probably bug in RStudio, not `{terra}`. See: https://github.com/rstudio/rstudio/issues/12682. In terminal it should work fine.

**Comment by AMBarbosa** [comment]
Thanks -- I'm closing the issue then. Let's hope RStudio fixes it soon.

**Comment by rhijmans** [comment]
Unfortunately, this does not work in the current version of RStudio, and I am not aware of a work-around for RStudio.  But it does work on more standard plotting devices.
