### ISSUE TITLE
Why filetype="TIF" in writeRaster is invalid ?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#1047]
I do not understand why `PNG` is accepted as a `filetype`, but not `TIF`, in `writeRaster`:

```
> library(terra)
terra 1.7.3
> r <- rast(ncols=2, nrows=2, vals=1)
> writeRaster(r,"test1",filetype="PNG")
> writeRaster(r,"test2",filetype="TIF")
Error: [writeRaster] invalid driver
```

**Comment by Nowosad** [comment]
@jldupouey I assume that `"PNG"` is a driver name, while `"TIF"` is not (see `terra::gdal(drivers = TRUE)`). 

Btw, there is `GTiff` on the list.

**Comment by jldupouey** [comment]
You are wright, the correct `gdal` name is `GTiff`. Thanks.
