### ISSUE TITLE
Data with color table: when crop & mask adds 0s instead of 255s for INT1U rasters

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1048]
Hi @rhijmans 
 
I originally was using NLCD that have a color table. When crop & mask, values outside are stored as 0 and that is a problem since 0 is also a valid value. At least when exploring in ArcGIS.

See example:
```
f <- system.file("ex/elev.tif", package="terra")
r<- rast(f)
r <- setValues(r, 0:99)
f2 <- system.file("ex/lux.shp", package="terra")
v <- vect(f2)

nctb_cm <- crop(r, v[1,], mask=TRUE,filename="test_nctb.tif",overwrite=TRUE,wopt=list(datatype='INT1U'))

coltb <- data.frame(value=0:99, col=rainbow(100, end=.9))
coltab(r) <- coltb
ctb_cm <- crop(r, v[1,], mask=TRUE,filename="test_ctb.tif",overwrite=TRUE,wopt=list(datatype='INT1U'))

```
Values in yellow should be NoData but in ArcGIS pro are 0? 
![image](https://user-images.githubusercontent.com/55965799/222805470-ed141ed2-cd46-4f93-ae5e-cdc0a530b06c.png)

But data in memory show NA outside mask correctly:
```
plot(ctb_cm,colNA="grey")
plot(nctb_cm,colNA="grey",legend=FALSE)
```
![image](https://user-images.githubusercontent.com/55965799/222807302-6735c7c1-6dbd-48c1-9dbe-bbeb4fe0d464.png)
![image](https://user-images.githubusercontent.com/55965799/222807714-f7d894c2-c897-4613-87a1-0cd5b8db1c4d.png)

Something related to the #620 maybe?
Thanks!

**Comment by rhijmans** [comment]
I do not have easy access to ArcGIS pro but in ArcMap 10.8.1 I get the same map as in R.

<img width="469" alt="arcmap" src="https://user-images.githubusercontent.com/11481397/222809497-0fc5b432-11cb-4565-baa5-6f0d4e0f106f.png">

**Comment by rhijmans** [comment]
And I am puzzled by "When crop & mask, values outside are stored as 0"?  In my NLCD data there are no values outside of the 0 to 255 range (but I may have a different dataset). Can you be more specific?

**Comment by Rapsodia86** [comment]
A value of 0 is valid for NLCD TreeCanopy and Impervious datasets (both percentages)
I put yellow to NA for test_nctb.tif to see the background. 
But indeed, in ArcMap, pixels outside the mask are both NoData! Well, that is disturbing for ArcGIS Pro users.
![image](https://user-images.githubusercontent.com/55965799/222839055-51ac4194-a3c1-461a-835a-fda379b5fea1.png)

Thank you for checking it and sorry about the fuss!
