### ISSUE TITLE
How to keep NA values with writeRaster and PNG files?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#1049]
Following https://github.com/rspatial/terra/issues/134, I'm a bit confused with the handling of `NA` values when writing PNG files with `writeRaster`. 

I wonder why the value `NA` is not kept by `writeRaster`, but replaced by 0, in the following example:

```
library(terra)
# terra 1.7.3

r <- rast(ncols=16, nrows=16, vals=0:255)

r[120]=NA

rr <- writeRaster(r, "testr.png", overwrite=TRUE)

rr[120]
#  lyr.1
#1     0
```

Is there a way to preserve NA values when writing such PNG files?

**Comment by kadyb** [comment]
You can use `NAflag` argument in `writeRaster()` to specify what number use to mark missing values, e.g.: `writeRaster(r, "testr.png", overwrite=TRUE, NAflag=0)`.

**Comment by jldupouey** [comment]
Thanks kadyb, but your proposal just adds a new problem. Now, `0`, which was not considered a `NA` value in the initial raster, and was even a value contained in cell 1, became a `NA` value after the `PNG` file was written:

```
library(terra)
# terra 1.7.3

r <- rast(ncols=16, nrows=16, vals=0:255)
r[1]
#  lyr.1
#1     0

r[120]=NA

rr <- writeRaster(r, "testr.png", overwrite=TRUE, NAflag=0)

rr[1]
#  lyr.1
#1    NA

rr[120]
#  lyr.1
#1    NA
```

How to keep the `NA` values of the original raster in the `PNG` file, and only those?

**Comment by kadyb** [comment]
> Now, 0, which was not considered a NA value in the initial raster, and was even a value contained in cell 1

This is expected, because you used 0 to specify NA. You can use different value, e.g. 999, but then you have to change the datatype from `Byte` to e.g. `Int16`.

**Comment by jldupouey** [comment]
Thanks, it works fine. Now I want to add a color table. And there, it doesn't work anymore:

```
r <- rast(ncols=16, nrows=16, vals=0:255)
 
coltb <- data.frame(t(col2rgb(rainbow(256), alpha=TRUE)))
coltab(r) <- coltb

r[120]=NA

rr <- writeRaster(r, "testr.png", overwrite=TRUE, NAflag=999, datatype="INT2U")
#Error: [writeRaster] mem copy create failed for PNG
#In addition: Warning messages:
#1: libpng: Invalid IHDR data (GDAL error 1) 
#2: [writeRaster] change datatype to INT1U to write the color-table
```

Do you have any idea why? The color table seem to be accepted only with the `INT1U` data type. Is it possible to build a `PNG` with a color table and `NA` values? Or, is my color table not correct?

**Comment by brownag** [comment]
> The color table seems to be accepted only with the `INT1U` data type. Is it possible to build a `PNG` with both a color table and `NA` values?

Yes it is possible, but you need to use a NAflag value within [0,255] range to use `INT1U`. 

With your color table you can depict 256 unique colors, but one of those 256 colors can't be shown depending on choice of `NAflag`. Using `NAflag` value outside [0,255] with `INT1U` output will cause those values to be converted to `0`.

This works, with the color table, but you lose the ability to use e.g. the 255 value/color for data:
``` r
library(terra)
#> terra 1.7.3
r <- rast(ncols=16, nrows=16, vals=0:255)

coltb <- data.frame(t(col2rgb(rainbow(256), alpha=TRUE)))
coltab(r) <- coltb

r[120] <- NA

rr <- writeRaster(r, "testr.png", overwrite=TRUE, NAflag=255, datatype="INT1U")

plot(rr)
```

![](https://i.imgur.com/uF5YPH6.png)

```r
rr[120]
#>   lyr.1
#> 1    NA
```

**Comment by rhijmans** [comment]
Or you can use transparency instead of setting a missing value flag.

```
library(terra)
r <- rast(ncols=16, nrows=16, vals=0:255)
coltb <- data.frame(t(col2rgb(rainbow(256), alpha=TRUE)))
coltb$alpha[1] <- 0
coltab(r) <- coltb
rr <- writeRaster(r, "testr.png", overwrite=TRUE, NAflag=NA, datatype="INT1U")
plot(rr)
```

**Comment by rhijmans** [comment]
It is also possible to write the colors as an attribute table 

```
library(terra)
r <- rast(ncols=16, nrows=16, vals=0:255)
coltb <- data.frame(t(col2rgb(rainbow(256), alpha=TRUE)))
levels(r) <- data.frame(ID=0:255, coltb)
r[120]=NA
rr <- writeRaster(r, "testr.png", overwrite=TRUE, NAflag=999, datatype="INT2U")
plot(rr, legend=FALSE)
``` 

With the commit I just made, you do not need to use `legend=FALSE` . 

More could be done to make this work more seamlessly.
