### ISSUE TITLE
Terra do not read netcdf properly (in comparison with raster)

### ISSUE THREAD

**Issue by BastienFR** [rspatial/terra#105]
I was hesitant between starting a new thread or continuing [this one](https://github.com/rspatial/terra/issues/94).  I decided to start a new thread as I think the situation is slightly different, sorry if it was the wrong choice.

I'm working with NOAA weather data which are in the netcdf format and I'm currently migrating my code from the raster to the terra package to harness terra's new power.  However, while managing some netcdf, multiple problems and differences from raster occurred.  I decided to post my finding here with a RE so it could be use to improve the package.  There no precise questions or requests in my post, apart from wondering if terra could behave a little more like raster in handling netcdf files.  Feel free to close this issue if you think it doesn't bring useful information.

Here are my observation:

Preparing the session:
```
library(raster)
library(terra)

the_ras <- paste(tempdir(), "/vwnd.10m.2015.nc", sep = "")

utils::download.file("ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/vwnd.10m.2015.nc",
                     the_ras, 
                     method = "auto", 
                     mode = "wb", 
                     cacheOK = TRUE, 
                     extra = getOption("download.file.extra"))
```

Reading the layers with both terra and raster

```
ras_terra <- rast(the_ras)
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: dimension #1 (nbnds) is not a Longitude/X dimension.
  Warning 1: dimension #0 (time) is not a Latitude/Y dimension.
  Warning message:
  skipped subdatasets (different geometry):
     time_bnds
  See 'describe_sds' for more info
 
ras_raster <- stack(the_ras)
  Loading required namespace: ncdf4
```
Notice the multiple warnings when reading with the terra package.  These warnings may not be a R problem as a quick google search points to gdal, qgis and python errors.  However, they return after constantly after when applying terra functions so it would be nice to have a way to silence them.

The first thing we can notice in the differences between raster and terra is the number of layers:

```
terra::nlyr(ras_terra)
  [1] 367
raster::nlayers(ras_raster)
  [1] 365
```
terra include the first two layers representing the coordinates, which is useless.  Raster handle this better.  This can be visualize with:

```
terra::plot(ras_terra[[1:4]])
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
```
![image](https://user-images.githubusercontent.com/10979480/100118492-e84d5200-2e43-11eb-951f-57b9a2032d3a.png)

```
raster::plot(ras_raster[[1:4]])
```
![image](https://user-images.githubusercontent.com/10979480/100118540-f1d6ba00-2e43-11eb-829e-9c333019773f.png)

On those plots, we can also see that the coordinates are wrong.  Actually, the way terra manage the projection and the coordinates is wrong:

```
terra::crs(ras_terra)
  [1] "GEOGCRS[\"unknown\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]],\n        ID[\"EPSG\",6326]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433],\n        ID[\"EPSG\",8901]],\n    CS[ellipsoidal,2],\n        AXIS[\"longitude\",east,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433,\n                ID[\"EPSG\",9122]]],\n        AXIS[\"latitude\",north,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433,\n                ID[\"EPSG\",9122]]]]"
terra::crs(ras_raster)
  CRS arguments:
   +proj=lcc +lat_0=50 +lon_0=-107 +lat_1=50 +lat_2=50 +x_0=5632642.22547 +y_0=4612545.65137 +datum=WGS84
   +units=m +no_defs 

terra::ext(ras_terra)
  SpatExtent : -180, 180, -90, 90 (xmin, xmax, ymin, ymax)
terra::ext(ras_raster)
  SpatExtent : -16231.4942528736, 11313351.4942529, -16231.5, 8976019.5 (xmin, xmax, ymin, ymax)
```

The layer names are also badly labelled but that is a known issue ([here](https://github.com/rspatial/terra/issues/80)):

```
head(names(ras_terra))
  [1] "vwnd.10m.2015" "vwnd.10m.2015" "vwn_1"         "vwn_2"         "vwn_3"         "vwn_4"        
head(names(ras_raster))
  [1] "X2015.01.01" "X2015.01.02" "X2015.01.03" "X2015.01.04" "X2015.01.05" "X2015.01.06"
```

Now, all this is a problem if we want to extract data from the raster, the terra raster not being properly localized in space:

```
library(sf)
  Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
coo <- data.frame(id = 1:3,
                   lon = c(7841172, 8088294, 8173747),
                   lat = c(4350968, 4663015, 4691137)) %>% 
   st_as_sf(coords = c("lon", "lat")) 

raster::extract(ras_raster[[1:4]], coo)
       X2015.01.01 X2015.01.02 X2015.01.03 X2015.01.04
  [1,]    5.768288   1.2576851   1.8956697   1.4743252
  [2,]    3.148170   0.6893257  -0.6072600  -1.3205967
  [3,]    3.930397   0.4510444  -0.7449553  -0.9954014

terra::extract(ras_terra[[1:4]], vect(coo))
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
       ID vwnd.10m.2015 vwnd.10m.2015 vwn_1 vwn_2
  [1,]  1           NaN           NaN   NaN   NaN
  [2,]  2           NaN           NaN   NaN   NaN
  [3,]  3           NaN           NaN   NaN   NaN
```

Now, because I really need the power of `terra::extract` and because I cannot use directly the output from `rast("my_netcdf_files.nc")`, I need to find a way to convert the `RasterStack` class to `SpatRaster`.  I've try `as` but it didn't work:

```
as(ras_raster, "SpatRaster")
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
  Warning 1: dimension #1 (nbnds) is not a Longitude/X dimension.
  Warning 1: dimension #0 (time) is not a Latitude/Y dimension.
  class       : SpatRaster 
  dimensions  : 277, 349, 367  (nrow, ncol, nlyr)
  resolution  : 1.031519, 0.6498195  (x, y)
  extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
  coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
  source(s)   : vwnd.10m.2015.nc:lat  
              vwnd.10m.2015.nc:lon  
              vwnd.10m.2015.nc:vwnd  (365 layers) 
  names       : vwnd.10m.2015, vwnd.10m.2015, vwn_1, vwn_2, vwn_3, vwn_4, ... 
  Warning message:
  skipped subdatasets (different geometry):
     time_bnds
  See 'describe_sds' for more info
```

I get a object similar to the one obtained from `rast` (2 layers to many and bad projection).  Therefore, the only way I manage to create a `SpatRaster` object with my netcdf files was to manually create it from the metadata obtained by reading it with the `raster` function.

```
base_ras <- rast(extent = terra::ext(ras_raster),
                  nrows = nrow(ras_terra),
                  ncols = ncol(ras_terra),
                  nlyrs=nlyr(ras_terra)-2,
                  crs = terra::crs(ras_raster))
 
terra::values(base_ras) <- terra::values(ras_terra[[3:nlyr(ras_terra)]])
  Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
 
names(base_ras) <- names(ras_raster)
```

This way around works for me but it is not 100% independant of the raster package.  Ideally, the terra package would handle the netcdf files the same way.

**Comment by rhijmans** [comment]
Thank you, this is very timely, as I am working on improving the ncdf handling this week. Your file adds some other interesting twists that I will address. I will update my answer over the coming days. For now, with this file you would need to specificy the variable to get at what you are after. 

```
library(terra)
path <- tempdir()
f <- file.path(path, "vwnd.10m.2015.nc")
source <- "ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/vwnd.10m.2015.nc"
if (!file.exists(f)) {
  utils::download.file(source, f, method = "auto", mode = "wb")
}

r <- rast(f, "vwnd")
```
or 

```
s <- sds(f)
s[3]
```

**Comment by mdsumner** [comment]
A related note, these files contain "lonlat" arrays which are coordinates stored as data (instead of a regular transform). These can be plotted with the anglr package function `mesh_plot(var, coords = brick(lon, lat))` where 'var' is one of the raster layers, and lon,lat the first (2,1) arrays shown in the figure above. 

I've long wanted something in raster/terra to "know about" this kind of curvilinear coordinates, and I put all my helpers into angstroms and the anglr package (with long plans to somehow formalize those ideas better). The crux perspective is that of a "quad mesh", like the mesh3d type in rgl - which stores each cell corner uniquely with a mesh index. 

Finally, what is seen as 'curvilinear' is simply sometimes a map projection with untransformed lonlat arrays, but that's not always the case.

**Comment by rhijmans** [comment]
Mike, I am interested in what you propose. Maybe file a separate ticket to avoid that it gets lost?

**Comment by fabeit** [comment]
I also have gotten constant crashes when working with large files with 2k-3k levels at 2 degrees resolution, which is not huge by any mean and I have 32GB of ram. So I had to use writetodisk=TRUE when working with this rasterbrick in a loop. Eventually I ended up using directly ncdf4 library.

**Comment by rhijmans** [comment]
There is not much I can do without a more concrete example (file and code). `RasterBrick` is a class of the raster package, not `terra`
