### ISSUE TITLE
focal3D is not computing correct values

### ISSUE THREAD

**Issue by flaviomoc** [rspatial/terra#1057]
Dear Robert,

When applying the focal3D function, I noticed that the values on the right end (east side) of the raster are lower than they should be. Also, when using na.policy = "omit", it is returning an error even though there are no NAs in the raster.

I would appreciate it if you could help.

Here is an example code:
```
r <- terra::rast(ncol = 10, nrow = 10, nlyr = 11)
values(r) <- 1:ncell(r)

test <- terra::focal3D(r, c(3, 3, nlyr(r)), function(x) {
  min(x, na.rm = TRUE)
}, na.policy = "all")

plot(test)

test <- terra::focal3D(r, c(3, 3, nlyr(r)), function(x) {
  min(x, na.rm = TRUE)
}, na.policy = "omit")
# Error: [writeValues] incorrect number of values (too few) for writing
```

**Comment by rhijmans** [comment]
I understand why you think it is wrong but the values on the right side are correct, I think. Your data are global lon/lat, so you need to consider that the right-most column is adjacent to the left-most column. So the low values in the fist column affects to results.  This is not the case with any other crs.   

```
r <- terra::rast(ncol = 10, nrow = 10, nlyr = 11, crs="local")
values(r) <- 1:ncell(r)
test <- terra::focal3D(r, c(3, 3, nlyr(r)), mean, na.rm=TRUE)
```

But you were of course right that the `na.policy` argument did not work and thank you for reporting that. This now works:

```
test <- terra::focal3D(r, c(3, 3, nlyr(r)), fun=min, na.rm = TRUE, na.policy = "omit")
```

**Comment by rhijmans** [comment]
Fixed. Thanks again!
