### ISSUE TITLE
Hyphen in file or layer name causes where and query to fail

### ISSUE THREAD

**Issue by pricer-landcare** [rspatial/terra#1058]
R 4.2.2
Terra 1.7.3

I have a shapefile with hyphens in the name that I cannot query either with vect or query. 

prm.shp.reg <- r"[O:\BaseData\NZ\Boundaries\Loc_body\Region\StatsNZ_v20210209\regional-council-2020-generalised.shp]"
vct.regc <- terra::vect(x = prm.shp.reg, proxy = T)
vct.regc.gis <- terra::query(x = vct.regc, where = "REGC2020_1 = 'Gisborne Region'")

**_Error: [vect] Query failed
In addition: Warning message:
SQL Expression Parsing Error: syntax error, unexpected '-', expecting end of string. Occurred around :
SELECT * FROM regional-council-2020-generalised WHERE REGC2020
                      ^ (GDAL error 1)_** 

 vct.regc <- terra::vect(x = prm.shp.reg, query = "SELECT * FROM regional-council-2020-generalised WHERE REGC2020_1 = 'Gisborne Region'")
### **Error: [vect] Query failed
In addition: Warning message:
SQL Expression Parsing Error: syntax error, unexpected '-', expecting end of string. Occurred around :
SELECT * FROM regional-council-2020-generalised WHERE REGC2020
                      ^ (GDAL error 1)** 

> vct.regc <- terra::vect(x = prm.shp.reg, query = "SELECT * FROM [regional-council-2020-generalised] WHERE REGC2020_1 = 'Gisborne Region'")
Error: [vect] Query failed
In addition: Warning message:
SQL Expression Parsing Error: syntax error, unexpected $undefined, expecting string or identifier. Occurred around :
SELECT * FROM [regional-council-2020-generalised] WHER
              ^ (GDAL error 1) 

 vct.regc <- terra::vect(x = prm.shp.reg, query = "SELECT * FROM [regional-council-2020-generalised] WHERE REGC2020_1 = 'Gisborne Region'")
etc etc etc... tried all variabts of name quoting I can think of []{}()!!``|| without any luck

**Comment by rhijmans** [comment]
Thanks for reporting this. I believe this works now.

Example data 

```
library(terra)
v <- vect(system.file("ex/lux.shp", package="terra"))
f <- "regional-council-2020-generalised.shp"
writeVector(v, f)

vr <- terra::vect(f, proxy = TRUE)
x <- terra::query(x = vr, where = "NAME_1 = 'Diekirch'")

# you can also do
y <- vect(f, query="SELECT * FROM \"regional-council-2020-generalised\" WHERE NAME_1 = 'Diekirch'")
```
