### ISSUE TITLE
NAvalue implemented?

### ISSUE THREAD

**Issue by pbaylis** [rspatial/terra#106]
Great package! Has NAvalue been implemented yet? It [shows up](https://github.com/rspatial/terra/search?q=NAvalue) in some of the C++ code but I'm unable to get it to work in R.

```
r <- rast(ncol=10, nrow=10, xmin=-150, xmax=-80, ymin=20, ymax=60)

terra::NAvalue(r) <- -99
# Error: 'NAvalue<-' is not an exported object from 'namespace:terra'
```

Apologies if I'm just missing it -- I also tried `raster::NAvalue` but that threw an error as well.

**Comment by rhijmans** [comment]
Not there yet. Coming soon.

**Comment by rhijmans** [comment]
This is now implemented in terra as `NAflag`

**Comment by pbaylis** [comment]
Phenomenal, thank you!
