### ISSUE TITLE
Desaturation RGB Image

### ISSUE THREAD

**Issue by dominicroye** [rspatial/terra#1060]
I just found the colorize function in the terra package, and I was trying to desaturate an RGB image. 

Until now, I used to apply a custom function with app(). But it is even with parallel slow, so I wondered how to change the saturation with colorize. 

```
saturation <- function(rgb, s = .5){
  
  hsl <- plotwidgets::rgb2hsl(as.matrix(rgb))
  hsl[2, ] <- s

  rgb_new <- as.vector(t(plotwidgets::hsl2rgb(hsl)))
  
  return(rgb_new)
  
}
```

I finally tried the following:

```
library(terra)

r <- rast(system.file("ex/logo.tif", package="terra"))   

rh <- colorize(r, to = "hsl")
rh[[2]] <- rh[[2]]*0.1
rh

colorize(rh, to = "rgb")
Error: [] input color scheme should be one of 'hsv', 'hsi' or 'hsl'
```
Unfortunately, when I convert the hsl back to RGB, I get an error about the color scheme. How should I proceed? 

Thanks!!

**Comment by vorpalvorpal** [comment]
The need to use `set.RGB` in between the two colorize steps is not documented in the help file for `colorize` which just says you can use "rgb" as the `to` argument for `colorize`. I was completely stuck trying to do the same thing until I found this issue.
