### ISSUE TITLE
Click function gives shifted (relatively to the visible plot) coordinates

### ISSUE THREAD

**Issue by sergeikharchenko** [rspatial/terra#1063]
Hi!

I have tried to get approximate border of my interest polygons by clicking the border above my raster.
Unfortunately, function click always gives me shifted position of points and lines.

Reproducible example:
```
library(terra)
elev_rast <- rast(system.file("ex/elev.tif", package = "terra"))
plot(elev_rast)
c1 <- click(n = 4, type = "l")
```
I try to reproduce the line of any valley on the elevation raster.
![image](https://user-images.githubusercontent.com/59537139/224925208-8478e901-53a7-451e-920b-a9f0dfd575ac.png)

But the real positions of objects are always shifted orthogonally (?).

**Comment by sergeikharchenko** [comment]
Oh, I'm sorry. I didn't think I should look the **unsolved** problem description in the list of **closed** issues.
https://github.com/rspatial/terra/issues/1046

**Comment by rhijmans** [comment]
I did not close it, but that was a reasonable thing to do since it is a bug in Rstudio: https://github.com/rstudio/rstudio/issues/12682 , not in terra

**Comment by rhijmans** [comment]
There is a workaround suggested [here](https://github.com/rstudio/rstudio/issues/12682):  Set "Display Setting -> Scale -> 100%"
That does not help me much as that makes the fonts too small for me to read.

**Comment by aloboa** [comment]
I just found this problem (I rarely use click()).
Unfortunately, the RStudio ticket is closed! 
The trick of using a x11() works on linux. 
As there is little hope that this will be fixed in RStudio, I suggest the issue be prominently stated on the click() man page.
Even a warning message could be issued by click() itself. Many people are likely to get wrong values, this problem can be easily overlooked.

**Comment by rhijmans** [comment]
I cannot fix this, but I have added a once per session warning that is triggered when using `draw`, `sel` or `click` in RStudio.

```
Warning message:
#['click', 'draw', and 'sel' may not work properly
#with the default RStudio plotting window. See ?click] 
```
