### ISSUE TITLE
ascii file exported by `writeRaster` may not be standard

### ISSUE THREAD

**Issue by shy86** [rspatial/terra#1068]
I use `resample` to interpolate the tif file and output it as an ascii file. The result produced using the `terra` package seems to have an extra space at the beginning, and this causes the file not to be recognized correctly by some applications (e.g. anusplin). However, using the `raster` package can export correct file for the same process.

However，when I use the `raster` package for interpolation and then use terra's `writeraster`, the output file is fine. So it is not the `writeraster` function causing the error, but I am not sure exactly why.

Result by `raster` package:
![image](https://user-images.githubusercontent.com/72924309/226529108-b9cfdf66-c8a9-4e91-8948-1edc43049040.png)
Result by `terra` package:
![image](https://user-images.githubusercontent.com/72924309/226529155-0e434371-7293-4ad8-a4e6-df266ead1d78.png)

**Comment by rhijmans** [comment]
It seems to me that that is a bug/feature of ANUSPLIN, but here is a simple workaround for "test.asc". 

```
remove_ws <- function(f) {
   writeLines(trimws(readLines(f)), f)
}
remove_ws("test.asc")
```
