### ISSUE TITLE
about the extent of raster from row and colume

### ISSUE THREAD

**Issue by flvyhy** [rspatial/terra#1069]
Hello! When I get the extent from a raster by function ext(), I found I can't get extent from the row and colume of a raster like the things in raster package. Can you help me?

**Comment by rhijmans** [comment]
You can use argument "cells"

```
library(terra)
r <- rast()
ext(r, cellFromRowCol(r, c(50,53), c(50,53)))
#SpatExtent : -131, -127, 37, 41 (xmin, xmax, ymin, ymax)
``` 

or you can do 

```
x <- rast(r)
x[50:53, 50:53, drop=FALSE]  |> ext()
# SpatExtent : -131, -127, 37, 41 (xmin, xmax, ymin, ymax)
```

**Comment by mdsumner** [comment]
eek nice, I should write a guide to this - functions in terra vs equivalents in terra

**Comment by flvyhy** [comment]
Thank you very much! I got it.
