### ISSUE TITLE
ERROR: compilation failed for package 'terra'

### ISSUE THREAD

**Issue by max-poltora** [rspatial/terra#108]
Hello, I am trying to install terra package in R:
```
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.4.0          fansi_0.4.1       prettyunits_1.1.1 crayon_1.3.4      withr_2.3.0      
 [6] rprojroot_1.3-2   assertthat_0.2.1  R6_2.4.1          backports_1.1.10  cli_2.1.0        
[11] curl_4.3          remotes_2.2.0     callr_3.5.1       tools_3.6.1       glue_1.4.2       
[16] compiler_3.6.1    processx_3.4.4    pkgbuild_1.1.0 
```
But when I run `remotes::install_github("rspatial/terra")` it fails to install with following message:

> Downloading GitHub repo rspatial/terra@HEAD
> Installing 1 packages: raster
> trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.6/raster_3.4-5.zip'
> Content type 'application/zip' length 3380019 bytes (3.2 MB)
> downloaded 3.2 MB
> 
> package ‘raster’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
>         C:\Users\user\AppData\Local\Temp\Rtmpk7MUSZ\downloaded_packages
>   
>   
>   
>    checking for file 'C:\Users\user\AppData\Local\Temp\Rtmpk7MUSZ\remotes71c655d7865\rspatial-terra-374cbcf/DESCRIPTION' ...
>   
> √  checking for file 'C:\Users\user\AppData\Local\Temp\Rtmpk7MUSZ\remotes71c655d7865\rspatial-terra-374cbcf/DESCRIPTION'
> 
>   
>   
>   
> -  preparing 'terra': (2.7s)
>    checking DESCRIPTION meta-information ...
>   
>    checking DESCRIPTION meta-information ... 
>   
> √  checking DESCRIPTION meta-information
> -  cleaning src
> 
>   
>   
>   
> -  checking for LF line-endings in source and make files and shell scripts (1.4s)
> 
>   
>   
>   
> -  checking for empty or unneeded directories (384ms)
> 
>   
>   
>   
> -  building 'terra_0.9-12.tar.gz'
> 
>   
> Warning:
>   
>    Warning: file 'terra/cleanup' did not have execute permissions: corrected
> 
>   
>    Warning: file 'terra/configure' did not have execute permissions: corrected
> 
>   
>    
> 
> * installing *source* package 'terra' ...
> ** using staged installation
> 
>    **********************************************
>    WARNING: this package has a configure script
>          It probably needs manual configuration
>    **********************************************
> 
> 
> ** libs
> rm -f terra.dll RcppExports.o RcppFunctions.o RcppModule.o aggregate.o area.o arith.o buffer.o categories.o cellnumber.o crs.o distRaster.o distance.o extent.o extract.o file_utils.o focal.o gdal_info.o gdalio.o geos_methods.o math_utils.o memory.o modal.o mosaic.o moving.o ncdf_util.o pointInPolygon.o polygonize.o ram.o raster_coerce.o raster_methods.o raster_stats.o rasterize.o read.o read_gdal.o read_ogr.o reclassify.o rectify.o resample.o sample.o sources.o spatDataframe.o spatOptions.o spatRaster.o spatVector.o string_utils.o terrain.o time.o vecmathfun.o vector_methods.o warp.o write.o write_gdal.o write_ogr.o
> mkdir -p ../inst
> "C:/R/R-36~1.1/bin/x64/Rscript.exe" --vanilla "../tools/winlibs.R" 3.0.4
> cp -r ../windows/gdal3-3.0.4/share/gdal ../inst/
> cp -r ../windows/gdal3-3.0.4/share/proj ../inst/
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppFunctions.cpp -o RcppFunctions.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppModule.cpp -o RcppModule.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c aggregate.cpp -o aggregate.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c area.cpp -o area.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c arith.cpp -o arith.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c buffer.cpp -o buffer.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c categories.cpp -o categories.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c cellnumber.cpp -o cellnumber.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c crs.cpp -o crs.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c distRaster.cpp -o distRaster.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c distance.cpp -o distance.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c extent.cpp -o extent.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c extract.cpp -o extract.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c file_utils.cpp -o file_utils.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c focal.cpp -o focal.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_info.cpp -o gdal_info.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdalio.cpp -o gdalio.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c geos_methods.cpp -o geos_methods.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c math_utils.cpp -o math_utils.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c memory.cpp -o memory.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c modal.cpp -o modal.o
> c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-36~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -I"C:/R/R-3.6.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c mosaic.cpp -o mosaic.o
> mosaic.cpp: In function 'std::vector<double> mean2d(const std::vector<std::vector<double> >&)':
> mosaic.cpp:13:22: error: 'isnan' was not declared in this scope
>     if (!isnan(x[i][j])) {
>                       ^
> mosaic.cpp:13:22: note: suggested alternative:
> In file included from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/random:38:0,
>                  from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/bits/stl_algo.h:66,
>                  from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/algorithm:62,
>                  from spatBase.h:19,
>                  from spatDataframe.h:22,
>                  from spatVector.h:19,
>                  from spatRaster.h:20,
>                  from spatRasterMultiple.h:18,
>                  from mosaic.cpp:1:
> C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/cmath:632:5: note:   'std::isnan'
>      isnan(_Tp __x)
>      ^
> make: *** [C:/R/R-36~1.1/etc/x64/Makeconf:215: mosaic.o] Error 1
> ERROR: compilation failed for package 'terra'
> * removing 'C:/R/R-3.6.1/library/terra'
> Error: Failed to install 'terra' from GitHub:
>   (converted from warning) installation of package ‘C:/Users/user/AppData/Local/Temp/Rtmpk7MUSZ/file71c57f53e1c/terra_0.9-12.tar.gz’ had non-zero exit status

What do I miss?

**Comment by rhijmans** [comment]
Should be fixed now.

**Comment by max-poltora** [comment]
@rhijmans, thank you, Robert! It works now!

**Comment by rhijmans** [comment]
For the record, this error slipped through because it only occurs with R version < 4  (you are using version 3.6.1)
