### ISSUE TITLE
Option to not snug axes around map?

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1080]
[enhancement, only if easy to implement]

It is great that axes are now drawn snugly around the maps, but sometimes the user may prefer (for uniformity or for reproducing previous scripts) to have the option for a map to fill the entire plotting region as it used to do. Take e.g. the following script:
```
library(geodata)
wrld <- world(path = tempdir())
wrld <- merge(wrld, country_codes(), by.x = "GID_0", by.y = "ISO3")
par(mfrow = c(4, 2))
for (i in unique(wrld$continent)) {
  plot(subset(wrld, wrld$continent == i), main = i)
}
```
With previous versions of terra, we got all plots in the same size:

![image](https://user-images.githubusercontent.com/12085508/227946717-7a8afe73-1cf5-41a4-af2d-d38d7cc5e8a7.png)

...whereas now we get the same plots in disparate sizes:

![image](https://user-images.githubusercontent.com/12085508/227929770-1d33e520-d6ef-4ca5-8908-a3e265e2dd96.png)

If it's not a hassle, would it be possible to reproduce older behaviour when this is desired? Cheers!

**Comment by rhijmans** [comment]
You can now achieve that with `plot(x, clip=FALSE)`
