### ISSUE TITLE
`nearby` crashes R if `k = 0` or `distance = 0`

### ISSUE THREAD

**Issue by CeresBarros** [rspatial/terra#1082]
Hi `terra` developers,

I wanted to report something that is not exactly a bug, but just unexpected behaviour - at least for me.

When `nearby(..., k =0)` or `nearby(..., distance = 0)` R crashes with a "fatal error" message. 
Although it is logical that `k`/`distance` should be > 0, I would not have expected R to crash completely. The crashing made it hard for me to identify the source of the problem, because the `nearby` call was being run in parallel and `k` was being estimated internally (and the estimation didn't always result in 0).

So I was wondering if a check could be put in place that would throw an error when the user passes a 0 to `k` or `distance`?

Thanks!

Here's a reprex:
```
library(terra)
ras <- matrix(1:25, nrow=5, ncol=5)
ras <- rast(ras)

points <- as.points(ras)
points$ID <- 1:length(points)

focalPoint <- points[13,]
ngbPoints <- points[c(1:12,14:25)]

nearby(focalPoint, ngbPoints, k = 0)
nearby(focalPoint, ngbPoints, distance = 0)
```

and my `sessionInfo`:
```
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.7-3

loaded via a namespace (and not attached):
[1] compiler_4.2.2   tools_4.2.2      Rcpp_1.0.9       codetools_0.2-18
```

**Comment by rhijmans** [comment]
Thanks, fixed now. terra should, of course, never make R crash!
