### ISSUE TITLE
Issues with installing terra : 

### ISSUE THREAD

**Issue by alexyr23** [rspatial/terra#1083]
Hi everyone, 

In order to install other spatial packages, I needed to install a more recent version of terra and that's where I got stuck. 

install.packages("terra")

At first, everything seems fine and the installation is running, but suddently the console returns : 
checking GDAL: /nix/store/llvw2hy84rcqcnxq752xgk6rl10pr2qk-gdal-3.6.2/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.6.2
checking for proj.h... no
checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package 'terra'
* removing '/home/rosaa-ext/R/x86_64-pc-linux-gnu-library/4.2/terra'

I can't find any solution that is working anywhere. 
Do you know what can cause this problem ? 

Thank you

**Comment by rhijmans** [comment]
What is the operating system you are using?

**Comment by alexyr23** [comment]
I'm using a computing cluster that operates on linux

**Comment by rhijmans** [comment]
You probably need to specify the location of the proj lib. Perhaps something like tis

```
install.packages("terra", type = "source", configure.args = "--with-proj-lib= ______ /lib/")
```

**Comment by alexyr23** [comment]
I tried   
install.packages("terra", type = "source", configure.args = "--with-proj-lib= /nix/store/3p82vlwj4x2laizwm7kmkwwhmq1ybkyc-user-environment/lib/")
And sf package installation also doesn't work

**Comment by rhijmans** [comment]
Sorry I cannot help more. It is very difficult to troubleshoot this. But I would search for "sf" install Q and A because there is more of that online.
