### ISSUE TITLE
coerce 'retro' to FALSE if map units are not degrees

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1085]
The `retro` argument for `pax` (within `terra::plot`) is really cool, but it should probably be ignored (with a warning or a message) if the coordinates are not actually in degrees.
```
v <- vect(system.file("ex/lux.shp", package="terra"))
plot(project(v, "+proj=laea"), pax = list(retro = TRUE))
```
The axes should probably not show coordinates like 5380000ºN  :)

**Comment by rhijmans** [comment]
Thanks. Your example now ignores the "retro=TRUE" with a warning: 

```
Warning message:
[plot] 'retro' labels can only be used with lonlat data 
```
