### ISSUE TITLE
keep 'grid' inside ploting region

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1086]
When plotting a map with `grid=TRUE`, the grid lines extend outside the plotting region, sometimes to the north and sometimes to the east, which makes the maps look weird:

```
v <- vect(system.file("ex/lux.shp", package="terra"))
plot(v, grid = TRUE)
v1 <- v[1]
plot(v1, grid = TRUE)
```
This happens with raster maps as well. Could the grid lines be cut to fit within the map?
Cheers!

**Comment by rhijmans** [comment]
Thank you very much for reporting this. Fixed now.
