### ISSUE TITLE
focalMat() example returns 1 by 1 Matrix

### ISSUE THREAD

**Issue by MarkusZehner** [rspatial/terra#109]
Hello!

Im while adjusting scripts to use terra instead of Raster i've come across the focal function: 

Running 
`r <- rast(ncols=36, nrows=18, xmn=0)`
`gf <- focalMat(r, 2, "Gauss")`

from the Documentation returns a 1 by 1 Matrix with weight 1.

`gf`
 `    [,1]`
`[1,]    1`

Using a quite large filter
`r <- rast(ncols=71, nrows=71, xmn=0)`
`gf <- focalMat(r, 8, "Gauss")`

returns a 19 by 19 Matrix.

Is this intended? My understanding from the documentation was that the window size is defined by the raster, so i'd expect a window of 36 by 18, 71 by 71. Have i missed something?

Also as mentioned in #88 the Session terminates when running filters with large window sizes, which do work with the raster package. 

Thanks!

**Comment by rhijmans** [comment]
Thank you, I think the focalMat problem has been fixed. I will try to get to https://github.com/rspatial/terra/issues/88 later this week.
