### ISSUE TITLE
Extract function is returning a dataframe instead of Spatraster

### ISSUE THREAD

**Issue by tobioke** [rspatial/terra#1090]
Hi there,

I'm applying the "extract"  function in terra to some netcdf  files and the function is returning a dataframe instead of a Spatraster. I have restarted R several times to make sure there is no package conflict.  I was wondering if you are aware of this issue or if it is just peculiar to me. 

Also, the "crop" function does not clip to the shape of my study area when I used "ext(-141.0069, -123.7893, 60, 69.64794)" or when I used a shapefile . 

For both issues I have always included the namespaces.

A subset of my data is here if you are curious https://drive.google.com/drive/folders/1sdj6OMv2WQZk7BaTBjTZrZOJdA7VgQ0i

Thanks,

Tobi

**Comment by kadyb** [comment]
> I'm applying the "extract" function in terra to some netcdf files and the function is returning a dataframe instead of a Spatraster. I have restarted R several times to make sure there is no package conflict. I was wondering if you are aware of this issue or if it is just peculiar to me.

Are you sure you mean the `extract()` function? According to the documentation (https://rspatial.github.io/terra/reference/extract.html), it only returns `data.frame`, `matrix` or `SpatVector`. Maybe you should use zonal statistics for polygons with `as.raster = TRUE` argument (https://rspatial.github.io/terra/reference/zonal.html)?

**Comment by tobioke** [comment]
Thanks for getting back to me. 

That was my error. I was confusing `extract by mask ` usage in ArcGIS with `terra's `.  I found a solution to my problem. You may close this ticket.

**Comment by rhijmans** [comment]
@tobioke: for future reference, when reporting a bug please include a *minimal, self-contained, reproducible example* (that is code and data that ships with R or generated by R, that produce the error you are getting).
