### ISSUE TITLE
`plot()` uses times as main titles even when time is invariant

### ISSUE THREAD

**Issue by dramanica** [rspatial/terra#1091]
When plotting a raster, times are used as titles for different layers if a time axis is present. However,
it is possible (e.g. when subsetting sds objects) to obtain a SpatRaster with a time axis where all values
are identical (i.e not informative).

```
x <- rast(nrows=5, ncols=9, vals=1:45)
add(x) <- x*3
names(x) <-c("var1","var2")
time(x)<-c(2023,2023)
plot(x)
```

In that case, it would make sense to use the names of the layers as titles (as it would occur in the absence of a time axis):

`plot(x,main=names(x))`

The desired behaviour could be obtained by changing line 766-772 in plot_raster.R from

```
if (missing("main")) {
  tm <- time(x)
  if (!any(is.na(tm))) { #this only checks for NAs from a missing time axis
    main <- as.character(time(x))
  } else {
    main <- names(x)
  }
```
  
to

```
if (missing("main")) {
  tm <- time(x)
  if (all(!any(is.na(tm)),length(unique(tm))>1)) { #now we ensure that the time axis has multiple values
    main <- as.character(time(x))
  } else {
    main <- names(x)
  }
```

**Comment by rhijmans** [comment]
Thanks, this has now been implemented.
