### ISSUE TITLE
rast() function reads Red band values

### ISSUE THREAD

**Issue by JessciaH-D** [rspatial/terra#1092]
I was loading a landcover raster using rast() function, and after plotting it, I realized that the Red band values were extracted instead of the first column.
![attirbute](https://user-images.githubusercontent.com/115422929/229370840-015c3346-fd04-416f-80af-2dda9b13e015.PNG)
![band](https://user-images.githubusercontent.com/115422929/229370841-af6ba318-d32e-4d0d-befe-1794e8335a86.PNG)

 I am unsure if this issue is related to the raster being a change product, 92/2001 retrofit. 

Your help is appreciated. Thanks.

**Comment by rhijmans** [comment]
From what you show I infer that this is a raster with an attribute table.  You can pick another attribute, or remove the attributes. But "Modified_A" would be a more sensible default pick than "Red".

Without more information and/or the file I cannot help you much. When raising an issue, please show R output, not an image from another program. At minimum show what you get with you print/show the SpatRaster.

**Comment by JessciaH-D** [comment]
Thank you. I included the attribute table in case I could not describe the raster accurately, given that it differs slightly from the usual NLCD rasters. Below is what I did:                                                                                                                                                    
 lc_retro <- rast("Input/OH_change.tif")
 plot(lc_retro)
![Capture](https://user-images.githubusercontent.com/115422929/229405531-83bb64d0-10f9-48a5-a15c-b3914a79fa97.PNG)

**Comment by JessciaH-D** [comment]
lc_retro
class       : SpatRaster 
dimensions  : 14259, 12444, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : 922035, 1295355, 1786905, 2214675  (xmin, xmax, ymin, ymax)
coord. ref. : NAD_1983_Albers 
source      : OH_change.tif 
color table : 1 
categories  : Red, Green, Blue, Opacity, Modified_A, Land_Cover 
name        : Red 
min value   :   0 
max value   : 255 

summary(lc_retro)
   Red       
 0   :22776  
 255 :44020  
 192 :   50  
 209 : 1149  
 64  :  564  
 NA's:31785

**Comment by rhijmans** [comment]
you can remove the attributes with 

```
levels(lc_retro) <- NULL 
```

Or pick another one with 

```
activeCat(lc_retro) <- "Modified_A"
```
