### ISSUE TITLE
std::bad_alloc with subset in loop

### ISSUE THREAD

**Issue by jvandoninck** [rspatial/terra#1093]
Hi,

I'm running a set of terra functions (subset, mask) in a loop (tried lapply and for), on a computer with 8 GB RAM (but also running some other basic programs). 
At some point, the loop always runs into a std:bad_allow error, either in a `subset` or in a `mask` command. When running the function for a given spatRaster line-by-line, without the loop, I don't get any errors. So it's unfortunately difficult to provide a reproducible example.

Error message:
```
Error in x@ptr$subset(subset - 1, opt) : std::bad_alloc
```

I've tried setting parameters in `terraOptions`, e.g., `memfrac`, `memmin` and `steps`. This is one output of `terraOptions()` with low values for memory: 
```
memfrac   : 0.2
tempdir   : C:/Users/VandoninckJ/AppData/Local/Temp/Rtmpc376JK
datatype  : FLT4S
progress  : 0
todisk    : FALSE
verbose   : TRUE
tolerance : 0.1
memmin    : 0.1
```

Setting `terraOptions(verbose=TRUE)` results in this type of message before the error:
```
memory avail. : 1.72 GB
memory allow. : 0.34 GB
memory needed : 0.048 GB  (4 copies)
in memory     : true
block size    : 1116 rows
n blocks      : 50
pb            : 0
```

I checked `mem_info()` for the object `x` (11-layer spatRaster) on which `subset` is applied:
```
------------------------
Memory (GB) 
------------------------
check threshold : 1  (memmin)
available       : 1.64
allowed (20%)   : 0.33
needed (n=1)    : 0.13
------------------------
proc in memory  : TRUE
nr chunks       : 1
------------------------
```

Do you have any other suggestions on how to avoid this error?

**Comment by rhijmans** [comment]
That is difficult to debug without the data (and possibly the computer on which you encounter the problem). 
But it will probably go away if you write the values in the newly created SpatRasters to disk, with a filename argument in `mask`.

**Comment by rhijmans** [comment]
Closing because there is nothing I can do without more info.
