### ISSUE TITLE
Error: [rast] cannot open this file as a SpatRaster and GDAL error 4

### ISSUE THREAD

**Issue by millie-robson** [rspatial/terra#1097]
Hello,

I am trying to run a patch-based model using the RangeShifter platform in RStudio, but I am encountering a few errors when trying to load in my habitat patches. I believe these errors are related to the terra package.

The habitat patches were created in ArcMap and converted into raster format, then the attributes were exported as an asc. file. I am trying to run the following code to read in the habitat patches:

patches <- terra::rast(paste0(dirpath,'Inputs/Raster_MCE_Std2_10_largest_areas.asc'))

But I receive the following errors:
Error: [rast] cannot open this file as a SpatRaster: /Users/millierobson/Documents/UNI/MRes/RangeShifter/RangeShifter PM/Models/PM_Reintroduction/Inputs/Raster_MCE_Std2_10_largest_areas.asc
In addition: Warning message:
`/Users/millierobson/Documents/UNI/MRes/RangeShifter/RangeShifter PM/Models/PM_Reintroduction/Inputs/Raster_MCE_Std2_10_largest_areas.asc' not recognized as a supported file format. (GDAL error 4)

I have installed and loaded all the relevant packages (raster, terra, rgdal).

I do not understand the errors here and I was hoping someone may be able to help. I appreciate any help!

Many thanks.

**Comment by rhijmans** [comment]
Not much anyone can say without having the file. Instead of using an ascii file you may try a GeoTiff. Also, this type of question is better asked on [stackoverflow.com](https://stackoverflow.com). This site is for bugs and feature requests.
