### ISSUE TITLE
Error associated with resample threads option 

### ISSUE THREAD

**Issue by amegbor** [rspatial/terra#1101]
Hello,

I am using resample function and when I specify the threads=T option I get an error message. The message reads

"Errror: [write] unknown options(s): threads"

On my office PC the code works fine, however, I need more computing space due to the size of my data. Any idea what might be wrong?

**Comment by rhijmans** [comment]
That suggests you are using a very old version or terra that does not have this argument.

**Comment by amegbor** [comment]
> That suggests you are using a very old version or terra that does not have this argument.

Thanks, Robert. I am surprised though given I installed it from cran. I am reinstalling the package again. I will close this once I am able to confirm I have the latest version and the threads option works

**Comment by amegbor** [comment]
I have the latest versions now and the option works. Thank you.
