### ISSUE TITLE
plot() ignores 'colNA' when 'alpha' is defined

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1102]
When plotting a raster map, the 'colNA' argument works fine until you add a value for 'alpha':
```
r <- rast(system.file("ex/elev.tif", package = "terra"))
plot(r, colNA = "blue")  # OK
plot(r, colNA = "blue", alpha = 0.6)  # NA pixels no longer blue
```
I'm using terra version 1.7.23. Tried on both Windows 10 Home and Linux Mint Cinnamon 21.1.
Cheers!

**Comment by rhijmans** [comment]
Thank you for this --- and keep them coming, please. Fixed.
