### ISSUE TITLE
Error while trying to load terra when installed in a conda environment via mamba

### ISSUE THREAD

**Issue by gonzarizzo** [rspatial/terra#1104]
Hello,

I am traying to load terra within R, after installing it via mamba using conda-forge channel.

The installation succeed but when tryin to load terra I get the following error.

```
> library(terra)
Error: package or namespace load failed for ‘terra’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/grizzo/miniconda3/envs/mexico/lib/R/library/terra/libs/terra.so':
  libproj.so.15: cannot open shared object file: No such file or directory
```

Any suggestion on how to fix it would be greatly appreciated!

**Comment by rhijmans** [comment]
I have no idea. I see that you have also asked this [here](https://stackoverflow.com/questions/75968123/error-loading-r-package-within-conda-environment-libproj-so-15-cannot-open-sha). That is probably a better place to ask. Otherwise, ask the conda/mamba people?
