### ISSUE TITLE
Error in (function (classes, fdef, mtable)  :  unable to find an inherited method for function ‘extract’ for signature ‘"SpatRaster", "SpatialPointsDataFrame"’

### ISSUE THREAD

**Issue by gayensubrata** [rspatial/terra#1105]
I suppose to extract Bio-climatic variable from the DEM file using this codes:
library(tidyverse)
library(terra)
library(sf)
library(sp)
library(rgdal)
library(raster)
x = read.csv("D:/16. FINAL SPECIES LIST OF DDBR_THESIS/MORPHO_coodinates/Co_ABRAXAS_VAR.csv", header = T)
head(x)
dem = rast("D:/2. GIS/LETM_GIS_ZSI/GIS_ZSI/Dem resample_Himalaya/dem_Resample1.tif")
plot(dem)
plot(env_var)

# 
is.na(x)

geo_cordinates = x %>% drop_na()
geo_cordinates$species = 1
head(geo_cordinates)
# 
coordinates(geo_cordinates) = ~ lon+lat
#define crs coordinates
crs.geo = CRS("+proj=longlat +epsg:4326")
proj4string(geo_cordinates) = crs.geo

points(geo_cordinates)

## I am getting error using this function
extract(dem, geo_cordinates)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘extract’ for signature ‘"SpatRaster", "SpatialPointsDataFrame"’

Thank you.

**Comment by rhijmans** [comment]
The error message is very clear. If you do not understand it, then please ask your question on an appropriate forum such as stackoverflow.com. This site is for bug reports and feature requests. You can do

```
library(terra)
x = read.csv("D:/16. FINAL SPECIES LIST OF DDBR_THESIS/MORPHO_coodinates/Co_ABRAXAS_VAR.csv", header = T)
dem = rast("D:/2. GIS/LETM_GIS_ZSI/GIS_ZSI/Dem resample_Himalaya/dem_Resample1.tif")

xy <- na.omit(x[, c("lon", "lat")])
e <- extract(dem, xy)
```
