### ISSUE TITLE
Typo in dependency checking

### ISSUE THREAD

**Issue by Shu-Wan** [rspatial/terra#1106]
A simple typo found during installation:

"fur" -> "for"

https://github.com/rspatial/terra/blob/9383cec33fc197b926559b7ea6c9af43d3aaea75/configure.ac#L286

**Comment by rhijmans** [comment]
I copy these from "sf", perhaps @rsbivand can fix it there

**Comment by rsbivand** [comment]
Probably @edzer, no write access to the `sf` repo.
