### ISSUE TITLE
mosaic potentially not combining spatRasters

### ISSUE THREAD

**Issue by CCheCastaldo** [rspatial/terra#1107]
I can't tell if this is a bug or not or just me being an idiot. I am trying to mosaic two spatRasters together. They have identical extents, the same origin, and same resolution. 

<img width="1264" alt="Screen Shot 2023-04-08 at 11 31 40 PM" src="https://user-images.githubusercontent.com/14003444/230752686-308b5f87-78ac-4555-bb2a-c114510d9066.png">

They are stored in a list (scene_list). Here are the two scenes and their mosaic computed using: `terra::mosaic(scene_list[[1]], scene_list[[2]])`

<img width="1568" alt="Screen Shot 2023-04-08 at 11 21 36 PM" src="https://user-images.githubusercontent.com/14003444/230752442-1d01cd07-7bc5-4563-a15d-bd59c57e712a.png">

and again reversing the order of the scenes in the mosaic function: `terra::mosaic(scene_list[[2]], scene_list[[1]])`

<img width="1531" alt="Screen Shot 2023-04-08 at 11 21 20 PM" src="https://user-images.githubusercontent.com/14003444/230752433-9d2af2dc-2111-4b7b-ae2c-90a0a32b26eb.png">

I would like these two scenes to be combined, where the cell values are specified using the fun argument in mosaic (max, min. etc). It appears as though mosaic is ignoring the second scene entirely, or at least the portion of the second scene that is NA. There does not appear to be a na.rm argument for mosaic, and I get the same result using terra::sprc on the list first, terra::merge, or different fun arguments in mosaic (max, min, etc.). I am using terra 1.6-41 in R 4.2.0 on an Apple M1 Pro running Monterey. 

Many thanks....

**Comment by rhijmans** [comment]
I am under the impression that you misunderstand the purpose of mosaic, and that what you are looking for can be achieved with something like

```
mean(scene_list[[2]], scene_list[[1]]. na.rm=TRUE)
``` 

or with 

```
app(scene_list[[1:2]], mean, na.rm=TRUE)
```

**Comment by CCheCastaldo** [comment]
@rhijmans thank you so much - I should have realized that. Your solution worked perfectly.
