### ISSUE TITLE
Problem with terra::rasterize

### ISSUE THREAD

**Issue by sitscholl** [rspatial/terra#111]
Hi,

I came across an issue when using terra::rasterize compared to raster::rasterize. I have several SpatialPointsDataFrames and would like to transform them into rasters. This works fine using raster::rasterize, but, takes quite some time to calculate. I supposed this should work faster when using terra and therefore tried to use terra::rasterize. However, as a result I always get a raster with a constant value of 1 for all pixels. I created a simple reproducible example below using the meuse dataset.

It always gives me the same result, regardless of what I specify in the field argument. When I specify both the field and the fun arguments it gives me an error. Am I missing something or is this a bug?

```{r}
library(raster)
library(terra)

data("meuse")
coordinates(meuse) <- ~x+y
crs(meuse) <- crs('EPSG:4326')

meuse1 <- vect(meuse)


## Terra
r1 <- rast(meuse1)
r1 <- rasterize(x = meuse1, y = r1, field = 'copper')
r1 <- rasterize(x = meuse1, y = r1, field = 'copper', fun = "last")


## Raster
r2 <- raster(meuse)
r2 <- rasterize(x = meuse, y = r2, field = 'copper')
```

**Comment by rhijmans** [comment]
Thank you. Here is a workaround

```
library(raster)
library(terra)
data("meuse")
coordinates(meuse) <- ~x+y
crs(meuse) <- crs('EPSG:4326')
rr <- raster(meuse)
meuse1 <- vect(meuse)

rt <- rast(rr)
r1a <- rasterize(meuse1, rt, field = meuse1$copper, fun=sum)
r1b <- rasterize(meuse1, rt, field = meuse1$copper, fun="last")

## Raster
r2 <- rasterize(x = meuse, y = rr, field = 'copper')

all(values(r2) == values(r1b), na.rm=TRUE)
#[1] TRUE 
```

Meanwhile I have fixed this, made the treatment of points the same as that of lines and polygons, and improved the documentation. There is still some more work needed. Rasterization with lines/polygons is much faster than with raster, but with points it is probably the same --- the current version is more a prototype, and also as memory safe as the others. I will fix that too for the next release.
