### ISSUE TITLE
Title cropped when plotting RGB raster

### ISSUE THREAD

**Issue by jguelat** [rspatial/terra#1110]
Text titles are cropped when plotting RGB rasters. You can use the following code snippet to reproduce the bug.

```
library(terra)
b <- rast(system.file("ex/logo.tif", package = "terra"))
plot(b, main = "My nice map")
# The same happens when plotting the title separately
plot(b)
title("My nice map")

# No problem when plotting a single band
plot(b[[1]], main = "My nice map")
title("A great title")
```

Here's how the output looks like on my computer

![maptemp](https://user-images.githubusercontent.com/15686289/231416720-3bae6a01-d6a5-4ddd-b452-bd2cbcde562e.jpg)

```
> packageVersion("terra")
[1] ‘1.7.23’
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
```

**Comment by rhijmans** [comment]
That is by design. But you can change the margins like this:

```
plot(b, mar=c(1,1,3,1))
title("My nice map")
```

I have now added a few words about that to the help file.

**Comment by jguelat** [comment]
OK, thanks for the clarification and for the additional words in the help file!

A negative value for the "line" argument of the "title" function is also working:

`title("My nice maps", line = -2)`
