### ISSUE TITLE
focalMat: type="circle" makes square window

### ISSUE THREAD

**Issue by hagc** [rspatial/terra#1116]
Hi. 
I don't get a circle "moving window" with this:

`r <- rast(ncols=180, nrows=180, xmin=0)`
`focalMat(r, 5, "circle")`

But I get it with raster package:
`r <- raster::raster(ncols=180, nrows=180)`
`raster::focalWeight(r, 5, "circle")`

I'm facing the same issue with real data, with meters as the unit of crs (the example above is latlong).
I'm using terra version 1.7.23.
Thanks
Hugo

**Comment by rhijmans** [comment]
I do not see any difference:

```
library(terra)
library(raster)
r <- rast(ncols=180, nrows=180, xmin=0)
ter <- terra::focalMat(r, 5, "circle")
rst <- raster::focalWeight(raster(r), 5, "circle")

x <- rast(c(terra=rast(ter), raster=rast(rst)))
plot(x)
```

![window](https://user-images.githubusercontent.com/11481397/231912113-1aa28cfd-1597-4c73-9c69-ffa0dac88e76.png)

**Comment by hagc** [comment]
I found that focalMat changes when `terraOptions(todisk=TRUE)`, at least in my computer. Please try this

```
library(terra)
r <- rast(ncols=1800, nrows=1800, xmin=0)
ter1 <- terra::focalMat(r, 5, "circle")
terraOptions(todisk=TRUE)
ter2 <- terra::focalMat(r, 5, "circle")

plot( rast(c(todisk_FALSE=rast(ter1), todisk_TRUE=rast(ter2))) )

```


![image](https://user-images.githubusercontent.com/9258574/232025697-7846e6f6-e7a9-4da0-9a76-f5792fbb0250.png)

I tried in a different computer, which has terra version 1.5.21, and focalMat works well. So at the moment I don't know if the problem is the version of terra or something weird in my computer.

Hope this is useful
Hugo

**Comment by rhijmans** [comment]
Thank you very much for reporting this. Your example now works as it should.
