### ISSUE TITLE
$<- factor() gives "character"

### ISSUE THREAD

**Issue by mkschneider** [rspatial/terra#1117]
Thanks for the great package. I am updating skripts using raster and sf and notice that
v <- vect(system.file("ex/lux.shp", package="terra"))
v$ID_1 <- factor(LETTERS[1:12])
class(v$ID_1)
[1] "character"
The same with as.POSIXlt()
I use these formats often in spatial datasets as well.

**Comment by rhijmans** [comment]
Thank for catching this bug. It works again:

```
library(terra)
#terra 1.7.24
v <- vect(system.file("ex/lux.shp", package="terra"))
v$ID_1 <- factor(LETTERS[1:12])
class(v$ID_1)
#[1] "factor"
```
