### ISSUE TITLE
Feature request: for `SpatVector`, return `NULL` for non-existent column

### ISSUE THREAD

**Issue by dfriend21** [rspatial/terra#1118]
If you try to access a non-existent column on a `SpatVector` using `$`, an error is thrown. This differs from the default behavior of a `data.frame`, where `NULL` is returned. I've noticed this because I typically use `is.null(df$column)` to check if a column exists on a data frame, and therefore tried to use the same approach for a `SpatVector`. Personally, I think it'd be nice for the sake of consistency for a `SpatVector` to behave as a `data.frame` does in this case. However, there may be reasons to throw an error in this case rather than returning `NULL` - feel free to close this issue if this isn't how you want a `SpatVector` to behave.

``` r
library(terra)
#> terra 1.7.22

v <- vect(system.file("ex/lux.shp", package = "terra"))
v$not_a_column
#> Error: [$] not_a_column is not a variable name in x

v_df <- as.data.frame(v)
v_df$not_a_column
#> NULL
```

<sup>Created on 2023-04-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
> it'd be nice for the sake of consistency for a SpatVector to behave as a data.frame

Of course, that is the intent. But it is easy to overlook details like this. Thanks for pointing that out. 

I now get:

```
library(terra); v=vect(cbind(0,0)); v$id
#terra 1.7.25
vect(cbind(0,0))$id
#NULL
```
