### ISSUE TITLE
Rgui crashes when calling writeRaster with BMP format

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#112]
Rgui crashes on a call to writeRaster in BMP format:
```
> library(terra)
terra version 1.0.1
> mat <- matrix(c(0,0,0,1,1,1),ncol=3,byrow=TRUE)
> colnames(mat) <- c("X","Y","Z")
> test <- rast(mat,type="xyz")
>  writeRaster(test,"test.asc",overwrite=TRUE,wopt=list(filetype="AAIGrid"))  # works
>  writeRaster(test,"test.bmp",overwrite=TRUE,wopt=list(filetype="BMP"))  # crashes
```

**Comment by rhijmans** [comment]
Thanks. It appears that this is because of a format specific requirement that to write BMP one must supply a color table (not 100% sure). With the fix I made, you are forced to supply one; but I can also add one automatically if it is missing (gray scale?). Would that be helpful?

```
library(terra)
#terra version 1.0.1
r <- rast(ncol=3, nrow=2, vals=0:5)
x <- writeRaster(r, "test.bmp", overwrite=TRUE)
#Error: [writeRaster] For BMP the SpatRaster must have a color-table. See ?coltab
x <- writeRaster(c(r,r), "test.bmp", overwrite=TRUE)
#Error: [writeRaster] For BMP, the SpatRaster must have 1 or 3 layers (3 is not currently supported)
 
coltb <- data.frame(t(col2rgb(rainbow(6, end=.9), alpha=TRUE)))
coltb
#  red green blue alpha
#1 255     0    0   255
#2 235   255    0   255
#3   0   255   41   255
#4   0   194  255   255
#5  82     0  255   255
#6 255     0  153   255

coltab(r) <- coltb
plot(r)

x <- writeRaster(r, "test.bmp", overwrite=TRUE)
plot(x)
```

**Comment by rhijmans** [comment]
I implemented a default color table:

```
library(terra)
r <- rast(ncol=3, nrow=2, vals=seq(10,240, length.out=6))
x <- writeRaster(r, "test1.bmp", overwrite=TRUE)
plot(x)

#Setting the reverse color table to show that you can do this by hand
# and that you can also use "colors" not only RGB(A)
cols <- gray(seq(0, 1, length.out=255))
coltab(r) <- rev(cols)
plot(r)

y <- writeRaster(r, "test2.bmp", overwrite=TRUE)
```

**Comment by rhijmans** [comment]
Also note that the values for these files run from 0 to 255, and that terra used 255 as NA flag. If your data has values of 255 you can set the NAflag to another value --- perhaps outside the range `wopt=list(NAflag=300)` to have no NAs

**Comment by jldupouey** [comment]
Thanks to your explanation, I found another workaround. According to the BMP specifications, the color table is only required when the number of bits per pixel is higher than 8. Indeed, using the INT1U datatype works:

```
r <- rast(ncol=3, nrow=2, vals=seq(10,240, length.out=6))
x <- writeRaster(r, "test.bmp", overwrite=TRUE, wopt=list(filetype="BMP",datatype="INT1U"))  # works
```

However, I wondered what would happen when using the INT1U option with raster values above 255. That shouldn't be possible, should it? I tried:

```
r <- rast(ncol=3, nrow=2, vals=seq(-1e9,1e9, length.out=6))
x <- writeRaster(r, "test.bmp", overwrite=TRUE, wopt=list(filetype="BMP",datatype="INT1U"))
```

and it worked. Reading the test.bmp file gave the original values back:

```
> rast("test.bmp")
class       : SpatRaster 
dimensions  : 2, 3, 1  (nrow, ncol, nlyr)
resolution  : 120, 90  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
source      : test.bmp 
name        :  lyr.1 
min value   : -1e+09 
max value   :  1e+09
```

I wonder how that's possible.

**Comment by rhijmans** [comment]
Ay --- that is what I looked at first, but by mistake I used INT2U rather than INT1U. To write a color table with GDAL, you must use INT1U. And it turns out that GDAL adds the same gray scale color table as I did --- so I am now using the default. 
The min/max values you are seeing is false advertising. Try `values(x)`. I have fixed this now, to get:

 
library(terra)
r <- rast(ncol=3, nrow=2, vals=c(-100, -10, 0, 10, 100, 300))
x <- writeRaster(r, "testt.bmp", overwrite=TRUE, wopt=list(filetype="BMP",datatype="INT1U"))
values(x)
#     lyr.1
#[1,]   NaN
#[2,]   NaN
#[3,]     0
#[4,]    10
#[5,]   100
[#6,]   NaN

x
#class       : SpatRaster 
#dimensions  : 2, 3, 1  (nrow, ncol, nlyr)
#resolution  : 120, 90  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : testt.bmp 
#name        : lyr.1 
#min value   :     0 
#max value   :   100

**Comment by jldupouey** [comment]
Thanks for all that work! I am not sure the default values you selected are the most adequate. With these choices, by default, all raster values outside 0-255 will be silently replaced by NA values. Perhaps it would be more cautious to keep the values as they are in the raster to be written, using a float format for pixel values, but supplying a default color table? 

If you keep this default behaviour, it needs at least a strong warning for the users when pixel values are larger than one byte integer and cannot fit in `INT1U`.

**Comment by rhijmans** [comment]
With [GDAL](https://gdal.org/drivers/raster/bmp.html), you can only write unsigned bytes to a BMP file, either as single band or as three bands (RGB). I have not yet implemented the three band format.  Also GDAL will only write a color table for a band with byte values.  

I am thinking of giving a warning if the user explicitly set the datatype to something else than INT1U, but not if they are using the default FLT4S.
