### ISSUE TITLE
Error installing 'terra'

### ISSUE THREAD

**Issue by KingaHill** [rspatial/terra#1123]
Hello,
I am trying to install the latest version of terra and I am getting an error. 

remotes::install_github('rspatial/terra')
Downloading GitHub repo rspatial/terra@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\Kinga Hill\AppData\Local\Temp\RtmpqASygQ\remotes4fac24f51448\rspatial-terra-62a1632/DESCRIPTION' ... OK
* preparing 'terra':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'terra_1.7-27.tar.gz'
Installing package into ‘C:/Users/Kinga Hill/AppData/Local/R/cache/R/renv/library/cloudburst-3117b673/R-4.2/x86_64-w64-mingw32’
(as ‘lib’ is unspecified)
* installing *source* package 'terra' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
rm -f terra.dll RcppExports.o RcppFunctions.o RcppModule.o arith.o crs.o distRaster.o distance.o extract.o file_utils.o focal.o gcp.o gdal_algs.o gdal_multidimensional.o gdalio.o geodesic.o geos_methods.o geosphere.o math_utils.o mediancut.o memory.o movingWindow.o ncdf.o ram.o raster_methods.o raster_stats.o rasterize.o read.o read_gdal.o read_ogr.o sample.o sort.o spatBase.o spatDataframe.o spatFactor.o spatRaster.o spatRasterMultiple.o spatSources.o spatTime.o spatVector.o spatVector2.o string_utils.o vecmath.o vecmathse.o vector_methods.o write.o write_gdal.o write_ogr.o
cp -r "C:/Users/Kinga Hill/AppData/Local/renv/extsoft/share/gdal" ../inst/
cp -r "C:/Users/Kinga Hill/AppData/Local/renv/extsoft/share/proj" ../inst/
g++ -std=gnu++14  -I"C:/PROGRA~1/R/R-42~1.3/include" -DNDEBUG  -I'C:/Users/Kinga Hill/AppData/Local/R/cache/R/renv/library/cloudburst-3117b673/R-4.2/x86_64-w64-mingw32/Rcpp/include'   -I"C:/Users/Kinga Hill/AppData/Local/renv/extsoft/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++14  -I"C:/PROGRA~1/R/R-42~1.3/include" -DNDEBUG  -I'C:/Users/Kinga Hill/AppData/Local/R/cache/R/renv/library/cloudburst-3117b673/R-4.2/x86_64-w64-mingw32/Rcpp/include'   -I"C:/Users/Kinga Hill/AppData/Local/renv/extsoft/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppFunctions.cpp -o RcppFunctions.o
RcppFunctions.cpp: In function 'std::vector<std::__cxx11::basic_string<char> > getCRSname(std::string)':
RcppFunctions.cpp:113:9: warning: variable 'west' set but not used [-Wunused-but-set-variable]
  113 |  double west, south, east, north;
      |         ^~~~
RcppFunctions.cpp:113:15: warning: variable 'south' set but not used [-Wunused-but-set-variable]
  113 |  double west, south, east, north;
      |               ^~~~~
RcppFunctions.cpp:113:22: warning: variable 'east' set but not used [-Wunused-but-set-variable]
  113 |  double west, south, east, north;
      |                      ^~~~
RcppFunctions.cpp:113:28: warning: variable 'north' set but not used [-Wunused-but-set-variable]
  113 |  double west, south, east, north;
      |                            ^~~~~
g++ -std=gnu++14  -I"C:/PROGRA~1/R/R-42~1.3/include" -DNDEBUG  -I'C:/Users/Kinga Hill/AppData/Local/R/cache/R/renv/library/cloudburst-3117b673/R-4.2/x86_64-w64-mingw32/Rcpp/include'   -I"C:/Users/Kinga Hill/AppData/Local/renv/extsoft/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppModule.cpp -o RcppModule.o
g++ -std=gnu++14  -I"C:/PROGRA~1/R/R-42~1.3/include" -DNDEBUG  -I'C:/Users/Kinga Hill/AppData/Local/R/cache/R/renv/library/cloudburst-3117b673/R-4.2/x86_64-w64-mingw32/Rcpp/include'   -I"C:/Users/Kinga Hill/AppData/Local/renv/extsoft/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c arith.cpp -o arith.o
g++ -std=gnu++14  -I"C:/PROGRA~1/R/R-42~1.3/include" -DNDEBUG  -I'C:/Users/Kinga Hill/AppData/Local/R/cache/R/renv/library/cloudburst-3117b673/R-4.2/x86_64-w64-mingw32/Rcpp/include'   -I"C:/Users/Kinga Hill/AppData/Local/renv/extsoft/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c crs.cpp -o crs.o
crs.cpp: In member function 'SpatVector SpatVector::project(std::string, bool)':
crs.cpp:383:9: error: 'class OGRCoordinateTransformation' has no member named 'SetEmitErrors'
  383 |   poCT->SetEmitErrors(false);
      |         ^~~~~~~~~~~~~
make: *** [C:/PROGRA~1/R/R-42~1.3/etc/x64/Makeconf:260: crs.o] Error 1
ERROR: compilation failed for package 'terra'
* removing 'C:/Users/Kinga Hill/AppData/Local/R/cache/R/renv/library/cloudburst-3117b673/R-4.2/x86_64-w64-mingw32/terra'
Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In i.p(...) :
  installation of package ‘C:/Users/KINGAH~1/AppData/Local/Temp/RtmpqASygQ/file4fac3b2e31b5/terra_1.7-27.tar.gz’ had non-zero exit status

Any idea what the issue might be? 
I am using a Windows computer, My R version is 4.2.3 (2023-03-15 ucrt) -- "Shortstop Beagle" and I have RTools 4.2 installed
Thank you

**Comment by rhijmans** [comment]
I do not know. You see a lot of warnings that I do not get. I use Rtools 4.3. I see you are on windows but perhaps on some kind of cloud system? Either way, I would recommend getting the development version with 

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
```

**Comment by KingaHill** [comment]
Thank you so much for your answer. I will try the development version.

**Comment by rhijmans** [comment]
I assumed you wanted the development version since you were using 

```
remotes::install_github('rspatial/terra')
``` 

If you want the latest released version, you can use 

```
install.packages('terra')
```
