### ISSUE TITLE
A small typo with regress function

### ISSUE THREAD

**Issue by liushlcn** [rspatial/terra#1124]
A small typo in the script **[regress.R](https://github.com/rspatial/terra/blob/master/R/regress.R)** in line 125 `formula <- stas::as.formula(formula)`, which would bring error information _Error in loadNamespace(x)_ when x is a **SpatRaster** as below.

```r
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
x <- regress(s, s)
```
The right one should be **stats**.

**Comment by rhijmans** [comment]
Thanks! Fixed.
