### ISSUE TITLE
terra::t() does not accept "additional arguments for writing files as in writeRaster"

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#1125]
According to the help page, it seems like 
"additional arguments for writing files as in writeRaster"
would apply for both terra::t() and terra::trans()
but it actually applies to terra::trans() only:

```
> tr2 <- trans(r, file="test", filetype="GTiff", overwrite=TRUE)
> r <- rast(nrows=18, ncols=36)
> values(r) <- 1:ncell(r)
> tr1 <- t(r, file="test", filetype="GTiff", overwrite=TRUE)
Error in t(r, file = "test", filetype = "GTiff", overwrite = TRUE) : 
  unused arguments (file = "test", filetype = "GTiff", overwrite = TRUE)
> tr2 <- trans(r, file="test", filetype="GTiff", overwrite=TRUE)
>
```
Just a clarification in the help page would be enough.

**Comment by rhijmans** [comment]
If you look under "Usage" you can see that these arguments apply to `trans` and not to `t`. 

```
## S4 method for signature 'SpatRaster'
t(x)

## S4 method for signature 'SpatRaster'
trans(x, filename="", ...)
```

I understand that this can lead to confusion. But this is a very common situation in R help files. 
Whenever there are multiple functions documented in a single help file, it is likely that not all arguments apply to all functions.
