### ISSUE TITLE
`show<SpatVector>` with `object@ptr$source`  path too long for `basename()`

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#1126]
I ran into a case where a URL with long query string `object@ptr$source`  may be too long for `basename()`, which causes an error when calling the `show()` method (prevents the display of the CRS information)

Similarly very long local file names can cause a similar issue with e.g. `writeVector()`

``` r
library(terra)
#> terra 1.7.29
dsn <- "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/6/query?geometry=%7B%22rings%22%3A%5B%5B%5B-121.355%2C%2037.56%5D%2C%5B-121.355%2C%2037.555%5D%2C%5B-121.35%2C%2037.555%5D%2C%5B-121.35%2C%2037.56%5D%2C%5B-121.355%2C%2037.56%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPolygon&inSR=4326&spatialRel=esriSpatialRelIntersects&outSR=4326&f=geojson"
x <- vect(dsn)
x
#>  class       : SpatVector 
#>  geometry    : polygons 
#>  dimensions  : 1, 1  (geometries, attributes)
#>  extent      : -121.3766, -121.2023, 37.47325, 37.61852  (xmin, xmax, ymin, ymax)
#> Error in basename(object@ptr$source): path too long
```

```r
y <- writeVector(x, paste0(paste0(letters[1:1000], collapse = "-"), ".shp"))
#> Error in basename(filename): path too long
```

I don't find either of these to be a huge problem or work stoppage... but perhaps having some sort of fallback when `basename()` errors would be cleaner.

```
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  version  R version 4.2.2 (2022-10-31 ucrt)
#>  os       Windows 10 x64 (build 19044)
```

**Comment by rhijmans** [comment]
I could make a safe basename (at least for display) but I do not get the basename error on windows or linux. I do get 

```
y <- writeVector(x, paste0(paste0(letters[1:1000], collapse = "-"), ".shp"))
#Warning message:
#Destination buffer too small (GDAL error 1) 
```

**Comment by brownag** [comment]
> I could make a safe basename (at least for display) but I do not get the basename error on windows or linux. I do get
> 
> ```
> y <- writeVector(x, paste0(paste0(letters[1:1000], collapse = "-"), ".shp"))
> #Warning message:
> #Destination buffer too small (GDAL error 1) 
> ```

I am using GDAL 3.5.2 on windows when I get that error. I just figured I would point out the display issue primarily. I do not need file names that long

**Comment by brownag** [comment]
Also, on this _particular_ Windows machine registry entry `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` has value `0` and I do not have permissions to change it. 

If this is something you would rather not work around on terra end I understand.

**Comment by rhijmans** [comment]
I have added a work-around. Can you check it?

**Comment by brownag** [comment]
Thanks! I can check it soon; I do see a typo on show.R L11 and 13, I think: `lenght()` versus `length()`?

**Comment by rhijmans** [comment]
Thanks, I fixed the length misspelling.

**Comment by brownag** [comment]
Perfect, on the Windows machine in question I now get:

``` r
library(terra)
#> terra 1.7.30
dsn <- "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/6/query?geometry=%7B%22rings%22%3A%5B%5B%5B-121.355%2C%2037.56%5D%2C%5B-121.355%2C%2037.555%5D%2C%5B-121.35%2C%2037.555%5D%2C%5B-121.35%2C%2037.56%5D%2C%5B-121.355%2C%2037.56%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPolygon&inSR=4326&spatialRel=esriSpatialRelIntersects&outSR=4326&f=geojson"
x <- vect(dsn)
x
#>  class       : SpatVector 
#>  geometry    : polygons 
#>  dimensions  : 1, 1  (geometries, attributes)
#>  extent      : -121.3766, -121.2023, 37.47325, 37.61852  (xmin, xmax, ymin, ymax)
#>  source      : query?geometry=%7B%22rings%22%3A%5B%5B%5B-121.355%2C%2037.56%5D%2C%5B-121.355%2C%2037.555%5D%2C%5B-121.35%2C%2037.555%5D%2C%5B-121.35%2C%2037.56%5D%2C%5B-121.355%2C%2037.56%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPolygon&inSR=4326&spatialRel=esriSpatialRelIntersects&outSR=4326&f=geojson (OGRGeoJSON)
#>  coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#>  names       :         name
#>  type        :        <chr>
#>  values      : Ingram Creek
```

**Comment by brownag** [comment]
Here is an edge case I encountered when the data source name vector has length > 1

``` r
library(terra)
#> terra 1.7.30
a <- rast(matrix(runif(9), ncol=3))
b <- rast(matrix(runif(9), ncol=3))
d <- rast(matrix(runif(9), ncol=3))

a <- classify(a, cbind(0, 0.5, 1), others = 0)
b <- classify(b, cbind(0, 0.3, 1), others = 0)
d <- classify(d, cbind(0, 0.8, 1), others = 0)

r <- c(a, b, d)

r
#> class       : SpatRaster 
#> dimensions  : 3, 3, 3  (nrow, ncol, nlyr)
#> resolution  : 1, 1  (x, y)
#> extent      : 0, 3, 0, 3  (xmin, xmax, ymin, ymax)
#> coord. ref. :
#> Error in if (nchar(x) > 256) {: the condition has length > 1
```

**Comment by rhijmans** [comment]
Already fixed.

**Comment by kadyb** [comment]
By the way, it looks like there is an anniversary. This is most likely the 1000th fixed issue and you have made ~4000 commits in three years. So huge congratulations Robert to you and huge thanks for your awsome work!

![gif](https://user-images.githubusercontent.com/35004826/234985455-f95751f7-9250-45e3-813a-af821518f9a7.gif)

**Comment by rhijmans** [comment]
Thank you for all the help along the way.
