### ISSUE TITLE
Crop (an also when crop & mask) to the output file does not change the datatype 

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1128]
Hello,
Was there recently any change in crop to the file? 
I do have an MCD12Q2 EVI2 file that when loaded using` rast()` has a scale factor applied automatically. That is fine. 
The problem is when I do crop to file in one line. It saves the files with the original datatype ('INT2S') and I end up with all values being 0.
When I do it in two steps:  first `crop()` to variable and then the variable is saved using `writeRaster()` then it changes the datatype according to the values and everything is ok. 
I am using 1.7-24 dev version on Windows. 

Not long ago, everything was ok, and the output from one linear was ok! 
[MCD12Q2.061_EVI_Minimum_0_doy2015001_proj.zip](https://github.com/rspatial/terra/files/11296681/MCD12Q2.061_EVI_Minimum_0_doy2015001_proj.zip)

**Comment by rhijmans** [comment]
I do not see that. This is what I see:

```
library(terra)
#terra 1.7.30
f <- "MCD12Q2.061_EVI_Minimum_0_doy2015001_proj.tif"
r <- rast(f)
e <- ext(160000, 400000, 620000, 950000 )

minmax(crop(r, e))
#    MCD12Q2.061_EVI_Minimum_0_doy2015001_proj
#min                                    0.1200
#max                                    0.4518
 
x = crop(r, e, filename="test.tif", overwrite=TRUE)
minmax(x)
#    MCD12Q2.061_EVI_Minimum_0_doy2015001_proj
#min                                    0.1200
#max                                    0.4518
```

And while the input file has a scale and offset, the output does not. 

```
describe(f)[62]
#[1] "  Offset: 0,   Scale:0.0001"
```

I think that first a change was made such that crop maintains the data-type, and later an additional change, to not do that when there is a scale and offset (the alternative would have been to also write the scale and offset, but I find that too much complexity to be worth it).  So perhaps your version is in-between these two changes? Can you please try with the current CRAN or devel version?

**Comment by Rapsodia86** [comment]
Ok, I see the problem is due to the mask within the crop:
```
x = crop(r, xmask,mask=TRUE, filename="test.tif", overwrite=TRUE)
minmax(x)
#    MCD12Q2.061_EVI_Minimum_0_doy2015001_proj
#min                                         0
#max                                         0
 
x2 = crop(r, xmask,mask=TRUE)
minmax(x2)
#    MCD12Q2.061_EVI_Minimum_0_doy2015001_proj
#min                                    0.1200
#max                                    0.5029
```

**Comment by rhijmans** [comment]
Yes, that was it. This example now also works:

````
library(terra)
#terra 1.7.30
r = rast("MCD12Q2.061_EVI_Minimum_0_doy2015001_proj.tif")
m = matrix(c(11000, 488000, -105000, 11000, 1065000, 669000, 669000, 1065000), ncol=2)
v = vect(m, "polygons", crs=crs(r))
 
x = crop(r, v, mask=T, filename="test.tif", overwrite=TRUE)
minmax(x)
#    MCD12Q2.061_EVI_Minimum_0_doy2015001_proj
#min                                    0.1200
#max                                    0.5029
```

**Comment by Rapsodia86** [comment]
Thank you!
