### ISSUE TITLE
fresh install : unable to writeRaster by layer

### ISSUE THREAD

**Issue by arthurdegrandpre** [rspatial/terra#1130]
Hi,

I have been having trouble using writeRaster to create one .tif file for every layer of a stack over a fresh R installation. This could be done without any issues prior to the system update.
I have tried multiple methods, but there seems to be an issue in the call to GDAL.
I could write a function to loop through layers but I feel like this should be adressed.

With different calls of writeRaster I have managed to generate a few different error messages:

Error in if (filename == "") { : the condition has length > 1

Error in .startGDALwriting(x, filename, gdal = options, format = filetype,  : 
  formal argument "sources" matched by multiple actual arguments

Error in (function (classes, fdef, mtable)  : 
  impossible to find inherited method for ‘writeRaster’ for signature ‘"SpatRaster", "missing"’

Here is a reproducible example with different calls.

`
f <- system.file("external/test.grd", package="raster")
r <- raster::raster(f)
s <- raster::stack(r,r)
t <- rast(s)

terra::writeRaster(s, names=paste0(names(s), ".tif"), overwrite=TRUE)

terra::writeRaster(t, names=paste0(names(t), ".tif"), overwrite=TRUE)

raster::writeRaster(s,
                filename = "test",
                format = "GTiff",
                bylayer = T,
                suffix = names(s),
                overwrite = overwrite)
`

Many thanks,
Arthur

R version 4.3 (also occured on 4.2.3)
terra version 1.7.29
raster version 3.6.20
Windows 10

**Comment by arthurdegrandpre** [comment]
Based on rhijmans answer on https://github.com/rspatial/terra/issues/272 I was able to use writeRaster as I wanted.

To make it work, I had to make my stack into a SpatRaster, and assign my names to a vector.

The call ended up being writeRaster(my_SpatRaster, my_names).

**Comment by rhijmans** [comment]
One common source of confusion is that there is a difference between `terra::writeRaster(x)` and `raster::writeRaster(x)` . There is not. There are different implementations of the generic `writeRaster` but the one you get depends on the `<class of x>`. So if you do `terra::writeRaster(<RasterStack>)` you get the method for a RasterStack that is implemented in the raster package. 

Your data 

```
library(terra)
library(raster)
f <- system.file("external/test.grd", package="raster")
s <- raster::stack(f,f)
t <- rast(s)
```

With your SpatRaster `t` you can do:

```
writeRaster(t, filename=paste0(names(t), ".tif"), overwrite=TRUE)
```

That is, you can supply multiple filenames. You must always supply a filename argument. See `?terra::writeRaster` (which goes to the `writeRaster` documentation in the "terra" package, and covers the case where `x` is a SpatRaster. 

There is a bug in the current raster package. You can either create a SpatRaster as Arthur suggests, or install the development version with 

```
install.packages('raster', repos='https://rspatial.r-universe.dev')
```

Then you can do:

```
writeRaster(s, filename = "test", format = "GTiff", bylayer = T,
                suffix = names(s), overwrite = TRUE)
```

Note that in both cases you can prepend `writeRaster` with `terra::` or `raster::` --- that does not change the result.
