### ISSUE TITLE
Missing `time()` and `timeInfo()` methods for `SpatRasterDataset`

### ISSUE THREAD

**Issue by dramanica** [rspatial/terra#1135]
`SpatRasterDataset` is missing methods for `time()` and `timeInfo()`. I made a pull request with those method implemented as simple `lapply()` of the `SpatRaster` methods. With the patch in #1134, I can get sensible output from:

```
a <- rast(matrix(1:9,ncol=3))
s <- list(c(a,a),c(a,a,a))
time(s[[1]], tstep="years") <- 2000 + 0:1
time(s[[2]], tstep="years") <- 2000 + 0:2
w <- sds(s)

time(w)
timeInfo(w)

```

**Comment by rhijmans** [comment]
Thanks!
