### ISSUE TITLE
roll() only for n >= nlyr(x)?

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1137]
Is that correct the roll() function only works when there is more than one layer in the raster? Is it like a **temporal** function? 
If so, maybe it would be good to add this into documentation? Also, in the Examples section, it says "SpatVector" while should be"SpatRaster".
![image](https://user-images.githubusercontent.com/55965799/235476736-7dad9e54-eb3a-4fe5-a89f-5f792207287c.png)

**Comment by rhijmans** [comment]
Yes, it is for the cell-wise rolling functions (that could be a time-series). I have expanded and fixed the documentation.

**Comment by Rapsodia86** [comment]
Thank you!
