### ISSUE TITLE
enhancement for focal() or moving window? 

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1138]
So, now I can get focal values by defining or using an odd size window. But the moving window always "overlaps" on values, it is rolling across.
Any chance to have a moving window that creates a new SpatRaster with a smaller size (based on w) and the windows do not overlap? 

Now we have: 
```
r <- rast(ncols=6, nrows=6, ext(0, 6, 0, 6))
values(r) <- 1:ncell(r)
fx=matrix(c(1,1,0,1,1,0,0,0,0), nrow=3) #two x two window
ff <- focal(r, w=fx, fun="sum") 
> as.matrix(r, wide=TRUE)
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    2    3    4    5    6
[2,]    7    8    9   10   11   12
[3,]   13   14   15   16   17   18
[4,]   19   20   21   22   23   24
[5,]   25   26   27   28   29   30
[6,]   31   32   33   34   35   36
> as.matrix(ff, wide=TRUE) #result
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]   NA   NA   NA   NA   NA   NA
[2,]   NA   18   22   26   30   NA
[3,]   NA   42   46   50   54   NA
[4,]   NA   66   70   74   78   NA
[5,]   NA   90   94   98  102   NA
[6,]   NA   NA   NA   NA   NA   NA
```
The moving window ver 2 would result in: 
```
     [,1] [,2] [,3]
[1,]   18   26   34
[2,]   66   74   82
[3,]  114  122  130
```

**Comment by rhijmans** [comment]
for this specific example, you can do 

```
aggregate(r, 2, sum) |> as.matrix(wide=TRUE)
#     [,1] [,2] [,3]
#[1,]   18   26   34
#[2,]   66   74   82
#[3,]  114  122  130
```

**Comment by Rapsodia86** [comment]
Ha, yes, that works! And aggregate allows for two integers (horizontal and vertical aggregation factor) when specifying factor/window, so that is a lot of flexibility.
Would then `zonal()` be extended to provide zones based on the window size (two integers as above) or matrix? Or would that result in overlapping functionality with `aggregate()`?
Thank you!

**Comment by rhijmans** [comment]
I think that is better handled by aggregate; and I have added a reference to that in the zonal documentation. I could imagine adding a matrix method to aggregate, but that seems a bit esoteric. You can also do that now, by specifying a function that multiplies the values with the weights before computing (e.g. the sum).

**Comment by Rapsodia86** [comment]
Makes sense, thank you!:)

**Comment by Nowosad** [comment]
@Rapsodia86 -- your request seems similar to the function I wrote sometime ago -- maybe it will be useful for you: see https://github.com/Nowosad/spquery/blob/main/R/spq_collapse.R

**Comment by Rapsodia86** [comment]
Hi @Nowosad ,
Thank you for the information, I will check it when get back to the office. 
Meanwhile, greetings from Warsaw:)
