### ISSUE TITLE
`levels<-` character  first column "Error in round(value[, 1]): non-numeric argument to mathematical function"

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#1142]
With current terra (1.7-30) I noticed that when the first column of a data.frame of input values to `levels<-` is a character, the following error occurs

``` r
library(terra)
x <- rast(matrix(rep(1:3, 3), ncol = 3))
levels(x) <- data.frame(LETTERS[1:3], 1:3)
#> Error in round(value[, 1]): non-numeric argument to mathematical function
```

In the case I ran into this, the data.frame had different column order where the "ID" column wasn't first. I was puzzled by the error initially, and then saw that re-arranging the columns was what I needed. 
Could a more informative error message be issued here?

**Comment by rhijmans** [comment]
Thanks, you now get this message:

```
# Error: [set.cats] the first column of 'value' must have integer or numeric values
```
