### ISSUE TITLE
`plot` for SpatVector could use column names as "main" by default

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1146]
Just a suggestion, but to me it would be more practical if the default `main` in `plot` for SpatVector, rather than an empty character string, were the name(s) of the column(s) specified in `y`. Cheers!
```
v <- vect(system.file("ex/lux.shp", package="terra"))
names(v)

plot(v, 2:4)
plot(v, 2:4, main = names(v)[2:4])

plot(v, c("NAME_1", "NAME_2"))
plot(v, c("NAME_1", "NAME_2"), main = c("NAME_1", "NAME_2"))
```

**Comment by rhijmans** [comment]
I agree. And that is how it works for SpatRaster. Thanks.
