### ISSUE TITLE
legend starts too far south when plotting SpatVector columns

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1147]
I'm not sure this is desired behaviour, but with recent versions of 'terra', when plotting columns of a SpatVector, by default the legend is placed further down than it used to, often leaving an awkward amount of white space on top and requiring more space at the bottom:

```
v <- vect(system.file("ex/lux.shp", package="terra"))
plot(v, c("NAME_1", "NAME_2"), nc = 1)
```
![image](https://user-images.githubusercontent.com/12085508/236848581-b2d8b5eb-d485-4dde-b35b-7dc5dc142f9f.png)

Could the legend be made to start (by default) at the ymax coordinate of the plotting region, as I think it used to (when `clip` was always FALSE)?

**Comment by rhijmans** [comment]
I think it is now restored to its old glory. What happened was that space for a legend title was reserved, even if there was no title.

**Comment by rhijmans** [comment]
But you may still want to reduce the legend size with something like 

```
plot(v, c("NAME_1", "NAME_2"), nc = 1, plg=list(cex=.8))
```
