### ISSUE TITLE
Feature request: same range in all panels

### ISSUE THREAD

**Issue by dramanica** [rspatial/terra#1149]
When plotting certain rasters, it makes sense to have the same scale for all layers. This is usually the case when layers represent time rather than different variables. In principle, we can achieve this result with:
```
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
r <- c(r,r*2,r*3)
time(r,tstep="years")<-c(0,10,20)
plot(r,range=rep(c(min(global(r,"min",na.rm=TRUE)),
             max(global(r,"max",na.rm=TRUE)))))
```
But it does feel a bit unwieldy for the behaviour that would be expected by default. Would you consider adding something like `same_range=TRUE` to `plot` to achieve this behaviour? And if so, might it be possible to have it as the default behaviour when we have temporal layers? (for temporal layers, `plot` already behaves differently by plotting the time rather than the variable name at title of each panel, so I don't think this change would be confusing to the user).
Happy to put together a pull request with the necessary changes if you are happy with this suggestion, but I thought I would ask first, as I understand that it adds yet another parameter to the already busy `plot` function.

**Comment by rhijmans** [comment]
What about 

```
panel(r)
```

That has the additional benefit of having a single legend. And that is why it is not an option to plot, as that changes a lot of things.

Also, you can express the call to plot a little more succinctly like this:

```
plot(r, range=range(minmax(r, T)))
```

**Comment by dramanica** [comment]
Ok, I have to confess that I had not spotted `panel`! And the `range` code is very elegant.
So, in principle, you have already solved my feature request. But whilst checking out `panel`, I am afraid that I managed to break it. If I create a spatRaster with just one value (as it is sometimes the case when creating masks), `panel` breaks:
``` r
library(terra)
#> terra 1.7.32
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
r <- c(r,r+1,r+2)
r[r<300]<-NA
r[!is.na(r)]<-1
time(r,tstep="years")<-c(0,10,20)
# panel fails
panel(r)
#> Error in .as.raster.continuous(out, x, type): out$range[2] > out$range[1] is not TRUE
```

``` r
# but plot works just fine
plot(r)
```

![](https://i.imgur.com/SSme9cC.png)

<sup>Created on 2023-05-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
As always, thank you so much with all your efforts with `terra`, it's a great package.

**Comment by dramanica** [comment]
@rhijmans One more question, if I may. When working on a medium size raster [dimensions  : 1080, 2160, 12  (nrow, ncol, nlyr)] stored as netcdf, the first time I issue `range(minmax(x,TRUE))`, I get `-Inf Inf`. If I then reissue the command, I get the correct values. 
Does that ring any bells? I can try to create a reprex for this strange behaviour, but as it requires a largish file (incidentally, it is just 12 months of tavg from worldclim at 10 min resolution), I thought I would ask first, in case it was obvious what is going on.

**Comment by rhijmans** [comment]
Thanks, I think both of these issues have now been solved.

**Comment by dramanica** [comment]
Amazing, thank you!
