### ISSUE TITLE
filename not working

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#115]
The `filename` function is well described in the documentation but, whatever the raster, the call to the `filename `function always returns the same error: 

```
> r=rast("sresa1b_ncar_ccsm3-example.nc")
> filename(r)
Error in filename(r) : could not find function "filename"
```

**Comment by rhijmans** [comment]
`terra` has no `filename` argument (but see `sources`). You are probably looking at the documentation of `raster::filename`

**Comment by jldupouey** [comment]
OK. In this case, perhaps it should be better to remove this function from the documentation of the terra package (https://cran.r-project.org/web/packages/terra/terra.pdf, p. 10: "filename          Filename(s) to which a SpatRaster is linked").

**Comment by rhijmans** [comment]
Yes, that was wrong. Thank you.
