### ISSUE TITLE
`plot()` `type="classes"` specifying `levels` with different order than natural value order

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#1151]
I think I noticed an issue when specifying `levels` argument to `plot()` for a categorical SpatRaster when the the `value` order is different from `category` order 

For example when value has reversed order of the alpha order of categories, it results in a legend with the correct category order but no corresponding change in assignment of colors/values.

```r
library(terra)
x <- rast(matrix(round(runif(9)*2), ncol=3))
levels(x) <- data.frame(value=rev(0:2), category=letters[1:3])
plot(x, type="classes")
plot(x, type="classes", levels = letters[1:3])
```
![image](https://github.com/rspatial/terra/assets/20842828/2670822f-cd42-4322-91dd-2dd9251395b3)
![image](https://github.com/rspatial/terra/assets/20842828/95327111-fff0-402a-9076-97d59fcc54e8)

**Comment by rhijmans** [comment]
I am not sure if that is a bug or a (questionable) feature. The argument is to allow using prettier labels. For example 

```
plot(x, levels=c("Cat", "Bee"), type="classes")
plot(x, levels=c("Dog", "Cat", "Bee", "Ape"), type="classes")
```

It is your responsibility to match them. That can be tricky, so perhaps the argument is a bad idea and should be removed. You could add a column to the categories table instead. That could be made easier with a dedicated function. Or am I missing something?

For what you appear to be after in this case, there already is

```
plot(x, all_levels=T, type="classes")
```

**Comment by brownag** [comment]
Thanks @rhijmans.  I think `all_levels=TRUE` works for my simple case and also some more general cases I can think of. I don't think I have used that argument before.

I appreciate you taking the time to explain.  I think there is not an issue here. After posting I considered how complex it would be to support arbitrary relabeling aware of existing categories and their order. I should probably not use `levels=` as a shortcut

The tricky part for me is sometimes I have multiple categories mapped to a common "key" value. The different categories may differ in their logical order... i.e. potentially different from the numeric order of the key value and/or their row position in the category table. Particular extents may not have all of the possible categories in an ordinal set represented, which can complicate ordering and making nice legends given data from arbitrary areas.

Overall I think this is a "feature" (that caused me to ask a question) to allow relabeling outside the categories tables at the `plot()` level. I was just surprised in an instance I was careless with the reordering/matching values 1:1.

I can imagine as you suggest wanting to specify a subset of n labels and have legend/plot show only those (rather than replace the first n labels), but I think its not unreasonable to set up the categories or classify()/subst() through existing means.

**Comment by brownag** [comment]
I am going to close this issue, thanks for the help. In the cases I have all of the levels I want in an order I want in my category table `all_levels=TRUE` works great. 

For more general cases I created a draft PR with some ideas. https://github.com/rspatial/terra/pull/1154 Feel free to close that if you think it is not feasible, or pirate it for ideas if it inspires anything that can be done with ordered factors.
