### ISSUE TITLE
writeCDF mishandles time in months

### ISSUE THREAD

**Issue by dramanica** [rspatial/terra#1152]
If time is set in "months", `writeCDF` writes time units as "unknown". This triggers warnings from gdal when reading the file in with `rast` (as time units are invalid), as well as losing the time information on loading the file. Looking at the code of `writeCDF`, it handles seconds, days, and years, but not months. As "months" is a valid `tstep` unit, it would be nice to have it catered for in `writeCDF`.

**Comment by rhijmans** [comment]
Thanks, this should work now.
