### ISSUE TITLE
Does not work with PROJ 6; require PROJ 4

### ISSUE THREAD

**Issue by soccin** [rspatial/terra#1155]
If you have a modern version of PROJ >= 6 instead of PROJ 4 then gdal_has_proj check fails with:
```
OGRCoordinateTransformation() does not return a coord.trans: PROJ not available
```
Might want to add that in the requirements.

**Comment by rhijmans** [comment]
I can install terra (the development version) with PROJ versions 4.9.3, 5.2.0, 8.2.0, 9.2.0

Perhaps it fails for PROJ 6 (or only with the CRAN version?), but your error message suggests another problem. Perhaps caused by having multiple installations of PROJ installed?
