### ISSUE TITLE
resample in parallel

### ISSUE THREAD

**Issue by zhangzhixin1102** [rspatial/terra#1156]
Dear terra developer,

Thank you for developing such a helpful R package. I am writing to ask: is it possible to resample a large raster file in parallel?

In my study, I need high-resolution (30 meters) rasters, so I need to resample my 5 arcmin rasters into 30 meters. My scripts work fine but the calculation takes extremely long time (seems never stop). Is it possible to resample in parallel (I can get access to over 60 cores in my pc)? Below are my initial R scripts:

`

rm(list = ls())
t1 <- Sys.time()

library(terra)
library(geodata)

## raster in 5 arcmin
r.elevation.5min <- geodata::elevation_global(res = 5, download = F, path = 'data')

## template layer at 30 m resolution
r.template.30m  <- rast(ext(-18, 180, -90, 90), resolution = c(0.0002777006, 0.0002777006))

# resample (take time)
r.elevation.30m <- resample(r.elevation.5min, r.template.30m, method = "bilinear")

Sys.time() - t1
`

Many thanks for your kind help.

Best regards,

Chou

**Comment by kadyb** [comment]
1. This is not answer to your question, but why don't you download some data originally in 30 m (e.g. SRTM, NASADEM or GLO)? By doing upsampling in this way you are not increasing the information.
2. You can try using `threads = TRUE` in `resample()`. You can also test [disagg()](https://rspatial.github.io/terra/reference/disaggregate.html) function, maybe it will work better.
3. Did you try using [gdal_translate](https://gdal.org/programs/gdal_translate.html) or [gdalwarp](https://gdal.org/programs/gdalwarp.html) directly?

**Comment by rhijmans** [comment]
If you have a hpc computer you could do this by tiles (that overlap, to avoid edge effects).
