### ISSUE TITLE
Writing rasters to virtual file system?

### ISSUE THREAD

**Issue by cboettig** [rspatial/terra#1159]
`terra::writeVector()` can write to GDAL virtual filesystems like S3 (`/vsis3/`) no problem, which is rather wonderful.  

However, when I attempt to write geotif to the same virtual filesystem in the same way, `terra` just tells me it cannot find the path, suggesting that it is trying to interpret the `/vsis3` prefix as a local POSIX filesystem instead.  Would it be possible for `writeRaster()` to support VSI like `writeVector` already does?  Thanks!!

**Comment by jtfrench12-SR** [comment]
Tried this yesterday with the same issue. This functionality would be awesome.

**Comment by cboettig** [comment]
@jtfrench12-SR my guess is that terra is somehow checking the path exists before writing, relying on some POSIX logic.  (it is a bit strange that GDAL didn't use the URI protocol notation, s3://, for this purpose, note that popular Python wrappers often support either the URI or native GDAL notation ...)  

Meanwhile, just a note that you can use `stars` to write rasters directly to S3.  Remember to first set the env var `CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE=YES`, as the gdal cli will helpfully tell you, but the R wrappers will not.  Thanks goes to @edzer for this https://github.com/r-spatial/stars/issues/631

**Comment by rhijmans** [comment]
This was indeed, at least partly, caused by normalizing the path. It probably works now; also for "s3://etc/file.tif"

**Comment by rhijmans** [comment]
Based on https://github.com/rspatial/terra/issues/1209 I assume this now works (did not test it myself).
