### ISSUE TITLE
`panel()` with some continuous data fails without min/max limits 

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#1161]
With some continuous data in a multilayer SpatRaster plotted with `panel()` I get the following warning and error from `.get_breaks()`

```r
#> Warning: [minmax] min and max values not available for all layers. See
#> 'setMinMax' or 'global'
#> Error in if ((r[1]%%1) != 0) {: missing value where TRUE/FALSE needed
```
using terra 1.7-33 the following creation of a geopackage successfully creates a file containing two raster datasets that can be read in with `rast()` and plotted with `panel()`

``` r
library(terra)
#> terra 1.7.33
r <- rast(system.file("ex", "elev.tif", package="terra"))

gpkg_temp <- tempfile(fileext = ".gpkg")

writeRaster(r, gpkg_temp, overwrite = TRUE)

writeRaster(r, gpkg_temp, gdal=c("RASTER_TABLE=DEM2", "APPEND_SUBDATASET=YES"))

rast(gpkg_temp) |> 
  panel()
```

![](https://i.imgur.com/ZTfuhrZ.png)

If I add a third layer as subdataset with `"FLT4S"` datatype, `panel()` breaks on the SpatRaster object result. This error appears to occur if one or more layers were written with `datatype="FLT4S"`. 

``` r
writeRaster(r, gpkg_temp, datatype = "FLT4S", gdal=c("RASTER_TABLE=DEM3", "APPEND_SUBDATASET=YES"))

rast(gpkg_temp) |> 
  panel()
#> Warning: [minmax] min and max values not available for all layers. See
#> 'setMinMax' or 'global'
#> Error in if ((r[1]%%1) != 0) {: missing value where TRUE/FALSE needed
```
It seems that the min/max values return Inf/-Inf for this layer, causing the error. As the warning indicates, adding `setMinMax(rast(gpkg_temp))` fixes the problem. Should calculation of min/max be forced for cases like this (default plot limits) or is it expected to have to call `setMinMax()`? In this example it is not costly to do so, but I can imagine cases where it would take more time

**Comment by rhijmans** [comment]
That was a bug. Fixed now with https://github.com/rspatial/terra/commit/9fd20a30368bceeadb1c1fb1913dd04137008c57
