### ISSUE TITLE
creating SpatVector of points with attributes from scratch

### ISSUE THREAD

**Issue by phuais** [rspatial/terra#1164]
I am getting an error when trying to create a SpatVector of points from scratch, with attributes. For instance:

`d <- data.frame(id=1:2, name=c("a", "b"))`
`m <- vect(data.frame(x = c(5, 4), y = c(6, 8)), 
          geom = c("x", "y"), 
          atts=d, 
          crs="+proj=longlat +datum=WGS84")`

Error message:

`Error in .local(x, ...) : unused argument (atts = list(1:2, c("a", "b")))`

I don't know if is a bug or not, but I can't figure it out.

Also, I know this is not the most suitable platform to ask this, but I was having trouble to manually modify the coordinates of  the points of a SpatVector. I thought that setting the values to the output of `terra::crds` would do the trick, but it did not work.

R version 4.3.0 (2023-04-21)
Package terra version 1.7-29

Thanks

**Comment by rhijmans** [comment]
You are using the `vect<data.frame>` method, but "atts" is an argument to the `vect<matrix>` method. So you can do.

```
d <- data.frame(id=1:2, name=c("a", "b"))
m <- vect(cbind(x = c(5, 4), y = c(6, 8)),  atts=d,  crs="+proj=longlat +datum=WGS84")
```

You cannot directly manipulate the geometry of a SpatVector with `crds<-` or something like that; but that is an interesting idea.
