### ISSUE TITLE
plotRGB() error when run in R Mac Builder

### ISSUE THREAD

**Issue by GastonMauroDiaz** [rspatial/terra#1165]
Hello,

I extensively use terra package to do most of the image processing needed within my package, called rcaiman (https://cran.r-project.org/web/packages/rcaiman/index.html).

I work with conventional photographs taken with normal cameras (8-bit RGB JPEG). I like to use plotRGB() to quickly see the picture within R.

My package came with some JPEG to run the examples. I can show you this one in particular https://github.com/GastonMauroDiaz/rcaiman/blob/master/inst/external/b4_2_5724.jpg

Well, the problem is that I use (as a quick fix, I am changing it now to avoid conflict) plotRGB() in the examples, but the CRAN machines are throwing an error. I replicated it with https://mac.r-project.org/macbuilder/submit.html

Here is the important part extracted from the  result:

Build system: r-prerelease-macosx-arm64|4.3.0|macosx|macOS 13.3.1 (22E261)|Mac mini|Apple M1||en_US.UTF-8|macOS 11.3|clang-1403.0.22.14.1|GNU Fortran (GCC) 12.2.0

Build log 
-------
NOTE: there is no source for package terra [terra], installed CRAN version will be used.

 Check Log
---------
* using R version 4.3.0 beta (2023-04-11 r84222)
* using platform: aarch64-apple-darwin20 (64-bit)
* R was compiled by
    Apple clang version 14.0.0 (clang-1400.0.29.202)
    GNU Fortran (GCC) 12.2.0
* running under: macOS Ventura 13.3.1
* using session charset: UTF-8
> ### ** Examples
> 
> path <- system.file("external/b4_2_5724.jpg", package = "rcaiman")
> caim <- rast(path)
Warning: [rast] unknown extent
> plotRGB(caim)
Error in .local(x, y, ...) : 
  (min(y) > 0) & (max(y) <= nlyr(x)) is not TRUE
Calls: plotRGB ... plotRGB -> .local -> plot -> plot -> .local -> stopifnot
Execution halted
----------

This link may give you the full results https://mac.r-project.org/macbuilder/results/1684499043-b39453123a04e979/results.tar.bz2 (I do not know how much time they store it)

I found plotRGB() in the terra source code (line 909 from plot_rater.R), but although there is nothing there suggesting that the error message is from terra, you might want to take a look. It could be a  numerical issue from base R. 

Thank you!

**Comment by rhijmans** [comment]
This is because an old version of terra::plot is used, which conflicts with `plotRGB`. It is an odd situation, caused by another package importing `terra::plot` and "freezing" it (until it gets re-installed). Since "rcaiman" depends on "lidR" I assume that this cause the problem. See this:  https://github.com/r-lidar/lidR/pull/672

The problem should go away when a new version of lidR is sent to CRAN (but that it could resurface again in the future, unless something more structural is done about it)

**Comment by GastonMauroDiaz** [comment]
Thank you for the summary since the discussion between you and Jean-Romain is a bit outside my current skills. 

I will not reverse the examples to the version using plotRGB() since they are not essential and, as you mention, the problem could resurface again after fixing it. 

Because now I know the origin of the error message, I will close this issue. 

Thank you,
Gastón
