### ISSUE TITLE
No legend for points when add=TRUE

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1166]
Hi,
The code below used to work as expected, but now (latest CRAN version of terra, 1.7.29, and latest GitHub version of terra, 1.7.33, on Linux Mint 21.1 and Windows 10 Home) the legends for the points maps do not appear if they're in a command with `add=TRUE`:
```
pol <- vect(system.file("ex/lux.shp", package="terra"))
pts <- centroids(pol)

plot(pol)  # tried also with clip = FALSE, mar = c(4, 4, 4, 4)
plot(pts, "AREA", cex = 0.5, add = TRUE, plg = c(x = "topleft", title = "Area"))
plot(pts, "POP", pch = 1, cex = 1.5, add = TRUE, plg = c(x = "bottomleft", title = "Population"))
```
Cheers,

**Comment by rhijmans** [comment]
Thanks. The default value of "legend" was changed from `TRUE` to `!add`. So in your case you now need to do 

```
plot(pol)  # tried also with clip = FALSE, mar = c(4, 4, 4, 4)
plot(pts, "AREA", cex = 0.5, add = TRUE, plg = c(x = "topleft", title = "Area"), legend=TRUE)
plot(pts, "POP", pch = 1, cex = 1.5, add = TRUE, plg = c(x = "bottomleft", title = "Population"), legend=TRUE)
```

That is, of course, more cumbersome, but my thinking was that in most cases you would not want a legend. Although the design is to use `points`, `lines`, or `polygons` in those cases. What I see in class is that students tend to discover/remember/use "add=TRUE" instead.

**Comment by AMBarbosa** [comment]
Personally I would prefer this default for `axes` but not for `legend`, but that's entirely up to you, of course :)

But I think it would make sense, then, to set the default `axes` (and `legend`) to `!add` also for SpatRaster objects.

**Comment by rhijmans** [comment]
Changed according to your suggestions. Thanks.
