### ISSUE TITLE
January 1st date formatted incorrectly in `.tif.aux.json`.

### ISSUE THREAD

**Issue by colinbrust** [rspatial/terra#1168]
I recently had to query one of the `.json` files created with a `.tif` and noticed that instead of being formatted as {Year}-01-01, Jan 1st is formatted as {Year - 1}-13-01, which lead to issues when parsing the file outside of `terra`. I did a little digging but was unable to find what might be causing this to happen. Here is an example: 

``` r
library(terra)
#> terra 1.7.33

r <- terra::rast(nrow=4, ncol=3, nlyrs=3, vals=rep(1:12, 3))
terra::time(r) <- seq.Date(from=as.Date("2022-12-31"), to=as.Date("2023-01-02"), by="days")

terra::writeRaster(r, "./test.tif", overwrite=TRUE)
readLines("./test.tif.aux.json")[2]
#> [1] "\"time\":[\"2022-12-31\",\"2022-13-1\",\"2023-1-2\"],"
```

<sup>Created on 2023-05-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Thank you for reporting this. I now get 

```
[1] "\"time\":[\"2022-12-31\",\"2023-1-1\",\"2023-1-2\"],"
```
