### ISSUE TITLE
Option to disable wrapping in adjacent() and focalValues()

### ISSUE THREAD

**Issue by andrewmarx** [rspatial/terra#1172]
I just realized that depending on the projection and extent, the adjacent() and focalValues() functions (and possibly others I'm not thinking of) will wrap to the opposite edge of the raster. This makes sense, but it caught me off guard while running tests with procedurally generated rasters where the default extents wrap. I'm not sure this behavior is necessary for my packages and will require me to potentially sacrifice some optimizations I have in my packages to account for it. I'm also not sure my users ever really need it, and in fact, some of them may be falling into the same trap as me and not realizing their generated data wraps and produces a different result than intended. Ideally, I would disable the behavior with something like a `wrap = FALSE` argument in these functions, warn users when they have a raster that does technically wrap, and then maybe rewrite my code later if it does end up being important for some users to support wrapping.

**Comment by rhijmans** [comment]
I cannot think of a situation where `wrap=FALSE` would be desirable. Cells touching either side of the data-line simply *are* adjacent.

**Comment by andrewmarx** [comment]
That's fine; I mentioned in #1174 my concern about users accidentally stumbling into a situation they weren't expecting, but just being able to check the data so I can respond accordingly is sufficient
