### ISSUE TITLE
Document wrapping behavior in functions like adjacent() and focalValues()

### ISSUE THREAD

**Issue by andrewmarx** [rspatial/terra#1173]
Related to #1172 could we get a brief mention in the documentation for functions like adjacent() and focalValues() (and others I may not be thinking of) that, in certain circumstances, these functions can wrap to the opposite edge of the rasters? It makes sense that this occurs, but it had never occurred to me this would happen until I got caught off guard with testing some niche code using generated test rasters where it caused an obvious issue. I could see a lot of people doing things where this doesn't cause an issue but they also don't realize it is occurring

**Comment by rhijmans** [comment]
Thanks
