### ISSUE TITLE
Function to identify if a raster wraps

### ISSUE THREAD

**Issue by andrewmarx** [rspatial/terra#1174]
Related to #1172 would it be possible to get a function to quickly check if a raster wraps on itself? I would like to be able to warn users when they provide a raster that does because it's easy to unintentionally create a raster that does using functions like rast() and raster::raster() if the default CRS of lon/lat is applied

**Comment by rhijmans** [comment]
east/west "wrapping" only occurs if the left and right sides of the raster are adjacent. That is, when the CRS is lon/lat and the extent is global. To check for that, you can use 

```
is.lonlat(rast(), global=T)
#[1] TRUE
```

I do not understand why you would need to warn users about that. It may be that they had not thought of it, but I cannot think of a situation where that would not be desirable.

**Comment by rhijmans** [comment]
By the way, cells that touch the north pole and all cells that touch the south pole are also adjacent, but I ignore that in most cases because it changes the total number of cells considered.  It is considered in gridDistance (and costDistance, I think).

**Comment by andrewmarx** [comment]
> east/west "wrapping" only occurs if the left and right sides of the raster are adjacent. That is, when the CRS is lon/lat and the extent is global. To check for that, you can use
> 
> ```
> is.lonlat(rast(), global=T)
> #[1] TRUE
> ```

Sweet, I wasn't sure if there was only one case to be looking for.



> I do not understand why you would need to warn users about that. It may be that they had not thought of it, but I cannot think of a situation where that would not be desirable.

I guess I know a lot of people that would assume these two approaches to creating a raster would be functionally equivalent and not catch that the extents/resolution are different:

```
> r1 = rast(nrow = 10, ncol = 10)
> r1[] = 1:100
> r1
class       : SpatRaster 
dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
resolution  : 36, 18  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
source(s)   : memory
name        : lyr.1 
min value   :     1 
max value   :   100 

> r2 = rast(matrix(nrow = 10, ncol = 10))
> r2[] = 1:100
> r2
class       : SpatRaster 
dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0, 10, 0, 10  (xmin, xmax, ymin, ymax)
coord. ref. :  
source(s)   : memory
name        : lyr.1 
min value   :     1 
max value   :   100 
```

For a lot of applications/analyses, it might not matter. But for the packages I work on, it does, and it's not uncommon for people to create rasters manually to illustrate ideas in figures under the assumption that all four edges are a boundary. The former approach is definitely rarer than the latter, in my experience, so I would only expect it to be something that rarely comes up. In my case, it came up while trying to rebuild the overview vignette for the gdistance package, which uses the former approach, and it broke under a new optimization; otherwise, I never would have thought to account for it. So I just want to make sure any users that unintentionally stumble into this situation are aware of how my packages are interacting with their data.

**Comment by rhijmans** [comment]
I understand this can trip one up when creating a toy example for illustration purposes. The solution is to create an appropriate planar raster. It seems to me that, with real data, "wrapping" is always correct, even if people may not expect this to happen.

**Comment by rhijmans** [comment]
I understand this can trip one up when creating a toy example for illustration purposes. The solution is to create an appropriate planar raster. It seems to me that, with real data, "wrapping" is always correct, even if people may not expect this to happen.
