### ISSUE TITLE
spatSample() not taking a random distribution of points

### ISSUE THREAD

**Issue by liannemit** [rspatial/terra#1176]
Hello,

I used the spatSample function (terra package v 1.6.53) to create 100 subsamples in 10 different test sites, which contain binary values for a species distribution (1 = presence, 0 = absence). In each test site, the species distribution varies. However, I noticed that across all of my subsamples in the different test sites, there was consistently a greater number of points selected using SpatSample at the bottom of the test site, with fewer points at the top of the test site.

I cannot share my original file but to test if this was a bug associated with clustered presence points, I created a shapefile (attached below) using a vector grid with 100489 cells. This test site has a 100% coverage with no missing values. To match the distribution of a species, 30% of cells were assigned a binary value for presence (1) using a QGIS tool for random selection. This has a more widespread distribution. The resulting shapefile contained two polygon geometries for presence (1) and absence (0) in a column labelled 'PA'. When I used spatSample to create a subsample of 5000 points, the similar trend of sampled points with a greater number selected at the bottom of the test site and fewer at the top.

There seems to be an issue where spatSample() is not taking a truly random sample.

The code used is attached after importing the file attached as a SpatVect using vect("file-path"):

```
# view file
practice

# sample
set.seed(111)
practicesample <- spatSample(x = practice, size = 2500, method = "random", strata = practice$PA, chess="") # want to take an equal sample of presence and absence points so taken within column 'PA' which contains the binary values

# check data
practicesample # geometry of 5000 points
samplepresence <- sum(practicesample$PA == 1) / sum(!is.na(practicesample$PA)) # check presence is 50%
samplepresence
plot(practicesample) # view distribution of sampled points
```

An alternate way to sample by splitting the dataset into two objects which contain either presence points or absence points:

```
presence_points <- practice[practice$PA == 1]
absence_points <- practice[practice$PA == 0]

presence_sample <- spatSample(x = presence_points, size = 2500, method = "random")
absence_sample <- spatSample(x = absence_points, size = 2500, method = "random")

practicesample2 <- rbind(presence_sample, absence_sample)
```

The plots for the two subsamples produced are attached as pictures and the shapefile is attached as well:
![Test2](https://github.com/rspatial/terra/assets/130184780/e029a28a-15d0-4666-8a1c-69e642d7a57c)
![Test1](https://github.com/rspatial/terra/assets/130184780/65351346-3e74-437f-8305-6c405d2c6201)
[Test.zip](https://github.com/rspatial/terra/files/11593985/Test.zip)

**Comment by rhijmans** [comment]
Thanks, but if things do not work, the first action to take is to update "terra". You are pretty far behind, and I think this problem does not exist in the current version (but do let me know if I am wrong).

**Comment by liannemit** [comment]
Thank you - I missed the updates for terra and doing so has now resolved the issue!
