### ISSUE TITLE
terra: plet() to plot a quantitative field of SpatVector

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#1177]
(see also in https://stackoverflow.com/questions/76359833/terra-plet-to-plot-a-quantitative-field-of-spatvector)

I have problems producing reasonable plots of quantitative fields in SpatVector objects.
Using data from the example on the help page:

    v <- vect(system.file("ex/lux.shp", package="terra"))
    plet(v, "POP", tiles="")

[![enter image description here][1]][1]
Note the color scale is not appropriate for a continuous variable and the legend is not ordered.
    
    r <- rast(system.file("ex/elev.tif", package="terra"))
    #correct plot:
    plet(r, tiles="")

[![enter image description here][2]][2]

    #but
    rp <- as.points(r)
    plet(rp, "elevation", tiles="")

[![enter image description here][3]][3]

It looks like the quantitative field is plotted as if it were qualitative, but
I do not see specific options in the parameter list.

  [1]: https://i.stack.imgur.com/aJUgg.jpg
  [2]: https://i.stack.imgur.com/ab0dd.jpg
  [3]: https://i.stack.imgur.com/i6HU2.jpg

**Comment by rhijmans** [comment]
Thanks, I believe this now works. The choice of legend is based on the data (character or numeric), and for numeric how many unique values there are. You can also set the legend type with argument "type". Also see arguments "breaks" and "breakby"

**Comment by aloboa** [comment]
Yes, it does work, thank you:

```
v <- vect(system.file("ex/lux.shp", package="terra"))
plet(v, "POP", tiles="")
```

![image](https://github.com/rspatial/terra/assets/6074054/39a136ae-448e-4846-932f-ffcc53fb4588)

Please consider adding this example to the help page.

Regarding breaks and breakby, I observe they do not exist for spatial raster objects.

```
         plet(r, tiles="")
         plet(r, tiles="", breaks=0:100)
         Error in .local(x, ...) : unused argument (breaks = 0:100)
         plet(r, tiles="", breakby="eqint")
         Error in .local(x, ...) : unused argument (breakby = "eqint")

```
