### ISSUE TITLE
crs argument provided in the rast function does not override crs of the external file

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#118]
`crs` argument in `rast` function of terra does not always operate. When reading a `SpatRaster`, the `crs` argument does not override the crs associated with the layer in the external file. 

That is a rather unexpected behaviour. The argument given by the user should override the information contained in the file. 

If it is not the case, a warning should be emitted for such a call to the `rast` function. Alternatively, this unsual choice should be clearly indicated in the documentation.

I am not dealing with transformations of coordinate systems, of course, only their setting.

```
library(terra)
# terra version 1.0.2

r <- rast(ncol=2, nrow=2, vals=c(5.3, 7.1, 3, 1.2))  
crs(r)   # epsg 4326 by default

# [1] "GEOGCRS[\"unknown\",\n    DATUM[\"World Geodetic System 1984\"...

crs(r) <- "epsg:2154"  # change to epsg 2154
crs(r)    # OK, changed to epsg 2154
# [1] "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\"...

writeRaster(r,"test.tif",overwrite=TRUE)
t1 <- rast("test.tif")  

crs(t1) #OK, 2154

# [1] "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\"...

# try to read test.tif as WGS84 (epsg 4326):

t2 <- rast("test.tif",crs="epsg:4326")  #argument crs= does not operate!

crs(t2)  # epsg is still the one associated with test.tif

# [1] "PROJCRS[\"RGF93 / Lambert-93\",\n    BASEGEOGCRS[\"RGF93\"....

# it can be changed later, but this is not the point:

crs(t2) <- "epsg:4326"
crs(t2)  # OK, changed to 4326
# [1] "GEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\"...
```

**Comment by rhijmans** [comment]
I have removed the ellipses, so that you now get 

```
t2 <- rast("test.tif",crs="epsg:4326")  #argument crs= does not operate!
#Error in .local(x, ...) : unused argument (crs = "epsg:4326")
```
Allowing for what you want to do would get too many beginners in trouble, I am afraid.

**Comment by jldupouey** [comment]
The warning is adequate. But I think it's the way it works now that should be disruptive to users, for several reasons:

. Assignments, in a very general way in R and in all programming languages, erase previous or default values, most often without any warning.

. The fact that:

`MyRast=rast("MyFile", crs=...)` does not always take into account the crs argument, depending on the properties of the file read,

but that the double call to `crs`:
```
MyRast=rast("MyFile",crs=...)
crs(MyRast)=...
```
does it is counter-intuitive. 

.  In the particular case of spatial objects in R, functions such as `sf::st_read` have the opposite behavior (the crs specified in the call erases the one associated with the layer, when it exists, with a warning message). It is an annoying point, to have heterogeneous behaviors according to functions, for the same functionalities (assign a crs), especially for beginners.

Whatever, it is a choice, and the main point is to have it documented, and a warning associated. Thanks.

**Comment by rhijmans** [comment]
I it is an error, not a waring. So this 

       r <- rast("filename", crs="") 

is not possible anymore, because the  `rast(character)` method does not have a `crs` argument (and no ellipses).  I think that makes sense, as you are reading from a file that normally would provide you with the crs (and the extent, resolution, and cell values). I understand it occasionally happens that you need to set the crs manually for a file based raster, but in my experience that is rare. 

It would of course be handy to be able to set it when needed. But I fear the confusion, and mistakes, that this will cause.
