### ISSUE TITLE
reprojection became very slow

### ISSUE THREAD

**Issue by brry** [rspatial/terra#1181]
`terra::project` is very slow on a raster by the german weather service DWD.  
It is now 100 seconds for what used to be 1.4 seconds last year, see the code below.
Is that a bug or expected with the new gdal/proj situation? Can it be sped up?

```r
link <- paste0("ftp://opendata.dwd.de/climate_environment/CDC/grids_germany/seasonal/",
        "air_temperature_mean/16_DJF/grids_germany_seasonal_air_temp_mean_188216.asc.gz")
tfile <- tempfile(fileext="airtemp.asc.gz")
download.file(link, tfile) # 0.2 MB
rfile <- R.utils::gunzip(tfile, remove=FALSE, skip=TRUE)

r <- terra::rast(rfile)
terra::crs(r) <- "EPSG:31467"
system.time(
rp <- terra::project(r, "+proj=longlat +datum=WGS84 +no_defs") # takes 100 seconds!
)

terra::plot(rp)
rdwd::addBorders() # optional for checking the projection - looks all good
```
This is on `R 4.3.0` with `raster 3.6-20`,` rgdal 1.6-7`, `sp 1.6-1`, `terra 1.7-29`.  
On my local `R 4.2.0` installation mid 2022 with `raster 3.5-15`,` rgdal 1.5-32`, `sp 1.5-0`, `terra 1.5-34`, it takes 1.4 seconds.  
The projection comes from the Description pdf file at <https://opendata.dwd.de/climate_environment/CDC/grids_germany/seasonal/air_temperature_mean>

Just for completeness, my original code was in raster and shows pretty much the same:
```r
r <- raster::raster(rfile)
proj <- "+proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0
         +ellps=bessel +datum=potsdam +units=m +no_defs"
proj <- sp::CRS(proj)
raster::projection(r) <- proj
raster::plot(r)
system.time(
rp <- raster::projectRaster(r, crs="+proj=longlat +datum=WGS84 +no_defs") # 96.2 vs 2.4 seconds
)
raster::plot(rp)
rdwd::addBorders()
```

**Comment by kadyb** [comment]
In the new version of `raster` you also see degradation or not? Because for me both `raster 3.6.20` and `terra 1.7.29` perform this operation in ~60 seconds on my PC. I see similar result in `stars::st_warp()` too:

```r
library("stars")
r <- read_stars(rfile, proxy = FALSE)
st_crs(r) <- "EPSG:31467"
system.time(
  rr <- st_warp(r, crs = st_crs("+proj=longlat +datum=WGS84 +no_defs"),
                use_gdal = TRUE, method = "bilinear", no_data_value = -999)
)
#>   user  system elapsed 
#>  62.65    0.04   62.69
```

In `terra::project()` you can set the number of threads too.

**Comment by kadyb** [comment]
Probably not problem with GDAL:

```r
system.time(
  sf::gdal_utils(util = "warp",
                 source = rfile,
                 destination = "test.tif",
                 options = c("-s_srs", "EPSG:31467",
                             "-t_srs", "+proj=longlat +datum=WGS84 +no_defs",
                             "-r", "bilinear")
  )
)
#>   user  system elapsed 
#>   2.94    0.02    2.95
```

**Comment by brry** [comment]
> In the new version of `raster` you also see degradation or not? 

yes, in the old version it took 2.4 seconds, now it is 96.2. Sorry, the comment in the initial post was not quite clear.

**Comment by brry** [comment]
setting gdal=FALSE does not change the time. setting threads=TRUE reduces the time to 40 secs on my machine.
parallel::detectCores() shows 4.

**Comment by rhijmans** [comment]
I get much better results on a PC. I am using the development vers

```
library(terra)
#terra 1.7.35
system.time(rp <- terra::project(r, "+proj=longlat +datum=WGS84 +no_defs") 
#   user  system elapsed 
#   0.84    0.11    1.03 

system.time(rp <- terra::project(r, "+proj=longlat +datum=WGS84 +no_defs", threads=T))
#   user  system elapsed 
#   1.33    0.14    0.61 
``` 

on an Ubuntu system with  

```
gdal(lib="")
#    gdal     proj     geos
# "3.7.0"  "9.2.0" "3.11.2"
packageVersion("terra")
#[1] ‘1.7.29’
```
I first got

```
#Warning messages:
#1: PROJ: Cannot open https://cdn.proj.org/de_adv_BETA2007.tif: Could not resolve host: cdn.proj.org (GDAL error 1)
#   user  system elapsed
#  0.474   0.008  10.480
```

But then 

```
#   user  system elapsed
#  0.866   0.004   0.871
```

**Comment by rhijmans** [comment]
The version of raster, rgdal, sp do not matter here as terra does not use them. But the versions of GDAL and PROJ _may_ be important.

**Comment by brry** [comment]
I updated to terra 1.7-35 and the issue has disappeared. It now reprojects in 0.6 / 0.8 seconds on my machine as well. I did not change anything else in between.

Thank you so much for finding out it works correctly in the development version again! (I feel slightly stupid for not trying that myself...)

**Comment by rhijmans** [comment]
If it is a consolation, you should know that I never tried this with the CRAN version. I just did, and I am really surprised to see that it is so much slower. I do not know why this is the case.
