### ISSUE TITLE
clarification on the use of focalPairs and focalReg

### ISSUE THREAD

**Issue by enricopisoni** [rspatial/terra#1182]
Dears

I have two rasters, related to emissions (raster1) and concentrations (raster2) in the atmosphere (both are 2-dimensional rasters).

for each area in raster2 (i.e. an area of 3x3 cells surrounding each cell in raster2) I want to compute the correlation between raster2 values (in the defined area) and the same area in raster1

then I would need to do the same, shifting raster1 of 1 cell to the left, then shifting raster1 of 2 cells, etc... always keeping raster2 fixed

is focalPairs useful for this purpose? or focalReg?

thanks for your help
bests
Enrico

**Comment by rhijmans** [comment]
I believe you can do the focal correlation with focalPairs, the shifting with a combination of shift, crop and extend
This is a how-to question. Please use stackoverflow.com (or similar) for that. Always include some simple (code-generated) example data.
