### ISSUE TITLE
Runtime failure when building with GCC 8

### ISSUE THREAD

**Issue by GreatEmerald** [rspatial/terra#1193]
I'm not sure if there is a way to improve it, but when attempting to install `terra` version 1.7-37 on CentOS 8 / Oracle Linux 8 that ships GCC 8.5, the compilation and linking seemingly goes fine, but dyn.load fails with a missing symbol error:

```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘terra’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object 'R/x86_64-redhat-linux-gnu-library/4.2/00LOCK-terra/00new/terra/libs/terra.so':
 R/x86_64-redhat-linux-gnu-library/4.2/00LOCK-terra/00new/terra/libs/terra.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv
Error: loading failed
Execution halted
ERROR: loading failed
```
It seems that it's using C++ capabilities that are not enabled by default on GCC 8. I tried to pass `-lstdc++fs` but the result was still the same. Switching to GCC 12 fixes the issue.

I'm a bit surprised that it manages to get this far, i.e. configure does not fail, and neither does linking fail. The configure output states:
```
configure: CXX: g++ -std=gnu++14
```
But the compilation and linking is using `gnu++17`:
```
g++ -std=gnu++17 -shared -L/usr/lib64/R/lib -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
  -o terra.so RcppExports.o RcppFunctions.o RcppModule.o arith.o crs.o distRaster.o distance.o extract.o
  file_utils.o focal.o gcp.o gdal_algs.o gdal_multidimensional.o gdalio.o geodesic.o geos_methods.o geosphere.o
  math_utils.o mediancut.o memory.o movingWindow.o ncdf.o ram.o raster_methods.o raster_stats.o rasterize.o read.o
  read_gdal.o read_ogr.o sample.o sort.o spatBase.o spatDataframe.o spatFactor.o spatRaster.o spatRasterMultiple.o
  spatSources.o spatTime.o spatVector.o spatVector2.o string_utils.o vecmath.o vecmathse.o vector_methods.o
  write.o write_gdal.o write_ogr.o -lproj -L/usr/lib64 -lgdal -L/usr/lib64 -lgeos_c -L/usr/lib64/R/lib -lR
```

So if GCC 8 is too old and not supported, ideally this would be caught by configure and a clear error message should be shown to that effect.

**Comment by rhijmans** [comment]
I have tried to fix this in the development version (https://github.com/rspatial/terra/issues/1191). Could you try with that version?

**Comment by GreatEmerald** [comment]
Yes, that works! I never thought I'd run into a 2-day-old but already fixed issue :)
