### ISSUE TITLE
Terra tempdir cannot handle "~"

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#1195]
You can set a `tempdir` in `terraOptions` that contains a "~" and it is considered valid (and is valid for other functions such as `writeRaster`); however this will lead to an error later on when the computer attempts to write temp files there. To avoid confusion perhaps have a call to `path.expand` internally as this solves the issue or throw an error saying the path cannot be used.

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.3.1
#> terra 1.7.38

if(!dir.exists("~/temp")){
  dir.create("~/temp")
}

terraOptions(tempdir=("~/temp"))

r<- rast(matrix(nrow = 10000, ncol=10000))
set.seed(5)
values(r)<- rnorm(ncell(r))

terrain(r)
#> Error: [terrain] path does not exist


terraOptions(tempdir=(path.expand("~/temp")))
terrain(r)
#> |---------|---------|---------|---------|=========================================                                          
#> class       : SpatRaster 
#> dimensions  : 10000, 10000, 1  (nrow, ncol, nlyr)
#> resolution  : 1, 1  (x, y)
#> extent      : 0, 10000, 0, 10000  (xmin, xmax, ymin, ymax)
#> coord. ref. :  
#> source      : spat_4DTcZdBbRm1vP2J_24864.tif 
#> name        :        slope 
#> min value   :  0.003808846 
#> max value   : 69.063812256
```

<sup>Created on 2023-06-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mdsumner** [comment]
it's a gdal thing it doesn't normalize the tilde but will create a directory of that name

**Comment by rhijmans** [comment]
Thanks; that was already done for filename arguments, but not for the tempdir.
