### ISSUE TITLE
memfrac limit not set by default?

### ISSUE THREAD

**Issue by MarcioFCMartins** [rspatial/terra#1196]
I ran into something which I don't know if it's intended behavior. If this is not intended behavior I'll try to create a reprex so we can diagnose it.

**Versions:**
terra: 1.7.29-1 on an Ubuntu-based OS (binary from the https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu/ ppa)
R:  4.3.0
OS: Pop!_OS 22.04 LTS

My goal is to create composites of partially overlapping rasters, similar to the `mosaic` method. However, I want to use a custom function for averaging the overlapping cells. To do so, I implemented the following workflow:

1. Read band *i* of all rasters
2. Create a `SpatRaster` of all bands i
3. Save to disk
4. Apply the `quantile` function to create composite of band i
5. Save band i composite to disk
6. Repeat 1 to 5 for all bands
7. Combine the composites of individual bands into the final `SpatRaster`
8. Save to disk

In the larger regions of interest, during step 4, my RAM would fill up, then all my Swap and eventually either the machine freezes or the process gets killed by the OOM. I found this odd, since `terraOptions` says that the memory usage shouldn't go above 0.6. I decided to try to set `terraOptions(memfrac = 0.5)` and now the program runs much better, with RAM rarely going above 50%.

My understanding is that, even without me ever running `terraOptions` command, the `memfrac`  should be set to 60% by default. However, it seems like this is not happening. Is it working as intended?

Thank you for a great library and your work!

**Comment by rhijmans** [comment]
it is hard to say from your description. But if you are using, for example, `stats::quantile` then you would be loading all values into memory and there is nothing that terra can do about that. This type of question is more suitable for stackoverflow.com
