### ISSUE TITLE
Error to install Terra in Rsutdio

### ISSUE THREAD

**Issue by SOCIENCEAC** [rspatial/terra#1198]
There is an error in Installing Terra in Rsutdio.
R version 4.2.2 (2022-10-31)

Rstudio Version:

version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          2.2                         
year           2022                        
month          10                          
day            31                          
svn rev        83211                       
language       R                           
version.string R version 4.2.2 (2022-10-31)
nickname       Innocent and Trusting       
> version()

-----------------------
> install.packages("terra")
Retrieving 'https://cran.rstudio.com/src/contrib/terra_1.7-39.tar.gz' ...
	OK [file is up to date]
Installing terra [1.7-39] ...
	FAILED
Error installing package 'terra':
=================================

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang -arch arm64
configure: CXX: clang++ -arch arm64 -std=gnu++14
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’

**Comment by rhijmans** [comment]
It is probably best not to install from source. But if you do, see the instructions here: https://github.com/rspatial/terra/
