### ISSUE TITLE
Why does terra::mask not work for select rasters and why does terra::rast change raster values from numeric to factor?

### ISSUE THREAD

**Issue by raruggie** [rspatial/terra#1199]
I am trying to clip a raster to a vector outline based on the workflow in this post: https://stackoverflow.com/questions/23073669/clipping-raster-using-shapefile-in-r-but-keeping-the-geometry-of-the-shapefile
While this post uses `raster::crop` and `raster::mask`, `terra` has the same functions (and is supposed to replace `raster`)

This workflow works for some of my raster's but not all of them and I cannot figure out why. Here is a reproducible example of two raster's that the crop + mask workflow does and does not work for:
```
library(streamstats) # devtools::install_github("markwh/streamstats")
library(FedData)
library(terra)
library(sf)
library(tidyverse)

#### Example of crop + mask working ####

# download the watershed boundary and convert to sf:

setTimeout(400)
ws1 <- delineateWatershed(xlocation = -77.51194, ylocation = 43.14500, crs = 4326,includeparameters = "false") # takes a minute to run
ws1_sp<-toSp(ws1, what = 'boundary') # also takes a minute to run
ws1_sf<-st_as_sf(ws1_sp)

# download the NLCD raster data:

nlcd<-get_nlcd(template = ws1_sf,label = 'IRONDEQUOIT CR ABOVE BLOSSOM RD NEAR ROCHESTER ',year = 2016)

# clip raster (crop + mask)

nlcd_crop<-crop(nlcd, raster::extent(as_Spatial(st_transform(ws1_sf, crs(nlcd)))))

nlcd_mask<-mask(nlcd_crop, as_Spatial(st_transform(ws1_sf, crs(nlcd))))

# look at clipped raster:

plot(nlcd_mask) # looks good!

#### Example of crop + mask NOT working (different watershed outlet coordinates) ####

# download the watershed boundary and convert to sf:

ws1 <- delineateWatershed(xlocation = -73.65167, ylocation = 42.93556, crs = 4326,includeparameters = "false") # takes a minute to run
ws1_sp<-toSp(ws1, what = 'boundary') # also takes a minute to run
ws1_sf<-st_as_sf(ws1_sp)

# download the NLCD raster data:

nlcd<-get_nlcd(template = ws1_sf,label = 'HUDSON RIVER AT STILLWATER, NY',year = 2016)

# clip raster (crop + mask)

nlcd_crop<-crop(nlcd, raster::extent(as_Spatial(st_transform(ws1_sf, crs(nlcd)))))

nlcd_mask<-mask(nlcd_crop, as_Spatial(st_transform(ws1_sf, crs(nlcd))))

# look at clipped raster:

plot(nlcd_mask) # no data

# if we look at the crop output step there is data:

plot(nlcd_crop)
```
As we can see the issue occurs in the `mask` step, but I don't know what is different between the two example raster's that causes no data to be returned. Also, note that I am using `raster::extent` in `terra::crop` because there is no `terra::extent`. If there is a more efficient way to clip a raster using a vector using `terra` please also let me know!

The second issue in the title, 'why does terra::rast change raster values from numeric to factor?' occurred when I looked for a solution to the first issue. A workaround to the first issue is to instead crop + mask a reprojected raster (instead of reprojecting the outline vector, which is what is being done above). I asked a stackoverflow question explaining the issue I am having with `terra::rast`: https://stackoverflow.com/questions/76533978/why-does-terrarast-change-raster-values-from-numeric-to-factor.

packageVersion("terra")
[1] ‘1.6.17’

I appreciate any help with this. Thank you.

**Comment by rhijmans** [comment]
stackoverflow is indeed the right place to ask about this

**Comment by raruggie** [comment]
I appreciate your response on SO but the issues are still unresolved. I first posted only the second half of this question on stackoverflow because I though that was the more interesting issue. However, I also wanted to open an issue on github with both parts of the question in case this was a bug in the `mask` function. _I am still looking for an answer as to why `mask` isn't working for no explainable reason, and why `rast` changes raster cell values_. I looked at the helpfile for `rast` and it is not clear in `?rast` why `rast` would have this behavior - I read all the arguments for `rast` and tried setting the logical arguments to both `TRUE` and `FALSE`  but it still changes the cell values. Also, it is not clear how `rast` is making the connection to the NLCD legend data and why it is putting Pasture/Hay backwards from its official title in the legend (I see in your output on SO that it is listed as Pasture/Hay but when I run the exact code chunk you posted on SO on my machine it is Hay/Pasture...no idea how, maybe something to do with alphabetical but they should be set character strings, right?). I know you are probably very busy, and maybe it is not clear from my SO and github posts what I am asking, but I would very much appreciate if you can take a second look at the issue here and on SO. Thank you for your time.

**Comment by rhijmans** [comment]
I do not think that rast changes values. It does not touch the labels and it certainly won't change "Pasture/Hay" to "Hay/Pasture".  I am guessing that you have some old cached data that wreak havoc.

**Comment by raruggie** [comment]
I don't know which download folder to clear out - I see that when I run `get_nlcd` the rasters are saved to a file in `AppData\\Local\\Temp\\Rtmp2vYBG8\\FedData\\1_NLCD_Land_Cover_2016.tif`. I tried emptying `AppData\\Local\\Temp`   (most of files deleted, including the `Rtmp2vYBG8` folder, but a few would not delete) but I am still seeing Hay/Pasture. Also, just in case this matters, the class for Barren Rock is different too. What do you suggest I do to fix this? Thank you in advance for your help.

**Comment by rhijmans** [comment]
My guess is that this is something funky with FedData. You could just download the nlcd files yourself. You can also ask them. It would be helpful to have an example that can be reproduced. Perhaps it depends on the area of interest?
