### ISSUE TITLE
Build Error, generic arguments isLonLat

### ISSUE THREAD

**Issue by wildintellect** [rspatial/terra#12]
After submitting pull request #11 hitting an error on the Check related to the generic definition of isLonLat. Not seeing an obvious issue with the generic definition.
```
Creating a new generic function for ‘hasValues’ in package ‘terra’
Creating a new generic function for ‘init’ in package ‘terra’
Creating a new generic function for ‘couldBeLonLat’ in package ‘terra’
Creating a new generic function for ‘cellFromRowColCombine’ in package ‘terra’
Error in rematchDefinition(definition, fdef, mnames, fnames, signature) : 
  methods can add arguments to the generic ‘isLonLat’ only if '...' is an argument to the generic
Error: unable to load R code in package ‘terra’
```
Should probably setup Travis for Terra to catch these much sooner.

**Comment by rhijmans** [comment]
I think this happens if you did not first update `raster`

**Comment by wildintellect** [comment]
Confirmed. terra requires raster > 2.9-5, suggest updating DESCRIPTION to require a higher raster version, currently lists ```raster (>= 2.9-5)``` which is too low.

**Comment by mdsumner** [comment]
You can also put

```DESCRIPTION
Remotes: rspatial/raster
```

which `devtools::install_github("rspatial/terra")` will use along with the version check.

**Comment by rhijmans** [comment]
This should no longer be an issue now with current (CRAN) raster >= 2.9-22, that `terra` depends on,.
