### ISSUE TITLE
Setting parameters for terra::plot

### ISSUE THREAD

**Issue by rupertoverall** [rspatial/terra#1204]
The plotting functions for `terra` objects are not using/setting plot parameters correctly.

Expected behaviour: the plot functions should use global settings by default or return global settings to their previous values if overridden.

Current behaviour: terra::plot only recognises parameters set via its own 'par' parameter and uses these to overwrite global settings.

```
custom.margins = c(1, 1, 1, 1)
par(mar = custom.margins)
par("mar") # The custom margins are now set globally...
# [1] 1 1 1 1

# ...but terra::plot does not use them...
poly = terra::vect(cbind(x = c(-1, 1, 1, -1, -1), y = c(1, 1, -1, -1, 1)), type = "polygons", crs = "local")
terra::plot(poly)	
par("mar") #...and even writes over the global settings.
# [1] 3.1 3.1 2.1 2.1

# Passing the custom margins as a parameter plots correctly...
terra::plot(poly, mar = custom.margins)	
par("mar") #...but again writes over the global settings.
# [1] 1 1 1 1

```

This is with terra version 1.7.39 and R version 4.3.0.
I use an M1 Mac (arm64) running MacOS 11.6.7

**Comment by rhijmans** [comment]
Your statement is not correct.  "mar" is an exception to the rule. That is by design, and for obvious reasons.
