### ISSUE TITLE
GDAL error in R, not reading raster (TIFF) by LERC compression 

### ISSUE THREAD

**Issue by robertodawid** [rspatial/terra#1205]
I am trying to read a TIFF file using the libraries raster or terra. In both cases, I was unable to read the TIFF file. The TIFF file has a LERC compression.
```

library(raster)
tif_file = 'GAEZ_V4/land_cover/09.tif'
tif_arr = raster(tif_file)
```

In any case, using one of the libraries, this error occurs:

```
Warning: C:/Users/xxx/land_cover/09.tif: Cannot open TIFF file due to missing codec LERC. (GDAL error 1)Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.
```
I tried using the raster library with other TIFF files (LZW compression), and it works. Link to the [TIFF](https://drive.google.com/file/d/1vF2PBR-x6J8MYVh5PWZN5xfwXxwkNLXF/view?usp=sharing)

**Comment by rhijmans** [comment]
The GDAL docs (https://gdal.org/drivers/raster/gtiff.html) state that 

> LERC and LERC_DEFLATE are available only when using internal libtiff for GDAL < 3.3.0. Since GDAL 3.3.0, LERC compression is also available when building GDAL against external libtiff >= 4.3.0, built itself against https://github.com/esri/lerc

It would seem that Rtools (used to compile the package on Windows) uses external libtiff; but does not use https://github.com/esri/lerc. I will ask the maintainer of Rtools for advice.

**Comment by rhijmans** [comment]
This now on windows when installing terra with the current version of RTools43 (thanks to a lot of work by Tomas Kalibera)

```
library(terra)
x <- rast("09.tif")
x
#class       : SpatRaster 
#dimensions  : 2160, 4320, 1  (nrow, ncol, nlyr)
#resolution  : 0.08333333, 0.08333333  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : 09.tif 
#name        : 09 

plot(r)
```

![lerc](https://github.com/rspatial/terra/assets/11481397/568c104b-5ecc-4b68-9811-0fa60d9c4d25)
