### ISSUE TITLE
errors on the first call to functions applied to terra outputs, not on the second call

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#121]
I get errors on the first call to several functions applied to `terra` outputs, but not on a second call, just after the first one. Here is the simplest code I could build in order to reproduce these errors:

```
library(terra)
# terra version 1.0.5

altFRA <- raster::getData('alt', country='FRA', mask=T) 
# Warning message:
# In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
#  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition

altFRA1 <- rast(altFRA*1) 

altFRA2 <- rast( gsub("grd$", "vrt", raster::filename(altFRA)) )  # no error afterwards if this line is not executed!!

plot(altFRA1)  # no error afterwards if this line is not executed!

v1 <- values (altFRA1) 

head(v1)  # error messages on the first call
# Error in x$.self$finalize() : attempt to apply non-function
# Error in (function (x)  : attempt to apply non-function
# Error in x$.self$finalize() : attempt to apply non-function
# Error in (function (x)  : attempt to apply non-function
# Error in (function (x)  : attempt to apply non-function
#      FRA_msk_alt
# [1,]          NA
# [2,]          NA
# [3,]          NA
# [4,]          NA
# [5,]          NA
# [6,]          NA

head(v1)    # no error messages on the second call!
#      FRA_msk_alt
# [1,]          NA
# [2,]          NA
# [3,]          NA
# [4,]          NA
# [5,]          NA
# [6,]          NA
```
I get the same messages with other function calls (`summary`...). These errors are not easy to isolate because their occurrence depends on the context, and in particular on the presence or absence of previous apparently unrelated lines. I think these messages come from a `terra` problem.

**Comment by rhijmans** [comment]
I think this is the same as https://github.com/rspatial/terra/issues/30

**Comment by jldupouey** [comment]
Thanks. I agree. The instability of the error message strongly suggests that it is related to garbage collector calls. But the fact that this error appears only for specific packages also suggests that it may be related to some inadequate memory or pointer management in those packages, revealed by the calls to gc. If this were not the case, the messages would appear much more often in R (and the problem would have already been solved).

Translated with www.DeepL.com/Translator (free version)

**Comment by jldupouey** [comment]
Thanks. I agree. The instability of the error message strongly suggests that it is related to garbage collector calls. But the fact that this error appears only for specific packages also suggests that it may be related to some inadequate memory or pointer management in those packages, revealed by the calls to gc. If this were not the case, the messages would appear much more often in R (and the problem would have already been solved).

**Comment by rhijmans** [comment]
What you say makes sense. The odd thing is that I see this in all packages in which I use a module. Also in the much simple cases like `Recocrop`, `Rwofost`, and `raster`. There are no pointers; but I must be missing something. It almost has to be something I do that is  different, and perhaps wrong.

**Comment by jldupouey** [comment]
I have no idea at all, because I know nothing about how libraries or of garbage collector work. Could it be related to https://stackoverflow.com/questions/57104634/rcpp-objects-seem-to-be-destroyed-by-rs-garbage-collector?

**Comment by rhijmans** [comment]
closing this because it is the same as #30
