### ISSUE TITLE
`plot` for SpatVector picks wrong column names

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1210]
When plotting scattered columns of a SpatVector, the column names that are used as titles for the maps are the first N column names in the attributes table, not the names of the actual columns that are plotted:

```
v <- vect(system.file("ex/lux.shp", package="terra"))

names(v)
# [1] "ID_1"   "NAME_1" "ID_2"   "NAME_2" "AREA"   "POP"

plot(v, c("NAME_1", "NAME_2"))
```
![Rplot](https://github.com/rspatial/terra/assets/12085508/452127f0-6541-408c-a173-76197870a79d)

**Comment by rhijmans** [comment]
Oops, thank you! Fixed.
