### ISSUE TITLE
Add ncells argument for global(x, fun=quantile)

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#1213]
In `terra` to get quantiles across cells for a layer you can use `terra::global(x, fun=quantile)`. In `raster` this was done using `raster::quantile`. For large rasters this can take a long time or fail since I believe determining quantiles requires reading all values into memory. `raster::quantile` had an `ncells` argument to allow for a random sample of a specified size to be used instead. Perhaps this could be added if `quantile` is used as the function, or perhaps even better as an argument to `global` more generally.

**Comment by rhijmans** [comment]
Thanks. `global` has a new argument "maxcell"
