### ISSUE TITLE
colorize(, "rgb") could be faster 

### ISSUE THREAD

**Issue by mdsumner** [rspatial/terra#1214]
Hi replacing this line of `subst()` 

https://github.com/rspatial/terra/blob/5f6f8be67e3d980be82f11319091e2311a4323ef/R/RGB.R#L184

with 

```R
out <- setNames(rast(x, vals = ct[values(x) + 1,-1], nlyrs = ncol(ct)-1), nms)
```

is quite a bit faster. I also think that `filename` and `overwrite` should be passed down there in the call to `subst()`?

I haven't navigated the details of `subst()` itself but perhaps that can be made faster at least for this case and I'll explore that 

tested with 

```R
dsn <- "/vsicurl/https://noaadata.apps.nsidc.org/NOAA/G02135/south/daily/geotiff/2023/06_Jun/S_20230628_concentration_v3.0.tif"
colorize(rast(dsn), "rgb")
```

**Comment by rhijmans** [comment]
Thanks. `filename` and `overwrite` are now not reset. I would not want to use this:

```
out <- setNames(rast(x, vals = ct[values(x) + 1,-1], nlyrs = ncol(ct)-1), nms)
``` 

Because it is not memory safe. If it is much faster than `subst`  the way to go could be to implement this substitution in C++, chunk by chunk, which should be easy enough.
