### ISSUE TITLE
Converting 3 band raster with write.raster yields 'blank' image

### ISSUE THREAD

**Issue by statslover123** [rspatial/terra#1219]
I am trying to convert a float 32 3 band raster (rgb) to 8 byte format, however, the output is blank in qgis and r

writeRaster(EX1, f, overwrite=TRUE, gdal=c("COMPRESS=NONE", "TFW=YES"), NAflag=0,datatype='INT1U')

**Comment by rhijmans** [comment]
Please use stackoverflow.com for general questions like this. But wherever you go, you need to provide more information. Ideally create a *minimal, self-contained, reproducible example*. If that is too difficult show your (minimal) code, and `show(input)` and `show(output)` (e.g. `show(EX1)`.
