### ISSUE TITLE
rast does not accept a matrix without any column name

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#122]
rast with parameter `type="xyz"` accepts as input a matrix in which only the longitude and latitude columns are named. In this case, the data column is automatically named "X":

```
library(terra) 
# terra version 1.0.5

Mat <- cbind(A=seq(1,100,1), B=seq(1,100,1), runif(100))
rast(Mat,type="xyz")
# class       : SpatRaster 
# dimensions  : 100, 100, 1  (nrow, ncol, nlyr)
# resolution  : 1, 1  (x, y)
# extent      : 0.5, 100.5, 0.5, 100.5  (xmin, xmax, ymin, ymax)
# coord. ref. :  
# source      : memory 
# name        :           X 
# min value   : 0.004967547 
# max value   :   0.9885646
```

But if no column name is given to the matrix, an error is generated by rast. This is perhaps inconsistent, since rast knows how to generate a column name by default (as in the case above), and the documentation indicates that it is the position (first and second) which defines the longitude and latitude columns.

```
Mat <- cbind(seq(1,100), seq(1,100), runif(100))
rast(Mat,type="xyz")
# Error : [names<-] incorrect number of names
```
The question holds whatever the number of layers.

**Comment by rhijmans** [comment]
Thank you very much, again!
