### ISSUE TITLE
Error when running terra::predict(). Caught exception 'std::bad_alloc' in function 'MakeADFunObject'

### ISSUE THREAD

**Issue by JingpengCao** [rspatial/terra#1223]
Hello,

I tried to use the predict() function in the terra package to make a prediction out of a glmmTMB result. I have 4 spatraster files in R environment and I stack them together as raster stack for the prediction. 1 of the 4 spatraster is categorical. I would post my code below. 

The error message I have received is: 
```
Error in MakeADFunObject(data, parameters, reportenv, ADreport = ADreport,  : 
  Caught exception 'std::bad_alloc' in function 'MakeADFunObject'
```
I actually have successfully run the prediction once when I am still trying things out. But then when I run the exact same code, this error occurred. 

From what I learned online, this could mean I run out of memory or storage, which is super weird. 
I have tried to clean the R memory and environment with gc() and rm(). I also tried to enlarge the memory size for R (which I do not know if I have succeeded in because I still have the same error after it). I have also updated the terra package to the newest one. Nothing helps.

The code I run:
```
envi <- c(dist_building, dist_road, dist_coast, habitat_type) 
#those are my rasters, and habitat_type is a categorical raster, which I define by terra::as.factor()
names(envi) <- c('dist_building','dist_road','dist_coast','habitat_type')

prediction_oland_tuned <- terra::predict(object = envi,
                                                                  model = model_oland_tuned, 
                                                                  type = "response", #I have also tried not to include this, did NOT help
                                                                  const = data.frame(ID=NA),
                                                                   re.form = NA)
```
Please help.... Thanks in advance.

**Comment by rhijmans** [comment]
I have tried to respond here: https://stackoverflow.com/a/76632821/635245
