### ISSUE TITLE
Linking to `SpatExtent` doc from `ext()` returns an error

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#1225]
1. Open RStudio.
2. Open `ext()`'s doc.
3. Click `SpatExtent` link in Value section.

The following error will appear in the dialog box and console:

`Error in base::args(object) : could not find function "Rcpp_SpatExtent"`

Maybe instead of `\code{\link{SpatExtent}}` it should be `\code{\link{SpatExtent-class}}`?

**Comment by rhijmans** [comment]
That looks like a bug in RStudio, triggered by the presence of 

```
\alias{Rcpp_SpatExtent-class}
```

**Comment by rhijmans** [comment]
Closing the issue here as it appears to be a R-Studio issue.
