### ISSUE TITLE
Is there the `sparse` argument in `relate()`?

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#1226]
In the `relate()` documentation we can see:

> na.rm -- logical. If TRUE and sparse=TRUE, geometries in x for which there is no related geometry in y are omitted

But is the `sparse` argument present in this function?

**Comment by rhijmans** [comment]
Thanks, presumably that was a remnant of an earlier version of `relate`

**Comment by tz05** [comment]
> Thanks, presumably that was a remnant of an earlier version of `relate`

I did some tests and found that "sparse" should be a typo of "pairs", which is an argument of `relate()`.

**Comment by rhijmans** [comment]
Thanks @tz05. Fixed by restoring and changing sparse" to "pairs".
