### ISSUE TITLE
Error: [writeRaster] invalid drive 

### ISSUE THREAD

**Issue by tobioke** [rspatial/terra#1227]
Hi there,

I tried to write an ASCII file but kept getting an error message that did not occur when I use the same code to write GTiff files. See below. After updating the packages the problem persists and I was wondering if this is a bug. 

`terra::writeRaster(elev, "elev.asc", filetype="ascii", overwrite=TRUE)`

> Error: [writeRaster] invalid driver

PackageVersion = terra 1.7.29
Operating system = Windows 11

The test data is here: https://drive.google.com/file/d/1lwyQWA6Pxw9AXTifeezH604SP0eEUcHz/view?usp=sharing

**Comment by rhijmans** [comment]
There is no driver called "ascii", so this is not a bug. This works

```
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
terra::writeRaster(r,  "elev.asc", overwrite=TRUE)
```
See: https://gdal.org/drivers/raster/index.html and `terra::gdal(drivers=TRUE)`

Please ask questions like this on stackoverflow.com and do not include links to files unless there is a specific issue with a particular file. Use example data like above.

**Comment by tobioke** [comment]
Thanks, Robert. 
I wasn't sure whether this is appropriate for SO as I have looked at the answers there and their code structures are identical to mine, especially when it was working for `GTiff` files. I suspect that Google was returning a code structure that is more appropriate to the `raster` package. The other stuff was just me following the default instruction from here.

**Comment by rhijmans** [comment]
No worries. I am just trying to keep this site manageable. The format you were looking for is "AAIGrid" but the extension should do it.
