### ISSUE TITLE
ext=c(1,2,1,2) within plotRGB returns error

### ISSUE THREAD

**Issue by DaveEdge1** [rspatial/terra#1228]
reproducible snippet:

"
coreImg <- terra::rast("https://github.com/nickmckay/specimR/raw/development/data/CORE_XYZ.tif")
terra::plotRGB(coreImg, r=2, g=4, b=6, stretch = "hist")
#plots without error
terra::plotRGB(coreImg, r=2, g=4, b=6, stretch = "hist", ext=c(1,2,1,2))
Error in if (hadWin) { : the condition has length > 1
"

I believe this error is new with the most recent update to Rcpp.

packageVersion("terra")
[1] ‘1.7.39’
packageVersion("Rcpp")
[1] ‘1.0.11’

OS: Windows 10

**Comment by DaveEdge1** [comment]
This error did not occur after I reverted to terra 1.7.3 and Rcpp 1.0.9.

Also, ext=c(368, 779, 13147, 13193) provides a valid cropping

**Comment by rhijmans** [comment]
Thanks. I can now (again) do 

```
terra::plotRGB(coreImg, r=2, g=4, b=6, stretch = "hist", ext=c(1200,1287,13150,13217))
```
