### ISSUE TITLE
relate() unexpected results with "contains" and "overlaps" 

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1238]
I have a polygon layer `u` and a bunch of other polygon layers, each of which I need to overlay to `u` -- here's a minimal example:
```
u <- vect("https://github.com/AMBarbosa/files/raw/main/u.gpkg")
b <- vect("https://github.com/AMBarbosa/files/raw/main/b.gpkg")

plot(u, axes = FALSE)
plot(b, col = "royalblue", add = TRUE)
text(crds(centroids(u)), labels = 1:length(u))
```
![image](https://github.com/rspatial/terra/assets/12085508/2b68c9de-b37b-4cae-a907-ed4f391ef423)

I need to select the white polygons of `u` that are partially or totally overlapped by (but not just touched by or adjacent to) blue polygons of `b` -- in this case, white polygons 2 and 5. Reading the `?relate` help file, I'd think the appropriate `relation` would be 'contains' or 'overlaps'. However, neither is giving me the expected result:
```
rel <- relate(u, b, relation = "contains")
yes <- rowSums(rel) > 0
plot(u[yes, ], density = 50, col = "darkred", add = TRUE)

# Error: [plot] SpatVector has zero geometries


rel <- relate(u, b, relation = "overlaps")
yes <- rowSums(rel) > 0
plot(u[yes, ], density = 50, col = "darkred", add = TRUE)

# adjacent polygons polygons also selected
```
![image](https://github.com/rspatial/terra/assets/12085508/607b85a0-f364-4d55-bfce-d5a68f9b0c53)

Am I missing something, or incorrectly interpreting the help file? I tried also with other options that sounded like they could get me what I need, e.g. "crosses", "covers", "coveredby", "within", as well as "DE-9IM" strings that seemed to aim for the same, but I always got the above undesired results.

Regards,

**Comment by AMBarbosa** [comment]
I now suspect that the borders of the polygons in layer `b`, most of which should perfectly overlap those in layer `u`, actually slightly invade the adjacent `u` polygons, which is causing the results above.

It seems to work more as expected if I create polygons whose borders overlap exactly where they should:

```
# make some polygons:
r <- rast(ncols = 3, nrows = 3, extent = c(0, 3, 0, 3))
p1 <- as.polygons(r)

# get a partially overlapping polygon:
vertices <- vect(crds(p1))
v2 <- vertices[c(22:24, 22), ]
plot(v2, col = "red", add = TRUE)
p2 <- as.polygons(as.lines(v2))

plot(p1, axes = FALSE)
plot(p2, col = "darkblue", add = TRUE)
```
![image](https://github.com/rspatial/terra/assets/12085508/4fadb618-88cd-4ea5-bb5a-9dee8c4a3243)

Now, to get the polygons of p1 that are overlapped (not just touched) by p2, it works as expected with "contains":
```
ovl <- relate(p1, p2, relation = "contains")
plot(p1[ovl, ], col = "orange", density = 30, add = TRUE)
```
![image](https://github.com/rspatial/terra/assets/12085508/8b974d62-0486-430f-a27e-193acc2decef)

But now "overlaps" returns zero geometries, which to me is still unexpected:
```
ovl <- relate(p1, p2, relation = "overlaps")
plot(p1[ovl, ], col = "red", density = 30, add = TRUE)
# Error: [plot] SpatVector has zero geometries
```

**Comment by rhijmans** [comment]
Hi, I *think* that is because (see https://en.wikipedia.org/wiki/DE-9IM) : 

> a overlaps b if they have *some* but *not all* points in common. 

In this case, all of p2 is also covered by p1, so that is a "contains", but not an "overlaps" (and the above suggests these relations are mutually exclusive).
