### ISSUE TITLE
rasterizeWin returns NaN values

### ISSUE THREAD

**Issue by fab4ap** [rspatial/terra#1239]
Here is the code - tried various combinations but does not work as expected (rasterize() works)
Terra version: 1.7.39
[rasterizeWin_files.zip](https://github.com/rspatial/terra/files/12083930/rasterizeWin_files.zip)

library(sf)
library(terra)

geo4326 = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
na_aea = "+proj=aea +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
rsp = read.csv("conus_s131_respall2.csv")
rsp = rsp[, c("lon","lat","rivo")]
rsps = st_as_sf(rsp, coords=c("lon","lat"), crs=st_crs(geo4326))
rspsa = st_transform(rsps, crs=st_crs(na_aea))
canusmex20kmsk = rast("canusmex20kmsk.tif")

canusmex20kmsk
class       : SpatRaster 
dimensions  : 378, 409, 1  (nrow, ncol, nlyr)
resolution  : 20000, 20000  (x, y)
extent      : -5105795, 3074205, -2951323, 4608677  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
source      : canusmex20kmsk.tif 
name        : canusmex20kmsk 
min value   :              1 
max value   :              1 

xyz = data.frame(st_coordinates(rspsa), rivo=rspsa$rivo)

summary(xyz)
       X                 Y                 rivo       
 Min.   :-120739   Min.   :-1261303   Min.   :  0.50  
 1st Qu.: 462225   1st Qu.: -935139   1st Qu.: 21.70  
 Median : 842783   Median : -767727   Median : 52.30  
 Mean   : 847623   Mean   : -740677   Mean   : 51.78  
 3rd Qu.:1263323   3rd Qu.: -607403   3rd Qu.: 81.70  
 Max.   :1720612   Max.   :  324427   Max.   :100.00 

rspsa
Simple feature collection with 18775 features and 1 field
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -120739.1 ymin: -1261303 xmax: 1720612 ymax: 324426.5
Projected CRS: +proj=aea +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs

# rasterize works
xr = rasterize(rspsa, canusmex20kmsk, field="rivo", fun="mean") 
> xr
class       : SpatRaster 
dimensions  : 378, 409, 1  (nrow, ncol, nlyr)
resolution  : 20000, 20000  (x, y)
extent      : -5105795, 3074205, -2951323, 4608677  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
source(s)   : memory
name        :  mean 
min value   :   1.1 
max value   : 100.0 

x = rasterizeWin(xyz, canusmex20kmsk, field="rivo", win="rectangle", pars=c(3,3), fun="mean", na.rm=T)
x = rasterizeWin(vect(rspsa), canusmex20kmsk, field="rivo", win="rectangle", pars=c(3,3), fun="mean", na.rm=T)

# NOTE:  Tried all combinations of fun= ;win= ;and pars= ; but still get NaN

x
class       : SpatRaster 
dimensions  : 378, 409, 1  (nrow, ncol, nlyr)
resolution  : 20000, 20000  (x, y)
extent      : -5105795, 3074205, -2951323, 4608677  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
source(s)   : memory
name        : canusmex20kmsk 
min value   :            NaN 
max value   :            NaN

**Comment by fab4ap** [comment]
I withdraw this issue - realized that pars needs to be in actual units - so if the cellsize is 20k, then pars for a rectangle of 4 x 4 cells should be 80000, 80000. This seems rather unintuitive to me. Should be clarified in the documentation as it is currently confusing....so, the foll. works:
x = rasterizeWin(xyz, canusmex20kmsk, field="rivo", win="rectangle", pars=c(80000, 80000), fun="mean", na.rm=T)
Thanks!

**Comment by rhijmans** [comment]
Suggestions for additional remarks in the docs are welcome.
