### ISSUE TITLE
Older GDAL rasterize support

### ISSUE THREAD

**Issue by bernorev** [rspatial/terra#124]
Hi,

I'm using terra package on shinyapps.io where the gdal version is still stuck at 2.2.2. The newest version (1.0.7) breaks when trying to use the rasterize fuction. The error is 

`Error : [rasterize] field value not found`

Is there a possibility to keep compatibility? 

Thanks!

**Comment by rhijmans** [comment]
Thanks for that report. I am testing on 2.2.3. 

```
library(terra)
gdal()
# [1] "2.2.3"

f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
r <- rast(v, ncol=75, nrow=100)

# this worked
x <- rasterize(v, r, "ID_2")
# but this failed 
y <- rasterize(v, r)
# and now works again
```
