### ISSUE TITLE
Make vrt() with multi-band rasters less opaque

### ISSUE THREAD

**Issue by sam-a-levy** [rspatial/terra#1244]
My goal is to produce a multi-band Virtual Raster Dataset using a set of multi-band tiles (each with identical band structure, i.e. same number, same names, and in the same order).

When I create the VRT with `vrt()` it appears to successfully combine the multi-band images as hoped for, but it does so in a highly opaque fashion. Specifically, the output bands are renamed and no information is provided on how the bands are compiled or what will occur if the tiles do not have identical band structures.

It would be great to have some control over this process, some information how it is executed in the `vrt()` function, and ideally the ability to retain band names.

I include a reproducible example below to illustrate my point.

```
#following vrt() example, create a raster then turn to tiles
r <-  rast(ncols=100, nrows=100,names="r1")
values(r) <- 1:ncell(r)

#adding the stage of creating an additional band & binding
r2 <- rast(ncols=100, nrows=100,names="r2")
values(r2) <- 1:ncell(r)*2
rr <- c(r,r2)

x <- rast(ncols=2, nrows=2)
filename <- paste0(tempfile(), "_.tif")
ff <- makeTiles(rr, x, filename)
ff

#create VRT
vrtfile <- paste0(tempfile(), ".vrt")
v <- vrt(ff, vrtfile)
v

# show structure of first tile
d <- rast(ff[[1]])
d
```

**Comment by kadyb** [comment]
`terra::vrt()` uses `gdalbuildvrt` as backend. You can find some information [here](https://gdal.org/programs/gdalbuildvrt.html).

**Comment by rhijmans** [comment]
You can now use argument `set_names`, as shown below:

```
v <- vrt(ff, vrtfile, set_names=T)
v
#class       : SpatRaster 
#dimensions  : 100, 100, 2  (nrow, ncol, nlyr)
#resolution  : 3.6, 1.8  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : file32082f5b1ca0.vrt 
#names       :    r1,    r2 
#min values  :     1,     2 
#max values  : 10000, 20000 
```
