### ISSUE TITLE
Documentation: extend a SpatExtent with algebraic notation example missing

### ISSUE THREAD

**Issue by jcoliver** [rspatial/terra#1245]
Reading the documentation for `extend()`:

> You can also enlarge a SpatExtent with this method, or with algebraic notation (see examples)

But I think the example is missing. Could add those two lines from the `raster::extend()` documentation (along with a third):

```
r <- rast(xmin=-150, xmax=-120, ymin=30, ymax=60, ncols=36, nrows=18)
e <- ext(r)
# Add 10 columns / rows on all sides
e + 10
# Double extent
e * 2
# Increase extent by 25%
e * 1.25
```

**Comment by rhijmans** [comment]
Thank you. Done as suggested.
