### ISSUE TITLE
Extract exact and weights not working for fun=table

### ISSUE THREAD

**Issue by aarongraybill** [rspatial/terra#1246]
Loving the `extract` function with `fun=table`. However, the function appears to be broken when specifying `exact` or `weights` as `TRUE`.

```R
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
v <- v[1:2,]

rf <- system.file("ex/elev.tif", package="terra")
x <- rast(rf)
extract(x, v,fun=table,weights=TRUE)
```

which gives the following error:

```
Error: [extract] if 'weights' or 'exact' is TRUE, you can only use functions mean, sum, min, max and table
```

Of course, I'm specifying table, so this seems like it should work!

I've tried this on both 1.7.41 (current GitHub version) and 1.7.39 (current CRAN release) with the same issue. Issue appears on both OS's i have access to, Linux GNU (R 4.1.3) and Windows (R 4.2.1).

**Comment by brownag** [comment]
In current terra I think passing function name as character e.g. `fun="table"` works with `exact` or `weights` whereas passing the raw function `fun=table` doesn't.  In other functions that take a `fun` argument, like `focal()`, function and name are handled equivalently so you are probably right to expect this would work

**Comment by rhijmans** [comment]
Thanks for reporting this. It should not work with both `fun=table` and `fun="table"`
