### ISSUE TITLE
Large negative values of  buffer widths can create possitive buffers

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#1247]
See the example below. I would think that example `b3` would result in empty geometry, and example `b4` would result in either empty geometry (and possibly a warning) or an error.

``` r
library(terra)
#> terra 1.7.41
v = vect(cbind(10, 10), crs = "+proj=merc")
b = buffer(v, 20)
b2 = buffer(v, -10)
b3 = buffer(v, -20)
b4 = buffer(v, -22)

plot(b, col = "lightgrey")
plot(b2, add = TRUE, border = "red")
plot(b3, add = TRUE, border = "yellow")
plot(b4, add = TRUE, border = "blue")
```

![](https://i.imgur.com/NCvv6xr.png)

**Comment by rhijmans** [comment]
Hi, did you mean to use `b` instead of `v`? As in

```
b2 = buffer(b, -10)
b3 = buffer(b, -20)
b4 = buffer(b, -22)
```

In which case you get an NA polygon for `b4`

```
b4  <- buffer(b, -22)
b4
# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 1, 0  (geometries, attributes)
# extent      : NaN, NaN, NaN, NaN  (xmin, xmax, ymin, ymax)
# coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
```

**Comment by Nowosad** [comment]
@rhijmans yes, you are right -- this solves the b4 case. 

However, 

1. for the "v" examples -- would it not be more proper to do not allow negative buffers for points (or at least return warnings in these cases)?

```
library(terra)
v = vect(cbind(10, 10), crs = "+proj=merc")
b = buffer(v, 20)
b2 = buffer(v, -10)
b3 = buffer(v, -20)
b4 = buffer(v, -22)
```

2.  for the "b" examples -- should not `b3` be empty here? It is a matter or setting a precision?

```
library(terra)
v = vect(cbind(10, 10), crs = "+proj=merc")
b = buffer(v, 20L)
b3 = buffer(b, -20L)
```

**Comment by rhijmans** [comment]
Thanks. Negative buffers on points and lines now return an error 

```
b2 = buffer(v, -1000)
#Error: [buffer] a negative buffer is only meaningful with polygons
``` 

As for `b3`. This indeed appears to be related to a loss of precision. 

```
buffer(b, -20.00000000000001)
# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 1, 0  (geometries, attributes)
# extent      : NaN, NaN, NaN, NaN  (xmin, xmax, ymin, ymax)
# coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
```

**Comment by Nowosad** [comment]
Thank you.

**Comment by simoncarrignon** [comment]
Sorry to re-open that but just wanted to ask a question about this:
https://github.com/rspatial/terra/blob/80120c3a84d7f61a859d3029ba69e5bd0b5bc1b8/src/geos_methods.cpp#L1109C4-L1110C6
 is there a reason why zero is considered as a negative value? it was handy to add buffer values in [0,+inf) on points, where zero can be use when nothing happened... I am happy to go with `<=0`,  if there is a good reason for it,  but it also sounded a bit weird to me that zero was considered as a negative value!
