### ISSUE TITLE
as.polygons results in clockwise polygons

### ISSUE THREAD

**Issue by srfall** [rspatial/terra#1249]
I'm not an expert on the wkt standard but as far as I am aware of, the exterior boundary of a polygon should be defined counter clockwise and many other applications require this format (e.g see the issue in rgbif here: ropensci/rgbif/issues/662).

Observed problem:
````r
terra::geom(terra::as.polygons(terra::ext(2, 18, 45, 55), crs = "+proj=longlat"), wkt = TRUE)
````

returns
`"POLYGON ((2 45, 2 55, 18 55, 18 45, 2 45))"`
which is clockwise, instead of the desired counter clockwise
`"POLYGON ((2 45, 18 45,18 55, 2 55,  2 45))"`

It looks like `as.polygons` is the cause:
````r
wkt_polygon_input <- "POLYGON ((2 45, 18 45,18 55, 2 55,  2 45))"

terra::geom(terra::as.polygons(terra::vect(wkt_polygon_input, crs = "+proj=longlat")), wkt = TRUE)
# "POLYGON ((2 45, 2 55, 18 55, 18 45, 2 45))"
# undesired result

terra::geom(terra::vect(wkt_polygon_input, crs = "+proj=longlat"), wkt = TRUE)
# "POLYGON ((2 45, 18 45, 18 55, 2 55, 2 45))"
# desired result

````

**Comment by edzer** [comment]
Some background on polygon orientation: https://github.com/r-spatial/sf/issues/2096

**Comment by rhijmans** [comment]
I have added a new method `forceCCW` that returns counter-clockwise polygons.

```
library(terra)
#terra 1.7.42
p <- terra::as.polygons(terra::ext(2, 18, 45, 55), crs = "+proj=longlat")
x <- forceCCW(p)

geom(p, wkt = TRUE)
#[1] "POLYGON ((2 45, 2 55, 18 55, 18 45, 2 45))"
geom(x, wkt = TRUE)
#[1] "POLYGON ((2 45, 18 45, 18 55, 2 55, 2 45))"

#Also see
plot(x, axes=F, border="azure", lwd=4)
text(as.points(x), 1:4)
```

It would be trivial to change the order returned by `as.polygons<SpatExtent>`  to CCW if that is helpful.
