### ISSUE TITLE
terra vect function does not correctly read XYZ (or XYM) data

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#125]
```
# building and writing a simple polygon 
pts1 <- matrix(c(0,0,10,0,0,10,0,0),ncol=2, byrow=TRUE)
pol1 <- st_sfc(st_polygon(list(pts1)))
st_write(pol1,"test1.shp",append=FALSE)
# Writing layer `test1' to data source `test1.shp' using driver `ESRI Shapefile'
# Writing 1 features with 0 fields and geometry type Polygon.

# correctly read by terra::vect
vect("test1.shp")
#  class       : SpatVector 
#  geometry    : polygons 
#  dimensions  : 1, 1  (geometries, attributes)
#  extent      : 0, 10, 0, 10  (xmin, xmax, ymin, ymax)
# coord. ref. : +proj=longlat +datum=WGS84 
#  names       :   FID
#  type        : <num>
#  values      :     0

# make and write an XYZ polygon
pts2 <- cbind(pts1, 0)
pol2 <- st_sfc(st_polygon(list(pts2), "XYZ"))
st_write(pol2,"test2.shp",append=FALSE,layer_options="SHPT=POLYGONZ")
# Writing layer `test2' to data source `test2.shp' using driver `ESRI Shapefile'
# options:        SHPT=POLYGONZ 
# Writing 1 features with 0 fields and geometry type 3D Polygon.

# not correctly read (extent is false)
vect("test2.shp")
#  class       : SpatVector 
#  geometry    : polygons 
#  dimensions  : 1, 1  (geometries, attributes)
#  extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#  coord. ref. : +proj=longlat +datum=WGS84 
#  names       :   FID
#  type        : <num>
#  values      :     0
```

I suppose terra does not support XYZ/M data but, when reading such files, either an error should be thrown, or (preferably), the file should be (correctly) read and Z/M values dropped (with ou without a warning)? 

Such XYZ vector data are commonly found now, e.g. in Google Earth outputs.

**Comment by rhijmans** [comment]
Thanks, this example now works; although terra indeed ignores Z/M values but that should change soon. As you say, at minimum a warning should be given --- and I will keep this issue open for that.

**Comment by rhijmans** [comment]
I now get

```
library(sf)
pts1 <- matrix(c(0,0,10,0,0,10,0,0),ncol=2, byrow=TRUE)
pts2 <- cbind(pts1, 0)
pol2 <- st_sfc(st_polygon(list(pts2), "XYZ"))
st_write(pol2,"test2.shp",append=FALSE,layer_options="SHPT=POLYGONZ")

library(terra)
v <- vect("test2.shp")
#Warning message:
# [vect] Z coordinates ignored
```

I may, of course, be better to just read the Z/M values. And I will eventually do that. I am not too inspired as I never use them, so if anyone out there would really like to have them, let me know.

**Comment by consumere** [comment]
having this kml structure, provided by ClimateExplorer:
(https://climexp.knmi.nl/) 
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
<Document>
<name>data/plotlist3919984.txt</name>
<LookAt>
<longitude>  10.655</longitude>
<latitude>  49.770</latitude>
<range>    275000.000</range>
</LookAt>
<Placemark>
<name>BAMBERG (DE)</name>
<Point><coordinates>
   10.9200,   49.8800,    0.0000
</coordinates></Point>
<description><![CDATA[
<a href="http://climexp.knmi.nl/becawspd.cgi?id=someone@somewhere&WMO=40&STATION=BAMBERG (DE)">becawspd</a>
]]></description>
</Placemark>
<Placemark>
<name>MEININGEN (DE)</name>
<Point><coordinates>
   10.3800,   50.5600,    0.0000
</coordinates></Point>
<description><![CDATA[
<a href="http://climexp.knmi.nl/becawspd.cgi?id=someone@somewhere&WMO=486&STATION=MEININGEN (DE)">becawspd</a>
]]></description>
</Placemark>
</Document>
</kml>

i get: 
x='D:/ClimateExplorer/windspeed/tst.kml'
pt = vect(x)
crds(pt)

x	y
10.92	0
10.38	0
