### ISSUE TITLE
rast(array(1)) uses entire system memory

### ISSUE THREAD

**Issue by andreimirt** [rspatial/terra#1254]
obviously, array(1) was not my real data, but when trying to use an array to create a SpatRaster, it tried to use the entire system memory, and the entire pagefile. (128GB x 2)
Interestingly enough, it didn't crash the system, as the memory went down, and then up again.
I am running windows 10, R 4.3.1, and terra 1.7.39
Code to reproduce is simply ```rast(array(1))```

**Comment by andreimirt** [comment]
by looking at the source code of rast, it's obvious that I'm misusing it, as it's supposed to handle mutidimensional arrays.
I was hoping to be able to give rast a list of values, an extent, and optionally a crs, and rast to figure that I want those values arranged uniformly inside the extent.

Instead, it caused an unintended DOS attack on my PC.

**Comment by andreimirt** [comment]
I pulled the code for rast for "array" signature using `getMethod(rast,"array")` and it showed me the following code:

```
function (x, ...) 
{
    .local <- function (x, crs = "", extent = NULL) 
    {
        dims <- dim(x)
        if (length(dims) > 3) {
            if (length(dims) == 4) {
                if (dims[4] == 1) {
                  x <- x[, , , 1]
                }
                else {
                  error("rast,array", "rast cannot handle an array with 4 dimensions (try 'sds')")
                }
            }
            else {
                error("rast,array", "cannot handle an array with more than 3 dimensions")
            }
        }
        r <- methods::new("SpatRaster")
        if (!is.null(extent)) {
            e <- as.vector(extent)
        }
        else {
            e <- c(0, dims[2], 0, dims[1])
        }
        crs <- character_crs(crs, "rast")
        r@ptr <- SpatRaster$new(dims, e, crs)
        values(r) <- x
        messages(r, "rast")
    }
    .local(x, ...)
}
<bytecode: 0x000001eeec3ee2d0>
<environment: namespace:terra>

Signatures:
        x      
target  "array"
defined "array"
```

Then I tried to figure this function so that it works as I explained, and I came up with this modified version:

```
function (x, ...) 
{
  .local <- function (x, crs = "", extent = NULL) 
  {
    dims <- dim(x)
    if (length(dims)==1){
      x <- array(x,c(1,dim(x)))
    }
    if (length(dims) > 3) {
      if (length(dims) == 4) {
        if (dims[4] == 1) {
          x <- x[, , , 1]
        }
        else {
          error("rast,array", "rast cannot handle an array with 4 dimensions (try 'sds')")
        }
      }
      else {
        error("rast,array", "cannot handle an array with more than 3 dimensions")
      }
    }
    r <- methods::new("SpatRaster")
    if ((length(dim)==1) & (!is.null(extent))) {
      sizex <- (e[2]-e[1])
      sizey <- (e[4]-e[3])
      resolution <- sqrt(sizex * sizey / length(x))
      dimx <- roundup(sizex/resolution)
      dimy <- roundup(sizey/resolution)
      x <- array(x,c(dimx,dimy))
    } else if (!is.null(extent)) {
    e <- as.vector(extent)
    }
    else {
      e <- c(0, dims[2], 0, dims[1])
    }
    crs <- terra:::character_crs(crs, "rast")
    r@ptr <- terra:::SpatRaster$new(dims, e, crs)
    terra:::values(r) <- x
    messages(r, "rast")
  }
  .local(x, ...)
}
```
but then I looked into the actual source code of R/SpatRasterDataset.R and it looks nothing like above. I noticed that github doesn't have the latest version available on cran, i.e. 1.7-39, so I went to cran and downloaded that, but that looks like the version here on github. Then I searched the code on google and figured that somehow what I'm using is version 1 of terra, although, it definitely says 1.7-39 when loading. Moreover, no matter how many times I reinstall the package, the behaviour doesn't change.

I have no clue what's going on, but it may be that this is a non-issue in version 1.7-39, if I am actually running version 1, only shown as version 1.7-39.

I'll try on a different machine and see what I get.

**Comment by rhijmans** [comment]
Thanks for reporting this. Very ugly. I now get:

```
library(terra)
#terra 1.7.41
rast(array(1))
#Error: [rast,array] cannot handle an array with less than 3 dimensions
``` 

I do not fully understand what functionality you are looking for; but I would be happy to look at that if you can clarify.
