### ISSUE TITLE
The console cursor is not positioned correctly after the progress bar is displayed

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#126]
After calling the writeRaster function with progress bar, the cursor in console does not come back to the first column of the display area. It stays stuck there, even after keyboard carriage returns or a console clearing. It is not convenient and requires a restart of R if you want to return to a correct display. Perhaps some \r\n\b not properly used within or after progress bar calls? 

> r=rast(nrows=100, ncols=100) 
> values(r)=0
> writeRaster(r,"test.tif",overwrite=T,wopt=list(progress=1))

![image](https://user-images.githubusercontent.com/42430070/104248086-22f96100-5469-11eb-8d2d-92bd0eea0407.png)

**Comment by rhijmans** [comment]
There was a shortcut in writeRaster that was fine, except for the progress bar. Seems to work OK again. Thank you very much

**Comment by jldupouey** [comment]
I find the same problem with the aggregate function.
