### ISSUE TITLE
Mosaic fails since 1.7.39 (at least)

### ISSUE THREAD

**Issue by Jean-Romain** [rspatial/terra#1262]
The following MRE is working with `1.7.29` but returns incorrect output with `1.7.39`

```r
library(terra)

x1 <- rast(xmin=-110, xmax=-60, ymin=40, ymax=70, res=1, vals=1)
x2 <- rast(xmin=-110, xmax=-60, ymin=40, ymax=70, res=1, vals=2)
x  <- c(x1, x2)

y1 <- rast(xmin=-95, xmax=-45, ymax=60, ymin=30, res=1, vals=3)
y2 <- rast(xmin=-95, xmax=-45, ymax=60, ymin=30, res=1, vals=4)
y  <- c(y1, y2)

m1 <- mosaic(x, y)
m1
```

`1.7.29` 

```
class       : SpatRaster 
dimensions  : 40, 65, 2  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -110, -45, 30, 70  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
source(s)   : memory
names       : lyr.1, lyr.1 
min values  :     1,     2 
max values  :     3,     4 
```

`1.7.39` 

```
class       : SpatRaster 
dimensions  : 40, 65, 2  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -110, -45, 30, 70  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
source(s)   : memory
names       : lyr.1, lyr.1 
min values  :   1.5,   1.5 
max values  :   3.5,   3.5 
```

**Comment by cnrakt** [comment]
I recently encountered an issue with the mosaic function also. When trying to combine a list of SpatRaster objects using mosaic, I noticed that the resulting raster exhibited unexpected shifts, duplicated patterns, , and introduced incorrect noise pixels that were not present in the original rasters. To further investigate the issue, I compared the output with the merge function and found the results from merge to be correct, whereas mosaic exhibited the described errors.

rsrc <- sprc(r_lis_filtered)
resul <- mosaic(rsrc, fun = "sum") 

I also try looping over a common extent for the rasters (r_lis_filtered) than employing the mosaic function: 

resul <- terra::rast(extent = cumulative_extent, res = 0.05)
    rl <- length(r_lis_filtered)
    for(i in 1:rl) {
        resul <- mosaic(resul, r_lis_filtered[[i]], fun = "sum")
    }

However, this approach also yielded the same errors.  I can share, "r_lis_filtered" list and  screenshots to illustrate the discrepancies between the two functions. I hope this report helps in identifying and fixing the potential bug in the mosaic function. Thanks for your time and consideration! 
Best, Caner
