### ISSUE TITLE
Filter raster by taking the max of a Gaussian filter

### ISSUE THREAD

**Issue by nikosGeography** [rspatial/terra#1264]
I have a raster which I applied a Gaussian filter. By "default", the Gaussian filter, takes the mean within the kernel. How can I take the max, instead of the mean, within the kernel? Here is how I applied the Gaussian filter:

```
library(terra)

wd = "test/"

dem = rast(paste0(wd, "dem.tif")) # my original raster

gf <- focalMat(dem, 0.5*30, "Gauss")
r_gf <- focal(dem, w = gf, na.rm = TRUE)
```
The raster I am using:

```
class       : SpatRaster 
dimensions  : 487, 538, 1  (nrow, ncol, nlyr)
resolution  : 29.97561, 29.97126  (x, y)
extent      : 330330.3, 346457.2, 4451378, 4465974  (xmin, xmax, ymin, ymax)
coord. ref. : GGRS87 / Greek Grid (EPSG:2100) 
source      : dem.tif 
name        :       dem 
min value   :  144.7688 
max value   : 2169.7751 
```
I am using `R` 4.3.1 and `RStudio` 2023.06.1 Build 524.

I asked the same question on GIS SE but I haven't received an answer yet.

**Comment by rhijmans** [comment]
The instructions state:

> When reporting a bug, please include a minimal, self-contained example that reproduces the problem 

But since this is an "how-to" question, it is indeed more appropriate for SO or SE. 

I think you can use `fun=max`
