### ISSUE TITLE
Inconsistent behaviour between documentation and function `clamp` - also possibly with raster package

### ISSUE THREAD

**Issue by gdrouart** [rspatial/terra#1278]
Hi! I have an inconsistent behaviour with the `clamp` function. Doc report as `NA` but `NaN` is reported. Note: raster package is returning NA (see second snippet).

terra version: 1.7-23
R version: 4.2.1
os: Ubuntu 22.04.3 LTS

Minimum reproducible example:
```R
library(terra)
empty_raster <- terra::rast(extent = terra::ext(-1, 1, 4, 5), resolution = 1/20)
set.seed(1)
filled_raster <- terra::init(empty_raster, fun = runif)
clamped_raster <- terra::clamp(filled_raster, lower = 0.2, upper = 0.8, values = FALSE)
min(clamped_raster)
```

For ease of comparison:
```R
library(raster)
empty_raster <- raster::raster(ext = raster::extent(c(-1, 1, 4, 5)), resolution = 1/20)
set.seed(1)
filled_raster <- raster::init(empty_raster, fun = runif)
clamped_raster <- raster::clamp(filled_raster, lower = 0.2, upper = 0.8, useValues = FALSE)
min(clamped_raster)
```

**Comment by rhijmans** [comment]
You are not showing any `NaN` or `NA` values, so I am not sure what you refer to. I am guessing you were using `values`, and I have updated the manual so that it now says that you get `NaN` (unless you use `dataframe=TRUE`)
