### ISSUE TITLE
Inconsistent behaviour for `mask` function

### ISSUE THREAD

**Issue by gdrouart** [rspatial/terra#1279]
I observe some inconsistencies between documentation and behaviour. Note: similar issue exist with raster package.

terra version: 1.7-23
R version: 4.2.1
os: Ubuntu 22.04.3 LTS

Minimum workable example: 
```R
library(terra)
library(testthat)
empty_raster <- terra::rast(extent = terra::ext(-1, 1, 4, 5), resolution = 1/20)
filled_raster <- terra::init(empty_raster, fun = runif)

mask <- filled_raster < 0.4
masked_raster <- terra::mask(filled_raster, mask)
testthat::expect_equal(masked_raster, filled_raster) # is successful

masked_raster <- terra::mask(filled_raster, mask, maskvalue = 100)
testthat::expect_equal(masked_raster, filled_raster) # is successful

masked_raster <- terra::mask(filled_raster, mask, maskvalue = TRUE) # inconsistency, see below
testthat::expect_equal(masked_raster, filled_raster) # is failing

```
In the `?mask` the `maskvalue` is indicated as a "numeric", not as a logical. see also `clamp` function behaviour.

**Comment by rhijmans** [comment]
In R, logical values are generally accepted where a numerical value is expected (FALSE is equivalent to 0 and TRUE is equivalent to 1). For example:

```
TRUE + TRUE
#[1] 2
```

**Comment by gdrouart** [comment]
Alright, got it. Thanks!
