### ISSUE TITLE
The asc file generated using writeRaster in terra cannot be read by VB6

### ISSUE THREAD

**Issue by tlwang2022** [rspatial/terra#1282]
I can use VB6 to read the values of the ASC file generated by writeRaster in raster. However, the ASC file generated by writeRaster in terra cannot be read by VB6. It reads the entire file using either "Input" or "Line Input" function.

**Comment by rhijmans** [comment]
There is not much I can do with a comment like this. Unless you can *show* something that suggests otherwise, the problem would seem to be with your VB6 code.

**Comment by tlwang2022** [comment]
Thanks for your quick response. Here are more details of the issue.

Line Reading the ASC file generated by raster:
![raster](https://github.com/rspatial/terra/assets/111156236/6513162b-a7f6-43e8-ab3f-320a4011d330)
It can correctly read the first line of the ASC file.

Line Reading the ASC file generated by terra:
![terra](https://github.com/rspatial/terra/assets/111156236/36e06edc-07ac-4457-9da1-5d51a8769c09)
It reads the entire ASC file into a single string.
