### ISSUE TITLE
draw() function does not align correctly in RStudio display.

### ISSUE THREAD

**Issue by matthewseanmarcus** [rspatial/terra#1283]
When clicking on an image in RStudio with draw(), say after running plotRGB(x, ...), the points clicked are offset from where they should be. This problem disappears when the image is plotted after running dev.new(), but this creates its own issues.

**Comment by rhijmans** [comment]
I believe this is a bug in RStudio. There is not much I can do about that. See https://github.com/rstudio/rstudio/issues/12682
