### ISSUE TITLE
The ASC file generated using writeRaster cannot be correctly read by VB6

### ISSUE THREAD

**Issue by tlwang2022** [rspatial/terra#1284]
I can use VB6 to read the values of the ASC file generated by writeRaster in raster. However, the ASC file generated in terra cannot be correctly read by VB6. For example,

Line Input the ASC file generated by raster:
![raster](https://github.com/rspatial/terra/assets/111156236/1a5f92f4-a8b7-431c-b273-a69bfadaa5c9)
It can correctly read the first line of the ASC file.

Line Input the ASC file generated by terra:
![terra](https://github.com/rspatial/terra/assets/111156236/8c4a2bc6-01d1-4b34-bbcb-b9eab12f504c)
It reads the entire ASC file into a single string. Even I use the Input function to read a single value, it also reads the entire file.

**Comment by rhijmans** [comment]
Again, I cannot fix your VB code. Apparently it is expecting a different EoL character. Probably windows (CR LF) vs linux (LF) convention.

**Comment by tlwang2022** [comment]
I see. But the same VB code works with _raster_ ASC but not the _terra_ ASC. 
Thanks for your amazing package anyway.
