### ISSUE TITLE
Remotes::install_github failed

### ISSUE THREAD

**Issue by fang19911030** [rspatial/terra#1285]
My R version is 4.0.3

I used remotes::install_github("rspatial/terra") for installation.

Here is my error, which doesn't provide so much useful information 
```
> remotes::install_github("rspatial/terra")
Downloading GitHub repo rspatial/terra@HEAD
Error: Failed to install 'terra' from GitHub:
  $ operator is invalid for atomic vectors
In addition: Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'terra' is missing or broken
```

**Comment by rhijmans** [comment]
Your R version is three years old (October 2020). You are not reporting your operating system. If you are on windows you should be able to install from the R-universe (see instructions on this site).
