### ISSUE TITLE
rast() reads ncdf file incorrect

### ISSUE THREAD

**Issue by BGWKlein** [rspatial/terra#1289]
I tried to read a ncdf file using 
`ras <- terra::rast("tp_GPCC_25_ltmonsum_1951_2000.nc") `
and the y dimensions is not interpreted correctly.
Plotting the first layer 
`plot(ras[[1]]`
leads to the following result:
![terra](https://github.com/rspatial/terra/assets/62026436/0d6ce53f-c540-404d-acab-0d56c3d6cc8e)
If I plot the first layer with the external ncdf viewer panoply I get the following figure (which seems correct to me):
![panoply](https://github.com/rspatial/terra/assets/62026436/f43befcc-5c1a-4689-849f-0c86db074e61)

NCDF-Data could be downloaded from:
https://www.dropbox.com/scl/fi/fybz1w514y3issi94q4yu/tp_GPCC_25_ltmonsum_1951_2000.nc?rlkey=azwxekzq8rn1woc67x804uaww&dl=0
[](https://www.dropbox.com/scl/fi/fybz1w514y3issi94q4yu/tp_GPCC_25_ltmonsum_1951_2000.nc?rlkey=azwxekzq8rn1woc67x804uaww&dl=0)

I am using R version 4.3.1 with terra version 1.7-46 on windows

**Comment by kadyb** [comment]
It looks like this file can be loaded correctly by `{raster}` package. Surprisingly, converting `RasterBrick` to `SpatRaster` also results in vertically inverse pixel layout.

**Comment by rhijmans** [comment]
The difference between "terra" and "raster" is that "terra" uses GDAL to read ncdf, whereas raster does not. 
This may be a GDAL problem and I will report it there. 
 
Here are two work-arounds:

```
f <- "tp_GPCC_25_ltmonsum_1951_2000.nc"
library(raster)
library(terra)
setGDALconfig("GDAL_NETCDF_BOTTOMUP", "no")
x <- rast(f)

# or read with raster and force to memory before coercing to a SpatRaster
r <- rast(brick(f) + 0)
```

**Comment by rhijmans** [comment]
The conclusion is that terra/GDAL does not get this as expected because the file does not follow the CF conventions. It is of course nice that 'raster' and 'panoply' work around that, but GDAL does not. Even Roualt suggested the best work-around for this case:

```
f <- "tp_GPCC_25_ltmonsum_1951_2000.nc"
library(terra)
x <- rast(f, opts="IGNORE_XY_AXIS_NAME_CHECKS=YES")
```

**Comment by BGWKlein** [comment]
Great thanks for the detailed answers and the workarounds, shame on me I didn't follow the CF conventions when writing the file.
