### ISSUE TITLE
rast on a list is memory hungry

### ISSUE THREAD

**Issue by BastienFR** [rspatial/terra#129]
I have a list of 365 `SpatRaster` layers of matched 245*207 layers.  When I stack them with `rast` it's using over 32 gb of Ram.  Same process doesn't seems to use memory in raster.

Example:

characteristic my raster:

```
nr=245   # number of rows
nc=207  # number of columns 
nd=200  # number of days (layers), I officially have 365, but for the sake of the example I reduced it
```

Doing it with `terra`

```
list_terra_layer <- lapply(1:nd, function(dd){
  set.seed(dd)
  one_terra_layer <- terra::rast(nrows=nr,ncols=nc)
  terra::values(one_terra_layer) <- runif(nr*nc) 
  one_terra_layer
})

system.time(terra_brick <- terra::rast(list_terra_layer))

```
![image](https://user-images.githubusercontent.com/10979480/104501287-81c7f300-55ad-11eb-851f-e2c153306c88.png)

Doing it with raster is faster and leads to no memory consumption:

```
list_raster_layer <- lapply(1:nd, function(dd){
  set.seed(dd)
  one_raster_layer <- raster::raster(nrows=nr,ncols=nc)
  raster::values(one_raster_layer) <- runif(nr*nc) 
  one_raster_layer
})

library(raster)
system.time(raster_brick <- do.call("brick", list_raster_layer))
```

![image](https://user-images.githubusercontent.com/10979480/104501592-ec792e80-55ad-11eb-8f08-eabe290f537d.png)

Is there a way to do this task in `terra` without using as much memory?  Thanks

**Comment by rhijmans** [comment]
With the last update, I now get 

```
library(terra)
r_terra <- terra::rast(nrows=245,ncols=207)
set.seed(200)
x <- lapply(1:200, function(i) {
  setValues(r_terra, runif(ncell(r_terra))) 
})

system.time(y <- terra::rast(x))
#   user  system elapsed 
#   0.03    0.03    0.06 
```

Which is about 100 times faster than before. 

There may be more to do, and there was a [similar issue](https://github.com/rspatial/terra/issues/86) before, that got closed prematurely.
