### ISSUE TITLE
`time` function does not give correct information

### ISSUE THREAD

**Issue by liushlcn** [rspatial/terra#1291]
I have an NC file as uploaded, I tried to extract the date information using the `time` function in terra, version terra_1.7-46. However, I get the values that attribute to `numeric`, not as expected `Date`. [cdo](https://code.mpimet.mpg.de/projects/cdo) gives the correct date information. If some bugs exist here?
```{r}
library(terra)
rc <- rast("mrso_CESM2-WACCM_ssp245.nc")
time(rc) |> class()
```
```cdo
cdo showdate mrso_CESM2-WACCM_ssp245.nc
```

[mrso_CESM2-WACCM_ssp245.zip](https://github.com/rspatial/terra/files/12724498/mrso_CESM2-WACCM_ssp245.zip)

**Comment by kadyb** [comment]
You probably need to do the conversion yourself to read the dates correctly.

```r
f = "mrso_CESM2-WACCM_ssp245.nc"
describe(f)
#>  [99] "  time#units=minutes since 2015-01-15T11:45:00"

r = rast(f)
as.POSIXct(time(r), origin = "2015-01-15 11:45:00")
#>  [1] "2016-06-15 15:45:15 CEST" "2016-06-16 03:33:15 CEST"
#>  [3] "2016-06-16 15:21:15 CEST" "2016-06-17 03:33:15 CEST"
#>  ...
```

Check if these dates are correct, because I'm not sure.

**Comment by kadyb** [comment]
To this line:

```r
origin.pcict <- as.PCICt(strsplit(time.units, ' ')[[1]][3], cal=time.calendar)
```

try adding time formatting:

```r
origin.pcict <- as.PCICt(strsplit(time.units, ' ')[[1]][3], cal=time.calendar, format = "%Y-%m-%dT%T")
```

**Comment by liushlcn** [comment]
```
origin.pcict <- as.PCICt(strsplit(time.units, ' ')[[1]][3], cal=time.calendar, format = "%Y-%m-%dT%T")
```
thanks @kadyb 
If the time format is not the same as the [file](https://github.com/rspatial/terra/files/12724498/mrso_CESM2-WACCM_ssp245.zip) we just upload. we can not set the correct format and get the correct time. 

For the `time` function in `terra`, see the script below and the source [code](https://github.com/rspatial/terra/blob/5363b7b1cd6ca40ee58ed94aae7f8532e2d24f5f/R/time.R#L105C12-L105C17
) , `timestep` has attributions including seconds, days, ..., while `minutes` will return as `raw`.

@rhijmans do you have any plans to add support for timestep as `minutes` in the `time` function?
```
> library(terra)
> packageVersion("terra")
[1] '1.7.46'
> rc = rast("mrso_CESM2-WACCM_ssp245.nc")
> s = rc@pnt
> s$hasTime
[1] TRUE
> s$timestep
[1] "raw"
```

**Comment by rhijmans** [comment]
Thanks for reporting this. "terra" supported hours and seconds, but not minutes as time distance from the origin. I had never encountered that (but it should perhaps have been obvious that someone would use it). It now does. Note, however, that if a non-standard calendar of 360 or 365 days is used, the "time" component of the "date/time" is currently ignored; you only get the date. That applies here as the calendar is "365_day".  That can be improved.

```
library(terra)
#terra 1.7.49
rast("mrso_CESM2-WACCM_ssp245.nc")
#class       : SpatRaster 
#dimensions  : 192, 288, 12  (nrow, ncol, nlyr)
#resolution  : 1.25, 0.9424084  (x, y)
#extent      : -0.625, 359.375, -90.4712, 90.4712  (xmin, xmax, ymin, ymax)
#coord. ref. :  
#source      : mrso_CESM2-WACCM_ssp245.nc:mrso 
#varname     : mrso (Total Soil Moisture Content) 
#names       : mrso_1, mrso_2, mrso_3, mrso_4, mrso_5, mrso_6, ... 
#unit        : kg m-2, kg m-2, kg m-2, kg m-2, kg m-2, kg m-2, ... 
#time (days) : 2100-01-15 to 2100-12-15 
```

**Comment by liushlcn** [comment]
Thanks a lot,  now the function works despite the date is still slightly strange for `day` "%d".

**Comment by rhijmans** [comment]
And I now see:

```
rast("mrso_CESM2-WACCM_ssp245.nc") |> time()
# [1] "2100-01-15" "2100-02-14" "2100-03-15" "2100-04-15" "2100-05-15"
# [6] "2100-06-15" "2100-07-15" "2100-08-15" "2100-09-15" "2100-10-15"
#[11] "2100-11-15" "2100-12-15"
```

**Comment by rhijmans** [comment]
I think I now get the same as you what you showed with cdo 

```
rast("mrso_CESM2-WACCM_ssp245.nc") |> time()

# [1] "2100-01-15 12:00:00 UTC" "2100-02-14 00:00:00 UTC" "2100-03-15 12:00:00 UTC"
# [4] "2100-04-15 00:00:00 UTC" "2100-05-15 12:00:00 UTC" "2100-06-15 00:00:00 UTC"
# [7] "2100-07-15 12:00:00 UTC" "2100-08-15 12:00:00 UTC" "2100-09-15 00:00:00 UTC"
#[10] "2100-10-15 12:00:00 UTC" "2100-11-15 00:00:00 UTC" "2100-12-15 12:00:00 UTC"
```
