### ISSUE TITLE
configure script throws SEGFAULT under conditions involving multiple versions of PROJ libraries

### ISSUE THREAD

**Issue by cboettig** [rspatial/terra#1295]
On Ubuntu-22.04, I build PROJ, GEOS, and GDAL from source (to have access to the most recent versions).  `terra` is fine with this, until I try to include some optional but gdal-recommended external libraries like `libgeotiff-dev`, which depends on `libproj-dev`.  All the OSGeo libraries still compile and work fine, but unfortunately this combination of libraries appears to result in a SEGFAULT on the `./configure` step of when R attempts to build `terra`.  (This same segfault occurs in the `sf` package, both on line 3665 of the `configure` script, see complete build logs in:
https://github.com/boettiger-lab/nasa-topst-env-justice/actions/runs/6315364948/job/17147738622#step:4:9639 ).  Note that I'm installing the source versions in the usual `/usr/local/` path, so it's not clear to me why the segfault should occur when some of those libraries are also in `/usr`, but is perhaps a failure on my part to run the appropriate linkers or path config?   

For context, I maintain the `rocker/geospatial` docker images where we would like to provide R (and python) users with ready access to the most recent versions of GDAL, which as you know offer significant improvements and abilities.  My [experimental build recipe]( https://github.com/rocker-org/rocker-versioned2/blob/d4d4f05f583e8e18c5f44f88b9373539b6c15dce/scripts/install_dev_osgeo.sh) is based on the Docker Ubutnu 22.04 recipe from [osgeo/gdal](https://github.com/OSGeo/gdal/blob/master/docker/ubuntu-full/Dockerfile), which includes several packages from the ubuntu repos that implicitly depend on `libproj-dev`, and including any of these in the GDAL build results in the segfault crash (most provide optional support for additional but less common drivers and maybe are best to omit? I'm not an expert here and open to ideas).

**Comment by rhijmans** [comment]
I'll close this here there a duplicate at https://github.com/r-spatial/sf/issues/2236  and there is some discussion there. 
If anyone has something to add or suggest, probably best to do so there.
