### ISSUE TITLE
terra::plot() changes par()

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1297]
Every time we plot a SpatRaster or SpatVector, plotting parameters such as margin widths are changed for the rest of the R session, affecting other plots we want to make:

```
library(terra)
# terra 1.7.46

x <- 1:10
plot(x)  # default margins OK

r <- rast(system.file("ex/elev.tif", package="terra"))
plot(r)

plot(x)  # small margins now, axis labels not visible

par(mar = c(4, 4, 2, 1))
plot(x)  # margins OK

v <- vect(system.file("ex/lux.shp", package="terra"))
plot(v)

plot(x)  # small margins again, axis labels not visible
```

When we're alternating between terra maps and base plots, it can be quite annoying (and distracting for students) to have to set `par(mar = ...)` again every time. I see that the functions do include code for resetting the graphical parameters to those previously in the R session (e.g. `old.par <- graphics::par(no.readonly = TRUE); on.exit(graphics::par(old.par))`), but for some reason it doesn't seem to be (always) taking effect.

Cheers!

**Comment by rhijmans** [comment]
Thank you, I think this has now been fixed.
