### ISSUE TITLE
warning on disk space

### ISSUE THREAD

**Issue by fgoerlich** [rspatial/terra#1299]
In disaggregating a raster I get
`Warning message:`
`[disagg] Estimated disk space needed without compression: 208GB. Available: 157 GB.`
but the script finished normally, and the raster is disaggregated.

May I assume that the result is correct?

Thanks a lot!

**Comment by rhijmans** [comment]
If it finished it should be correct. This warning is given for in case writing does fail; so that you know you have to increase disk space.   Compression is used by default for GTiff, which I am guessing you used. The amount of compression you get depends on the data you are writing.
