### ISSUE TITLE
No direct conversion from terra SpatVector to sf?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#130]
It would be great to have a direct conversion from terra SpatVector to sf working, instead of being obliged to pass through sp:

```
library(terra)
# terra version 1.0.11
library(sf)
# Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

fname <- system.file("shape/nc.shp", package="sf")
fTerr <- vect(fname)

as(fTerr,"sf")
# Error in as(fTerr, "sf") : 
#  no method or default for coercing “SpatVector” to “sf”

fSp <- as(fTerr, "Spatial")
fSf <- st_as_sf(fSp)
fSf
# Simple feature collection with 100 features and 14 fields
# geometry type:  MULTIPOLYGON
# dimension:      XY
# bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
# CRS:            +proj=longlat +datum=NAD27 +no_defs
# First 10 features:
# ...
```
 If I well understand, it is on the way in sf ([https://github.com/r-spatial/sf/issues/1567](url))?

**Comment by rhijmans** [comment]
I agree, but that would ideally be done in `sf`. Hence https://github.com/r-spatial/sf/issues/1567

**Comment by jldupouey** [comment]
The conversion from `terra `to `sp `is very time consuming as soon as the volume of the `SpatVector `becomes a little large (a few thousand or tens of thousands of polygons). Time is not at all proportional to the number of polygons.

If direct conversion to `sf `is not immediately feasible, perhaps there is a way to improve the `terra `-> `sp `conversion?

**Comment by rhijmans** [comment]
`terra -> sf` is now available in the development versions (https://github.com/r-spatial/sf/issues/1567#issuecomment-757215985); and `terra -> sp`  is now much faster than before.

**Comment by jldupouey** [comment]
Great! Thanks for all this work.

**Comment by rhijmans** [comment]
And thank you very much for all your very useful suggestions and bug reports.
