### ISSUE TITLE
While plotting a SpatVect object if breaks is not null it should be assumed that it is "interval"

### ISSUE THREAD

**Issue by gonzarizzo** [rspatial/terra#1303]
Hi Robert,

I have found the following issue. When you make a plot and the variable is numeric, but the number of observations is low, the plot function assumes that the variable is categorical, even if you set a vector of breaks.

My suggestion to make this more intuitive is that if breaks is not null, it should assume that type is "interval" rather than "classes" as it is right now.

See the example below:

```
library(terra)
f <- system.file("ex/lux.shp", package = "terra")
v <- vect(f)

plot(v, "POP")
plot(v[1:6,], "POP")
plot(v[1:6,], "POP", breaks = seq(5000, 40000, 5000))
```

Hope you find this comment useful!

Gonzalo

**Comment by rhijmans** [comment]
Thank you. Implemented as suggested.
