### ISSUE TITLE
crop with mask=TRUE and maskvalues: Error: [write] unknown option(s): maskvalues

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1309]
Dear @rhijmans,
According to the documentation of crop(), we can use the mask and select the mask values that will be set to NA.
"You can only crop rectangular areas, but see mask for setting cell values within SpatRaster to NA. (..) "
However, when I use `crop()` and `mask()` together I am getting error: `[write] unknown option(s): maskvalues`

Here is a small example: 
```
library(terra)
terra 1.7.46
```
Warning message:
package ‘terra’ was built under R version 4.2.3 

```
##Data preparation
r <- rast(system.file("ex/elev.tif", package="terra"))
v <- vect(system.file("ex/lux.shp", package="terra"))
cm <- crop(r, v[9:12,], mask=TRUE)

##TESTS
#WORKS: Crop with mask FALSE
r2 <- crop(r,cm,mask=FALSE)
plot(r2)
```
![image](https://github.com/rspatial/terra/assets/55965799/93a03ace-a959-47f9-8a71-21cba362d4d5)
```
#WORKS: Crop with mask TRUE
r3 <- crop(r,cm,mask=TRUE)
plot(r3)
```
![image](https://github.com/rspatial/terra/assets/55965799/d533d5de-86fd-4324-b417-91226f99aa3d)
```
#FAILS: Crop with mask TRUE & using mask value
r4 <- terra::crop(r,cm,mask=TRUE,maskvalues=277)
```
Error: [write] unknown option(s): maskvalues
```
#Mask on already cropped raster using mask values
r5 <- mask(r3,cm,maskvalues=277)
plot(r5)
```
![image](https://github.com/rspatial/terra/assets/55965799/0342969d-49ae-48e6-aff3-1125dbaa9524)
```
sessionInfo()
```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] terra_1.7-46

loaded via a namespace (and not attached):
[1] compiler_4.2.2   tools_4.2.2      Rcpp_1.0.11      codetools_0.2-18

Thanks!

**Comment by rhijmans** [comment]
"terra" has these two methods

```
crop(x, y, snap="near", mask=FALSE, touches=TRUE, extend=FALSE, filename="", ...)
mask(x, mask, inverse=FALSE, maskvalues=NA, updatevalue=NA, filename="", ...)
```

 `crop` has argument "mask=TRUE", but if you want to use argument "maskvalues" you cannot do this in one step, and you need to use `mask` after `crop`. I improved the documentation to make a clearer distinction between argument "mask=" and the `mask` method.
