### ISSUE TITLE
R Session aborted when calculating distances of non overlapping spatial objects

### ISSUE THREAD

**Issue by ElsLommelen** [rspatial/terra#131]
When calculating distances for the cells of a SpatRaster to a given SpatVector, the R session is aborted if there is no overlap between the spatial objects.

Example:
```
library(terra)
crs <- "+proj=utm +zone=1 +datum=WGS84"
r <- rast(ncol = 20, nrow = 20, xmin = 20, xmax = 40, ymin = 20, ymax = 40, crs=crs)
L1 <- vect("LINESTRING(1 11, 4 6, 10 6)", crs=crs)
L2 <- vect("LINESTRING(8 14, 12 10)", crs=crs)
L3 <- vect("LINESTRING(1 8, 12 14)", crs=crs)
lns <- c(L1, L2, L3)
distance(r, lns)
```

This occurs if the SpatVector contains lines or polygons.  If it contains points, distances are calculated for the raster cells.

The spatial objects may show no overlap by mistake, so it is up for debate whether a calculation is needed in this case, but it would anyway be helpful if an informative error message could prevent a crash of the R session.

**Comment by rhijmans** [comment]
Thank you very much for reporting this, and for the good example. You now get" 

```
distance(r, lns)
#Error: [distance] no overlap between vector and raster
```

I think that distance should be computed in this case, but for now, as you suggest, it is better to have an error message than a crash.
