### ISSUE TITLE
"You should reinstall package 'terra'"

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#1312]
On R version 4.1.2 (2021-11-01) -- "Bird Hippie" I get:
```
> library(terra)
terra 1.7.55
WARNING: different compile-time and run-time versions of GEOS
Compiled with:3.8.0-CAPI-1.13.1
 Running with:3.10.2-CAPI-1.16.0

You should reinstall package 'terra'

```
I do and get the same message again.

> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie

**Comment by rhijmans** [comment]
That suggests you have two version of GEOS installed. One gets used when "terra" is installed, and the other when "terra" runs. That can lead to crashes. Can you remove the older version of GEOS?

**Comment by aloboa** [comment]
As far as I understand, according to these commands, I only have 3.10.2:

```
(base) alobo@pop-os:~$ sudo apt search libgeos
Sorting... Done
Full Text Search... Done
libgeos++-dev/jammy 3.10.2-1 amd64
  Geometry engine for GIS - C++ development files

libgeos-c1v5/jammy,now 3.10.2-1 amd64 [installed,automatic]
  Geometry engine for Geographic Information Systems - C Library

libgeos-dev/jammy,now 3.10.2-1 amd64 [installed,automatic]
  Geometry engine for GIS - Development files

libgeos-doc/jammy,jammy 3.10.2-1 all
  Documentation for the GEOS GIS geometry engine library

libgeos3.10.2/jammy,now 3.10.2-1 amd64 [installed,automatic]
  Geometry engine for Geographic Information Systems - C++ Library

(base) alobo@pop-os:~$ cd /usr
(base) alobo@pop-os:/usr$ find -name "libgeos*"
./lib/x86_64-linux-gnu/libgeos_c.so
./lib/x86_64-linux-gnu/libgeos_c.so.1.16.0
./lib/x86_64-linux-gnu/libgeos_c.so.1
./lib/x86_64-linux-gnu/libgeos.so.3.10.2
./share/doc/libgeos-c1v5
./share/doc/libgeos-dev
./share/doc/libgeos3.10.2
./local/lib/python3.9/dist-packages/shapely.libs/libgeos-ee7a1634.so.3.11.1
./local/lib/python3.9/dist-packages/shapely.libs/libgeos_c-5ef8a841.so.1.17.1
```

**Comment by kadyb** [comment]
@aloboa, did you try reinstall `terra` to use a newer version of GEOS for compilation?

**Comment by aloboa** [comment]
Yes, of course. The installation ends by stating:
`You should reinstall package 'terra'`
I do it and get the same message again.
The output of the compilation mentions 3.10.2 only.

**Comment by aloboa** [comment]
I think this can be closed, as I no longer get the message. However, I do not have an explanation for what happened.
