### ISSUE TITLE
Terra installation fails. "../tools/winlibs.R" cannot be found or opened

### ISSUE THREAD

**Issue by RafP2021** [rspatial/terra#1313]
Hi everybody, I'm new of R and I am trying to install "terra" and "raster" packages in order to run some tests with other packages relying on them.
Unfortunately, every time I try to install "terra" package, RStudio gives me the output I copied here below. I may guess that the line I bolded shows the issue. I translated in English the very few dialogue parts that R showed in my language. I hope you can have any idea of what I did wrong (maybe I did not install correctly rtools...? Maybe there's something wrong in folder redirecting...?), because I am clueless. Thank you very much for any suggestion!

--------------------------------------
>install.packages("terra")
Installing package in ‘C:/Users/humbo/Documents/R/win-library/4.1’
(as ‘lib’ is not specified)

  Theres a binary version available, but the version with sources is successive:
      binary source needs_compilation
terra 1.7-23 1.7-55              TRUE

installing sources package ‘terra’

trying URL 'https://cran.rstudio.com/src/contrib/terra_1.7-55.tar.gz'
Content type 'application/x-gzip' length 827639 bytes (808 KB)
downloaded 808 KB

* installing *source* package 'terra' ...
** package 'terra' successfully unpacked and MD5 sums checked
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
rm -f terra.dll RcppExports.o RcppFunctions.o RcppModule.o arith.o crs.o distRaster.o distance.o extract.o file_utils.o focal.o gcp.o gdal_algs.o gdal_multidimensional.o gdalio.o geodesic.o geos_methods.o geosphere.o math_utils.o mediancut.o memory.o movingWindow.o ncdf.o ram.o raster_methods.o raster_stats.o rasterize.o read.o read_gdal.o read_ogr.o sample.o sort.o spatBase.o spatDataframe.o spatFactor.o spatRaster.o spatRasterMultiple.o spatSources.o spatTime.o spatVector.o spatVector2.o string_utils.o vecmath.o vecmathse.o vector_methods.o write.o write_gdal.o write_ogr.o
mkdir -p ../inst
"C:/PROGRA~1/R/R-41~1.1/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R" 3.4.1
**Irreversible error: it is not possible to open the file '../tools/winlibs.R': No such file or directory**

make: *** [Makevars.win:27: winlibs] Error 2
ERROR: compilation failed for package 'terra'
* removing 'C:/Users/humbo/Documents/R/win-library/4.1/terra'
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
----------------------------------------

My R version and OS details are:

```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          1.1                         
year           2021                        
month          08                          
day            10                          
svn rev        80725                       
language       R                           
version.string R version 4.1.1 (2021-08-10)
```

**Comment by kadyb** [comment]
This issue is related to compilation from source. The easier solution will be to update R to a newer version, then you can download the binary version of `{terra}`.

**Comment by rhijmans** [comment]
Installing from source on Windows should work if you update R *and Rtools* to the latest versions.

**Comment by RafP2021** [comment]
Thank you very much @kadyb  and @rhijmans !
I updated to R 4.3.1 and the issue is solved!
