### ISSUE TITLE
sieve returns a raster with values rounded to integer

### ISSUE THREAD

**Issue by spono** [rspatial/terra#1324]
Running `sieve(r, 4, 4)` on a Canopy Height Model with values spanning from 2 to 45 meters, clumps seem to be removed but all the other values of the output raster get rounded to integer (as well as the `NA` value (-9.223372e+18) that becomes -9.223.etc.etc ) creating a sort of `focal('modal')` effect.

tested with `terra 1.7-55` and `1.7-57` on R 4.2.3 and 4.3.1 (W10)

![sieve](https://github.com/rspatial/terra/assets/14940295/c25aa5da-e797-4db2-b146-66983c0059b4)

**Comment by kadyb** [comment]
I think the sieve filter is mainly used to smooth categorical data such as classification and that is [expected](https://gdal.org/programs/gdal_sieve.html):

> The input dataset is read as integer data which means that floating point values are rounded to integers. Re-scaling source data may be necessary in some cases (e.g. 32-bit floating point data with min=0 and max=1).

**Comment by spono** [comment]
mmm...ok, it never did it before. May I ask precisely what am I expected to do?

**Comment by rhijmans** [comment]
I have added to the help file that sieve creates integers. If you want to keep e.g. 3 decimal numbers you could first multiply the input raster with 1000. (and divide again by 1000 after sieving)?

**Comment by kadyb** [comment]
I'm not sure if the sieve filter should be used for numeric (continuous) data? See the example below, the result looks strange:
- some pixels was removed (bug?)
- the square in the middle wasn't filled
- NA was changed to 0 (bug?)

```r
library("terra")

f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
r[33:35, 33:35] = 0
plot(r)

rr = sieve(r, 10)
plot(rr)
```

**Comment by spono** [comment]
> I think the sieve filter is mainly used to smooth categorical data such as classification

you're right: I realise only now that my previous use cases were related to classes. This lead me to think it was a general easy way to remove tiny patches instead of using `patches`. My fault.

> you could first multiply the input raster with 1000. (and divide again by 1000 after sieving)

that's a good idea, thanks. So I guess the need to stick to integers is something related to how the algorithm works.

**Comment by kadyb** [comment]
Hi @rhijmans, could you please verify two things compared to [gdal_sieve](https://gdal.org/en/stable/programs/gdal_sieve.html)?

1. I think the NA flag is not passed in `terra::sieve()` maybe after saving.
2. Some pixels on the edges of the terrain have been removed for some reason (this doesn't happen in `gdal_sieve`).

```r
f <- system.file("ex/elev.tif", package="terra") # int16 datatype
r <- rast(f)
r[34:35, 34:35] = NA
plot(r)
writeRaster(r, "test_dem.tif")

system('gdal_sieve "C:/Users/Krzysztof/test_dem.tif" -st 10 -8 "C:/Users/Krzysztof/output_dem.tif"')
```

**Comment by rhijmans** [comment]
Can you share the output of 
```
system('gdal_sieve "C:/Users/Krzysztof/test_dem.tif" -st 10 -8 "C:/Users/Krzysztof/output_dem.tif"')
```
?

**Comment by rhijmans** [comment]
And I am not sure why you think there is something off with the NA flag. I see 

```
r <- writeRaster(r, "test_dem.tif", overwrite=T)
s <- is.na(x) + is.na(r)
unique(s)
#  elevation
#1         0
#2         2
```

**Comment by kadyb** [comment]
> And I am not sure why you think there is something off with the NA flag.

```r
library("terra")
f <- system.file("ex/elev.tif", package="terra") # int16 datatype
r <- rast(f)
r[34:35, 34:35] = NA
rr = sieve(r, 10)
plot(rr)
```

![Rplot](https://github.com/user-attachments/assets/13788ef2-59da-4aae-bc91-951ef94b0f63)

Shouldn't the image background be white?

**Comment by rhijmans** [comment]
Of course. I believe it now works as expected (https://github.com/rspatial/terra/commit/cd14f8bcb0a9e1c4dcf853fd786badfab0305be4)

**Comment by kadyb** [comment]
Now it's fixed too much 😄  -- the example in the doc no longer works:

```r
library("terra")

r <- rast(nrows=18, ncols=18, xmin=0, vals=0, crs="local")
r[2, 5] <- 1
r[5:8, 2:3] <- 2
r[7:12, 10:15] <- 3
r[15:16, 15:18] <- 4
plot(r)

x <- sieve(r, 8)
plot(x)
y <- sieve(r, 9)
plot(y)
```

**Comment by rhijmans** [comment]
Not my best day.... But it looks pretty good to me now

```
r <- rast(system.file("ex/elev.tif", package="terra"))
plot( sieve(r/50, 50))
```

**Comment by kadyb** [comment]
I tested a bit and it seems to work. Thank you very much Robert!
