### ISSUE TITLE
How to add a superscript to a title

### ISSUE THREAD

**Issue by cug-xyx** [rspatial/terra#1325]
Dear Maintainer:

Thank you for your awesome R package. I would like to know how to set the **superscript** when adding the `main` parameter to `plot(SpatRaster)`, also I am not able to set the **superscript** in the `title` parameter in `plot(plg=list()`.

Thank you for taking the time to solve my problem!

**Comment by kadyb** [comment]
I think normally this should work, but there is some bug with the legend title (in `plg` argument):

```r
library("terra")
f = system.file("ex/elev.tif", package="terra")
r = rast(f)
plot(r, main = expression("My Title"^2),
     plg = list(title = expression("My Title"^2)))
```

**Comment by cug-xyx** [comment]
Thank you for being able to reply to me so quickly! Actually `main` doesn't work for me either, I don't know what's going on.

```
library("terra")
f = system.file("ex/elev.tif", package="terra")
r = rast(f)
plot(r, main = expression("My Title"^2),
  plg = list(title = expression("My Title"^2)))

##> Error in x$main != "" : comparison is not allowed for expressions
```

![image](https://github.com/rspatial/terra/assets/77427610/cf12a4a7-a8b6-4e27-ada5-5bdb1a3fb09c)

**Comment by kadyb** [comment]
What version of `{terra}` do you have? I have 1.7.55.

**Comment by cug-xyx** [comment]
My version of `terra` is **1.7.23**.

**Comment by kadyb** [comment]
So try to update. You can also test the new version on [webR](https://webr.r-wasm.org/latest/).

**Comment by cug-xyx** [comment]
Thanks! Now `main` is ready

**Comment by kadyb** [comment]
@rhijmans, there is also a problem with the superscript in the legend:

```r
library("terra")
f = system.file("ex/elev.tif", package="terra")
r = rast(f)
plot(r, main = expression("My Title"^2),
     plg = list(title = expression("My Title"^2)))
```

**Comment by cug-xyx** [comment]
@kadyb , thanks a lot : )

**Comment by kadyb** [comment]
Real thanks to Robert, because he fixed it 😃
