### ISSUE TITLE
fill(inverse = TRUE) resets CRS information

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#133]
I just found a small bug using the `fill()` function when `inverse` is set to `TRUE`. Here is a reproducible example:

```
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
v_transform <- project(v, "epsg:3005")

v_transform_holes <- fill(v_transform, inverse = TRUE)
v_transform_filled <- fill(v_transform, inverse = FALSE)

crs(v_transform) == crs(v_transform_filled)
# TRUE
crs(v_transform_holes) == crs(v_transform_filled)
# FALSE
crs(v_transform) == crs(v_transform_holes)
# FALSE
```

There aren't actually any holes in this polygon, but the example is reproducible in polygons with holes. I just wanted to keep the reprex short here.

**Comment by rhijmans** [comment]
Thank you very much for reporting. Fixed now.
