### ISSUE TITLE
strange buffer using terra

### ISSUE THREAD

**Issue by zhangzhixin1102** [rspatial/terra#1330]
I want to generate a buffer around minimum convex polygon. However, the results are quite strange.
Could you please confirm the issue?
Below is my scripts and data.

```
library(terra)
locs <- read.csv("opportunistic-occ2.csv", row.names = 1)
locs <- vect(locs, crs="+proj=longlat")
mcp <- convHull(locs)

# generate buffer around MCP
d <- 1000*1000 ## 1000 km 
b <- terra::buffer(mcp, width = d)

maps::map('world', col = 'grey85', fill = T, border = 'grey85')
points(locs, pch = 20, col = "red")
lines(mcp)
lines(b)
```
[opportunistic-occ2.csv](https://github.com/rspatial/terra/files/13204234/opportunistic-occ2.csv)

![image](https://github.com/rspatial/terra/assets/42627764/3c266270-a416-458f-8981-9e3cf412cdbc)

**Comment by kadyb** [comment]
I think you should reproject your longitude and latitude data to a planar coordinate system (e.g. [EPSG:4087](https://epsg.io/4087)). If you want to use coordinates in degrees, you should use the `{sf}` package, which supports calculations on the sphere. See this article: https://r-spatial.github.io/sf/articles/sf7.html

**Comment by zhangzhixin1102** [comment]
Thanks for the editing by @rhijmans and the suggestion from @kadyb.
I tried the sf package and below are the results. I am still wandering: can terra solve this issue?

`library(sf)
library(terra)
locs <- read.csv("opportunistic-occ2.csv", row.names = 1)
locs <- vect(locs, crs="+proj=longlat")
mcp <- convHull(locs)

# generate buffer around MCP
d <- 1000*1000 ## 1000 km 
b <- terra::buffer(mcp, width = d)

## generate bufer using sf
sf::sf_use_s2(TRUE)
mcp.sf <- st_as_sf(mcp, crs = 4326)
a <- st_wrap_dateline(st_transform(x = st_buffer(x = st_transform(x = mcp.sf, crs = 4087), dist = d), crs = 4326), options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"), quiet = TRUE)

maps::map('world', col = 'grey85', fill = T, border = 'grey85')
points(locs, pch = 20, col = "red")
lines(mcp)
plot(a$geometry, add = T)`

![image](https://github.com/rspatial/terra/assets/42627764/0d2e2233-5826-4dbc-8e06-e83996c41259)

**Comment by rhijmans** [comment]
Thank you for reporting this. This case now works (but there are a few other extreme cases that need to be addressed).

```
library(terra)
xy <- read.csv("opportunistic-occ2.csv", row.names = 1)
locs <- vect(xy, crs="+proj=longlat")
mcp <- convHull(locs)
b <- terra::buffer(mcp, width = 1000*1000)

maps::map('world', col = 'grey85', fill = T, border = 'grey85')
points(locs, pch = 20, col = "red")
lines(mcp)
lines(b, col="blue", lwd=2)
```

![points](https://github.com/rspatial/terra/assets/11481397/038aabad-8603-408f-94c7-01765dd00e24)
