### ISSUE TITLE
R Session aborted when calculating a buffer from a vector

### ISSUE THREAD

**Issue by Julian090601** [rspatial/terra#1331]
Hi,

I have encountered some strange behaviour when calculating a buffer from a vector. 

In R version 4.3.1, if the buffer size is larger than 54 metres, the session aborts immediately. However, when I do the same in R version 4.2.3, everything works fine. I have tested on several machines and always come up with the same result. 

I have attached the polygon where the error occurs. I have checked the geometry and the crs but I cannot see any problems with them.

terra version: 1.7.55

[Krycklan_2015_poly.zip](https://github.com/rspatial/terra/files/13216359/Krycklan_2015_poly.zip)

**Comment by rhijmans** [comment]
Thanks. I see that this works 


```
library(terra)
v <- vect("Krycklan_2015_poly.shp")
b <- buffer(v, 75)
```

But that this crashes R 

```
b <- buffer(v, 100)
```

**Comment by rhijmans** [comment]
This example now works. I am not sure why it failed before.
