### ISSUE TITLE
extract() not working as expected with layers

### ISSUE THREAD

**Issue by ewanwakefield** [rspatial/terra#1332]
Hi,

Not sure if this is a bug or a misunderstanding of the way the function works. In short, the issue is that when I specify layer as numeric in the extract function, values from the layer n-1 are extracted. Here's an example. I'm using Windows and version 1.7.46 of terra.

Thanks,

Ewan

-----------------------

library(terra)

r <- rast(ncol=4, nrow=4, nlyr=3, extent=ext(-2, 2, -2, 2))

values(r[[1]]) <- 1
values(r[[2]]) <- 2
values(r[[3]]) <- 3

xy <- data.frame(x=-1:1,y=-1:1)

extract(r, xy[,1:2]) # Behaves as expected
extract(r, xy[,1:2], ID=F, layer=c(1,1,1)) # Returns error
extract(r, xy[,1:2], ID=F, layer=c(2,2,2)) # Extracts from layer 1 not 2!
extract(r, xy[,1:2], ID=F, layer=c(3,3,3)) # Extracts from layer 2 not 3!
extract(r, xy[,1:2], ID=F, layer=c(4,4,4)) # Does not extract from layer 3!

**Comment by rhijmans** [comment]
Thank you very much for reporting this. I now get:

```
library(terra)
#terra 1.7.60
r <- rast(ncol=4, nrow=4, nlyr=3, extent=ext(-2, 2, -2, 2))
values(r) <- rbind(11:13)
xy <- data.frame(x=-1:1,y=-1:1)
extract(r, xy)
#  ID lyr.1 lyr.2 lyr.3
#1  1    11    12    13
#2  2    11    12    13
#3  3    11    12    13
extract(r, xy, ID=FALSE, layer=1:3)
#  layer value
#1 lyr.1    11
#2 lyr.2    12
#3 lyr.3    13
extract(r, xy, ID=TRUE, layer=1:3)
#  ID layer value
#1  1 lyr.1    11
#2  2 lyr.2    12
#3  3 lyr.3    13
```
