### ISSUE TITLE
`distance`: accept data.frame input and guess `lonlat` automatically

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1336]
The `distance` function accepts a `matrix` as input, but throws an error if x and/or y is a `data.frame`. It would be very practical if it also accepted objects inheriting class `data.frame`.

`distance` also throws an error if the input is a matrix and `lonlat` is not provided. I think it would be good if it checked if the coordinates are within the lonlat limits, in which case it could automatically set lonlat=TRUE, otherwise FALSE -- and then emit a message like "_assuming lonlat is TRUE_" (or _FALSE_).

Cheers!

**Comment by rhijmans** [comment]
Implemented as suggested. Thank you.
