### ISSUE TITLE
Mosaic NA handling

### ISSUE THREAD

**Issue by dmi3kno** [rspatial/terra#1338]
I want to merge two equisized raster files preserving NAs. 
``` r
library(terra)
#> terra 1.7.55
r <- rast(nrows=3, ncols=3, vals=c(1:3,NA,5:9))
r2 <- rast(nrows=3, ncols=3, vals=rev(c(1:6,NA,8:9)))
m <- mosaic(r,r2, fun="sum") 
```
Expectation:
![](https://i.imgur.com/RXvuSGd.png)

Reality
``` r
m |> plot()
```

![](https://i.imgur.com/c849Spw.png)

<sup>Created on 2023-11-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think `mosaic` should have `na.rm` argument exposed. It can be set to TRUE by default, but the user should be able to change that. The proposed interface is:

```r
mosaic(r,r2, fun="sum", na.rm=FALSE) 
```

**Comment by rhijmans** [comment]
Mosaic is not the right method here (it is for combining rasters that do not have the same extent). You can do 

```
s <- sum(c(r, r2))
```

or 

```
s <- sum(c(r, r2), na.rm=TRUE)
```
