### ISSUE TITLE
Request for a function for morphological and creation of spatial filters for rasters

### ISSUE THREAD

**Issue by URF-analyst** [rspatial/terra#1339]
I think there is no function in terra yet for image morphological operations like dilate or erode. These filters are very useful in image analysis.

**Comment by kadyb** [comment]
FWIW: There are already several image processing packages in R where morphological filters are implemented, e.g. [OpenImageR](https://cran.r-project.org/web/packages/OpenImageR/index.html), [mmand](https://cran.r-project.org/web/packages/mmand/index.html), [imager](https://cran.r-project.org/web/packages/imager/index.html), [EBImage](https://bioconductor.org/packages/release/bioc/html/EBImage.html) (but they usually support arrays).

**Comment by URF-analyst** [comment]
Are they compatible with terra package ?

**Comment by kadyb** [comment]
> Currently, I may transform raster to arrays ... apply the filters ... and convert back to raster ... right ?

Yes, there is example:

```r
library("terra")
library("OpenImageR")

f = system.file("ex/elev.tif", package = "terra")
r = rast(f)
mat = as.matrix(r, wide = TRUE) # convert raster to matrix
mat = dilationErosion(mat, Filter = c(3, 3), method = "dilation") # dilation filter
mat[mat == -Inf | mat == 0] = NA # replace values with NA
rr = rast(r, vals = mat) # create new raster

par(mfrow = c(1, 2))
plot(r, main = "Original")
plot(rr, main = "Dilation")
```

![Rplot](https://github.com/rspatial/terra/assets/35004826/1efe9876-3161-463d-91cb-27586f00675e)

**Comment by URF-analyst** [comment]
Thanks a lot.
