### ISSUE TITLE
values are lost when writing images with an associated color table 

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#134]
When writing a `SpatRaster `to a `PNG `file, with (any) color table, the value 255 is lost. Without a color table, the value is not lost. I suspect it could be a bug linked to some rescaling of raster values when a color table is given. Or perhaps am I ignoring some specification of the `PNG `format?

```
library(terra)
# terra version 1.0.11

r <- rast(ncols=16, nrows=16, vals=0:255)
coltb <- data.frame(t(col2rgb(rainbow(256), alpha=TRUE)))
coltab(r) <- coltb

values(r)[256,]
# lyr.1 
#   255 

writeRaster(r,"testr.png",wopt=list(filetype="PNG"),overwrite=TRUE)
rr <- rast("testr.png")

values(rr)[256,]
# lyr.1 
#  NaN 
```

**Comment by rhijmans** [comment]
With byte data, `terra` uses 255 as NA flag. You can set it to a value outside ofthe 0-255 range (or NA).

```
rr <- writeRaster(r,"testr.png",wopt=list(filetype="PNG", NAflag=NA), overwrite=TRUE)
rr[256]
# lyr.1
#1   255
``` 

I could make this the default for cases where (1) the values are (or can be) in memory so that I can check for the presence of an NA; AND (2) there are no NA values; AND (3) the user did not set the NAflag.

**Comment by jldupouey** [comment]
Thank you, it's clear. Since it seems to be a `terra` specification, not a `GDAL` or `PNG` specification, perhaps it should be indicated somewhere in the documentation. For example, by indicating in the `writeRaster` help page, at the description of the `NAflag` content, something about the default values chosen for missing values. Or in any other more appropriate place. Without this knowledge, in case of large rasters, the non-missing values are silently lost and it is even difficult for the user to notice it.

**Comment by rhijmans** [comment]
I have added a note about this on the writeRaster help page
