### ISSUE TITLE
Options argument is getting ignored when building a VRT using terra::vrt()

### ISSUE THREAD

**Issue by ericko443** [rspatial/terra#1341]
Hello,

I was trying to read several adjacent non-overlapping TIF files into R using `terra::vrt()`. Due to reasons I don't know, some of these files have a different CRS definition than others although they use the same general projection and I know that they align perfectly. It still shouldn't be a problem to create the VRT, since the option `-allow_projection_difference` can be set which ignores the projection of each input file. This, however, did not work. Passing other possible options as function arguments was not a problem but with this particular one, I ran into problems. Here is an example:

```
library(terra)
#terra 1.7.55

x <- rast(nrow = 10, ncol = 10, res = 1, vals = 1:100)
x_left <- crop(x, ext(-180, 0, -90, 90))
x_right <- crop(x, ext(0, 180, -90, 90))
crs(x_right) <- NULL
writeRaster(x_left, "x_left.tif")
writeRaster(x_right, "x_right.tif")

vrt(c("x_left.tif", "x_right.tif"))
#class       : SpatRaster 
#dimensions  : 180, 180, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 0, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : spat_kxW7ldWzuLSfHp0_140301.vrt 
#name        : spat_kxW7ldWzuLSfHp0_140301 
#min value   :                           1 
#max value   :                         100 

vrt(c("x_left.tif", "x_right.tif"), options="-allow_projection_difference")
#class       : SpatRaster 
#dimensions  : 180, 180, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 0, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : spat_XtR5YkYlJw6iAQV_140301.vrt 
#name        : spat_XtR5YkYlJw6iAQV_140301 
#min value   :                           1 
#max value   :                         100 
```
As you can see, no matter if I specify the option or not, only the first of the two raster files is considered when calling the function (see extent of the two SpatRasters). I then ran `gdalbuildvrt` via the command line, passed the two dummy rasters through a TXT file and specified `-allow_projection_difference` again:
```
gdalbuildvrt -allow_projection_difference -input_file_list file_list.txt vrt_out.vrt
```
Then I read the output raster into R using `rast()`:
```
rast("vrt_out.vrt")
#class       : SpatRaster 
#dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : vrt_out.vrt 
#name        : vrt_out 
#min value   :       1 
#max value   :     100 
```
The native GDAL call seems to consider the option but `terra::vrt()` seems to ignore it. Is this a bug or am I missing something?

**Comment by kadyb** [comment]
What version of GDAL do you have? Because I see this with GDAL 3.6.2:

```r
v = vrt(c("x_left.tif", "x_right.tif"), options="-allow_projection_difference")
dim(v)
#> [1] 180 360   1

gdal()
#> [1] "3.6.2"

packageVersion("terra")
#> [1] ‘1.7.55’
```

**Comment by rhijmans** [comment]
I also see this problem on Ubuntu, with GDAL 3.4.3. 
I am assuming this is a GDAL bug that has been fixed; as it works for me on Windows with GDAL 3.5.2 and 3.7.2
For that reason, I am closing the issue.
