### ISSUE TITLE
Error: 'minCircle' is not an exported object from 'namespace:terra'

### ISSUE THREAD

**Issue by ManuelPopp** [rspatial/terra#1342]
MRE:
`
require(terra)
xy <- cbind(c(0, 1, 1, 0, 0), c(0, 0, 1, 1, 0))
polygon_sf <- sf::st_sfc(sf::st_polygon(list(xy)))
plot(polygon_sf)
terra::minCircle(polygon_sf)
`
Output:
`
Error: 'minCircle' is not an exported object from 'namespace:terra'
`

?minCircle however, shows the help page for `convHull {terra}`, where it is listed. There are working examples for the other functions listed there. minRect() works as expected, just minCircle does not. Something seems to be off here...

`
> packageVersion("terra")
[1] ‘1.7.55’
`

**Comment by rhijmans** [comment]
Thanks very much for reporting this. I forgot to export the method. Fixed now.

**Comment by bennotkin** [comment]
In 1.7-78 I have `minRect()` but no `minCircle()` (though documentation exists for both)

**Comment by rhijmans** [comment]
This works with terra 1.7.78:

```
library(terra)
#terra 1.7.78
xy <- cbind(c(0, 1, 1, 0, 0), c(0, 0, 1, 1, 0)) 
p <- vect(xy, type="polygon")
mc <- terra::minCircle(p)

plot(mc, lwd=2, border="blue")
lines(p, col="red")
```

<img width="340" alt="circle" src="https://github.com/user-attachments/assets/74fe2278-4e51-446b-9b88-2366683a7b68">

If it does not for you, then you have not installed the new version correctly (install in a clean environment, with no other packages loaded, do not use RStudio)
