### ISSUE TITLE
do.call(merge, rlist) does not allow to write directly to file as it did in raster package

### ISSUE THREAD

**Issue by brendo1001** [rspatial/terra#1348]
When using do.call(merge,) i am unable to write output directly to file as could be done with raster package. Simple example below illustrates this.
Thanks for your great work!

R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS/LAPACK: /apps/intel/mkl/2020.1.217/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] raster_3.6-3  sp_1.5-0      sf_1.0-14     ranger_0.14.1
[5] terra_1.7-39 

library(terra);library(raster)

# Terra implementation
x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, res=1, vals=1)
y <- rast(xmin=-85, xmax=-55, ymax=60, ymin=30, res=1, vals=2)
z <- rast(xmin=-60, xmax=-30, ymax=50, ymin=20, res=1, vals=3)

# terra::merge
rlist <- list(x, y, z)
mos <- do.call(merge, rlist) # works fine

rlist$filename <- "file_out"
rlist$datatype <- "FLT4S"
rlist$overwrite <- TRUE
rlist$na.rm <- TRUE
mos <- do.call(merge, rlist) 
# Error: [sprc] list elements should be 'SpatRaster' is of class: character

# Raster implementation
r1 <- raster(xmx=-150, ymn=60, ncols=30, nrows=30)
values(r1) <- 1:ncell(r1)
r2 <- raster(xmn=-100, xmx=-50, ymx=50, ymn=30)
res(r2) <- c(xres(r1), yres(r1))
values(r2) <- 1:ncell(r2)

# raster::merge
rlist <- list(r1, r2)
mos <- do.call(merge, rlist) # works fine

rlist$filename <- "file_out"
rlist$datatype <- "FLT4S"
rlist$overwrite <- TRUE
rlist$na.rm <- TRUE
mos <- do.call(merge, rlist) # works fine

**Comment by Rapsodia86** [comment]
Function `merge()` does not have a `datatype` argument; there is `wopt`: list with named options for writing files as in `writeRaster` (https://rdrr.io/cran/terra/man/merge.html)
So, try this:
```
x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, res=1, vals=1)
y <- rast(xmin=-85, xmax=-55, ymax=60, ymin=30, res=1, vals=2)
z <- rast(xmin=-60, xmax=-30, ymax=50, ymin=20, res=1, vals=3)

rlist <- list(x, y, z)
rlist$filename <- "file_out.tif"
rlist$overwrite <- TRUE
rlist$na.rm <- TRUE
rlist$wopt <- list(datatype="FLT4S")

mos <- do.call(merge, rlist)
> mos
class       : SpatRaster 
dimensions  : 50, 80, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -110, -30, 20, 70  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
source      : file_out.tif 
name        : lyr.1 
min value   :     1 
max value   :     3 
```

**Comment by rhijmans** [comment]
The real issue here is that you should use a SpatRasterCollection instead of using `do.call` with `terra::merge`

```
library(terra)
x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, res=1, vals=1)
y <- rast(xmin=-85, xmax=-55, ymax=60, ymin=30, res=1, vals=2)
z <- rast(xmin=-60, xmax=-30, ymax=50, ymin=20, res=1, vals=3)

r <- sprc(x, y, z)
m <- merge(r)
```
