### ISSUE TITLE
rast() changes layer names to bigfile[,varname] when loading one tiff or list

### ISSUE THREAD

**Issue by francisvolh** [rspatial/terra#1349]
Hello, I asked this question on SO a week ago and got no feedback, so I thought I move it here. Apologies in advance if this does not classify as an issue in itself!
(https://stackoverflow.com/questions/77470934/rast-function-in-terra-package-changes-layer-names-to-bigfile-varname-when-loa)

I am working with tif file rasters from the climateNA website (https://adaptwest.databasin.org/pages/adaptwest-climatena/), each file is about 18 to 40MB. So I would not upload the files here as of now, and downloading the whole set would take a good chuck of time (so not asking you to that yet!). So not sure how to make my issue more reproducible. But I will try to explain as best as I can.

When loading a raster file (each raster contains only 1 layer) with function `rast()` from terra I get the following:

```
class       : SpatRaster 
dimensions  : 7617, 7688, 1  (nrow, ncol, nlyr)
resolution  : 1000, 1000  (x, y)
extent      : -4352000, 3336000, -3341000, 4276000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
source      : Normal_1991_2020_bFFP.tif 
name        : bigfile[, varname] 
min value   :                  0 
max value   :                292 
```
Notice how the source is correct but the name has changed to "bigfile[, varname]". Which does not happen with other smaller size rasters. I can rename the layer with `terra::name()`. I haven't really attempted to manually assign the name within the function with the `name =` parameter. But this would be for only 1 file. And I need to work with several in an automated way.

So, my main issues is that I am actually using a list of rasters and reading them within `rast()` like this:

```
# produces a list of name from the previously defined folder containing all the raster tif files
Normrast<- list.files(path = clim.folder, pattern='.tif$', all.files=TRUE, full.names=TRUE)

# Get and stack Climate rasters from folder above
NormStack<-terra::rast(Normrast)
```
Which produces the following object:

```
> NormStack
class       : SpatRaster 
dimensions  : 7617, 7688, 12  (nrow, ncol, nlyr)
resolution  : 1000, 1000  (x, y)
extent      : -4352000, 3336000, -3341000, 4276000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
sources     : Normal_1991_2020_CMD.tif  
              Normal_1991_2020_EMT.tif  
              Normal_1991_2020_FFP.tif  
              ... and 9 more source(s)
names       : bigfi~name], bigfi~name], bigfi~name], bigfi~name], bigfi~name], bigfi~name], ... 
min values  :           0,       -67.9,           0,       -27.3,       -45.1,       -14.7, ... 
max values  :        2185,        29.2,         365,        30.4,        28.4,        38.8, ...
```

If I attempt to change the names with `terra::names()` it seems to work by assigning a vector of names using `list.files()` from the folder all the files are in, but I wonder why this behaviour occurs. I also worry about being sure the assignment using `terra::names()` is working right, with more files making the cross checking more complicated than when using about 10 raster files or so. Maybe the order of the files is sometimes not respected (Which so far, it seems like it).

I have searched far and wide why this happens, but to no avail. I have found a reference to something similar happening in the raster package (https://gis.stackexchange.com/questions/317591/why-raster-layer-name-change-to-default-when-using-rastercalc-function) But nothing on this particular issue.

I tried looking into the source code for `rast()` but really got lost in the type of file a tiff should be. 

Thanks for any advice you have! Cheers!

**Comment by rhijmans** [comment]
answered on SO
