### ISSUE TITLE
object 'names' is not exported by 'namespace:terra'

### ISSUE THREAD

**Issue by jvandoninck** [rspatial/terra#1352]
```
require(terra)
x <- rast()
terra::names(x)
```
Returns:
```
Loading required package: terra
terra 1.7.55
Error: 'names' is not an exported object from 'namespace:terra'
```

Was names intentionally not exported?

**Comment by rhijmans** [comment]
It was not exported as there is no real need for it with `names`  as it is a primitive function. But with this change you can now do `terra::names` as well.

**Comment by jvandoninck** [comment]
Thanks.
I guess the same goes for other primitive function such as `round`? I'm just seem to run into problems when trying to use these functions in a package I'm developing myself and that imports.
E.g., my package includes the line
```
extent <- round(extent, digits)
```
where `extent` is a SpatExtent object. This gives an error:
```
Error: 'round' is not an exported object from 'namespace:terra'
```

terra:::round() doesn't seem to work either. What would be in general the best way to include these extended primitive functions in a package that imports terra? In this specific case extent could be transformed to a numeric and back to SpatExtent after applying round, but that seems unpractical.
Apologies if this should be a stupid question, I'm not so experienced in creating packages and couldn't find any more info elsewhere.

**Comment by rhijmans** [comment]
that surprises me because in an interactive session that works fine

```
x <- terra::rast()

terra::round(x)
#Error: 'round' is not an exported object from 'namespace:terra'

round(x)
#class       : SpatRaster 
#dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84)  
```

**Comment by rhijmans** [comment]
`terra::round` now also works.
