### ISSUE TITLE
Scale factor returns out-of-range values from MODIS products

### ISSUE THREAD

**Issue by sigmafelix** [rspatial/terra#1354]
Hello,

I am using MODIS HDF files with `{terra}`. I found that the scaling factor multiplication in `src/gdalio.cpp` returns unexpectedly large values in `SpatRaster` object. It seems that Lines 801-817 assume that the scaling factor should always be multiplied to the raw values stored in the dataset, even though the scale in MODIS HDF files is supposed to be divided:

https://github.com/rspatial/terra/blob/490a513a646277479ed0fe1dadbb3937d2cc8f73/src/gdalio.cpp#L807-L817

Below is my example (NASA credentials are required for full reproducibility) for MODIS 16-day NDVI (MOD13A2) product HDF files read in `{terra}_1.7_55`.

```r
# file is available at: https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/61/MOD13A2/2018/001/MOD13A2.A2018001.h09v05.061.2021313023538.hdf
# (credentials are required)

library(terra)
mod13 <- terra::rast("MOD13A2.A2018001.h09v05.061.2021313023538.hdf")

summary(mod13["1 km 16 days NDVI"])
#  X.1.km.16.days.NDVI.
#  Min.   :-19760000   
#  1st Qu.: 18130000   
#  Median : 24150000   
#  Mean   : 27300047   
#  3rd Qu.: 33890000   
#  Max.   : 83900000   
#  NA's   :63         

# describe subdataset
describe('HDF4_EOS:EOS_GRID:"MOD13A2.A2018001.h09v05.061.2021313023538.hdf":MODIS_Grid_16DAY_1km_VI:"1 km 16 days NDVI"')
#   [1] "Driver: HDF4Image/HDF4 Dataset"                                                                                                                                
# # truncated ...
# [184] "  scale_factor=10000"                                                                                                                                          
# [185] "  scale_factor_err=0"                                                                                                                                          
# # truncated ...
# [215] "  valid_range=-2000, 10000"                                                                                                                                    
# # truncated ...
# [227] "  Description = 1 km 16 days NDVI"                                                                                                                             
# [228] "  NoData Value=-3000"                                                                                                                                          
# [229] "  Unit Type: NDVI"                                                                                                                                             
# [230] "  Offset: 0,   Scale:10000" 

```

I would like to suggest giving users a warning or a message about the presence of `scale_factor` in the input dataset instead of automatically multiplying `scale_factor` to the raw values. The other option would be to add an argument (e.g., `autoscale`) to `terra::rast` to multiply `scale_factor` automatically if it is present in the metadata of the input.

**Comment by rhijmans** [comment]
> It seems that Lines 801-817 assume that the scaling factor should always be multiplied to the raw values stored in the dataset, even though the scale in MODIS HDF files is supposed to be divided:

I would not call that an assumption. That is how scale and offset are defined. If the values need to be divided by 10000 the scale should have been set to 0.0001. 

I have added an argument "raw=FALSE" to `rast`, `sds` and `sprc`. 
Use "raw=TRUE" to not apply the scale and offset reported in the file. 

```
library(terra)
#terra 1.7.61

f <- "MOD13A2.A2018001.h09v05.061.2021313023538.hdf"
rast(f)[[1]] |> minmax(TRUE)
#    "1 km 16 days NDVI"
#min           -20000000
#max            92440000

rast(f, raw=TRUE)[[1]] |> minmax(TRUE)
#    "1 km 16 days NDVI"
#min               -2000
#max                9244
```
