### ISSUE TITLE
`set.values()` with doesn't work properly with vsicurl/WCS

### ISSUE THREAD

**Issue by dfriend21** [rspatial/terra#1355]
I've been working with a lot of network based rasters recently, and sometimes I want a way to get the values into memory without performing an operation on the raster (like doing `r + 0` or `r * 1`). `set.values()` does this, but it doesn't seem to be working properly. I have two examples below - one using `vsicurl` and the other using the WCS driver.

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.3.2
#> terra 1.7.62

e <- ext(-114.202212749135, -114.150165743847, 35.2766228126154, 35.308855528189)
r <- rast("/vsicurl/http://rangeland.ntsg.umt.edu/data/rap/rap-vegetation-cover/v3/vegetation-cover-v3-2010.tif",
          win = e)
set.values(r)

plot(r)
#> Error in eval(expr, envir, enclos): std::bad_alloc
r + 0 # this line causes R to abort

e2 <- ext(-1631650.01456382, -1626602.60560418, 1514452.31964633, 1517650.28264809)
r2 <- rast("WCS:https://www.mrlc.gov/geoserver/rcmap_anhb/wcs?coverage=rcmap_anhb__rcmap_annual_herbaceous_2010",
           win = e2)
set.values(r2)

# both of these lines cause R to abort
plot(r2)
r2 + 0
```

<sup>Created on 2023-11-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Thanks for reporting this bug. `set.values` did not consider that a SpatRaster might have a window. 
That is fixed with this change.  `set.values`  now makes the window permanent.
