### ISSUE TITLE
Specifying multiple output files to sapp results in an error

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#1358]
I am trying to specify multiple output files in an `sapp()` function call so that my individual layers may be written to individual files within the `sapp()` function; however, when I try to give it multiple file paths I am met an error stating that the length of the filenames is greater than 1. Here is my reprex:

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))
y <- sapp(s, mean, filename = file.path(tempdir(), paste0(names(s), ".tif")), overwrite = TRUE)

# Error in if (filename != "") { : the condition has length > 1
```

The interesting thing is that if `terraOptions(todisk = TRUE)` is set, then three files are output, so I can see that it is possible to do this, though I imagine that this is unrelated:

```
terraOptions(todisk = TRUE)
y <- sapp(s, mean)
sources(y)

# [1] "C:/Users/matth/AppData/Local/Temp/RtmpYjTUmm/spat_Wr6zih3TjdYoK4s_4324.tif"
# [2] "C:/Users/matth/AppData/Local/Temp/RtmpYjTUmm/spat_wIaDTzQkutLvu9T_4324.tif"
# [3] "C:/Users/matth/AppData/Local/Temp/RtmpYjTUmm/spat_RZRd5ha7R1MwGNu_4324.tif"
```

The workaround is to run the `sapp()` function first and then `writeRaster()` after that, but I was wondering if there could be a provision to include multiple file paths in the `sapp()` function call (and perhaps other functions as well)? This would just be for convenience and to make my workflows a bit cleaner.

Thank you :)

**Comment by rhijmans** [comment]
fixed this for `sapp`; and it makes sense for that method. But making this a general feature would be a major undertaking.

**Comment by mcoghill** [comment]
Thanks so much @rhijmans ! I figured it would be a large task to complete this in each case, but thanks for tackling this one specifically, I do appreciate it :)
