### ISSUE TITLE
Behaviour of terra::boundaries at the border of the raster

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#136]
The `boundaries `help page indicates that the boundary cells are those "that have more than one class in the 4 or 8 cells surrounding it". It does not indicate what happens when the cell has less than 4 or 8 cells surrounding it, on the raster border. A test shows that these raster border cells are never classified as boundary cells. It would be interesting to be able to classify these raster border cells as boundary cells when they have more than one class in their 3 or 5 cells surrounding them. Otherwise, frontiers identified by `boundaries` stop one pixel before the raster edge, which could be a problem in applications:

. it seems to me that when searching for boundaries, this choice is not the favourite one in most cases. This is similar to applying and therefore losing a buffer one cell wide. 
. the choice was just the opposite in the former `raster `package. Why change?
. there is no easy way to correct this afterwards, apart from time-consuming recalculations. The user could adapt more easily to the opposite behavior, by removing from the borders calculated by `boundaries` all the cells at the raster border, if needed. 

Perhaps an option to choose the behavior of the `boundaries` function at the raster border would be useful, or reversing to the former `raster `way of calculation?

**Comment by rhijmans** [comment]
This has now been fixed and the results are the same as what you would get with `raster`
