### ISSUE TITLE
Read netCDF file

### ISSUE THREAD

**Issue by mhesselbarth** [rspatial/terra#1360]
Hello, 

I am currently running into some issue with a netCDF file. The file is rather larger, but can be downloaded [here](https://gitlab.iiasa.ac.at/forestnavigator/wp2/public/-/blob/main/Forest4model_v1_Disturbance_intensity.nc?ref_type=heads). 

When reading the file using `terra`, all values are `NA`. However, reading the file with `raster` works and there are values present. Interestingly, after reading the file with `raster`, writing it to the disk, and re-reading it with `terra`, values are identical to the `raster`-read data. 

Last, when reading with `raster` there are some warnings related to 8-byte values. I am attaching some code examples demonstrating the behavior. 

Thank you very much for the help.

``` r
library(raster)
library(terra)
library(rnaturalearth)
library(dplyr)

path <- "C:/Users/hesselbarth/Downloads/Forest4model_v1_Disturbance_intensity.nc"

# get country polygon
aus_poly <- rnaturalearth::ne_countries(type = "countries", scale = "small", returnclass = "sf") |> 
  dplyr::filter(admin == "Austria")

# read terra
t <- terra::rast(path) |> 
  terra::crop(y = aus_poly)

# read raster
r <- raster::raster(path) |> 
  raster::crop(y = aus_poly)
#> Loading required namespace: ncdf4
#> [1] ">>>> WARNING <<<  attribute add_offset is an 8-byte value, but R"
#> [1] "does not support this data type. I am returning a double precision"
#> [1] "floating point, but you must be aware that this could lose precision!"
#> [1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
#> [1] "var (or dimvar) name: crs"
#> [1] "file name: C:\\Users\\hesselbarth\\Downloads\\Forest4model_v1_Disturbance_intensity.nc"
#> [1] ">>>> WARNING <<<  attribute add_offset is an 8-byte value, but R"
#> [1] "does not support this data type. I am returning a double precision"
#> [1] "floating point, but you must be aware that this could lose precision!"

# re-write to disk
tmp_file <- paste0(tempfile(), ".tif")
raster::writeRaster(x = r, filename = tmp_file)

# re-read raster layer
t_rr <- terra::rast(tmp_file)

# check extent and ncell
terra::ext(t) == (raster::extent(r) |> terra::ext())
#> [1] TRUE
raster::ncell(r) == terra::ncell(t)
#> [1] TRUE

# check extent and ncell
terra::ext(t_rr) == (raster::extent(r) |> terra::ext())
#> [1] TRUE
terra::ncell(t_rr) == raster::ncell(r)
#> [1] TRUE

# compare values
all(r[!is.na(r)] == c(t_rr[!is.na(t_rr)]))
#> [1] TRUE

length(r[!is.na(r)])
#> [1] 2225313
length(c(t[!is.na(t)]))
#> [1] 0
length(c(t_rr[!is.na(t_rr)]))
#> [1] 2225313
```

<sup>Created on 2023-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

```
raster_3.6-26      terra_1.7-57
```

**Comment by kadyb** [comment]
`{stars}` doesn't open this file properly either:

```r
library("stars")
f = "Forest4model_v1_Disturbance_intensity.nc"
r = read_stars(f)
#> Warning message:
#> In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
#>                    GDAL Message 1: The dataset has several variables that could be identified as vector fields,
#>                    but not all share the same primary dimension. Consequently they will be ignored.
smp = st_sample(r, size = 100000)[[1]]
all(is.na(as.vector(smp))) # check for NAs
#> [1] TRUE
```

GDAL also has a problem with calculating statistics:

```r
terra::describe(f, options = "stats")
#> Warning message:
#> C:/Users/Krzysztof/Desktop/Forest4model_v1_Disturbance_intensity.nc, band 1:
#> Failed to compute statistics, no valid pixels found in sampling. (GDAL error 1) 
```

so probably the issue is with GDAL.

**Comment by rhijmans** [comment]
You can open the file successfully with "terra" like this

```
library(terra)
f <- "Forest4model_v1_Disturbance_intensity.nc"
x <- rast(f, opts=c("HONOUR_VALID_RANGE=NO"))
```
The reason that is necessary, it seems to me, is that there is an error in the file metadata. It specifies

>valid_max: 1
>valid_min: 0
>add_offset: 0
>scale_factor: 0.001

The valid_min and valid_max checks are done on the data as it is stored in the file, not on the transformed data.  The values in the file range from 10 to 1000 (that is, 0.01 to 1 after transformation) and these are all outside the value range of [0, 1] 

So the metadata should be 

>valid_max: 1000
>valid_min: 0
>add_offset: 0
>scale_factor: 0.001

**Comment by mhesselbarth** [comment]
Thank you so much! This really helps.
