### ISSUE TITLE
Regular spatSample returns huge sample for awkwardly shaped grid

### ISSUE THREAD

**Issue by dschlaep** [rspatial/terra#1362]
I am taking a regular sample from a grid, and I expected the result to be roughly (not exactly) the requested size.

I have an awkwardly shaped grid (where extent in one dimension is 1). This leads unexpectedly to a result with many more elements than requested (100s vs. requested 10).

Also, the size of the result depends on if I request spatial data to be returned (argument "xy" or "as.points") in addition to just the values:
  * Return objects that include spatial information contain more rows than when I request just values.
  * Return objects that include spatial information contain more rows than there are cells in the grid.

``` r
# Create 1-cell "wide" grid (a cell for each latitude)
rlat <- terra::rast(
  xmin = 0, xmax = 1,
  ymin = -90, ymax = 90,
  crs = "OGC:CRS84",
  resolution = c(1, 1),
  vals = 1:180
)

terra::ncell(rlat)
#> [1] 180


# Take a regular sample of size 10
# --- I expect that my result has roughly 10 elements
vs <- terra::spatSample(rlat, size = 10L, method = "regular")
nrow(vs)
#> [1] 43

xydf <- terra::spatSample(rlat, size = 10L, method = "regular", xy = TRUE)
nrow(xydf)
#> [1] 568
nrow(unique(xydf))
#> [1] 180

xysv <- terra::spatSample(rlat, size = 10L, method = "regular", as.points = TRUE)
terra::nrow(xysv)
#> [1] 568
terra::nrow(terra::unique(xysv))
#> [1] 180


osVersion
#> [1] "macOS Ventura 13.6.2"
R.version.string
#> [1] "R version 4.2.3 (2023-03-15)"
packageVersion("terra")
#> [1] '1.7.55'
```

<sup>Created on 2023-12-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Thank you and sorry for the long wait. I now get:

```
x <- terra::rast(xmin = 0, xmax = 1, ymin = -90, ymax = 90, crs = "OGC:CRS84", resolution = c(1, 1), vals = 1:180)
terra::spatSample(x, size = 10L, method = "regular") |> nrow()
#[1] 10

terra::spatSample(x, size = 10L, method = "regular", xy=TRUE) |> nrow()
#[1] 10

r <- terra::disagg(x, c(1,4))
terra::spatSample(r, size = 10L, method = "regular") |> nrow()
#[1] 10
```
