### ISSUE TITLE
Error with installation of R package - OGRCoordinateTransformation

### ISSUE THREAD

**Issue by robin-sto** [rspatial/terra#1371]
Hello, I was trying to install terra in our HPC R/4.2.3 environment and received this error:

crs.cpp: In member function ‘SpatVector SpatVector::project(std::string, bool)’:
crs.cpp:383:9: error: ‘class OGRCoordinateTransformation’ has no member named ‘SetEmitErrors’
  383 |   poCT->SetEmitErrors(false);
      |         ^~~~~~~~~~~~~
make: *** [crs.o] Error 1
ERROR: compilation failed for package ‘terra’

Can you please help?  I am running centos7.9

**Comment by robin-sto** [comment]
gdal/2.1.2
proj.4/4.9.1

**Comment by rhijmans** [comment]
Those are very old versions. The minimum requirements stated are  GDAL (>= 2.2.3) and PROJ (>= 4.9.3). 
I have made a change such that this compilation error should not occur anymore. However, others are likely to pop up and I may not be able to address these.  Updating GDAL/PROJ/GEOS would be the way to go.
