### ISSUE TITLE
Replacing the CRS of a SpatVector object leaves the return value of sources() untouched

### ISSUE THREAD

**Issue by florisvdh** [rspatial/terra#1372]
I would expect that changing the CRS of a SpatVector object should drop the link with the file source, but that doesn't seem to be the case. I didn't check with SpatRaster yet.

``` r
library(terra)
#> terra 1.7.55
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
v
#>  class       : SpatVector 
#>  geometry    : polygons 
#>  dimensions  : 12, 6  (geometries, attributes)
#>  extent      : 5.74414, 6.528252, 49.44781, 50.18162  (xmin, xmax, ymin, ymax)
#>  source      : lux.shp
#>  coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#>  names       :  ID_1   NAME_1  ID_2   NAME_2  AREA   POP
#>  type        : <num>    <chr> <num>    <chr> <num> <int>
#>  values      :     1 Diekirch     1 Clervaux   312 18081
#>                    1 Diekirch     2 Diekirch   218 32543
#>                    1 Diekirch     3  Redange   259 18664
sources(v)
#> [1] "/home/floris/lib/R/library/terra/ex/lux.shp"

# Changing data does change sources() value ------------------------------

dim(v)
#> [1] 12  6
v <- v[-1]
dim(v)
#> [1] 11  6
sources(v)
#> [1] ""

# Replacing CRS does not change sources() value --------------------------

v <- vect(f)
crs(v) <- "EPSG:3035"
v
#>  class       : SpatVector 
#>  geometry    : polygons 
#>  dimensions  : 12, 6  (geometries, attributes)
#>  extent      : 5.74414, 6.528252, 49.44781, 50.18162  (xmin, xmax, ymin, ymax)
#>  source      : lux.shp
#>  coord. ref. : ETRS89-extended / LAEA Europe (EPSG:3035) 
#>  names       :  ID_1   NAME_1  ID_2   NAME_2  AREA   POP
#>  type        : <num>    <chr> <num>    <chr> <num> <int>
#>  values      :     1 Diekirch     1 Clervaux   312 18081
#>                    1 Diekirch     2 Diekirch   218 32543
#>                    1 Diekirch     3  Redange   259 18664
sources(v)
#> [1] "/home/floris/lib/R/library/terra/ex/lux.shp"
```

<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31)
#>  os       Linux Mint 21.2
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2023-12-12
#>  pandoc   3.1.1 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.1   2023-03-23 [3] RSPM (R 4.2.0)
#>  codetools     0.2-19  2023-02-01 [3] RSPM (R 4.2.0)
#>  digest        0.6.33  2023-07-07 [3] RSPM (R 4.2.0)
#>  evaluate      0.23    2023-11-01 [3] RSPM (R 4.3.0)
#>  fastmap       1.1.1   2023-02-24 [3] RSPM (R 4.2.0)
#>  fs            1.6.3   2023-07-20 [3] RSPM (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [3] RSPM (R 4.2.0)
#>  htmltools     0.5.7   2023-11-03 [3] RSPM (R 4.3.0)
#>  knitr         1.45    2023-10-30 [3] RSPM (R 4.3.0)
#>  lifecycle     1.0.4   2023-11-07 [3] RSPM (R 4.3.0)
#>  magrittr      2.0.3   2022-03-30 [3] RSPM (R 4.2.0)
#>  purrr         1.0.2   2023-08-10 [3] RSPM (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [3] RSPM (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [3] RSPM (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [3] RSPM (R 4.2.0)
#>  R.utils       2.12.3  2023-11-18 [3] RSPM (R 4.3.0)
#>  Rcpp          1.0.11  2023-07-06 [3] RSPM (R 4.2.0)
#>  reprex        2.0.2   2022-08-17 [3] RSPM (R 4.2.0)
#>  rlang         1.1.2   2023-11-04 [3] RSPM (R 4.3.0)
#>  rmarkdown     2.25    2023-09-18 [3] RSPM (R 4.3.0)
#>  rstudioapi    0.15.0  2023-07-07 [3] RSPM (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [3] RSPM (R 4.2.0)
#>  styler        1.10.2  2023-08-29 [3] RSPM (R 4.2.0)
#>  terra       * 1.7-55  2023-10-13 [1] RSPM (R 4.3.2)
#>  vctrs         0.6.5   2023-12-01 [3] RSPM (R 4.3.0)
#>  withr         2.5.2   2023-10-30 [3] RSPM (R 4.3.0)
#>  xfun          0.41    2023-11-01 [3] RSPM (R 4.3.0)
#>  yaml          2.3.7   2023-01-23 [3] RSPM (R 4.2.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by rhijmans** [comment]
Is there a practical reason why you would want the link to the source to be dropped? I am asking because it is possible to do with a SpatVector (always in memory anyway); but not with a SpatRaster (or a copy would need to be made). It would not be possible with SpatVectorProxy either if it *had* a `crs()<-` method.

**Comment by florisvdh** [comment]
In the qgisprocess package, we try to support some common R objects as input for QGIS (more specifically: for the `qgis_process` standalone). In the case of spatial R objects, QGIS needs a file path. For SpatRaster, if possible we pass the file source of a SpatRaster object to QGIS instead of running `terra:writeRaster()` to do that, provided that [some conditions](https://github.com/r-spatial/qgisprocess/blob/4d57de4eae93425ee2574c43007266642108104a/R/compat-terra.R#L80-L92) are met (especially to capture band selection or reordering in R, which still preserves the source).

I'm adding something similar to also support SpatVector, including support for the case that a specific layer needs to be selected from the data source, which is indicated by `sources()` with `::`.

I understand that for SpatRaster we should add the 'non-corrected CRS' condition too; thanks for helping me get there. The referral to the source file in terra is to access data, since data are often not in memory.

For SpatVector I could also add such a condition (if CRS not equal: write new file from R with the correct CRS).

BTW I discovered this by mere accident; just wanted to do something simple that triggers dropping the source, as a test while developing code, and resetting the CRS came to mind first.

Whether for SpatVector you consider an updated CRS to be enough reason to drop the source (old CRS) is up to you! At first sight that seemed logical to do so in terra: the object is loaded in memory indeed and its CRS has been reset compared to the file source. But considering the potential merge with SpatVectorProxy (https://github.com/rspatial/terra/issues/638#issuecomment-1127021706), reasoning may become the same as SpatRaster; perhaps you want to keep as-is.

Projected SpatVector and SpatRaster objects drop their source anyway, so that's OK.

**Comment by florisvdh** [comment]
Considering SpatVectorProxy: it could be easily supported in qgisprocess as well as an input argument. Is the merge with SpatVector envisaged any time soon, or is it better to indeed still add it?

**Comment by florisvdh** [comment]
The dev version of qgisprocess has gained vector support for terra, both SpatVector and SpatVectorProxy (https://github.com/r-spatial/qgisprocess/pull/184/commits/ca11941). In the conversion of terra objects to QGIS input arguments, in which it is decided whether the `sources()` value can be used, the package takes into account the above described relationship between `sources()` and updated CRS, both for SpatVector and SpatRaster, as well as some other things that won't drop the source referral, such as band selection/reordering or updated attribute names.

Feel free to close!

**Comment by rhijmans** [comment]
Thank you for doing that and for your elaborate comments. The source is now removed after setting the CRS on a SpatVector.
