### ISSUE TITLE
vect(wkt) with strange behavior for MULTIPOINT

### ISSUE THREAD

**Issue by silasprincipe** [rspatial/terra#1376]
Hi, I'm using terra to get the convex hull of multiple types of geometries. It worked for all cases that I tested (polygon, multipolygon, linestring, multilinestring, point), except one: **multipoint**. Interestingly, it correctly reads the wkt, but then the `convHull` function does not returns what is expected (a linestring, in this particular test). Using the package `sf` or a mix of `terra` and `sf` works. Is that a bug or is there any option I'm missing? Thanks in advance!

See examples:

``` r
wkt <- "MULTIPOINT ((0 1), (0 -1))"

# sf version, working properly
s <- sf::st_as_sfc(wkt)
p <- sf::st_cast(s, "POINT")
mp <- sf::st_combine(p)
h <- sf::st_convex_hull(mp)
h

# Geometry set for 1 feature 
# Geometry type: LINESTRING
# Dimension:     XY
# Bounding box:  xmin: 0 ymin: -1 xmax: 0 ymax: 1
# CRS:           NA
# LINESTRING (0 1, 0 -1)

# terra + sf version, working properly
s <- terra::vect(sf::st_as_sfc(wkt))
h <- terra::convHull(s)
h

# class       : SpatVector 
# geometry    : lines 
# dimensions  : 1, 0  (geometries, attributes)
# extent      : 0, 0, -1, 1  (xmin, xmax, ymin, ymax)
# coord. ref. :  

# terra only version, not working
s <- terra::vect(wkt)
h <- terra::convHull(s)
h

# Returns points, not a line as expected

# class       : SpatVector 
# geometry    : points 
# dimensions  : 1, 0  (geometries, attributes)
# extent      : 0, 0, 1, 1  (xmin, xmax, ymin, ymax)
# coord. ref. :  
```

`terra` version: 1.7.65
`sf` version: 1.0.14
gdal version: 3.5.3
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4.1

**Comment by silasprincipe** [comment]
Just to complement the issue, I think that it can be because `terra` is considering a MULTIPOINTS wkt as a single geometry. So see for example:

``` r
wkt <- "MULTIPOINT (-64.02832 26.39187, -65.961914 26.627818)"
s <- terra::vect(wkt)
s

# class       : SpatVector 
# geometry    : points 
# dimensions  : 1, 0  (geometries, attributes)
# extent      : -65.96191, -64.02832, 26.39187, 26.62782  (xmin, xmax, ymin, ymax)
# coord. ref. :  

# If extract coordinates and then convert again
crds_s <- terra::vect(terra::crds(s))

# class       : SpatVector 
# geometry    : points 
# dimensions  : 2, 0  (geometries, attributes)
# extent      : -65.96191, -64.02832, 26.39187, 26.62782  (xmin, xmax, ymin, ymax)
# coord. ref. :  
```

Probably this is the expected result (`sf::st_as_sfc(wkt)` will also return a MULTIPOINT object instead of POINT), but is there a quick and more elegant way to ensure terra uses it as individual points when using `convHull`?

**Comment by htopazian** [comment]
Thanks for suggesting the `sf::st_as_sfc` workaround, I am having this issue too with v. 1.7-39. Running code from a year ago which used to work with `vect` with the same SpatVector object

**Comment by rhijmans** [comment]
Thanks, fixed now. I am sorry that it took so long.
