### ISSUE TITLE
PROJ: proj_create_from_database. It comes from another PROJ installation. (GDAL error 1) 

### ISSUE THREAD

**Issue by GuiSPinto** [rspatial/terra#1378]
Hello everyone, 

I'm having troubles when trying to re-project vectors or even load them. 

> swe <- geodata::gadm(country=c("Sweden"),level=0,path=tempdir())
> trying URL 'https://geodata.ucdavis.edu/gadm/gadm4.1/pck/gadm41_SWE_0_pk.rds'
> Content type 'unknown' length 1284598 bytes (1.2 MB)
> downloaded 1.2 MB
> 
> swe
>  class       : SpatVector 
>  geometry    : polygons 
>  dimensions  : 1, 2  (geometries, attributes)
>  extent      : 10.96139, 24.1724, 55.33625, 69.05904  (xmin, xmax, ymin, ymax)
>  coord. ref. : lon/lat WGS 84 (EPSG:4326) 
>  names       : GID_0 COUNTRY
>  type        : <chr>   <chr>
>  values      :   SWE  Sweden
> 
> terra::crs(swe)
> [1] "GEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]"
> 
> swe <- terra::project(swe,"EPSG:3006")
> Error: [project] output crs is not valid
> In addition: Warning message:
> PROJ: proj_create_from_database: ~/AppData/Local/Programs/R/R-4.3.1/library/rgdal/proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation. (GDAL error 1) 

Or

> swe.grid <- terra::vect("../R/shapefile/Data_grid_v1.shp", crs = "EPSG:3006")
> Warning messages:
> 1: PROJ: proj_identify:  ~/AppData/Local/Programs/R/R-4.3.1/library/rgdal/proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation. (GDAL error 1) 
> 2: PROJ: proj_create_from_database: ~/AppData/Local/Programs/R/R-4.3.1/library/rgdal/proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation. (GDAL error 1) 
> 3: [crs<-] Cannot set SRS to vector: empty srs 
>
> swe.grid
>  class       : SpatVector 
>  geometry    : points 
>  dimensions  : 736, 11  (geometries, attributes)
>  extent      : 280000, 905000, 6150000, 7650000  (xmin, xmax, ymin, ymax)
>  source      : Data_grid_v1.shp
>  coord. ref. :  
>  names       : Key_ID FID_2       VEGZONSNA Distance KOMMUNKOD KOMMUNNAMN LANSKOD        LANSNAMN
>  type        :  <int> <int>           <chr>    <num>     <int>      <chr>   <int>           <chr>
>  values      :    369     5 Sydligt boreal~    339.5      2262      Timrå      22 Västernorrland~
>                   349     0       Alpin zon        0      2361 Härjedalen      23   Jämtlands län
>                   358     0       Alpin zon        0      2361 Härjedalen      23   Jämtlands län
>  Distance_1   Lat  Long
>       <num> <num> <num>
>           0 62.43 17.52
>           0 62.23 13.65
>           0 62.43 12.19

**Comment by rhijmans** [comment]
The messages suggest you have mare than one installation of PROJ. That causes problems. Remove the older version(s) and re-install terra. It is hard to help much as you do not provide any of the required information. What is your OS? You seem to be on Windows because of "AppData/Local/Programs/R" but it seems unlikely to get this error on that OS.  And the "~/" is unexpected on Windows. Also, how did you install terra?  From source? From CRAN?

**Comment by GuiSPinto** [comment]
Hi, 

sorry for the lack of information. The OS is actually Windows (10 Version 10.0.19045). I used the "~" and ".." just to keep some part of the login name and company information "blurred". I installed terra from CRAN, with the normal install.packages. I also just tried to remove and re-install terra, but there was no change. 

Within my R folder, there's only the "R-4.3.1" version, with only one rgdal folder with one proj folder as well. What do you mean with "remove the older version(s)"? Do you think that installing R4.3.2 would work?

And using the same command as above, but changing the crs input (from EPSG to PROJ.4) I get a warning, but I manage to get the coord. ref. included. Also, using PROJ.4 I can work with the functions properly. It's a bit of a hassle, but works...

> swe.grid <- vect("../R/shapefile/Data_grid_v1.shp", crs = "+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs")
> Warning message:
> PROJ: proj_identify: C:\Program Files\PostgreSQL\13\share\contrib\postgis-3.1\proj\proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation. (GDAL error 1)
> 
> swe.grid
>  class       : SpatVector 
>  geometry    : points 
>  dimensions  : 736, 11  (geometries, attributes)
>  extent      : 280000, 905000, 6150000, 7650000  (xmin, xmax, ymin, ymax)
>  source      : Data_grid_v1.shp
>  coord. ref. : +proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
>  names       : Key_ID FID_2       VEGZONSNA Distance KOMMUNKOD KOMMUNNAMN LANSKOD        LANSNAMN
>  type        :  <int> <int>           <chr>    <num>     <int>      <chr>   <int>           <chr>
>  values      :    369     5 Sydligt boreal~    339.5      2262      Timrå      22 Västernorrland~
>                   349     0       Alpin zon        0      2361 Härjedalen      23   Jämtlands län
>                   358     0       Alpin zon        0      2361 Härjedalen      23   Jämtlands län
>  Distance_1   Lat  Long
>       <num> <num> <num>
>           0 62.43 17.52
>           0 62.23 13.65
>           0 62.43 12.19

**Comment by FloFranz** [comment]
I get a similar error when trying to set CRS of a raster or change it using EPSG-Codes:

```
# using example raster file
f <- system.file("ex/elev.tif", package="terra")
r <- terra::rast(f)
terra::crs(r) <- 'EPSG:25832'
r_projected <- terra::project(r, 'epsg:25832')
```

Warning messages:
1: PROJ: proj_create_from_database: Cannot find proj.db (GDAL error 1) 
2: [crs<-] Cannot set raster SRS: empty srs

Same as @GuiSPinto there is no problem using PROJ.4:

```
terra::crs(r) <- '+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs'
```

I also work on a Windows machine. I already tried to solve the error by uninstalling PostgreSQL, because the error was slightly different before, pointing to my PostgreSQL installation. Something like this:

C:\Program Files\PostgreSQL\11\share\contrib\postgis-3.2\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation.

But it doesn't helped.

**Comment by rsbivand** [comment]
As far as `rgdal` is concerned, it should be: `remove.packages("rgdal")` at your earliest convenience. This also suggests that `raster` has not been updated since mid-2022, so `update.packages()` would also help. Workflows with non-updated `raster` will pull in `rgdal` and `rgeos`, and may re-set `PROJ_LIB` already set correctly by `terra`.

**Comment by GuiSPinto** [comment]
So, I removed `rgdal` and `rgeos`, updated `raster`, and removed and re-installed `terra`. The warning/error changed to this one: 

> swe.grid <- terra::vect("../R/shapefile/Data_grid_v1.shp", crs = "EPSG:3006")
> Warning messages:
> 1: PROJ: proj_identify: C:\Program Files\PostgreSQL\13\share\contrib\postgis-3.1\proj\proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation. (GDAL error 1) 
> 2: PROJ: proj_create_from_database: C:\Program Files\PostgreSQL\13\share\contrib\postgis-3.1\proj\proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation. (GDAL error 1) 
> 3: [crs<-] Cannot set SRS to vector: empty srs

**Comment by rhijmans** [comment]
Thank you for providing the additional details.  The problem appears to be that PostGIS sets the `PROJ_LIB` environment variable to point to its own installation of PROJ. See the seem issue [disccused at sf]( https://github.com/r-spatial/sf/issues/2298) that @kadyb refers to.  This temporary work-around was suggested:

```
plib <- Sys.getenv("PROJ_LIB")
prj <- system.file("proj", package = "terra")[1]
Sys.setenv("PROJ_LIB" = prj)

# and perhaps set it back so that you can use Postgres
Sys.setenv("PROJ_LIB" = plib)
```

**Comment by FloFranz** [comment]
Thank you for providing the work-around. That works. Interestingly, the problem persists even after uninstalling PostGIS (which I did). When I run:

`Sys.getenv("PROJ_LIB")`

it still refers to the proj folder in the PostGIS installation as part of PostgreSQL:

> "C:\\Program Files\\PostgreSQL\\15\\share\\contrib\\postgis-3.3\\proj"

**Comment by GuiSPinto** [comment]
Hi @rhijmans, 
thanks a lot for the work-around solution. It does work now. 

FYI, I need to re-run the work-around every time I work on R and before loading any package, otherwise I'm back on to the same warning/error.

**Comment by kadyb** [comment]
I have exactly the same problem on all faculty computers with Windows 10 where PostGIS is installed, but the [solution](https://github.com/rspatial/terra/issues/1378#issuecomment-1864893650) given by Robert works.

```r
# with fresh R installation
library("terra") # terra 1.8.29, binary version
Sys.getenv("PROJ_LIB")
#> [1] "C:\\Program Files\\PostgreSQL\\14\\share\\contrib\\postgis-3.2\\proj"

f = system.file("ex/elev.tif", package = "terra")
r = rast(f)
project(r, "EPSG:3857")
#> ERROR: [project] cannot get output boundaries for the target crs
#> Warning message:
#> 1: PROJ: proj_create_from_database: C:\Program Files\PostgreSQL\14\share\contrib\postgis-3.2\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 4 is expected. It comes from another PROJ installation. (GDAL error 1) 
#> 2: PROJ: proj_create_from_database: C:\Program Files\PostgreSQL\14\share\contrib\postgis-3.2\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 4 is expected. It comes from another PROJ installation. (GDAL error 1) 
#> 3: [project] Cannot set raster SRS: empty srs 
```

**Comment by Nowosad** [comment]
@kadyb -- some of the students also reported this issue to me today. Interestingly, that issue does not exist for `sf::st_transform()`.

**Comment by rsbivand** [comment]
`nad.lst` is present in `list.files(system.file("proj", package="terra"))` for the current Windows `terra` CRAN binary.

Assuming that PostgresDB is installed from EDB, and stack builder used to install PostGIS, the box for registering `PROJ_LIB` is checked by default. Actually, since PROJ 9.1 it should be `PROJ_DATA`. How was PostGIS installed in the lab?

If line 96 in `sf/R/init.R`: https://github.com/r-spatial/sf/blob/b9436af48fa6909ffae3b4f81b446e8715136f00/R/init.R#L96 succeeds, `PROJ_LIB` and `PROJ_DATA` work by following https://proj.org/en/stable/usage/environmentvars.html#envvar-PROJ_DATA, that is `sf` in R sets the handle in its GDAL runtime. `terra` seems to do something similar here: https://github.com/rspatial/terra/blob/e0ebf5f2861d950851be099d4daa7aae2caf69de/src/RcppFunctions.cpp#L423.

**Comment by Nowosad** [comment]
@kadyb -- could you check how the PostGIS was installed in the labs in Poznan (in my case students used their own computers and I do not have a way to know how this was done).

**Comment by kadyb** [comment]
I asked the IT department and PostGIS is installed in two ways:

1. Using binary versions from PostGIS (https://download.osgeo.org/postgis/windows/).
2. Using Stack Builder (https://www.enterprisedb.com/docs/supported-open-source/postgresql/installing/using_stackbuilder/).

I don't know exactly in which lab it was installed, but probably both methods don't work with `terra`. Moreover, students who installed PostGIS on their private laptops also have the same problem.

**Comment by rhijmans** [comment]
Can you try with the current development version? 

And more generally, do these function help?

```
library(terra)
terra:::.get_proj_search_paths()
terra:::.set_proj_search_paths("the path you want")
```

**Comment by rhijmans** [comment]
I installed PostgreSQL 17 & postgis-3.5 with the enterprisedb installer. 

But CRAN terra still returns 

```
terra:::.get_proj_search_paths()
#[1] "C:/soft/R/R-4.4.3/library/terra/proj"
```

So perhaps this problem has gone away with newer PostGIS (and your students also have older postGIS)? 

I can also do

``` 
terra:::.set_proj_search_paths("C:/Program Files/PostgreSQL/17/share/contrib/postgis-3.5/proj")
```

And things still work; but that is probably because postgis is also using 

```
terra:::libVersion("proj")
#[1] "9.5.1"
```

**Comment by kadyb** [comment]
I suspect most PCs in labs have PostgreSQL 14 and PostGIS 3.2. Tomorrow I will check the patch and `terra:::.get_proj_search_paths()`.

**Comment by kadyb** [comment]
@rhijmans, it seems this problem has returned in newer versions of terra (at least 1.9.1).
