### ISSUE TITLE
Cropping two specific vectors causes R fatal error

### ISSUE THREAD

**Issue by eragrostis** [rspatial/terra#1379]
Cropping these two particular vectors always causes a fatal error. I have no idea why as I've looped through about 200 of these operations with different locationsVect1 objects created by the same code and only two failed in this manner (let me know if you want the other one). I don't have the time to reduce this down to a more minimal example, but hopefully this example is reproducible (it is on my system) and will help you debug. 

Interestingly, if you were to change the order and crop(HI1, locationsVect1) then it does not fail.

Windows 11
R version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes"
terra 1.7.55

library(terra)
HI1 <- readRDS("HI.txt") #ignore the file extensions, changed them so github would let me upload
locationsVect1 <- readRDS("locationsVect.txt")

locationsVect <- crop(locationsVect1, HI1) #fatal error

[HI.txt](https://github.com/rspatial/terra/files/13721780/HI.txt)
[locationsVect.txt](https://github.com/rspatial/terra/files/13721781/locationsVect.txt)

**Comment by StephanLo** [comment]
I am experiencing the same behavior for terra::intersect() between specific vectors.
After closer inspection I noticed the fatal error occurred only for invalid polygons. I'm not sure if this the same issue as in @eragrostis case.
The validity of polygons can be checked using terra::is.valid() 
And if they are invalid they can sometimes be made valid by manually removing inner loops in the polygon. or automatically using is.valid() or the sf::st_make_valid() function.
 
But, I guess the fatal error is still maybe a bug? 

If I run my script in Visual Studio Code, I get the following exit code message:
![image](https://github.com/rspatial/terra/assets/33830195/f00b5b3b-8b40-4584-b293-6cefe95bda9a)
 
**System information:**
R version 4.3.0
Platform: x86_64-w64-mingw32/x64 (64-bit)
terra 1.7.29

**Comment by mhines-usgs** [comment]
I also am seeing terra::makeValid() crash my environment completely.. here's what I see on Linux, tried many a container, even in the r2u container unfortunately. But same code works OK on Windows which is maddening, so I feel like it's an environment issue... but r2u should have been the gold standard yah? or is it something _special_ about the poly file triggering it?

ms_poly_path is a path to this geodatabase file, uncompressed on disk - [WBD_National_GDB.zip](https://www.sciencebase.gov/catalog/item/60cb5edfd34e86b938a373f4) 

```r
wbd_ms <- fix_polygons_read(ms_poly_path, layer = "WBDHU12") |>
    tidyterra::select(ms_huc12 = HUC12) |>
    terra::makeValid() |>
    terra::project("EPSG:5070")
```

```
Backtrace:
1. targets::tar_make()
2. targets:::callr_outer(targets_function = tar_make_inner, targets_arguments = targets…
3. targets:::callr_dispatch(targets_function = targets_function, targets_arguments = ta…
4. targets:::if_any(is.null(callr_function), callr_inner(targets_function = targets_fun…
5. base::do.call(callr_function, callr_prepare_arguments(callr_function, …
6. (function (func, args = list(), libpath = .libPaths(), repos = default_rep…
7. callr:::get_result(output = out, options)
8. callr:::throw(new_callr_crash_error(output, killmsg))
Execution halted
```

Dockerfile ->

```
FROM artifactory.wma.chs.usgs.gov/docker-official-mirror/rocker/r2u:22.04
 
RUN apt-get update \
    && apt-get install -y \
        libxml2-dev \
        libglpk-dev \
        libudunits2-dev \
        libxt-dev \
        libgdal-dev \
        libgeos-dev \
        libproj-dev \
        libsodium-dev \
        libarchive-dev \
        libsqlite3-dev \
    && apt-get install -y --no-install-recommends \
        awscli \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/*log /var/log/apt/* /var/lib/dpkg/*-old /var/cache/debconf/*-old \
    \
    && install2.r --error \
        fs \
        dplyr \
        targets \
        tarchetypes \
        readr \
        tidyr \
        yaml \
        sbtools \
        assertthat \
        stringr \
        Hmisc \
        data.table \
        tidyverse \
        secret \ 
        jsonlite \
        tidytable \
        units \
        sf \
        purrr \
        tibble \
        archive \ 
        cli \
        Rcpp \
        terra \
        tidyterra 
```

**Comment by rhijmans** [comment]
The example works now. I think this bug was fixed at some point, but I am not sure when or how.
