### ISSUE TITLE
Rgui crashes on an (erroneous) call to focal

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#138]
When calling `focal` with an even value of `w`, Rgui crashes. According to the help page, this is an erroneous call, but it would be better to get an error message than lose everything.

```
r <- rast(ncols=10, nrows=10, ext(0, 10, 0, 10))
values(r) <- 1:ncell(r)

# OK
f <- focal(r, w=3, fun="mean") 

# Rgui crashes
f <- focal(r, w=4, fun="mean") 
```

**Comment by rhijmans** [comment]
Thank you very much!
