### ISSUE TITLE
Equivalent to raster's function setZ

### ISSUE THREAD

**Issue by nikosGeography** [rspatial/terra#1380]
I would like to ask if there is an equivalent to [setZ](https://search.r-project.org/CRAN/refmans/raster/html/zvalues.html) from the raster package in terra.

**Comment by rhijmans** [comment]
You can use `time<-`

**Comment by nikosGeography** [comment]
I am getting the following error 
```
Error in UseMethod("time<-") : 
  no applicable method for 'time<-' applied to an object of class "SpatRaster"
```

when I try to apply the `time` function to a raster stack with 12 raster.

Here is an example code:

```
spatraster <- rast(nrows = 10, ncols = 10, nlyr = 12)
time(spatraster, tstep="months") <- 1:3
```

or 

`time(spatraster) <- seq(as.Date("2019-01-01"), as.Date("2019-12-01"), by = "month")`

**Comment by rhijmans** [comment]
Another package probably hides it. If so, it may work with 

```
terra::time(spatraster) <- seq(as.Date("2019-01-01"), as.Date("2019-12-01"), by = "month")
```

`stackoverflow.com` is appropriate place to ask this type of "how-to" questions.
