### ISSUE TITLE
Exend not working consistently

### ISSUE THREAD

**Issue by mem48** [rspatial/terra#1383]
I have a problem when using `terra::extend` where the returned raster has a slightly different extent than expected

For example:

```
# Load required packages
library(terra)

# Create input rasters
r1 <- rast(
  ncol = 1000
  , nrow = 852
  , xmin = 317296
  , xmax = 319000
  , ymin = 1e+06
  , ymax = 1002000
)
values(r1) <- runif(ncell(r1))

r2 <- rast(
  ncol = 500
  , nrow = 497
  , xmin = 318007
  , xmax = 319001
  , ymin = 1002000
  , ymax = 1003000 
)
values(r2) <- runif(ncell(r2))

# Define the extent of both rasters
e = ext(c(min(e1[1],e2[1]),max(e1[2],e2[2]),min(e1[3],e2[3]),max(e1[4],e2[4])))

# extend both rasters to cover the combined extent
r1e = extend(r1, e)
r2e = extend(r2, e)

# Compare extents
ext(r1e) == ext(r2e) # False
ext(r1e) == e       # True
ext(r2e) == e       # False

```

My use case is having partially overlapping rasters that I want to combine into a single larger raster. In most cases, the method above works fine but in a few cases, this error occurs.

**Comment by rhijmans** [comment]
That is expected. You can only add entire rows and columns, not fractions. Therefore, extend cannot guarantee to return a SpatRaster with exactly the requested extent. I have added some test to the manual.  

```
library(terra)
r1 <- rast(ncol = 1000, nrow = 852, xmin = 317296, xmax = 319000, ymin = 1e+06, ymax = 1002000)
r2 <- rast(ncol = 500, nrow = 497, xmin = 318007, xmax = 319001, ymin = 1002000, ymax = 1003000)

e <- union(ext(r1),  ext(r2))
r1e <- extend(r1, e)
r2e <- extend(r2, e)

e
#SpatExtent : 317296, 319001, 1e+06, 1003000 (xmin, xmax, ymin, ymax)
ext(r1e)
#SpatExtent : 317296, 319001.704, 1e+06, 1003000 (xmin, xmax, ymin, ymax)
ext(r2e)
#SpatExtent : 317295.296, 319001, 1e+06, 1003000 (xmin, xmax, ymin, ymax)


round(origin(r2), 6)
#[1] 0.556 0.000
round(origin(r1), 6)
#[1] -0.728  0.000
```

As you can see, the extents are very similar. But since the origins of the rasters are not the same you cannot give them the same geometry with extend.

**Comment by mem48** [comment]
Thanks @rhijmans for the explanation, it now makes sense.  It might be worth adding a warning to `extend` for cases when the output does not perfectly match the input.
