### ISSUE TITLE
panel=TRUE breaks plet()

### ISSUE THREAD

**Issue by elisehellwig** [rspatial/terra#1384]
Hi,

I noticed that when I set `panel=TRUE` inside `plet()` I get the error

> Error in make.panel(x, maxcell) : object 'nl' not found

This happens using the following code. And it the code works fine if I remove `panel=TRUE`.

```
library(terra)

elev_fn = system.file("ex/elev.tif", package="terra")

elev = rast(elev_fn)

elev2 = c(elev, elev*1.1)

plet(elev2, y=1:2, panel=TRUE)

```

My session info is below. 

Thanks,
Elise

R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.0

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.7-67

loaded via a namespace (and not attached):
[1] compiler_4.3.2   tools_4.3.2      Rcpp_1.0.11      codetools_0.2-19

**Comment by rhijmans** [comment]
Thanks! This works now.

**Comment by elisehellwig** [comment]
Thanks!
