### ISSUE TITLE
Large raster datasets predictions: fatal error and session aborted

### ISSUE THREAD

**Issue by filrat2** [rspatial/terra#1386]
Hi, I try to make predictions on large raster datasets (10–20 band rasters with a size of around 3-6 GB) with terra package, but I always get fatal errors and the R session is aborted.

![problem](https://github.com/rspatial/terra/assets/81258303/6f857ff3-f23d-4579-818a-323586369af1)

I have autotuned random forest (ranger) models from mlr3 package and 32 GB of RAM in my machine. I work under Windows 10 and R 4.3.2.

Here is the code from prediction with terraOptions(verbuse = TRUE):
```
> pred = terra::predict(multiband_raster, model = autotuner_rf)
filename      : C:/Users/Dell 3620/AppData/Local/Temp/Rtmpqs4XHf/spat_Oo6ZPX1PfuWIttF_2356.tif
compute stats : 1, GDAL: 0, minmax: 0, approx: 1
driver        : GTiff
disk available: 38.6 GB
disk needed   : 0.4 GB
memory avail. : 28.54 GB
memory allow. : 17.12 GB
memory needed : 35.93 GB  (40 copies)
in memory     : false
block size    : 3139 rows
n blocks      : 4
pb            : 3
```
I know that it is a problem with the amount of RAM (I have too little RAM in my machine), but is there another way to make predictions on large raster datasets with only 32 GB of RAM? I can paste here more information about my R environment, machine, or all of my code.

**Comment by rhijmans** [comment]
You can reduce memory use with `terraOptions`. Alternatively, you can use `wopt=list(steps=10)` to set the number of blocks directly. I would need a small reproducible example to say more about this particular case (even that example does not crash, as this will likely be RAM-dependent). It seems to me that the appropriate place for this question is stackoverflow. Also, please do not include screenshots; they are very hard to read and use. Just include code and things that are printed on the console.

**Comment by rhijmans** [comment]
Closing as this was also posted on [stackoverflow](https://stackoverflow.com/questions/77718581/large-raster-datasets-predictions-with-r-terra-and-mlr3-fatal-error-and-sessio)

**Comment by filrat2** [comment]
@rhijmans Dear Robert, sorry for the open issue here, I don't have a lot of experience with GitHub and stackoverflow yet. The way proposed by you (wopt=list(steps=10)) works good, after adding this parameter, everything is right. Thanks for your help, and once again, sorry for the open issue here.
