### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by mablmabl** [rspatial/terra#1389]
In terra::vect() I lack a possibility to include an option for encoding similar to sf::st_read(x,options = "ENCODING=WINDOWS-1252"). 

Why? 
I have Windows-1252 encoded shapefiles and want to open directly with vect instead of current workaround via st_read and conversion to SpatVector. If opening with vect today the swedish letters åäö will be wrong (e.g. "fiskefria omr\xe5den" instead of "fiskefria områden"

My versions:

packageVersion("terra") [1] ‘1.7.65’

R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

locale:
[1] LC_COLLATE=Swedish_Sweden.utf8  LC_CTYPE=Swedish_Sweden.utf8    LC_MONETARY=Swedish_Sweden.utf8
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.utf8

**Comment by rhijmans** [comment]
I can now do 

```
v <- vect(f, opts="ENCODING=WINDOWS-1252")
```

Can you test if it works as expected?

**Comment by mablmabl** [comment]
Yes it works as I expected. Many thanks for fixing this :-)
