### ISSUE TITLE
Documentation of plotRGB

### ISSUE THREAD

**Issue by jebyrnes** [rspatial/terra#1390]
Might I suggest adding that the minq = 0.02 and maxq = 0.98 in documentatoin regarding the default stretch for `plotRGB()`. I just killed an hour or two trying to figure out why `plot(my_rast, stretch = "lin")` and `plot(stretch(my_rast))` looked different.

(for those of us who are teaching the package in particular!)

**Comment by rhijmans** [comment]
Done, and sorry about that.
