### ISSUE TITLE
Using `predict` to only write a single binary classes probability to disk [FEATURE REQUEST]

### ISSUE THREAD

**Issue by sagesteppe** [rspatial/terra#1392]
I am wondering whether it is feasible to support only writing the probabilities of a single class to a raster on disk? I suspect this would be useful for those predicting SDM's and wanting probabilities rather than the binary predictions. Across very large domains or fine grains, I suspect writing both probabilities is time intensive and, and for several applications redundant . 

Thanks

**Comment by rhijmans** [comment]
That is supported. You can write to disk whatever you like.  See argument `fun`. Hard to say more without more context (what type of model?). I would suggest making a *self-contained, minimal, reproducible example* and ask your question on stackoverflow.com (unless it has already been asked and answered there).
