### ISSUE TITLE
raster coarsens when added to smaller-extent map

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1394]
In some circumstances, when a raster map is added to a smaller-extent vector map, it is plotted at a coarser resolution, without a warning or message. This may be undesirable, and it doesn't appear to be documented. Here's a reproducible example:

```
v <- geodata::gadm("Greenland", level=1, path=tempdir())

r <- geodata::worldclim_country("Greenland", var="wind", path=tempdir())
r <- r[[1]]

# plot raster over smaller extent:
plot(r, ext=ext(v[1, ]))  # OK
plot(v[1, ], add=TRUE)

# add raster to smaller-extent vector:
plot(v[1, ])
plot(r, add=TRUE)  # coarser pixels!
```

**Comment by rhijmans** [comment]
Thanks.  When using "add=TRUE" the raster data was sampled without considering the extent of the map.  That was not intentional. Fixed now.
