### ISSUE TITLE
puzzling outcome plotting multilayer raster with add=TRUE

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1395]
When we (possibly unknowingly) try to add a multilayer raster to a map, the result is quite puzzling:

```
v <- vect(system.file("ex/lux.shp", package="terra"))
r <- geodata::worldclim_country("Luxembourg", var="wind", path=tempdir())
plot(v)
plot(r, add=TRUE)
```
![image](https://github.com/rspatial/terra/assets/12085508/285a9b80-dddd-4882-98cb-55e5b1f1ee1c)

I think it would be useful to add a check for multilayer raster when add=TRUE, in which case add just the first layer with a message like "_Map has more than one layer; adding just the first one_". Cheers!

**Comment by rhijmans** [comment]
Fixed as suggested. Thanks again and please keep them coming in 2024!
