### ISSUE TITLE
vars argument of query() does not work in some cases

### ISSUE THREAD

**Issue by erkent-carb** [rspatial/terra#1398]
Hi. I am using terra version 1.7.46 on Windows 10. 

When trying to use both the filter and vars arguments of query() , the vars argument does not appear to work (i.e., all the column names are reflected in the output, not just the ones specified in vars). This also appears to occur in other cases where the start and/or n arguments are also not supplied. This behavior does not appear to be reflected in the documentation.   

An example from the documentation that works as expected: 

```
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f, proxy=TRUE)
v

# original example in the documentation of query function
x <- query(v, vars=c("ID_2", "NAME_2"), start=5, n=2)
# only columns specified in vars are there: it works as expected
x
```

Examples where the vars argument does not have the expected effect on the output: 

```
# removing the start and n arguments
x2 <- query(v, vars=c("ID_2", "NAME_2"))
# all columns are in the output: vars argument doesn't work
x2

# another example, using the filter argument (what I ultimately want to do)
x3 <- query(v, vars=c("ID_2", "NAME_2"), filter = x )
# again, all columns are in the output: vars argument doesn't work
x3
```

For datasets that are not too large I can remove unnecessary columns after the query, but for large datasets it would be very helpful to be able to only read desired columns into memory.

**Comment by rhijmans** [comment]
Thank you very much for reporting this bug. I now get 

```
x3
# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 7, 2  (geometries, attributes)
# extent      : 5.74414, 6.528252, 49.58699, 50.18162  (xmin, xmax, ymin, ymax)
# source      : lux.shp
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       :  ID_2   NAME_2
# type        : <num>    <chr>
# values      :     1 Clervaux
#                   2 Diekirch
#                   3  Redange
```

**Comment by erkent-carb** [comment]
I get the expected output now too, thanks!
