### ISSUE TITLE
analog to raster::buffer()?

### ISSUE THREAD

**Issue by cjcarlson** [rspatial/terra#14]
Hi - I'm so excited to try terra! I'm just wondering, is there a faster alternative to raster::buffer() in terra? We're doing a project with ~20,000 SDM buffers and it's taking months of computing time. If there's a way to even cut down some of that runtime with terra, that would be a lifesaver... thanks! (Sorry if I've missed something obvious)

**Comment by cjcarlson** [comment]
Sorry, realizing this may have been a stupid question with terra::gridDistance, which would mostly do it - but it seems like the longlat/meters functionality isn't in there yet, or am I misreading the documentation?

**Comment by rhijmans** [comment]
I have now implemented a `distance` method but still with a naive algorithm; so I am not if the speed is good enough. Will work on improving that in the near future.

**Comment by cjcarlson** [comment]
Thank you! I'll write a temporary buffer() analog that uses distance and boundaries - that should probably still be faster than raster::buffer() I suspect

**Comment by rhijmans** [comment]
I have also added a buffer method. Please do some spot checks the results of these new functions (e.g. compare with "raster" for a few species.

**Comment by cjcarlson** [comment]
Thank you!!! That's so nice of you. I'll check it out!
