### ISSUE TITLE
terra::expand does not add the specified number of rows and columns. 

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#140]
According to the help page, in `expand`, "you can provide a numeric vector of length 2 indicating the number of rows and columns that need to be added". Thus, the example given in the help page, and reproduced below, should add 2 rows and 10 columns (on each side). But it adds 10 rows, and 8 columns (5 rows and 4 columns on each side). It does not seem to work properly. I have tested for some other values. The function adds to rows one time the number of columns specified, and it adds to columns four times the number of specified rows.

```
r <- rast(xmin=-150, xmax=-120, ymin=30, ymax=60, ncol=36, nrow=18)

# expand with a number of rows and columns (at each side)
re2 <- expand(r, c(2,10))

# 10 rows added, not 2*2 as expected
nrow(re2)-nrow(r)
# [1] 10  

# 8 columns added, not 2*10 as expected
ncol(re2)-ncol(r)
# [1] 8
```

**Comment by rhijmans** [comment]
Thanks, this now works:

```
library(terra)
r <- rast(xmin=-150, xmax=-120, ymin=30, ymax=60, ncol=36, nrow=18)
re2 <- expand(r, c(2,10))
dim(re2)-dim(r)
#[1]  4 20  0
```

But note that the rows and columns are added at each side. So effectively you are always adding twice the number specificied. I have expanded the documentation to clarify that.
