### ISSUE TITLE
Use GitHub Releases and tags 

### ISSUE THREAD

**Issue by mfansler** [rspatial/terra#1404]
What commits correspond to CRAN versions are opaque due to lack of consistent use of tags and GitHub Releases. Please consider being more diligent about using these features to generate metadata.

**Comment by rhijmans** [comment]
If you want me to do something for you, it would help if you provided a motivation.

**Comment by mfansler** [comment]
Concretely, I needed a bisection for when `terra::readRDS` was introduced because another package started using it without declaring a minimum version. I ended up using [the CRAN mirror](https://github.com/cran/terra), which has the releases tagged. Nothing major - just something to make it easier to view the state of the repository at a given release.

**Comment by rhijmans** [comment]
OK, that makes sense; but I am not great at that type of housekeeping. And the CRAN mirror is as good as it gets for this purpose. 

For your use case you could also look at the [NEWS file](https://raw.githubusercontent.com/rspatial/terra/master/NEWS.md) according to which `writeRDS`/`readRDS` were first introduced in version 1.5-34 (2022-06-09).
