### ISSUE TITLE
Display ID (row number) in console with terra::click?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#1405]
A possible minor improvement to the `click` function, which is very useful: it would be interesting to display the sequence number of clicked points (i.e. their row number) in the console, especially when acquiring values at a large number of points. At present, the number displayed at the beginning of the line, for each click, remains 1. This would help the operator to know where he is in the progress of the capture process. It is possible to display it on the plot (map) with `id=TRUE`, but it would be useful to have it in the `console` window too, when you don't want to overload the `plot` window. It does not have to be an option.

```
r <-rast(system.file("ex/elev.tif", package="terra"))
plot(r)
c <- click(r,n=2,xy=TRUE,cell=TRUE,id=TRUE)
# row number remains at 1, would be more informative if incremented:
#          x        y cell elevation
# 1 5.945833 49.89583 3350       446
#          x       y cell elevation
# 1 6.129167 49.7875 4607       289
c
#          x        y cell elevation
# 1 5.945833 49.89583 3350       446
# 2 6.129167 49.78750 4607       289
```

**Comment by rhijmans** [comment]
Thanks, I think this now works as you suggested.
