### ISSUE TITLE
issue with spatSample when na.rm=T and replace=T!

### ISSUE THREAD

**Issue by babaknaimi** [rspatial/terra#1411]
Dear Robert,

I just realised that the argument of replace=TRUE in spatSample seems not to work appropriately when na.rm = TRUE. Here is an example:

f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
s <- spatSample(r, 10000, replace=TRUE,na.rm=TRUE)
Warning message:
[spatSample] more non-NA cells requested than available 

nrow(s) # the number is the total non-NA pixel (the same as replace=F)

# the terra version is 1.7-55 (Mac OS)

**Comment by rhijmans** [comment]
Hi Babak, thank you very much for reporting this. Fixed now.
