### ISSUE TITLE
Spatrasters won't plot

### ISSUE THREAD

**Issue by qldsleo** [rspatial/terra#1412]
Hello,

I'm having issues plotting large cloud optimised geotiffs using terra.
I've just updated R to version 4.3.2 and was previously using 4.0.5.
I didn't have any issues plotting the geotiffs using the old R version.
Now it won't plot and remains processing indefinitely.

This is my code:
library(terra); library(paletteer)
setwd()
r_files = list.files(pattern='.tif', full.names=T)
r = rast(r_files[c(1,5,3,4,6,2)]) # reorder
names(r) = c('0-5 cm', '5-15 cm', '15-30 cm', '30-60 cm','60-100 cm', '100-200 cm')
plot(r, col=paletteer_c('grDevices::Spectral', 30), box=F,
     range=c(0,90), axes=F)

plot(r[[1]]) won't even work. Neither will reducing the cells using maxcells.
Any help would be great.

Thanks!

**Comment by kadyb** [comment]
Maybe it's related to the change in https://github.com/rspatial/terra/issues/1088#issuecomment-1512422144?

**Comment by qldsleo** [comment]
Potentially. Do you know how I would be able to force it to read from the actual data instead of the overviews?

**Comment by rhijmans** [comment]
Can you share, if need be privately, an example file?

**Comment by kadyb** [comment]
Sorry @rhijmans for bothering you, but could you look into this issue when you find some free time?

**Comment by rhijmans** [comment]
Sorry that it took me so long. I now get 

```
library("terra")
url = "/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/55/G/DM/2023/12/S2A_55GDM_20231230_0_L2A/B02.tif"
x = terra::rast(url)
system.time(plot(x))
#   user  system elapsed 
#   0.53    0.11    0.89 
```

**Comment by kadyb** [comment]
Thank you very much and all the best in the New Year!
