### ISSUE TITLE
`alpha` parameter of `polys()` doesn't work

### ISSUE THREAD

**Issue by dfriend21** [rspatial/terra#1413]
The `alpha` parameter of `polys()` isn't working - below is an example demonstrating that alpha works for `plot()` but not for `polys()`.

``` r
library(terra)
#> terra 1.7.65
v <- vect(system.file("ex/lux.shp", package = "terra"))

# works
plot(v, col = "red", alpha = .1)
```

![](https://i.imgur.com/fUretRH.png)

``` r

# doesn't work
plot(ext(v), border = "transparent")
polys(v, col = "red", alpha = .1)
```

![](https://i.imgur.com/pSNwUew.png)

<sup>Created on 2024-01-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Fixed, thank you.
