### ISSUE TITLE
Name of argument align in terra::project is confusing

### ISSUE THREAD

**Issue by see24** [rspatial/terra#1416]
In `project()` there is an argument named `align` which has confused me before and recently confused a colleague. I see from issue #388 that the argument was added to give the option to align the extent with the input but I have found the name confusing. 

With default arguments if y is a SpatRaster `project` will change the CRS and align the extent, resolution and origin with y. 
If align = TRUE then the same is done except the extent is not aligned with y but instead is set such that all of x is included. 

For a typical use case where you want to combine x and y in a future step the default is what you want. However, myself and a colleague have been confused by the name of the align argument because we know we want the output to be both projected and aligned with y, so without carefully reading the documentation we set align = TRUE and then are frustrated when the result is in fact not aligned with y unless align = FALSE. 

Would it be possible to change the argument name to something like align_x, align_x_ext, or match_x_ext so that the argument name more clearly evokes what the argument does?

**Comment by rhijmans** [comment]
Thanks. I have renamed it to "align_only" to better express what it does. This way, scripts that use "align" still work.
