### ISSUE TITLE
terra::rasterize cover=TRUE doesn't seem to work with spatRast and spatVect (polygon)

### ISSUE THREAD

**Issue by ChrisJones687** [rspatial/terra#142]
Not sure if this is by design since it is left out of the documentation in some locations.

I was hoping that it would perform similarly to getCover in raster::rasterize which works with the same data but is very slow. Would be happy to assist in implementation if it is a desired feature. I can provide a reproducible example if that is helpful.

**Comment by rhijmans** [comment]
I think what you are looking for is not available in the CRAN version, but was already available in the development version

```
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
r <- rast(v, ncol=75, nrow=100)
x <- rasterize(v, r, "NAME_2", cover=TRUE)
```

**Comment by ChrisJones687** [comment]
Yes, this is exactly what I wanted. Thank you for pointing out that it works in the development version. I will use that going forward.

**Comment by aloboa** [comment]
cover is not documented.
Also:
`> rm(r)
> library(terra)
> f <- system.file("ex/lux.shp", package="terra")
> v <- vect(f)
> r <- rast(v, ncol=15, nrow=20)
> dim(r)
[1] 100 107   1`
Should dim(r) not be 20, 15, 1 ?

**Comment by rhijmans** [comment]
`cover` is documented in the _development version_   (currently version 1.1.2). 

With that version, I also get the expected dimensions:
 
```
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
r <- rast(v, ncol=15, nrow=20)
dim(r)
#[1] 20 15  1
```
