### ISSUE TITLE
Manual caption of terrain() cutoff

### ISSUE THREAD

**Issue by eragrostis** [rspatial/terra#1420]
In the manual page for terrain a paragraph says:

"TRIriley (TRI according to Riley et al. (2007)) returns the square root of summed squared differences between the value of a cell and its 8 surrounding cells. TRIrmsd computes the square root of the mean of the squared differences between these cells. The benefit of TRIrmsd"

e.g. https://search.r-project.org/CRAN/refmans/terra/html/terrain.html

This is clearly cut off at the end. What is the benefit?

**Comment by rhijmans** [comment]
I have removed the cut-off sentence. I do not remember what I wanted to say.
