### ISSUE TITLE
Can't delete buffer aroun inset() function

### ISSUE THREAD

**Issue by Armand-CT** [rspatial/terra#1422]
I'm using `inset()` function to add a location map to a `plot()` and adding the argument `buffer = F` to delete it and make the perimeter displaied match exactly the extent of the inset SpatVector. The `buffer` argument doesn't seem to work. Example:

`inset(world_crop, box = ext, col = "wheat2", background = "lightblue2", buffer = F)`

**Comment by rhijmans** [comment]
If have added arguments "offset=0.1" that allows changing the distance between the box and the scaled version of `x`. I have also added argument "add=TRUE". You can set it to "FALSE" and then do as you please.

**Comment by Armand-CT** [comment]
I've been trying to make it work but still doesn't find the solution.. If use the code with `offset = 0.1` the program returns me warnings:
`inset(mosca_crop, loc = "topright", col = "wheat2", lwd = 0.25, perimeter = T, box = ext(mdt_main_crop), pbox = list(col = "red"), offset = 0.1)`
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In graphics::polypath(g[[i]][[j]][[1]], g[[i]][[j]][[2]],  ... :
  "offset" is not a graphical parameter

![image](https://github.com/rspatial/terra/assets/159435352/90dd9c53-47f2-4d75-8083-3787ffab9f68)

And with `add` I get an error:
`inset(mosca_crop, loc = "topright", col = "wheat2", lwd = 0.25, perimeter = T, box = ext(mdt_main_crop), pbox = list(col = "red"), offset = 0.1, add = TRUE)`
Error in .local(x, y, ...) : 
  formal argument "add" matched by multiple actual arguments
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by kadyb** [comment]
@Armand-CT, did you update the package to dev version? This change is not yet available on CRAN. On Windows and macOS you can install this way:

```r
install.packages('terra', repos = "https://rspatial.r-universe.dev")
```

**Comment by Armand-CT** [comment]
Oh, I was updating it but as you say I wasn't working on the dev version. Works now, thanks!
