### ISSUE TITLE
sum across rasters does not ignore NA 

### ISSUE THREAD

**Issue by anjelinejeline** [rspatial/terra#1424]
Hi
I would like to sum a set of rasters I stored as sds to obtain a unique raster where each pixel is the sum of the pixels of the individual rasters however the function app seems to ignore the option na.rm=tTRUE and it returns me a raster where for some pixel I have NaN values which is strange given that at leat 1 individual raster contains data.. 
Could you help me with that? 
```

myrasters=list.files(path="./Rasters/", 
                     pattern=".tiff*",full.names = TRUE) |> map(\(x)rast(x))

myrasters_sds=sds(myrasters)

myrasters_sum=app(myrasters_sds,fun="sum",na.rm=TRUE)
```

**Comment by rhijmans** [comment]
I do not see that:

```
library(terra)
s1 <- rast(system.file("ex/logo.tif", package="terra"))   
s2 <- s3 <- s1 
s1[1:60, ] <- NA
s2[1:30, ] <- NA
s3[1:15, ] <- NA
x <- sds(s1, s2, s3)

r <- app(x, fun="sum", na.rm=TRUE)
plot(r)
```

And since you do not show the problem through an example, I have no way to address this bug, if it indeed exists.

**Comment by anjelinejeline** [comment]
Hi @rhijmans you are right the sum is not the issue... 
I am sorry that I have not checked the original rasters before but it seems that something is wrong with the projection of one of them... 
Before calculating the sum I transformed each individual raster using the function project .. however I noticed just now that one of the transformation gives me the following error .. 
do you know how can I sort this out? 
The transformation using the same template worked well for the other rasters 

**Too many points (529 out of 529) failed to transform, unable to compute output bounds. (GDAL error 1)**

```
r=rast("r.tif")
template=rast("template.tif")
r=project(r,template)
Warning messages:
1: Too many points (529 out of 529) failed to transform, unable to compute output bounds. (GDAL error 1)
```
