### ISSUE TITLE
Compilation of terra on suse 15

### ISSUE THREAD

**Issue by fvalenduc** [rspatial/terra#1429]
I am trying to install terra on suse 15. It seems to compile correctly, but it finally fails with this error:

** building package indices
** testing if installed package can be loaded from temporary location
sh: line 1:  2103 Aborted                 (core dumped) R_TESTS= '/usr/lib64/R/b                                                                                                                                                             in/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpeBSz6U/file43922411057'
double free or corruption (out)
ERROR: loading failed
* removing ‘/home/cpi-user/R/x86_64-suse-linux-gnu-library/4.3/terra’

The downloaded source packages are in
        ‘/tmp/RtmpveYSm8/downloaded_packages’
Warning message:
In install.packages("terra") :
  installation of package ‘terra’ had non-zero exit status

Does anybody understand what is happening ?

**Comment by rhijmans** [comment]
I do not know what causes this. But I would first look at GDAL and PROJ. Are they up to date and is there only a single version of each?
