### ISSUE TITLE
terra::vect fails to convert an sf MULTIPOLYGON

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#144]
Here is a case where `terra::vect` fails to correctly convert an `sf` `MULTIPOLYGON` to a `SpatVector`. It works if `pol` is built as a `POLYGON`.

```
library(terra)
# terra version 1.0.13

library(sf)

p1 = matrix(c(-50,-100,50,-100,150,50,0,50,-50,-100),ncol=2, byrow=TRUE)
h1 = matrix(c(79,12,56,6,92,8,79,12),ncol=2, byrow=TRUE)
h2 = matrix(c(3,-58,14,-59,18,-37,3,-58),ncol=2, byrow=TRUE)
pol = st_multipolygon(list(list(p1,h1,h2)))

PolSf=st_sf(st_sfc(pol,check_ring_dir = TRUE))

plot(PolSf,col="grey",axes=T)
```
![image](https://user-images.githubusercontent.com/42430070/106366291-229f0800-633b-11eb-9d6f-287c97124f56.png)

```
PolTerr <- vect(PolSf)
plot(PolTerr,col="grey")
```
![image](https://user-images.githubusercontent.com/42430070/106366298-3185ba80-633b-11eb-8f2f-e0cf48b7c3ab.png)

**Comment by rhijmans** [comment]
Thank you very much. Fixed now.
