### ISSUE TITLE
Error in `extract`

### ISSUE THREAD

**Issue by stla** [rspatial/terra#1442]
Hello,

I think there's a coding error in the `extract` function.

When you do
```r
extract(x, y, fun, bind = TRUE)
```
where `x` is `SpatRaster` and `y` is `sf`, then `extract` does:
```r
y <- vect(y)
extract(x, y, ......)
```
Now `y` is `SpatVector`. In the `extract` method for such types, there is:
```r
        if (bind) {
            if (nrow(e) == nrow(y)) {
                e <- cbind(y, e[, -1, drop = FALSE])
            }
            ......
```
And this call to `cbind` throws the error: `inherits(y, "data.frame") is not TRUE`. Indeed, `y` is no longer a dataframe.

I think one can get the expected output of `extract(x, y, fun, bind = TRUE)` without errors by doing:
```r
e <- extract(x, y, fun, bind = FALSE)
```
and then doing
```r
cbind(y, e[, -1, drop = FALSE])
```
Not sure, I'm absolutely not familiar with **terra**.

**Comment by daviskec** [comment]
I'm getting an unrelated error in `extract` which I wasn't as recently as last week.

When I got to extract values from an elevation raster (in SpatRaster format) at points (in either `sf` or `SpatVector` format, I've tried both), I get the following error:

`Error in .pmatch(x, table = lowerTable, useFirst = useFirst, error = error) : 
  Cannot find a match.`

My code worked as recently as last week. I've tried updating the package and I appear to have the most recent version (1.7-71).

**Comment by rhijmans** [comment]
I cannot reproduce this problem. For example, I get:

```
x <- rast(system.file("ex/elev.tif", package="terra"))
v <- vect(system.file("ex/lux.shp", package="terra"))[,c(2,4)]
s <- sf::st_as_sf(v)
se <- extract(x, s, mean, na.rm=TRUE, bind=TRUE)
se
# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 12, 3  (geometries, attributes)
# extent      : 5.74414, 6.528252, 49.44781, 50.18162  (xmin, xmax, ymin, ymax)
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       :   NAME_1   NAME_2 elevation
# type        :    <chr>    <chr>     <num>
# values      : Diekirch Clervaux     467.1
#               Diekirch Diekirch     333.9
#               Diekirch  Redange     377.4
```

**Comment by stla** [comment]
```r
se <- extract(x, s, function(x) list(mean(x), sd(x)), bind=TRUE)
Erreur dans cbind(deparse.level, ...) : 
  inherits(y, "data.frame") n'est pas TRUE
```
But no error with `bind = FALSE`.

**Comment by rhijmans** [comment]
I now get:

```
se <- extract(x, s, function(x, ...) c(mean(x, ...), sd(x, ...)), bind=TRUE, na.rm=T)
se
# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 12, 4  (geometries, attributes)
# extent      : 5.74414, 6.528252, 49.44781, 50.18162  (xmin, xmax, ymin, ymax)
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       :   NAME_1   NAME_2 elevation elevation.1
# type        :    <chr>    <chr>     <num>       <num>
# values      : Diekirch Clervaux     467.1       34.58
#               Diekirch Diekirch     333.9       68.03
#               Diekirch  Redange     377.4       77.14
```

**Comment by stla** [comment]
Ah ok. So the function must return an atomic vector. In fact I discovered this issue by helping a guy on StackOverflow, and he used a function returning a list.

But what if one wants to compute two values of different modes? (eg numeric and character). Maybe that makes no sense? (again I'm not familiar with **terra**)

**Comment by stla** [comment]
I've just tried your code and I get the error. I didn't understand you fixed the bug... Thanks.

**Comment by kadyb** [comment]
I tried the code posted by Robert and it works for me. Have you updated the package to dev version from GitHub or R-universe?
