### ISSUE TITLE
Report versions of spatial dependencies on load?

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#1444]
Currently, `sf` reports GDAL, GEOS and PROJ versions when loading. Maybe it would make sense for `terra` to do this too? I think it would help a bit with problems like [this](https://github.com/rspatial/terra/issues/1439).

```r
library("sf")
#> Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
```

**Comment by rhijmans** [comment]
I have added a request to add what is returned by `terra::gdal(lib="all")` to the issue template.

I don't like the clutter of startup messages very much. "terra" prints the package version for this reason, but I am inclined to eventually remove that as well now that the package has become more stable.
