### ISSUE TITLE
`rasterize` argument `fun = mean` doesn't appear to work

### ISSUE THREAD

**Issue by jflowernet** [rspatial/terra#1449]
Apologies if I am misunderstanding how the `rasterize(fun = )` argument works, but it seems like setting `fun = mean` does not seem to produce the expected output. The reprex below demonstrates, but where there are raster cells that intersect more than one polygon that is being rasterized, I expected those cells to be the (area weighted?) mean of the intersected polygons when `fun = mean`. So in the reprex, cells along the edges of the polygons would have differing values to those entirely within the polygons, but this is not the case. Instead, it looks like the the `fun` argument is being ignored.

``` r
library(terra)
#> terra 1.7.71

#some polygon data
polys <- vect(system.file("ex/lux.shp", package="terra"))

#create raster of same extent
ras <- rast(polys, ncol = 75, nrow = 100)

#plot the polygon data for population
plot(polys, "POP", type = "classes")
```

![](https://i.imgur.com/MFiTINc.png)

``` r

#rasterize the polygons using the population column
rasterized_polys <- rasterize(polys, ras, field = "POP", fun = "mean")

#plot
plot(rasterized_polys, type = "classes")
lines(polys)
```

![](https://i.imgur.com/T97u8dg.png)

<sup>Created on 2024-03-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by kadyb** [comment]
I think the `fun` argument is used if there are multiple geometries in one raster cell, like this:

```r
v = vect(rbind(c(0, 0), c(1, 1)))
v = buffer(v, width = 1)
v$value = c(10, 20)
plot(v, "value")
r = rast(v, nrows = 100, ncols = 100)
r = rasterize(v, r, field = "value", fun = "sum")
plot(r)
```

Maybe are you looking for the `extract()` function, where you can weight values, but this requires raster as input?

**Comment by jflowernet** [comment]
Ahh, ok that makes sense. I was mis-interpreting the help file. Many thanks @kadyb . A colleague suggested `rasterizeWin` as a potential solution which could indeed work.

Regarding the `fun` argument in `rasterize`, I think the documentation is currently a little vague:

**Comment by kadyb** [comment]
> A colleague suggested `rasterizeWin` as a potential solution which could indeed work.

But `rasterizeWin()` only works for points.

**Comment by rhijmans** [comment]
There is no method/argument that directly implements what you are after. But you can get close to it if you disaggregate the template raster before rasterization and then aggregate the output. 

```
library(terra)
polys <- vect(system.file("ex/lux.shp", package="terra"))
ras <- rast(polys, ncol = 50, nrow = 75)

n <- 25
x <- disagg(ras, n)
x <- rasterize(polys, x, field = "POP")
x <- aggregate(x, n, mean, na.rm=TRUE)
```

**Comment by jflowernet** [comment]
Ahh, yes, great idea. Thank you Robert!

**Comment by rhijmans** [comment]
Here is another way to do this

```
library(terra)
polys <- vect(system.file("ex/lux.shp", package="terra"))
ras <- rast(polys, ncol = 50, nrow = 75)
values(ras) <- 1:ncell(ras)
e <- extract(ras, polys, exact=TRUE, cell=TRUE)
e$pop <- polys$POP[e$ID] * e$fraction
a <- aggregate(e["pop"], e["cell"], sum)

out <- rast(ras)
out[a$cell] <- a$pop
```

This is not an approximation, but it may be slow and require more memory than is available. It should be possible to wrap this into a memory-safe procedure.

**Comment by jflowernet** [comment]
Thank you!
