### ISSUE TITLE
visual artefacts when plotting points with polar latitude

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1455]
I'm not sure this has some purpose, but when plotting points that are all at the same pole, they don't look like points but rather very thin vertical line segments:

```
library(terra)
# one point at one pole:
plot(terra::vect("POINT(-20 90)"), axes = FALSE)

# several points at one pole:
plot(terra::vect(c("POINT(-20 90)", "POINT(40 90)", "POINT(130 90)")), axes = FALSE)

# points at both poles, different longitudes:
plot(terra::vect(c("POINT(-20 90)", "POINT(40 -90)")), axes = FALSE)
plot(terra::vect(c("POINT(-20 90)", "POINT(40 90)", "POINT(40 80)")), axes = FALSE)

# points at both poles, same longitude:
plot(terra::vect(c("POINT(40 90)", "POINT(40 -90)")), axes = FALSE)
```

PS: I know the problem goes away if we add `xpd = NA`, but since this is not the default nor an option that is often used, I wonder if the default plot should have a slightly larger extent, so that polar points weren't almost invisible.

**Comment by rhijmans** [comment]
I think this fixes it. Thank you and sorry for the long wait.
