### ISSUE TITLE
Rasterize vector outputting incorrect cell value

### ISSUE THREAD

**Issue by heckstra** [rspatial/terra#1456]
[data.zip](https://github.com/rspatial/terra/files/14580084/data.zip)
When rasterizing a polygon that has an attribute value = 28547313, all resultant pixels have a cell value of 28547312. Additionally, the data type of the resultant raster is FLT4S but was requested as INT4S. That is less of a problem than the incorrect result cell value though. 

```
library(terra)
print(packageVersion("terra"))
```

[1] ‘1.7.71’
```
vect_gpkg <- vect("data/fown_clipped_bug.gpkg")
problematic_id <-  28547313
datatype <- "INT4S"
## Add a new attribute which is a repeating problematic number
vect_gpkg$fid = problematic_id

template_rast <- rast(xmin = 159587.5, ncols = 17216, nrows = 15744, xmax = 1881188, ymin = 173787.5, ymax = 1748188, crs = "EPSG:3005")
## Rasterize on the field which has the repeating problematic number
rast_band <- rasterize(vect_gpkg, template_rast, field = "fid", datatype = datatype) ## doesn't matter if I put fun=min or fun=max
print(paste0("Number of pixels where value = ", problematic_id, " is: ", length(which(values(rast_band) == problematic_id))))
```
[1] "Number of pixels where value = 28547313 is: 0"
```
print(paste0("Data type specific: ", datatype, " vs datatype of created rast: ", datatype(rast_band)))
```
[1] "Data type specific: INT4S vs datatype of created rast: FLT4S"
```
print(unique(values(rast_band)))
```

fid
[1,]      NaN
[2,] 28547312

**Comment by kadyb** [comment]
> Additionally, the data type of the resultant raster is FLT4S but was requested as INT4S.

For this one, I think you should pass `datatype` in `wopt()`, like:

```r
rasterize(v, template_rast, field = "fid", wopt = list(datatype = "INT4S"))
```

**Comment by heckstra** [comment]
Thanks @kadyb - this fixed my problem! 
A helpful improvement would be to have the function complain if there are any unused arguments (e.g. datatype).

**Comment by rhijmans** [comment]
Thanks. A warning is now given:

```
#library(terra)
terra 1.7.74
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
r <- rast(v, ncols=75, nrows=100)
z <- rasterize(v, r, "NAME_2", datatype="INT4S")
#Warning message:
#[rasterize] unexpected additional argument(s): datatype 
```

**Comment by kadyb** [comment]
Is there a bug here? In @heckstra example, the attribute value was 28547313, but after rasterization it is 28547312 (with the FLT4S datatype).

**Comment by rhijmans** [comment]
That probably happened because 28,547,313 is too large to be exactly represented by a four-byte real number ("single precision floating point").  This happens with numbers larger than 16,777,216 (or smaller than -16,777,217).
