### ISSUE TITLE
R crashes with (potentially edge cases) on terra operations

### ISSUE THREAD

**Issue by tati-micheletti** [rspatial/terra#1457]
I came across two different operations that lead C++ to crash R when using `terra` on development version (`1.7.73`). The same happened to the CRAN version (`1.7-71`). I have tested it on both a Linux machine using `RStudio server`, and on a Windows machine with `RSudio`. I also tested using `R GUI` and that's how I know the failure comes from C++, as it is reported there. In `RStudio`, it just crashes without reports.

The first example is a case where a vector extent is created as `NaN`, resulting in the crash when applying another `terra` function to it (i.e., `nearest`). The second example, is a case where terra crashes when using `erase` if `y` has zero features. 

I understand what leads to the crashes (i.e., unexpected inputs) and these cases would likely not happen during an interactive session. However, I am automating many operations with `terra` on many randomly simulated polygons which, every once in a while, result in an "invalid" polygon (which is not caught by `is.empty` or `is.valid`, returning, respectively, `FALSE` and `TRUE` and scaping my unit tests). 

Still, I was hoping `terra` could preemptively figure out that such operations would result in a crash and gracefully error instead -- or even better, return a potentially expected result with a warning. In example 1, I would expect any CRS's to behave like latlong and just "work". In example 2, I would expect (or hope!) `x` to be returned back unchanged, with a warning like `y has no features. Returning x unchanged`. 

Thanks a lot for your super hard work on `terra`, Robert! It's an amazing package!  =)

## First, session and package info:
```
library("terra")
packageVersion("terra") 
[1] ‘1.7.73’
sessionInfo()
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.7-73

loaded via a namespace (and not attached):
[1] compiler_4.3.0   tools_4.3.0      Rcpp_1.0.12      codetools_0.2-19
```
Now to the examples. 

## EXAMPLE 1

When I have a different crs coordinate (i.e., Canada_Albers_Equal_Area_Conic (ESRI:102001)) R crashed during an operation that works when the crs is latlong:

1. Create a SpatVector

```
aeaExtent <- ext(-1613510, -971499.8, 2398561, 3588542)
aeaCRS <- "ESRI:102001"
shp <- vect(aeaExtent, crs = aeaCRS)
shp

# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 1, 0  (geometries, attributes)
# extent      : -1613510, -971499.8, 2398561, 3588542  (xmin, xmax, ymin, ymax)
# coord. ref. : Canada_Albers_Equal_Area_Conic (ESRI:102001) 

set.seed(1983)
firstPoint <- spatSample(shp, size = 1)
firstPoint
# class       : SpatVector 
# geometry    : points 
# dimensions  : 1, 0  (geometries, attributes)
# extent      : -1152171, -1152171, 3287969, 3287969  (xmin, xmax, ymin, ymax)
# coord. ref. : Canada_Albers_Equal_Area_Conic (ESRI:102001) 

setPoints <- spatSample(shp, size = 4)
setPoints
# class       : SpatVector 
# geometry    : points 
# dimensions  : 4, 0  (geometries, attributes)
# extent      : -1562134, -1082297, 3067230, 3281726  (xmin, xmax, ymin, ymax)
# coord. ref. : Canada_Albers_Equal_Area_Conic (ESRI:102001) 
```

2. Buffer the point to a very small value. This happened when converting lines  to polygons for joining the layer with another polygon layer without adding "inexisting" area to them
```
bufferedPoint <- terra::buffer(firstPoint, width = 0.00000000000000001)
ext(bufferedPoint)
# SpatExtent : NaN, NaN, NaN, NaN (xmin, xmax, ymin, ymax)
```

3. This causes the following function to crash R when terra::nearest is used

```
nearestPoint <- terra::nearest(bufferedPoint, setPoints) # CRASHES R!
```

However, this doesn't happen when the CRS is latlong:

```
latlongShp <- vect(system.file("ex/lux.shp", package="terra"))
shp2 <- terra::project(shp, crs(latlongShp))
set.seed(1983)
firstPoint2 <- spatSample(shp2, size = 1)
setPoints2 <- spatSample(shp2, size = 4)
bufferedPoint2 <- terra::buffer(firstPoint2, width = 0.00000000000000001)
ext(bufferedPoint2)
# SpatExtent : -120.496055316278, -120.496055316278, 64.5498682238233, 64.5498682238233 (xmin, xmax, ymin, ymax)
nearestPoint2 <- terra::nearest(bufferedPoint2, setPoints2)
nearestPoint2
# class       : SpatVector 
# geometry    : points 
# dimensions  : 1, 7  (geometries, attributes)
# extent      : -123.1205, -123.1205, 66.55658, 66.55658  (xmin, xmax, ymin, ymax)
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       : from_id from_x from_y to_id   to_x  to_y  distance
# type        :   <num>  <num>  <num> <num>  <num> <num>     <num>
# values      :       1 -120.5  64.55     3 -123.1 66.56 2.544e+05
```
With latlong the operation works fine.

## EXAMPLE 2: 

R also crashes when terra::erase(A, B) if B has zero features, and that seems to be independent of the `crs`. This happened when I was performing some automated tasks that every once in a while resulted in zero features. 

```
set.seed(1983)
toErasePoly <- spatSample(shp, size = 1)
toErasePolyBuff <- terra::buffer(toErasePoly, width = 100000)
toErasePolyBuff <- toErasePolyBuff["X" == 0,]
toErasePolyBuff 
# class       : SpatVector 
# geometry    : none 
# dimensions  : 0, 0  (geometries, attributes)
# extent      : 0, 0, 0, 0  (xmin, xmax, ymin, ymax)
# coord. ref. : Canada_Albers_Equal_Area_Conic (ESRI:102001) 

erased <- terra::erase(shp, toErasePolyBuff) # CRASHES R!
```

Now With latlong, it also crashes R:

```
shp2 <- vect(system.file("ex/lux.shp", package="terra"))
set.seed(1983)
toErasePoly2 <- spatSample(shp2, size = 1)
toErasePolyBuff2 <- terra::buffer(toErasePoly2, width = 1000)
toErasePolyBuff2 <- toErasePolyBuff2["ID_1" == 0,]
toErasePolyBuff2
# class       : SpatVector 
# geometry    : none 
# dimensions  : 0, 6  (geometries, attributes)
# extent      : 0, 0, 0, 0  (xmin, xmax, ymin, ymax)
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       :  ID_1 NAME_1  ID_2 NAME_2  AREA   POP
# type        : <num>  <chr> <num>  <chr> <num> <int>

erased2 <- terra::erase(shp2, toErasePolyBuff2) # STILL CRASHES R!
```

**Comment by rhijmans** [comment]
These are nasty corner cases, and they may pop up again but these examples now run without crashing,
