### ISSUE TITLE
operations between rasters of different extents: throw an error or take the intersection?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#146]
Not a big deal, but the manual states, in regard to mathematical operations, that "If multiple `SpatRaster` objects are used, these must have the same extent and resolution".  But, when rasters with different extents (and with identical resolutions, row numbers and column numbers) are provided, no error is emitted and the final extent is that of the first argument (see below). I think this is a bit dangerous for the users, and a warning (or error) coud be thrown, in case of different extents. 

If you decide not to throw an error, perhaps a better habit would be to take the intersection of the rasters, in case of identical resolutions but different extents. I remember the former `raster` package behaved this way. Why change? 

```
r1=rast(res=10,ext=c(0,50,0,50))
values(r1)=1:ncell(r1)

r2=rast(res=10,ext=c(40,90,40,90))
values(r2)=1:ncell(r2)

(r1+r2)
# class       : SpatRaster 
# dimensions  : 5, 5, 1  (nrow, ncol, nlyr)
# resolution  : 10, 10  (x, y)
# extent      : 0, 50, 0, 50  (xmin, xmax, ymin, ymax)
# coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
# source      : memory 
# name        : lyr.1 
# min value   :     2 
# max value   :    50
```

**Comment by rhijmans** [comment]
This really is a bug. There is a check for the extent to be the same but that failed. I now get 

```
r1+r2
#Error: [+] extents do not match
```

I agree that returning the intersection could be reasonable --- but I have not implemented that yet.
