### ISSUE TITLE
nearest() returns NA for all to_id when centroids = FALSE

### ISSUE THREAD

**Issue by mablmabl** [rspatial/terra#1471]
I have a number of geographical points in the sea and a map with Swedish sea areas. I want to know in which sea area each point lies and for the points outside sea areas the distance to nearest sea area including ID for the nearest sea area.

```
library(terra) 
#version 1.7-74 

map <- vect("/vsizip//vsicurl/https://www.smhi.se/polopoly_fs/1.140307!/Havsomr_SVAR_2016_3b.zip")
id <- c(11,12,13,14,15,16,17,18,19,20,21,22,23,24,25)
lon <- c(15.29416656,15.10333347,15.27083302,15.27250004,15.1291666,15.31333351,15.24166679,15.30716705,15.32333374,15.38833332,15.41416645,15.40666676,15.27166653,15.26083374,15.1916666)
lat <- c(56.1566658,56.15000153,56.15250015,56.13999939,56.16383362,56.15333176,56.1558342,56.17416763,56.12366486,56.14250183,56.15916824,56.17666626,56.17666626,56.17300034,56.1570015)
pts <- vect(data.frame(id,lon,lat),geom=c("lon", "lat"), crs="EPSG:4326")
map <- project(map,"EPSG:3006")
pts <- project(pts,"EPSG:3006")
npol <- nearest(pts, map[,"HID"], centroids=FALSE)
```

As you can see when you run this simple code that to_id is always NA and of type logical. I want to have the column HID from map in column to_id (or other ID from map). Can I get that in some way?

```
npol
#class       : SpatVector
#geometry    : points
#dimensions  : 15, 5  (geometries, attributes)
#extent      : 506419.7, 525716.6, 6219890, 6225817  (xmin, xmax, ymin, ymax)
#coord. ref. : SWEREF99 TM (EPSG:3006) 
#names       : from_id    from_x    from_y     to_id distance
#type        :   <int>     <num>     <num> <logical>    <num>
#values      :       1 5.183e+05 6.224e+06      <NA>        0
#                    2 5.064e+05 6.223e+06      <NA>        0
#                    3 5.168e+05 6.223e+06      <NA>        0
```
Many thanks :-)

**Comment by mablmabl** [comment]
If I set centroids = TRUE in function call everything works as it should and to_id is filled with correct index integer values. It seems that it is centroids = FALSE that not works. Possibly a bug?

**Comment by mgdesaix** [comment]
I just ran into this problem too - I have code that used to work with centroids = FALSE from ~6 months or so ago. Not sure what my terra version was then, but now I have 1.7-71 and the same code is providing me with all NAs as well for the "to_id"

**Comment by mablmabl** [comment]
I tested today with terra version 1.8-0 and the problem is still the same, only NA returned when centroids = FALSE. When comparing (rbenchmark) different methods to calculate the intial task with 15 000 points in the sea terra::nearest is by far the fastest:

![bild](https://github.com/user-attachments/assets/5190d122-e553-4dfb-989f-a50aba165312)

**Comment by mablmabl** [comment]
I have done some more testing and looped through points to see which points that fails and returns NA in to_id. Interstingly there are very few that fail. In the example above only two points fail, all the other return the correct integer value. In the code below I show the method and plot these two points on the map. The two points are close to the polygon border. Can this be of some help to figure out what the error is?

```
library(terra)

map <- vect("/vsizip//vsicurl/https://www.smhi.se/polopoly_fs/1.140307!/Havsomr_SVAR_2016_3b.zip")
id <- c(11,12,13,14,15,16,17,18,19,20,21,22,23,24,25)
lon <- c(15.29416656,15.10333347,15.27083302,15.27250004,15.1291666,15.31333351,15.24166679,15.30716705,15.32333374,15.38833332,15.41416645,15.40666676,15.27166653,15.26083374,15.1916666)
lat <- c(56.1566658,56.15000153,56.15250015,56.13999939,56.16383362,56.15333176,56.1558342,56.17416763,56.12366486,56.14250183,56.15916824,56.17666626,56.17666626,56.17300034,56.1570015)
pts <- vect(data.frame(id,lon,lat),geom=c("lon", "lat"), crs="EPSG:4326")
map <- project(map,"EPSG:3006")
pts <- project(pts,"EPSG:3006")

for(i in 1:nrow(pts)) {
  npol <- nearest(pts[i], map[,"HID"], centroids=FALSE)
  cat(paste(i, " ", class(npol$to_id),"\n", sep = ""))
}

plot(crop(map,ext(pts[c(8,11)])+1000), col = "grey", axes = F)
points(pts[c(8,11)], col = "red")
````

**Comment by mablmabl** [comment]
Further testing. When using nearest with a multipoint spatvector, distance is calculated for all points even those that get to_id = NA. For the NA to_id points distance is never 0. When testing with 15 000 points only 137 where to_id NA. Distance in meters for these varied from 0.086 to 20396, i.e. not all where close to a boundary. All of the points where outside of polygons but several other points outside polygons could be handled correctly by nearest.

If one point in a multipoint spatvector nearest call is a to_id NA point (tested with single point spatvector nearest call) all points will get to_id NA of class logical.

I hope this can be of some help :-)

**Comment by rhijmans** [comment]
I am sorry for the very long delay in fixing this one.  I now get:

```
npol
# class       : SpatVector 
# geometry    : points 
# dimensions  : 15, 5  (geometries, attributes)
# extent      : 506419.7, 525716.6, 6219890, 6225817  (xmin, xmax, ymin, ymax)
# coord. ref. : SWEREF99 TM (EPSG:3006) 
# names       : from_id    from_x    from_y to_id distance
# type        :   <int>     <num>     <num> <int>    <num>
# values      :       1 5.183e+05 6.224e+06   279        0
#                     2 5.064e+05 6.223e+06   288        0
#                     3 5.168e+05 6.223e+06   279        0
```

**Comment by mablmabl** [comment]
I have now tested with all my 15 000 points and it works perfectly!

Many thanks for taking the time to fix this. It will save me a lot of time.
