### ISSUE TITLE
Layer name in output of rasterizeGeom doesn't match specified function

### ISSUE THREAD

**Issue by HRodenhizer** [rspatial/terra#1472]
When using `rasterizeGeom()`, I would expect the output layer name to match the function specified by the user. However, it appears that "area" is used regardless of the specified function. In the following example, I would expect the layer name to be "count" rather than "area".

```r
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
set.seed(44)
s <- spatSample(v, 100)
b <- buffer(s, 1000)
r <- rast(v, res=.1)

x <- rasterizeGeom(b, r, fun="count")
names(x)
```
```r
[1] "area"
```

Note: I haven't done a full survey of all the methods available for different geometry types to see if the output layer name is the same in all cases.

**Comment by rhijmans** [comment]
Thank you for reporting this. I now get

```
x <- rasterizeGeom(b, r, fun="count")
names(x)
#[1] "count"
```
