### ISSUE TITLE
Feature request: set option for default color palette

### ISSUE THREAD

**Issue by dfriend21** [rspatial/terra#1474]
`terra` by default uses the `terrain.colors()` color palette when no palette is specified - personally, I'm not a huge fan of this color palette - I feel like the very narrow band of yellow creates false "breaks" when plotting continuous data (see example below - in my opinion, using the viridis color palette in this situation more accurately depicts the fact that the values increase at a steady rate as you get farther from the center).

It'd be nice if there was an option to change what color palette is used by default. I realize that having to set the color palette every time isn't really all that onerous, and I could do something like make a wrapper function that sets the color palette, but still - it'd be cool if there was an option that I could set in .Rprofile so that my specified color palette would be automatically used in every session. But if you'd rather not, no worries - feel free to close this issue.

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.3.3
#> terra 1.7.71
library(viridis)
#> Loading required package: viridisLite

n <- 200
e <- ext(-90,90,-90,90)
r <- rast(e, nrow = n, ncol = n, vals = 1)
pt <- vect(cbind(mean(e[1:2]), mean(e[3:4])), crs = crs(r))
d <- distance(r, pt, unit = "km", progress = FALSE)
par(mfrow = c(1,2))
plot(d, main = "terrain.colors()")
plot(d, col = map.pal("viridis"), main = "map.pal(\"viridis\")")
```

![](https://i.imgur.com/cEYehiG.png)

<sup>Created on 2024-04-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
This change makes "viridris" the default palette; and you can change that setting with `options`

```
library(terra)
n <- 200
e <- ext(-90,90,-90,90)
r <- rast(e, nrow = n, ncol = n, vals = 1)
pt <- vect(cbind(mean(e[1:2]), mean(e[3:4])), crs = crs(r))
d <- distance(r, pt, unit = "km", progress = FALSE)
par(mfrow = c(1,2))

# this is the default 
options(terra.pal=NULL)
plot(d, main="viridris")

# set your own default palette
options(terra.pal=terrain.colors(10))
# see 
options("terra.pal")
#$terra.pal
# [1] "#00A600" "#2DB600" "#63C600" "#A0D600" "#E6E600" "#E8C32E" "#EBB25E"
# [8] "#EDB48E" "#F0C9C0" "#F2F2F2"

plot(d, main="terrain")
```

![viridris](https://github.com/rspatial/terra/assets/11481397/c12e7059-ed1e-46d5-bec4-8ddb110a86b3)
