### ISSUE TITLE
terra::plet type="interval" won't work with less than 11 unique observations?

### ISSUE THREAD

**Issue by caiohamamura** [rspatial/terra#1475]
Hello, I have been trying to use terra::plet to display the values in intervals but it won't work. It works fine for the polygon `ex/lux.shp` example dataset, but for this point vector data it is not working.

[atl08_seg.zip](https://github.com/rspatial/terra/files/14951592/atl08_seg.zip)

```r
library(terra)

unzip("atl08_seg.zip")

v <- terra::vect("atl08_seg.gpkg")
terra::plet(v, "h_canopy", tiles=c("Esri.WorldImagery"))
```

![image](https://github.com/rspatial/terra/assets/3440255/12caadf0-c58f-458e-abe4-3b64ccd74589)

I have already tried to use different parameters for type "interval" and setting breaks, but nothing works. I also tried to convert the h_canopy to integer `v$h_canopy <- as.integer(h_canopy * 100)` but it does not work either,

Thank you!

**Comment by caiohamamura** [comment]
Oh, I got it, for some reason there is a fixed conditional within `.get_leg` that will overwrite the specified type if there are less than 11 unique observations:

https://github.com/rspatial/terra/blob/29fe9681b7a4884bd44112ff1f38edf53cab4fb8/R/plot_let.R#L72C4-L72C16
```r
	if ((!is.numeric(v)) || (length(unique(v)) < 11)) {
```

Why is that? Can I provide a pull request to remove that hardcoded limit?

**Comment by caiohamamura** [comment]
Create a pull request https://github.com/rspatial/terra/pull/1479

**Comment by rhijmans** [comment]
Thanks. The change I made is that if you specify the type, it overrides the default (which is to use classes if there are few unique values).

```
library(terra)
v <- vect(system.file("ex/lux.shp", package="terra"))[1:8,]
terra::plet(v, "POP", tiles=c("Esri.WorldImagery"))
terra::plet(v, "POP", tiles=c("Esri.WorldImagery"), type="interval")
```
