### ISSUE TITLE
conversion of sf points to a terra SpatVector using vect does not work

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#148]
The following conversion of `sf` points to a `terra SpatVector` using `vect` does not work. Coordinates are lost, number of points is double the initial one.

```
library(terra)
# terra version 1.1.0

library(sf)
# Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

ptSf <- st_as_sf(data.frame(x=1:5,y=6:10),coords=c("x","y"))

plot(ptSf)
```

![image](https://user-images.githubusercontent.com/42430070/106783632-c7775900-664b-11eb-8182-76e3020aedb7.png)

```
plot(vect(ptSf), axes=TRUE)
```

![image](https://user-images.githubusercontent.com/42430070/106784109-466c9180-664c-11eb-86d7-644700757bfb.png)

```
geom(vect(ptSf))

#       geom part  x y hole
#  [1,]    1    1  1 0    0
#  [2,]    1    2  6 0    0
#  [3,]    2    1  2 0    0
#  [4,]    2    2  7 0    0
#  [5,]    3    1  3 0    0
#  [6,]    3    2  8 0    0
#  [7,]    4    1  4 0    0
#  [8,]    4    2  9 0    0
#  [9,]    5    1  5 0    0
# [10,]    5    2 10 0    0
```

**Comment by rhijmans** [comment]
Thanks, this has been fixed.
