### ISSUE TITLE
R crashes from a bad `free` when using `==` on an NLCD raster

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/terra#1482]
With `terra` 29fe9681b7a4884bd44112ff1f38edf53cab4fb8, the following code

```R
r = terra::rast("nlcd_2011_land_cover_l48_20210604.img")
  # From https://s3-us-west-2.amazonaws.com/mrlc/nlcd_2011_land_cover_l48_20210604.zip
r == "Open Water"
```

yields

```
free(): invalid pointer-------|---------|
zsh: abort (core dumped)  R --no-save -q
```

**Comment by rhijmans** [comment]
This works for me with terra-devel on Windows  and Ubuntu (for both with R 4.4.0; GDAL 3.8.4)

This equivalent also works
```
water <- r == 11
```
Perhaps you are using a Mac? Do other things work, like this:

```
x <- crop(r, c(-2339492, -2107943, 1835045, 2017846))
```

**Comment by Kodiologist** [comment]
Son of a gun, I can't even reproduce my original report now, although I'm pretty sure I haven't changed any software versions. Well, I'll close this issue and only reopen if it I learn more about how to reproduce it. Sorry for the noise.

I'm using R 4.2.1 and GDAL 3.0.4 on Ubuntu 20.04.
