### ISSUE TITLE
`tapp()` time order differs when using C++ vs. base R `fun`?

### ISSUE THREAD

**Issue by robe2037** [rspatial/terra#1483]
When aggregating by `"years"`, `"months"`, or `"yearmonths"`, using re-implemented C++ functions produces time values offset by one month compared to those produced when using the base R equivalent (or a user-defined function). The C++ implementations appear to be the correct time values. Layer names and raster values are consistent in both instances, though.

Maybe related to https://github.com/rspatial/terra/issues/1062?

Reprex:

``` r
library(terra)
#> terra 1.7.71

r <- rast(nrow = 1, ncol = 1, nlyrs = 89, vals = 1)

time(r) <- seq.Date(
  from = as.Date("2001-01-01"), 
  to = as.Date("2001-03-30"), 
  by = "days"
)

r1 <- tapp(r, "yearmonths", sum)
r2 <- tapp(r, "yearmonths", \(i) sum(i))

time(r1)
#> [1] 2001.000 2001.083 2001.167

time(r2)
#> [1] 2000.917 2001.000 2001.083

# Raster values are consistent
values(r1)
#>      ym_200101 ym_200102 ym_200103
#> [1,]        31        28        30

values(r2)
#>      ym_200101 ym_200102 ym_200103
#> [1,]        31        28        30
```

<sup>Created on 2024-04-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Thank you for reporting this. I know get

```
time(r1)
#[1] 2001.000 2001.083 2001.167
time(r2)
#[1] 2001.000 2001.083 2001.167
```

**Comment by robe2037** [comment]
Thanks!
