### ISSUE TITLE
Error from extend() with four-integer vector

### ISSUE THREAD

**Issue by mkschneider** [rspatial/terra#1486]
Documentation to extend() says "you can provide one, two or four non-negative integers indicating the number of rows and columns that need to be added at each side"

```
r <- rast(xmin=-150, xmax=-120, ymin=30, ymax=60, ncols=36, nrows=18)
re <- extend(r, c(2,10)) 
``` 
works, but

`re2 <- extend(r, c(2,10,2,10))`

**Error in .local(x, y, ...) : object 'adj' not found**

Thanks for wonderful terra library!

**Comment by rhijmans** [comment]
Thanks very much for reporting this. Fixed now

```
library(terra)
#terra 1.7.75
r <- rast(ncol=10, nrow=10, xmin=0, xmax=1, ymin=0, ymax=1)
extend(r, c(1,0,0,1))
class       : SpatRaster 
dimensions  : 11, 11, 1  (nrow, ncol, nlyr)
resolution  : 0.1, 0.1  (x, y)
extent      : -0.1, 1, 0, 1.1  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84) 
```
