### ISSUE TITLE
non-zero exit 

### ISSUE THREAD

**Issue by drchubos** [rspatial/terra#1488]
Hi, how could I solve this problem?

install.packages("terra") 

ERROR: compilation failed for package 'terra'
* removing 'C:/Users/user/Documents/R/win-library/4.0/terra'
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\user\AppData\Local\Temp\RtmpQX9m3H\downloaded_packages’

**Comment by drchubos** [comment]
ERROR: compilation failed for package 'terra'
* removing 'C:/Users/user/Documents/R/win-library/4.0/terra'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/user/AppData/Local/Temp/RtmpQX9m3H/file376c3bc65afa/terra_1.7-75.tar.gz’ had non-zero exit status

**Comment by rhijmans** [comment]
You do not provide much information. Why are you compiling terra? What I can see is that you are using a four years old version of R. Probably the easiest solution would be to update R to its current version (4.4)
