### ISSUE TITLE
terra::plot() fails if raster has only minimal differences due to "breaks are not unique"

### ISSUE THREAD

**Issue by srfall** [rspatial/terra#1491]
Seems like an unfortunate edge case: I discovered it in a situation where I had an inital raster all set to the same value and some code that just did minimal changes to it. When I tried to plot it, it failed with:

`Error in cut.default(Z, breaks, include.lowest = TRUE, right = FALSE) :
  'breaks' are not unique`
  
Here is a minimal example:
````{r}
test <- matrix(1, 4, 4)
test <- test + rnorm(4 * 4, sd = 0.00000000000001)
terra::plot(terra::rast(test))
````

Note that `terra::image(terra::rast(test))` works as it should.

````
> packageVersion("terra")
[1] '1.7.75'
````
(latest dev version)

**Comment by rhijmans** [comment]
Thanks, with this change I can do 

```
x <- terra::rast(test)
terra::plot(x)
terra::plot(x, type="classes", mar=c(1,1,1,8))
```

**Comment by srfall** [comment]
True that works. Although it might be nice if it would switch automaticall the "classes" in that case :)

If I look at `.get_breaks()`, it seems like this 
https://github.com/rspatial/terra/blob/353dee17849e246d9fac2daea1defe6360c9d2c0/R/plot_legend.R#L27

is the problem. E.g. 
````
breaks <- seq(1-1e-16, 1+1e-16, length.out=10)
stopifnot(length(breaks) == length(unique(breaks)))
````
