### ISSUE TITLE
plot fails if values are too similar due to "zero-length coordinates" in the legend

### ISSUE THREAD

**Issue by srfall** [rspatial/terra#1492]
Sorry to bother you again. First of all thanks for https://github.com/rspatial/terra/commit/dcd48b7e166e2d02034084161b632e9e44fe3e4b !

Unfortunately I discovered a subsequent bug related to the same situation, but this time affecting the drawing of the legend:

````
test <- matrix(293, 100, 100)
test <- test + rnorm(length(test), sd = 1e-13)
terra::plot(terra::rast(test))
````
results for me in:
`Error in graphics::segments(e$xmin, ypos, e$xmax + e$dx * 0.25, ypos,  : 
  cannot mix zero-length and non-zero-length coordinates`
  
  It only seem to happen if the values of the raster are large, e.g. this works:
````
test <- matrix(1, 100, 100)
test <- test + rnorm(length(test), sd = 1e-13)
terra::plot(terra::rast(test))
````

````
> packageVersion("terra")
[1] '1.7.76'
````

**Comment by rhijmans** [comment]
Thanks again. I believe both cases now work.
