### ISSUE TITLE
autocor() returns NaN if all raster values are equal

### ISSUE THREAD

**Issue by srfall** [rspatial/terra#1494]
Tbh this might just be a misunderstanding on my part about how Moran's I works, but I would expect `1` in that case and not `NaN`

````
r <- terra::rast(nrows = 10, ncols = 10, xmin = 0)
terra::values(r) <- 1
terra::autocor(r)
#> lyr.1 
#> NaN
````

> OS: Win 11

> packageVersion("terra")                         
[1] '1.7.76'

> terra::gdal(lib="all")
    gdal     proj     geos
 "3.6.2"  "9.2.0" "3.11.2"

**Comment by rhijmans** [comment]
I believe this is correct. If there is no variation, correlation cannot be computed. You can also see that in the [formula](https://en.wikipedia.org/wiki/Moran%27s_I);  with these numbers you get `0/0`. 

Also, Moran's *I* is not guaranteed to be between -1 and 1; it can be larger than 1.

For correlation:
```
cor(c(1,1,1), c(1,1,1))
[1] NA
#Warning message:
#In cor(c(1, 1, 1), c(1, 1, 1)) : the standard deviation is zero
```
