### ISSUE TITLE
`plot(ext = )` seems to have inconsistent behaviour

### ISSUE THREAD

**Issue by jflowernet** [rspatial/terra#1495]
The `ext=` argument of `plot` seems to have some odd behaviour. Using `ext` in EPSG:4326 seems to work, but when the same raster and vector data are projected into a local projection, the `ext=` argument does not seem to work properly, with the plot covering only part of the full extent it should. I can force the plot to cover the desired area using `xlim = ` and `ylim = `, but I can't see why just using `ext = ` is not working. Reprex below shows the issue. I have also tested with Molleweide projection and get the same results.

``` r
library(terra)
#> terra 1.7.71

r <- rast(xmin = 0, xmax = 5, ymin = 0, ymax = 5, resolution = 1)
values(r) <- 1:ncell(r)

v <- ext(0, 6, 0, 6) |>
  vect() |>
  set.crs("epsg:4326")

#works as expected
plot(r, ext = ext(v))
lines(v, col = "red", lwd = 2)
```

![](https://i.imgur.com/fKsKG2L.png)

``` r

#Albers Africa projection
proj_albers <- "ESRI:102022"

r_albers <- project(r, proj_albers)

v_albers <- project(v, proj_albers)

plot(r_albers)
```

![](https://i.imgur.com/WKMPhvE.png)

``` r

#larger extent, but not encompassing full extent of v_albers as I would expect
plot(r_albers, ext = ext(v_albers))
lines(v_albers, col = "red", lwd = 2)
```

![](https://i.imgur.com/58QOxvP.png)

``` r

#works as expected: extent of v_albers
plot(r_albers, xlim = c(ext(v_albers)$xmin, ext(v_albers)$xmax), ylim = c(ext(v_albers)$ymin, ext(v_albers)$ymax))
lines(v_albers, col = "red", lwd = 2)
```

![](https://i.imgur.com/ECnsbHN.png)

``` r

gdal()
#> [1] "3.4.1"
```

<sup>Created on 2024-05-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Thanks. That happens because the extent is aligned with the raster.  You only notice it with very large cells. For example, see

```
disagg(r_albers, 10) |> plot(ext = v_albers)
lines(v_albers, col = "red", lwd = 2)
```
I am not sure why I introduced the alignment. I have removed it and things now work as expected.
