### ISSUE TITLE
`plet()` has no default tile provider

### ISSUE THREAD

**Issue by jflowernet** [rspatial/terra#1499]
It seems like `plet()` has no default tile provider. Is this intentional? Open Street Maps would seem like a good default.

``` r
library(terra)
#> terra 1.7.71

r <- rast(system.file("ex/elev.tif", package="terra"))

plet(r)
```

![](https://i.imgur.com/TjgK9gG.png)

``` r

plet(r, tiles = "Streets")
```

![](https://i.imgur.com/Y1A5cgX.png)

``` r

packageVersion("leaflet")
#> [1] '2.2.2'

gdal(lib="gdal")
#> [1] "3.4.1"
```

<sup>Created on 2024-05-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
There is a default provider for SpatVector but not for SpatRaster. My thinking was that a base map is generally not that useful for raster data; and it can be distracting and undesirable. It can of course be useful, especially when using transparent rasters. With vector data, the base map map is probably the main reason for using leaflet.

**Comment by jflowernet** [comment]
Ah, interesting, and thanks for the response. I guess I normally use leaflet maps as a way of putting my data in a geographical context. I work in marine science so it can be useful to do an interactive map with a satellite basemap so I can see where data is relative to the coast and shallow water features. So I would advocate for also having a default for the SpatRaster case, but also appreciate that I might be an outlier in my usage.

**Comment by rhijmans** [comment]
You got it (https://github.com/rspatial/terra/commit/4d2818314e063d8d430a64669eb06efb52142b2c)

**Comment by jflowernet** [comment]
Many thanks Robert
