### ISSUE TITLE
SpatBase.h

### ISSUE THREAD

**Issue by cjcarlson** [rspatial/terra#15]
Hey howdy,

We're (me and @gfalbery) getting this error on two different RStudio servers we've tried to install to. Any clue what this might mean? (Can we not install on linux?)

file_utils.cpp:1:22: fatal error: SpatBase.h: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:176: recipe for target 'file_utils.o' failed
make: *** [file_utils.o] Error 1
ERROR: compilation failed for package ‘terra’
* removing ‘/research-home/ccarlson/R/x86_64-pc-linux-gnu-library/3.6/terra’
Error: Failed to install 'terra' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmphkapLo/file8d3575d25961/terra_0.2-9.tar.gz’ had non-zero exit status

Thanks!

**Comment by rhijmans** [comment]
That was because of erroneously spelling `spatBase.h` as `SpatBase.h` (same thing on windows, not on linux --- except when reading from a mounted windows file system --- and that is how I test on linux). Fixed now. Thanks for letting me know.
