### ISSUE TITLE
ext of SpatVectorProxy does not match ext of SpatVector

### ISSUE THREAD

**Issue by erkent-carb** [rspatial/terra#1501]
Hi, 

I have large shapefiles that I would like to get the extent of (bounding box). If I use the proxy=TRUE argument of vect(), I get a different extent than when I don't use a proxy. For example: 

``` R
f <- system.file("ex/lux.shp", package="terra")

v1 <- vect(f, proxy=TRUE)
ext(v1)

v2 <- vect(f)
ext(v2)

ext(v1) == ext(v2) 

```

Is this a bug or am I missing something? 

> packageVersion("terra")
[1] ‘1.7.72’
> terra::gdal(lib="all")
    gdal     proj     geos 
 "3.8.2"  "9.3.1" "3.11.2"

**Comment by kadyb** [comment]
It seems that only the extent of the first object from SpatVectorProxy is returned.

```r
ext(v1)
#> SpatExtent : 5.82623196, 6.16085005, 49.94611359, 50.18162155
ext(v2[1, ])
#> SpatExtent : 5.82623196, 6.16085005, 49.94611359, 50.18162155
```

**Comment by rhijmans** [comment]
Thank you for reporting this. This seems to work now, at least for shapefiles:

```
library(terra)
#terra 1.7.76
f <- system.file("ex/lux.shp", package="terra")
v0 <- vect(f)
v1 <- vect(f, proxy=TRUE)
ext(v0)
#SpatExtent : 5.74414015, 6.52825212, 49.44780731, 50.18162155 (xmin, xmax, ymin, ymax)
ext(v1)
#SpatExtent : 5.74414015, 6.52825212, 49.44780731, 50.18162155 (xmin, xmax, ymin, ymax)
ext(v0) == ext(v1)
#[1] TRUE
```

**Comment by kadyb** [comment]
Generally, this also works for the geopackage format, but I noticed that there may be some differences due to precision.

```r
library(terra)
f <- system.file("gpkg/nc.gpkg", package = "sf")
v0 <- vect(f)
v1 <- vect(f, proxy=TRUE)
ext(v0)
#> SpatExtent : -84.3238525390625, -75.4569778442383, 33.8819923400879, 36.5896492004395
ext(v1)
#> SpatExtent : -84.3239, -75.457, 33.882, 36.5896
ext(v0) == ext(v1)
#> [1] FALSE
```

**Comment by erkent-carb** [comment]
Thank you, I confirmed it now works for my shapefile cases.
