### ISSUE TITLE
Check maximum 'memfrac' value

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#151]
There should be a check for maximum *memfrac* value in `terraOptions()`. The doc states:

> memfrac - value between 0.1 and 0.8

```r
library("terra")
terraOptions(memfrac = 1)
terraOptions()
# memfrac   : 1
```

```r
library("raster")
rasterOptions(memfrac = 1)
#> Warning message:
#> In setMemfrac(memfrac) :
#>   memfrac argument must be a value between 0.1 and 0.9
```

**Comment by rhijmans** [comment]
Thank you. I added a warning and updated the manual.  I now get:

```
library(terra)
#terra version 1.1.1
terraOptions(memfrac=1)
#Warning message:
#[terraOptions] memfrac > 0.9 
```

The manual now says: `memfrac - value between 0.1 and 0.9 (larger values give a warning). The fraction of RAM that may be used by the program.` 

The reason for allowing higher values is that on a OSX that works; apparently the operating system creates virtual memory. So there is no absolute need to stay within RAM limits.

**Comment by kadyb** [comment]
Thanks!
