### ISSUE TITLE
Ploting an arbitrary projection rast and add lat-long grid and axis

### ISSUE THREAD

**Issue by Schuch666** [rspatial/terra#1517]
Hi, I'm trying to implement a custom plot using the terra package. 

My goal is to plot some model data in the original projection and add a graticule (lines of latitude and longitude) and label the axis with the latitude and longitude (instead of the plot original coordinates / projection). I'm plotting the graticule using fun argument of terra::plot and a modified version of .plot.axes from this package to add the custom axis.

This is my code bellow, the position of the grid and x-axis is not matching (y-axis looks ok so far), it may be related to the coordinates from par('usr') . Do you know a way to fix this? there is a better approach to do that using terra R-package?

![latlon_grid_rast](https://github.com/rspatial/terra/assets/32721340/5f8839ec-da49-4d37-a7ad-df3d7cd06861)

library(terra)
library(eixport)

wrf <- paste(system.file("extdata", package = "eixport"),"/wrfinput_d01", sep="")
r   <- wrf_raster(file=wrf, name='XLAT')
r   <- rast(r)

int     = 2
e_o     <- ext(r)
Points  <- vect(cbind(x = e_o[1:2], y = e_o[3:4]), type="points",
                crs =  terra::crs(r,proj=TRUE))
proj_p  <- project(Points,"+proj=longlat +datum=WGS84 +no_defs")
e_p     <- ext(proj_p)
min_lon <- as.numeric(e_p[1])
max_lon <- as.numeric(e_p[2])
min_lat <- as.numeric(e_p[3])
max_lat <- as.numeric(e_p[4])

vet_lon <- seq(-80,80,by = int)
vet_lon <- vet_lon[vet_lon > min_lon - int & vet_lon < max_lon + int]
vet_lat <- seq(-180,180,by = int)
vet_lat <- vet_lat[vet_lat > min_lat - int & vet_lat < max_lat + int]

extra <- function(){
  terra::lines(terra::graticule(lon = vet_lon,lat = vet_lat,
                                crs = terra::crs(r,proj=TRUE)),
               lty = 3,lwd = 1.2)
  terra::add_box()
}

.plot.latlon <- function(x,proj,int,e,tn = 100) {

  vet_lon <- seq(-80,80,by = int)
  lab_lon <- c(paste0(seq(80,int,by=-int),"\u00baS"),'0',
               paste0(seq(int,80,by=int),"\u00baN"))

  usr <- par('usr')
  tx  <- rep(usr[1], tn)
  ty  <- seq(usr[3], usr[4], length.out=tn)

  firstPoints  <- vect(cbind(x = tx, y = ty), type="points",crs = proj)
  tt           <- project(firstPoints,"+proj=longlat +datum=WGS84 +no_defs")
  axis_coords  <- crds(tt)
  tfcn         <- approxfun(axis_coords[,2], ty)

  vet_lat <- seq(-180,180,by = int)
  lab_lat <- c(paste0(seq(180,int,by=-int),"\u00baW"),'0',
               paste0(seq(int,180,by=int),"\u00baE"))

  tx <- seq(usr[1], usr[2], length.out = tn)
  ty <- rep(usr[3], tn)

  firstPoints  <- vect(cbind(x = tx, y = ty), type="points",crs = proj)
  tt           <- project(firstPoints,"+proj=longlat +datum=WGS84 +no_defs")
  axis_coords  <- crds(tt)
  tfcn2        <- approxfun(axis_coords[,1], tx)

  if (is.null(x$axs$cex.axis)) {
    x$axs$cex.axis = 1
  }
  x$axs$cex.axis <- x$axs$cex.axis * 1.0

  if (is.null(x$axs$mgp)) {
    x$axs$mgp = c(2, .25, 0)
  }
  if (is.null(x$axs$tcl)) {
    x$axs$tcl <- -0.25
  }
  if ((!x$clip) & x$draw_grid) {
    x$axs$tck <- 1
    x$axs$mgp <- c(2, .15, 0)
  }

  xlab <- ylab <- NULL
  if (!is.null(x$axs$labels)) {
    xlab <- ylab <- x$axs$labels
  }
  if (!is.null(x$axs$xlabs)) {
    xlab <- x$axs$xlabs
    x$axs$xlabs <- NULL
  }
  if (!is.null(x$axs$ylabs)) {
    ylab <- x$axs$ylabs
    x$axs$ylabs <- NULL
  }

  xat <- yat <- NULL
  if (!is.null(x$axs$at)) {
    xat <- yat <- x$axs$at
  }
  if (!is.null(x$axs$xat)) {
    xat <- x$axs$xat
    x$axs$xat <- NULL
  }
  if (!is.null(x$axs$yat)) {
    yat <- x$axs$yat
    x$axs$yat <- NULL
  }

  min_lon <- as.numeric(e[1])
  max_lon <- as.numeric(e[2])
  min_lat <- as.numeric(e[3])
  max_lat <- as.numeric(e[4])

  valid_lat <- tfcn2(vet_lat)
  valid_lon <- tfcn(vet_lon)

  valid_lon[ valid_lon >= max_lat ] = NA
  valid_lon[ valid_lon <= min_lat ] = NA
  valid_lat[ valid_lat >= max_lon ] = NA
  valid_lat[ valid_lat <= min_lon ] = NA

  yat  <- valid_lon
  ylab <- lab_lon
  xat  <- valid_lat
  xlab <- lab_lat

  sides <- unique(x$axs$side)
  if (!is.null(sides)) sides <- round(sides)
  sides <- sides[sides > 0 & sides < 5]
  if (is.null(sides)) {
    x$axs$side <- sides <- 1:2
  }

  ticks <- x$axs$tick
  if (is.null(ticks)) {
    x$axs$tick <- ticks <- sides
  }
  labs <- x$axs$lab
  if (is.null(labs)) {
    x$axs$lab <- labs <- sides
  }

  if (x$clip) {
    usr <- x$lim
  } else {
    usr <- graphics::par("usr")
  }

  y <- x$axs
  retro <- isTRUE(y$retro)
  if (retro && (!x$lonlat)) {
    warning("'retro' labels can only be used with lonlat data")
    retro <- FALSE
  }
  y$retro <- y$lab <- y$tick <- NULL
  y$line <- NA
  y$outer <- FALSE
  y$line.lab <- NULL
  if (is.null(y$col)) y$col <- "black"
  if (x$clip) {
    lnpts <- crds(as.points(ext(x$lim)))
    lnpts <- rbind(lnpts[4,], lnpts)
  } else {
    lnpts <- crds(as.points(ext(usr)))
    lnpts <- rbind(lnpts[4,], lnpts)
  }
  for (s in 1:4) {
    y$side <- s
    y$labels <- NULL
    if (s %in% c(1,3)) {
      ur <- usr[2] - usr[1]
      edg <- c(usr[1]-10*ur, usr[2]+10*ur)
      if (is.null(xat)) {
        axt <- graphics::axTicks(s)
        y$at <- axt[axt >= usr[1] & axt <= usr[2]]
      } else {
        y$at <- xat
      }
      if (is.null(xlab)) {
        y$labels <- if (retro) retro_labels(y$at, lat=FALSE) else y$at
      } else {
        y$labels <- xlab
      }
      y$pos <- ifelse(s==1, usr[3], usr[4])
      if (x$clip && x$draw_grid && s == 1) {
        clp <- get.clip()
        if (!is.null(clp)) {
          for (i in seq_along(y$at)) {
            lines(rbind(c(y$at[i], clp[3]), c(y$at[i], clp[4])), col=y$col)
          }
        }
      }
    } else {
      ur <- usr[4] - usr[3]
      edg <- c(usr[3]-10*ur, usr[4]+10*ur)
      if (is.null(yat)) {
        axt <- graphics::axTicks(s)
        y$at <- axt[axt >= usr[3] & axt <= usr[4]]
      } else {
        y$at <- yat
      }
      if (is.null(ylab)) {
        y$labels <- if (retro) retro_labels(y$at, lat=TRUE) else y$at
      } else {
        y$labels <- ylab
      }
      y$pos <- ifelse(s==2, usr[1], usr[2])

      if (x$clip && x$draw_grid && s == 2) {
        clp <- get.clip()
        if (!is.null(clp)) {
          for (i in seq_along(y$at)) {
            lines(rbind(c(clp[1], y$at[i]), c(clp[2], y$at[i])), col=y$col)
          }
        }
      }
    }
    z <- y
    z$lwd <- 0

    if (s %in% labs) {
      z$lwd.ticks <- 0
      do.call(graphics::axis, z)
    }
    z$labels <- FALSE
    if (s %in% ticks) {
      z$lwd <- 0
      z$lwd.ticks <- y$lwd.ticks
      if (is.null(z$lwd.ticks)) z$lwd.ticks <- 1
      do.call(graphics::axis, z)
    }
    if (s %in% sides) {
      lin <- lnpts[s:(s+1), ]
      if (is.null(y$lty)) {
        lty <- 1
      } else {
        lty <- y$lty
      }
      lines(lin, y$lwd, lty=lty, col=y$col)
    }
  }
  if (x$xlab != "") {
    posx <- usr[1] + diff(usr[1:2])/2
    text(posx, usr[3], x$xlab, pos=1, offset=x$axs$line.lab, cex=x$axs$cex.lab, xpd=TRUE)
  }
  if (x$ylab != "") {
    posy <- usr[3] + diff(usr[3:4])/2
    text(usr[1], posy, x$ylab, pos=2, offset=x$axs$line.lab, srt=90, cex=x$axs$cex.lab, xpd=TRUE)
  }
}

retro_labels <- function(x, lat=TRUE) {
  return(0)
}

get.clip <- function() {
  return(0)
}

p <- terra::plot(r, fun = extra, axe = F, main = 'WRF XLAT variable',plg=list(tic = 'none',shrink=0.98))
.plot.latlon(x = p,proj = terra::crs(r,proj=TRUE),int = int,e = e_o)

Thank you

**Comment by rhijmans** [comment]
Your code is too long for me to look at (I would prefer a *minimal* example), but I suspect that instead of 

```
usr <- graphics::par("usr")
```

You need to use the coordinates from 

```
terra:::get.clip()
```

**Comment by Schuch666** [comment]
I'm also testing the argument pax (this can be a direct way), but if I provide the argument labels the labels are missing

library(terra)
wrf <- paste(system.file("extdata", package = "eixport"),"/wrfinput_d01", sep="")
r   <- eixport::wrf_raster(file=wrf, name='XLAT')
r <- rast(r)
ax <- list(side =1,at =0, labels = 'test')
plot(r,pax = ax)

**Comment by rhijmans** [comment]
I have added a new function `map_extent` to get the coordinates for the axes and `plot( pax=list(labels= ))` now  works as expected (but also see arguments "xlabs" and "ylabs").

```
library(terra)
r <- rast(system.file("ex/elev.tif", package="terra"))
plot(r, pax=list(side=1, at=c(6, 6.2), labels=c("A", "B")))
# more control
plot(r, pax=list(xat=c(6, 6.2), xlabs=c("A", "B"), yat=c(49.6, 50), ylabs=c("C", "D")))

map_extent()
#     xmin     xmax     ymin     ymax  geo
# 5.741667 6.533333 49.44167 50.19167 TRUE
```

**Comment by Schuch666** [comment]
It is working great now, thank you!
