### ISSUE TITLE
Warning: [readStart] source already open for reading when mask with self and assign to new object

### ISSUE THREAD

**Issue by see24** [rspatial/terra#1525]
I am getting a strange warning after calling mask with the same object as both `x` and `mask`. If I then try to do anything with the input raster I get "Warning: [readStart] source already open for reading."  I have since realize that it makes more sense to use `subst` instead of mask for this task but this behavior is still strange. 

``` r
# Causes warning
rst <- terra::rast(nrows=5, ncols=5, vals=1:25)

rst1 <- terra::mask(rst, rst, maskvalue = 0, updatevalue = NA)

vals <- terra::values(rst)
#> Warning: [readStart] source already open for reading


# doesn't cause warning if all objects have same name
rst <- terra::rast(nrows=5, ncols=5, vals=1:25)

rst <- terra::mask(rst, rst, maskvalue = 0, updatevalue = NA)

vals <- terra::values(rst)

packageVersion("terra")
#> [1] ‘1.7.71’

terra::gdal(lib="all")
#>    gdal     proj     geos 
#> "3.8.2"  "9.3.1" "3.11.2" 
```

<sup>Created on 2024-05-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by Rapsodia86** [comment]
Hi @see24,
Could you update terra to the most recent dev version?
There has been an issue fix done #1473 related to the `mask()` function, so maybe that will also work for you.

**Comment by see24** [comment]
Thanks for checking but yes it still happens with terra version 1.7.79

**Comment by rhijmans** [comment]
Thank you for reporting. This warning is mostly meant for the developer, to make sure that files are properly opened and closed. In this situation is that the same file is opened twice, and the warning is triggered the second time. The warning is attached to `rst`, so only when you use that object again the warning message may be shown. It disappears when you overwrite `rst`.  There are ways to work around this but I am not going to worry about it unless this pops up elsewhere. This particular case, as you indicated, is not a good use of mask anyway.
