### ISSUE TITLE
zlim does not affect terra::plot [Potential Feature Request]

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#1527]
The `zlim` parameter in `terra::plot` does not seem to be affecting the plot. According to an [older version of the documentation](https://www.rdocumentation.org/packages/terra/versions/0.5-2/topics/plot) `zlim` can be used to set the "range of allowed values." I can't seem to find it in the documentation anymore except in `terra::plotRGB`. Is this capability no longer available? In `raster` this functionality is available, but it makes cells outside the range white. It'd be useful to be able to set bounds like in `tmap` where anything below the minimum just gets that lowest color on the scale and the highest value gets the highest color on the scale. This is useful for plotting data where extremes may be causing the image to look very washed out without making the user edit the data (e.g. reassign actual data values outside `zlim` to be at the min/max of `zlim`). Also, allowing for supplying a different `zlim` for each layer of a multiband `SpatRaster` (maybe via a list) could also be super useful.

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.3.3
#> terra 1.7.79
library(raster)
#> Warning: package 'raster' was built under R version 4.3.3
#> Loading required package: sp
library(tmap)


r <- rast(nrows=10, ncols=10)
values(r) <- 1:100
my_colors<- colorRampPalette(c("blue", "yellow", "red"))(100)


#terra plot no zlim
plot(r, col=my_colors, main="terra NO zlim")
```

![](https://i.imgur.com/8ZIr9WX.png)

``` r

#terra plot with zlim
plot(r, col=my_colors, zlim=c(90,95), main="terra WITH zlim")
```

![](https://i.imgur.com/wTsLgmn.png)

``` r


#terra plot with zlim
plot(raster(r), col=my_colors, zlim=c(90,95), main="raster WITH zlim")
```

![](https://i.imgur.com/AwyWdXf.png)

``` r

tm_shape(r)+
  tm_raster(palette = my_colors, style="cont", breaks=c(90,95))+
  tm_layout(main.title = "tmap WITH zlim")
#> Warning: Values have found that are less than the lowest break
#> Warning: Values have found that are higher than the highest break
```

![](https://i.imgur.com/JyLkrqe.png)

<sup>Created on 2024-05-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
with terra you can, instead of "zlim", use argument "range": 

```
plot(r, col=my_colors, range=c(90,95), main="terra WITH range")
```

**Comment by ailich** [comment]
Would it be possible to plot the pixels below the range or above the range as the the lowest/highest colors withing the range, rather than white? Currently accomplishing something like the tmap plot requires using mask to overwrite the values above/below the range to those limits.

**Comment by ailich** [comment]
Would it be possible to plot the pixels below the range or above the range as the the lowest/highest colors withing the range, rather than white? Currently accomplishing something like the tmap plot requires using mask to overwrite the values above/below the range to those limits.

``` r
library(terra)
#> terra 1.7.78

r <- rast(nrows=10, ncols=10)
values(r) <- 1:100
my_colors<- colorRampPalette(c("blue", "yellow", "red"))(100)


#Plot with range
plot(r, range=c(90, 95), col=my_colors, main="original with range")

#tmap
library(tmap)
#> Breaking News: tmap 3.x is retiring. Please test v4, e.g. with
#> remotes::install_github('r-tmap/tmap')
```

![](https://i.imgur.com/FA8KN1w.png)

``` r

tm_shape(r)+
  tm_raster(palette = my_colors, style="cont", breaks=c(90,95))+
  tm_layout(main.title = "tmap")
#> Warning: Values have found that are less than the lowest break
#> Warning: Values have found that are higher than the highest break
```

![](https://i.imgur.com/cxIUA2V.png)

``` r

# Overwrite values
r2<- r
r2<- mask(r2, mask = r < 90, maskvalues=1, updatevalue=90)
r2<- mask(r2, mask = r > 95, maskvalues=1, updatevalue=95)

plot(r2, range=c(90, 95), col=my_colors, main= "overwitten with range")
```

![](https://i.imgur.com/cu125tH.png)

<sup>Created on 2024-10-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Instead of `mask` you can use `clamp` like this 

```
x <- clamp(r, 90, 95)
plot(x)
```

But you now can also set argument "fill_range"  to `TRUE`

```
plot(r, range=c(90,95), fill_range=TRUE)
```

**Comment by ailich** [comment]
Thanks, I didn't know about clamp but nice to have both options!
