### ISSUE TITLE
External reference error in *writeRaster*

### ISSUE THREAD

**Issue by bryce-carson** [rspatial/terra#1538]
[This script, preaggregator.tar.gz](https://github.com/user-attachments/files/15778270/preaggregator.tar.gz), fails due to one two errors:

1. (in #1539) "file already exists" despite the argument `overwrite = TRUE`, or
2. (in this issue) an "external reference" error.

I am re-running the script, which takes a few minutes, and then I will update this issue and the related issue with further information and explicit quotations of the error messages.

**Comment by bryce-carson** [comment]
The directory structure is as diagrammed below.

```
[bryce@fedora]~/src/r/spatialEpisim% tree -d -L 1
.
├── gadm
├── misc
├── observeddata
├── preaggregated_data
├── R
├── rsconnect
├── scripts
├── seeddata
├── tif
└── www
```

**Comment by bryce-carson** [comment]
I apologize for the series of comments and the slight disorganization of the issue; I can modify the script with the reprex package in mind if needed. The script is quite simple and simply checks for existing files and overwrites them if necessary after aggregating some downloaded TIF format rasters from worldpop.org.

**Comment by bryce-carson** [comment]
Running the script serially, with `%do%`, somehow permitted the script to run to completion. I did also enable the `cores` argument in aggregate.

**Comment by rhijmans** [comment]
This error most likely occurs because SpatRaster objects cannot be serialized. You need to take some additional steps to use them in To use them in parallel computing. There is some discussion here: https://stackoverflow.com/a/67449818/635245 and in similar places.
