### ISSUE TITLE
Readable output of (WKT) representation of the CRS

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#154]
Would it be possible having a readable output of `crs(r)` ?
Also, something just providing the epsg code would be very useful (even if you hate epsg codes), i.e.
`epsg(r)`
could output something like:
25831

**Comment by rhijmans** [comment]
You can now do:

```
library(terra)
x <- rast()
crs(x, describe=T)
#    name EPSG  area             extent
#1 WGS 84 4326 World -180, 180, 90, -90 
```

Of course this only works if there is a known EPSG code.
