### ISSUE TITLE
Faster way to check if a SpatRaster has at least one non-NA value

### ISSUE THREAD

**Issue by kevinwolz** [rspatial/terra#1540]
To check if a SpatRaster (`x`) has at least one non-NA value, I am currently using this:
```
any(as.numeric(terra::global(x, fun = "notNA")[,1]) > 0)
```
This works on SpatRasters that have one or multiple layers. It works fine, but I think `terra::global` is checking the entire raster. I don't need to check the entire raster, and, for large rasters, this can take a long time. I'm looking for a method that stops when it finds the first non-NA value. This would save considerable time when checking a large SpatRaster.

Would it be possible to implement something like `fun = "anynotNA"` for `terra::global`?

For context, the reason I am doing this check in the first place is because I am using `terra::trim()` in a situation where the raster may or may not have non-NA values. When applying `terra::trim()` to a SpatRaster with only NA values, it throws an error, so I must check to ensure there is at least one non-NA value before applying `terra::trim()`. Perhaps there is a better way to deal with this in this specific example? Either way, I think this feature would be useful in other contexts as well.

**Comment by rhijmans** [comment]
I have added functions "anyNA", "anynotNA" that ought to be more efficient.

**Comment by kevinwolz** [comment]
@rhijmans I noticed that you added "anyNA" and "anynotNA" to the Description section of the documentation for `global()` but did not add them to the section describing the `fun` argument. Adding them to the `fun` argument definition would be helpful.
