### ISSUE TITLE
`plet(SpatRaster)` default `tiles` argument produces a warning

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1542]
We get a somewhat puzzling warning when pletting a raster with the default settings:

```
r <- rast(system.file("ex/elev.tif", package="terra"))
plet(r)

# Warning message:
# [plet] only a single tileset can be used with raster data
```

In the _Usage_ section of the `?plet` help file, we have:

```
## S4 method for signature 'SpatRaster'
plet(x, y=1, col, alpha=0.8, main=names(x), 
	tiles=c("Streets", "Esri.WorldImagery", "OpenTopoMap"), 
	[. . .]
```
So maybe the `tiles` default for rasters should be just `tiles="Streets"`?

Cheers!

**Comment by rhijmans** [comment]
Thanks, fixed now. With SpatVector it is possible to supply multiple tile sets.
