### ISSUE TITLE
`rast()` crashes R with some .nc files where `raster::brick()` does not. 

### ISSUE THREAD

**Issue by MartinHoldrege** [rspatial/terra#1544]
Thank you for developing and maintaining the excellent terra package!

I'm having R crash immediately when running `terra::rast()` for some publicly available netCDF files containing climate data  (http://thredds.northwestknowledge.net:8080/thredds/catalog/MET/climatologies/monthlyClimatologies/catalog.html). I am managing to open the files with some other R packages.  

The file used in the example below can be downloaded via this link: 
http://thredds.northwestknowledge.net:8080/thredds/fileServer/MET/climatologies/monthlyClimatologies/gridmet_tmmx_monthlyClimatologies_19912020.nc

Code illustrating the problem: 

`
path <- 'gridmet_tmmx_monthlyClimatologies_19912020.nc'

ncdf4::nc_open(path) # works
RNetCDF::open.nc(path) # works
tmp <- raster::brick(path) # works
tmp2 <- raster::readAll(tmp) # works
terra::rast(tmp2) # works
terra::rast(path) # R crashes
terra::rast(raster::brick(path)) # R crashes
`

Output:
`
> tmp <- raster::brick(path) # works
> tmp2 <- raster::readAll(tmp) # works
> terra::rast(tmp2) # works
class       : SpatRaster 
dimensions  : 585, 1386, 12  (nrow, ncol, nlyr)
resolution  : 0.041666, 0.041666  (x, y)
extent      : -124.793, -67.04392, 25.04224, 49.41686  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
source(s)   : memory
names       :       X0,       X1,       X2,       X3,       X4,       X5, ... 
min values  : 262.3419, 264.3821, 265.2548, 267.7100, 271.6484, 274.2667, ... 
max values  : 298.9000, 300.2929, 302.0581, 306.5667, 311.5097, 317.3400, ... 
`
-----------------------------------------------------
Session info: 

`> version
               _                                
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          4.0                              
year           2024                             
month          04                               
day            24                               
svn rev        86474                            
language       R                                
version.string R version 4.4.0 (2024-04-24 ucrt)
nickname       Puppy Cup                        
> packageVersion("terra")
[1] ‘1.7.78’
> terra::gdal(lib="all")
    gdal     proj     geos 
 "3.8.4"  "9.3.1" "3.12.1" `

**Comment by rhijmans** [comment]
Thanks for reporting this. That happened because the months are encoded 0-11 (I expected 1-12)

I now get:

```
path <- "gridmet_tmmx_monthlyClimatologies_19912020.nc"
terra::rast(path) 
#class       : SpatRaster
#dimensions  : 585, 1386, 12  (nrow, ncol, nlyr)
#resolution  : 0.041666, 0.041666  (x, y)
#extent      : -124.793, -67.04392, 25.04224, 49.41686  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84)
#source      : gridmet_tmmx_monthlyClimatologies_19912020.nc
#varname     : tmmx (tmmx)
#names       : tmmx_1, tmmx_2, tmmx_3, tmmx_4, tmmx_5, tmmx_6, ...
#unit        :      K,      K,      K,      K,      K,      K, ...
#time (mnts) : Jan to Dec
```

**Comment by MartinHoldrege** [comment]
Great, thank you!
