### ISSUE TITLE
alternate behavior for `range=` argument in `terra::plot()` for SpatRasters to not mask extreme values

### ISSUE THREAD

**Issue by mikoontz** [rspatial/terra#1553]
Hello!

I am trying to plot a SpatRaster with the color palette mapped to a specific range in the data. I can use the `range=` argument to set the bounds for the data to be mapped, such that the full range of the color palette is used. The default behavior in this case is to mask out values that are beyond the specified `range`. Is it possible to instead color those points using the extreme value of the color palette? 

```
set.seed(1)
r = terra::rast(nrow = 5, ncol = 5)
terra::values(r) = sample(x = 1:25, size = 25)
terra::plot(r, col = viridis::inferno(100, direction = -1), range = c(5, 20))
```

![image](https://github.com/rspatial/terra/assets/11068126/3d971f89-19d1-4c1c-95db-fdf1ee4d7a6b)

If this is possible (or a reasonable feature to request), is it possible to also adjust the legend to suggest that the extreme colors represent values <= (and/or >=) the minimum (and/or maximum) specified in the `range`? 

This would essentially be mimicking matplotlib's `extend` argument for creating a `colorbar` (https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.colorbar.html). That implementation uses triangles at the end of the colorbar to suggest the extreme colors of the palette represent all values smaller and/or larger than the range.

[teunbrand](https://stackoverflow.com/users/11374827/teunbrand) hacked ggplot2 to do this [here](https://stackoverflow.com/questions/68440366/how-can-i-add-triangles-to-a-ggplot2-colorbar-in-r-to-indicate-out-of-bound-valu). (Note this implementation may not work in recent versions of ggplot2, but the author built a more generalized approach in their package [here](https://teunbrand.github.io/gguidance/reference/guide_colourbar_custom.html)). And a real life Python example is [here](https://stackoverflow.com/questions/32072198/distinguishing-clipped-values-in-colorbar/32072348#32072348) (but which uses extra `set_under` and `set_over` methods to force the extreme colors to be something different than the extreme colors in the supplied plotting palette.)

I'm certainly open to other ways of visualizing the >= or <= than triangles at the end of the colorbar. Even a label on the extreme values to literally say `<=` and/or `>=` next to the minimum value and/or maximum value of the range might suffice?

A real example of this might look like this:
![image](https://github.com/rspatial/terra/assets/11068126/7113f09f-ab9f-45f0-9f94-c11f9fd9f5ad)

With the barebones code to recreate it looking like this (with `range` specified, but which masks out values outside that range and with a squared off colorbar).

```
nightfire = read.csv("https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-04325-1/MediaObjects/41586_2021_4325_MOESM2_ESM.csv")
r = terra::rast(nightfire, crs = sf::st_crs(4326)$wkt)
terra::plot(r, range = c(0, 60), col = viridis::inferno(100, direction = -1))
```

```
> packageVersion("terra")
[1] ‘1.7.71’
> terra::gdal(lib="all")
    gdal     proj     geos 
 "3.8.2"  "9.3.1" "3.11.2" 
```

**Comment by rhijmans** [comment]
Thank you for that suggestion. I have added the argument `fill_range=FALSE`. Setting it to `TRUE`  may give you what you are after. 

```
library(terra)
set.seed(1)
r = terra::rast(nrow = 5, ncol = 5, vals=sample(1:25, 25))
terra::plot(r, range=c(5, 20), fill_range=TRUE)
```
![range](https://github.com/user-attachments/assets/856995e0-cb58-46d8-b547-57bcb536698e)

```
nightfire = read.csv("https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-04325-1/MediaObjects/41586_2021_4325_MOESM2_ESM.csv")
x = terra::rast(nightfire, crs = sf::st_crs(4326)$wkt)
terra::plot(x, range = c(0, 60), col=viridis::inferno(100, direction=-1), fill_range=TRUE)
```
![fire](https://github.com/user-attachments/assets/23714c5e-ecdf-41e3-9e97-ecf909f2c5e5)


To only limit one extreme, you can now also do 

```
terra::plot(x, range = c(NA, 60), col=viridis::inferno(100, direction=-1), fill_range=TRUE)
```

**Comment by mikoontz** [comment]
@rhijmans !! This is very slick! Thank you so much for implementing this suggestion. It gets me exactly what I was after.
