### ISSUE TITLE
as.polygons() renders upside-down object

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#1559]
While the following works fine:

```
library(terra)
r2 <- k_means(rast(system.file("ex/logo.tif", package="terra"))[[1]], centers=8)
crs(r2) <- "local"
r2
#class       : SpatRaster 
#dimensions  : 77, 101, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#coord. ref. : Cartesian (Meter) 
#source(s)   : memory
#varname     : logo 
#name        : red 
#min value   :   1 
#max value   :   8 

v2 <- as.polygons(r2) 
plot(r2,col=sample(rainbow(8)))
plot(v2,add=TRUE)
```

The vector is upside-down with my data:

```
s <- rast("../microsam/commits/committed_objects_auto.tif")
Warning message:
[rast] unknown extent 

crs(s) <- "local"
s
class       : SpatRaster 
dimensions  : 1920, 2560, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0, 2560, 0, 1920  (xmin, xmax, ymin, ymax)
coord. ref. : Cartesian (Meter) 
source      : committed_objects_auto.tif 
name        : committed_objects_auto 
min value   :                      0 
max value   :                   2276 

crs(s)
[1] "ENGCRS[\"Cartesian (Meter)\",\n    EDATUM[\"Local Datum\"],\n    CS[Cartesian,2],\n        AXIS[\"x\",east,\n            ORDER[1],\n            LENGTHUNIT[\"Meter\",1]],\n        AXIS[\"y\",north,\n            ORDER[2],\n            LENGTHUNIT[\"Meter\",1]]]"

v <- as.polygons(s)
crs(v)
[1] "ENGCRS[\"Cartesian (Meter)\",\n    EDATUM[\"Local Datum\"],\n    CS[Cartesian,2],\n        AXIS[\"x\",east,\n            ORDER[1],\n            LENGTHUNIT[\"Meter\",1]],\n        AXIS[\"y\",north,\n            ORDER[2],\n            LENGTHUNIT[\"Meter\",1]]]"

plot(s,col=sample(rainbow(2276)))
plot(v,add=TRUE)
```

![image](https://github.com/user-attachments/assets/baa9d5e6-285e-437d-afff-a797aa2f5401)

```
plot(flip(s,direction="v"),col=sample(rainbow(2276)))
plot(v,add=TRUE)
```

![image](https://github.com/user-attachments/assets/5891ec4a-23bd-40e7-a9cb-298d13ffcf57)
(the correct orientation is the one of the unflipped raster, this is just for illustration)

Why? 
```
> ext(s)
SpatExtent : 0, 2560, 0, 1920 (xmin, xmax, ymin, ymax)
> ext(v)
SpatExtent : 0, 2560, 0, 1920 (xmin, xmax, ymin, ymax)
> 
```
Input raster here:
https://www.dropbox.com/scl/fi/lqxwof1lwhk0ib8grg7c5/committed_objects_auto.tif?rlkey=eqw0vf1rne2p1nq8j09otesap&dl=0

**Comment by rhijmans** [comment]
The data in the file do not seem to match your images. Also, you do not show how you get there, but if I do 

```
library(terra)
r <- rast("committed_objects_auto.tif")
k <- k_means(r, centers=8)
vk <- as.polygons(k) 
plot(k,col=sample(rainbow(8)))
lines(vk)
```
 Or

```
rr <- r
crs(rr) <- "local"
kk <- k_means(rr, centers=8)
vkk <- as.polygons(kk) 
plot(kk, col=sample(rainbow(8)))
lines(vkk)
```

Everything looks as expected. 

Are you using the current version of "terra"?

**Comment by aloboa** [comment]
Using terra_1.7-78
By some reason, the rotation gets "fixed" by k_means(), but I do not want to use k_means() with
my data, as the values are a categorical variable: it is the result of a segmentation and the
values are just a unique index for each patch- The segmentation is calculated with napari micro-sam:

```
rr <- rast("committed_objects_auto.tif")
crs(rr) <- "local"
kk <- k_means(rr, centers=8)
vkk <- as.polygons(kk) 
plot(kk, col=sample(rainbow(8)))
lines(vkk)

```
![image](https://github.com/user-attachments/assets/e9c7c4bd-aed1-4be6-8e21-0988ec4dbac1)

It is also fixed by:

```
rr2 <- rr*1
vrr2 <- as.polygons(rr2) 
plot(rr2, col=sample(rainbow(1024)))
lines(vrr2)
```
(which works to circumvent the problem)
But:

```
vrr <- as.polygons(rr) 
plot(rr, col=sample(rainbow(1024)))
lines(vrr)
```

![image](https://github.com/user-attachments/assets/71188d99-7ea7-4d6a-a721-9b46350555eb)

**Comment by rhijmans** [comment]
OK, thank, I now understand the issue 


```
library(terra)
#terra 1.7.80
r <- rast("committed_objects_auto.tif")
#Warning message:
#[rast] unknown extent

#v1 is flipped vertically 
v1 <- as.polygons(r) 

#v2 is correct
v2 <- as.polygons(r * 1)
```
I do not see this with other SpatRasters that have file data source, so I am guessing this is related to the file having incomplete metadata (no extent).

**Comment by aloboa** [comment]
> I do not see this with other SpatRasters that have file data source, so I am guessing this is related to the file having incomplete metadata (no extent).

Right, and I agree with your edit of the Title, the rotation is probably unrelated to the CRS.
Lacking extent is probably the case for many image files not coming from GIS software.

**Comment by rhijmans** [comment]
Fixed now, at least for the example file. Thanks for reporting.
