### ISSUE TITLE
Differences in grid projections between raster and terra

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#156]
This may not be an issue, but rather something that I'm not familiar with how it works. Projecting grids from lat/long in `raster` to a projected system will create a `RasterLayer` with an unequal resolution (xres != yres). Doing the same projection in `terra` will produce a grid with equal x and y resolutions but those will vary from those found in the reprojections in `raster`. Here is a reproducible example:

```
library(raster)
library(terra)

f <- system.file("ex/elev.tif", package="terra")

r <- raster(f)
r_trans <- projectRaster(r, crs = crs("+init=epsg:3005"))

t <- rast(f)
t_trans <- project(t, "epsg:3005")

res(r_trans)
# 886 574

res(t_trans)
# 771.8744 771.8744
```

When I bring this file into different GIS programs (QGIS/GDAL) and perform a similar projection, I'll get the same results as `terra`, SAGA GIS reproduces something closer to the maximum resolution of the `raster` result. I am curious what the differences in grid projection are between `raster` and `terra`, and how they might relate to other programs as well?

**Comment by rhijmans** [comment]
the underlying reason for these discrepancies is that transforming raster data is not well defined if you only provide the target CRS (this is not the case for vector data). To fully define the output with raster data, the 'raster' and 'terra' packages allow you to provide a target raster template --- and that  is the only appropriate way to do it.  Only specifying the CRS is allowed as a shortcut and to help create the output template, but it is not something you should use in an analytical workflow. 

For the 'raster' package, I wrote the rules to determine the output extent and resolution. 'terra' uses GDAL for this. Hence the difference. Apparently QGIS also uses GDAL, while SAGA has its own algorithm that is similar to what I wrote for raster.

**Comment by rhijmans** [comment]
(The commit above was for another issue)
