### ISSUE TITLE
mtext equivalent function

### ISSUE THREAD

**Issue by Schuch666** [rspatial/terra#1567]
Is there a equivalent function of mtext from base, to include text outside the ploting region of maps using terra::plot() ?
There is a way to make it work with mtext or other way to plot outside the map from terra::plot?

**Comment by rhijmans** [comment]
I have added a new function `add_mtext` that uses the map's margins. 

```
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)

plot(r, axes=FALSE, legend=FALSE)
add_box()
for (i in 1:4) add_mtext("margin text", i, cex=i, col=i, line=2-i)
```

![mtext](https://github.com/user-attachments/assets/836247b2-b0ac-4f7b-a4fb-e665bcaa5dc3)

The function may need some more work to support fancy stuff.

An alternative approach would be to use `text(x, y, "text", xpd=TRUE)`

**Comment by Schuch666** [comment]
Thanks it works!
