### ISSUE TITLE
resample()'s cubic and Lanczos window sizes are undocumented

### ISSUE THREAD

**Issue by twest820** [rspatial/terra#1568]
I'm extracting aligned samples from several rasters with different cell sizes and then standardizing them to one cell size with `resample()`. Because the rasters are large (hundreds of MB to tens of GB for the virtual rasters) and the standardization is to the smallest cell size, it's necessary to window the area of interest before resampling. I had a bug where the windows weren't necessarily quite large enough, resulting in `resample()` occasionally producing `NA`s at area of interest edges.

As part of fixing this, I noticed terra's `resample()` documentation doesn't state window size requirements for cubic and Lanczos. I'm guessing terra indirectly calls [`IRasterIO()`](https://gdal.org/api/gdalrasterband_cpp.html) with `resample()`'s `method` argument remapped to [`GDALRIOResampleAlg`](https://gdal.org/api/raster_c_api.html#_CPPv420GDALRasterIOExtraArg). Is this correct? If so, the result would be `cubic` and `cubicspline` use a 4x4 window and `lanczos` a 6x6.

**Comment by rhijmans** [comment]
This uses [GDALwarp](https://gdal.org/api/gdalwarp_cpp.html) , but surely RasterIO uses the same underlying algo. I have added the window size to the docs (adding 1, as I think it should be 5x5 and 7x7). Thanks.
