### ISSUE TITLE
Write multiple layers in terra functions

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#157]
For functions like `mask`, it is possible to write the output as a single file; however, when the input is multilayered it will force a single file output. I've included an example below, mostly using the example code provided from the `mask` documentation:

```
library(terra)
r <- rast(ncol=10, nrow=10, nlyrs=2)
m <- rast(ncol=10, nrow=10)
values(r) <- 1:100
set.seed(1965)
x <- round(3 * runif(ncell(r)))
x[x==0] <- NA
values(m) <- x

# Attempt to write two layers to separate files, throws a warning and writes only one file
mr <- mask(r, m, filename = tempfile(pattern = names(r), fileext = ".tif"))
#Warning message:
#[mask] only the first filename supplied is used
```

Is it possible to include such functionality? I'm aware that `writeRaster` is able to do this on its own, I was trying to skip that part though and write multiple layers to separate files straight from the function. Or, in a case such as this, is it better to apply the function separately to each layer? For example:

```
mr2 <- rast(lapply(1:nlyr(r), function(x) {
  mask(r[[x]], m, filename = tempfile(pattern = names(r[[x]]), fileext = ".tif"))
}))
```

I'm not sure if there is a simpler way of achieving a similar result as above using `terra` functions so please indicate if there is a better way to go about this. Do you think that masking (or performing other functions) by layer will have an impact on processing speed, vs. if the layers were kept together and the function is performed on each? 

Thank you for your guidance, I know I've submitted issues in the past and you've been very helpful with resolving them!

**Comment by rhijmans** [comment]
The only way to achieve that would be to loop over the layers, as you do with `lapply`. It would be neat to allow providing multiple filenames to all methods. That should be possible to do, but that would require some major changes that I currently cannot make (there are too many other things to improve).

**Comment by mcoghill** [comment]
Thanks for the input, I'll keep using the `lapply` methods that I've been able to figure out and keep an eye out if any further updates add this kind of functionality!
