### ISSUE TITLE
Add arguments to math functions

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#158]
I haven't tried all of the math functions, and only noticed this using `log`, but it appears that some arguments may need to be incorporated for use in this package, for example:

```
library(terra)
f <- system.file("ex/logo.tif", package="terra")
r <- rast(f)

# Same math functions, different results
l10 <- log(r, base = 10)
l10_base <- log10(r)

# Same math functions, different results
l2 <- log(r, base = 2)
l2_base <- log2(r)

# Display of differing results (0 = FALSE, 1 = TRUE)
l2_eq <- l2 == l2_base
l10_eq <- l10 == l10_base
l2_l10_eq <- l2 == l10

plot(l2_eq)
plot(l10_eq)
plot(l2_l10_eq)
```
In this case, I think that the argument for `base` is missing in the log calculation. I'm not sure what other math functions need to be considered, this is just my first encounter with the issue. A workaround is to perform the log calculation in the `app` function which will generate the expected results.

**Comment by rhijmans** [comment]
`log` is now implemented separately, and not via the group-generic Math methods (see ?Math`), and the base argument is now honored. I now get, e.g., 

```
minmax(log10(r))
#         red   green    blue
#[1,]    -Inf    -Inf    -Inf
#[2,] 2.40654 2.40654 2.40654
minmax(log(r, 10))
#         red   green    blue
#[1,]    -Inf    -Inf    -Inf
#[2,] 2.40654 2.40654 2.40654
```
