### ISSUE TITLE
`unit` argument of `distance` is not working properly.

### ISSUE THREAD

**Issue by LuisLauM** [rspatial/terra#1586]
From the issue reported previously ([link](https://github.com/rspatial/terra/issues/1545)), I have noticed that the problem persists. I leave a reproducible example

```
df <- data.frame(Lat = c(42.1234, 41.0192, 40.9988, 51.0175, 50.6523, 50.9214), 
                 Lon = c(26.5462, 25.9967, 27.0001, 31.1542, 31.8924, 32.1025))

distance(x = as.matrix(df[,c("Lon", "Lat")]),
         y = as.matrix(df[,c("Lon", "Lat")]), 
         lonlat = TRUE, unit = "m")
distance(x = as.matrix(df[,c("Lon", "Lat")]), 
         y = as.matrix(df[,c("Lon", "Lat")]),
         lonlat = TRUE, unit = "km")
```

![image](https://github.com/user-attachments/assets/d6d41baf-c0b8-440a-8f73-9e70528105c0)

**Comment by kadyb** [comment]
Have you updated `terra` to devel version? The new version has not been released on CRAN yet. You can download binary version that does not require compilation by yourself from R-Universe:

```r
install.packages("terra", repos = "https://rspatial.r-universe.dev")
```

**Comment by LuisLauM** [comment]
In fact, in the devel version the problem has already been corrected.
