### ISSUE TITLE
Feature Request: analog to sp::surfaceArea()

### ISSUE THREAD

**Issue by hannahlowens** [rspatial/terra#1587]
As the subject line says, it would be fantastic to have a `terra` option for `sp::surfaceArea()`--that is, using an elevation raster to calculate surface area. I've been using cellArea/cos(slope), but it's not as satisfying.

**Comment by ailich** [comment]
The SurfaceArea function in MultiscaleDTM can accomplish this if you're still looking for a solution.

https://github.com/ailich/MultiscaleDTM

**Comment by rhijmans** [comment]
And you can now compare that to `terra::surfArea`
@ailich: MultiscaleDTM looks great!

**Comment by ailich** [comment]
As a comparison
- The final results are essentially identical (e-15 level differences) 
- Your terra implementation seems to be about 2.75 times faster
- terra has edge corrections for the edge of the raster. MultiscaleDTM will have those as NA's by default.
- MultiscaleDTM has an na.rm flag (though this slows things down). This will provide different results than the edge correction implemented in terra but can also handle na's in the raster grid.

**Comment by hannahlowens** [comment]
Fabulous! Thanks for this!
