### ISSUE TITLE
Using the win argument when reading in multiple files results in: [rast] extents do not match

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1589]
Hi Robert! 
I am not sure if that is an issue, or the expected behavior. If the latter, then I take it back! 
I do have many files that I want to load as a raster stack. They have slightly different extents. To handle that, I would use the "win" argument in `rast()`, to "internally crop" the data and load up. 

If I do this in a loop, everything is ok. 
But if I use a vector of file names, then the error shows up: `Error: [rast] extents do not match`. 

Does that mean `rast()` first stacks all the rasters and then applies the "win"? Or it should be that it takes each object separately (like in a loop), applies the "win" and then stacks? 

Below is a small example with only two files: (terra dev version)
```
library(terra)
terra 1.7.79
> aoi_ext <- ext(c(633138, 634573, 4694581, 4697348))
> rasts <- c("X:/MYDIR/HLS_S30_sr_evi2_doy2023342_aid0001_16N.tif", "X:/MYDIR/HLS_S30_sr_evi2_doy2023347_aid0001_16N.tif")
> 
> rstack <- rast(rasts,win=aoi_ext)
Error: [rast] extents do not match

##Here one by one works!:

> rstack <- rast()
> for (ff in rasts){
+   rstack <- c(rstack,rast(ff,win=aoi_ext))
+ }
Warning message:
[rast] the first raster was empty and was ignored 
> rstack
class       : SpatRaster 
dimensions  : 92, 47, 2  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
window      : 633150, 634560, 4694580, 4697340  (xmin, xmax, ymin, ymax)
coord. ref. : WGS 84 / UTM zone 16N (EPSG:32616) 
sources     : HLS_S30_sr_evi2_doy2023342_aid0001_16N.tif  
              HLS_S30_sr_evi2_doy2023347_aid0001_16N.tif  
names       : HLS_S30_sr_evi2~342_aid0001_16N, HLS_S30_sr_evi2~347_aid0001_16N 
```
```
sessionInfo()
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.7-79

loaded via a namespace (and not attached):
[1] compiler_4.4.0   tools_4.4.0      Rcpp_1.0.12      codetools_0.2-20
```

Thanks!

[win_terra_rspatial_test.zip](https://github.com/user-attachments/files/16733753/win_terra_rspatial_test.zip)

**Comment by Rapsodia86** [comment]
Hi @rhijmans, 
Looks like a work-around has been removed? So, the only way is with vrt?

**Comment by rhijmans** [comment]
Hi, this seems to work:

```
f <- system.file("ex/elev.tif", package="terra")
r <- rast(c(f,f), win=c(5.8, 6, 50, 50.1))
```

If you see something that does not work, then please start a new issue.

**Comment by rhijmans** [comment]
Or the "work-around"

```
library(terra)
f1 <- system.file("ex/elev.tif", package="terra")
f2 <- "test.tif"
r <- writeRaster(shift(rast(f1), 0.1, 0.1)*1, f2, overwrite=TRUE)
x <- lapply(c(f1, f2), \(f) rast(f, win=e)) |> rast()
```

**Comment by Rapsodia86** [comment]
Hi @rhijmans,
Thank you and sorry! 
Turned out, I was getting "extents do not match" error, because the rasters were misaligned by so little that I did not notice it first. 
I used vrt for a quick fix, but then decided to reproject one to another. Your two examples work well; thank you again!
