### ISSUE TITLE
Too large margins in 'plotRGB'

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#159]
The default margins in `plotRGB()` seem too large making the image small. Oddly enough, using `plotRGB()` from **raster**, and then using **terra** again, makes better margins.

```r
library("terra")
library("raster")

file = system.file("ex/logo.tif", package = "terra")

ras_terra = rast(file)
ras_raster = brick(file)
```

```
terra::plotRGB(ras_terra)
```
![1](https://user-images.githubusercontent.com/35004826/108601111-33bbc180-739b-11eb-96ef-9a04de72b15a.png)

```
raster::plotRGB(ras_raster)
```
![2](https://user-images.githubusercontent.com/35004826/108601119-3d452980-739b-11eb-8a61-dd24ec77eb7f.png)

```
terra::plotRGB(ras_terra)
```
![3](https://user-images.githubusercontent.com/35004826/108601127-46ce9180-739b-11eb-9f70-6e701c929431.png)

**Comment by rhijmans** [comment]
In terra, the help shows how to set the margin with  `graphics::par(plt=c(0,1,0,1))`
you can also do graphics::par(mar=c(0,0,0,0))`
But the development version now has a `mar` argument (like `terra::plot`) that by default sets the margins to zero, such that it behaves like the `raster` package.
