### ISSUE TITLE
Problem with images created with terra::colorize() in leaflet::addRasterImage

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#1591]
Is there perhaps something to be attempted from the terra side to at least circumvent the problem
described at the end of https://github.com/rstudio/leaflet/issues/900 ?

**Comment by rhijmans** [comment]
Can you provide a reproducible example?

**Comment by rhijmans** [comment]
`plet(a)` and `plet(r)`  look much better in the dev version of `terra` (probably because I improved the color-table created by `colorize`).  So I think this has been solved.

**Comment by rhijmans** [comment]
```
plet(a)
```

<img width="585" alt="image" src="https://github.com/user-attachments/assets/85bf5bb7-f71c-4224-a812-ee1313fb65f4">

**Comment by aloboa** [comment]
I confirm it works fine with terra 1.8.3
