### ISSUE TITLE
Display color raster with plet()

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#1596]
Given
```
s <- rast(system.file("ex/logo.tif", package="terra"))   
s
plot(s)
```
![image](https://github.com/user-attachments/assets/87497583-50de-444a-be28-afb0c0df7e4e)

Is it possible to get plet() to display the same colors?

`plet(s)`

![image](https://github.com/user-attachments/assets/6c664698-f8c2-418e-83b2-e9e5105b44e7)

Same result with

```
ss <- colorize(s, "col")
plet(ss)
```

**Comment by jflowernet** [comment]
Might be an issue with an older version of `terra`? I get the expected results:

``` r
library(terra)
#> terra 1.7.83
gdal()
#> [1] "3.4.1"

s <- rast(system.file("ex/logo.tif", package="terra"))   
s
#> class       : SpatRaster 
#> dimensions  : 77, 101, 3  (nrow, ncol, nlyr)
#> resolution  : 1, 1  (x, y)
#> extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#> coord. ref. : Cartesian (Meter) 
#> source      : logo.tif 
#> colors RGB  : 1, 2, 3 
#> names       : red, green, blue 
#> min values  :   0,     0,    0 
#> max values  : 255,   255,  255
plot(s)
```

![](https://i.imgur.com/k5ldrt4.png)

``` r


plet(s)
```

![](https://i.imgur.com/k6E48Bl.png)

``` r

RGB(s) <- 1:3
plet(s)
```

![](https://i.imgur.com/dqXqKod.png)

``` r
s <- colorize(s, "color")
plet(s)
```

![](https://i.imgur.com/swQrihS.png)

<sup>Created on 2024-10-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by aloboa** [comment]
With terra 1.7.83 I get now:

```
s <- rast(system.file("ex/logo.tif", package="terra"))  
plet(s)
```

![image](https://github.com/user-attachments/assets/13a8e6f5-6ff2-475b-a74e-bf62e0d441e5)

which is better but still not the same as 
`plot(s)`

**Comment by rhijmans** [comment]
Thanks. This now works as expected.

**Comment by aloboa** [comment]
Yes!

**Comment by rhijmans** [comment]
You can now do  

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))
plet(s, stretch="hist")
```

<img width="369" alt="image" src="https://github.com/user-attachments/assets/235c6e21-537c-432d-aa28-4c33ce76540f">

**Comment by aloboa** [comment]
Not with last version 1.8.3:
```

> library(terra)
terra 1.8.3
s <- rast(system.file("ex/logo.tif", package="terra"))/100
plotRGB(s,1,2,3)
plotRGB(s,1,2,3,stretch="lin")
```
![image](https://github.com/user-attachments/assets/35a428c2-7c04-4200-b9f9-f352cc4642b8)

`plet(s)`
![image](https://github.com/user-attachments/assets/d9f7774f-7f2a-4064-a1ac-40bb8629c386)

Same with:

```
plet(s, stretch="hist")
plet(s, stretch="lin")
```

**Comment by rhijmans** [comment]
By *my example* works (at least for me). You divide the raster by 100 and then it is no longer an RGB image.

**Comment by aloboa** [comment]
> You divide the raster by 100 and then it is no longer an RGB image.

`stretch=lin` is not supposed to take care of that, as it does in plotRGB()?

**Comment by rhijmans** [comment]
With `plotRGB` there is no doubt that we are dealing with an RGB raster. With `plot` and `plet` that needs to be explicit.

**Comment by rhijmans** [comment]
For example compare the two plots 

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))
plot(s)
plot(s/100)
```

**Comment by aloboa** [comment]
I see, but
```
> class(s)
[1] "SpatRaster"
attr(,"package")
[1] "terra"
> class(s/100)
[1] "SpatRaster"
attr(,"package")
[1] "terra"
```
still think that stretch="lin" should transform the object to the (0,255) range, and thus I would expect
`plot(r/100, stretch="lin)`
to be the same colors as
`plot(r, stretch="lin")`

But you must have your reasons. 
What I would like to know is, how should we display r/100 to have the same colors as plot(r) ?
__

**Comment by aloboa** [comment]
Excellent!
