### ISSUE TITLE
Plot legend disappears when using coltab()

### ISSUE THREAD

**Issue by avaloncookpb** [rspatial/terra#1602]
Hi there,

I recently discovered the coltab() function, which allows me to assigned fixed colors to specific values in a raster -- highly useful. It also seems that the plot does not produce a legend after I run my raster through the coltab() function. I've not been able to find a workaround to this. The example provided for the coltab() function demonstrates the issue. I've shortened it here:

```
r <- rast(ncols=3, nrows=2, vals=1:6)
plot(r)
coltb <- data.frame(value=1:6, col=rainbow(6, end=.9))
coltab(r) <- coltb
plot(r)
```

Can you advise?

Thanks

**Comment by Nowosad** [comment]
@avaloncookpb I assume you also need to add your labels:

``` r
library(terra)

r <- rast(ncols=3, nrows=2, vals=1:6)
coltb <- data.frame(value=1:6, col=rainbow(6, end=.9))

plot(r)
```

![](https://i.imgur.com/ifJFGvR.png)

``` r

coltab(r) <- coltb
plot(r)
```

![](https://i.imgur.com/gyqDyA2.png)

``` r

levels(r) <- data.frame(value = 1:6, cat = LETTERS[1:6])
plot(r)
```

![](https://i.imgur.com/gtphd0S.png)

<sup>Created on 2024-09-13 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
If you do not want to change the labels another approach is to use `coltb` as the "col" argument in `plot`.

```
library(terra)
r <- rast(ncols=3, nrows=2, vals=1:6)
coltb <- data.frame(value=1:6, col=rainbow(6, end=.9))
plot(r, col=coltb)
```
