### ISSUE TITLE
Unable to modify the time of a nc file

### ISSUE THREAD

**Issue by renliang1996** [rspatial/terra#1603]
In fact, even the examples in the help document cannot be reproduced:

```
library(terra)
r <- rast(system.file("ex/logo.tif", package="terra"))   
s <- c(r, r)
time(s) <- as.Date("2001-01-01") + c(0:2, 5:7)
time(s)
```

**Comment by rhijmans** [comment]
That works fine for me

````
time(s)
#[1] "2001-01-01" "2001-01-02" "2001-01-03" "2001-01-06" "2001-01-07" "2001-01-08"
````

When raising an issue, please follow the instructions (do not add screenshots; provide information about versions).

**Comment by rhijmans** [comment]
My best guess is that this does not work for you because you have loaded another package with a `time<-` method. 
In that case, you could do:

```
terra::time(s) <- as.Date("2001-01-01") + c(0:2, 5:7)
```
