### ISSUE TITLE
loading a saved SpatExtent object leads to "Object with null pointer"

### ISSUE THREAD

**Issue by Canderson156** [rspatial/terra#161]
I've found that I can't save a SpatExtent object as an RDS. I'd like to save the extent of one raster in one script, and then open it in a different script to crop other rasters to have the same extent. This works fine with sf, but not with the equivalent functions in terra. When the extent object is read in, Rstudio identifies it as "Object with null pointer". Is this a bug? 

```
nc_sf <- st_read(system.file("shape/nc.shp", package="sf"))
nc_terra <- vect(nc_sf)

nc_extent <- extent(nc)
nc_ext <- ext(nc_terra)

saveRDS(nc_extent, "nc_extent.RDS")
saveRDS(nc_ext, "nc_ext.RDS")

test1 <- readRDS("nc_extent.RDS")
test2 <- readRDS("nc_ext.RDS")

> test1
class      : Extent 
xmin       : -84.32385 
xmax       : -75.45698 
ymin       : 33.88199 
ymax       : 36.58965 
> test2
Error in .Call(list(name = "CppField__get", address = <pointer: 0x0>,  : 
  NULL value passed as symbol address
```

Plotting nc_extent, nc_ext, and test1 work fine, while plotting test2 causes R to abort.

**Comment by Rapsodia86** [comment]
Hi, 
I just reproduced your error.
As a work-around you can saveRDS() as a vector:

saveRDS(as.vector(nc_ext), "nc_ext_vector2.RDS")
ext2 <- readRDS("nc_ext_vector2.RDS")
> ext2
    xmin     xmax     ymin     ymax 
-1976816 -1159358  1328199  1765646 
> terra::ext(ext2)
SpatExtent : -1976816.15702724, -1159358.08437276, 1328198.83639081, 1765646.0593 (xmin, xmax, ymin, ymax)


Surely, it would be better to go straight from SpatExtent object to *.RDS

**Comment by rhijmans** [comment]
This is by a direct consequence of the design of the package. The terra R objects (SpatExtent, SpatVector, SpatRaster and friends) are all proxy objects that contain a pointer to a C++ object. The reason for this design is to do as much as possible in C++ for better performance. The downside is that you cannot directly save them to Rds (but you can use writeRaster or writeVector).

However, to save the SpatVector (or SpatRaster) in a Rds, you can use `pack` and then use `vect` after reading it.

```
library(terra)
f <- system.file("shape/nc.shp", package="sf")
nc <- vect(f)
e <- ext(nc)

saveRDS(pack(nc), "test.rds")
v <- vect(readRDS("test.rds"))
```

For consistency, I could add a pack method for `SpatExtent`, but all it would do would be `as.vector`. So you might as well do (as @Rapsodia86  points out)

```
saveRDS(as.vector(e), "test_e.rds")
ee <- ext(readRDS("test_e.rds"))
```

**Comment by rhijmans** [comment]
I added some code such that this now gives an error, rather than a crash. 

```
plot(test2)
#Error in plot(test2) : invalid SpatExtent
```
And I may add some safeguards like that to other methods as well

**Comment by Rapsodia86** [comment]
> I added some code such that this now gives an error, rather than a crash.
> 
> ```
> plot(test2)
> #Error in plot(test2) : invalid SpatExtent
> ```
> 
> And I may add some safeguards like that to other methods as well

Just a friendly suggestion, maybe either in the documentation add an info why is that or in the error itself provide a solution like:
#Error in plot(test2) : invalid SpatExtent, e.g. export as.vector()

**Comment by rhijmans** [comment]
I added a paragraph to `?terra`. Perhaps the more common situation where this will occur is when sessions are saved and reopened (I have never understood why R asks you to do that).

**Comment by rCarto** [comment]
For future reference `pack()` has been renamed to `wrap()` since version 1.2-5. 
https://rspatial.github.io/terra/reference/wrap.html
