### ISSUE TITLE
Non expected output of `distance` between `SpatVector` objects

### ISSUE THREAD

**Issue by LuisLauM** [rspatial/terra#1615]
Hello.

I am having a little problem with the `distance` function. When I apply it on two `SpatVector` objects that have CRS WGS84 (EPSG:4326), the results it returns don't seem to be in meters or km. Maybe I am forgetting some intermediate step, but I don't know which one exactly. I leave my script and the reproducible data:

```
require(terra)

# Read main polygon of Peru
peru <- vect(x = "gadm41_PER.gpkg", 
             layer = "ADM_ADM_0")

# Convert lon/lat coordinates 
read.csv(file = "lonlat_pts.csv") |> 
  
  # Convert to SpatVector object
  vect(crs = "EPSG:4326") |> 
  
  # Calculate distances in meters
  distance(y = peru, unit = "m")
```

When I change the `unit` argument from `m` to `km`, the results are divided by 1000 (logically), but the values are not correct and seem to be affected on a scale of ~105. That is, 1m in the result (of the script) represents ~105m in reality.

Data: 
- lonlat_pts.csv (attached) [lonlat_pts.csv](https://github.com/user-attachments/files/17276056/lonlat_pts.csv)
- gadm41_PER.gpkg (downloaded from [GADM.org](https://geodata.ucdavis.edu/gadm/gadm4.1/gpkg/gadm41_PER.gpkg))

I'm using the latest (Github) version of terra: 1.7.82

**Comment by kadyb** [comment]
This is described in the [docs](https://rspatial.github.io/terra/reference/distance.html):

> If x is a SpatVector: The distance is always expressed in meter, except when the coordinate reference system is longitude/latitude AND one of the SpatVector(s) consists of lines or polygons. In that case the distance is in degrees, and thus not very useful (this will be fixed soon).

**Comment by rhijmans** [comment]
This now works, albeit a bit slowly (I think I will be able to improve that)

```
library(terra)
pts <- read.csv("https://github.com/user-attachments/files/17276056/lonlat_pts.csv") |> vect(crs="+proj=longlat")
peru <- geodata::gadm("Peru", level=0, path=".")
speru <- simplifyGeom(peru, 0.01) # make it faster
d <- distance(pts[1:5], speru, unit="km")
d
#         [,1]
#[1,] 105.1726
#[2,] 322.0423
#[3,] 208.4305
#[4,] 216.7173
#[5,] 223.7899
```
