### ISSUE TITLE
split(SpatVector, SpatVector) problem

### ISSUE THREAD

**Issue by mdsumner** [rspatial/terra#1619]
Here I don't see splitting occuring everywhere expected. 

``` r
library(terra)
#> terra 1.7.78
```

``` r
v <- vect(system.file("ex/lux.shp", package="terra"))[1:5, ]

## split geometries
line <- vect(matrix(c(5.79, 6.22, 5.75, 6.1, 5.8, 
                    50.14, 50.05, 49.88, 49.85, 49.71), ncol=2), "line")
s <- split(v, line)

op <- par(mfrow= n2mfrow(nrow(s)))
for (i in 1:nrow(s)) {plot(line, main = i); plot(s[i, ], add = TRUE)}
par(op)
```

![](https://i.imgur.com/UjHGVu3.png)

<sup>Created on 2024-10-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Panels 5 and 6 show splitting (from the polygon in panel 1). But, should we expect all polygons to be sliced where a line crosses them? And for the inputs to be removed replaced by the parts?

**Comment by rhijmans** [comment]
I do not know why this does not work. With an older terra/geos I get a better result

```
library(terra)
terra 1.7.38
gdal(lib="all")
   gdal    proj    geos
"2.2.3" "4.9.3" "3.6.2"
plot(s, col=rainbow(13))
```

<img width="492" alt="Screenshot" src="https://github.com/user-attachments/assets/8613d936-68d0-4c47-bc37-127bb5121435">

**Comment by rhijmans** [comment]
Reverted to an older version that worked.
