### ISSUE TITLE
Erroneous scaling of values when opening hdf4 files

### ISSUE THREAD

**Issue by nielja** [rspatial/terra#1620]
Opening an hdf4 file with terra and reading in the values of each band adds a scaling factor of 10000 without providing a warning. 

I ran into this issue opening a NASA MODIS file as downloaded from their earth data storage ([Link to sample hdf4 file](https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/MOD13A3.061/MOD13A3.A2022335.h12v09.061.2023006050604/MOD13A3.A2022335.h12v09.061.2023006050604.hdf) note that this requires a free NASA Earth data account to download, I unfortunately did not manage to create any sample hdf4 files for this example).
```
library(terra)

#Load downloaded file
r <- terra::sds('MOD13A3.A2022335.h12v09.061.2023006050604.hdf')

#Convert to SpatRaster
r_rast <- terra::rast(r)

#Look at NDVI data
r_vals <- values(r$MOD13A3.A2022335.h12v09.061.2023006050604$`1 km monthly NDVI`)

#Print head of the data
head(r_vals)
```

This leads to this output: 
 1 km monthly NDVI
[1,]          70140000
[2,]          85000000
[3,]          81190000
[4,]          81290000
[5,]          83610000
[6,]          81910000

However, per NASA documentation, the NDVI values should be in a range of [-2000, 10000] and looking at the same file in the ([HDFView Program](https://www.hdfgroup.org/download-hdfview/) does in fact show these to be the corresponding values:

7014	
8500	
8119	
8129	
8361	
8191

Somehow, opening the file using terra adds this scaling factor. The same issue occurs when just opening the file directly using 
`terra::rast()`

I am using terra version 1.7.55 on Windows.

**Comment by kadyb** [comment]
This product has an incorrectly specified scaling factor, rather it should be 0.0001. You can load the raw data like this:

```r
r <- sds('MOD13A3.A2022335.h12v09.061.2023006050604.hdf', raw = TRUE)
```

See also: https://github.com/rspatial/terra/issues/1354

**Comment by rhijmans** [comment]
I see:

```
f <- "HDF4_EOS:EOS_GRID:\"MOD13A3.A2022335.h12v09.061.2023006050604.hdf\":MOD_Grid_monthly_1km_VI:\"1 km monthly EVI\""
describe(f) |> tail(1)
#[1] "  Offset: 0,   Scale:10000"
```

That explains it.  It is an unfortunate situation, but this suggests that there is an error in the file, as @kadyb pointed out.
