### ISSUE TITLE
Request for r-terra v1.7 for Windows on conda-forge

### ISSUE THREAD

**Issue by katieb1** [rspatial/terra#1621]
The current version of r-terra for windows on conda-forge is 1.5_17 (https://anaconda.org/conda-forge/r-terra). Is it possible to update the version available on conda-forge to 1.7? 

We would like to create conda environment w/ r-base v4.41 and terra v1.7.

Thank you!

**Comment by rhijmans** [comment]
I suppose that is possible, and a good idea since that version is rather old. But this is not something that I am involved in. You should ask that question to the conda people instead.
