### ISSUE TITLE
Error: [writeRaster] source and target filename cannot be the same

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#1622]
In both the CRAN version and development version, I cannot overwrite an existing file if the SpatRaster is linked to that file, even if I subset the SpatRaster so there was a change.

``` r
library(terra)
#> terra 1.7.78
r<- rast(matrix(1:9, nrow=3, ncol=3))
r<- c(r, r*2)
names(r)<- c("lyr.1", "lyr.2")

writeRaster(r, "test.tif")

r<- rast("test.tif")
r<- r[[1]] # subset later
writeRaster(r, "test.tif", overwrite=TRUE) #overwrite with just first layer
#> Error: [writeRaster] source and target filename cannot be the same
```

<sup>Created on 2024-10-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
`writeRaster` needs to read from "test.tif" what needs to be written to "test.tif".  

In principle, this behavior could be changed by reading all values into memory before writing, or, if that is not possible,  by making a copy. But it seems to me that this would more often than not lead to accidentally overwriting a file. 

And you might get a situation like this where `r` would not be valid anymore (the object has two layers, but these are not in the file anymore).  

```
r <- rast("test.tif")
x<- r[[1]] # subset later
writeRaster(x, "test.tif", overwrite=TRUE) 
```

You can create that problem in other ways, of course. I have considered keeping a list of *all* files that are in use, but that seemed overkill,

**Comment by ailich** [comment]
Thanks. Hadn't run into this before so thought it might be a bug. What you describe makes sense, and since this is intended behavior I'll close out this issue. Thanks!
