### ISSUE TITLE
ERROR: Installing Terra fails due to unexpected input

### ISSUE THREAD

**Issue by quinn-r88** [rspatial/terra#1623]
## Issue:

Attempting to install the terra package causes the following error:
```
** R
Error in parse(outFile) : 
  /tmp/RtmpdUYukX/R.INSTALL213476df3aa2/terra/R/plot_let.R:123:42: unexpected input
122:                 
123:                 if (missing(col)) col <- \
                                              ^
ERROR: unable to collate and parse R files for package ‘terra’
```

## To Reproduce:
- Install dependencies
- In an R terminal, type `packages.install('terra')`

My Setup:
- Ubuntu 20.04
- R 3.6.3

**Comment by quinn-r88** [comment]
It seems very likely that this problem was in commit ae5f77, [here](https://github.com/rspatial/terra/commit/ae5f773be604ee251a320270e507ea01ed14f01b#diff-c169628ff16533922f9a58107cd70b72af562b787b40ee4cbc61dfb4ebb857a5R123)

**Comment by rhijmans** [comment]
It should work again on R 3.6.3  (and I would suggest updating R)

**Comment by quinn-r88** [comment]
much appreciated!
