### ISSUE TITLE
Feature Request: Support legend title expressions

### ISSUE THREAD

**Issue by ngoodkind** [rspatial/terra#1626]
Is it possible to add support for expressions in the legend title? As far as I can tell, it is not possible to use `expression` to add a subscript or superscript to the legend title. 

```r
library("terra")
f = system.file("ex/elev.tif", package="terra")
r = rast(f)
plot(
 r, 
 main = expression("My Title"^2), # Works as expected
 plg = list(title = expression("My Title"^2)) # Does not work as expected
)
```

This was also mentioned in #1325, but it didn't seem like a solution was provided.  

Terra version:
``` r
packageVersion("terra")
# [1] ‘1.7.82’
```

gdal version:
```r 
terra::gdal(lib="all")
#    gdal     proj     geos 
# "3.4.1"  "8.2.1" "3.10.2" 
```

Thanks for the package!

**Comment by rhijmans** [comment]
I think this works now. Thanks.
