### ISSUE TITLE
JPG images are flipped when imported with rast()

### ISSUE THREAD

**Issue by rCarto** [rspatial/terra#1627]
Hello, 

This behavior occurs on both CRAN and dev versions. 

``` r
library(terra)
#> terra 1.8.0
library(curl)
#> Using libcurl 7.88.1 with OpenSSL/3.0.14
filename <- tempfile(fileext = ".jpg")
curl_download(url = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/JPG_Test.jpg/477px-JPG_Test.jpg", 
              destfile = filename, quiet = FALSE, mode = "wb")
testjpg <- terra::rast(filename)
#> Warning: [rast] unknown extent
plotRGB(testjpg)
```

![](https://i.imgur.com/gcOyH7g.png)

``` r
terra::gdal(lib="all")
#>     gdal     proj     geos 
#>  "3.6.2"  "9.1.1" "3.11.1"
sessionInfo()
#> R version 4.4.1 (2024-06-14)
#> Platform: x86_64-pc-linux-gnu
#> Running under: Debian GNU/Linux 12 (bookworm)
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.11.0 
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0
#> 
#> locale:
#>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
#>  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
#>  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: Europe/Paris
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] curl_5.2.3  terra_1.8-0
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.37     codetools_0.2-20  fastmap_1.2.0     xfun_0.48        
#>  [5] glue_1.8.0        knitr_1.48        htmltools_0.5.8.1 rmarkdown_2.28   
#>  [9] lifecycle_1.0.4   cli_3.6.3         reprex_2.1.1      withr_3.0.1      
#> [13] compiler_4.4.1    rstudioapi_0.17.0 tools_4.4.1       evaluate_1.0.1   
#> [17] Rcpp_1.0.13       yaml_2.3.10       rlang_1.1.4       fs_1.6.4
```

``` r
library(terra)
#> terra 1.7.78
library(curl)
#> Using libcurl 7.88.1 with OpenSSL/3.0.14
filename <- tempfile(fileext = ".jpg")
curl_download(url = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/JPG_Test.jpg/477px-JPG_Test.jpg", 
              destfile = filename, quiet = FALSE, mode = "wb")
testjpg <- terra::rast(filename)
#> Warning: [rast] unknown extent
plotRGB(testjpg)
```

![](https://i.imgur.com/z2cdh28.png)

``` r
terra::gdal(lib="all")
#>     gdal     proj     geos 
#>  "3.6.2"  "9.1.1" "3.11.1"
sessionInfo()
#> R version 4.4.1 (2024-06-14)
#> Platform: x86_64-pc-linux-gnu
#> Running under: Debian GNU/Linux 12 (bookworm)
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.11.0 
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0
#> 
#> locale:
#>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
#>  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
#>  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: Europe/Paris
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] curl_5.2.3   terra_1.7-78
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.37     codetools_0.2-20  fastmap_1.2.0     xfun_0.48        
#>  [5] glue_1.8.0        knitr_1.48        htmltools_0.5.8.1 rmarkdown_2.28   
#>  [9] lifecycle_1.0.4   cli_3.6.3         reprex_2.1.1      withr_3.0.1      
#> [13] compiler_4.4.1    rstudioapi_0.17.0 tools_4.4.1       evaluate_1.0.1   
#> [17] Rcpp_1.0.13       yaml_2.3.10       rlang_1.1.4       fs_1.6.4
```

<sup>Created on 2024-10-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by kadyb** [comment]
Maybe this is regression from https://github.com/rspatial/terra/commit/049111ecabb9fc4eb7dafe0fdf558ba10160177b (if it worked in terra 1.7.78)?

**Comment by rhijmans** [comment]
Sorry, https://github.com/rspatial/terra/commit/a0c09d9d35e120d5bffeb9fbf4cb2ce16eb3c65c is not related to this issue.

**Comment by aloboa** [comment]
This problem is not exclusive of the jpg format:
Given 
https://www.dropbox.com/scl/fi/qv7gph4sszd48beu43da1/DI17_2.tif?rlkey=1qo1i4p8h2xlx8gv17b6vgdyp&dl=0
![image](https://github.com/user-attachments/assets/c037b961-0060-4e56-96a6-5acbbd3d472c)

```
> library(terra)
terra 1.7.83
```
`plot(rast(file.path(dirdata, "DI17_2.tif")), col=gray.colors(256))`

![image](https://github.com/user-attachments/assets/430c1850-a60b-47da-87a5-ca83d6c299ef)

**Comment by lerouxr-dev** [comment]
I have the same probleme. On my machine (ubuntu), it works well, on a virtual machine (windows and ubuntu) it is fleeped. The only difference is the gdal library version 
`gdal     proj     geos 
 "3.4.1"  "8.2.1" "3.10.2" `

This version works well. 

This one does not :   `gdal     proj     geos 
 "3.9.3"  "9.4.1" "3.12.2"`

**Comment by rhijmans** [comment]
This now works as expected:

```
library(terra)
url <- "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/JPG_Test.jpg/477px-JPG_Test.jpg"
x <- terra::rast(url)
plot(x)
```

This behavior was caused by a fix for a case where flipping was needed. The problem is that these non-georeferenced images really *are* flipped in the way that GDAL returns the coordinates, but I won't correct for that. If need be I can add an option for files where flipping is required. .

**Comment by aloboa** [comment]
I confirm it works, thanks.

> If need be I can add an option for files where flipping is required. .

I think this would be best. Is there any way to check that a given file requires the vertical flip without displaying it?
(eg, some missing or wrong tag in the header).

**Comment by rCarto** [comment]
Hi, 
It seems that jpg are flipped again in current CRAN version. I've added a `flip` arg in `maptiles` downstream (with a default to TRUE for jpg tiles).

**Comment by aloboa** [comment]
> library(terra)
terra 1.8.16
> url <- "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/JPG_Test.jpg/477px-JPG_Test.jpg"
> x <- terra::rast(url)
Warning message:
[rast] unknown extent 
> plot(x)
> crs(x) <- "local"
> plot(x)

![Image](https://github.com/user-attachments/assets/079de315-3b5a-4904-80e2-d7a69379b182)

**Comment by rhijmans** [comment]
I am sorry for breaking this --- I should have (at the minimum) warned you.  

The underlying issue is that GDAL reports the image should be flipped vertically (the lower y coordinate is higher than the upper y coordinate):

```
library(terra)
url <- "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/JPG_Test.jpg/477px-JPG_Test.jpg"
d <- describe(url)
cat(paste(d[9:13], "\n"))
#Corner Coordinates: 
# Upper Left  (    0.0,    0.0) 
# Lower Left  (    0.0,  599.0) 
# Upper Right (  477.0,    0.0) 
# Lower Right (  477.0,  599.0) 
```

I introduced a work-around to ignore this for rasters that were not georeferenced; but that created new issues. So rather then trying to catch these new issues I figured it would make more sense to keep them as-is.  

It is probably not ideal to check for jpg as these files *can* be georeferenced. I have now added `terra::is.flipped` which should be a more robust check, and would also work with other image formats.

```
r <- rast(url)
#Warning message:
#[rast] unknown extent 
is.flipped(r)
#[1] TRUE
```

**Comment by rCarto** [comment]
All right I understand. I'll use `is.flipped()` in next versions. 
Thank you!

**Comment by rhijmans** [comment]
I have another, perhaps better way to deal with this:

When using `rast` with argument "noflip=TRUE" rasters (images) that are not-georeferenced will not be considered to be flipped. Setting that value explicitly should also guard against future changes in the code.

```
library(terra)
#terra 1.8.18
url <- "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/JPG_Test.jpg/477px-JPG_Test.jpg"
r <- rast(url, noflip=TRUE)
plot(r)
``` 

And this also gives expected output for https://github.com/rspatial/terra/issues/1704 where `as.polygons` is used in a subsequent step.

**Comment by rCarto** [comment]
Ok, and the default is "noflip=FALSE" (to keep the current CRAN version behavior)?

**Comment by enatijohnson** [comment]
I am having the same issue, but with a georeferenced TIFF.
is.flipped() returns FALSE, despite it being flipped vertically.
adding the noflip=TRUE argument also does not change anything.

**Comment by rhijmans** [comment]
@enatijohnson can you please start a new issue, and please include an example file.

**Comment by rhijmans** [comment]
You can also start by including what is returned by `terra::describe("your_file.tif")`
