### ISSUE TITLE
Change getBlockSize to be more dynamic based on nlyr

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#163]
I was running into issues with map predictions using many large raster files in the input dataset where my session kept crashing, even when changing `terraOptions(memfrac = 0.1)`. I decided to use the `raster` package to fulfill my map prediction needs, but I wanted to know why `raster` might be working over `terra`. The `raster` package has a nifty function `blockSize()` which can calculate the blocks needed to be loaded into memory during prediction, and I noticed that a similar function in `terra` exists internally, `getBlockSize()`. 

During map prediction in `terra`, the function `writeStart()` is called, which produces the blocks through the internal `getBlockSize()` command. I can't find documentation on this internal command, though it would appear that it takes 2 arguments: n, and memfrac. I am fairly sure that n refers to the `nlyr` of the input SpatRaster object and have documented my evidence for that below. Note that results may differ from machine to machine and based on available system memory (this system has 8GB total memory and ~50% was in use at the time of running this):

```
library(terra)

r <- rast(nrows = 10000, ncols = 10000, nlyr = 10)
mem <- 0.6

# getBlockSize returns list of row start, nrows, and n (number of blocks)
# Extract n from each result
b <- sapply(1:10, function(x) r@ptr$getBlockSize(x, mem)$n)
b
 [1]  4  8 12 16 20 24 28 32 36 39
```

Notice as the value of the fist argument increases, the number of blocks appears to increase in a (more or less) linear fashion. The reason for the discrepancy at the last value appears to be that `terra` performs this calculation based on the current available system memory since I've noticed it change when re-running the same call over and over with slightly different results.

Anyways, the problem is that the [first argument in the `getBlockSize` function is hard coded as 4](https://github.com/rspatial/terra/blob/1d3e95e36cb592dba32cb03c1752c882c70b94f1/R/write.R#L7). For models with a high amount of input variables (e.g.: 30 raster layers), this is not ideal since the number of blocks it is creating will be substantially lower than what it should be:

```
sapply(c(4, 30), function(x) r@ptr$getBlockSize(x, mem)$n)
[1]  16 120
```

In the above case, when I try to perform a model prediction, it will iterate over 16 blocks of data when in reality I would likely need 120 blocks to make sure that there is enough memory available to perform the raster predictions. Interestingly, when I try to do a similar function in `raster`, the number of blocks that are returned are approximately double that from what is reported in `terra`:

```
library(raster)

r2 <- brick(nrows = 10000, ncols = 10000, nl = 10)
b2 <- b2 <- sapply(1:10, function(x) blockSize(r2, n = x)$n)
b2
 [1]  8 16 25 33 40 49 57 65 73 80
```

I suspect that this might have something to do with the raster options `chunksize` and/or `maxmemory`, which don't appear in `terraOptions`. At any rate, when doing map predictions using the `raster` package and the same input rasters, I did not experience my R session crashing - it ran perfectly, compared to using the `terra` package predict function for the exact same model and raster data. I noticed that in `raster`, the `n` argument for the `blockSize()` function is based on the [number of layers in the input dataset increased by 3](https://github.com/rspatial/raster/blob/94cbd005703133764c92fa6a8d4dc04824e8822a/R/predict.R#L99), so that is where I got the idea in the first place to check what was going on in terra. I don't know for sure that what I've outlined is something that could solve the issues for larger datasets, it's just what I experienced and I thought that I should try documenting it and providing some sort of starting point if it is a real problem. Let me know if you need more clarification on anything here as well, I'm happy to assist if possible!

**Comment by rhijmans** [comment]
I think you hit it on the nail. In most cases, `nlyr()` of the input is the same as of the output so either can be used. But with `predict` you many input layers and only a single output layer so the former (or in general, the max or sum) should be used. I changed that, and I suspect that it now works as expected. By the way, to look at memory needs, there is also the (currently hidden function) `terra:::.mem_info()` that takes a SpatRaster as first argument.

**Comment by mcoghill** [comment]
Thank you so much for the provided fix @rhijmans! Map predictions with many large input rasters are now working as expected when using the development version of `terra`. 

You're welcome, I wanted to be sure to point you in the right direction and not just have an issue stating "terra predictions are not working, but raster predictions are". It may have been a long winded description but hopefully it made your life easier!
