### ISSUE TITLE
Request: modify patches() to output clumps of cells wth the same value

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#1632]
It would be helpful if the output of patches() were clumps of cells with the same value, regardless
the neighbors are NA or not.

input:
55555555555
55555555555
55444554455
55444554445
54444454455
55555555555
output
11111111111
11111111111
11222113311
11222113331
12222213311
11111111111

(see end of https://github.com/rspatial/terra/issues/576)

The desired output can be (inefficiently) obtained by running the current patches() within a loop for all unique(values(input)).

**Comment by aloboa** [comment]
> Same as #495?

Yes, and it is very similar to #576 too. I opened a new one to make a more appropriate title and specify it as a Feature request, not a bug.

**Comment by rhijmans** [comment]
You can now use argument `values=TRUE` for that. 

```
library(terra)
#terra 1.8.2
v <- matrix(c(5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,5,5,4,4,5,5,5,5,4,4,4,5,5,4,4,4,5,5,4,4,4,4,4,5,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5), nrow=6, byrow=TRUE)
r <- rast(v)

x <- patches(r, values=TRUE)
plot(x); text(x, halo=TRUE)
```
![patch](https://github.com/user-attachments/assets/b1797f3d-0890-4cd4-b31e-01367e336dce)

**Comment by aloboa** [comment]
I confirm it works, thanks!
