### ISSUE TITLE
Problem installing via CRAN on MacOS platforms

### ISSUE THREAD

**Issue by Breeze-Hu** [rspatial/terra#1635]
Dear Robert Hijmans,

There have been problem installing version 1.7-83 on CRAN (MacOS).
I wonder if there are plans to fix this recently?

Best wishes,
Hu

**Comment by rhijmans** [comment]
Thank you, I had not seen that. The changes I just made may fix this. 
For now, you may be able to install from the R-Universe like this

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
```

**Comment by Breeze-Hu** [comment]
Okay, thank you very much！

**Comment by kadyb** [comment]
I wonder why it hasn't come out in [CI](https://github.com/rspatial/terra/actions/workflows/rcmdcheck.yml)? Because CRAN uses an older version of the compiler (`Apple clang version 14.0.3`)?

**Comment by rhijmans** [comment]
I do not know why the CRAN compiler has this problem.
