### ISSUE TITLE
'warn' parameter not used in write_part() routine

### ISSUE THREAD

**Issue by MichaelChirico** [rspatial/terra#1637]
https://github.com/rspatial/terra/blob/001bdfb526abdfe3e2355c63b8c1c821dde5a513/src/raster_methods.cpp#L3470

This is flagged by `clang`'s `-Wunused-but-set-parameter`. Reading the implementation the warning looks good -- the routine takes `warn` as an input but doesn't use it.

Should a warning be thrown somewhere if it winds up `true`? Or perhaps it should be dropped.

I'm happy to file a PR but lack context on what's the right fix.

**Comment by rhijmans** [comment]
Fixed with https://github.com/rspatial/terra/issues/1634
