### ISSUE TITLE
Issue to update from 1.7-78 to 1.7-83

### ISSUE THREAD

**Issue by geamaro** [rspatial/terra#1639]
CRAN update to version 1.7-83 downloads version 1.7-78 and does not updateWhich would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: terra (1.7-78 -> 1.7-83) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 4
terra (1.7-78 -> 1.7-83) [CRAN]
Installing 1 packages: terra
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.4/terra_1.7-78.tgz'
Content type 'application/x-gzip' length 97585776 bytes (93.1 MB)
==================================================
downloaded 93.1 MB

**Comment by rhijmans** [comment]
Same as https://github.com/rspatial/terra/issues/1635
