### ISSUE TITLE
ncols parameter of values() ignored

### ISSUE THREAD

**Issue by GreatEmerald** [rspatial/terra#1640]
In terra version 1.7.78, replacing raster values using a matrix does not work because the package expects a "flattened" matrix. Trivial reprex showing failure when replacing values using the matrix the SpatRaster was created with:

``` r
library(terra)
#> terra 1.7.78
m <- matrix(1:25, nrow=5, ncol=5)
rm <- rast(m)
rm[] <- m
#> Error: [`[`] dimensions of the matrix do not match the SpatRaster
```

<sup>Created on 2024-11-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

This apparently happens because:

``` r
> dim(m)
[1] 5 5
> dim(rm[])
[1] 25  1
dim(values(rm))
[1] 25  1
```

And the same goes even if explicitly using `values(rm, ncols=5)`, it's still flattened.

Library versions:

```r
> terra::gdal(lib="all")
    gdal     proj     geos 
 "3.8.4"  "9.4.0" "3.12.1" 
```

**Comment by rhijmans** [comment]
It was possible to do 

```
values(rm) <- m
```

But now you can also do 

```
rm[] <- m
```

**Comment by GreatEmerald** [comment]
Thanks! Reading `?values` closer, I see the output is meant to be one column per layer, with the x/y flattened. Getting the values as a matrix works as expected this way:
```r
> as.matrix(rm, wide=TRUE)
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
```
