### ISSUE TITLE
Can't find gdal-config during installation

### ISSUE THREAD

**Issue by davidelahoz** [rspatial/terra#1647]
When trying to install terra on a Rstudio server running on ubuntu server, the following message is shown, impeding this package installation:

```
* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++17
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/home/operador/R/x86_64-pc-linux-gnu-library/4.3/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
```

I have GDAL 3.8.4 installed on that server

Does this package require a specific version of GDAL to work?

**Comment by rhijmans** [comment]
@rsbivand, does the above suggestion make sense to you? If so, would you change, in the sf script that I use as the master, the message "gdal-config not found or not executable." to something like "gdal-config not found or not executable (did you install libgdal-dev?)."?

**Comment by rsbivand** [comment]
It is only `libgdal-dev` on debian/ubuntu, we'd need a longer list in general. It gets messy when Windows or macOS users stumble into source installs. I'll try to think of something concise.
