### ISSUE TITLE
SpatRaster::compare_geom() extent, size, resolution, layer, and CRS errors and warnings are uniformative

### ISSUE THREAD

**Issue by twest820** [rspatial/terra#1648]
For example, the [current CRS reporting](https://github.com/rspatial/terra/blob/162c51b3bf69412622ea0e147962c2db929b16ba/src/spatBase.cpp#L491) is just
```
			if (warncrs) {
				addWarning("CRS do not match");
			} else {
				setError("CRS do not match");
				return false;
			}
```
A more user actionable approach would say which layers don't match and report how they're mismatched. It's not like it's hard to go through terra calls like
```
c(raster1, raster2, raster3, raster4, raster5, raster6, raster7)
```
and find the mismatches. But, for example, checking all parts of the proj strings gets tedious, particularly in situations like catching an upstream bug missing a horizontal reprojection from EPSG n to n + 1 when all of the layers have compound CRSes. It's a one character mismatch somewhere in 40+ kB of text.

`compare_geom()`'s signature would benefit form changes to flow calling context into user visible messages but trivial mitigations are also possible. Such as
```
setError("Number of layers does not match. Layer counts are " + nlyr() + " and " + x.nlyr() + ".");
```
instead of the current
```
setError("number of layers does not match");
```
(Also might be good to clarify the `tol` argument's naming. It's used only for extent with cell size having a separate, hard coded tolerance.)

**Comment by rhijmans** [comment]
Thanks. I have made the nlyr related message more informative. The CRS differences can be very messy, but there is not a whole lot more that I can do about that. In most cases that would lead to a warning.
