### ISSUE TITLE
Any suggestions for running gridDist in parallel?

### ISSUE THREAD

**Issue by simkessy** [rspatial/terra#1653]
Hi, 

I'm trying to see if there's any suggestions on how to improve the performance of my script when using gridDist. Currently I'm looping over a data frame, creating a raster, calculating distance and extracting the result. It's very slow and i'm wondering how I could make this faster? 

```r
# Calculate distances along waterways between origin point and potential matching locations
if(nrow(matching_points) > 0){
 distance_mask <- base_mask
 origin_position <- cellFromXY(distance_mask, origin_coords)
 distance_mask[origin_position] <- 500  # Mark origin with unique value (500) for distance calculation
 
 # Use terra::gridDist() to find actual water-route distances rather than straight-line distances
 distance_grid <- gridDist(distance_mask, target = 500, scale=1000) # Result in kilometers  
 matching_points$path_distance <- extract(distance_grid, matching_points[,c('x','y')])$water_mask
```

**Comment by rhijmans** [comment]
The "gDistance" package might be a better match for what you want.

**Comment by simkessy** [comment]
@rhijmans is there a reason for the suggestion, is gdistance much faster or does gdist not work well in parallel? Just trying to get some more context. Thank you.
