### ISSUE TITLE
`compareGeom` doesn't seem to work for SpatVectors

### ISSUE THREAD

**Issue by jflowernet** [rspatial/terra#1654]
According to the documentation `compareGeom` should work for comparing two SpatVectors and comparing a single SpatVector with itself which should check for duplicate geometries. Neither of these options seem to work unless I'm missing something:

``` r
library(terra)
#> terra 1.7.83

v <- vect(rbind(c(10,10), c(0,60)), crs="+proj=merc")

v_dupes <- vect(rbind(c(10,10), c(0,60), c(0,60)), crs="+proj=merc")

compareGeom(v, v)
#> Error: could not find valid method

compareGeom(v_dupes)
#> Error: unable to find an inherited method for function 'compareGeom' for signature 'x = "SpatVector", y = "missing"'

gdal(lib = "all")
#>     gdal     proj     geos 
#>  "3.4.1"  "8.2.1" "3.10.2"
```

<sup>Created on 2024-11-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I'll also note that the documentation title for `compareGeom` is "Compare geometries of SpatRasters". Assuming it is meant to work for SpatVectors, "Compare geometries" might be a better title!

As ever, many thanks for creating `terra`

**Comment by rhijmans** [comment]
Thanks! I think this is fixed now...

**Comment by jflowernet** [comment]
I can confirm it works with the development version of `terra`. Many thanks for the quick fix.

``` r
library(terra)
#> terra 1.8.3

v <- vect(rbind(c(10,10), c(0,60)), crs="+proj=merc")

v_dupes <- vect(rbind(c(10,10), c(0,60), c(0,60)), crs="+proj=merc")

compareGeom(v, v)
#>       [,1]  [,2]
#> [1,]  TRUE FALSE
#> [2,] FALSE  TRUE

compareGeom(v_dupes)
#>       [,1]  [,2]  [,3]
#> [1,]  TRUE FALSE FALSE
#> [2,] FALSE  TRUE  TRUE
#> [3,] FALSE  TRUE  TRUE
```

<sup>Created on 2024-11-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
