### ISSUE TITLE
transparency does not seem to work in plot() 

### ISSUE THREAD

**Issue by rCarto** [rspatial/terra#1655]
I'm not sure but this may be related to #1642.

On the current dev version: 
``` r
library(terra)
#> terra 1.8.3
packageVersion("terra")
#> [1] '1.8.3'
terra::gdal(lib="all")
#>     gdal     proj     geos 
#>  "3.6.2"  "9.1.1" "3.11.1"
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
plot(r, alpha = .5)
```

![](https://i.imgur.com/PhMvLtB.png)

On the CRAN version: 
``` r
library(terra)
#> terra 1.7.83
packageVersion("terra")
#> [1] '1.7.83'
terra::gdal(lib="all")
#>     gdal     proj     geos 
#>  "3.6.2"  "9.1.1" "3.11.1"
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
plot(r, alpha = .5)
```

![](https://i.imgur.com/AGdsIMH.png)

<sup>Created on 2024-11-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Thank you very much for catching that. This was introduced when improving the plotting speed if colors are specified as names: 
https://gis.stackexchange.com/questions/487112/plotting-discrete-categorical-rasters-with-custom-colors-slows-down-r-terra/488012#488012

**Comment by rCarto** [comment]
Thank you for working on this. 
I'm not sure this is intended, but transparency is removed from hex colors using transparency :
CRAN version:
``` r
library("terra")
#> terra 1.7.83
elev <- rast(system.file("ex/elev.tif", package = "terra"))
# transparency from alpha
plot(elev, type = "interval", breaks = 4, 
     col = hcl.colors(4, "Reds 2"), 
     alpha = .5)
```

![](https://i.imgur.com/Kp0zmwg.png)

``` r
# transparency from input palette
plot(elev, type = "interval", breaks = 4, 
     col = hcl.colors(4, "Reds 2", alpha = .5))
```

![](https://i.imgur.com/39PU1GZ.png)

``` r
# using both, alpha is used. 
plot(elev, type = "interval", breaks = 4, 
     col = hcl.colors(4, "Reds 2", alpha = .5), 
     alpha = .1)
```

![](https://i.imgur.com/a9XB15a.png)

Current dev
``` r
library("terra")
#> terra 1.8.3
elev <- rast(system.file("ex/elev.tif", package = "terra"))
# transparency from alpha
plot(elev, type = "interval", breaks = 4, 
     col = hcl.colors(4, "Reds 2"), 
     alpha = .5)
```

![](https://i.imgur.com/RlQn7ac.png)

``` r
# transparency from input palette
plot(elev, type = "interval", breaks = 4, 
     col = hcl.colors(4, "Reds 2", alpha = .5))
```

![](https://i.imgur.com/X6XvtYt.png)

**Comment by rhijmans** [comment]
Thanks again, for another good catch.
