### ISSUE TITLE
Feature Request: Progress bar for `writeCDF`

### ISSUE THREAD

**Issue by ErikKusch** [rspatial/terra#1658]
Saving large SpatRaster objects to disk takes a long time. Even more so when using the Compression argument in `writeCDF`.  In keeping with the progress bars in other `terra` functions, would it be possible to enable saving .nc files with a progress bar?

Alternatively, is there a way to write individual layers to disk appending them to the same file? In that case, I can build my own progress bar as I loop over files.

**Comment by rhijmans** [comment]
Thanks, I have implemented the progress bar.

**Comment by ErikKusch** [comment]
Amazing! Thanks for taking this on board. While on the topic of progress bars, I have already put together [my own custom function for NeCDF file saving](https://github.com/ErikKusch/ClimHub/blob/master/R/WriteRead.NC.r), but will probably pivot back to using `terra` contained functionality to reduce maintenance hassles on my end. 

I am using progress bars as provided by the `progress` package. Personally, I think the estimator of time remaining is incredibly useful for end-users. I was wondering if you might consider switching to more informative progress bars like those at some point?
