### ISSUE TITLE
Point to `expanse()` if SpatVector is used

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#1663]
Can we somehow redirect users if they want to calculate area of polygons? I think in 99% of the different GIS software, the method to calculate the area of the geometry is called `area`, but in terra it is `expanse()`, which can make it unintuitive.

```r
library("terra")
v <- vect(system.file("ex/lux.shp", package="terra"))
area(v)
#> Error: unable to find an inherited method for function ‘area’ for signature ‘x = "SpatVector"’
```

Maybe we can improve it in these two files?

1. https://github.com/rspatial/terra/blob/master/R/Zdeprecated.R
2. https://github.com/rspatial/terra/blob/master/man/deprecated.Rd

Another issue is the name of the function to calculate length and perimeter. For example, in sf there are two separate functions named `st_length()` and `st_perimeter()`. However, in terra it is one function -- `perim()`. Maybe it would be a good idea to unify this in the future (if it doesn't cause more confusion)?

**Comment by rhijmans** [comment]
with this: https://github.com/rspatial/terra/commit/ce61b917e629cd1a8e4b0f95d73bd91691438e82

`?area` brings you to the manual entry for `expanse` and:

```
library("terra")
#terra 1.8.3
v <- vect(system.file("ex/lux.shp", package="terra"))
area(v)
#Error: [area] this method was removed. Use 'expanse'
``` 

I agree that using `perim` for length is not great. The problem is that `length` already refers to the length of the object in R. I could add something like `geom_length`

**Comment by rhijmans** [comment]
And to clarify: at some point I changes the names of methods that clashed with names in tidyverse. `area` also conflicted with a method with the same name in spatstat

**Comment by kadyb** [comment]
Ah, right. I hadn't thought about name conflicts with other functions. Thanks!
