### ISSUE TITLE
minor bug in plot() with plg: title.cex replaces title if latter missing

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1664]
```
library(terra)
r <- rast(system.file("ex/elev.tif", package="terra"))
plot(r, plg = list(title = "Elevation", title.cex = 1.5, lwd = 0.2, size = 1))
```
<img src="https://github.com/user-attachments/assets/0df7c87a-4ecf-4825-9dab-64f671e12776" width=20% height=20%>

However, if from `plg` I remove the `title` but forget to remove `title.cex`, the `title.cex` becomes the title:

```
plot(r, plg = list(title.cex = 1.5, lwd = 0.2, size = 1))
```
<img src="https://github.com/user-attachments/assets/f8e0f51a-9c60-40e8-bd13-6cf479057725" width=20% height=20%>

Regards!

**Comment by rhijmans** [comment]
Thanks! Fixed.
