### ISSUE TITLE
plot() 'col' default different for raster and vector (and not documented)

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1670]
The `?terra::plot` help file says that the default `col` is `map.pal("viridis", 100)`, but this seems to be true only for SpatRaster maps. Is this intentional, or should the default be made the same for SpatVector maps?

`plot(rast(system.file("ex/elev.tif", package="terra")))`

<img src="https://github.com/user-attachments/assets/46ef4b04-2964-4414-9e24-2c1ee045b2a7" width=20% height=20%>

plot(vect(system.file("ex/lux.shp", package="terra")), "AREA")

<img src="https://github.com/user-attachments/assets/9c50d51a-aa38-41fd-bf59-37f3d85d4433" width=20% height=20%>

**Comment by rhijmans** [comment]
Thank you. `plot<vector>` now also uses "viridis"
