### ISSUE TITLE
segfault of expanse(transform=TRUE) on patches(values=TRUE) output

### ISSUE THREAD

**Issue by MichaelChirico** [rspatial/terra#1671]
I am excited for the new `values=` argument to `patches()`!

Unfortunately I quickly caused a segfault while trying to find the areas of each region it produces. Using the example from #1632:

https://github.com/rspatial/terra/issues/1632#issuecomment-2495728774

```r
library(terra)
v <- matrix(c(5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,5,5,4,4,5,5,5,5,4,4,4,5,5,4,4,4,5,5,4,4,4,4,4,5,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5), nrow=6, byrow=TRUE)
r <- rast(v, crs="local")

x <- patches(r, values=TRUE)
expanse(x) # I was trying byValue=TRUE
# crash
```

Looks like I made a mistake -- I should use `transform=FALSE` given `crs="local"`. But a segfault looks bad!

**Comment by rhijmans** [comment]
Thanks for reporting this. We sure don't like segfaults. I now get:

```
expanse(x)
#  layer area
#1     1   66
 
expanse(x, byValue=TRUE)
#  layer value area
#1     1     1   48
#2     1     2   11
#3     1     3    7
```
