### ISSUE TITLE
Is relation `equals` missing in `relate()`?

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#1672]
I wonder if `equals` relation is missing in `relate()` function? To check if two geometries are identical, we currently have to extract them as WKT/WKB and compare them using `==` or `identical()`?

> relation -- character. One of "intersects", "touches", "crosses", "overlaps", "within", "contains", "covers", "coveredby", "disjoint". Or a "DE-9IM" string such as "FF*FF****".

**Comment by rhijmans** [comment]
You can use `compareGeom(x, y)`

```
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)

compareGeom(v[1:3])
#      [,1]  [,2]  [,3]
#[1,]  TRUE FALSE FALSE
#[2,] FALSE  TRUE FALSE
#[3,] FALSE FALSE  TRUE

compareGeom(v[1:2], v[2:1])
#      [,1]  [,2]
#[1,] FALSE  TRUE
#[2,]  TRUE FALSE
```

**Comment by kadyb** [comment]
Ok, I think we should add this information to the `relate()` doc (#1678).

**Comment by rhijmans** [comment]
And "equals" was indeed missing, and I have added it now (https://github.com/rspatial/terra/pull/1678)

**Comment by kadyb** [comment]
Great, thank you!
