### ISSUE TITLE
Add datatype documentation to terra

### ISSUE THREAD

**Issue by tylerhoecker** [rspatial/terra#1673]
I frequently refer to the documentation about allowed datatypes, the values the represent, and the strings that should be used to define them in `terra`. 

I noticed that this comprehensive version of the documentation is only associated with [`raster::dataType`](https://search.r-project.org/CRAN/refmans/raster/html/dataType.html) and the [`terra::datatype`](https://rdrr.io/cran/terra/man/datatype.html) documentation lacks these useful details. Suggest including them in the `terra` docs too.

**Comment by rhijmans** [comment]
Thank you for the helpful suggestion.

**Comment by tylerhoecker** [comment]
Thanks Robert!
