### ISSUE TITLE
feature request: haversine distance for SpatVectors

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1677]
Hi,
`distance()` has arguments for faster computation, like `haversine` and `rasterize`, but these are only implemented for SpatRasters. They would be very useful for SpatVectors too, e.g. for computing pairwise distances among numerous points. Maybe import/implement the `measure` options available in `geodist::geodist`?
Cheers!

**Comment by rhijmans** [comment]
The distance methods now have a new argument "method=" that can be set to "geo", "haversine" and "cosine"
