### ISSUE TITLE
as.data.frame not incorporating XY coordinates

### ISSUE THREAD

**Issue by francisvolh** [rspatial/terra#1679]
Hello, I have been trying to use terra::as.data.frame and as per the documentation xy = TRUE should include the coordinate, but this is not happening for me.

```
f <- system.file("ex/lux.shp", package="terra")

v <- terra::vect(f)

terra::as.data.frame(v, xy = TRUE)

```
what I have been doing is calling `terra::crds()` and binding it with terra::as.data.frame(). But I think this is to much trouble if xy = TRUE should be working. Unless I am doing something wrong?

Thanks for any comment you have may have. 

```
> packageVersion("terra")
[1] ‘1.7.83’
```

**Comment by Rapsodia86** [comment]
In the documentation (https://rdrr.io/cran/terra/man/as.data.frame.html)
`xy` is for rasters: `logical. If TRUE, the coordinates of each raster cell are included`

For SpatVector, there is `geom`: `character or NULL. If not NULL, either "WKT" or "HEX", to get the geometry included in Well-Known-Text or hexadecimal notation. If x has point geometry, it can also be "XY" to add the coordinates of each point`

**Comment by francisvolh** [comment]
Thanks, but I just tried 
```
f <- system.file("ex/lux.shp", package="terra")
v <- terra::vect(f)
terra::as.data.frame(v, geom = "WKT")
```
or
`terra::as.data.frame(v, geom = "HEX")`

And it surely does not produce the desired output. 


The documentation does say "if x has point geometry, it can also be "XY" to add the coordinates of each point", that you clearly pointed out. And a SpatVector is point geometry, correct?  so is if this XY is not  the parameter xy, I think its a bit misleading also. 

The xy parameter does say "coordinates of each raster cell" but I think is not super clear that is ONLY for raster, and maybe an "error" or warning may be better.

**Comment by Rapsodia86** [comment]
Try updating the package.
```
> library(terra)
terra 1.8.5
Warning message:
package ‘terra’ was built under R version 4.4.2 
> f <- system.file("ex/lux.shp", package="terra")
> v <- terra::vect(f)
> vv <- terra::as.data.frame(v, geom = "WKT")
```
![image](https://github.com/user-attachments/assets/66e26003-c094-4e49-83d0-9c89a91f2c8a)

If you put geom="XY" it gives an error, since that is not point geometry: 
```
> vv <- terra::as.data.frame(v, geom = "XY")
Error: [as.data.frame] geom="XY" is only valid for point geometries
```
![image](https://github.com/user-attachments/assets/c3bcf757-1825-409b-8116-5291bde5a14f)

**Comment by francisvolh** [comment]
Thanks for pointing that out. Sorry for the troubles!
