### ISSUE TITLE
Subsetting in terra as in raster?

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#168]
Given 3 rast objects of 1 band, rc, rw and rs,
in raster I can do
rc[rw==2] <- rs[rw==2]
but this is an error in terra,
how would be the correct syntax in terra for the same operation?

**Comment by rhijmans** [comment]
Example for `raster`

```
library(raster)
x <- y <- z <- raster(nrow=2, ncol=2)
values(x) <- c(1,1,2,2)
values(y) <- c(1,2,1,2)
values(z) <- 10
i <- y == 2
x[i] <- z[i]
```

Example for terra

```
library(terra)
xx <- yy <- zz <- rast(nrow=2, ncol=2)
values(xx) <- c(1,1,2,2)
values(yy) <- c(1,2,1,2)
values(zz) <- 10
```

This fails, because using a `SpatRaster` as index has not been implemented --- I will add that.

```
ii <- yy == 2
xx[ii] <- zz[ii]
```

But either way, the below works, and I think it is more elegant

`rr <- ifel(yy == 2, zz, xx)
`

```

**Comment by aloboa** [comment]
Thanks. Either way, I'm just used to the indexing way.

**Comment by rhijmans** [comment]
This works now. Te reason why it failed is that `zz[ii]` returns a `data.frame`. In the equivalent `raster` code you get a vector. The reason for returning a `data.frame` is that it can return numbers but also factor/character values if they are associated with the SpatRaster.

```
ii <- yy == 2
class(zz[ii])
# [1] "data.frame"

zz[ii]
#  lyr.1
#1    10
#2    10
``` 
So there is also this workaround 

```
ii <- yy == 2
xx[ii] <- unlist(zz[ii])
```

**Comment by aloboa** [comment]
understood
