### ISSUE TITLE
Feature request: as.data.frame applied to multi-level rasters

### ISSUE THREAD

**Issue by Breeze-Hu** [rspatial/terra#1680]
Dear Robert Hijmans,

I am currently using the `as.data.frame` function to connect raster data to a ggplot `geom_tile` plot, but it seems to only work with a single layer of data?
Can the `as.data.frame` function work with multi-layered raster data by adding a column (e.g. name? class? ) in addition to the `x` and `y` columns to categorize the layer the data is in?

Best regards,
Hu

**Comment by rhijmans** [comment]
Apparently you did not try it? Either way, plotting Spat* objects with ggplot is easy with the "tidyterra" package.

**Comment by Breeze-Hu** [comment]
Sorry about that, after trying this one did basically achieve the desired result. I'll follow up on your suggestion to try using `tidyterra` for plotting. Thank you for your suggestion!
But I'm now running into a problem:
```
library(terra)

m <- matrix(1:25, nrow=5, ncol=5)
rm <- rast(m)
n <- matrix(rep(5,time=25),nrow = 5,ncol = 5)
rn <- rast(n)

dt <- c(rm,rn)
data <- terra::as.data.frame(dt,xy=TRUE)
head(data)
```
```
> head(data)
    x   y lyr.1 lyr.1
1 0.5 4.5     1     5
2 1.5 4.5     6     5
3 2.5 4.5    11     5
4 3.5 4.5    16     5
5 4.5 4.5    21     5
6 0.5 3.5     2     5
```

After merging the two raster data here, the names of the layers are both `lyr.1`. Is it possible to bring the original names into the layers (in the example: `rm` and `rn`)?

Best regards,
Hu
