### ISSUE TITLE
crop(x = SpatRaster, y = SpatVector, mask = TRUE) failing after 1.8 update.

### ISSUE THREAD

**Issue by edixon1** [rspatial/terra#1686]
I was unable to reproduce this issue with the terra example data sets, so I've used public data:

1. [North Carolina County Boundaries](https://www.nconemap.gov/datasets/NCDOT::ncdot-county-boundaries/about)
2. [MRLC's NLCD](https://s3-us-west-2.amazonaws.com/mrlc/nlcd_2021_land_cover_l48_20230630.zip)

The following code works as expected when using terra 1.7-83, but throws the following error on terra 1.8-5: 

```
library(terra)
nlcd <- terra::rast("nlcd_2021_land_cover_l48_20230630.img")
counties <- vect("NCDOT_County_Boundaries.shp") |>  project(nlcd)
nlcd <- crop(nlcd, counties, mask = TRUE, steps=5)

# Error: [crop] mask raster has no values
```

OS: Windows 11, Build 26100.2605

`packageVersion("terra")` Output: '1.8.5'

`terra::gdal(lib="all")` Output: gdal 3.9.3, proj 9.4.1, geos 3.12.2

**Comment by rhijmans** [comment]
Thank you, I think this fixes it.

**Comment by edixon1** [comment]
Thanks very much!

**Comment by cwader** [comment]
What was the fix?

**Comment by rhijmans** [comment]
See above: completed in https://github.com/rspatial/terra/commit/9796b5f87942a68013e5b8aaaa00c3122166039c

**Comment by kadyb** [comment]
@cwader, you need to install the devel version of `terra`. On Windows or macOS you can do in this way:

```r
install.packages("terra", repos = "https://rspatial.r-universe.dev")
```

Later, a new version of `terra` with this fix will be published on CRAN.

**Comment by tgelmi-candusso** [comment]
still having this issue
