### ISSUE TITLE
Getting error while using crop function, error:[path] does not exist 

### ISSUE THREAD

**Issue by SHIVAM2607** [rspatial/terra#1687]
I have one spatraster and using crop function to crop it with below command
ras2=crop(ras,ext(c(xmin,xmax,ymin,ymax))
But getting error [crop]:path does not exist, I am using linux machine, please suggest if any other information is needed from my end

**Comment by rhijmans** [comment]
The instructions state what is required for a new issue. I would like to help or fix things, but there is nothing I can do with the scant information that you have provided.

**Comment by SHIVAM2607** [comment]
In my raster extent is -180,180,-59,85 , but in extent which is I am using has -170,120,-59,85 and causing issue while when I am providing -182,120,-59,85 its working not sure why its accepting this value
