### ISSUE TITLE
terra::cells() weights don't seem to return what would be expected

### ISSUE THREAD

**Issue by ptitle** [rspatial/terra#169]
In the cells() function, the documentation says that, if y has polygons, then weights = TRUE should lead to "the fraction of each cell that is covered is returned as well"

However, if I try this, the weights column returns values that don't look like fractions. They can be greater than 1, and even greater than 100, whereas I would have expected either values between 0 and 1, or percents. 
```
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
r <- rast(v)
cv <- cells(r, v, weights = TRUE) 
head(cv)
     id cell weights
[1,]  1   33    7.65
[2,]  1   34   45.90
[3,]  1   35   63.75
[4,]  1   36   96.90
[5,]  1   37  153.00
[6,]  1   38  209.10
```
Am I just misunderstanding, or is there an issue here?
thanks!

**Comment by rhijmans** [comment]
Are you using an older version? I get:

```
head(cv)
#     id cell weights
#[1,]  1   33    0.03
#[2,]  1   34    0.18
#[3,]  1   35    0.25
#[4,]  1   36    0.38
#[5,]  1   37    0.60
#[6,]  1   38    0.82
```

**Comment by ptitle** [comment]
Ok, looks like I had a slightly outdated version, so I updated to the latest version on CRAN. Now:

```
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.1-4

loaded via a namespace (and not attached):
[1] compiler_4.0.4   sp_1.4-5         Rcpp_1.0.6       raster_3.4-5    
[5] codetools_0.2-18 grid_4.0.4       lattice_0.20-41 
```

However, I still get the following:
```
> library(terra)
terra version 1.1.4
> f <- system.file("ex/lux.shp", package="terra")
> v <- vect(f)
> r <- rast(v)
> cv <- cells(r, v, weights = TRUE) 
There were 12 warnings (use warnings() to see them)
> head(cv)
     id cell weights
[1,]  1   33    7.65
[2,]  1   34   45.90
[3,]  1   35   63.75
[4,]  1   36   96.90
[5,]  1   37  153.00
[6,]  1   38  209.10
```

Also, not sure what these warnings are about (might not be directly terra related):
```
> warnings()
Warning messages:
1: Too many command options '7≠A' (GDAL error 6)
2: Too many command options '~≠A' (GDAL error 6)
3: Too many command options '≠A' (GDAL error 6)
4: Too many command options '†¨A' (GDAL error 6)
5: Too many command options '§¨A' (GDAL error 6)
6: Too many command options '?≠A' (GDAL error 6)
7: Too many command options '¶¨A' (GDAL error 6)
8: Too many command options '§¨A' (GDAL error 6)
9: Too many command options 'û¨A' (GDAL error 6)
10: Too many command options 'H§A' (GDAL error 6)
11: Too many command options '<≠A' (GDAL error 6)
12: Too many command options '<≠A' (GDAL error 6)
```

**Comment by ptitle** [comment]
Still the same with the version installed directly from github.

**Comment by rhijmans** [comment]
It all works for me with the same OSX (and on others). The warnings seems to point to the problem. That is, GDAL is uses for this, but some of the arguments passed to it are not recognized. What is your gdal version --- as returned by  `terra::gdal()` ?

**Comment by ptitle** [comment]
I get 
```
> terra::gdal()
[1] "3.2.1"
```

**Comment by rhijmans** [comment]
Did you install GDAL via homebrew, or in some other way? Sorry for all the questions, but it would be great to get to the bottom of the mystery.

**Comment by ptitle** [comment]
Oh I'm happy to provide details and figure this out!
I do have gdal installed via homebrew, and gdal-config is found at /usr/local/bin/gdal-config
Homebrew tells me that is version 3.2.1.

**Comment by ptitle** [comment]
Although, if I load the sf package, it says `Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1`, which indicates a different version of GDAL.

**Comment by rhijmans** [comment]
Thanks Pascal. I can now reproduce this by installing from CRAN --- in which case  I also get GDAL 3.1.4  --- that makes sense, the same as for `sf` but not as for your version of `terra` as you compiled it yourself from source. I
 get the same numbers as you (they seem to be the fractions multiplied with 255) -- but no warning messages. But I do not see this when I install from source. I will keep looking.

**Comment by ptitle** [comment]
Thanks!

**Comment by rhijmans** [comment]
The underlying problem was with `rasterize`. I completely reimplemented that method, which was a good thing to do anyway, and I am guessing that the problem no longer exists. Guessing as I could only reproduce it with a binary install from CRAN on OSX Catalina. I wiped my mac and upgraded to Big Sur and there all is good with current R and GDAL (both installed with homebrew).

**Comment by ptitle** [comment]
I just tested this out, and it works now. Values make sense, and no more GDAL warnings. thanks so much for the quick response!
