### ISSUE TITLE
Is zlim available in plot function for terra?

### ISSUE THREAD

**Issue by ptitle** [rspatial/terra#170]
In the raster package, there was a very useful feature where you could specify the bounds for the color ramp:

```
library(raster)
logo <- raster(system.file("external/rlogo.grd", package="raster")) 
plot(logo, zlim = c(150, 400))
```
Is that feature available in terra? I've been looking, but haven't found it, but maybe I missed it.

thanks!

**Comment by rhijmans** [comment]
It is called `range` in `terra` 

```
library(terra)
logo <- rast(logo*1)
plot(logo, range = c(150, 400))
```

**Comment by ptitle** [comment]
Oh, of course. I had looked at that but must have confused myself. Apologies!
