### ISSUE TITLE
Raster::clump equivalent

### ISSUE THREAD

**Issue by ChrisJones687** [rspatial/terra#171]
In the documentation, there is a raster::clump equivalent as terra::patches but it doesn't appear to be implemented yet. Is there a timeline for this functionality?

My use case to calculate the number and size of patches in a landscape that are infested with a specific pest.

**Comment by rhijmans** [comment]
Thank you for reminding. I should be able to add that this week.

**Comment by rhijmans** [comment]
I have now implemented the `patches` method. Please let me know if it (does not) work, if you can.

**Comment by ChrisJones687** [comment]
This works exactly like raster::clump if all 0 value cells are NA but returns a giant patch is cells are 0.

**Comment by rhijmans** [comment]
I have added an argument `zeroAsNA`. The default is `FALSE`. Setting it to `TRUE` give the same results as raster.
