### ISSUE TITLE
`app` does not like rasts with dims of (1,1,*)

### ISSUE THREAD

**Issue by dahcase** [rspatial/terra#172]
`app`'s [test run to determine the return shape](https://github.com/rspatial/terra/blob/ee7f1058571b199e85a603ee1216520c9aef0370/R/app.R#L22) via `round(0.5*nrow(x))` returns 0 when nrow(x) == 1. This in turn seems to make `readValues` grumpy. I think changing the .5 to .51 should fix things.

The common functions with a c++ implementation (e.g. `mean`) seem to behave just fine. 

``` r
library('terra')
#> terra version 1.0.10

a = c(rast(matrix(1)), rast(matrix(2)))

app(a, mean)
#> class       : SpatRaster 
#> dimensions  : 1, 1, 1  (nrow, ncol, nlyr)
#> resolution  : 1, 1  (x, y)
#> extent      : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
#> coord. ref. :  
#> source      : memory 
#> name        : mean 
#> min value   :  1.5 
#> max value   :  1.5

app(a, function(x) mean(x))
#> Error in .local(x, ...): row > 0 is not TRUE
```

**Comment by rhijmans** [comment]
Thank you. Now using 0.51 in `app`, `lapp`, `interpolate`, and `predict` to avoid "row 0"
