### ISSUE TITLE
Applying terrain() to multiple layers

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#175]
I'm trying to run terrain() over several DSMs.
While this works
```
elevation <- raster::getData('alt', country='CHE')
x <- terrain(elevation,v="roughness")
x <-lapply(c(elevation,elevation),FUN= terrain, v="roughness")
```
lapp() does not work:
```
> lapp(c(elevation,elevation),fun= terrain, v="roughness")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘lapp’ for signature ‘"list"’
```
Am I not using lapp() in the right way?

**Comment by rhijmans** [comment]
In this case, `lapply` is the way to go. `lapp` takes a function that operates on vectors and applies it to each cell of `SpatRaster` (see the examples).  I make a few changes to the docs to make that clearer.

**Comment by aloboa** [comment]
Could you perhaps consider a function (or an option) acting as lapply() but returning a multilayer SpatRast instead of a list?
Normally, if the function is to be applied independently to each layer of an input multilayer SpatRast, the user seeks a multilayer SpatRast as output.

**Comment by rhijmans** [comment]
You were able to do 

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
x <- sapply(1:nlyr(s), function(i) terrain(s[[i]]))
y <- rast(s)
```

Now you can do 

```
x <- sapply(as.list(s), terrain)
y <- rast(s)
```
Or use the new `sapp` 

```
z <- sapp(s, terrain)
```

I do this with some hesitation, as in this case I should really improve `terrain` and a handful of other methods that currently only work for one layer at a time. But I figured that because other packages may have functions like that, this would still be useful.
