### ISSUE TITLE
Predicting in parallel requires model package export to nodes

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#178]
The title pretty much says it all. Predicting on large rasters is working wonderfully now thanks to the adjustment of the `getBlockSize` function, and I was looking into reducing the prediction speed a bit. I came across the `cores` option in `predict` and tried that out using a `ranger` model, but that didn't seem to work when the number of cores was more than 1. Here is an example mostly using the sample code from the `predict` help page:

```
library(terra)
library(ranger)

logo <- rast(system.file("ex/logo.tif", package="terra"))   
names(logo) <- c("red", "green", "blue")
p <- matrix(c(48, 48, 48, 53, 50, 46, 54, 70, 84, 85, 74, 84, 95, 85, 
              66, 42, 26, 4, 19, 17, 7, 14, 26, 29, 39, 45, 51, 56, 46, 38, 31, 
              22, 34, 60, 70, 73, 63, 46, 43, 28), ncol=2)

a <- matrix(c(22, 33, 64, 85, 92, 94, 59, 27, 30, 64, 60, 33, 31, 9,
              99, 67, 15, 5, 4, 30, 8, 37, 42, 27, 19, 69, 60, 73, 3, 5, 21,
              37, 52, 70, 74, 9, 13, 4, 17, 47), ncol=2)

xy <- rbind(cbind(1, p), cbind(0, a))

# extract predictor values for points
e <- extract(logo, xy[,2:3])

# combine with response (excluding the ID column)
v <- data.frame(cbind(pa=xy[,1], e[,-1]))

#build a model, here with glm 
model <- ranger(formula=pa~., data=v, num.threads = 1)

#predict to a raster (works)
r1 <- predict(logo, model, fun = function(model, ...) predict(model, num.threads = 1, ...)$predictions)

#predict in parallel (fails)
r2 <- predict(logo, model, fun = function(model, ...) predict(model, num.threads = 1, ...)$predictions,
              cores = 2)

# Error in checkForRemoteErrors(val) : 
#   2 nodes produced errors; first error: no applicable method for 'predict' applied to an object of class "ranger"

```
I think this is coming about from the `ranger` package not being exported to each of the cores. Perhaps this is something that can be incorporated into the [clusterExport](https://github.com/rspatial/terra/blob/b246ecf73a20be250d1aa40d65c042ddd5456bad/R/predict.R#L139) part of the prediction execution? I've also tried doing this with a `randomForest` model with the same results, hence my suspicion. Admittedly, I don't use parallelism as much as I would like to so I don't have a lot of knowledge with it and perhaps I'm missing something, but at the moment I don't see it. 

Thanks again for your hard work!

**Comment by rhijmans** [comment]
You can add the library call to the predict function. 

```
pf <- function(model, ...) {
	library(ranger)
	predict(model, ..., num.threads = 1)$predictions
}
r2 <- predict(logo, model, fun = pf, cores = 2)
``` 

With `randomForest` 

```
library(randomForest)
rfm <- randomForest(formula=pa~., data=v)
rfun <- function(mod, dat, ...) {
	library(randomForest)
	predict(mod, dat, ...)
}
prf <- predict(logo, rfm, fun=rfun, cores=2)
```

I suppose I should add some documentation.

**Comment by mcoghill** [comment]
Ah, thank you for the explanation! Yes I was unaware it was needed in `fun`, that should be the ticket.

**Comment by rhijmans** [comment]
And you can also parallelize `fun` instead of `terra::predict`. Perhaps like this 

```
library(terra)
logo <- rast(system.file("ex/logo.tif", package="terra"))   
names(logo) <- c("red", "green", "blue")
p <- matrix(c(48, 48, 48, 53, 50, 46, 54, 70, 84, 85, 74, 84, 95, 85, 
              66, 42, 26, 4, 19, 17, 7, 14, 26, 29, 39, 45, 51, 56, 46, 38, 31, 
              22, 34, 60, 70, 73, 63, 46, 43, 28), ncol=2)
a <- matrix(c(22, 33, 64, 85, 92, 94, 59, 27, 30, 64, 60, 33, 31, 9,
              99, 67, 15, 5, 4, 30, 8, 37, 42, 27, 19, 69, 60, 73, 3, 5, 21,
              37, 52, 70, 74, 9, 13, 4, 17, 47), ncol=2)
xy <- rbind(cbind(1, p), cbind(0, a))
e <- extract(logo, xy[,2:3])
v <- data.frame(cbind(pa=xy[,1], e[,-1]))


library(randomForest)
rfm <- randomForest(formula=pa~., data=v)

rfun <- function(mod, dat, ...) {
	ncls <- length(cls)
	nr <- nrow(dat)
	s <- split(dat, rep(1:ncls, each=ceiling(nr/ncls), length.out=nr))
	unlist(  parallel::clusterApply(cls, s, function(x, ...) predict(mod, x, ...))  )
}

library(parallel)
cls <- parallel::makeCluster(2)
parallel::clusterExport(cls, c("rfm", "rfun", "randomForest"))
prf <- predict(logo, rfm, fun=rfun)
parallel::stopCluster(cls)
```

**Comment by mcoghill** [comment]
Thanks again for this explanation. Is there a benefit of performing parallel calls in `fun` rather than defining the number of cores? Again, I'm not well versed in parallelism so I apologize if I'm missing something obvious.

**Comment by rhijmans** [comment]
I would say that setting the number of cores is easier, but if that fails, there is this alternative. I think `party::cforest` has parallelization build into the predict function as an argument, so that should be pretty easy too. 
As for performance I really don't know. In the toy examples parallelization is much slower, as expected, because of the additional overhead. It could pay off with large rasters when using a `predict.model` function that is relatively slow (perhaps a randomForest model with many deep trees).

**Comment by pat-s** [comment]
With respect to speed when parallelizing, I found no gain when using `cores >= 2` in `terra::predict()`, even for large rasters (12 mio cells).

[Here](file:///Users/pjs/git/mlr-org/mlr3spatial/docs/articles/benchmark.html) is a benchmark with some toy code. I've checked on Ubuntu and macOS with no differences.
Is this an issue within {terra}? I'd expect a speed improvement for such a large raster when going parallel despite the parallel overhead.
You can also see the speed improvement we get when using the mlr3 internal predict function (which is using its own parallel predict approach).

**Comment by rhijmans** [comment]
Can you add the benchmark code?

**Comment by pat-s** [comment]
Ups, forgot to add the hyperlink. Now added in the previous comment.

**Comment by rhijmans** [comment]
In this simplified example I see a clear speed improvement:


```
library(mlr3)
library(mlr3learners)
library(mlr3spatial)
library(terra)

stack = demo_stack_spatraster(size = 125, layers = 5)
backend = DataBackendSpatRaster$new(stack)
task = as_task_classif(backend, target = "y", positive = "TRUE")
task = as_task_classif(backend, target = "y", positive = "TRUE")
set.seed(42)
row_ids = sample(1:task$nrow, 500)
e1071svm = e1071::svm(y ~ ., task$data(rows = row_ids))

system.time(tseq <- predict(stack, e1071svm)
#   user  system elapsed 
# 188.84    1.77  194.28 
system.time(tseq <- predict(stack, e1071svm)
#   user  system elapsed 
# 175.80    0.78  177.53 

system.time(tseq <- predict(stack, e1071svm, cores = 4, cpkgs = "e1071"))
#   user  system elapsed 
#  18.00    3.55   59.84 
system.time(tseq <- predict(stack, e1071svm, cores = 4, cpkgs = "e1071"))
#   user  system elapsed 
#  13.29    3.25   50.27 

```

**Comment by pat-s** [comment]
It seems that on my machine the single-core performance is too good and the parallel overhead too much to profit with this size of the raster.
At least with the parallelism {terra} uses.

As shown in the [benchmark in {mlr3spatial}](https://mlr3spatial.mlr-org.com/articles/benchmark.html), the future-based parallelism seems to include less overhead.

``` r
library(mlr3)
library(mlr3learners)
library(mlr3spatial)
library(terra)
#> terra version 1.3.19
library(e1071)
#> 
#> Attaching package: 'e1071'
#> The following object is masked from 'package:terra':
#> 
#>     interpolate

stack <- demo_stack_spatraster(size = 125, layers = 5)
backend <- DataBackendSpatRaster$new(stack)
task <- as_task_classif(backend, target = "y", positive = "TRUE")
task <- as_task_classif(backend, target = "y", positive = "TRUE")
set.seed(42)
row_ids <- sample(1:task$nrow, 500)
e1071svm <- e1071::svm(y ~ ., task$data(rows = row_ids))

bench::mark(
  "3-terra-sequential" = terra::predict(stack, e1071svm, cores = 1, cpkgs = "e1071"),
  "7-terra-4-cores" = terra::predict(stack, e1071svm, cores = 4, cpkgs = "e1071"),
  check = FALSE, filter_gc = FALSE, max_iterations = 1, memory = FALSE
)
#> # A tibble: 2 × 6
#>   expression              min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>         <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 3-terra-sequential    25.4s    25.4s    0.0393        NA   0.511 
#> 2 7-terra-4-cores       34.4s    34.4s    0.0290        NA   0.0581

system.time(terra::predict(stack, e1071svm, cores = 1, cpkgs = "e1071"))
#>    user  system elapsed 
#>  22.887   1.054  24.139

system.time(terra::predict(stack, e1071svm, cores = 4, cpkgs = "e1071"))
#>    user  system elapsed 
#>  11.470   2.017  32.966
```

<sup>Created on 2021-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
