### ISSUE TITLE
Perhaps change `predict`'s readValues function to also extract data from the middle column

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#179]
Hi, sorry for submitting another issue, I know you're busy.

I am currently trying to do probability predictions, so the output I'm looking for is multi-layered for the probability of each class in a model. The shape of my study area is fairly irregular though and I'm getting a single layered output instead of only the first probability category. Here is an example:

```
library(terra)
library(ranger)

# Create dataset
r <- rast(nrow = 500, ncol = 1000)
x <- init(r, fun="col")
y <- init(r, fun="col")

# Change first 500 columns to NA values
y[y<=500] <- NaN

r1 <- rast(lapply(1:5, function(z) x + z))
r2 <- rast(lapply(1:5, function(z) y + z))
names(r1) <- paste0("lyr.", 1:nlyr(r1))
names(r2) <- paste0("lyr.", 1:nlyr(r2))

# extract points at random cell numbers
cn <- round(runif(100, 1, ncell(r1)))

# extract predictor values for points
e <- extract(r2, cn)
e <- e[complete.cases(e), ]

# Create random factor data
p <- factor(sample(LETTERS, nrow(e), replace = TRUE))

# combine with response
v <- data.frame(cbind(pa=p, e))

#build a model, here with ranger
model <- ranger(formula=pa~., data=v, probability = TRUE)

#predict to a raster 
pf <- function(model, ...) {
  predict(model, ...)$predictions
}

# Multi-layered output
p1 <- predict(r1, model, fun = pf, na.rm = TRUE)

# Single layered output
p2 <- predict(r2, model, fun = pf, na.rm = TRUE)

sapply(list(p1, p2), nlyr)
# [1] 19  1
```
And here is a screenshot of what my study area looks like:

![Screenshot 2021-03-21 124900](https://user-images.githubusercontent.com/50680476/111918770-f69f2980-8a43-11eb-8e25-a882ca1f7be3.png)

I think I've found what is going on: In the `predict` function, it initiates predictions by opening the raster files and selecting data from the middle row and first column, then moving across and getting data from the first 500 columns. At least, that is my interpretation of [this line.](https://github.com/rspatial/terra/blob/5c647156382d92999329cfa95db49ce42e9396a2/R/predict.R#L128) It then goes on to predict values if there is at least one row of returned data, but if there are no rows then the resulting number of columns is [hard set to 1.](https://github.com/rspatial/terra/blob/5c647156382d92999329cfa95db49ce42e9396a2/R/predict.R#L45-L47) This works good for regression and classification modelling, but with probabilities at least, you would want the number of columns to equal the number of predictive classes so that the output is consistent. Perhaps adding some sort of check for returned data after column initialization should be required, or maybe a new definition of where to read the first set of data from is the key. I'm not sure at this point, but maybe I'll leave that for you to decide :)

**Comment by mcoghill** [comment]
Here is a suggestion that you could use in the `predict` function before reading cell values:

```
# Find cell numbers that have data in them
valid <- spatSample(subset(object, 1L), 1, na.rm = TRUE, cells = TRUE)[1]
cs <- colFromCell(object, valid)
rs <- rowFromCell(object, valid)

# Use the column and row start values to initiate predictions
readStart(object)
on.exit(readStop(object))
d <- readValues(object, row=rs, nrow=1, col=cs, ncols=min(nc-cs, 500), TRUE, TRUE)
```
The idea there is that there should always be at least 1 non-NA value in d, which would result in the proper expected amount of columns in `.runModel`. Again, it's just a suggestion - you might have a better plan of attack!

**Comment by rhijmans** [comment]
Thank you very much. I just saw your solution, which is not bad, but I took a somewhat different route. By sampling up to 3 entire rows. I now get:

```
library(terra)
library(ranger)
r <- rast(nrow = 500, ncol = 1000)
x <- init(r, fun="col")
y <- init(r, fun="col")
y[y<=500] <- NaN
r1 <- rast(lapply(1:5, function(z) x + z))
r2 <- rast(lapply(1:5, function(z) y + z))
names(r1) <- paste0("lyr.", 1:nlyr(r1))
names(r2) <- paste0("lyr.", 1:nlyr(r2))
set.seed(1)
cn <- round(runif(100, 1, ncell(r1)))
e <- extract(r2, cn)
e <- e[complete.cases(e), ]
p <- factor(sample(LETTERS, nrow(e), replace = TRUE))
v <- data.frame(cbind(pa=p, e))
model <- ranger(formula=pa~., data=v, probability = TRUE)

pf <- function(model, ...) {
  predict(model, ...)$predictions
}

# Multi-layered output
p1 <- predict(r1, model, fun = pf, na.rm = TRUE)
nlyr(p1)
#[1] 24

# Now also multilayered output
p2 <- predict(r2, model, fun = pf, na.rm = TRUE)
nlyr(p2)
#[1] 24
```

If all three rows are NA:

``` 
r2[130,]=NA
r2[255,]=NA
r2[380,]=NA
p3 <- predict(r2, model, fun = pf, na.rm = TRUE)
#Warning message:
#[predict] Cannot determine the number of output variables. Assuming 1. Use argument 'index' to set it manually 
nlyr(p3)
#[1] 1
 
p3 <- predict(r2, model, fun = pf, na.rm = TRUE, index=1:23)
nlyr(p3)
#[1] 23
p3
#class       : SpatRaster 
#dimensions  : 500, 1000, 23  (nrow, ncol, nlyr)
#resolution  : 0.36, 0.36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : memory 
#names       :         lyr1,         lyr2,         lyr3,         lyr4,         lyr5,         lyr6, ... 
#min values  : 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, ... 
#max values  :    0.4192675,    0.1509159,    0.2413770,    0.1756524,    0.2763206,    0.4361976, ... 
```

But we have lost the variable names.

**Comment by mcoghill** [comment]
That's great! The loss of variable names I think is reasonable in this case. Plus, I was trying my suggestion out and sometimes `spatSample` does not return anything. This could be overcome by changing `size` to be more than 1 (e.g.: 100) but your solution here will likely be better. Thank you again!

**Comment by rhijmans** [comment]
I have made an additional change based on your suggestion. With the example data above the last case now also works.
