### ISSUE TITLE
Attribute table not preserved when writing to files

### ISSUE THREAD

**Issue by qdread** [rspatial/terra#187]
This is related to [this question on GIS stackexchange](https://gis.stackexchange.com/questions/391215/attribute-table-in-r-terra-package) but I believe I now have a better idea of exactly what my issue is.

I read from a large raster file that has both a color table and attribute table, do a crop and aggregate operation on it, and restore the color table and attribute table to the cropped and aggregated raster. When I write this raster to a file using `writeRaster` then try to read it back in using `rast`, the color table is still there but the attribute table is not (it is a copy of the color table again).

Following is a (hopefully) reproducible example. The NLCD raster I read in originally is too large to include here but is available at the "Download" link at <https://www.mrlc.gov/data/nlcd-2016-land-cover-conus>. It consists of the .img file, a spillover .ige file, and .rrd and .rde files.

```
# Read from NLCD raster
library(terra)
nlcd <- rast('NLCD_2016_Land_Cover_L48_20190424.img')

# View head of color table and attributes.
head(coltab(nlcd)[[1]], 12)
head(rats(nlcd)[[1]], 12)

# Crop to a specified extent and aggregate to a coarser resolution.
maryland_ext <- ext(c(xmin = 1394535, xmax = 1845135, ymin = 1724415, ymax = 2101515))
nlcd_maryland <- crop(nlcd, maryland_ext) 
nlcd_maryland_agg <- aggregate(nlcd_maryland, fact = 5, fun = 'modal')

# Replace the lost color table and attributes.
coltab(nlcd_maryland_agg) <- coltab(nlcd)
rat <- data.frame(ID = 0:255, NLCD.Land.Cover.Class = rats(nlcd)[[1]]$NLCD.Land.Cover.Class)
rats(nlcd_maryland_agg) <- rat

# Confirm that these are as desired.
head(coltab(nlcd_maryland_agg)[[1]], 12)
head(rats(nlcd_maryland_agg)[[1]], 12)

# Write to another .img file.
writeRaster(nlcd_maryland_agg, 'nlcd_agg.img', overwrite = TRUE)

# Read back in and test whether color table and attributes were preserved.
nlcd_reload <- rast('nlcd_agg.img')

# Color table is preserved but attribute table is now equivalent to the color table.
head(coltab(nlcd_reload)[[1]], 12)
head(rats(nlcd_reload)[[1]], 12)
```

*edited: fixed a couple typos in script*

**Comment by rhijmans** [comment]
Your question on stackexchange triggered me to revise all this. I have removed the `rats` method, and treat "categories" and "attributes" as equivalent. That has simplified things and you can now do:

```
library(terra)
nlcd <- rast('NLCD_2016_Land_Cover_L48_20190424.img')
plot(nlcd)
# smaller exent for testing
ext <- ext(c(xmin = 1394535, xmax = 1445135, ymin = 1724415, ymax = 1801515))
nlcd_ext <- crop(nlcd, ext) 
nlcd_agg <- aggregate(nlcd_ext, fact = 10, fun = 'modal')

# Replace the lost color table and attributes.
coltab(nlcd_agg) <- coltab(nlcd)
levels(nlcd_agg) <- levels(nlcd)
plot(nlcd_agg)

x <- writeRaster(nlcd_agg, 'nlcd_agg.img', overwrite = TRUE)
plot(x)
``` 

A next step to take is to not loose the colors and levels when using aggregate with modal (and to speed that up a bit). 
Also, in writing only a single category is saved --- that is enough in almost all cases, but I will improve that.

**Comment by qdread** [comment]
Thanks so much! This works great for our purposes. Out of curiosity, when would this version be released on CRAN?

**Comment by rhijmans** [comment]
I sent it to CRAN yesterday --- so it may be available there next week; depending on what their checks may find.

**Comment by rhijmans** [comment]
color table and levels are now preserved when using `aggregate(x, fun="modal")`
