### ISSUE TITLE
terra::resample crashes R session

### ISSUE THREAD

**Issue by erydit** [rspatial/terra#188]
I am trying to resample Sentinel-2 layer on another raster. Just a simple code:
`r_resample <- terra::resample(x=r_savi, y=r_zone, method="bilinear")`

If I run the code interactively (in RStudio, for example), the R session crashes with no errors. Wrapping the code into tryCatch does not prevent from crashing.

If I run the code in command line using Rscript, I get the error: 
`<std::bad_alloc in x@ptr$warp(y@ptr, "", method, FALSE, opt): std::bad_alloc>`

Other terra functions seems to work normally on the same rasters.

My sessionInfo() 
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0
```
terra version : 1.1-4
I run the code with the` terraOptions(memfrac=0.6, todisk=T, tempdir = file.path(fld_CACHE, "terra_temp"))`

**Comment by erydit** [comment]
terra::project leads to the same error

**Comment by rhijmans** [comment]
Thanks for reporting this.  Can you `show(r_savi) and `show(r_zone)`?

**Comment by erydit** [comment]
```
show(r_savi)
class       : SpatRaster 
dimensions  : 10980, 10980, 1  (nrow, ncol, nlyr)
resolution  : 10, 10  (x, y)
extent      : 6e+05, 709800, 5990220, 6100020  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=39 +datum=WGS84 +units=m +no_defs  
source      : 39UXA_20200403_SAVI-masked.tif 
name        :  lyr1 
min value   : -3900 
max value   :  8719 

show(r_zone)
class       : SpatRaster 
dimensions  : 6255, 6334, 1  (nrow, ncol, nlyr)
resolution  : 10, 10  (x, y)
extent      : 605635, 668975, 6055909, 6118459  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=39 +datum=WGS84 +units=m +no_defs  
```

```
r_resample <- terra::resample(x=r_savi, y=r_zone, method="bilinear", verbose=T)
filename      : /home/dsuser/RSMonitor/A_RS_cache//terra_temp/spat_HZKtH2XvBZT0v7J.tif
compute stats : 1, GDAL: 0, minmax: 0, approx: 1
driver        : GTiff
disk available: 23.8 GB
disk needed   : 0.1 GB
memory avail. : 2.69 GB
memory allow. : 1.62 GB
memory needed : 0.59 GB  (2 copies)
in memory     : false
block size    : 6255 rows
n blocks      : 1
pb            : 0
```

I also update R to version 4.0.5. and the problem is still preserved.
However on my home computer everything work without any issues. 
My home pc:
```
sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.9.0
LAPACK: /usr/lib/liblapack.so.3.9.0
```

**Comment by rhijmans** [comment]
Here is a reproducible version of what you reported

```
library(terra)
x <- rast(nrow= 10980, ncol=10980, ext=ext(6e+05, 709800, 5990220, 6100020), crs="+proj=utm +zone=39 +datum=WGS84 +units=m")
y <- rast(nrow= 6255, ncol=6334, ext=ext(605635, 668975, 6055909, 6118459), crs="+proj=utm +zone=39 +datum=WGS84 +units=m")
x <- init(x, "cell")  
r <- resample(x, y)
```

Please let me know if it still fails for you.  I am assuming that it failed on a computer with an older version of GDAL --- as reported by `terra::gdal()`.  I think it should now work with GDAL >= 2.1;

**Comment by erydit** [comment]
Sorry for not reproducible example in an initial message. Im not very experienced in it.

Am i need to reinstall terra package from github using devtools to get the problem fixed? As I understand, the fix have not got in the cran yet?

**Comment by rhijmans** [comment]
Yes you had to install it from github. Updates to CRAN are monthly at best.  Thank you very much for letting me know that it now works.
