### ISSUE TITLE
as.polygons not working with "values=T"

### ISSUE THREAD

**Issue by bevingtona** [rspatial/terra#19]
Hi there, comparing speeds between the raster and terra packages - and terra is awesome. I have a large raster mask (land cover of value 1, and the rest are NA) and am failing to convert the raster to a vector and dissolve it. 

Here is a reproducible example of the `raster` workflow that works just fine: 

```
library(raster)
r1 <- raster(ncol = 10, nrow = 10)
values(r1) <- round(runif(ncell(r1), 0, 1))
p1 <- rasterToPolygons(r1, fun=function(x){x==1}, dissolve = T, na.rm = T)
```

And using `terra`, when I use `as.polygons()`, the example works, but it does not work when `values = true`, RStudio crashes immediately. Also it doesn't seem that there is no dissolve option in `as.polygons()`, like there was in the raster package above. 

```
library(terra)
r1 <- rast(ncol = 10, nrow = 10)
values(r1) <- round(runif(ncell(r1), 0, 1))
p1 <- as.polygons(r1, values = T)
```

Thanks for your insights

**Comment by rhijmans** [comment]
It has taken me a while, but I have now fixed the `values=TRUE` bit. I will keep this open for the `dissolve` part .

**Comment by rhijmans** [comment]
as.polygons now dissolves/aggregates.
