### ISSUE TITLE
xy in spatSample(): return coordinates in addtion to values

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#191]
According to the doc:
> xy	logical. If TRUE, coordinates are returned instead of values

could it become:
xy	logical. If TRUE, coordinates are returned along values

and also have an option such as "as.vector" to get a vector point layer?

**Comment by rhijmans** [comment]
There are now two new arguments: `as.vector=FALSE` and `values=TRUE`. 
And, `cells` and `xy` and `values` are no longer mutually exclusive.
