### ISSUE TITLE
as.matrix doesn't return dimensions

### ISSUE THREAD

**Issue by tlhenvironment** [rspatial/terra#195]
I am trying to read out raster data in it's matrix representation. The [documentation ](https://rdrr.io/github/rspatial/terra/man/values.html) suggests to use 'as.matrix()', since here _the number of rows and columns matches that of x, if x has a single _layer__

I found this is not the case, e.g:
```
matrix(1:100, nrow = 10, ncol = 10) -> mm
rast(mm) -> spat_raster

as.matrix(spat_raster)
```

results in a 1dim matrix.  Is there a way to extract a 2D matrix representation, without the need to write some re-formatting function on the 1D output?

**Comment by rhijmans** [comment]
The below is from the example in `?as.matrix`

```
library(terra)
r <- rast(ncol=2, nrow=2)
values(r) <- 1:ncell(r)
as.matrix(r, wide=TRUE)
#     [,1] [,2]
#[1,]    1    2
#[2,]    3    4
```
