### ISSUE TITLE
raster::terrain - terra::terrain

### ISSUE THREAD

**Issue by salder** [rspatial/terra#196]
Hi,
I get different results when running terrain i raster and terra for a 2m x 2m DEM.
Choosing degrees in terra::terrain seams to deliver wrong values (much largern than 90)?
(I have just downloaded and new installed terra from Github but the differances is still there..
(if you need the data file I can send it to you be email)

hm.slope<-terra::terrain(hm, v="slope", neighbors=8, unit="degrees")
hm.slope
class       : SpatRaster 
dimensions  : 500, 500, 1  (nrow, ncol, nlyr)
resolution  : 2, 2  (x, y)
extent      : 640126, 641126, 7507978, 7508978  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
source      : memory 
name        :     slope 
min value   : 0.1355786 
max value   :   639.098

hm.r.slope<-raster::terrain(hm.r,opt="slope", neighbors=8, unit="degrees")
hm.r.slope
class      : RasterLayer 
dimensions : 550, 550, 302500  (nrow, ncol, ncell)
resolution : 2, 2  (x, y)
extent     : 640076, 641176, 7507928, 7509028  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs 
source     : memory
names      : slope 
values     : 0.09442247, 84.87707 (min, max)

Best regards
Sven

**Comment by rhijmans** [comment]
Thank you very much for reporting this. The tangent of the slope was returned (when using unit="radians") by `terra`, instead of the slope. I now get the same results for `terra` and `raster`. Illustrated here:

```
library(terra)
library(raster)
er_deg <- getData('alt', country='CHE')
et_deg <- rast(er_deg*1)

et_utm <- project(et_deg, "+proj=utm +zone=33 +datum=WGS84")
er_utm <- raster(et_utm)

ngb = 8
unit = "degrees"

x <- terrain(er_deg, "slope", neighbors=ngb, unit=unit)
y <- terrain(et_deg, "slope", neighbors=ngb, unit=unit)

a <- terrain(er_utm, "slope", neighbors=ngb, unit=unit)
b <- terrain(et_utm, "slope", neighbors=ngb, unit=unit)

par(mfrow=c(1,2))
plot(rast(x), y, cex=.5); abline(0,1,col="red")
plot(rast(a), b, cex=.5); abline(0,1,col="red")
```

**Comment by salder** [comment]
Hi
Thank you very much for your fast answer and correction of the function!
Tested it and it works perfect!
Best regards
Sven
