### ISSUE TITLE
Using rast object as input in parallelized function

### ISSUE THREAD

**Issue by STBrinkmann** [rspatial/terra#197]
I am trying to use a rast object as a parameter in a parallelized function.
Let's say we have this simple function:
```
test_fun <- function(sf_obj, rast_obj) {
    return(terra::crop(rast_obj, sf::st_buffer(sf_obj, 100)))
}
```
With an rast object called `rast_obj` and some point features converted to a list: 
```
sf_obj <- data.frame(
    x = seq(487618, 487626, by=1),
    y = seq(5455970, 5455974, by=0.5)
) %>% 
    sf::st_as_sf(coords = c("x","y")) %>% 
    sf::st_set_crs(26910) %>%
    split(seq(nrow(.)))
```

Now, I apply the test_fun on sf_obj using the lapply function works just fine:
`lapply(sf_start_list, test_fun, DTM)`

However, If i want to use parallel lapply like this:
`parallel::mclapply(sf_start_list, test_fun, DTM, mc.cores = 2)`
I get this error:
```
$`1`
class       : SpatRaster 
Error in x@ptr$nrow() : external pointer is not valid
```

I am wondering how to use rast objects and terra function inside mclapply.

**Comment by rhijmans** [comment]
Spat* objects cannot be serialized. So you need to create them in the nodes. For example, by passing a filename, or, for smaller objects, a packed object (see `pack`). My plan is to build in parallelization at the C++ level, but I have not done that yet. See some more discussion `https://github.com/rspatial/terra/issues/36`

**Comment by rCarto** [comment]
For future reference `pack()` has been renamed to `wrap()` since version 1.2-5. 
https://rspatial.github.io/terra/reference/wrap.html

**Comment by GuiAlDuS** [comment]
I'm going through a similar issue as @STBrinkmann, but my case is with the terra::crop function. 
The interesting thing with mclapply is that, even though it shows the same external pointer error when I try to access the elements of the resulting list, the raster files are actually created (using the filename argument of the crop function).

My "not-so-elegant" solution is to load the resulting rasters after the mclapply processes finish, and continue with the analysis.

Hope it helps!
