### ISSUE TITLE
Incompatibility with PROJ 8.0.0

### ISSUE THREAD

**Issue by ofisette** [rspatial/terra#199]
The recently released PROJ 8.0.0 seems incompatible with R `terra`. The package compiles but fails during the test phase with:

```
** testing if installed package can be loaded from temporary location
sh : ligne 1 : 30764 Aborting                 R_TESTS= '/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/r/4.0.5/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmppzaKXK/file6dc14a1e6eea'
free(): invalid pointer
ERROR: loading failed
* removing ‘/home/ofisette/tests/Renvs/terra/terra’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp1KTr2C/file6cc464b7ad49/terra_1.2-4.tar.gz’ had non-zero exit status
```

Downgrading to PROJ 7.0.1 fixed the issue.

This was tested with R 4.0.5 on a Linux HPC cluster using the Compute Canada software stack.

**Comment by amarbler** [comment]
Hi,

I don't think that this is an terra issue. I'm using PROJ 8.0.1 and have no problems:

Check PROJ version
```
library(sf)
Linking to GEOS 3.7.1, GDAL 3.3.0, PROJ 8.0.1
```
Confirm that terra can be loaded:
```
library(terra)
terra version 1.3.10
```

**Comment by edzer** [comment]
@ofisette this is usually an indication that you have multiple instances of PROJ, GDAL or GEOS installed on your system.

**Comment by ofisette** [comment]
@edzer Thanks, that’s helpful. I found that our GDAL library was linked against PROJ 7.0.0. That was the issue.
