### ISSUE TITLE
allow subdataset strings

### ISSUE THREAD

**Issue by mdsumner** [rspatial/terra#20]
I'd rather like to be able to use general SDS strings, and not just file names. 

I tried out a naive approach, here in rasterFromFile.cpp: 

```
bool SpatRaster::constructFromFile(std::string fname) {


	if (!file_exists(fname)) {
#ifdef useGDAL
	  return constructFromFileGDAL(fname);
#endif // useGDAL
	}
```

And that works fine - and returns a reasonable error if it's not a valid SDS -  but it's not clear to me how the cascade of checks should go. Can it catch the error from GDAL and *then* check if it's not a file? 

Example: 

```R
sds <- vapour::vapour_sds_names(system.file("extdata/gdal/sds.nc", package = "vapour", mustWork = TRUE) )
> rast(sds$subdataset[2])
class       : SpatRaster 
dimensions  : 61, 87, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0.5, 87.5, 0.5, 61.5  (xmin, xmax, ymin, ymax)
coord. ref. :  
data source : NETCDF:"/usr/local/lib/R/site-library/vapour/extdata/gdal/sds.nc":vv2 
names       : sds 
```

**Comment by mdsumner** [comment]
The reason this is needed atm is when there are 1D array SDS listed first, and GDAL can't read them - I can get an example .nc file if that's helpful but this is what the output looks like: 

```R
rast("~/data/my.cmems-du.eu/Core/SEALEVEL_GLO_PHY_L4_REP_OBSERVATIONS_008_047/dataset-duacs-rep-global-merged-allsat-phy-l4/1993/dt_global_allsat_phy_l4_19930101_20180115.nc")
Warning 1: dimension #1 (nv) is not a Longitude/X dimension.
Warning 1: dimension #1 (nv) is not a Longitude/X dimension.
Warning 1: dimension #0 (longitude) is not a Latitude/Y dimension.
 Error: (rast) dimensions and/or extent do not match 
```

**Comment by mdsumner** [comment]
If you are interested in the particular file I could send it to you, 8Mb under gzip. The actual source requires a log in as per description here: https://github.com/AustralianAntarcticDivision/blueant#cmems-global-gridded-ssh-near-real-time

**Comment by rhijmans** [comment]
I think it works now.

**Comment by mdsumner** [comment]
It does, thanks! 

But, for that particular file we're getting ydim = 2 rather than 1 (not related to this issue).

**Comment by mdsumner** [comment]
nvm, it does work  - all good!
