### ISSUE TITLE
crop() issues in version 1.2-5

### ISSUE THREAD

**Issue by STBrinkmann** [rspatial/terra#201]
I updated terra from version 1.1-4 and noticed some issues. Before I could use crop(rast, sf_object), where rast is a spatialRaster and sf_object is a sf polygon.
I get this warning:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'mask': [crop] cannot get a SpatExtent from y
```
To solve this I need to do crop(rast, vect(sf_object)).

**Comment by rhijmans** [comment]
Very sorry about that. I am not sure how that happened but I think it now works again. 

```
library(terra)
r <- rast(system.file("ex/elev.tif", package="terra"))
v <- vect(system.file("ex/lux.shp", package="terra"))

x <- crop(r, v[1])
s <- sf::st_as_sf(v[1])
y <- crop(r, s)
```
