### ISSUE TITLE
R crashes reading shp with terra::vect

### ISSUE THREAD

**Issue by consumere** [rspatial/terra#202]
Hi,
I am not sure if this is a bug in terra::vect or something else. If this is the wrong place to report, please let me know. 

R crashes without any diagnostics when reading the shapefile (see code below) using vect().
No problems by using sf::read_sf() .... 

Tested on Rstudio.cloud and Rstudio Windows Version 1.3.1093
terra version 1.2.5

Greetings
Chris

```
require(curl)
tt = tempfile()
tt = curl_download(
  'https://www.eea.europa.eu/data-and-maps/data/european-river-catchments-1/zipped-shapefile-vector-polygon/zipped-shapefile-vector-polygon/at_download/file',tt
)
require(utils)
unzip(tt)

####crashes immediately
require(terra)
watst <- vect("ERC110108v2.shp")

##this works... 
require(sf)
waf<-read_sf("ERC110108v2.shp")
```

**Comment by rhijmans** [comment]
Thank you very much for reporting this. This was caused by a NULL geometry that not caught in time. I need to a few more things to make sure that these are handled well.

**Comment by rhijmans** [comment]
Thanks again, that was very useful. I can now also roundtrip to `sf`.

```
library(curl)
zipf <- tempfile()
curl_download(
"https://www.eea.europa.eu/data-and-maps/data/european-river-catchments-1/zipped-shapefile-vector-polygon/zipped-shapefile-vector-polygon/at_download/file", zipf)

utils::unzip(zipf)

library(sf)
library(terra)
# terra version 1.2.7
x <- vect("ERC110108v2.shp")
y <- st_as_sf(x)
z <- vect(y)
```
