### ISSUE TITLE
extract causes segmentation fault

### ISSUE THREAD

**Issue by fab4ap** [rspatial/terra#203]
Using "bilinear" method in terra::extract() causes segmentation fault in R windows, terra version 1.2.5 ; however "simple" method works.

**Comment by rhijmans** [comment]
Thank you for reporting but can you provide some more details?  For example `show(x)` and/or `as.character(x)` for raster `x` and some description of the points you are using? And the version of `terra`?  This is because I do not see this: 

```
library(terra)
#terra version 1.2.7
f <- system.file("ex/meuse.tif", package="terra")
r <- rast(f)
xy <- cbind(179000, 330000)
xy <- rbind(xy-100, xy, xy+1000)
extract(r, xy)
#  test
#1  378
#2  251
#3  208
extract(r, xy, method="bilinear")
#    test
#1 378.00
#2 270.75
#3 197.25

```

**Comment by rhijmans** [comment]
Thanks, it was the combination of `method="bilinear"` **and** `cells-TRUE`.   This now works in the development version:

```
library(terra)
# terra version 1.2.7
f <- system.file("ex/meuse.tif", package="terra")
r <- rast(f)
xy <- cbind(179000, 330000)
xy <- rbind(xy-100, xy, xy+1000)

extract(r, xy, method="bil", cells=T)
#    test cell
#1 378.00 8173
#2 270.75 8016
#3 197.25 6041
```
