### ISSUE TITLE
Merge: excessive usage of disk space

### ISSUE THREAD

**Issue by mtalluto** [rspatial/terra#210]
Hello,
I have a list of rasters I am trying to merge. The rasters are all spatially continuous, and total size of the rasters in the list is around 45 MB. And output mosaic made with another program is also around 450 MB. Running this with `do.call(merge, r_list)` takes a very long time, and eventually eats all of my hard drive space. I aborted midway through, and now have 110 GBs of scratch .tif's in my tempdir. Many individual files are much larger than all of the input rasters combined (2GB+). Just to be sure it was terra, I removed all the tifs and re-ran merge again, with the same result. It seems to be somewhat scale dependent. Running the merge on a smaller subset of the list (5 of 29) finishes very quickly, and if it writes tempfiles they are cleaned up quickly. Trying with 10 was very slow and started creating lots of large tempfiles, so I killed it before it finished. have you seen similar behaviour before? I can provide the data privately if needed to reproduce.

Running the same list through raster::merge takes only about a minute, and produces a single 500 mb scratch file before writing the output.

R: 3.6.3
terra: 1.2.10

Thanks!

**Comment by rhijmans** [comment]
Thanks for reporting this. I think the issue with `do.call` is that it calls `merge` on the first two SpatRasters and then recursively on the output of `merge` and the next `SpatRaster` in the list. If two `SpatRasters` are far apart a temp file may be written for that and all subsequent merges. So the differences you see probably have to do with the total area covered and perhaps the order of the rasters in the list.  

I have now exposed a more efficient internal method, in which you first create a `SpatRasterCollection`

Example data 

```
library(terra)
x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, ncols=30, nrows=30)
y <- rast(xmin=-85, xmax=-55, ymax=60, ymin=30, ncols=30, nrows=30)
z <- rast(xmin=-60, xmax=-30, ymax=50, ymin=20, ncols=30, nrows=30)
values(x) <- 1:ncell(x)
values(y) <- 1:ncell(y)
values(z) <- 1:ncell(z)

r_list <- list(x, y, z)
``` 

And now do

```
rsrc <- src(r_list)
m <- merge(rsrc)
```

It would be great if you can try this with the development version and report back.

You can also contact me over email for the files, or simply report their structure like this:

```
sapply(r_list, as.character)
``` 

Furthermore, there is another approach to `merge` from file-based rasters like this:

```
writeRaster(x, "test1.tif", overwrite=TRUE)
writeRaster(y, "test2.tif", overwrite=TRUE)
writeRaster(z, "test3.tif", overwrite=TRUE)

v <- vrt(c("test1.tif", "test2.tif", "test3.tif"), "test.vrt", overwrite=T)
plot(v)
# writeRaster(v, "merged.tif")
```

**Comment by mtalluto** [comment]
Thanks for the quick fix! I'm happy to test with my data, but I'm afraid I'm a bit stuck. Running on a different machine (R 4.1 alpha on arm64/apple silicon), because the machine 3.6 isn't set up to compile terra from source. I forgot to mention before, but I also tried my original example with the same build for R 4.1, with the same results. However, terra now is failing to build. It worked a week ago, so I have no idea what changed! The following fails, whether I try to install from github or try to reinstall from CRAN. I haven't changed PROJ since then, so if you have some idea how I might troubleshoot this, that would be most helpful. I've tried specifying LDFLAGS via configure.vars, also via .R/Makevars, no joy. 

```
remotes::install_github("rspatial/terra", configure.args = c("--with-proj-lib=/opt/local/lib/", "--with-proj-include=/opt/local/include/"))
# also fails, but previously worked fine
# install.packages("terra", type="source", configure.args = c("--with-proj-lib=/opt/local/lib/", "--with-proj-include=/opt/local/include/"))

configure: CC: clang -arch arm64
configure: CXX: clang++ -arch arm64 -std=gnu++11
checking for gdal-config... /opt/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.2.2
checking GDAL version >= 2.0.1... yes
checking for gcc... clang -arch arm64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang -arch arm64 accepts -g... yes
checking for clang -arch arm64 option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -arch arm64 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /opt/local/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.2.2
checking proj.h usability... yes
checking proj.h presence... yes
checking for proj.h... yes
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no

```

**Comment by r2j2ritson** [comment]
@rhijmans , I have a quick question after reading this. Will the virtual tile approach work for the `mosaic` function as well? Thanks!
