### ISSUE TITLE
Extract with cells = TRUE doesn't return correct cell or value from the SpatRaster

### ISSUE THREAD

**Issue by ChrisJones687** [rspatial/terra#216]
@rhijmans Thanks for the great work on this package. We use it internally for a package we maintain. 

The latest release v1.2-10 leads the extract function returning incorrect values and cell ids. This is probably related to #214 as it seems to be in the same vain. This worked in all versions prior to 1.2-10. The reproducible example below:

``` R
x <- rast(x = matrix(0, 5,5))
x[2,2] <- 20
x[1,2] <- 15
p <- terra::as.points(x)
names(x) <- "data"
names(p) <- "data"
x <-
  terra::classify(x,
                  matrix(c(0, NA), ncol = 2, byrow = TRUE), right = NA)
p <- p[p$data > 0]
terra::extract(x, p, cells = TRUE)
  ID data cell
1  1   15   21
2  2    1    7
terra::extract(x, p)
  ID data
1  1   15
2  2   20
```

**Comment by rhijmans** [comment]
Thank you for reporting, That is really bad. I believe it works again.

```
library(terra)
x <- rast(matrix(0, 5,5))
x[2,2] <- 20
x[1,2] <- 15
p <- terra::as.points(x)
names(x) <- "data"
names(p) <- "data"
x <- terra::classify(x, matrix(c(0, NA), ncol = 2, byrow = TRUE), right = NA)
y <- p[p$data > 0]
terra::extract(x, y, cells = TRUE, xy=T)
#  ID data cell   x   y
#1  1   15    2 0.3 0.9
#2  2   20    7 0.3 0.7
terra::extract(x, y)
#  ID data
#1  1   15
#2  2   20

```

**Comment by ChrisJones687** [comment]
Do you already have a test suite in place. I would be happy to contribute some tests and set up the CI for having it autorun with GitHub Actions on push or PRs. This is what we are doing with the package I manage.

**Comment by rhijmans** [comment]
That would be great; even if it had one or two trivial tests. The package uses `tinytest` for unit testing, but not enough is covered. And I do not want to make `R CMD check` testing take much longer. So further tests could be done through the mechanism you suggest. I have additional tests that flag if things break but not always when output changes, as in this case.
