### ISSUE TITLE
print name of invalid file name

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/terra#219]
https://github.com/rspatial/terra/blob/e3eb789e0dd47da1a6de2f8490efdc180a1a1607/R/rast.R#L135

This code returns this message
Error: [rast,character] provide a valid filename.

Would it be possible have it return the invalid file name?

**Comment by rhijmans** [comment]
Changed to the clearer message: `filename is empty. Provide a valid filename`

**Comment by GeraldCNelson** [comment]
Thanks!

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

From: Robert Hijmans ***@***.***>
Reply-To: rspatial/terra ***@***.***>
Date: Wednesday, May 19, 2021 at 4:44 PM
To: rspatial/terra ***@***.***>
Cc: Gerald Nelson ***@***.***>, Author ***@***.***>
Subject: Re: [rspatial/terra] print name of invalid file name (#219)


Changed to the clearer message: filename is empty. Provide a valid filename
