### ISSUE TITLE
Unable to read SDSs from a particular MODIS product

### ISSUE THREAD

**Issue by EmanuelCastanho** [rspatial/terra#222]
I am reading MODIS products from 2001 to 2020 and in some of these products I have gotten the following output with error:

```
class: SpatRasterDataset 
subdatasets : 12 
Error: [[] layer number for R, G, B, cannot exceed the number of layers
```

Some of these products include:
MCD18A1.A2002186.h15v05.061.2020104224313.hdf 
MCD18A1.A2020364.h15v05.061.2021025173131.hdf

Is this a limitation of terra package? Because I can open this products in Panoply and using MODIS+rgdal packages in R.

Using terra package:
```
library(terra)

HDFproduct <- "ModisProductsOriginal/MCD18A1.A2020364.h15v05.061.2021025173131.hdf"

SDSs <- sds(HDFproduct)
SDS <- SDSs[8]
```

Using MODIS+rgdal packages:
```
library(MODIS)
library(rgdal)

HDFproduct <- "ModisProductsOriginal/MCD18A1.A2020364.h15v05.061.2021025173131.hdf"

SDSs <- getSds(HDFproduct)

SDS <- readGDAL(SDSs$SDS4gdal[8], as.is = TRUE)
```

I would like to know more about this error and how to solve it without having to migrate to another package.

**Comment by rhijmans** [comment]
It sounds like a but, but not like an inherent limitation. Can you share a file?

**Comment by rhijmans** [comment]
Based on the error message I was able to fix this, I think. But it would still be great to have an example file to verify this and to understand why it happened.

**Comment by EmanuelCastanho** [comment]
Here is one of the files: https://drive.google.com/drive/folders/1RG3JkXlbaotBax-h5lEMT7lEn-ObwWsD?usp=sharing

Yes, it is a display error.
I am testing my code with MODIS+rgdal but the processing takes longer compared to terra package, so it would be great to know how this bug happens.
