### ISSUE TITLE
Problem with development version - Probably installation

### ISSUE THREAD

**Issue by EmanuelCastanho** [rspatial/terra#225]
I've been reading the README and in the **Installation** section, if I understand it correctly, there are two quick methods to install the terra package:
`install.packages("terra")`
`install.packages('terra', repos='https://rspatial.r-universe.dev')`

I tried the installation of both (one at a time) with success, however the second method shows me an error when reading a MODIS HDF product. Do I need to install GDAL first? If yes, perhaps this should be indicated in the documentation before the: _The easiest way to use the development version..._

I am using macOS Catalina+RStudio and my script is this one:
```
library(terra)
HDFproduct <- "ModisProductsOriginal_Test/MCD18A1.A2020364.h15v05.061.2021025173131.hdf"
SDSs <- sds(HDFproduct)
```

When I run it with the second installation method, I have the following output in RStudio Console:
```
Error: [sds] cannot read from PATH/ModisProductsOriginal_Test/MCD18A1.A2020364.h15v05.061.2021025173131.hdf
In addition: Warning message:
PATH/ModisProductsOriginal_Test/MCD18A1.A2020364.h15v05.061.2021025173131.hdf' not recognized as a supported file format. (GDAL error 4)
```

**Comment by rhijmans** [comment]
Thank you for pointing this out.  On a Mac, when I use CRAN I get

```
install.packages("terra")
library(terra)
g <- gdal(drivers=TRUE)
grep("HDF", g[,1], value=TRUE)
#[1] "HDF4"      "HDF4Image" "HDF5"      "HDF5Image"
```

But when I use r-universe to install I get:

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
library(terra)
g <- gdal(drivers=T)
grep("HDF", g[,1], value=TRUE)
#[1] "HDF5"      "HDF5Image"
```

In other words, the `r-universe` OSX build does not include the HDF4 plugin for GDAL.  Perhaps @jeroen can comment.

**Comment by jeroen** [comment]
Our build system for macos is based off homebrew. It looks like their GDAL does indeed not enable hdf4: https://github.com/homebrew/homebrew-core/blob/master/Formula/gdal.rb

In fact it seems homebrew does not even have a hdf4 formula.

**Comment by EmanuelCastanho** [comment]
For MODIS products like the MCD18A1 it is important to have a HDF4 driver. So, maybe it is important to refer this in the README documentation.

**Comment by rhijmans** [comment]
It is in the README now. Unfortunately it remains an important driver because of the MODIS data, and other NASA data as well, I believe. Jeroen: thanks a million for R-universe --- that is a game changer; even at this initial stage.

**Comment by jeroen** [comment]
I have updated the mac server to gdal 3.3.2 and added hdf4 support:

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
library(terra)
g <- gdal(drivers=T)
grep("HDF", g[,1], value=TRUE)
##[1] "HDF4"      "HDF4Image" "HDF5"      "HDF5Image"
```
