### ISSUE TITLE
The `hillShade` function in terra

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#226]
The **raster** package has the  `hillShade` function, which works based on the outputs of the `terrain` function. However, I was unable to find its counterpart in the **terra** package (nothing is mentioned on https://rspatial.github.io/terra/reference/terra-package.html). @rhijmans are there any plans to add this function to **terra**?

``` r
library(terra)
#> terra version 1.2.10
data(nz_elev, package = "spDataLarge")
nz_elev = rast(nz_elev)

nz_slope = terrain(nz_elev, v = "slope")
nz_aspect = terrain(nz_elev, v = "aspect")

# hillshade?
library(raster)
#> Loading required package: sp
nz_hillshade = hillShade(raster(nz_slope),
                         raster(nz_aspect))
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded datum Unknown based on GRS80 ellipsoid in Proj4
#> definition

#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj
#> = prefer_proj): Discarded datum Unknown based on GRS80 ellipsoid in Proj4
#> definition
plot(nz_hillshade)
```

![](https://i.imgur.com/goTDq46.png)

<sup>Created on 2021-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rhijmans** [comment]
It was implemented in `shade` but not exported  (I think because I wanted to first make `hillShade` a generic in `raster`. I may still do that and change the name in terra to `hillShade` as well.  It is exported now.

       s <- shade(nz_slope, nz_aspect)

**Comment by Nowosad** [comment]
Thank you. I have added this function to the documentation - https://github.com/rspatial/terra/pull/230
