### ISSUE TITLE
Minor issue: terraOptions fails if terra is not attached

### ISSUE THREAD

**Issue by karldw** [rspatial/terra#229]
I noticed that if I call `terra::terraOptions()` without attaching terra (with `library(terra)`), I get an error. I think maybe `.create_options()` should be in `.onLoad()` instead of `.onAttach()`?

``` r
terra::terraOptions(progress = 0)
#> Error in terra::terraOptions(progress = 0): trying to get slot "ptr" from an object of a basic class ("NULL") with no slots
```

https://github.com/rspatial/terra/blob/e870d64eee42c4e6a34ed9190f60e34498ccaabb/R/zzz.R#L18-L34

**Comment by rhijmans** [comment]
> maybe .create_options() should be in .onLoad() instead of .onAttach()?

That is what I would think too, but I did not get it work like that. I took we a while to get `terra::rast` to work (see https://github.com/rspatial/terra/issues/23)

With the last commit, I get 

```
#Type 'demo()' for some demos, 'help()' for on-line help, or
#'help.start()' for an HTML browser interface to help.
#Type 'q()' to quit R.

terra::terraOptions(progress = 0)
terra::terraOptions()
#memfrac   : 0.6
#tempdir   : C:/temp/Rtmpk7YxZ6
#datatype  : FLT4S
#progress  : 0
#todisk    : FALSE
#verbose   : FALSE
```
