### ISSUE TITLE
rast doesn't work unless terra is loaded

### ISSUE THREAD

**Issue by CGMossa** [rspatial/terra#23]
This is a small discovery I've made:
``` r

# Create a SpatRaster from a file
f <- system.file("exdata/test.tif", package="terra")
r <- terra::rast(f)
#> Error: (rast) cannot read from C:/[redacted]/R/win-library/3.6/terra/exdata/test.tif
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But this works fine if one has a `library(terra)`. 

I'm not sure why this happens though.

**Comment by rhijmans** [comment]
Thanks for reporting this, Without calling `library(terra)`, you *can* do 

```
terra::rast()
#class       : SpatRaster 
#dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 
#data sources: no data
#names       : lyr.1 
```
But not, as you point out, 

```
f <- system.file("exdata/test.tif", package="terra")
terra::rast(f)
```

This is because GDAL does not get initialized. When terra loads, this happens:

```
x <- terra::SpatRaster$new()
x$spatinit()
```
And now you can do

```
terra::rast(f)
#class       : SpatRaster 
#dimensions  : 115, 80, 1  (nrow, ncol, nlyr)
#resolution  : 40, 40  (x, y)
#extent      : 178400, 181600, 329400, 334000  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.237,50.0087,465.658,-0.406857,0.350733,-1.87035,4.0812 +units=m +no_defs  
#data source : C:/soft/R/R-3.6.3/library/terra/exdata/test.tif 
#names       :    test 
#min values  : 128.434 
#max values  : 1805.78 
```

I need to see if there is a clever way to avoid this.

**Comment by mdsumner** [comment]
Isn't it a matter of .onLoad() vs .onAttach()?

**Comment by rhijmans** [comment]
Maybe, you would think, but I get an error with `.onLoad(terra::SpatRaster$new()$spatinit())`

**Comment by mdsumner** [comment]
Ah ok, I'll have a look see if I can find anything

**Comment by rhijmans** [comment]
It works now, with the package having `.onLoad` *and* `onAttach`, and with `loadModule("spat", TRUE)` in `.onLoad` as well as stand-alone. Not sure if some of this is redundant, or bad.

**Comment by rhijmans** [comment]
I rolled that back, giving errors with R CMD check. 
This now works in a different way --- by registering the drivers at the C++ side, on the first call to GDAL.
```
f <- system.file("exdata/test.tif", package="terra")
r <- terra::rast(f)
```
But it does not help very much, because the S4 generics for terra objects are not registered --- so you cannot do much with `r` (the only method that I found to be working is `show`.

**Comment by rhijmans** [comment]
This now works; but is via a hack. I have yet to find a good way to do this (calling .init() onLoad or thereabouts) that passes R CMD check.
