### ISSUE TITLE
GDAL Error 4: Too many open files

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#231]
Hi,

I was trying to create a SpatRaster file from a set of ~100 000 files, when I got the following error message:

```
Error: [*] cannot read from /data/IMERG_V06B/3B-HHR-GIS.MS.MRG.3IMERG.20040927-S050000-E052959.0300.V06B.tif
In addition: Warning message:
In e1@ptr$arith_numb(e2, oper, FALSE, opt) :
  GDAL Error 4: /data/IMERG_V06B/3B-HHR-GIS.MS.MRG.3IMERG.20040927-S050000-E052959.0300.V06B.tif: Too many open files
```

The previous file actually exists within the hard disk in the specified location.

By using `ulimit -n` I realised that the maximum number of open files  for the current user in my system is 1024. Yesterday I solved the problem by modifying the hard and soft limits in the `/etc/security/limits.conf` file. However, today I'm facing the same error message.

I there any way to change such a limit within the R session or should I have to make another change at the operative system level?

Thanks in advance for any help,

Mauricio

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=es_CL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] hydroTSM_0.6-0      xts_0.12.1          zoo_1.8-9          
[4] hydroGISterra_0.1.1 terra_1.2-10        sf_0.9-8           

loaded via a namespace (and not attached):
 [1] automap_1.0-14     Rcpp_1.0.6         plyr_1.8.6         pillar_1.6.1      
 [5] compiler_4.1.0     class_7.3-19       tools_4.1.0        gstat_2.0-7       
 [9] lifecycle_1.0.0    tibble_3.1.2       lattice_0.20-44    pkgconfig_2.0.3   
[13] rlang_0.4.11       DBI_1.1.1          parallel_4.1.0     e1071_1.7-6       
[17] dplyr_1.0.6        raster_3.4-10      generics_0.1.0     vctrs_0.3.8       
[21] classInt_0.4-3     grid_4.1.0         tidyselect_1.1.1   reshape_0.8.8     
[25] spacetime_1.2-4    glue_1.4.2         R6_2.5.0           pbapply_1.4-3     
[29] fansi_0.4.2        foreign_0.8-81     sp_1.4-5           purrr_0.3.4       
[33] magrittr_2.0.1     intervals_0.15.2   codetools_0.2-18   ellipsis_0.3.2    
[37] units_0.7-1        maptools_1.1-1     assertthat_0.2.1   utf8_1.2.1        
[41] KernSmooth_2.23-20 proxy_0.4-25       FNN_1.1.3          crayon_1.4.1      
```

Regarding my GDAL version:

```
 library(rgdal)
Loading required package: sp
rgdal: version: 1.5-23, (SVN revision 1121)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 3.2.1, released 2020/12/29
Path to GDAL shared files: /usr/share/gdal
GDAL binary built with GEOS: TRUE 
Loaded PROJ runtime: Rel. 7.2.1, January 1st, 2021, [PJ_VERSION: 721]
Path to PROJ shared files: /home/hzambran/.local/share/proj:/usr/share/proj
PROJ CDN enabled: FALSE
Linking to sp version:1.4-5
To mute warnings of possible GDAL/OSR exportToProj4() degradation,
use options("rgdal_show_exportToProj4_warnings"="none") before loading rgdal.
```

**Comment by rhijmans** [comment]
I do not have experience with changing this limit on linux or other OS. You can use `system` to run shell commands from R.
Either way, it would be nice to avoid this issue from happening. When terra processes a SpatRaster it first opens all files, then reads one or more chunks of data, and then closes all files. A use-case like yours may require another approach. The only general alternative approach for when there are many files that I can think of ,is to open-read-close a file for each chunk. That could slow things down considerably, especially with so many files (unless they are very small and one read suffices), but it should work.

**Comment by rhijmans** [comment]
I wonder what happens if you make a `vrt` 

`vrt(x, filename="test.vrt", overwrite=FALSE)`

Where `x` is a vector of filenames. And then do  

`r <- rast("test.vrt") `

For `terra` this is now one file, and whether processing it will fail depends on how GDAL manages it in the background.

**Comment by hzambran** [comment]
Thank you very much for your prompt reply Robert.

I just tried the `vrt` function you mentioned, but I got the same error message:
```

vrt(x=fnames, filename="/home/hzambran/test.vrt", overwrite=FALSE)
Error: [] cannot open /data/IMERG_V06B/3B-HHR-GIS.MS.MRG.3IMERG.20010122-S053000-E055959.0330.V06B.tif
In addition: Warning message:
/data/IMERG_V06B/3B-HHR-GIS.MS.MRG.3IMERG.20010122-S053000-E055959.0330.V06B.tif: Too many open files (GDAL error 4) 
```

So far, the use of `system("ulimit -n 300000")` seems the best option. 

Because all the files have the same spatial properties (extent, xres, yres, crs). would is be any advantage in using a *SpatRasterDataset*?

**Comment by rhijmans** [comment]
The `SpatRasterDataset` is for sub-datasets. These may be present within a file (common in HDF and NETCDF files). It can also be used if you have multiple files (`SpatRaster`s) with multiple layers that you want together but separated (e.g. daily rainfall and daily temperature). Turning single layer `SpatRaster`s into a `SpatRasterDataSet` would be rather inefficient. Also, there currently not that much you can do with a `SpatRasterDataSet` (they can be used in e.g. `lapp`).

**Comment by hzambran** [comment]
Thank you very much for your comments about `SpatRasterDataset`s

Just in case it e useful for somebody else: when using `system("ulimit -n 300000")` at the beginning of my script I get the error mentioned at the beginning, while if I execute `ulimit -n 300000` from the system console and then run R, I don't get the error message. More tests are needed..

Thank you very much for all the help

**Comment by mdsumner** [comment]
oh cool, ta - this issue makes VRT pretty unusable for scaling things up - I'll have another look now

**Comment by rhijmans** [comment]
This has now been fixed.
