### ISSUE TITLE
sqlite3 missing in SystemRequirements

### ISSUE THREAD

**Issue by bastistician** [rspatial/terra#232]
Without `sqlite-dev[el]`, installing **terra** from source fails with

```
checking for proj.h... yes
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package 'terra'
```

In Ubuntu, `libsqlite3-dev` is necessarily installed as a dependency of `libproj-dev`, but not in, e.g., Alpine Linux or RPM-based distros.

I think `sqlite3` should be added to the SystemRequirements field in the DESCRIPTION.
See https://github.com/r-spatial/sf/pull/1546 for a related patch in **sf**.

**Comment by rhijmans** [comment]
Thank you very much!
