### ISSUE TITLE
Issues with reading in ESRI grid (adf) file with rast

### ISSUE THREAD

**Issue by jullee** [rspatial/terra#234]
I posted full details on StackOverflow [here](https://gis.stackexchange.com/questions/398061/reading-rasters-in-r-using-terra-package?noredirect=1#comment651664_398061)

But a quick summary: I am having trouble reading an adf file (reads fine with raster package) with terra rast command. It seems to convert values in the file to factor?

**Comment by rhijmans** [comment]
GDAL says the file has a "raster attribute table" so both terra and raster interpret it as categorical. But in cases like this, where the categories are `"VALUE"` and `"COUNT"` it is probably best to ignore that.  I think ArcInfo GRID does that for all integer grids. I can't remember, I had not seen one for a while.  `raster` had some logic for that but still returned a categorical RasterLayer. `terra` now treats it as numeric.
