### ISSUE TITLE
Raster and Terra: function "focal" fails: Evaluation error: could not find function "fun".

### ISSUE THREAD

**Issue by gdurner** [rspatial/terra#236]
I am attempting to run the R focal function in a loop to find the minimum and maximum values in a 3X3 neighborhood for multiple rasters.

I receive the same error in `raster` and in `terra`.  `focal` runs correctly for the first raster, but fails in subsequent rasters.  I receive the following message for the second iteration of the loop. My code:  

```
files <- c("USGS_AK5M_AK_NPRA_Recollect_IfSAR_2018_D18_DTM_n7115w15645P.tif",
               "USGS_AK5M_AK_NPRA_Recollect_IfSAR_2018_D18_DTM_n7115w15700P.tif")
m <- matrix(1, nrow=3, ncol=3)

library(raster)
for (b in files){
    dem <- raster(b)
    focalmax <- focal(dem, w=m, fun = max)
    focalmin <- focal(dem, w=m, fun = min)
}

#Error in .focal_fun(values(x), w, as.integer(dim(out)), runfun, NAonly) : 
#  Evaluation error: could not find function "fun".
```

Both geotiffs are in the attached [zip file](https://github.com/rspatial/terra/files/6580123/IFSAR.zip)

Thank you for any assistance that you can provide.

George

**Comment by rhijmans** [comment]
I assume you are doing something more than that, because it works for me. Here with `terra`. 
A minor change to your script is that I do not overwrite the output in the loop, but that should not affect what you report. 

```
files <- list.files()
m <- matrix(1, nrow=3, ncol=3)

library(terra)
out <- list()
for (i in 1:length(files)){
   dem <- rast(files[i])
   fmx <- focal(dem, w=m, fun = max)
   fmn <- focal(dem, w=m, fun = min)
   out[[i]] <- c(fmn, fmx)
}

out
#[[1]]
#class       : SpatRaster 
#dimensions  : 5649, 2184, 2  (nrow, ncol, nlyr)
#resolution  : 5, 5  (x, y)
#extent      : -101470, -90550, 2362835, 2391080  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=aea +lat_0=50 +lon_0=-154 +lat_1=55 +lat_2=65 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
#sources     : memory  
#              memory  
#names       : USGS_AK5M_AK_NP~TM_n7115w15645P, USGS_AK5M_AK_NP~TM_n7115w15645P 
#min values  :                               0,                               0 
#max values  :                        13.99483,                        14.22610 

#[[2]]
#class       : SpatRaster 
#dimensions  : 5654, 2204, 2  (nrow, ncol, nlyr)
#resolution  : 5, 5  (x, y)
#extent      : -110655, -99635, 2363200, 2391470  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=aea +lat_0=50 +lon_0=-154 +lat_1=55 +lat_2=65 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
#sources     : memory  
#              memory  
#names       : USGS_AK5M_AK_NP~TM_n7115w15700P, USGS_AK5M_AK_NP~TM_n7115w15700P 
#min values  :                               0,                               0 
#max values  :                        21.29380,                        21.96833 
```
 

```

**Comment by gdurner** [comment]
Hello Robert,

I appreciate your reply.  I did provide you with an abbreviated script, so I'll look further into that.

Best regards,

George Durner
________________________________
From: Robert Hijmans ***@***.***>
Sent: Saturday, June 5, 2021 4:12 PM
To: rspatial/terra ***@***.***>
Cc: Durner, George M ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [rspatial/terra] Raster and Terra: function "focal" fails: Evaluation error: could not find function "fun". (#236)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I assume you are doing something more than that, because it works for me. Here with terra.
A minor change to your script is that I do not overwrite the output in the loop, but that should not affect what you report.

files <- list.files()
m <- matrix(1, nrow=3, ncol=3)

library(terra)
out <- list()
for (i in 1:length(files)){
   dem <- rast(files[i])
   fmx <- focal(dem, w=m, fun = max)
   fmn <- focal(dem, w=m, fun = min)
   out[[i]] <- c(fmn, fmx)
}

out
#[[1]]
#class       : SpatRaster
#dimensions  : 5649, 2184, 2  (nrow, ncol, nlyr)
#resolution  : 5, 5  (x, y)
#extent      : -101470, -90550, 2362835, 2391080  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=aea +lat_0=50 +lon_0=-154 +lat_1=55 +lat_2=65 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs
#sources     : memory
#              memory
#names       : USGS_AK5M_AK_NP~TM_n7115w15645P, USGS_AK5M_AK_NP~TM_n7115w15645P
#min values  :                               0,                               0
#max values  :                        13.99483,                        14.22610

#[[2]]
#class       : SpatRaster
#dimensions  : 5654, 2204, 2  (nrow, ncol, nlyr)
#resolution  : 5, 5  (x, y)
#extent      : -110655, -99635, 2363200, 2391470  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=aea +lat_0=50 +lon_0=-154 +lat_1=55 +lat_2=65 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs
#sources     : memory
#              memory
#names       : USGS_AK5M_AK_NP~TM_n7115w15700P, USGS_AK5M_AK_NP~TM_n7115w15700P
#min values  :                               0,                               0
#max values  :                        21.29380,                        21.96833

**Comment by rhijmans** [comment]
I now notice that the error message says that `focal` is looking for ` runfun` but that it is not available (on a compute node?).
