### ISSUE TITLE
write to filename in summarize methods

### ISSUE THREAD

**Issue by jnephin** [rspatial/terra#238]
I accidentally included a filename to save the results of terra::mean() to file when converting some code from raster to terra. I noticed that the filename option does nothing and that overwrite affects the results but no error is generated. 

```
# create a raster
r <- rast(nrows = 150, ncols = 150, nlyr = 1)
values(r) <- runif(150 * 150 * 1)

# Create multiple layers to calculate the mean across
s <- c( r, r^2, r*-2 )

# Calculate mean
m <- terra::mean(s)
m

# Calculate mean with filename option and overwrite=TRUE
mt <- terra::mean(s, filename="out.tiff", overwrite=TRUE)
mt

# Calculate mean with filename option and overwrite=FALSE
mf <- terra::mean(s, filename="out.tiff", overwrite=FALSE)
mf
```

Raster m, mt and mf all differ. Raster m has the correct mean values of the 3 raster layers.

**Comment by rhijmans** [comment]
Thanks for reporting this.  `mean` had no argument `overwrite`, but you can combine `SpatRaster`(s) and `numeric`, `integer` and `logical` values. Therefore, `overwrite=TRUE` was interpreted as a `1`, while filename was ignored. Illustrated below:

r <- rast(nrows = 150, ncols = 150, nlyrs = 1, vals=0)
mean(r)
#min value   :    0 
#max value   :    0 

mean(r, overwrite=TRUE)
#min value   :  0.5 
#max value   :  0.5 

mean(r, overwrite=100)
#min value   :   50 
#max value   :   50 
 
I changed this such that (a) you can provide `filename`, `overwrite` and `wopt`. If there are other arguments that cannot be interpreted as a `SpatRaster` or a numerical value an error is given. A logical is a edge-case, but I am allowing it as this is standard behavior in R and other languages. So now you get

```
mean(r)
#min value   :    0 
#max value   :    0 

mean(r, overwrite=TRUE)
#min value   :    0 
#max value   :    0 

mean(r, 10)
#min value   :    5 
#max value   :    5 

mean(r, "abc")
#Error: [mean] invalid argument(s)

mean(r, test=10)
#Error: [mean] additional arguments cannot be names (except for `filename`, `overwrite` and `wopt`)

mean(r, filename="test.tif", overwrite=TRUE)
#class       : SpatRaster 
#dimensions  : 150, 150, 1  (nrow, ncol, nlyr)
#resolution  : 2.4, 1.2  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : test.tif 
#name        : mean 
#min value   :    0 
#max value   :    0 
```

Which is much better.
