### ISSUE TITLE
FR: add "pairs" to the terra::adjacent() method for SpatRaster

### ISSUE THREAD

**Issue by kbvernon** [rspatial/terra#239]
Hi, would it be possible to add a `pairs` argument to the `terra::adjacent()` method for SpatRaster? It would be nice to have the option of returning a from-to matrix as with `raster::adjacent()`. 

Thanks!

**Comment by rhijmans** [comment]
Good suggestion, thanks. Done in version 1.2-18: 

```
library(raster)
r <- raster(nrows=10, ncols=10)
adjacent(r, cells=c(1, 55), directions=4, pairs=TRUE) 
#     from to
#[1,]    1 10
#[2,]   55 54
#[3,]    1  2
#[4,]   55 56
#[5,]   55 45
#[6,]    1 11
#[7,]   55 65

library(terra)
# terra version 1.2.18
rr <- rast(r)
adjacent(rr, cells=c(1, 55), directions=4, pairs=TRUE) 
#     from to
#[1,]    1 10
#[2,]    1  2
#[3,]    1 11
#[4,]   55 45
#[5,]   55 54
#[6,]   55 56
#[7,]   55 65

```

**Comment by kbvernon** [comment]
Awesome! Thanks for doing that. Looking forward to working with `terra` more.

**Comment by kbvernon** [comment]
Hi @rhijmans, I haven't learned all the correct Github etiquette yet, so I'm not sure if I should open another issue since this is closed, but I'm getting some odd behavior when I install the dev version now:

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
library(terra)
rr <- rast(nrows = 10, ncols = 10)

adjacent(rr, cells = c(1, 55), directions = 4, pairs = TRUE)
# from to
# [1,]    2 10
# [2,]    2  2
# [3,]    2 11
# [4,]   56 45
# [5,]   56 54
# [6,]   56 56
# [7,]   56 65
```

You see that it is bumping the _from_ cells up by one. I tried running the internal code you changed line by line to see if I could find the issue, and this weird thing happened:

```
v <- rr@ptr$adjacent(c(1, 55)-1, directions="4", include=FALSE)

v
# [1] NaN   9   1  10  44  53  55  64
```

Pretty sure, `v` is supposed to be a list, so I'm a little mystified why your `do.call(cbind, v)` is not throwing an error when I run `adjacent()`. 

I'm afraid I have zero grasp of Rcpp or C++ code, so I can't really diagnose this if the problem is there. Sorry.

Here is my session info in case it's something on my end:

```
sessionInfo()
# R version 4.0.2 (2020-06-22)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19042)
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
# [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
# [5] LC_TIME=English_United States.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] terra_1.2-18
# 
# loaded via a namespace (and not attached):
#   [1] compiler_4.0.2   tools_4.0.2      sp_1.4-5         yaml_2.2.1       Rcpp_1.0.6      
# [6] raster_3.4-10    codetools_0.2-16 grid_4.0.2       lattice_0.20-41 
```

**Comment by rhijmans** [comment]
This works, and I could have re-opened the issue. But I think there is no need as it works again.

```
library(terra)
#terra version 1.2.18
rr <- rast(nrows = 10, ncols = 10)

adjacent(rr, cells = c(1, 55), directions = 4, pairs = TRUE)
#     from to
#[1,]    1 10
#[2,]    1  2
#[3,]    1 11
#[4,]   55 45
#[5,]   55 54
#[6,]   55 56
#[7,]   55 65
```

I did some additional work on the function, both streamlining it for performance (returning a vector instead of a list), and adding the option to provide an adjacency matrix; and that introduced the bug. The underlying issue is that R uses 1-based indexing whereas C uses 0-based indexing.

**Comment by kbvernon** [comment]
That's great. Thank you! And thanks for being so generous with your time.
