### ISSUE TITLE
Suggest transitioning CRS/crs to WKT2_2019 

### ISSUE THREAD

**Issue by rsbivand** [rspatial/terra#24]
If dropping +datum=, +nadgrids= and +towgs84= doesn't matter, you may prefer to ignore this, but `OSRexportToProj4()` at https://gdal.org/api/ogrspatialref.html#classOGRSpatialReference_1a271b3de4caf844135b0c61e634860f2b
says:

> Use of this function is discouraged. Its behaviour in GDAL >= 3 / PROJ >= 6 is significantly different from earlier versions. In particular +datum will only encode WGS84, NAD27 and NAD83, and +towgs84/+nadgrids terms will be missing most of the time. PROJ strings to encode CRS should be considered as a legacy solution. Using a AUTHORITY:CODE or WKT representation is the recommended way.

Since **terra** is new, users will not have problems adapting; **raster** also needs to consider moving at your earliest convenience.

Good to see `-ge 6` in the github version of `configure.ac`, the CRAN 0.5-2 release is broken on released PRØJ 7.0.0.

**Comment by rhijmans** [comment]
Thank you for your help with this. `terra` uses wkt for coordinate transformation (and proj for display). The same is under development in `raster`
