### ISSUE TITLE
cores argument fails in app function

### ISSUE THREAD

**Issue by BastienFR** [rspatial/terra#240]
Hello,

It seems using the `cores` argument in the `app` function produce erroneous raster.  See example:

### Preparing the data
I downloaded a raster because it's simple and I had the code already. 

```
library(terra)

the_ras <- paste(tempdir(), "/vwnd.10m.2015.nc", sep = "")

utils::download.file("ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/vwnd.10m.2015.nc",
                     the_ras, 
                     method = "auto", 
                     mode = "wb", 
                     cacheOK = TRUE, 
                     extra = getOption("download.file.extra"))

ras_terra <- rast(the_ras)
```

### making the cell calculations:

```
fc_stat <- function(xx){
  the_max <- max(xx)
  the_min <- min(xx)
  the_mean <- mean(xx)
  
  c(the_max, the_min, the_mean)
}

test_1c <- app(ras_terra, fc_stat, cores=1)
test_8c <- app(ras_terra, fc_stat, cores=8)
```

### plotting the results:

`plot(test_1c)`

The result is as expected:

![image](https://user-images.githubusercontent.com/10979480/120799550-e22fe080-c50c-11eb-8583-5f208c393474.png)

`plot(test_8c)`

The result seems corrupted

![image](https://user-images.githubusercontent.com/10979480/120799607-f542b080-c50c-11eb-808c-65ce517da2a9.png)

**Comment by rhijmans** [comment]
Thank you. I seems that I never tested `app` with multiple layer output and `cores > 1`. I now the get the same result with `cores=2` as with `cores=1`
