### ISSUE TITLE
extract with option xy=TRUE

### ISSUE THREAD

**Issue by jnephin** [rspatial/terra#241]
There is a bug in extract(). If you set xy=TRUE, the results are incorrect. It appears like the result needs to be transposed. 

````
f <- system.file("ex/meuse.tif", package="terra")
r <- rast(f)

xy <- cbind(179000, 330000)
xy <- rbind(xy-100, xy, xy+1000)

extract(r, xy, xy=TRUE)
extract(r, xy, xy=FALSE)
````

**Comment by rhijmans** [comment]
You are right. This was fixed in the development version and I now get 

```
extract(r, xy, xy=TRUE)
#  test      x      y
#1  378 178900 329900
#2  251 179000 330000
#3  208 180000 331000

extract(r, xy, xy=FALSE)
#  test
#1  378
#2  251
#3  208
```
But I need to do some more testing before I send a new version to CRAN next week.

You can install the development version with 
`install.packages('terra', repos='https://rspatial.r-universe.dev')`

**Comment by Rapsodia86** [comment]
What was wrong here? I am getting exactly the same results as @rhijmans 
> library(terra) #my version is terra_1.1-4
> f <- system.file("ex/test.tif", package="terra")
> r <- rast(f)
> 
> xy <- cbind(179000, 330000)
> xy <- rbind(xy-100, xy, xy+1000)
> 
> extract(r, xy, xy=TRUE)
  test      x      y
1  378 178900 329900
2  251 179000 330000
3  208 180000 331000
> extract(r, xy, xy=FALSE)
  test
1  378
2  251
3  208
