### ISSUE TITLE
terra::focal: unexpected behavior for lon/lat raster

### ISSUE THREAD

**Issue by amarbler** [rspatial/terra#242]
Hi,

I recently switched from the raster to terra package and observed the following (for me) unexpected behavior using terra::focal:

```
library(terra)
library(raster)

xx = terra::rast(nrows=3, ncols=3)
terra::values(xx)<- 1:ncell(xx)
xxx = terra::focal(xx, w = 3, fun = "max", expand = T, fillvalue = NA, na.rm = T)
pdf("terra_test.pdf", height = 3, width = 8)
par(mfrow=c(1, 2))
plot(xx, legend = F, axes = F, main = "Terra Original"); text(xx)
plot(xxx, legend = F,  axes = F, main = "Terra Focal"); text(xxx)
dev.off()
```
![terra_focal](https://user-images.githubusercontent.com/48681651/120924219-cd04ae80-c6d2-11eb-9bd6-1b137ec6ab48.png)

For a lon lat raster spanning -180° west to 180° east I would expect the same behavior as in the raster package, i.e. "left" and "right" sides of the globe are the same place:

```
yy = raster::raster(nrows=3, ncols=3)
raster::values(yy)<- 1:ncell(yy)
yyy = raster::focal(yy, w = matrix(1, 3, 3), fun = max, pad = T, padValue = NA, na.rm = T)
pdf("raster_test.pdf", height = 3, width = 8)
par(mfrow=c(1, 2))
plot(yy, legend = F, axes = F, bty="n", box = F, main = "Raster Original"); text(yy)
plot(yyy, legend = F, axes = F, bty="n", box = F, main = "Raster Focal"); text(yyy)
dev.off()
```
![raster_focal](https://user-images.githubusercontent.com/48681651/120924257-089f7880-c6d3-11eb-88f4-b15e685c9ba6.png)

**Comment by rhijmans** [comment]
Thanks for pointing that out. Fixed now, sorry for the delay.

**Comment by amarbler** [comment]
Thanks!
