### ISSUE TITLE
focal function returns unexpected results using terra

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#243]
I have tried to use the Sobel filter using **raster** and **terra** objects. The result for **raster** seems ok, while **terra**'s returns very large values on the borders of the input data. 

A reproducible example is attached:

``` r
library(raster)
#> Loading required package: sp
library(terra)
#> terra version 1.1.17

srtm_path = system.file("raster/srtm.tif", package = "spDataLarge")
srtm_path
#> [1] "/home/jn/R/x86_64-redhat-linux-gnu-library/4.0/spDataLarge/raster/srtm.tif"

# works well
srtm_raster = raster(srtm_path)
srtm_raster_sobel = focal(srtm_raster, 
                          w = matrix(c(1, 2, 1, 0, 0, 0, -1, -2, -1) / 4, nrow = 3))
plot(srtm_raster_sobel)
```

![](https://i.imgur.com/DViLjAb.png)

``` r

# extreme values at the borders of the output
srtm_terra = rast(srtm_path)
srtm_terra_sobel = focal(srtm_terra, 
                         w = matrix(c(1, 2, 1, 0, 0, 0, -1, -2, -1) / 4, nrow = 3))
plot(srtm_terra_sobel)
```

![](https://i.imgur.com/4buKiut.png)

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rhijmans** [comment]
You get the expected result when you do this 

      w = matrix(c(1, 2, 1, 0, 0, 0, -1, -2, -1) / 4, nrow = 3)
      tsob1 = focal(srtm_terra, w, na.rm=FALSE)
      tsob2 = focal(srtm_terra, w, expand=TRUE)

With a filter like this `na.rm=TRUE` (the default in `terra`) won't work well; and perhaps the default in `raster::focal`  (and expected in R) of `na.rm=FALSE` is more sensible. You can get the result you had with `terra` when using `raster` if you do:  

      `rsob = focal(srtm_raster, w, pad=TRUE, na.rm=TRUE)`

In `terra` there is no `pad` option, it is always done, but you can set the value to another constant than `NA`, or to the neighboring cell, with `expand=TRUE`

**Comment by Nowosad** [comment]
Thanks for the explanation @rhijmans. I am still unsure of the consequences of `na.rm=FALSE` vs `na.rm=TRUE` here, but your response solve my problem.
