### ISSUE TITLE
Keep time attribute for arithmetic operations

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#246]
I'm using  `terra_1.2-10`, and I know that the `time` function is still experimental. 

However, is there any possibility to keep the time attribute after arithmetic operations are made on  `SpatRaster` objects?  .

A reproducible example of the issue is given below:

```
s <- rast(system.file("ex/logo.tif", package="terra"))   
time(s) <- as.Date("2001-05-04") + 0:2
time(s)
# "2001-05-04 UTC" "2001-05-05 UTC" "2001-05-06 UTC"

s1 <- s+1
time(s1)
# [1] NA NA NA

s2 <- s-1
time(s2)
# [1] NA NA NA

s3 <- s*1
time(s3)
# [1] NA NA NA

s4 <- s/1
time(s4)
# [1] NA NA NA

```

Thanks in advance for any enhancement to the time management in the `terra` package.

**Comment by rhijmans** [comment]
Good idea. Now implemented. Thanks!
