### ISSUE TITLE
Layers are dropped when converting a list to a SpatRaster object

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#247]
The list below has 11 rasters, but a final raster object has only 10 layers:

``` r
library(terra)
#> terra version 1.2.18
f = system.file("ex/elev.tif", package="terra")
r = rast(f)

r_list11 = list(r, r, r, r, r, r, r, r, r, r, r)
length(r_list11)
#> [1] 11

r_terra11 = rast(r_list11)
nlyr(r_terra11)
#> [1] 10
```

<sup>Created on 2021-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rhijmans** [comment]
Thanks very much --- I think this was in the development version only, so glad you caught it before it went out to CRAN.
