### ISSUE TITLE
Installing terra (ubuntu 20.10)

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#248]
I have the following problem at installing terra (Pop!_OS 20.10 based on ubuntu 20.10):
(I have PROJ 7.1.0-1 and gdal 3.13)

checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... ERROR 1: PROJ: proj_create_from_database: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date
ERROR 1: PROJ: proj_create_from_database: cannot build projectedCRS 3857: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
ERROR 6: Cannot find coordinate operations from `' to `'
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘terra’
* removing ‘/home/alobo/R/x86_64-pc-linux-gnu-library/4.0/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpW6t4R0/downloaded_packages’

**Comment by rhijmans** [comment]
And can you install `rgdal` or `sf` ?

**Comment by rhijmans** [comment]
It is probably because of the PROJ version(s).  [Here](https://stat.ethz.ch/pipermail/r-sig-geo/2021-January/028538.html), Roget Bivand says that:

> Some field names in proj.db (the SQLite database containing the CRS  specifications) changed with EPSG v10, introduced from PROJ 7.2.0, compared to earlier EPSG database versions and PROJ versions. So you need to ensure not only that proj-bin is unique, but that all the proj-* are the same version, and that rgdal is installed against that version of PROJ. GDAL also needs to be installed against that version. Code in R packages conditions on the declared version of PROJ in the PROJ binary. Please see [this vignette](https://cran.r-project.org/web/packages/rgdal/vignettes/CRS_projections_transformations.html) which contains code for examining proj.db using RSQLite.

There is also some discussion here:  https://community.rstudio.com/t/sf-installation-issues-on-r4-0-ubuntu18-04/93667/24

**Comment by aloboa** [comment]
rgdal and raster, yes.
sf: error at installation:

```
hecking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/RtmpmWfB7i/R.INSTALL7dcc478ce703/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
```

**Comment by rhijmans** [comment]
There is also this [sf issue](https://github.com/r-spatial/sf/issues/1636)
suggesting to use ubuntugis unstable

```
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
```

**Comment by aloboa** [comment]
Regarding sf, once I install udunits, I get the same proj error as with terra.
rgdal installs, loads and works with no problems.
Do not quite understand the proj problem: AFAIK I just have 7.1.0-1 and you mention a conflict with 7.2
https://www.dropbox.com/s/jpu0bb4n3sfxcqo/Screenshot%20from%202021-06-11%2008-14-35.png?dl=0

**Comment by aloboa** [comment]
This problem is related to https://github.com/qgis/QGIS/issues/43680

The conflict is caused by the OTB installation, which has its own proj (but 7.1 !)
/home/alobo/OTB/OTB-7.3.0-Linux64/bin/proj
I realized this fact thanks to rgdal, which reports:
Path to PROJ shared files: /home/alobo/OTB/OTB-7.3.0-Linux64/share/proj

**If I remove the OTB installation and restart, the problems are solved both in QGIS and in R, and I can successfully
install terra, and sf.** The rgdal installation, which always worked, reports another proj path:
> require(rgdal)
Loading required package: rgdal
Loading required package: sp
rgdal: version: 1.5-23, (SVN revision 1121)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 3.1.3, released 2020/09/01
Path to GDAL shared files: /usr/share/gdal
GDAL binary built with GEOS: TRUE 
Loaded PROJ runtime: Rel. 7.1.0, August 1st, 2020, [PJ_VERSION: 710]
Path to PROJ shared files: /home/alobo/.local/share/proj:/usr/share/proj
PROJ CDN enabled: FALSE
Linking to sp version:1.4-5
To mute warnings of possible GDAL/OSR exportToProj4() degradation,
use options("rgdal_show_exportToProj4_warnings"="none") before loading rgdal.

Unfortunately, If I install OTB even after having installed the R packages, I go back to problems in QGIS
and rgdal reports the OTB path again. I have not tested if terra and sf work fine after the OTB installation.
I will and report back.

As I do need OTB, is not there a way to specify which proj path should be used by R packages?

**Comment by aloboa** [comment]
Seems to have been solved by including both paths in otbenv.profile:
`PROJ_LIB=/home/alobo/.local/share/proj:/usr/share/proj:/home/alobo/OTB/OTB-7.3.0-Linux64/share/proj
`
I will report back in case of problems, but we can close this ticket by now.
