### ISSUE TITLE
terra::aggregate | Suppress the progress bar?

### ISSUE THREAD

**Issue by Lachlan00** [rspatial/terra#249]
Is there a way to suppress the progress bar when using `terra::aggregate`? I'm running the function in a loop and the functions progress bar is interpreting the progress bar I'm generating.
 
<img width="938" alt="Screen Shot 2021-06-12 at 5 59 44 pm" src="https://user-images.githubusercontent.com/17243322/121769637-14de7680-cba8-11eb-9846-0783b5a96d7e.png">

The methods I use for suppressing print outputs don't seem to work. I've tried:

 ```
y <- suppressMessages(terra::aggregate(x, fact=2))
capture.output(y <- terra::aggregate(x, fact=2))
invisible(y <- terra::aggregate(x, fact=2))
invisible(capture.output(y <- terra::aggregate(x, fact=2)))
```

**Comment by rhijmans** [comment]
You should be able to suppress all progress bars with 

`terraOptions(progress=0)`

Also, `aggregate`  shows the progress bar much earlier (smaller data sets) than other methods do and I need to change that.

**Comment by Lachlan00** [comment]
Thanks rhijmans. That worked. I wasn't aware of the `terraOptions`.

**Comment by rhijmans** [comment]
The default setting is much better now, only showing the progressbar for very large rasters.

**Comment by fabeit** [comment]
Is it possible to always show the progress bar?

**Comment by fabeit** [comment]
@rhijmans Thank you, unfortunately I am not seeing anything while performing aggregate on this raster
class       : SpatRaster 
dimensions  : 15234, 39540, 1  (nrow, ncol, nlyr)
resolution  : 0.0091047, 0.0091047  (x, y)
