### ISSUE TITLE
mask lead to no data

### ISSUE THREAD

**Issue by TianyaImpression** [rspatial/terra#252]
I created a spatRaster dimensions  : 548, 2537, 468  (nrow, ncol, nlyr)
I tried to mask data with a SpatRaster
after mask
the SpatRaster only left one layer data

the data before mask
![image](https://user-images.githubusercontent.com/22004043/122357788-9d815c00-cf86-11eb-996b-57cb063f94f8.png)

after mask:
![image](https://user-images.githubusercontent.com/22004043/122357883-b558e000-cf86-11eb-90dc-cee0cf679d2f.png)

**Comment by rhijmans** [comment]
Sorry about that. This has been fixed in the development version. It is easy to install with 

`install.packages('terra', repos='https://rspatial.r-universe.dev')` 

I will send this version to CRAN today or tomorrow.
