### ISSUE TITLE
Error: [rast] layer number for R, G, B, cannot exceed the number of layers

### ISSUE THREAD

**Issue by sm-potter** [rspatial/terra#253]
I have a raster with three bands I am trying to open in terra which opened perfectly fine before I updated my packages today.  I am now using version 1.2.10.  When I open the raster in terra I get the following errer:

`Error: [rast] layer number for R, G, B, cannot exceed the number of layers`

When I open the same file in the 'raster' package it is fine though and returns:

```
class      : RasterLayer 
band       : 1  (of  3  bands)
dimensions : 10128, 22588, 228771264  (nrow, ncol, ncell)
resolution : 463.3127, 463.3127  (x, y)
extent     : -11738491, -1273183, 4382475, 9074906  (xmin, xmax, ymin, ymax)
crs        : +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs 
source     : 2005.tif 
names      : X2005 
values     : 1.950896e-06, 1  (min, max)

Any thoughts on the reason terra can't open the file?  Apologies for the non-reproducible example, the file is my own. 
```

**Comment by rhijmans** [comment]
Sorry about that. This has been fixed in the development version. It is easy to install with 

install.packages('terra', repos='https://rspatial.r-universe.dev')

I will send this version to CRAN today or tomorrow.
