### ISSUE TITLE
distance and boundary functions run slower

### ISSUE THREAD

**Issue by fRIdanwismer** [rspatial/terra#254]
Hi, was there updates to these functions? They seem to run considerably slower compared to older version of terra. Thanks!

**Comment by rhijmans** [comment]
Not on purpose, but I can look into it. Do you have an example where you observed this, or can you `show(x)` where x is a SpatRaster? Is this a SpatRaster with a longlat crs?

**Comment by fRIdanwismer** [comment]
Thanks of the response Robert. Attached is the .tif I use in the following code chunk to generate distance to edge:

library(terra)
library(raster)

# Input binary raster
cb <-rast("./cb.tif")

# Reclassify
m <- c(0,NA, 1,1)
rclmat <- matrix(m, ncol=2, byrow=TRUE)
na_1 <- terra::classify(cb,rclmat)

# Aggregate 30m to 150m cell size
cb150m_terra <- terra::aggregate(na_1,5, fun='max')
cb150m_raster <- raster(cb150m_terra)

# Terra::Distance
start.time <- Sys.time()
d2cb <- terra::distance(cb150m_terra)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
# Time difference of 2.53582 mins

# Raster::Distance
start.time <- Sys.time()
d2cb <- terra::distance(cb150m_raster)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
# Time difference of 2.002817 mins

I appreciate you looking into this. Terra is a great package and I have begun converting my code base to replacing raster with it.

Dan


Dan Wismer, MGIS
GIS Analyst
GIS Program
[cid:friresearch_af8d7d28-1e93-4635-a5ee-fbaa7eb2008e.png]
fRI Research  |  1176 Switzer Drive, Hinton, Alberta, T7V 1V3
www.fRIResearch.ca  |  ***@***.***  |  Direct: (403) 470-9444

Disclaimer: This email message may contain certain confidential and privileged material for the sole use of the intended recipient. Any review, use, or distribution by others is prohibited. If you are not the intended recipient, please contact the sender, and destroy or delete all copies.

 <https://plus.google.com/+CodetwoSoftware/posts>  <https://twitter.com/CodeTwoSoftware>  <https://www.youtube.com/user/CodeTwoChannel#p/u>
<http://www.codetwo.com/exchange-folder-sync/>

**Comment by rhijmans** [comment]
Can you upload the file to github (or a file share and provide a link?).  Attaching by email does not work (and github generally works much if you avoid email responses)

**Comment by fRIdanwismer** [comment]
For sure. It is a .tif however and it won't let me upload. Any suggestions?

**Comment by rhijmans** [comment]
I have (at long last) been working on speeding these things up, but I no longer have the file to compare with your benchmark,

**Comment by rhijmans** [comment]
I am closing this as I do not have the file for comparison. But it would be great if you could share it again.
