### ISSUE TITLE
subds not work in rast

### ISSUE THREAD

**Issue by kongdd** [rspatial/terra#255]
Terra is the lastest version from CRAN.
subds not work as expect:
![image](https://user-images.githubusercontent.com/9815742/122645150-8049ba80-d14b-11eb-92ee-26804851802e.png)

**Comment by rhijmans** [comment]
Does the file have sub-datasets? I have not seen that in GTiff. A sub-dataset is not the same as another layer; it is a higher level. 
I am guessing that what you want is  

`rast(file)[[2]]`

**Comment by kongdd** [comment]
Thank you
