### ISSUE TITLE
time: distinguish between Date and POSIX* classes

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#256]
I'm using `terra 1.2.10`, and I know that the `time` function is still experimental. 

According to the current documentation, it only support `Date` objects for time attribute, but actually it currently supports any of  `Date` or `POSIXt` objects (which is way better !)

However, when assigning a `Date` time attribute to a `SpatRaster` object, the class is changed to `POSIX*`:

```
s <- rast(system.file("ex/logo.tif", package="terra"))   
 
ltime <- as.Date("2001-05-04") + 0:2    
class(ltime)
# [1] "Date"

time(s) <- ltime
class(time(s))
# "POSIXct" "POSIXt"
```

Would it be possible to preserve the original time class (either `Date` or `POSIX*`) for the the `SpatRaster` object?

**Comment by rhijmans** [comment]
Thanks, fixed.
