### ISSUE TITLE
raster::distanceFromPoints and terra:distance 

### ISSUE THREAD

**Issue by EiriniTryp** [rspatial/terra#259]
Using raster::distanceFromPoints(RasterLayer,matrix) and terra:distance(SpatRaster,SpatVector) is it supposed to get the same results when using  the same input data ? Because SpatVector overlaps with SpatRaster area and it only calculates outside distance of SpatRaster extent. How to solve that and get same results like raster::distanceFromPoints, where the distance is calculated from a point to all cells of the Raster object.

**Comment by rhijmans** [comment]
I am not sure if I understand your question. Can you provide a small example?
