### ISSUE TITLE
AAIGrid driver - writeRaster() with decimal precision

### ISSUE THREAD

**Issue by gui0me** [rspatial/terra#260]
Hi,
I am new with terra use and I am trying to write a merged SpatRaster to an Arc/Info ASCII Grid file. This merged raster comes from multiple .asc files I load and merged with merge() method.

I'd like to have only two decimal places for values in this file. So I added gdal=c("DECIMAL_PRECISION=2") in my writeRaster command but there is no effect. 

writeRaster(m, file.path("D:/test", "merged.asc"), overwrite=TRUE, filetype="AAIGrid", gdal=c("DECIMAL_PRECISION=2"), datatype="FLT8S", NAflag = -9999)

I just see a difference when I use FLT4S or FLT8S. With FLT8S type, some value have two decimal places and the others have 18 significants digits.

![write](https://user-images.githubusercontent.com/86349316/123073393-aa82cd00-d416-11eb-8930-e41847c322d1.JPG)

**Comment by rhijmans** [comment]
Thank you very much, that was it very useful as it a revealed a major bug. The gdal options where ignored for the formats that can not be written to directly but require "create-copy".  I believe this is fixed now, as I see: 

```
library(terra)
# terra version 1.3.6
r <- rast(nrows=3, ncols=3, xmax=0)
values(r) <- c(1:9)/3.3
as.matrix(r, wide=TRUE)
#          [,1]      [,2]      [,3]
#[1,] 0.3030303 0.6060606 0.9090909
#[2,] 1.2121212 1.5151515 1.8181818
#[3,] 2.1212121 2.4242424 2.7272727
 
f <- "test.asc"
writeRaster(r, f, overwrite=TRUE, gdal="DECIMAL_PRECISION=2", NAflag=-9999)
readLines(f)
#[1] "ncols        3"                
#[2] "nrows        3"                
#[3] "xllcorner    -180.000000000000"
#[4] "yllcorner    -90.000000000000" 
#[5] "cellsize     60.000000000000"  
#[6] "NODATA_value  -9999.00"        
#[7] " 0.30 0.61 0.91"               
#[8] " 1.21 1.52 1.82"               
#[9] " 2.12 2.42 2.73"               
```

**Comment by oSamTo** [comment]
on this, I have ~5,000 rasters that are predominantly NA, with ~25% double precision values. 

When using the following, I get values to 18 dp which the end user would like to avoid;
`writeRaster(r, "/path/myfile.asc", NAflag = -1, overwrite = T)`

when using the `gdal="DECIMAL_PRECISION=5"` argument, it does indeed truncate the values to 5dp (where using `round` does not) but also sets the NA flag to -1.00000, which in turn inflates the file size by 150%. 

Is there a way to change only the non-NA values in the written ascii to x d.p. and not effect the NA flag? thank you

**Comment by rhijmans** [comment]
This is a format from a bygone era, but, if you still need it, you may be able to use this work around:

```
library(terra)
r <- rast(nrows=3, ncols=3, xmax=0)
values(r) <- c(1:9)/3.3
r[2,] <- NA
 
f <- "test.asc"
writeRaster(r, f, overwrite=TRUE, gdal="DECIMAL_PRECISION=3", NAflag=-1)
x <- readLines(f)
x <- gsub("-1.000", "-1", x)
writeLines(x, f)
```
