### ISSUE TITLE
segfault with buffer() along edge of global SpatRaster 

### ISSUE THREAD

**Issue by pvjeetze** [rspatial/terra#261]
Hi,

I'm catching a segfault when I buffer points along the edges of a (tiled) global SpatRaster (xmin=-180, xmax=180, ymin=-90, xmax=90). 

The original example is a little complicated and embedded in a parallelized `foreach` loop, but I was able to reproduce the error with the following snippet:
```
> x <- rast(ncol=10, nrow=10)
> xpoly <- as.polygons(x)
> xbuff <- buffer(xpoly, width=2000)

 *** caught segfault ***
address (nil), cause 'unknown'
```
In the original example I use `as.points()` for selected pixels instead of `as.polygons`, but I'm guessing that the reason for both examples failing is the buffer crossing the raster extent.

Thanks and kind regards!

**Comment by rhijmans** [comment]
Thanks very much for raising this issue. This was caused by a bug in lon/lat buffer creation at the "edges" of the world.  This works much better now and the example runs without error; but there may still be more corner cases to be detected.

**Comment by rhijmans** [comment]
Sorry, there is one more thing I need to fix, reopening.

**Comment by rhijmans** [comment]
I believe it works now (while there is lot of scope for improving the algorithm; I hope to work on over the coming weeks.)

**Comment by pvjeetze** [comment]
Thanks a lot! I will not hide that I absolutely enjoy working with `terra`!
