### ISSUE TITLE
additional argument for reading NetCDF files

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#263]
Dear Robert,

The new function `writeCDF` is an excellent addition to the `terra` package in comparison to the `raster` one.

However, for reading NetCDF files the `raster` package allowed the following arguments which are currently not supported by `terra`:

* *varname*: character. The variable name, such as ’tasmax’ or ’pr’. If not supplied and the file has multiple variables are a guess will be made (and reported)
* *lvar*: integer > 0 (default=3). To select the ’level variable’ (3rd dimension variable) to use, if the file has 4 dimensions (e.g. depth instead of time)
* *level*: integer > 0 (default=1). To select the ’level’ (4th dimension variable) to use, if the file has 4 dimensions, e.g. to create a RasterBrick of weather over time at a certain height.
* 
Is there any possibility to include them (or at least *varname*) in the `terra` package ?

Thanks in advance

**Comment by rhijmans** [comment]
The `varname` argument is available, but now called `subds`.  (Also see the `sds` method)

As for `lvar` and `level`: high-dimensional structures are "flattened" instead. You can use the layer names to subset. I can imagine adding the option to subset when creating the object, as that could things go smoother.

**Comment by hzambran** [comment]
Thank you very much for the clarification. 

When using `subds` to provide the name of the variable I want to subset everything works as expected. 

Just  a last question: when `subds` is not used and more than one variable is stored within the source raster file, what is the correct way to subset the variable?

As an example:

```
x <- rast("temp_v20_day_1979_01_005deg.nc")
> x
class       : SpatRaster 
dimensions  : 800, 220, 62  (nrow, ncol, nlyr)
resolution  : 0.05, 0.05  (x, y)
extent      : -77, -66, -57, -17  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
sources     : temp_v20_day_1979_01_005deg.nc:tmin  (31 layers) 
              temp_v20_day_1979_01_005deg.nc:tmax  (31 layers) 
varnames    : tmin (Daily minimum temperature) 
              tmax (Daily maximum temperature) 
names       :  tmin_1,  tmin_2,  tmin_3,  tmin_4,  tmin_5,  tmin_6, ... 
unit        : Celsius, Celsius, Celsius, Celsius, Celsius, Celsius, ... 
time        : 1979-01-01 to 1979-01-31 
```

the two variables are `tmin` and `tmax`, but 

`x[["tmin"]] ` returns `NULL`.

 what is the correct way to subset `tmin` or `tmax`?

**Comment by rhijmans** [comment]
The names of the subdatasets cannot be used to subset, in the current version. I need to think about a good way to allow for doing that, 

You can do 

`x[[grep("tmin", names(x))]]
`

And I have that easier in the dev. version in which the partial matching is now done automatically if you use single brackets. I am little afraid this may be confusing when there are partial matches and a complete match as well. 

```
library(terra)

s <- rast(system.file("ex/logo.tif", package="terra"))   
s[["red"]]
#class       : SpatRaster 
#name        : red 

s[["re"]]
#NULL

s["red"]
#class       : SpatRaster 
#name        : red 

s["re"]
class       : SpatRaster 
names       : red, green 

s["^re"]
#class       : SpatRaster 
#name        : red 

```
