### ISSUE TITLE
Link to rspatial.org on R CRAN leads to Raster instead of terra

### ISSUE THREAD

**Issue by carbonmetrics** [rspatial/terra#265]
Clicking on the link in [R CRAN terra](https://cran.r-project.org/web/packages/terra/index.html) leads to https://rspatial.org/terra. 
Clicking on "spatial data with terra" leads to the `raster` page, not the `terra` page. 
Ditto with the "remote sensing" item.

**Comment by rhijmans** [comment]
Thank you! Fixed to `https://rspatial.org/terra/`  --- the last backslash makes all the difference.

**Comment by carbonmetrics** [comment]
I think that backslash needs to be added to the [CRAN URL](https://cran.r-project.org/web/packages/terra/index.html) as well.

**Comment by rhijmans** [comment]
That should happen when the next version of terra appears on CRAN
