### ISSUE TITLE
Edit text or make it an error

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/terra#266]
https://github.com/rspatial/terra/blob/80ea70d10887ed114232d7fd1ddbdbd1bf9ded66/R/subset.R#L22

Subset issues a warning when the items in the subset vector are not valid names or numbers for the layers in the raster. I'd suggest converting this to an error so execution stops and change the text to something like  "The list of layers to be retained contain items that are not in the SpatRaster."

**Comment by rhijmans** [comment]
I changed the warning to an error and the message now lists the offending items.

**Comment by GeraldCNelson** [comment]
Thanks!
