### ISSUE TITLE
Terra hexagon logo icon

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [rspatial/terra#267]
Hello people at Terra! 

I noticed there is no hexagon R logo and made one, I would like you to use it for free. I need to have something to show for my personal graphics portfolio.  I also code in R and love spatial data, novice level. If this idea is something the team wants I would be over the moon happy to help. Also, i would like to contribute code as I learn. 

The hexagon icon logo follows same design principles as CRAN icon logos and is in PNG format. 

Thanks for reading this.

**Comment by rhijmans** [comment]
Hi!  Thank you, can I see it?

**Comment by PythonCoderUnicorn** [comment]
> Hi! Thank you, can I see it?

Hey, Thanks for responding. 
sure,

I have 3 designs 

The link to the designs are on my Figma [Terra logos](https://www.figma.com/file/5yowE7d3zlLDBcxXwJYSsa/Terra-Logo)

**Comment by rhijmans** [comment]
Very nice! I like the middle one best.

**Comment by PythonCoderUnicorn** [comment]
Okay, I will upload the 2nd (middle) one.

**Thanks for letting me contribute** to the project! I appreciate it.  **Zane Dax  (she/her)** is my name and I'll be attending useR conference this weekend.

![Terra R pkg - 2](https://user-images.githubusercontent.com/55933131/124372808-77c4aa00-dc4a-11eb-8eb1-4c4bf71df02f.png)

**Comment by rhijmans** [comment]
Thank you!
