### ISSUE TITLE
more explanation please

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/terra#268]
https://github.com/rspatial/terra/blob/ac6906c96065663b31445d81081d2ecba9fede14/R/app.R#L75

Could the error message 	
error("app", "the number of values returned by 'fun' is not appropriate") 
be expanded to say how it is not appropriate? Or something about what would be appropriate.

This also is the case, a few lines down in the code.

**Comment by rhijmans** [comment]
I could add "it is not the product of the number of cells and and a positive integer" but I am not sure if that clarifies.
