### ISSUE TITLE
rast not importing netcdf file correctly

### ISSUE THREAD

**Issue by scbrown86** [rspatial/terra#27]
`terra::rast(x)` is importing a netcdf file but seems to be ignoring the coordinates stored within the file. 

The data structure (from `cdo sinfo`) is:
```
   File format : NetCDF4 zip
    -1 : Institut Source   T Steptype Levels Num    Points Num Dtype : Parameter ID
     1 : unknown  unknown  v instant       1   1     64800   1  I32z : -1            
   Grid coordinates :
     1 : lonlat                   : points=64800 (360x180)
                              lon : 0 to 359 by 1 degrees_east  circular
                              lat : -89.5 to 89.5 by 1 degrees_north
   Vertical coordinates :
     1 : surface                  : levels=1
   Time coordinate :  2 steps
     RefTime =  0000-01-01 00:00:00  Units = years  Calendar = 360_day
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
 -175000-01-01 00:00:00 -174975-01-01 00:00:00
```

However, when importing the data with `terra::rast(x)` we get the following:
```
> terra::rast("./example.nc")
class       : SpatRaster 
dimensions  : 180, 360, 2  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. :  
data source : ./example.nc 
names       : example1, example2 
```
The raster is also flipped vertically
![Rplot](https://user-images.githubusercontent.com/23713602/79814632-e8710500-83bd-11ea-9db0-d302a5802bf5.png)

There is no issue however when importing the file with `raster::stack(x)`

```
> raster::stack("./example.nc")
class      : RasterStack 
dimensions : 180, 360, 64800, 2  (nrow, ncol, ncell, nlayers)
resolution : 1, 1  (x, y)
extent     : -0.5, 359.5, -90, 90  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 
names      : X.175000, X.174975 
```
![Rplot01](https://user-images.githubusercontent.com/23713602/79814745-3554db80-83be-11ea-992a-c6b4187cb5e8.png)

Converting from a `raster::brick()` to a `SpatRaster` doesn't help either
```
as(brick("./example.nc"), "SpatRaster")
class       : SpatRaster 
dimensions  : 180, 360, 2  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. :  
data source : ./example.nc 
names       : example1, example2 
```

I've attached the example.nc file.
[example.nc.gz](https://github.com/rspatial/terra/files/4507155/example.nc.gz)

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] raster_3.1-5 sp_1.4-1     terra_0.5-11

loaded via a namespace (and not attached):
[1] compiler_3.6.3   tools_3.6.3      Rcpp_1.0.4.6     codetools_0.2-16 ncdf4_1.17       grid_3.6.3       lattice_0.20-38 
```

**Comment by rhijmans** [comment]
`raster` directly uses the netcdf library (via the ncdf4 package) whereas `terra` accesses the file via GDAL (that may change in the future). 

I get the same result on windows. On unbuntu, with a newer GDAL (version 3.0.4) `rast("example.nc")` crashes R (after showing `Warning 1: No UNIDATA NC_GLOBAL:Conventions attribute`). 

So perhaps this needs to be brought to the attention of the GDAL developers.

**Comment by mdsumner** [comment]
it works for me on ubuntu with GDAL 3.0.4 with CRAN terra

**Comment by rhijmans** [comment]
Thanks @mdsumner --- it now also works on the development version for that version of GDAL which had an unrelated bug that I was happy to find. I looks like that for windows we will have to wait for the release of R version 4, so that we can use https://github.com/rwinlib/gdal3

**Comment by rhijmans** [comment]
This works now with R 4.0.0 (and Rtools 4)
