### ISSUE TITLE
Unexpected result from the function merge

### ISSUE THREAD

**Issue by zavud** [rspatial/terra#271]
I used the `merge` function from `terra` to merge 2 raster images. But I got very strange result. 

The code:

```
library(terra)
# load the images
files = list.files(pattern = ".tif", recursive = T, full.names = T)

rs_1 = raster::brick(desis_files[1])
rs_2 = raster::brick(desis_files[2])

rs_merged = terra::merge(rs_1, rs_2)
```

When I plot a single band using `plot()` I notice that the `merge` function has not been able to merge the images succesfully:

![image](https://user-images.githubusercontent.com/63021993/124290298-8c724680-db53-11eb-83ab-a01a3f76ced7.png)

UPDATE: I used the `merge` function from `raster` this time, and it did work:

![image](https://user-images.githubusercontent.com/63021993/124295696-6f407680-db59-11eb-97c1-04291cb1ca25.png)

Would parallel computation cause this problem in `terra::merge`? Because I usually try to use all of my cores running `beginCluster` before image preprocessing.

Another interesting point: `raster::merge` took about 37 mins to merge the files, while `terra::merge` took 1.2 hours.

**Comment by rhijmans** [comment]
Thank you very much for reporting this. Very ugly. `terra::merge` failed on rasters that are not processed in one step (that is, larger files). You can simulate that by setting the `steps ` parameter to a value larger than `1.

```
library(terra)
x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, ncols=30, nrows=30)
y <- rast(xmin=-85, xmax=-55, ymax=60, ymin=30, ncols=30, nrows=30)
z <- rast(xmin=-60, xmax=-30, ymax=50, ymin=20, ncols=30, nrows=30)
values(x) <- 1:ncell(x)
values(y) <- 1:ncell(y)
values(z) <- 1:ncell(z)
m <- merge(x, y, z, wopt=list(steps=2))
plot(m)
```

This now works in the development version. 

`beginCluster` has no effect on `terra`.

**Comment by zavud** [comment]
@rhijmans is there any equivalent of `beginCluster`/ `endCluster` in `terra`?

**Comment by rhijmans** [comment]
There is not. Parallelization support is still pending. See https://github.com/rspatial/terra/issues/36 for some discussion
