### ISSUE TITLE
The `rast()` function rotates input matrices.

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#274]
Dear @rhijmans - I tried to convert a simple matrix to a **terra** object. The `rast` function works, but it rotates my matrix. Interestingly, also the `as.matrix()` output is different from the input matrix. I was not able to find anything about this in the documentation, and so I am unsure if this is a bug or (maybe?) some kind of a feature... A reproducible example is attached below:

``` r
library(terra)
#> terra version 1.3.12

# matrix
my_mat = matrix(c(rep(1, 15), 10, rep(2, 9)), nrow = 5)
my_mat
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]    1    1    1   10    2
#> [2,]    1    1    1    2    2
#> [3,]    1    1    1    2    2
#> [4,]    1    1    1    2    2
#> [5,]    1    1    1    2    2

# to raster
r = rast(my_mat)
plot(r)
```

![](https://i.imgur.com/dyXLzdd.png)

``` r

# back to matrix
as.matrix(r, wide = TRUE)
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]    1    1    1    1    1
#> [2,]    1    1    1    1    1
#> [3,]    1    1    1    1    1
#> [4,]   10    2    2    2    2
#> [5,]    2    2    2    2    2


# raster - different behavior
library(raster)
#> Loading required package: sp
plot(raster(my_mat))
```

![](https://i.imgur.com/FsjS2YS.png)

<sup>Created on 2021-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rhijmans** [comment]
Thank you. It seems that went wrong for matrices with the same `nrow` and `ncol`; in which both `rast` and `values<-` transposed the matrix (it needs to happen once). 

So with the CRAN version this is OK

```
library(terra)
m = matrix(1:12, nrow = 4, byrow=TRUE)
m
#     [,1] [,2] [,3]
#[1,]    1    2    3
#[2,]    4    5    6
#[3,]    7    8    9
#[4,]   10   11   12

r = rast(m)
as.matrix(r, wide=TRUE)
#     [,1] [,2] [,3]
#[1,]    1    2    3
#[2,]    4    5    6
#[3,]    7    8    9
#[4,]   10   11   12
```
But this is not 

``` 
m = matrix(1:9, nrow = 3, byrow=TRUE)
as.matrix(rast(m), wide=TRUE)
#     [,1] [,2] [,3]
#[1,]    1    4    7
#[2,]    2    5    8
#[3,]    3    6    9
``` 

Now, with `terra version 1.3.13` you get the correct

```
as.matrix(rast(m), wide=TRUE)
#     [,1] [,2] [,3]
#[1,]    1    2    3
#[2,]    4    5    6
#[3,]    7    8    9
```
