### ISSUE TITLE
R session crashes when `exact = TRUE`

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#275]
Today, I tried to use the `exact = TRUE` option of `extract()`. The option `exact = FALSE` works properly, but `exact = TRUE` crashes my R session. I have tested my code on the latest development version of **terra**.

```r
library(terra)
f1 = "volcano.tif"
if (!file.exists(f1)) {
  download.file("https://github.com/Nowosad/supercells/raw/master/inst/raster/volcano.tif", 
                f1, mode = "wb")
}
f2 = "volcano_regions.gpkg"
if (!file.exists(f2)) {
  download.file("https://github.com/Nowosad/laland/raw/master/inst/regions/volcano_regions.gpkg", 
                f2, mode = "wb")
}

r = rast("volcano.tif")
v = vect("volcano_regions.gpkg")

# works
e1 = extract(r, v)

# fails (R session crashes)
e2 = extract(r, v, exact = TRUE)
```

**Comment by rhijmans** [comment]
Thanks. That was literally a corner-case (cells that merely touched the polygon were included), and revealed a bug in SpatVector crop; so very useful.
