### ISSUE TITLE
intersect error 

### ISSUE THREAD

**Issue by zhangpf-cug** [rspatial/terra#28]
> rm(list = ls())
> library(terra)
> diri1 <- "datasets/map_data/HanRiverBasin/boundry.shp" 
> diri2 <- "datasets/map_data/gadm36_CHN_shp/gadm36_CHN_3.shp"
> ds1 <- terra::vect(diri1)
> ds2 <- terra::vect(diri2)
> ds3 <- raster::intersect(ds2, ds1)

Error in RGEOSBinTopoFunc(spgeom1, spgeom2, byid, id, drop_lower_td, unaryUnion_if_byid_false,  : 
  TopologyException: Input geom 0 is invalid: Self-intersection at or near point 112.45460824490014 33.010390401808422 at 112.45460824490014 33.010390401808422
> ds1
class       : SpatVector 
geometry    : polygons 
elements    : 1
extent      : 106.0862, 114.3041, 30.07086, 34.18566  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs  
names       : Shape_Leng, Shape_Area, HydroID, Name

**Comment by rhijmans** [comment]
This would perhaps be a `raster` issue, but not a `terra` issue. I think it is more something for stackoverflow.  The message (from GEOS) is pretty clear:

```Input geom 0 is invalid: Self-intersection at or near point 112.45460824490014 33.010390401808422 at 112.45460824490014 33.010390401808422```

Zoom in to the area and look at `ds1` and try to clean the topology, for example with package `cleangeo` 

Beyond that there is not much to say without having the data.

**Comment by zhangpf-cug** [comment]
Thank you very much.
