### ISSUE TITLE
rast hdf files fail

### ISSUE THREAD

**Issue by TianyaImpression** [rspatial/terra#280]
hdf data from:http://www.glass.umd.edu/NR/2015/
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
terra version 1.3.6

I found that terra rast hdf files not stable, some hdf files is ok, some not

each hdf has two bands: NR and QA

```
 gllist = list.files(path = "D:/XYDATA/GLASS/2015", pattern = ".hdf$")   #读取HDF列表
 gldir = paste0("D:/XYDATA/GLASS/2015/", gllist)
 gl1 = rast(gldir)   #读取所有的HDF
```

![](https://my-mdnice.oss-cn-beijing.aliyuncs.com/image_20210714115909.png)

**Comment by rhijmans** [comment]
I see no error:

```
library(terra)
#terra version 1.3.15
f <- "GLASS07B11.V40.A2015001.2020348.hdf"
 r <- rast(f)
r
#class       : SpatRaster 
#dimensions  : 3600, 7200, 2  (nrow, ncol, nlyr)
#resolution  : 0.05, 0.05  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +ellps=clrk66 +no_defs 
#sources     : GLASS07B11.V40.A2015001.2020348.hdf:GLASS07B11:NR  
#              GLASS07B11.V40.A2015001.2020348.hdf:GLASS07B11:QC  
#names       : GLASS07B11:NR, GLASS07B11:QC 
```
I think this is the file you used (I see it in the email, not on the website, please do not use image, just copy the text,
Can you try with the current development version of terra? Are there Chinese characters in your path name?

**Comment by TianyaImpression** [comment]
There is no Chinese characters in my path name, 

when I rast the data, is ok

then I trim and mask them, terra failed.
```
gllist = list.files(path = "D:/XYDATA/GLASS/2015", pattern = ".hdf$")   #读取HDF列表
gldir = paste0("D:/XYDATA/GLASS/2015/", gllist)
gl1 = rast(gldir)   #读取所有的HDF
sub2= seq(1,730,2)
gl2= subset(gl1, sub2)
gldate = seq.Date(from = as.Date("2015-01-01"), to = as.Date("2015-12-31"), by=1)   #生成2015年8天时间序列
names(gl2) = gldate   #图层用日期命名
cmr = vect("./SHP/CMR.shp")    #读取研究区矢量
glcmr = trim(mask(gl2, cmr))        #裁剪
```

![](https://my-mdnice.oss-cn-beijing.aliyuncs.com/image_20210714135437.png)

Thank you for your reply!

**Comment by TianyaImpression** [comment]
I wonder if I rast two many hdf files
I tried to trim all the 365 hdf bands

**Comment by TianyaImpression** [comment]
after subset, I tried to plot gl2, it failed

plot(gl2[[1:4]])
Error: [plot] SpatRaster has no cell values

**Comment by mdsumner** [comment]
there's a "number of files open" limit at about 1024 for GDAL, I suspect this is related - I mean to go deeper into the topic sometime, but there's an env var you can set (I don't ultimately get why GDAL has to have the files "open", it's limiting for some obvious tasks with VRT that stalled me before). Possibly stars and/or gdalcubes has touched on the issue

**Comment by TianyaImpression** [comment]
> there's a "number of files open" limit at about 1024 for GDAL, I suspect this is related - I mean to go deeper into the topic sometime, but there's an env var you can set (I don't ultimately get why GDAL has to have the files "open", it's limiting for some obvious tasks with VRT that stalled me before). Possibly stars and/or gdalcubes has touched on the issue

I tried `gdal_translate` to translate these hdf files to geotiffs，the translate succeed.

**Comment by rhijmans** [comment]
Closing this because the issue has become stale. There is no resolution, so if anyone has the same problem, please comment here, or open a new issue.
