### ISSUE TITLE
R crashes with inverse point-based masking

### ISSUE THREAD

**Issue by ChristianDueben** [rspatial/terra#281]
Consider the following example:

```
require("tidyverse")
require("terra")

example_r <- system.file("ex/logo.tif", package = "terra") %>% 
  rast() %>% 
  .[[1]]
example_p <- spatSample(example_r, size = 1, as.points = T)

mask(example_r, example_p, inverse = T)
```

The last line crashes R.

I use R 4.1.0 and terra 1.3-4 and tested the code both on Windows 10 and on Ubuntu 20.04.

**Comment by Nowosad** [comment]
Is it related to https://github.com/rspatial/terra/issues/264? Have you tried to use the development version of terra?

**Comment by ChristianDueben** [comment]
Yes, it appears that #264 relates to the same issue, but with a polygon rather than a point.

I tried the development version (terra 1.3-15) now. What strikes me as odd is that `spatSample` now throws an error: `Error in .local(x, ...) : unused argument (geom = c("x", "y"))`. According to the function's help file, the syntax should still be correct; and it worked with the CRAN version.

The masking still does not work. Replacing the `spatSample` line with an alternative
```
example_p <- data.frame(lon = 12.5, lat = 42.5) %>% 
  vect(crs = crs(example_r))
```
and running the mentioned `mask` function, R does not crash anymore but throws another error: `Error: [mask] rasterization failed`.

Since the development version also throws errors, I am wondering whether it is a good idea to drop the CRAN release in favor of the development version.

**Comment by rhijmans** [comment]
Thanks, that was a very useful bug report.  The below now works:

```
library("terra")
r <- system.file("ex/logo.tif", package = "terra")  |>  rast()
r <- r[[1]]
set.seed(333)
p <- spatSample(r, size = 1, as.points = T)
x <- rasterize(p, r)
m <- mask(r, x, inverse=TRUE)
plot(m)
points(p, pch=1)
```

I think the development version is generally better, but there are sometime new errors, and thank you for reporting one!

**Comment by ChristianDueben** [comment]
Thanks for fixing it.
