### ISSUE TITLE
Saving layer names in NetCDF file with writeCDF

### ISSUE THREAD

**Issue by fabeit** [rspatial/terra#285]
Thanks for the new writeCDF function, it's working much better than previous Terra versions.

The only issue I am having is to save the layer names with the file. I mean the names(myStack). Is this possible? It would be extremely useful when the layers represent species for example. Otherwise I am forced to save an additional file such as a .csv with the list of layer names and then import both files.

Thanks!

**Comment by rhijmans** [comment]
I do not think that NetCDF supports the layer name concept.  Species could be the third dimension of a variable, but then you need to use a numeric code. Instead, you could treat each species as a variable (subdataset). Something like this: 

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra")) 
x <- sds(as.list(s))
names(x) <- names(s)
n <- writeCDF(x, "species.nc", overwrite=TRUE)
```

But perhaps it is easier to use GTiff.
