### ISSUE TITLE
Problems with `spatSample()` for vector data

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#289]
`spatSample()` looks ok when `method = "random"`. However:
1. `method = "regular"` does not look completely regular. Distances between "rows" are different than the distances between "columns".
2. The documentation states that the method argument `"can also be "stratified" if x is a SpatVector"`. However, this does not work in practice.

See an example code below:

``` r
library(terra)
#> terra version 1.3.16
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.2.1
library(spData)
pol = subset(world, name_long == "Poland")
v = vect(pol)
v = project(v, "EPSG:2180")
plot(v)
```

![](https://i.imgur.com/PdXR1Sn.png)

``` r

plot(spatSample(v, size = 20))
```

![](https://i.imgur.com/nfGyZKf.png)

``` r
plot(spatSample(v, size = 20, method = "regular"))
```

![](https://i.imgur.com/dXzPyz4.png)

``` r
plot(spatSample(v, size = 20, method = "stratified"))
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'plot': 'arg' should be one of "regular", "random"
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by OldLipe** [comment]
This option is also not available in the source code: file `sample.R` in line [314](https://github.com/rspatial/terra/blob/master/R/sample.R#L314)

**Comment by rhijmans** [comment]
Sorry for the long (summer) delay. I think this works much better now.
