### ISSUE TITLE
`spatSample` performance

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#290]
This is more a question than an issue.
I have been working on extracting a sample of measurements from a raster-based on the polygon area. Doing this, I have noticed that it is faster to extract all values and then create a sample, than to create a sample using `spatSample` and then extract values based on the location of the new points. The time difference grows with the sample size. Are there any possible performance improvements? Or maybe, is there any other way to achieve this result?

``` r
library(terra)
#> terra version 1.3.16
f = system.file("ex/lux.shp", package="terra")
v = vect(f)

rf = system.file("ex/elev.tif", package="terra")
x = rast(rf)

a = function(x, v, size, ...){
  a = extract(x, v)
  a = sample(a$elevation, size = size, ...)
  a
}

b = function(x, v, size, ...){
  b = spatSample(v, size = size, ...)
  b = extract(x, b)$elevation
  b
}

bench::mark(a(x, v, 50),
            b(x, v, 50), 
            check = FALSE)
#> # A tibble: 2 x 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 a(x, v, 50)   12.8ms   13.6ms      69.5  274.21KB        0
#> 2 b(x, v, 50)   16.3ms   17.7ms      51.3    1.21MB        0

bench::mark(a(x, v, 250),
            b(x, v, 250), 
            check = FALSE)
#> # A tibble: 2 x 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 a(x, v, 250)   14.2ms   15.1ms      63.4   275.7KB        0
#> 2 b(x, v, 250)   72.2ms     74ms      13.1    17.8KB        0
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rhijmans** [comment]
I think this makes sense; sampling from a polygon works by sampling from the extent and then selecting the points that are actually inside; so your alternative approach is faster, especially with a large sample size. 

The only thing I can think of what I could do at the terra end is to provide a spatSample method with a polygon as argument such that this method can decide to read all values first if that is warranted given the relative size of the approximate number of cells covered by the polygon (based on its extent) and the sample size requested

**Comment by rhijmans** [comment]
There is a further complication with cells that touch the border of the polygon. If you sample points, the probability of selecting a cell is proportional to how much of it is inside the polygon. But if you first select the cells that is not the case, unless you also compute weights (`weights=TRUE`) and you use these in `sample(, prob=weights)` .  Whether this matters depends on the case. So perhaps the better approach is to speed up the point sampling; that should be possible.

**Comment by rhijmans** [comment]
"fixed" in the sense that the performance is better than it was before. 

```
library(terra)
f = system.file("ex/lux.shp", package="terra")
v = vect(f)
rf = system.file("ex/elev.tif", package="terra")
x = rast(rf)

a = function(x, v, size, ...){
  a = extract(x, v)
  a = sample(a$elevation, size = size, ...)
  a
}

b = function(x, v, size, ...){
  b = spatSample(v, size = size, ...)
  b = extract(x, b)$elevation
  b
}

for (n in c(25, 50, 250, 500)) {
	cat("n =", n, "\n")
	print(bench::mark(a(x, v, n), b(x, v, n), check = FALSE)[, 1:4])
	cat("\n")
}
```

Gives: 

```
n = 25 
# A tibble: 2 × 4
  expression      min   median `itr/sec`
  <bch:expr> <bch:tm> <bch:tm>     <dbl>
1 a(x, v, n)   31.7ms   32.9ms      29.4
2 b(x, v, n)     15ms   17.1ms      50.6

n = 50 
# A tibble: 2 × 4
  expression      min   median `itr/sec`
  <bch:expr> <bch:tm> <bch:tm>     <dbl>
1 a(x, v, n)   31.3ms   32.8ms      30.1
2 b(x, v, n)   18.9ms     20ms      49.1

n = 250 
# A tibble: 2 × 4
  expression      min   median `itr/sec`
  <bch:expr> <bch:tm> <bch:tm>     <dbl>
1 a(x, v, n)   30.8ms   32.5ms      29.9
2 b(x, v, n)   32.3ms   36.8ms      23.8

n = 500 
# A tibble: 2 × 4
  expression      min   median `itr/sec`
  <bch:expr> <bch:tm> <bch:tm>     <dbl>
1 a(x, v, n)   30.2ms   32.6ms      29.8
2 b(x, v, n)     53ms   57.5ms      16.0
```
 
So the same general pattern of increasing efficiency for method "a" with increasing sample size, but the two methods still have a similar performance at `n=250`.
