### ISSUE TITLE
Problem loading terra package in Windows 10

### ISSUE THREAD

**Issue by victoriasg** [rspatial/terra#292]
Hi, 
I am trying to load terra in RStudio, which is running in Windows 10, but I am getting the following error: 

`> library(terra)
Error: package or namespace load failed for ‘terra’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package terra: loadModule(module = "spat", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "spat": function 'Rcpp_precious_remove' not provided by package 'Rcpp'`

I am using R version 4.1.0 (2021-05-18) -- "Camp Pontanezen" 

I also tried in a Mac Os, and I didn't have any problems.

**Comment by rhijmans** [comment]
If you first update the `Rcpp`  package,  `terra` should install without problem.
