### ISSUE TITLE
FR: function for counting NAs

### ISSUE THREAD

**Issue by be-marc** [rspatial/terra#293]
We work on an extension for [mlr3](https://github.com/mlr-org/mlr3) to allow parallel prediction of raster files. We miss a function to count `NA`s in a `SpatRaster` object by layer. Currently, we have to load all cell values into R and check for `NA`s.

**Comment by rhijmans** [comment]
You can use `freq` 

```
r <- rast(nrows=10, ncols=10)
set.seed(2)
values(r) <- sample(5, ncell(r), replace=TRUE) - 2
r[1:2] <- NA
s <- c(r, r/r)

freq(s, value=NA)
#     layer value count
#[1,]     1    NA     2
#[2,]     2    NA    17
```
Or `global` (but that should be less efficient) 

```
global(is.na(s), fun="sum") 
#        sum
#lyr.1     2
#lyr.1.1  17
``` 

Does that cover it for your use?

**Comment by be-marc** [comment]
Yes and works much faster. Thank you!
