### ISSUE TITLE
The value is missing when using writeRaster()

### ISSUE THREAD

**Issue by grantdxl** [rspatial/terra#295]
I want to write rasters  using terra package. but the value of raster file is missing ,my code is below:
#load data
library(terra)
library(luna)
datadir <- file.path("D:\\NDVIdata\\2019")
mf <- file.path(datadir, "MOD13A3.A2019001.h27v06.006.2019038102552.hdf")
r <- rast(mf)
r
#plot
plotRGB(r, r = 5, g = 4, b = 6,stretch="lin")
#using qc file
from <- c(1,3,7,9,11,16)
to   <- c(2,6,8,9,11,16)
reject <- c("10,11", "1100,1101,1110,1111", "00,11", "1","1","1")
qa_bits <- cbind(from, to, reject)
qa_bits
#create mask
quality_mask <- modis_mask(qc, 16, qa_bits)
# mask file
rmask <- mask(r, quality_mask)
#plot
plotRGB(rmask,r = 5, g = 4, b = 6,stretch="lin")
#save file
f <- file.path("D:\\NDVIdata\\2019\\a201901.tif")
x<-writeRaster(rmask,f,overwrite=T, gdal=c("COMPRESS=LZW","TFW=YES","of=COG"), datatype='INT1U')
x
the result of x is:
class       : SpatRaster 
dimensions  : 1200, 1200, 11  (nrow, ncol, nlyr)
resolution  : 926.6254, 926.6254  (x, y)
extent      : 10007555, 11119505, 2223901, 3335852  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs 
source      : a201901.tif 
names       : MOD_G~NDVI", MOD_G~ EVI", MOD_G~lity", MOD_G~ance", MOD_G~ance", MOD_G~ance", ... 
min values  :           0,           0,         NaN,         NaN,         NaN,         NaN, ... 
max values  :           0,           0,         NaN,         NaN,         NaN,         NaN, ... 

Can you help me find the value? Thank you !
[2019.zip](https://github.com/rspatial/terra/files/6918899/2019.zip)

**Comment by grantdxl** [comment]
I've found the reason , It's the dataTpye.  If I replace it with INT4S, the Values appear:
> x2
class       : SpatRaster 
dimensions  : 1200, 1200, 11  (nrow, ncol, nlyr)
resolution  : 926.6254, 926.6254  (x, y)
extent      : 11119505, 12231456, 2223901, 3335852  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs 
source      : a201902.tif 
names       : MOD_G~NDVI", MOD_G~ EVI", MOD_G~lity", MOD_G~ance", MOD_G~ance", MOD_G~ance", ... 
min values  :   -20000000,   -12650000,        2057,           0,       50000,       10000, ...
max values  :   100000000,    69720000,       63487,    94630000,    95730000,    91880000, ... 
____________________
But the values are 10000 times of original value. the value I open in python is: 
np.unique(ndvi)
array([-3000, -2000, -1997, ...,  9951,  9979, 10000], dtype=int16)

the minimum is -3000, and the maximum is 10000.  so still a problem !

**Comment by kadyb** [comment]
Shouldn't you divide the values by a scalar to get NDVI between -1 and 1?

```r
library("terra")

r <- rast("MOD13A3.A2019001.h27v06.006.2019038102552.hdf")

ndvi <- r[[1]] / 100000000
summary(ndvi)
#> MOD_Grid_monthly_1km_VI:"1 km monthly NDVI"
#> Min.   :-0.2000       
#> 1st Qu.: 0.4072
#> Median : 0.5746
#> Mean   : 0.5251
#> 3rd Qu.: 0.7190
#> Max.   : 1.0000
#> NA's   :141

ndvi_calc <- (r[[5]] - r[[4]]) / (r[[5]] + r[[4]])
names(ndvi_calc) <- "NDVI"
summary(ndvi_calc)
#> NDVI
#> Min.   :-0.2000
#> 1st Qu.: 0.4072
#> Median : 0.5746
#> Mean   : 0.5252
#> 3rd Qu.: 0.7190
#> Max.   : 1.0000
#> NA's   :141
```

**Comment by grantdxl** [comment]
Thank you, kadyb ! thanks for your help!

       Basd on the user's guide of MOD13A3 ,the scale is 0.0001, not 0.000000001. the value become 10000 times when  load ing the data into R!  I can't find the reason. and I have another problem ,When using writeRaster( ), Can I be able to write it to a hdf-eos file but not  tif file? I tried but failed. Thank you very much!
















At 2021-08-03 21:59:59, "Krzysztof Dyba" ***@***.***> wrote:

Shouldn't you divide the values by a scalar to get NDVI between -1 and 1?

library("terra")

r<- rast("MOD13A3.A2019001.h27v06.006.2019038102552.hdf")

ndvi<-r[[1]] /100000000
summary(ndvi)
#> MOD_Grid_monthly_1km_VI:"1 km monthly NDVI"#> Min.   :-0.2000       #> 1st Qu.: 0.4072#> Median : 0.5746#> Mean   : 0.5251#> 3rd Qu.: 0.7190#> Max.   : 1.0000#> NA's   :141ndvi_calc<- (r[[5]] -r[[4]]) / (r[[5]] +r[[4]])
names(ndvi_calc) <-"NDVI"
summary(ndvi_calc)
#> NDVI#> Min.   :-0.2000#> 1st Qu.: 0.4072#> Median : 0.5746#> Mean   : 0.5252#> 3rd Qu.: 0.7190#> Max.   : 1.0000#> NA's   :141

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kadyb** [comment]
> Basd on the user's guide of MOD13A3 ,the scale is 0.0001, not 0.000000001. the value become 10000 times when  load ing the data into R!

I can see there is a `valid_range` tag (e.g. `valid_range=0, 10000`) in the metadata so maybe you should filter out values outside of this range. But shouldn't the reflectance be between 0 and 1 like in Landsat and Sentinel? 

```r
r <- rast("MOD13A3.A2019001.h27v06.006.2019038102552.hdf")
# transform NIR band
r[[5]] <- r[[5]] / 10000
r[[5]][r[[5]] > 10000] <- NA
r[[5]][r[[5]] < 0] <- NA
summary(r[[5]])
#> MOD_Grid_monthly_1km_VI:"1 km monthly NIR reflectance"
#> Min.   :   2
#> 1st Qu.:1769
#> Median :2159
#> Mean   :2578
#> 3rd Qu.:2722
#> Max.   :9817
#> NA's   :141
```

> I have another problem ,When using writeRaster( ), Can I be able to write it to a hdf-eos file but not  tif file?

Try to use [writeCDF](https://rspatial.github.io/terra/reference/writeCDF.html) function, but the recommended save formats are ".nc" or ".cdf".

Here are the tutorials: https://rspatial.org/terra/
