### ISSUE TITLE
spatSample does not replace when replace = TRUE

### ISSUE THREAD

**Issue by dklinges9** [rspatial/terra#297]
Apologies to be opening another issue with `spatSample` when there's others open. On the surface this one doesn't look related to the others.

```
# Works fine with size = 5000
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
s <- terra::spatSample(r, size = 5000, method = "random", replace = TRUE)
dim(s)
```

I'm hoping to use `spatSample` _with_ replacement. When I ask for a sample size > number of cells in the `rast`, I run into problems. Testing on several machines, the following error is received:

```
# Breaks with size = 10000, which is greater than # of cells in r
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
s <- terra::spatSample(r, size = 10000, method = "random", replace = TRUE)
> Error in .local(x, ...) : object 'out' not found
```

Using:
```
> packageVersion("terra")
[1] ‘1.3.4’
```

**Comment by rhijmans** [comment]
Thank you very much. This now works for me.
