### ISSUE TITLE
terra package unable to plot when the first layer of SpatRaster is NA

### ISSUE THREAD

**Issue by bappa10085** [rspatial/terra#305]
I want to plot multi-layer raster with first layer being NA using `terra` package. But it returns me the following error

>Error: [plot] no values

Here is a reproducible example
```
library(terra)

#Read a raster file
logo1 <- rast(system.file("ex/logo.tif", package="terra"))
plot(logo1, 1:3)

#Make the first layer NA
values(logo1[[1]]) <- NA
plot(logo1, 1:3)
```
But when I am using raster package it runs without the error like
```
library(raster)

#Load an image
logo <- stack(system.file("external/rlogo.grd", package="raster"))
plot(logo)

#Make the first layer NA
values(logo[[1]]) <- NA
plot(logo)
```

**Comment by rhijmans** [comment]
Thank you for reporting this. It works a bit better now.
