### ISSUE TITLE
New plot error

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#308]
The code below worked fine until very recently. (It could be related to changes in https://github.com/rspatial/terra/issues/305):

``` r
library(terra)
#> terra version 1.4.0
tf = tempfile(fileext = ".tif")
download.file("https://github.com/Nowosad/supercells/blob/master/inst/raster/ortho.tif?raw=true", tf)
b = rast(tf)   
plot(b)
#> Error in grDevices::rgb(RGB[, 1], RGB[, 2], RGB[, 3], alpha = alpha, maxColorValue = scale): color intensity NA, not in 0:255
```

<sup>Created on 2021-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

EDIT: it seems that the `plotRGB()` function does not handle NA values well:

``` r
b[is.na(b)] = 0
plot(b)
```

![](https://i.imgur.com/gjeCsPd.png)

**Comment by kadyb** [comment]
I tried your example but I encountered problems loading this file. Maybe the file is corrupted and that's why it doesn't work? After re-saving in QGIS, the visualization works fine.

```r
library(terra)
#> terra version 1.3.4
tf = tempfile(fileext = ".tif")
download.file("https://github.com/Nowosad/supercells/blob/master/inst/raster/ortho.tif?raw=true", tf)
b = rast(tf)
#> Warning message:
#> Line 16: Didn't find element token after open angle bracket. (GDAL error 1)
plot(b)
#> Error: [readValues] cannot read values

library(raster)
x = raster(tf)
#> Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
#> Cannot create a RasterLayer object from this file.

library(stars)
x = read_stars(tf)
#> Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  : 
#> read failure
#> In addition: There were 11 warnings (use warnings() to see them)

### load re-saved file
a = rast("ortho_new.tif")
plotRGB(a)
b = stack("ortho_new.tif")
plotRGB(b)
c = read_stars("ortho_new.tif")
plot(st_rgb(c))
```

**Comment by kadyb** [comment]
My post above is invalid. On Windows it should be:

```r
download.file("https://github.com/Nowosad/supercells/blob/master/inst/raster/ortho.tif?raw=true", tf,
              mode = "wb")
```

then the file is downloaded properly. So, as Jakub reported, it is probably a regression to version 1.3.4 (this one works for me).

**Comment by rhijmans** [comment]
Thank you. This bug crept in because I made changes to `RGB` and `plotRGB` to also deal with the alpha channel, if present. Unfortunately the example data did not have NA cells so it went undetected; I have fixed the code and updated the examples.
