### ISSUE TITLE
extent inconsistency

### ISSUE THREAD

**Issue by rhijmans** [rspatial/terra#31]
This was part of https://github.com/rspatial/terra/issues/30  by ealonsogzl  (thanks for reporting, but please do not report 2 issues in one message)

I have found that the rast() function sometimes reads a wrong extent from rasters after call it several times (lets say over 5000 times) in the same session. The values and dimensions seems to be ok. It is easily possible to check the error comparing the extents trough the ext() function.

I am running the package in a conda installed R version on a HPC cluster. I use to update regularly the package directly from github.

Cheers

**Comment by rhijmans** [comment]
With the file from https://github.com/rspatial/terra/issues/29 I cannot reproduce this

```
x <- replicate(10000, rast("r1/hdr.adf"))
y <- lapply(x, function(i) as.vector(ext(i)))
z <- do.call(rbind, y)
unique(z)
#        xmin   xmax    ymin   ymax
#[1,] -113455 -61365 -109795 -79565
```

My guess about what is happening is that sometime the connection with the file is not available, so that it cannot be read; and that a default SpatRaster is returned instead of an error. Can you confirm that? The extent would be `(-180, 18-0, -90, 90)` .

**Comment by ealonsogzl** [comment]
I was trying to generate a reproducible example on my laptop with a MODIS .hdf file and I face a read error when I run the following code before the extent error appears, so maybe you are right:

```
library(terra)

rast1 <- rast("~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf")
rast1_val <- values(rast1[[1]])
rast1_ext <- ext(rast1)

read_ext <- function(n) {
  rast.temp <- rast("~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf")
  tast_va.templ <- values(rast.temp[[1]])
  rast_ext.temp <- ext(rast.temp)
  if(!(rast1_ext==rast_ext.temp)){ #asdf_ext!=asdf_ext.temp : not implemented for SpatExtent
    stop(paste("ERROR extent loop: ",n))
  }
}

apply(matrix(1:10000),1,read_ext)

ERROR 4: Failed to open HDF-EOS file "~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf" for swath reading.
Error: (rast) cannot read from ~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf 
```
The error appears after some time
I'll check a bit more in depth my process to see if they are the same issue

**Comment by ealonsogzl** [comment]
I was trying to generate a reproducible example on my laptop with a MODIS .hdf file and I face a read error when I run the following code before the extent error appears, so maybe you are right:

```
library(terra)

rast1 <- rast("~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf")
rast1_val <- values(rast1[[1]])
rast1_ext <- ext(rast1)

read_ext <- function(n) {
  rast.temp <- rast("~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf")
  tast_va.templ <- values(rast.temp[[1]])
  rast_ext.temp <- ext(rast.temp)
  if(!(rast1_ext==rast_ext.temp)){ #asdf_ext!=asdf_ext.temp : not implemented for SpatExtent
    stop(paste("ERROR extent loop: ",n))
  }
}

apply(matrix(1:10000),1,read_ext)

ERROR 4: Failed to open HDF-EOS file "~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf" for swath reading.
Error: (rast) cannot read from ~/MYD09A1.A2017033.h21v05.006.2017045214555.hdf 
```

The error appears after some time
I'll check a bit more in depth my process to see if they are the same issue

Update:
I am not able to generate complete reproducible example. The error use to occur randomly between 1000 and 2000 loops

**Comment by mdsumner** [comment]
@ealonsogzl that hdf file is likely to have complex subdatasets and be a problem for unrelated reasons to this issue, can you point to a source for it? (or share)

**Comment by ealonsogzl** [comment]
@mdsumner Here it is https://we.tl/t-oBa5WprPRl

Answering @rhijmans. The extent it is not the one that you indicate for a default SpatRaster . Here are three pairs of extents that should be equal.  (The seconds are a product calculated from the MODIS 8day reflectance like this one  https://we.tl/t-oBa5WprPRl while the first ones are directly downloaded from https://e4ftl01.cr.usgs.gov/MOTA/MCD64A1.006/ )
```
extent      : -5559753, -4447802, -1111951, -5e-06  (xmin, xmax, ymin, ymax)
extent      : 17791208, 18903159, 0, 1111951  (xmin, xmax, ymin, ymax)
```
```
extent      : -6671703, -5559753, 6671703, 7783654  (xmin, xmax, ymin, ymax)
extent      : 14455357, 15567307, -1111951, 0  (xmin, xmax, ymin, ymax)
```
```
extent      : 13343406, 14455357, -2223901, -1111951  (xmin, xmax, ymin, ymax)
extent      : 4447802, 5559753, 5559753, 6671703  (xmin, xmax, ymin, ymax)
```

The projection is:
```
+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs
```

As you can see in the data source name, the MODIS grid are the same:
```
class       : SpatRaster
dimensions  : 2400, 2400, 5  (nrow, ncol, nlyr)
resolution  : 463.3127, 463.3127  (x, y)
extent      : -5559753, -4447802, -1111951, -5e-06  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs
data sources: HDF4_EOS:EOS_GRID:"./MCD64A1.A2000336.h13v09.006.2017012024716.hdf":MOD_Grid_Monthly_500m_DB_BA:"Burn Date"

class       : SpatRaster
dimensions  : 2400, 2400, 1  (nrow, ncol, nlyr)
resolution  : 463.3127, 463.3127  (x, y)
extent      : 17791208, 18903159, 0, 1111951  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs
data source :./NBR.A2000249.h13v09.006.tif
names       : sur_refl_b02

```

The error seem to appear randomly after many calculations in the same r session. That is why it is not easy to make a reproducible example. It have solved the problem removing the files with the corrupted extent an relaunching the calculations.

**Comment by rhijmans** [comment]
Since this thread has gone dormant, and nobody else as reported this problem, I am closing it for now.
