### ISSUE TITLE
provide layer id of the current layer when plotting with `fun` argument

### ISSUE THREAD

**Issue by btupper** [rspatial/terra#310]
Hi,

I'm wondering if the handling of the plot `fun` in the SpatRaster plot method could be modified ever so slightly to provide an identifier to the current layer being plotted. Currently only index 1 is passed - regardless of the current layer.  I can't decide if that is by design or an oversight.

https://github.com/rspatial/terra/blob/40be7e527ab0af84cd1192bb6db8e0809a526a58/R/plot_raster.R#L449

If `y` were passed instead of 1 then the user function could be "layer aware".  Perhaps like this...

```
if (!is.null(fun)) {
	if (!is.null(formals(fun))) {
		fun(y)
	} else {
		fun()
	}
}
``` 

I can submit a pull request if you prefer.

Thanks for `terra`!

**Comment by rhijmans** [comment]
Thanks for catching that. Fixed now.
