### ISSUE TITLE
Potential bug in focal on large rasters

### ISSUE THREAD

**Issue by jeffreyevans** [rspatial/terra#312]
I am getting some odd output from `terra::focal` where erroneous values are being written in the output (see figure 1). I believe this may be a bug associated with large rasters. I have a 18.1 GB 30m, 6 band image (38700x30922) that I am applying a focal functions to each band. The data has been previously projected from Geographic WGS84 to UTM Zone-44. I am running; R 4.1.0 x86_64-w64-mingw32/x64 and terra_1.3-4 (and just tested against the development version 1.4.1 with the same results).

Nothing tricky in the code. My focal matrix is 7x7.

```
library(terra)
oli <- terra::rast("oli_band01.tif")
f <- terra::focalWeight(oli[[1]], 90, "circle")
  f[f > 0] <- 1   
b1mean <- terra::focal(oli, w=f, fun="mean")
```

In reading just one band, here is my raster information from `print(oli)`

```
class       : SpatRaster 
dimensions  : 38700, 30922, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -405030, 522630, 2961120, 4122120  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=44 +datum=WGS84 +units=m +no_defs 
source      : oli_band01.tif 
name        :      hbb_1 
min value   : 0.04907251 
max value   :   1.921342 
```

Figure 1) Here is a plot of the incorrect focal result. The image on the right is the original and on the left is the result of the focal mean. The red box is a crop area and illustrates one of the mismatches in the output. It looks like portions of the image are being replicated and placed in another portion of the image, almost like a tile indexing error. 

![image](https://user-images.githubusercontent.com/9872383/131747557-8e61f7e4-ef36-497d-9d1e-99e4deff64b5.png)

However, if I crop the data (to the red box) the results are correct (fig 2), which is why I suspect a large raster issue associated with tiling/indexing during processing.

```
sub.oli <- terra::crop(oli, ext(-271140.2, -118953.8, 3688531, 3877242))
  s <- terra::focal(s, w=f, fun="mean")
    dev.new()
      par(mfrow=c(1,2))
        plot(sub.oli)
        plot(s)
```

Figure 2) Correct output on subset

![image](https://user-images.githubusercontent.com/9872383/131747453-f509fd96-b17a-4248-ab03-c304c59d0863.png)

Any ideas on what may be going on here and any potential workaround? And, yes we are getting the same odd results from `raster::focal`. The image stack is rather large (18GB) but [here is a link to download the first band](https://tnc.app.box.com/s/erejg7rmd2kj8qmozt1ffpy0n8dwolgp) (3GB) and I can replicate the issue on a single band pulled from the stack.

**Comment by ailich** [comment]
@jeffreyevans, I downloaded the data you provided and I also get an odd result using `terra` (1.4.3), though my result looks a bit more odd than yours.  I am however not seeing this issue in `raster` (‘3.4.13’). It's also worth noting though that `raster` and `terra` seem to handle the zero weights in a circular focal window differently when using the mean function (rspatial/raster#218 ).

# Plot in terra
![terra_circ](https://user-images.githubusercontent.com/28163862/134829811-9b673a3c-1f00-41a7-b9ce-b7d6c81cb8ce.png)

# Plot in raster
![raster_circ](https://user-images.githubusercontent.com/28163862/134829831-9ce64a59-4975-450e-ab8c-c5e8a0d7c496.png)
er

**Comment by rhijmans** [comment]
Jeffrey, Thank you very much for reporting this, and apologies for the very long wait. I believe this has now been fixed.
