### ISSUE TITLE
No data in NetCDF when red with terra

### ISSUE THREAD

**Issue by BastienFR** [rspatial/terra#314]
Hello,

I'm working on [NARR monolevel rasters](https://psl.noaa.gov/data/gridded/data.narr.monolevel.html) using your terra package.  For one specific variable (Vertical Speed Shear), when I read the raster in `terra` no values are loaded.  I initially thought it was a bug in the data source and wasn't planing to report that here, however I've notice that the same raster is properly loaded in `raster`.  I therefore decided to report the behavior here.  

Here is a reproducible example:

Preparing the session and loading the raster:

```
library(raster)
library(terra)

the_ras <- paste(tempdir(), "/vwnd.10m.2015.nc", sep = "")

utils::download.file("ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/vwsh.tropo.2015.nc",
                     the_ras, 
                     method = "auto", 
                     mode = "wb", 
                     cacheOK = TRUE, 
                     extra = getOption("download.file.extra"))
```

If I load it in raster:

```
with_raster <- stack(the_ras)
   Loading required namespace: ncdf4
plot(with_raster[[222]])
table(is.na(values(with_raster)))

   FALSE     TRUE 
34684125   601520 
```

making the plot:
![image](https://user-images.githubusercontent.com/10979480/132043555-87409ff6-c192-455d-b995-8f338e24fbcd.png)

But when I do the same in terra:

```
with_terra <- rast(the_ras)
plot(with_terra[[222]])
table(is.na(values(with_terra)))

    TRUE 
35285645 
```

and an empty plot:
![image](https://user-images.githubusercontent.com/10979480/132043677-727d5643-c223-4919-b22d-d42fc50311f0.png)

Is there a way to have it to work in terra as well?  Thanks.

**Comment by bappa10085** [comment]
I am also facing the same issue with h5 files. Here is an example
```
library(smapr)
library(raster)

start_date <- as.Date("2015-03-31")
end_date <- as.Date("2015-04-01")
date_sequence <- seq(start_date, end_date, by = 1)

available_data <- find_smap(id = 'SPL4SMAU', 
                            dates = date_sequence, 
                            version = 5)

local_files <- download_smap(available_data, overwrite = FALSE, verbose = FALSE)

library(terra)

#Load the covariate rasters
#Load the covariate rasters
files <- list.files(path="C:\\Users\\nn\\AppData\\Local\\smap\\smap\\Cache", 
                    pattern = "\\.h5$", full.names = TRUE)

r <- rast(files)
r

#> class       : SpatRaster 
#> dimensions  : 1624, 3856, 528  (nrow, ncol, nlyr)
#> resolution  : 0.0002593361, 0.0006157635  (x, y)
#> extent      : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#> sources     : sm_profile_analysis  
#>               sm_profile_analysis_ensstd  
#>               sm_rootzone_analysis  
#>               ... and 525 more source(s)
#> names       : sm_pr~lysis, sm_pr~nsstd, sm_ro~lysis, sm_ro~nsstd, sm_su~lysis, sm_su~nsstd, ... 

global(r["sm_surface_analysis"], fun="min")

#>                               min
#> sm_surface_analysis           NaN
#> sm_surface_analysis_ensstd    NaN
#> sm_surface_analysis.1         NaN
```

**Comment by rhijmans** [comment]
@bappa10085: you should use `na.rm=TRUE` to remove the NAs from the computation of `min`.

**Comment by bappa10085** [comment]
It is working now after using `na.rm=TRUE`. Actually, I usually get `min values` and `max values` below `names` like
```
class       : SpatRaster 
dimensions  : 77, 101, 3  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
source      : logo.tif 
red-grn-blue: 1, 2, 3 
names       : red, green, blue 
min values  :   0,     0,    0 
max values  : 255,   255,  255 
``` 
But I am unable to see it for the SMAP data as shown in the previous example.

**Comment by rhijmans** [comment]
@BastienFR 

Just to confirm the problem with this file, and that it does not occur with other files from the same source: 


```
options(timeout = max(300, getOption("timeout")))

ftp1 <- "ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/vwsh.tropo.2015.nc"
f1 <- basename(ftp1)
if (!file.exists(f1)) download.file(ftp1, f1, mode="wb", extra="timeout=3600")
sd1 <- "NETCDF:\"vwsh.tropo.2015.nc\":vwsh"

# another file from same server
ftp2 <- "ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/veg.1998.nc"
f2 <- basename(ftp2)
if (!file.exists(f2)) download.file(ftp2, f2, mode="wb")
sd2 <- "NETCDF:\"veg.1998.nc\":veg"


library(terra)
r1 <- rast(f1)
r2 <- rast(f2)

minmax(r1[[1]] * 1)
#     vwsh_1
#[1,]    NaN
#[2,]    NaN

# the other file
minmax(r2[[1]] * 1)
#     veg_1
#[1,]   1.0
#[2,]  94.6

#works with "raster" --- presumably because it does not use GDAL to read the file
library(raster)
rr <- raster(f1)
minValue(rr*1)
#[1] 0.0004114582

# but fails with "rgdal" that, like "terra" also uses GDAL to read the file 
library(rgdal)
g <- brick(readGDAL("NETCDF:\"vwsh.tropo.2015.nc\":vwsh"))
minValue(g[[1]])
#[1] NA
```

I have not been able to find out why this happens. It might be a GDAL bug, and I will report this on the GDAL github,

**Comment by rhijmans** [comment]
This was indeed caused by an issue in GDAL. The file specifies a valid range between 0 and 0.045. GDAL assumed the range to be integers, thus truncating the valid range to 0-0, and making all values invalid (NA). This has now been fixed in GDAL code but it will take a while before that becomes available to terra (unless you install GDAL from source).

As a work-around I have added a new argument to `rast` that takes "GDAL open options". In this case you can use the option "HONOUR_VALID_RANGE=NO"  (see [here](https://gdal.org/drivers/raster/netcdf.html)). 

```
options(timeout = max(300, getOption("timeout")))
ftp1 <- "ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/vwsh.tropo.2015.nc"
f1 <- basename(ftp1)
if (!file.exists(f1)) download.file(ftp1, f1, mode="wb", extra="timeout=3600")

library(terra)
r <- rast(f1, opts="HONOUR_VALID_RANGE=NO")
```

In this case you would still need to deal with the invalid (missing) values. Perhaps like this

```
x <- ifel(r < 0, NA, r)
plot(x[[222]])
```

**Comment by BastienFR** [comment]
That is great!  Thanks for having fix this.  And sorry for having gone through you instead of gdal directly, I didn't realized it was a gdal problem...

**Comment by rhijmans** [comment]
>  I didn't realize it was a gdal problem

That was far from obvious (to me) and it makes sense to report an issue where you encounter it. I am glad you reported it, so that the problem will eventually disappear.
