### ISSUE TITLE
writeVector causes R session to abort

### ISSUE THREAD

**Issue by timpwhite** [rspatial/terra#319]
Using writeVector when trying to write filename,shp, filetype="ESRI Shapefile" causes R session to abort. I found this to happen when the vector file does not contain geometries, which in my case was an error not to include the geometries. Nevertheless, perhaps terra could throw a warning or error message instead of crashing the R session.

R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

terra_1.3-22

**Comment by rhijmans** [comment]
Thank you, I now get:

```
library(terra)
#terra version 1.4.2
v <- vect()
writeVector(v, "test.shp", overwrite=TRUE)
#Error: [writeVector] no geometries to write
```
