### ISSUE TITLE
R crashes  when using mask()

### ISSUE THREAD

**Issue by shoebodh** [rspatial/terra#32]
I wonder why R keeps crashing when executing mask() for this rast object

library(terra)
library(sf)
library(magrittr)

##I am manually creating these to match the raster and vector I am working with.

aras = rast(nrow = 1292, 
            ncol = 2108, 
            xmin = -51555, 
            xmax = 11685, 
            ymin = 2174085,
            ymax = 2212845, 
            resolution = c(30, 30))
values(aras) = 1.0
acrs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,-0,-0,-0,0 +units=m +no_defs "
crs(aras) = acrs

X = c(11663.3888763746 ,  -40561.4152324756 ,  -41024.9820774198 , 
      -43953.4107328448 ,  -45024.7756178527 ,  -45750.2911400045 ,  
      -50620.904629191 ,  -51553.6949808968 ,  -51335.2668440301 ,  
      -51479.5322561605 ,  -49649.6378603617 ,  -46833.4110826737 ,  
      -45690.6631696934 ,  -44706.1217890674 ,  -43610.6930135799 ,  
      -10715.543899408 ,  -3054.16560716853 ,  11606.241540202 ,  
      11663.3888763746)

Y = c(2174090.09659196 ,  2174187.40368597 ,  2177995.19835269 , 
      2184931.31950377 ,  2184754.93027911 ,  2186014.66253283 ,  
      2190124.82402795 ,  2193237.93273675 ,  2195487.41540441 ,  
      2197215.42331215 ,  2199202.18388163 ,  2203965.95290691 ,  
      2203763.50619636 ,  2203926.07514223 ,  2212201.17543389 ,  
      2212632.83026156 ,  2212841.20869756 ,  2212086.67270691 ,  
      2174090.09659196)
stp = st_polygon(list(cbind(X, Y)))

bnd = st_sf(val = 1.0, st_sfc(stp), crs = acrs)
bnd_vect = as_Spatial(bnd) %>% vect()

#This fails(r crashes everytime)
aras_masked1 = mask(aras, bnd_vect)

#This succeeds with no problem though. 
aras_masked2 = raster::mask(raster::raster(aras), bnd)

For smaller objects there was not problem (though I didn't do extensive checking).

Checked with both R 4.0.0 and 3.6.3 versions on a windows machine
Here is the session info
sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.0

**Comment by rhijmans** [comment]
Thanks for reporting and the useful example.  The error came from `rasterize`. I can now do 

```
library(terra)
r <- rast(nrow = 1292, ncol = 2108, xmin = -51555, xmax = 11685, ymin = 2174085, ymax = 2212845)
values(r) <- 1.0

X = c(11663.3888763746 , -40561.4152324756 , -41024.9820774198 , -43953.4107328448 , -45024.7756178527 , -45750.2911400045 , -50620.904629191 , -51553.6949808968 , -51335.2668440301 , -51479.5322561605 , -49649.6378603617 , -46833.4110826737 , -45690.6631696934 , -44706.1217890674 , -43610.6930135799 , -10715.543899408 , -3054.16560716853 , 11606.241540202 , 11663.3888763746)

Y = c(2174090.09659196 , 2174187.40368597 , 2177995.19835269 , 2184931.31950377 , 2184754.93027911 , 2186014.66253283 , 2190124.82402795 , 2193237.93273675 , 2195487.41540441 , 2197215.42331215 , 2199202.18388163 , 2203965.95290691 , 2203763.50619636 , 2203926.07514223 , 2212201.17543389 , 2212632.83026156 , 2212841.20869756 , 2212086.67270691 , 2174090.09659196)

bnd <- vect(cbind(X,Y), "polygons")

x <- rasterize(bnd, r)
# or
m <- mask(r, bnd)

```
