### ISSUE TITLE
[enhancement] writeRaster: add 'bylayer' argument

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#320]
Would it be possible to add the `bylayer` argument to the  `writeRaster` function, similarly to the same function in the  `raster` package?

I'm asking this because I tried to use a `for` loop to replace the use of the `bylayer` argument when writing a `SpatRast` object with thousand of layers, and I realised that the use of `writeRaster` with `bylayer` argument (i.e., using the `raster` package) is orders of magnitude faster than my loop (i.e, some **hours** instead of some **weeks**).

**Comment by rhijmans** [comment]
Thanks, the functionality is available, see below, but it was not documented (it now is). Instead of a single filename you can supply a vector of filenames that has the same length as the number of layers in the SpatRaster. 

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
ff <- paste0(names(s), ".tif")
z <- writeRaster(s, ff, overwrite=T)
z

#class       : SpatRaster 
#dimensions  : 77, 101, 3  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#sources     : red.tif  
#              green.tif  
#              blue.tif  
#names       : red, green, blue 
#min values  :   0,     0,    0 
#max values  : 255,   255,  255 
```
