### ISSUE TITLE
Correcting the origins

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#326]
If the origins of two raster datasets are marginally apart, then in **raster** it is possible to:

1. Correct the origin with the `origin` function.
2. Increase the `tolerance` argument  of `raster::rasterOptions()`.

These options are not possible with **terra** - the `origin` function does not allow to changing values (only to see the existing origins), while the `terraOptions()` does not have a `tolerance` argument.

Are there any alternatives to this issue in **terra**?

**Comment by rhijmans** [comment]
I can now do:

```
library(terra)
r <- rast(ncol=10, nrow=10, xmin=0.4, xmax=10.4, ymin=0, ymax=10)
origin(r)
origin(r) <- c(0,0)
origin(r)

r1 <- rast(ncol=10, nrow=10, xmin=0, xmax=10, ymin=0, ymax=10, vals=1:100)
r2 <- rast(ncol=10, nrow=10, xmin=0.2, xmax=10.2, ymin=0, ymax=10, vals=1:100)
r1 + r2 
#Error: [+] extents do not match
terraOptions(tolerance=.5)

r1 + r2 
#class       : SpatRaster 
#dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0, 10, 0, 10  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : memory 
#name        : lyr.1 
#min value   :     2 
#max value   :   200 
```

"tolerance" is a fraction of the spatial resolution.

**Comment by Nowosad** [comment]
Thanks.
