### ISSUE TITLE
Downsample function?

### ISSUE THREAD

**Issue by mtennekes** [rspatial/terra#330]
Hi Robert, is there a downsample function in terra? So one that takes every k-th tile (with k being an integer > 1)  in both x and y dimension.

Probably I can use `aggregate(r, fact = k, fun = function(x) x[1])`, but is there also a dedicated function? One that is similar to `stars:::st_downsample` (which I hope will be exported).

Reason I ask is fast plotting in tmap (https://github.com/r-tmap/tmap/issues/597)

**Comment by ailich** [comment]
@mtennekes the [terra::plot](https://github.com/rspatial/terra/blob/master/R/plot.R) seems to use `spatSample` function to downsample rasters for plotting `x <- spatSample(x, maxcells, method="regular", as.raster=TRUE)`

**Comment by rhijmans** [comment]
@ailich is correct. `spatSample` can do that, and this is what is used in `terra` because on large files it is much faster than aggregate.   And it also avoids averaging categorical variables that have been declared as such.
