### ISSUE TITLE
'buffer' strange behaviour with lines

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#332]
Hello,
'buffer' seems to be working as expected on points and polygons, but with lines the buffer does not stay around them, but closes its polygons in the wrong place -- I'm probably not explaining myself very clearly, but here's an example:
```
lon <- c(-116.8, -114.2, -112.9, -111.9, -114.2, -115.4, -117.7)
lat <- c(41.3, 42.9, 42.4, 39.8, 37.6, 38.3, 37.6)
lonlat <- cbind(lon, lat)
lns <- vect(lonlat, type = "lines", crs = "+proj=lonlat")
plot(lns)
plot(buffer(lns, width = 10000), border = "blue", add = TRUE)
```
The expected behaviour would be something like:
`plot(raster::buffer(as(lns, "Spatial"), width = 0.2), border = "darkgreen", lwd = 2, add = TRUE)`
I'm using the development version of 'terra' (and 'raster') from the 'rspatial' universe.

**Comment by rhijmans** [comment]
Thank you very much for reporting that. Fixed now.
