### ISSUE TITLE
writeVector(...,driver="KML") swaps lat and lon

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#333]
Suppossed to be Belgium:
```
require(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
plot(v)
writeVector(v, "v.kml",filetype="KML")
```
Also, not all table fields are displayed in GE,
![image](https://user-images.githubusercontent.com/6074054/133601738-77e022ac-c78c-41cb-814d-770c68dc2bac.png)

**Comment by rhijmans** [comment]
This happens because the CRS reports that the coordinates are in latitude/longitude order. In spatial data software this has traditionally been ignored, and one assumes that it is always longitude/latitude. It seems that the KML GDAL-driver does not do that. 

The original CRS

```
v <- vect(f)
cat(crs(v), "\n")
#GEOGCRS["WGS 84",
#    DATUM["World Geodetic System 1984",
#        ELLIPSOID["WGS 84",6378137,298.257223563,
#            LENGTHUNIT["metre",1]]],
#    PRIMEM["Greenwich",0,
#        ANGLEUNIT["degree",0.0174532925199433]],
#    CS[ellipsoidal,2],
#        AXIS["geodetic latitude (Lat)",north,
#            ORDER[1],
#            ANGLEUNIT["degree",0.0174532925199433]],
#        AXIS["geodetic longitude (Lon)",east,
#            ORDER[2],
#            ANGLEUNIT["degree",0.0174532925199433]],
#    ID["EPSG",4326]] 
``` 

Change it to the generic lon/lat 

```
crs(v) = "+proj=longlat"
cat(crs(v), "\n")
#GEOGCRS["unknown",
#    DATUM["World Geodetic System 1984",
#        ELLIPSOID["WGS 84",6378137,298.257223563,
#            LENGTHUNIT["metre",1]],
#       ID["EPSG",6326]],
#    PRIMEM["Greenwich",0,
#        ANGLEUNIT["degree",0.0174532925199433],
#        ID["EPSG",8901]],
#    CS[ellipsoidal,2],
#        AXIS["longitude",east,
#            ORDER[1],
#            ANGLEUNIT["degree",0.0174532925199433,
#                ID["EPSG",9122]]],
#        AXIS["latitude",north,
#            ORDER[2],
#            ANGLEUNIT["degree",0.0174532925199433,
#                ID["EPSG",9122]]]] 
``` 

Note that the axis order has changed. Now you can do 

```
writeVector(v, "v.kml",filetype="KML", overwrite=TRUE)
``` 

So that is a work-around. I could perhaps add an argument to writeVector to deal with this; and or do this automatically for KML; but there are also GDAL options. I need to study this a bit first.

**Comment by aloboa** [comment]
Thanks. I understand this is just a problem of this particular shapefile, too bad it is precisely the one included as example in the ggmap package and left me quite astonished.
I would say just add a note to the writeVector help page (actually an example for KML output could be helpful) and close the ticket

**Comment by rhijmans** [comment]
This

```
library(terra)
v <- vect(system.file("ex/lux.shp", package="terra"))
writeVector(v, "v.kml") 
``` 

Now puts Luxembourg in the right place. 
This is a general issue related to the changes in the PROJ library and may create problems in other instances as well, but I think writeVector should now be safe.
