### ISSUE TITLE
`c` not works when using in do.call

### ISSUE THREAD

**Issue by kongdd** [rspatial/terra#334]
Very weird result. `r_dci` is a list of `rast` object. 
When using the combine function, `list(r_dci[[1]], r_dci[[2]]) %>% do.call(c, .)` works, while `r_dci[1:2] %>% do.call(c, .)` not. 
Any clue what is the problem?

![1631797677(1)](https://user-images.githubusercontent.com/9815742/133617745-ad4455b4-3b7a-4ace-aea7-346bd1e4449c.png)

**Comment by kongdd** [comment]
Sorry. Here is my example: 

``` r
library(terra)
#> terra version 1.3.22
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
x <- list(r1 = r, r2 = r)
do.call(c, x)
#> $r1
#> class       : SpatRaster 
#> dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
#> resolution  : 0.008333333, 0.008333333  (x, y)
#> extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#> source      : elev.tif 
#> name        : elevation 
#> min value   :       141 
#> max value   :       547 
#> 
#> $r2
#> class       : SpatRaster 
#> dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
#> resolution  : 0.008333333, 0.008333333  (x, y)
#> extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#> source      : elev.tif 
#> name        : elevation 
#> min value   :       141 
#> max value   :       547
```

<sup>Created on 2021-09-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kongdd** [comment]
Is this behavior expected?

**Comment by rhijmans** [comment]
This happens because you use a named list. Function `c` is generic -- meaning there are different implementations, and the implementation used depends on the class of the first argument(s). In this case that is argument `x`. If you do not name your list, the arguments are matched by position. If you do name them, you should use `x` to make sure you get the version of `c` you want. 
```
names(x)[1] <- "x"
do.call(c, x)
#class       : SpatRaster 
#dimensions  : 90, 95, 2  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#sources     : elev.tif  
#              elev.tif  
#names       : elevation, elevation 
#min values  :       141,       141 
#max values  :       547,       547 
```

**Comment by kongdd** [comment]
Thanks for your detailed explaination. I didn't realized this problem before. Understand now. 
Thank you!
