### ISSUE TITLE
rasterize() doesn't create an "ID" column in raster's cats() table

### ISSUE THREAD

**Issue by tabrasel** [rspatial/terra#337]
An "ID" column is automatically generated whenever I create a new factor raster with `rast()`. However, no "ID" column is included when I create a factor raster using `rasterize()`.

```
file <- system.file("ex/lux.shp", package="terra")
polys <- terra::vect(file)
grid <- terra::rast(polys, ncols=75, nrows=100)

r1 <- terra::rast(vals = c("a", "b", "c"))
r2 <- terra::rasterize(polys, grid, "NAME_2")

terra::cats(r1)
terra::cats(r2)
```

Is this expected behavior? I think including an ID column is very convenient, though it's easy enough to build and add manually.

**Comment by rhijmans** [comment]
Thanks! Fixed now.
