### ISSUE TITLE
'plot()' doesn't reset graphical parameters

### ISSUE THREAD

**Issue by dfriend21** [rspatial/terra#340]
When plotting a `SpatRaster`, the graphical parameter `mar` is not reset after plotting.

Example:

```
library(terra)
dev.off() # make sure parameters are at their default settings

rst <- rast(matrix(1, nrow = 100, ncol = 100))

par(mfrow = c(2,2))

mar1 <- par("mar")

plot(1,1, main = "before")
plot(rst)
plot(1,1, main = "after")

mar2 <- par("mar")

mar1
#> [1] 5.1 4.1 4.1 2.1
mar2
#> [1] 3.1 3.1 2.1 7.1
```
![Screen Shot 2021-09-21 at 1 45 23 PM](https://user-images.githubusercontent.com/7896671/134245011-cf899c58-e31f-4343-ac8d-6a751cb0e1d2.png)

**Comment by edzer** [comment]
This is probably deliberate: 
* if if wouldn't set margin, you'd get ugly large margins on maps
* if it would reset margin before returning, you couldn't add another layer (e.g. some vector data) on top of the raster

`sf::plot.sf` and `stars::plot.stars` reset the plotting device, but allow specifying `reset = FALSE` to prevent this for allowing incremental adding. Every choice here is a compromise of some sort.

**Comment by dfriend21** [comment]
Thanks for the response. And your explanation makes sense - I suppose it comes down the developers' preference. However, I like the idea of having a `reset` parameter. 

It might be helpful to explain the context in which I came across this. I'm doing some analysis of some simulation output. For each simulation run, I'm outputting as an image a grid of about 15 plots that summarize various aspects of the simulation. Several of these plots are rasters. So when I looked at the output plots, the margins for all of my non-raster plots were inconsistent with my previous settings. If `plot(<SpatRaster>)` doesn't reset the margins, I'll have to manually reset the graphical parameters after the raster plots in order for my other plots to look right - and given that I have multiple raster plots mixed in with non-raster plots, I'd probably have to do this multiple times. Granted, I can certainly do that, but it's kind of a pain, and it seems to me that the resetting of parameters should be handled within the `plot(<SpatRaster>)` function rather than being handled by the user.

So with all that said, I guess I'm advocating for the addition of a `reset` parameter - if it were to be added and the default set to `FALSE`, it wouldn't have any impact on any existing code, and it'd be very useful for situations like the one I described above.

**Comment by edzer** [comment]
You can also write a small wrapper function that does just that, plot the raster and resett `mar`.

**Comment by dfriend21** [comment]
That's a good point, and that's probably what I'll do - thanks for the suggestion. But I still think that there should be some way within the `plot(<SpatRaster>)` function itself to force the parameters to reset so that it doesn't cause unwanted side effects.

**Comment by rhijmans** [comment]
Thanks for the report and the discussion. I have added an argument `reset=FALSE` to `plot`. 
This can affect the plotting of additional objects (e.g. lines, points) that are added to the map. In the example below that can be circumvented with `xpd=TRUE`.

```
library(terra)
#terra version 1.4.4
dev.off() # make sure parameters are at their default settings
rst <- rast(system.file("ex/elev.tif", package="terra"))
v <- vect(system.file("ex/lux.shp", package="terra"))
par(mfrow = c(2,2))
mar1 <- par("mar")
plot(1,1, main = "before")
plot(rst, reset=TRUE)
lines(v, xpd=TRUE)
plot(1,1, main = "after")
mar2 <- par("mar")
mar1
mar2
mar1
#[1] 5.1 4.1 4.1 2.1
mar2
#[1] 5.1 4.1 4.1 2.1
```
