### ISSUE TITLE
'terra::extract()' runs significantly slower than 'raster::extract()'

### ISSUE THREAD

**Issue by dfriend21** [rspatial/terra#341]
First of all, thanks for all the work you've done in creating both `terra` and `raster`.

I've noticed that `terra::extract()` runs significantly slower than `raster::extract()`. Here's a reproducible example where I timed the two functions while increasing the number of points:

```
library(raster)
library(terra)

nr <- 500
nc <- nr
mat <- matrix(runif(nr * nc), nrow = nr)

raster <- raster(mat)
terra <- rast(t(mat))

n <- seq(100000, 2000000, by = 100000)
ext <- ext(terra)
pts <- cbind(runif(max(n), ext[1], ext[2]), runif(n, ext[3], ext[4]))

times_list <- lapply(1:length(n), function(i) {
  print(i)
  times_i <- bench::mark(extract(raster, pts[1:n[i],]), extract(terra, pts[1:n[i],]), check = FALSE, time_unit = "ms")  
  times_i$package <- c("raster", "terra")
  times_i$n <- n[i]
  return(times_i)
})

times <- do.call(rbind, times_list)

library(ggplot2)
ggplot(times, aes(x = n, y = median, color = package)) + 
  geom_point()  + 
  geom_line() + 
  xlab("# of points") + 
  ylab("time (ms)")
```

On my machine this produced the following plot:
![image](https://user-images.githubusercontent.com/7896671/134390181-10409242-2884-46cf-8baf-16f2514fb06c.png)

I also looked at the ratio between the times:

```
r_times <- times$median[times$package == "raster"]
t_times <- times$median[times$package == "terra"]

cbind(n, ratio = t_times/r_times)
```

which gave the following output:

```
            n      ratio
 [1,]  100000 113.790646
 [2,]  200000 116.490512
 [3,]  300000 120.241925
 [4,]  400000 116.737464
 [5,]  500000 111.687035
 [6,]  600000 120.136605
 [7,]  700000  61.268655
 [8,]  800000 123.102067
 [9,]  900000  73.737306
[10,] 1000000 107.970864
[11,] 1100000 116.472315
[12,] 1200000 114.363116
[13,] 1300000  81.381517
[14,] 1400000  71.721777
[15,] 1500000   9.855907
[16,] 1600000  78.552998
[17,] 1700000  82.419209
[18,] 1800000  71.241145
[19,] 1900000  70.444750
[20,] 2000000  88.691564
```

Also, here's the contents of the relevant columns of the `times` data frame, in case that's useful (`median` is in milliseconds):

```
   package       n  median
   <chr>     <dbl>   <dbl>
 1 raster   100000    3.30
 2 terra    100000  375.  
 3 raster   200000    6.28
 4 terra    200000  732.  
 5 raster   300000    9.35
 6 terra    300000 1124.  
 7 raster   400000   12.5 
 8 terra    400000 1462.  
 9 raster   500000   16.3 
10 terra    500000 1821.  
11 raster   600000   19.8 
12 terra    600000 2380.  
13 raster   700000   42.7 
14 terra    700000 2616.  
15 raster   800000   26.1 
16 terra    800000 3215.  
17 raster   900000   45.2 
18 terra    900000 3331.  
19 raster  1000000   35.3 
20 terra   1000000 3806.  
21 raster  1100000   37.4 
22 terra   1100000 4350.  
23 raster  1200000   40.4 
24 terra   1200000 4625.  
25 raster  1300000   69.1 
26 terra   1300000 5620.  
27 raster  1400000   75.1 
28 terra   1400000 5390.  
29 raster  1500000  611.  
30 terra   1500000 6023.  
31 raster  1600000   82.7 
32 terra   1600000 6495.  
33 raster  1700000   82.0 
34 terra   1700000 6756.  
35 raster  1800000   97.5 
36 terra   1800000 6947.  
37 raster  1900000  108.  
38 terra   1900000 7580.  
39 raster  2000000   85.2 
40 terra   2000000 7555.  
```

And here's some info about my system from `sessionInfo()`

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7
```

I'm using version `1.3-4` of `terra` and version `3.4-13` of `raster`.

UPDATE - after posting I realized that my version of `terra` was behind the current CRAN version (`1.3-22`). I updated and then reran the code and got pretty much the same results.

**Comment by tungmilan** [comment]
This is surprising. About 6 months ago I tested the `extract` function from both packages on 1000+GB dataset and found that `terra::extract` was significantly faster than `raster::extract`

**Comment by edzer** [comment]
That was probably not using in-memory rasters, as the test above does.

**Comment by rhijmans** [comment]
In `terra`, `extract`  is much faster for lines and polygons, but I have not given much attention to  `extract` with points ---- as that was reasonably fast in `raster`.

**Comment by dfriend21** [comment]
As a temporary "fix", in the `terra::extract()` function, could you simply convert the `SpatRaster` to a `Raster` object and then use `raster::extract()`? Obviously you'd only want to do it in situations where `terra::extract()` is slower than `raster::extract()` (which appears to be when using points on an in-memory raster?).  It'd be a bit of a hack, though, and not a long-term solution. I know that the user can just as easily convert it to a `Raster` themselves, but it'd be nice if `terra` had comparable speeds in this situation.

**Comment by rhijmans** [comment]
I now get about the same speeds: 

![extract2](https://user-images.githubusercontent.com/11481397/146628577-e4d7ba5d-99cc-4e13-9796-aba7a08a8b09.png)

More can be done here, no doubt, but for now this may be good enough.

**Comment by eragrostis** [comment]
I'm still getting quite slow speeds for extract. Extracting 100,000 points for a 4-layer raster (resolution of 20880 x 43200 cells) takes over 5 minutes. Based on the chart in the last post that should have taken less than a second. 

Any advice for debugging this? 

I think the rast is stored in memory as I just created it by using terra::subset on a rast with 20 layers.

**Comment by kadyb** [comment]
@eragrostis, this is pretty big raster. Could you check `inMemory()`? I see this:

```r
library("terra")

v = rnorm(20000 * 40000 * 4)
r = rast(nrows = 20000, ncols = 40000, nlyrs = 4, vals = v)
rm(v)
smp = spatSample(ext(r), size = 500000, lonlat = TRUE, as.points = TRUE)
inMemory(r)
#> [1] TRUE

system.time({e = extract(r, smp)})
#>  user  system elapsed 
#> 0.309   0.057   0.365
```

**Comment by eragrostis** [comment]
Also, running your code on my system gave the following, further suggesting something my raster is problematic rather than my system. 

```
> v = rnorm(20000 * 40000 * 1) #don't have enough memory for 4 layers
> r = rast(nrows = 20000, ncols = 40000, nlyrs = 1, vals = v)
> rm(v)
> smp = spatSample(ext(r), size = 500000, lonlat = TRUE, as.points = TRUE)
> inMemory(r)
[1] TRUE

>system.time({e = extract(r, smp)})
  user  system elapsed 
   0.42    0.02    0.53 
```

**Comment by kadyb** [comment]
> Also, running your code on my system gave the following, further suggesting something my raster is problematic rather than my system.

I think it's expected that processing a file from disk in blocks is slower than it would be in memory.

> I also did try converting it to a raster::raster and running raster::extract() and that ran much quicker.

I think in this case instead of using `raster()` you should use `stack()` because `raster()` returned one layer (not 5?). That's why it seems to be faster.

**Comment by eragrostis** [comment]
> I think it's expected that processing a file from disk in blocks is slower than it would be in memory.

I understand that, but wouldn't you then expect that task manager would show my disk usage being maxed rather than CPU usage? But that is not what I observe.

**Comment by HassanMasoomi** [comment]
I have noticed slower performance when extracting points from large rasters using the `terra` package compared to the `raster` package, with `terra` being about 10 times slower. However, when I try to create a reproducible example, `terra` consistently performs better. Is there something specific causing the slowdown in my actual use case?
