### ISSUE TITLE
Focal statistics in terra vs raster

### ISSUE THREAD

**Issue by NaturalCapitalSolutions** [rspatial/terra#347]
Hi, I have found that running focal statistics with a user defined function with large rasters is slow and sometimes breaks the R session. I currently avoid the issue by increasing raster cell size. I thought that since terra is faster this issue may not occur and I may be able to deliver the models I am running at the desired resolution. 

I am using a much smaller dataset than usual to test the terra approach and when running focal stats with a user defined function I get the following error message: 

Error in x@ptr$focalValues(w, fillvalue, b$row[i] - 1, b$nrows[i]) : 
  std::bad_alloc

I don't think I'm running out of RAM as I have 64GB and when I check the graph of my memory usage there is no spike. The raster I am processing is 2089kb and the raster package is able to process the focal stats in this raster with a user defined function. 

I have found this thread 
https://github.com/rspatial/terra/issues/86
but it doesn't seem to solve my issue.

Focal in the terra package works fine on the same raster when not using a user defined function. Is there something I missed/misunderstood in the thread that may actually help me? 

I have also found a difference between the outputs of terra and raster when running focal (this time not using a user defined function but a simple mean). 
This is the input raster I use to perform focal statistics.
![Initial raster](https://user-images.githubusercontent.com/88135376/135463800-6d371655-9853-4541-b635-6762565498df.PNG)

The following image shows the output of a focal statistic on the input raster using terra::focal with a circular window of 300m and I'm performing a mean. 

![Terra_focal](https://user-images.githubusercontent.com/88135376/135464044-1e21e898-2307-4bf4-aa56-795a0856b744.PNG)
This other image shows the same operation using raster::focal. 
![Raster_focal](https://user-images.githubusercontent.com/88135376/135464210-d2968176-44dd-4712-8370-8e64da457d67.PNG)

As you can see the raster version produces a raster that has NAs in the background, while terra seems to put a mean value in the background instead. 
I think there could be something crucial I am missing here about how the function works, but ultimately I would like to get the same output I had from raster::focal using terra::focal. 
Thank you for the amazing job you are doing!

**Comment by ailich** [comment]
@NaturalCapitalSolutions, would you be able to provide a small reproducible example of the issue you're running into, as that'd make it easier to debug? E.g. here's a small example of how to apply a custom function using both `raster` and `terra`, and they provide the same result. I will note however, that there does appear to be a difference in the behavior of `raster::focal` and `terra::focal` for circular windows, particularly with the `mean` function (see issue, rspatial/raster#218). Additionally, the default behavior for `terra::focal` is `na.rm=TRUE`, while for `raster::focal`, it is `na.rm=FALSE`
```
r_rast<- raster::raster(volcano) #create raster and terra objects using built in volcano dataset
r_terra<- terra::rast(volcano)

w<- matrix(data=1, nrow=5, ncol=5) #square 5x5 matrix

my_range_fun<- function(x, na.rm){
  out<- max(x,na.rm = na.rm)-min(x,na.rm=na.rm)
  return(out)
} #Function to calculate range in focal window

focal_rast<- raster::focal(r_rast, w=w, fun = my_range_fun, na.rm=TRUE)
plot(focal_rast)
```


![focal_rast](https://user-images.githubusercontent.com/28163862/135527934-2d8897cd-eb47-43a2-8ea7-41f1e1a0b01a.png)

```
focal_terra<- terra::focal(r_terra, w=w, fun = my_range_fun, na.rm=TRUE)
plot(focal_terra)
```


![focal_terra](https://user-images.githubusercontent.com/28163862/135527959-91524677-9480-4796-91ab-b0ba0e27ef74.png)

```
terra::rast(focal_rast)- focal_terra #Difference between objects is zero
# min value   :     0 
# max value   :     0 
```

**Comment by NaturalCapitalSolutions** [comment]
Apologies for the poor explainations, I'm a newbie. 
I'm attaching the input raster here hopefully that helps

[input_rast.zip](https://github.com/rspatial/terra/files/7265554/input_rast.zip)

r_rast<- raster::raster("input_rast.tif") 
r_terra <- terra::rast("input_rast.tif")

w_rast <- focalWeight(r, local, "circle")   # search window 
w_rast[w_rast > 0] <- 1     # replacing weights by 1 to get total 

w_terra <- focalMat(r, 300, "circle")
w_terra[w_terra > 0] <- 1     # replacing weights by 1 to get total 

focal_rast<- raster::focal(r_rast, w=w_rast, fun = mean, na.rm=TRUE)
focal_terra<- terra::focal(r_terra, w=w_terra, fun = mean, na.rm=TRUE)
If you plot these 2 rasters you'll see terra::focal output has the mean values as a background, unlike raster. 

This other bit of code is the one that works in raster but gives me std::bad_alloc when run in terra. 

mymean_rast <- function(x){mean(x[ w_rast != 0 ], na.rm=TRUE)}
mymean_terra <- function(x){mean(x[ w_terra != 0 ], na.rm=TRUE)}

focal_rast2 <- raster::focal(r_rast, w = w_rast, fun = mymean_rast)
focal_terra2 <- terra::focal(r_terra, w = w_terra, fun = mymean_terra)

**Comment by ailich** [comment]
@NaturalCapitalSolutions, I did not know you could subset by the window in 'raster', that's very cool! I'm also getting that error in `terra::focal` though for the custom function. However, I am not getting that issue of a background value in `terra` so try installing the latest version with `install.packages('terra', repos='https://rspatial.r-universe.dev')`. As of now, `terra::focal` automatically removes the zero's when using the `mean` function so it provides identical results  (down to like 18 decimal places) to using `raster::focal` with your custom function and `pad=TRUE` to deal with edge effects. It does however produce different results than passing `mean` to `focal::raster`. In the past, NA's could be used in circular focal windows in raster but that doesn't seem to be working at the moment (rspatial/raster#222). Using either `focal::raster` with your custom function or `focal::terra` with `mean` should give proper results.

```
packageVersion("raster")
#[1] ‘3.5.0’
packageVersion("terra")
#‘1.4.6’

count_NA<- function(x){
  if(class(x)=="RasterLayer"){
    raster::freq(x, value=NA)
  } else{
    terra::freq(x, value=NA, bylayer=FALSE)[2]
  }
}

mymean <- function(x){mean(x[w != 0], na.rm=TRUE)}

r_rast<- raster::raster("C://Users/socce/Downloads/input_rast.tif")
r_terra<- terra::rast("C://Users/socce/Downloads/input_rast.tif")

w <- terra::focalMat(r_terra, 300, "circle")
w[w > 0] <- 1 #Focal Matrix of 1's and 0's

w2<-w
w2[w2==0]<- NA #Focal matrix of 1's and NA's

focal_rast<- raster::focal(r_rast, w=w, fun = mean, na.rm=TRUE, pad=TRUE)
focal_rast2<- raster::focal(r_rast, w=w2, fun = mean, na.rm=TRUE, pad=TRUE)
focal_rast3 <- raster::focal(r_rast, w = w, fun = mymean, pad=TRUE)

focal_terra<- terra::focal(r_terra, w=w, fun = mean, na.rm=TRUE)
focal_terra2<- terra::focal(r_terra, w=w2, fun = mean, na.rm=TRUE)
focal_terra3 <- terra::focal(r_terra, w = w, fun = mymean)
# Error in x@ptr$focalValues(w, fillvalue, b$row[i] - 1, b$nrows[i]) : 
#   std::bad_alloc

raster::plot(focal_rast, main="raster 0/1")
```
![raster01](https://user-images.githubusercontent.com/28163862/135668727-1895950f-0b0f-4993-80da-9a6cdf948a07.png)

`raster::plot(focal_rast2, main= "raster NA/1")`

![rasterNA1](https://user-images.githubusercontent.com/28163862/135668747-1c70c92f-ced2-4bd5-85ba-06c9e45f8337.png)

`raster::plot(focal_rast3, main= "raster mymean")`

![rastermymean](https://user-images.githubusercontent.com/28163862/135669406-6d4a4ea3-a53e-4d56-ac63-cf835feea554.png)

`terra::plot(focal_terra, main = "terra 0/1")`
![terra01](https://user-images.githubusercontent.com/28163862/135668770-6a8a31fc-7452-414d-b127-b89d6764197a.png)


`terra::plot(focal_terra2, main= "terra NA/1")`


![rasterNA1](https://user-images.githubusercontent.com/28163862/135668934-dd169634-79a2-4102-b360-53f205dfe4d7.png)

```
Difference<- terra::rast(focal_rast)-focal_terra
terra::plot(Difference, main= "Diff raster0/1 and terra0/1")
```
![diff](https://user-images.githubusercontent.com/28163862/135668963-3bb08793-f32f-4e64-9219-8e8f6b73c217.png)

```
(Difference2<- terra::rast(focal_rast3)-focal_terra)
# min value   : -1.734723e-18 
# max value   :  1.734723e-18 
count_NA(focal_terra) == count_NA(focal_rast3) #TRUE
```

**Comment by rhijmans** [comment]
Thank you for reporting this and for the useful example. The `bad_alloc` error was due to not considering the dimensions of the focal window when computing the memory needs. 

Instead of 
`focal_terra2 <- terra::focal(r_terra, w = w_terra, fun = mymean_terra)`
You could do the much faster and clearer) 

```
w_terra[w_terra==0] <- NA
fterra2 <- terra::focal(r_terra, w = w_terra, fun = mean, na.rm=TRUE)
``` 

(the use of `NA` in the weights matrix is not available in `raster`)

I do not see the differences between `focal_rast` and `focal_terra` that you mention. Perhaps you are using an older version?
I notice that `raster` is faster than `terra` in your examples, so that is something I will need to look into.

**Comment by ailich** [comment]
@rhijmans, thanks. The last commit removed removed the `bad_alloc` when I install from github (I guess it make take a few moments to reach the Runiverse site). I do think there's still value in the custom function over  `w_terra[w_terra==0] <- NA` in some cases as specifying `mean(x[w != 0])` I believe would allow you to use `na.rm=FALSE`. Also, using 0's vs NA's in the weights matrix does not seem to affect the results of `terra::focal` when using `mean`.

**Comment by rhijmans** [comment]
> I do think there's still value in the custom function over w_terra[w_terra==0] <- NA in some cases as specifying mean(x[w != 0]) I believe would allow you to use na.rm=FALSE. 

When you use NA in the weight matrix you can also use `na.rm=FALSE`

> using 0's vs NA's in the weights matrix does not seem to affect the results of terra::focal when using mean.

Ah, yes, you are right. When using "mean" with a weights matrix you effectively get the weighted mean; the zeros are ignored altogether. That is not documented. The result would be different if you used `fun=function(i, na.rm) mean(i, na.rm)` 

> (I guess it make take a few moments to reach the Runiverse site)
A couple of hours.

**Comment by ailich** [comment]
@rhijmans, I am receiving some differences when using the custom function, and `na.rm=FALSE` is producing a raster of all NA's when using `mean`. 

library(terra)
#terra version 1.4.6


mymean <- function(x){mean(x[w != 0], na.rm=TRUE)}

r_terra<- terra::rast("C://Users/socce/Downloads/input_rast.tif")

w <- terra::focalMat(r_terra, 300, "circle")
w[w > 0] <- 1 #Focal Matrix of 1's and 0's

w2<-w
w2[w2==0]<- NA #Focal matrix of 1's and NA's

focal_terra1<- terra::focal(r_terra, w=w, fun = mean, na.rm=TRUE)
focal_terra2<- terra::focal(r_terra, w=w2, fun = mean, na.rm=TRUE)
focal_terra3 <- terra::focal(r_terra, w = w, fun = mymean, na.rm=TRUE)
focal_terra4<- terra::focal(r_terra, w=w2, fun = mean, na.rm=FALSE)


```
focal_terra1-focal_terra2
# min value   :          0 
# max value   :          0

focal_terra3-focal_terra2
# min value   :  -1.516364 
# max value   :   1.685333 

unique(values(focal_terra4))
# input_rast
# [1,]         NA
# [2,]        NaN
```

**Comment by rhijmans** [comment]
> na.rm=FALSE is producing a raster of all NA's when using mean.

But that would seem correct?

I also see the small differences. They probably occur at the edges of chunks, and I shall look into that. But the method with `NA` in the weights matrix appears to give the correct results. See below

```
d <- abs(focal_terra3-focal_terra2)
dd <- ifel(d > 0.5, d, NA)
x <- c(dd, focal_terra1, focal_terra3)
names(x) <- c("dif", "f1", "f2")
p <- as.points(x) 
p <- cbind(crds(p), as.data.frame(p))
p$cell <- cellFromXY(dd, cbind(p$x, p$y))
p$val <- NA

for (i in 1:nrow(p)) {
	acells <- as.vector(adjacent(d, p$cell[i], w))
	xy <- xyFromCell(d, acells)
	v <- unlist(r_terra[acells])
	p$val[i] <- mean(v, na.rm=TRUE)
}
all(p$f1 == p$val)
#[1] TRUE
```

**Comment by rhijmans** [comment]
With the latest push these differences are gone. Thank you very much for your help @ailich

**Comment by ailich** [comment]
@rhijmans,thank you and sorry for all the messages. You are right about the `NA` window. It evaluates to all NA's b/c this data is gappy so there is always at least one NA in the window.  The latest release however is causing an issue on my end where the R Session immediately aborts when I try to use the custom function in `focal`.

**Comment by rhijmans** [comment]
> Session immediately aborts when I try to use the custom function in focal.

Could be a compilation error. Can you do a fresh install (perhaps via Runiverse)?

**Comment by ailich** [comment]
I reinstalled from Runiverse this morning instead of github and now it runs and provides identical results down to the 8th decimal place. Thanks @rhijmans!

**Comment by NaturalCapitalSolutions** [comment]
Just read and followed your suggestions @rhijmans and @ailich. 
Indeed I was using an older version of terra but I now get the same results. 
Thank you very much for all the clarifications about the function, this was very useful!
