### ISSUE TITLE
area of the whole earth with terra?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#349]
When I try to obtain the area of the whole earth with terra, I see that the following cell gives a zero value. Is this normal ?

```
> r <- rast(ncols=1, nrows=1,xmin=0,ymin=-90,xmax=360,ymax=90)
> expanse(r)
[1] 0
```
I know this is a pretty special case, but I ask because it's pretty inconsistent with:

```
> r <- rast(ncols=2, nrows=1,xmin=0,ymin=-90,xmax=360,ymax=90)
> expanse(r)
[1] 5.100656e+14
```

**Comment by rhijmans** [comment]
Thanks for that. To compute areas, terra creates polygons from the raster cells. If you make a *polygon* from the "four corners of the earth", that polygon is in fact a line, and has no area; as the the four corners are at the same longitudes (0 == 360; or -180 == 180). Fixed now, by handling the corner-case of having a raster with only 1 column.
