### ISSUE TITLE
'save' a spatialRaster to an .RData workspace file?

### ISSUE THREAD

**Issue by dsjohnson** [rspatial/terra#353]
Is there currently any way to save a spatialRaster object to a workspace file via something like `save(rasterObject, file="myfile.RData")` ? This works with {raster} but does not work with {terra}

**Comment by rhijmans** [comment]
It is not possible to save a `SpatRaster` or `SpatVector` to a RData or a Rds file. Have a look at `wrap` for a work-around (for smaller datasets), or use `writeRaster` or `writeVector`. 

It is not guaranteed to work with the raster package either; it will fail if the Raster* object points to a temporary file, or another file that may be gone when reading RData.
