### ISSUE TITLE
cannot coerce class 'structure("SpatRaster", package = "terra")' to a data.frame

### ISSUE THREAD

**Issue by Ohm-Np** [rspatial/terra#354]
I was trying to load my raster cell values to a new data frame using
``` r
df <- as.data.frame(r)
```
however during the process it throws an error saying 
``` r
Error in as.data.frame.default(r) : 
    cannot coerce class 'structure("SpatRaster", package = "terra")' to a data.frame
```
`r` _is my spatRaster object._

I removed the library which was loaded from the CRAN and then installed it from the GitHub which worked fine in this case. 

So, I am having trouble with this error when building my r-package as I am using some functionalities from terra. Whenever I import terra to use it in my package, it loads it from CRAN by default and again the function which I wrote doesn't work because of the error mentioned above. So, what should I do to import `terra` from the **GitHub** but not from **CRAN** while building my new package? 
PS: I am using `roxygen2` for creating my package. And I am sorry if the question is not related to `terra` or should have been asked in `roxygen2`

**Comment by Rapsodia86** [comment]
Hi,
just be sure that you use  df <- terra::as.data.frame(r), because it looks like R uses the base data.frame function instead the one from terra.

**Comment by Ohm-Np** [comment]
Great! Worked like a charm! Thank you so much.
