### ISSUE TITLE
parallel lapp

### ISSUE THREAD

**Issue by kongdd** [rspatial/terra#365]
Dear @Robinlovelace,

I see that only `app` has the parameter `cores`. 
I am wondering whether `lapp`, `sapp` or `tapp` could support `cores`?

**Comment by rhijmans** [comment]
`lapp` and `tapp` now also have an argument `cores=1`. I cannot add that to `sapp` but that is a very important method anyway. 
See https://github.com/rspatial/terra/issues/36 for more discussion around parallelization.
