### ISSUE TITLE
Detecting patches in a SpatRaster without being divided by the longitude "on the edge" of the SpatRaster...

### ISSUE THREAD

**Issue by hirscht** [rspatial/terra#366]
I would like to create polygons in a SpatRaster by using patches( ) for the SpatRaster to identify patches and by converting these into polygons using as.polygon ( ).

My problem is that the patches created this way are divided by the longitude line on the edge of the SpatRaster. E.g. when taking a SpatRaster with longitudes -180 to 180 degrees, the patches lying on both side of the 180 (=-180) degrees longitude are divided by the this and are shown as separate patches. In reallity, there shouldn´t be such a separation. When I transform tha data to 0 to 360 degrees, I have same problem caused by the 0/360 degrees longitude.

Is there a way to solve this problem?

**Comment by rhijmans** [comment]
Thanks, that is an interesting problem that you should be fixed in `as.polygons`. But it could be useful to have a method that does this for existing polygon datasets. I have just added a draft version of such a method (still clumsy and not fast). Perhaps you can test it. Here is an example:


```
library(terra)
v1 = as.polygons(ext(170,180,50,70))
v2 = as.polygons(ext(170,180,20,40))
v3 = as.polygons(ext(170,180,-20,10))
v4 = as.polygons(ext(-180,-170,0,30))
v5 = as.polygons(ext(0,30,0,30))
z <- rbind(v1, v2, v3, v4, v5)
plot(z)

# no attributes
values(z) <- NULL
r1 <- terra:::connect_dateline(z)
plot(r1, col=rainbow(5))

# attributes all different
z$ID <- 1:5
r2 <- terra:::connect_dateline(z)
plot(r2, col=rainbow(5))

# some attributes match
z$ID <- c(1,2,1,2,3)
r3 <- terra:::connect_dateline(z)
plot(r3, col=rainbow(5))
```

**Comment by rhijmans** [comment]
I am sorry it took me so long, but I think both issues have now been fixed.  

That is, `patches` adjusts the output for global lon/lat data; so that the fix to the polygons used above is not needed. 

And `centroid` now accounts for lon/lat data that have parts that are nearer when going across the date line then when going across the 0 meridian.

```
library(terra)
r <- rast(nrows=18, ncols=36)
r[1:2, 5:8] <- 1
r[5:8, 1:6] <- 1
r[7:12, 22:36] <- 1
r[15:16, 18:29] <- 1
p <- patches(r)
v <- as.polygons(p)

plot(v, "patches", alpha=.5)
points(x, cex=1, pch="x")
``` 
![patches](https://user-images.githubusercontent.com/11481397/146689319-8c041e58-46f8-46b7-8076-fc7660ebf986.png)
