### ISSUE TITLE
distance function giving erroneous results for lat lon raster

### ISSUE THREAD

**Issue by phytoclast** [rspatial/terra#368]
Hi,
Up until recently, I had been using version 0.8 terra, but now upgraded to 1.4-11.  I had been impressed with the fact that the terra distances calculated as along the surface of a sphere rather than assuming a rectangular projection as many other GIS. However, upon upgrading I found that the distances do not make sense at all.
In this example, I calculated the distance from one point (derived from a 5 km global DEM), the distances from the point all seem to be zero along the same longitude. When I run the same script using the raster package, I get the appropriate distances radiating out from the single pixel.

elevdot <- Elev5km > 7000
elevdot <- aggregate(elevdot, fact = 100, fun='max')
elevdot[elevdot < 1] <- NA
dot.dist <- distance(elevdot)
plot(dot.dist)

![terradist](https://user-images.githubusercontent.com/34171749/137826225-aeabc756-2680-4cc4-bcae-62c8453bd1a8.png)
Distance from the Himalayas using the terra package
![rasterdist](https://user-images.githubusercontent.com/34171749/137826233-f0cc62e4-8c70-461f-9bff-4e435d02938b.png)
Distance from the Himalayas using the raster package

**Comment by rhijmans** [comment]
That is an awful bug. I was working on improving the speed of `distance` and clearly something went wrong. Works again now (albeit slowly) 



```
library(terra)
r <- rast(res=5)
r[cellFromXY(r, cbind(81, 35))] <- 1
dist <- distance(r)
plot(dist)
```
