### ISSUE TITLE
What would the terra approach to dismo::randomPoints be?

### ISSUE THREAD

**Issue by LDalby** [rspatial/terra#378]
I need to extract some background points from cells without presence points. This could be done using `dismo::randomPoints`.
Does `terra` provide the same functionality? 

I also looked into `background`  from the `predicts` package, but that does not appear to be exported - I can't seem to find it or the documentation anyway. But maybe it was not intended to by used in a case like this?

**Comment by rhijmans** [comment]
`predicts` now has an exported function `backgroundSample`. I think that will be the terra c.s. approach. It is probably best placed in `predicts` as it is a bit specialized. I hope to get back to `predicts` soon ...

**Comment by LDalby** [comment]
Thanks Robert!
