### ISSUE TITLE
sf into SpatVector

### ISSUE THREAD

**Issue by GuiAlDuS** [rspatial/terra#38]
Hi...
First thanks for all your amazing job putting together all these great spatial analysis tools.
I'm very much interested in moving from raster into terra, but so far I haven't been able to convert sf objets into SpatVector. I already looked into the rspatial.org website without being able to find a way to do it.
Is it still not possible to do this type of transformation?

Thanks!

**Comment by rhijmans** [comment]
With CRAN terra you can do 

```
# use files
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)

# coerce from sf *via* sp
library(sf)
vsf <- st_read(f)
vsp <- as(vsf, "Spatial")
v <- vect(vsp)
```

In response to your request, with development version, you can also do this directly

```
v <- vect(vsf)

```

**Comment by jldupouey** [comment]
I tried the direct conversion with terra development version 1.0.5 but got an error:

v <- vect(vsf)
# Error: [as,sf] coercion failed. You can try coercing via a Spatial* (sp) class
# In addition: Warning message:
# In if (class(geom[[1]][[1]]) == "list") { :
#   the condition has length > 1 and only the first element will be used
