### ISSUE TITLE
Values read as Count 

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#380]
The problem came back. I checked the #282 #234 but again, it does not read pixel values properly.
I used extract by mask (shapefile) to clip the original NLCD *.img in ArcMap and saved as *.tif. Then when read in R, using raster::raster(), the clipped *.tif is ok. Meaning, the values are numerical (not categorical anymore), but they are correct.
However, terra::rast() reads counts as values like in #282. 

I am using 1.4-13  dev version (#install.packages('terra', repos='https://rspatial.r-universe.dev')).

EDIT:
I followed with removing levels [ levels(read_file) <- NULL] and indeed now it shows proper values. But is this a desired approach?

**Comment by rhijmans** [comment]
Can you provide the file for which this does not work?

**Comment by Rapsodia86** [comment]
[Raster.zip](https://github.com/rspatial/terra/files/7445690/Raster.zip)
Here is resampled version of NLCD, so the file size is smaller. I have attached the *.tif with all other auxiliary files as generated by ArcMap. If I move the *.tif to other folder (so no extra files nearby), then terra reads correctly pixel values. So, ArcMap's additional files mess up with terra.

**Comment by rhijmans** [comment]
Thanks for reporting this and for the file. I think this is a different matter than the issues you referenced. In the other cases there was a value attribute table with counts only, which are generally not of interest. Here you have multiple categories, one of which is count:

```
library(terra)
f <- "nlcd_2019_land_cover_l48_20210604_ext_480.tif"
r <- rast(f)
r
#class       : SpatRaster 
#dimensions  : 1246, 1905, 1  (nrow, ncol, nlyr)
#resolution  : 480, 480  (x, y)
#extent      : -251139.8, 663260.2, 1451430, 2049510  (xmin, xmax, ymin, ymax)
#coord. ref. : Albers_Conical_Equal_Area 
#source      : nlcd_2019_land_cover_l48_20210604_ext_480.tif 
#categories  : Count, NLCD_Land 
#name        :     Count 
#min value   :    771449 
#max value   : 233018549 
``` 
You can change the active category like this: 
```
activeCat(r) <- 2
r
#class       : SpatRaster 
#dimensions  : 1246, 1905, 1  (nrow, ncol, nlyr)
#resolution  : 480, 480  (x, y)
#extent      : -251139.8, 663260.2, 1451430, 2049510  (xmin, xmax, ymin, ymax)
#coord. ref. : Albers_Conical_Equal_Area 
#source      : nlcd_2019_land_cover_l48_20210604_ext_480.tif 
#categories  : Count, NLCD_Land 
#name        :      NLCD_Land 
#min value   :    Barren Land 
#max value   : Woody Wetlands 
``` 

But since count is not that interesting, terra now skips it as the default category. So you now get:

``` 
r <- rast(f)
r
#class       : SpatRaster 
#dimensions  : 1246, 1905, 1  (nrow, ncol, nlyr)
#resolution  : 480, 480  (x, y)
#extent      : -251139.8, 663260.2, 1451430, 2049510  (xmin, xmax, ymin, ymax)
#coord. ref. : Albers_Conical_Equal_Area 
#source      : nlcd_2019_land_cover_l48_20210604_ext_480.tif 
#categories  : Count, NLCD_Land 
#name        :      NLCD_Land 
#min value   :    Barren Land 
#max value   : Woody Wetlands 
```

**Comment by Rapsodia86** [comment]
Thank you very much!:)
