### ISSUE TITLE
terra::rasterize: Error in y@ptr$setValues(values, opt) : std::bad_alloc

### ISSUE THREAD

**Issue by djfgerber** [rspatial/terra#382]
Dear all
I am new to terra and tried to translate my raster code into terra. When I compared 
```
r1 <- raster::rasterize(x = sample1 %>%
                    dplyr::select(geometry) %>%
                    sf::st_as_sf() %>%
                    sf::st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>%
                    sf::st_geometry() %>%
                    as("Spatial"),
                  y = pop2,
                  field = sample1 %>% pull(all_of(paste0("prevalence_sample_",1))))
toc()
tic("terra::rasterize")
t1 <- terra::rasterize(x = sample1 %>%
                          dplyr::select(geometry) %>%
                          sf::st_as_sf() %>%
                          sf::st_transform(crs = "EPSG:4326") %>% 
                         terra::vect(),
                        y = pop2_terra,
                        field = sample1 %>% pull(all_of(paste0("prevalence_sample_",1))))
toc()
```
the second one gave me the error
`Error in y@ptr$setValues(values, opt) : std::bad_alloc`

Any ideas where this comes from and if this is my problem or a terra problem? Unfortunately, this is not a reproducible example. The error message is not very helpful to me. All the arguments are evaluated smoothly and raster::rasterize throws no errors.

**Comment by rhijmans** [comment]
It is probably something with terra, but it is very difficult to say what it might e. It would help if you would `show` the objects you are using. Perhaps the output of this:


```
x = sample1 %>%  dplyr::select(geometry) %>%
                          sf::st_as_sf() %>%
                          sf::st_transform(crs = "EPSG:4326") %>% 
                         terra::vect()

field = sample1 %>% pull(all_of(paste0("prevalence_sample_",1))))
						 
x
field
pop2_terra

t1 <- terra::rasterize(x, pop2_terra, field)
```

**Comment by STBrinkmann** [comment]
Had a similar issue and solved by cropping y to x, maybe it helps. I have uploaded sample data on GitHub:

    # download files
    aoi_tmp <- tempfile(fileext = ".gpkg")
    download.file(url = "https://github.com/STBrinkmann/data/raw/main/rasterize/AOI.gpkg",
                  destfile = aoi_tmp, mode="wb")
    
    points_tmp <- tempfile(fileext = ".gpkg")
    download.file(url = "https://github.com/STBrinkmann/data/raw/main/rasterize/points.gpkg",
                  destfile = points_tmp, mode="wb")

    
    # generate raster mask with 5m res.
    aoi_mask <- terra::vect(aoi_tmp)
    mask_rast <- terra::rast(resolution = 5, crs = terra::crs(aoi_mask),
                             extent = c(483652.866593081, 523398.866593081, 5427715.16905125, 5462505.16905125),
                             vals = 1) %>%
      terra::mask(aoi_mask)
    
    
    # rasterize
    v <- terra::vect(points_tmp)
    
    # Error: "Error in y@ptr$setValues(values, opt) : std::bad_alloc"
    this_rast <- terra::rasterize(v, mask_rast, "VGVI")
    
    # works
    this_rast <- terra::rasterize(v, terra::crop(mask_rast, v), "VGVI")

**Comment by rhijmans** [comment]
Thanks, I believe this has now been fixed
