### ISSUE TITLE
GDAL 3.4.0rc1 breaks `gdal(drivers=TRUE)` in both released and development **terra**

### ISSUE THREAD

**Issue by rsbivand** [rspatial/terra#383]
See https://lists.osgeo.org/pipermail/gdal-dev/2021-November/054926.html for link to GDAL 3.4.0rc1:

```
> library(terra) 
terra version 1.4.16
> gdal()
[1] "3.4.0"
> gdal(drivers=TRUE)
Error in .gdaldrivers() : basic_string::_M_construct null not valid
```
GDAL released 3.3.3 OK, failure in 3.4.0rc1. Checked with **terra** 1.14.11 and current repo status.

Please check urgently, because if this is a regression in GDAL, it can still be fixed before release. If however a **terra** issue from possible code cleaning in GDAL, it needs fixing in **terra** fairly quickly, as GDAL only lets RC run for a few days.

**Comment by rhijmans** [comment]
Thank you. I will try do that asap, hopefully later today (it is a challenge). FYI here is the offending code. It would seem that  a NULL is now returned somewhere where there used to be an empty string.

```
// [[Rcpp::export(name = ".gdaldrivers")]]
std::vector<std::vector<std::string>> gdal_drivers() {
	size_t n = GetGDALDriverManager()->GetDriverCount();
	std::vector<std::vector<std::string>> s(5);
	for (size_t i=0; i<s.size(); i++) {
		s[i].reserve(n);
	}
    GDALDriver *poDriver;
    char **papszMetadata;
	for (size_t i=0; i<n; i++) {
	    poDriver = GetGDALDriverManager()->GetDriver(i);
		s[0].push_back(poDriver->GetDescription());
		s[4].push_back(poDriver->GetMetadataItem( GDAL_DMD_LONGNAME ) );

		papszMetadata = poDriver->GetMetadata();
		bool rst = CSLFetchBoolean( papszMetadata, GDAL_DCAP_RASTER, FALSE);
		s[1].push_back(std::to_string(rst));
		bool create = CSLFetchBoolean( papszMetadata, GDAL_DCAP_CREATE, FALSE);
		bool copy = CSLFetchBoolean( papszMetadata, GDAL_DCAP_CREATECOPY, FALSE);
		s[2].push_back(std::to_string(create + copy));
		bool vsi = CSLFetchBoolean( papszMetadata, GDAL_DCAP_VIRTUALIO, FALSE);
		s[3].push_back(std::to_string(vsi));

	}
	return s;
}

```

**Comment by rsbivand** [comment]
In **sf**, I think the code tests for returned null:
https://github.com/r-spatial/sf/blob/0e8bad6a458eda33129ae72a25649f080b485a96/src/gdal.cpp#L610-L638
In rgdal, `RGDAL_GetDriverNames(void)` in src/gdal_bindings.cpp lines 395-463 do the same. I don't know what may have changed - **rgdal** does not check `VIRTUALIO`.

**Comment by rhijmans** [comment]
I have not been able to figure out how to install the development version (to get it find PROJ), but will keep trying. I did change terra to test for NULLs in this function, so perhaps the issue is gone.

**Comment by rsbivand** [comment]
I install PROJ/GDAL/GEOS from source, replacing earlier versions, then have to install back the others if I get stuck.

The current state of terra master passes R CMD check with GDAL 3.4.0rc2, GEOS 3.10.1 and PROJ 8.2.0 for me with the usual note about installed package size.

**Comment by rhijmans** [comment]
Thank you very much for checking again and even more so for keeping track of GDAL releases. I think it is safe to assume that the error was in terra.
