### ISSUE TITLE
Install failed, missing geodesic.h

### ISSUE THREAD

**Issue by ArielPaulson** [rspatial/terra#384]
Installing today on R-4.1.0:

> install.packages("terra")
Installing package into ‘/home/apa/Rlibrary’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.microsoft.com/src/contrib/terra_1.4-11.tar.gz'
Content type 'application/octet-stream' length 541948 bytes (529 KB)
==================================================
downloaded 529 KB

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /n/apps/CentOS7/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.1.4
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /n/apps/CentOS7/install/gdal-2.1.4/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.1.4
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:    -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include
configure: Package LIBS: -lproj     -L/n/apps/CentOS7/install/gdal-2.1.4/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/n/apps/CentOS7/install/r-4.1.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/n/apps/CentOS7/install/r-4.1.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppFunctions.cpp -o RcppFunctions.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/n/apps/CentOS7/install/r-4.1.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppModule.cpp -o RcppModule.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/n/apps/CentOS7/install/r-4.1.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c arith.cpp -o arith.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/n/apps/CentOS7/install/r-4.1.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c crs.cpp -o crs.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/n/apps/CentOS7/install/r-4.1.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distRaster.cpp -o distRaster.o
distRaster.cpp:22:22: fatal error: geodesic.h: No such file or directory
 #include "geodesic.h"
                      ^
compilation terminated.
make: *** [/n/apps/CentOS7/install/r-4.1.0/lib64/R/etc/Makeconf:177: distRaster.o] Error 1
ERROR: compilation failed for package ‘terra’
* removing ‘/home/apa/Rlibrary/terra’

The downloaded source packages are in
	‘/tmp/Rtmpf74UHU/downloaded_packages’
Warning message:
In install.packages("terra") :
  installation of package ‘terra’ had non-zero exit status

**Comment by rhijmans** [comment]
I think this is because your GDAL is rather old (but the terra requirements states that it is not *too* old. I could fix this by adding geodesic.h to terra and use that instead of the version that ships with GDAL / or by requiring GDAL >= 2.2

**Comment by wporter** [comment]
That change would be great! I’m in the same boat, due to default GDAL being a little old in CentOS 7 repos.

**Comment by rhijmans** [comment]
I have added `geodesic.h/c` to terra. Can you now install the development version?

**Comment by rhijmans** [comment]
It can take a while before the r-universe version updates, so it is better to use `remotes::install_github("rspatial/terra")`  (except for installations on windows). 
The new error is odd, as a check fails that was fine before (in your original post). It seems extremely unlikely that it is because of something that I did, so I am guessing that it is related to the way you install terra.

**Comment by wporter** [comment]
I'm now getting the following error from the github install:

`g++ -std=gnu++11 -I"/opt/R/4.1.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I'/groups/porter/wcp/R/Rlibs/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c read_gdal.cpp -o read_gdal.o
read_gdal.cpp: In function ‘std::string basename_sds(std::string)’:
read_gdal.cpp:229:52: error: no matching function for call to ‘regex_replace(std::string&, std::regex, const char [1])’
  f = std::regex_replace(f, std::regex("\\.h5$"), "");
                                                    ^`

**Comment by rhijmans** [comment]
That suggests that your compiler is rather old, as it is not implement std::regex, which is C++11 (the 2011 standard). Anyhow, I have removed the use of `regex`, so please try again.

**Comment by ArielPaulson** [comment]
I tried the remotes::install_github method, and got a different error:

> remotes::install_github("rspatial/terra")
Downloading GitHub repo rspatial/terra@HEAD
✔  checking for file ‘/tmp/RtmpbzHZIB/remotes133d6150e692e/rspatial-terra-5c9fe3f/DESCRIPTION’ (468ms)
─  preparing ‘terra’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts (354ms)
─  checking for empty or unneeded directories
─  building ‘terra_1.4-16.tar.gz’

Installing package into ‘/home/apa/Rlibrary’
(as ‘lib’ is unspecified)
* installing *source* package ‘terra’ ...
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /n/apps/CentOS7/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.1.4
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /n/apps/CentOS7/install/gdal-2.1.4/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.1.4
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:    -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include
configure: Package LIBS: -lproj     -L/n/apps/CentOS7/install/gdal-2.1.4/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppFunctions.cpp -o RcppFunctions.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppModule.cpp -o RcppModule.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c arith.cpp -o arith.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c crs.cpp -o crs.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distRaster.cpp -o distRaster.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distance.cpp -o distance.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c extract.cpp -o extract.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c file_utils.cpp -o file_utils.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c focal.cpp -o focal.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gcp.cpp -o gcp.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal_algs.cpp -o gdal_algs.o
gdal_algs.cpp: In member function ‘SpatRaster SpatRaster::warper(SpatRaster, std::string, std::string, bool, SpatOptions&)’:
gdal_algs.cpp:89:2: error: ‘out’ was not declared in this scope
  out.setError("Not supported for this old version of GDAL");
  ^
make: *** [/n/apps/CentOS7/install/r-4.1.0/lib64/R/etc/Makeconf:177: gdal_algs.o] Error 1
ERROR: compilation failed for package ‘terra’

**Comment by rhijmans** [comment]
Thanks, that was a bug, fixed now, hope that was the last hurdle. Can you try again?

**Comment by ArielPaulson** [comment]
It is getting farther!

> remotes::install_github("rspatial/terra")
Downloading GitHub repo rspatial/terra@HEAD
✔  checking for file ‘/tmp/RtmpfjgHAu/remotes2367c241adc18/rspatial-terra-69eb57c/DESCRIPTION’ (525ms)
─  preparing ‘terra’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts (338ms)
─  checking for empty or unneeded directories
─  building ‘terra_1.4-16.tar.gz’

Installing package into ‘/home/apa/Rlibrary’
(as ‘lib’ is unspecified)
* installing *source* package ‘terra’ ...
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /n/apps/CentOS7/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.1.4
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /n/apps/CentOS7/install/gdal-2.1.4/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.1.4
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:    -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include
configure: Package LIBS: -lproj     -L/n/apps/CentOS7/install/gdal-2.1.4/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppFunctions.cpp -o RcppFunctions.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppModule.cpp -o RcppModule.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c arith.cpp -o arith.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c crs.cpp -o crs.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distRaster.cpp -o distRaster.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distance.cpp -o distance.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c extract.cpp -o extract.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c file_utils.cpp -o file_utils.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c focal.cpp -o focal.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gcp.cpp -o gcp.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal_algs.cpp -o gdal_algs.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal_multidimensional.cpp -o gdal_multidimensional.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdalio.cpp -o gdalio.o
gcc -std=gnu99 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -I/usr/include  -c geodesic.c -o geodesic.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c geos_methods.cpp -o geos_methods.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c graticule.cpp -o graticule.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c math_utils.cpp -o math_utils.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c mediancut.cpp -o mediancut.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c memory.cpp -o memory.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c ncdf.cpp -o ncdf.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c ram.cpp -o ram.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c raster_methods.cpp -o raster_methods.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c raster_stats.cpp -o raster_stats.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c rasterize.cpp -o rasterize.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c read.cpp -o read.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c read_gdal.cpp -o read_gdal.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c read_ogr.cpp -o read_ogr.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c sample.cpp -o sample.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatBase.cpp -o spatBase.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatDataframe.cpp -o spatDataframe.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatRaster.cpp -o spatRaster.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatSources.cpp -o spatSources.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-4.1.0/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.1.4/include -I/usr/include -I'/home/apa/Rlibrary/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatTime.cpp -o spatTime.o
spatTime.cpp: In function ‘std::vector<int> getymd(std::string)’:
spatTime.cpp:150:52: error: no matching function for call to ‘regex_replace(std::string&, std::regex, const char [1])’
    x[1] = std::regex_replace(s, std::regex("Z"), "");
                                                    ^
spatTime.cpp:150:52: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from spatTime.cpp:21:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
spatTime.cpp:150:52: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
    x[1] = std::regex_replace(s, std::regex("Z"), "");
                                                    ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from spatTime.cpp:21:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
spatTime.cpp:150:52: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
    x[1] = std::regex_replace(s, std::regex("Z"), "");
                                                    ^
make: *** [/n/apps/CentOS7/install/r-4.1.0/lib64/R/etc/Makeconf:177: spatTime.o] Error 1
ERROR: compilation failed for package ‘terra’

**Comment by rhijmans** [comment]
please try again...

**Comment by ArielPaulson** [comment]
Success!!   I will leave this thread open for wporter, though.

Thanks,
Ariel

**Comment by wporter** [comment]
All clear on my end too. Thank you so much for your responsiveness, Robert!
