### ISSUE TITLE
'range' argument for SpatVector plot?

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#385]
Hi,
The 'range' argument is often very useful for plotting rasters. It would also be very useful for vectors with continuous values, but it's silently ignored (code example below). Is it practical to implement it?
Cheers,
```
v <- vect(system.file("ex/lux.shp", package="terra"))
range(v$AREA)
plot(v, "AREA", type="continuous")
plot(v, "AREA", type="continuous", range = c(0, 500))  # nothing changes
```

**Comment by rhijmans** [comment]
Thanks, that works now --- but may need additional work for some corner cases.

**Comment by AMBarbosa** [comment]
Hi,
I've just tried it with terra 1.4.17 and it doesn't seem to be working right:

```
library(terra)
v <- vect(system.file("ex/lux.shp", package="terra"))
range(v$AREA)
plot(v, "AREA", type = "continuous")
plot(v, "AREA", type = "continuous", range = c(0, 500))  # but polygon colours don't change, only legend does
text(v, "AREA")  # see e.g. the orange and the green polygons, whose colours don't match this legend

```

**Comment by rhijmans** [comment]
Ay. I believe it works now. Thanks!
