### ISSUE TITLE
SpatExten operation

### ISSUE THREAD

**Issue by ecor** [rspatial/terra#386]
Dear all, 

I'm using terra, why is it so?

ext is 
SpatExtent : -15.5166666666667, 16.8583333333328, 5.38749999999938, 24.9499999999991 (xmin, xmax, ymin, ymax)

and 
> (exts)+c(-1,0,0,0)
SpatExtent : -14.5166666666667, 16.8583333333328, 5.38749999999938, 24.9499999999991 (xmin, xmax, ymin, ymax)
> ext(as.vector(exts)+c(-1,0,0,0))
SpatExtent : -16.5166666666667, 16.8583333333328, 5.38749999999938, 24.9499999999991 (xmin, xmax, ymin, ymax)
> 
Thank you 
Best
Emanuele

**Comment by rhijmans** [comment]
What you are seeing is:

```
library(terra)
e <- ext(-15, 16, 5, 24)
e + c(-1,0,0,0)
#SpatExtent : -14, 16, 5, 24 (xmin, xmax, ymin, ymax)

as.vector(e) + c(-1,0,0,0)
#xmin xmax ymin ymax 
# -16   16    5   24 
```

The reason that if you add something to an extent it gets bigger 

```
e + 1
#SpatExtent : -16, 17, 4, 25 (xmin, xmax, ymin, ymax)
```
and when you subtract something, it gets smaller
```
e - 1
#SpatExtent : -14, 15, 6, 23 (xmin, xmax, ymin, ymax)
```
