### ISSUE TITLE
Behavior of terra::project()?

### ISSUE THREAD

**Issue by mattwilliamson13** [rspatial/terra#388]
Hello,
I've finally started making the switch over to `terra` and have been using it in the courses I teach. I've recently come across a situation where my students have used `project(large.extent.raster, small.extent.raster)` and gotten a result that looks like it has been both projected and cropped, rather than distorted. I would have expected the result to be some strange "cramming" of the broader extent object into the smaller space, but that does not appear to be the case. Is this the expected behavior (i.e., `project` is both projecting and cropping)? Is that documented somewhere?

Thanks for a great package!
M

**Comment by rhijmans** [comment]
Hi Matt! 
You are not giving me much information, but if you do 

`project(large.extent.raster, small.extent.raster)` 

then the geometry of `small.extent.raster` will be used as template for the output, that is, set the extent, resolution, and coordinate reference system. This is documented in `?project` but probably not explicit enough.

But I am not sure what they were after or expected. I cannot think of a situation where you want "distorted". 

You can do 

`project(large.extent.raster, crs(small.extent.raster))` to avoid cropping, but generally this is not a good approach as you probably would want to align the projected data with existing raster data.

**Comment by mattwilliamson13** [comment]
Thanks Robert!
Right, sorry for not giving more information. The task was to have the students crop a `large.extent.raster` (e.g., CONUS elevation from the `getData()` package) with a smaller extent raster (e.g., land values in Idaho) and then use `project` or `resample` to align the two rasters. Several students bypassed the `crop` step and just used `project(large.extent.raster, small.extent.raster)`. As you described this produced output matches the geometry of the  `small.extent.raster` which is expected. It also appears that all of the data outside of the geometry of the `small.extent.raster` was dropped (i.e. it appears as if it was cropped) which I did not expect. I expected that projecting the un-cropped `broad.extent.raster` would result in an attempt to squeeze all of the data into the new, smaller extent (which is what I meant by distortion) making it clear that the `project` and `crop` (and `resample`) should be done separately.  Based on:


> then the geometry of `small.extent.raster` will be used as template for the output, that is, set the extent, resolution, and coordinate reference system. This is documented in `?project` but probably not explicit enough.

it sounds like the silent cropping is the expected behavior? Meaning that `project(large.extent.raster, small.extent.raster)` achieves both the projection and the crop in a single step? Sorry if this seems obvious, I didn't think this was the way `projectRaster` behaved in `raster` and so was surprised by the behavior.

Regardless, the new package is fantastic (even if I'm still climbing the learning curve)! Hope you're well and thanks for your help!

**Comment by rhijmans** [comment]
> cropping is the expected behavior?

It is, although I do not think of it that way. You project to a template, and you get estimated new values for the cells of that template. The template might cover a smaller or larger extent than what is covered by the projected input data. This is the same as in `raster`.

I have now added an option `align=FALSE`. If you set it to `TRUE`, the template is only used for the origin and resolution, but the extent is set to include all the input data (if possible).

**Comment by mattwilliamson13** [comment]
Got it. Thanks Robert!
