### ISSUE TITLE
Functions/Documentation for writing functions for rasters too large to fit in memory

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#389]
Are there/will there be functions like `raster::canProcessInMemory` and `raster::blockSize` for writing functions that deal with raster data too large to fit in memory as in the [appendix for the raster package](https://rspatial.org/raster/pkg/appendix1.html)? I'd like to convert some of my R packages over from `raster` to `terra` soon, but I'm unsure how to complete tasks in `terra` where the raster must be first converted to a matrix. In those cases I use those functions to determine appropriate block sizes to break the raster into smaller chunks that can fit in memory and then write the values back to a large raster on disk with `raster::writeValues`. The closest I can find is `terra::mem_info` which prints to the console whether the raster can be processed in memory but doesn't actually return the information in a way that can be stored in an R object like `raster::canProcessInMemory`.

**Comment by rhijmans** [comment]
It should be easiest to pass your functions to `app` or `lapp` .  

I would start there. You might be able to optimize your code a bit by  using the same pattern as `app`, which, in a bare form looks like this:

```
fun <- function(x, ...) {
	x
}

f <- function(x, ..., filename="", overwrite=FALSE, wopt=list())  {
	out <- rast(x)
	readStart(x)
	on.exit(readStop(x))
	nc <- ncol(x)
	b <- writeStart(out, filename, overwrite, wopt=wopt)
	for (i in 1:b$n) {
		v <- readValues(x, b$row[i], b$nrows[i], 1, nc, TRUE)
		v <- fun(v)
		writeValues(out, v, b$row[i], b$nrows[i])
	}
	writeStop(out)
}

library(terra)
r <- rast()
values(r) <- 1:ncell(r)
x <- f(r)
```

Note that `b` has the information you need 

```
b <- writeStart(out, filename, overwrite, wopt=wopt)
str(b)
#List of 3
# $ row  : num 1
# $ nrows: num 180
# $ n    : num 1
``` 

Also, "writing" will be in memory if `filename=""` and the raster is not too big (`writeStart` creates a temp file if need be). So there no more need for branching based on whether `canProcessInMemory` is true or false.

I could expose `blockSize` in `terra` if needed, but for me it works fine as in the above.

**Comment by ailich** [comment]
Thanks, I don't think `app` will work in my case since the functions are focal-like functions that use the surrounding cells rather than acting on a per cell basis (they return more than one layer and I pass them to C++ so I can't use `focal`). Would you be able to provide a little bit more detail as I'm just a bit confused on the syntax? What is `wopt` and does it need to be specified? Also I'm not quite following how to begin `writeStart` (see below).

```
library(terra)

r<- rast(volcano) #create  a raster

out<- rast(r) #Initialize output object
b<- writeStart(out) #Begin access to adding values to output and get info on if raster needs to be processed in chunks outside of memory
#Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘writeStart’ for signature ‘"SpatRaster", "missing"’
```

**Comment by rhijmans** [comment]
`wopt` is to pass options for writing files to writeStart if you use the ellipses `...` for another purpose. See ?writeRaster. You may not need it and I removed it from the example above (on the website). 

`writeStart is a  "S4 method for signature 'SpatRaster,character'" meaning the second argument cannot be missing. You can use `writeStart(x, "")`, but I would suggest that you use the template I provided and only change `fun(v)`

**Comment by ailich** [comment]
@rhijmans thanks!
