### ISSUE TITLE
Which requirements are correct ones: readme or DESCRIPTION?

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [rspatial/terra#390]
There are some differences between following files

DESCRIPTION:

> SystemRequirements: C++11, GDAL (>= 2.2.3), GEOS (>= 3.4.0), PROJ (>= 4.9.3), sqlite3

README.md:

> **Linux**
> The GDAL (>= 2.2.0), GEOS (>= 3.3.0) and PROJ (>= 6.0.0) libraries are required

Which ones are correct?

**Comment by rhijmans** [comment]
I have made them the same, using what was in DESCRIPTION. 

To be able to install terra, I now think it may be a bit lower: GDAL 2.1.4, PROJ 4.8.0, GEOS 3.3.0
(https://github.com/rspatial/terra/issues/384 has evidence for the GDAL and PROJ versions). 

For full functionality the versions needed are higher than either of these two specifications.

**Comment by tentacles-from-outer-space** [comment]
OK. I'm struggling with the installation on Centos (constrained environment) and with PROJ 4.9.3 it failed (but root cause could be something else).

Newest PROJ (8.1.1) is recommended?

**Comment by rhijmans** [comment]
What error message do you get? 

These are the highest versions I have worked with: GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1
But higher should be even better

**Comment by tentacles-from-outer-space** [comment]
For PROJ 4.9.3 there is no proj.h header on CentOS proj49 package (http://rpm.pbone.net/info_idpl_75905631_distro_redhatel7_com_proj49-devel-4.9.3-3.rhel7.x86_64.rpm.html)

I did a quick check for higher version (proj81=proj 8.1.1 or proj72 = proj 7.2.1), but I failed on correct path configurations, e.g. for 8.1 I came the furthest with the following configuration:

```r
configure.args = list(
		terra = c(
			"--with-gdal-config=/usr/gdal33/bin/gdal-config"
			,"--with-proj-include=/usr/proj81/include"
			,"--with-proj-share=/usr/proj81/lib" # why this must be switched??  I don't know :) But when changed it 
			,"--with-proj-lib=/usr/proj81/share" # fail with `configure: error: libproj not found in standard or given locations.`
		)
	)
```

which give me:

```
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
checking for pj_init_plus in -lproj... yes
configure: PROJ_LIB: /usr/proj81/lib
checking PROJ: epsg found and readable... no
Error: proj/epsg not found
Either install missing proj support files, for example
the proj-nad and proj-epsg RPMs on systems using RPMs,
or if installed but not autodetected, set PROJ_LIB to the
correct path, and if need be use the --with-proj-share=
configure argument.
ERROR: configuration failed for package ‘terra’
```

If I have a moment, I will try to finish it and give feedback.

**Comment by rhijmans** [comment]
It would be helpful if you provided the output you get (with the original proj lib) as in https://github.com/rspatial/terra/issues/384
If the issue is that proj.h is missing that is is something that I believe I can fix at my end.
