### ISSUE TITLE
netcdf with no projection metadata identifies as longlat

### ISSUE THREAD

**Issue by mdsumner** [rspatial/terra#391]
this file (attached) presents as if the extent is in longitude,latitude but it's in the normal degenerate index space default for GDAL
[19911203.zip](https://github.com/rspatial/terra/files/7500664/19911203.zip)

```R
 rast("/19911203.nc")
class       : SpatRaster 
dimensions  : 664, 632, 2  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0.5, 632.5, 0.5, 664.5  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
sources     : 19911203.nc:concentration  
              19911203.nc:quality_flag  
varnames    : concentration (sea-ice concentration) 
              quality_flag (quality_flag) 
names       : concentration, quality_flag 
unit        :       percent,          n/a 
time        : 1991-12-03 12:00:00 
```

obtained from ftp.ifremer.fr/ifremer/cersat/products/gridded/psi-concentration/data/antarctic/daily/netcdf/1991/

This shouldn't report the coord.ref as "lon/lat WGS 84". 

(the actual projection is 'EPSG:3031' with extent '-3950000, 3950000, -3950000, 4350000' and a specific matrix orientation but you cannot tell that from the file without interrogating in detail the longitude,latitude arrays that are provided separately)

**Comment by rhijmans** [comment]
Thanks very much, I now get:

```
library(terra)
#terra version 1.4.17
r <- rast("19911203.nc")
#[1] "vobjtovarid4: **** WARNING **** I was asked to get a varid for dimension named ni BUT this dimension HAS NO DIMVAR! Code will probably fail at this point"
#[1] "vobjtovarid4: **** WARNING **** I was asked to get a varid for dimension named nj BUT this dimension HAS NO DIMVAR! Code will probably fail at this point"
 
r
#class       : SpatRaster 
#dimensions  : 664, 632, 2  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0.5, 632.5, 0.5, 664.5  (xmin, xmax, ymin, ymax)
#coord. ref. :  
#sources     : 19911203.nc:concentration  
#              19911203.nc:quality_flag  
#varnames    : concentration (sea-ice concentration) 
#              quality_flag (quality_flag) 
#names       : concentration, quality_flag 
#unit        :       percent,          n/a 
#time        : 1991-12-03 12:00:00 
```

**Comment by mdsumner** [comment]
thank you, could possibly also not apply the longlat CRS if the geotransform is default `0 1 0 0 0 1`  with an extent in the longlat range ? (sorry I can't tell, maybe it already does that)

**Comment by rhijmans** [comment]
Yes, that is the intent. To not assume anything if there is no geotransform. But if there is, and the coordinates are in lonlat range assume lonlat if crs is missing.
