### ISSUE TITLE
Round trip from terra -> raster -> terra

### ISSUE THREAD

**Issue by Robinlovelace** [rspatial/terra#399]
I know there was an earlier issue opened on this but things seem to have changed. See reprex below.

``` r
remotes::install_github("rspatial/terra")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'terra' from a github remote, the SHA1 (d48a1316) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(terra)
#> terra version 1.4.18
library(raster)
#> Loading required package: sp
x <- rast(nrows=108, ncols=21, xmin=0, xmax=10)
values(x) = seq(108 * 21)
x_raster = as.raster(x)
x2 = rast(x_raster) # how to convert back to terra? fails for me (RL 2021-11)
#> Error in methods::as(x, "SpatRaster"): no method or default for coercing "raster" to "SpatRaster"
identical(x2, my_rast2)
#> Error in identical(x2, my_rast2): object 'x2' not found
```

<sup>Created on 2021-11-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Robinlovelace** [comment]
According to comments in this issue `rast(x_raster)` should work https://github.com/rspatial/terra/issues/8

**Comment by rhijmans** [comment]
From `?terra::as.raster`: 

> Implementation of the generic as.raster function to create a "raster" (small r) object. Such objects can be used for plotting with the rasterImage function. NOT TO BE CONFUSED with the Raster* (big R) objects defined by the 'raster' package!

(but who reads the manual 😉?)

Instead of `as.raster`, you can use `raster` (or `brick` or `stack`) or `as(x, "Raster")`.

```
library(terra)
library(raster)
x <- rast(nrows=108, ncols=21, xmin=0, xmax=10)
values(x) = seq(108 * 21)

x_raster = as.raster(x)
class(x_raster)
#[1] "raster"


r1 <- raster(x)
class(r1)
#[1] "RasterLayer"
#attr(,"package")
#[1] "raster"

x1 <- rast(r1) 

r2 <- as(x, "Raster")
class(r2)
#[1] "RasterLayer"
#attr(,"package")
#[1] "raster"
x2 <- rast(r2) 
```

**Comment by Robinlovelace** [comment]
Thanks for the quick reply and apologies, should have more carefully read the docs!  

It seems that the `x_raster` object of class `raster` contains the same information as the object of class `RasterLayer`. What would be the disadvantage of making `rast(x_raster)` return the same object as `rast(r1)` in the example?

Below is a reproducible example building on the above. 

``` r
library(terra)
#> terra version 1.4.18
library(raster)
#> Loading required package: sp

# correct round trip
x <- rast(nrows=108, ncols=21, xmin=0, xmax=10)
values(x) = seq(108 * 21)
r1 <- raster(x)
x1 <- rast(r1) 
identical(x, x1)
#> [1] FALSE
waldo::compare(x, x1) # they are identical but have different pointers I think
#> `old@ptr@.xData` is <env:0x55ded8671f80>
#> `new@ptr@.xData` is <env:0x55dedb0411c8>
identical(terra::values(x), terra::values(x1))
#> [1] TRUE

x_raster = as.raster(x)

class(r1)
#> [1] "RasterLayer"
#> attr(,"package")
#> [1] "raster"
plot(r1)
```

![](https://i.imgur.com/IHriFJE.png)

``` r
class(x_raster)
#> [1] "raster"
plot(x_raster)
```

![](https://i.imgur.com/4udZAJB.png)

``` r
plot(x1)
```

![](https://i.imgur.com/ZbNGF5t.png)

``` r
x2 <- rast(x_raster)
#> Error in methods::as(x, "SpatRaster"): no method or default for coercing "raster" to "SpatRaster"

r2 <- as(x, "Raster")
class(r2)
#> [1] "RasterLayer"
#> attr(,"package")
#> [1] "raster"
identical(r1, r2)
#> [1] TRUE
```

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
