### ISSUE TITLE
as.factor() doesn't work. (Error in unique.default(x, nmax = nmax) :    unique() applies only to vectors)

### ISSUE THREAD

**Issue by zzw0034** [rspatial/terra#400]
> set.seed(0)
> r <- rast(nrow=10, ncol=10)
> terra::values(r) <- runif(ncell(r)) * 10
> is.factor(r)
[1] FALSE
> r <- round(r)
> f <- terra::as.factor(r)
Error in unique.default(x, nmax = nmax) : 
  unique() applies only to vectors

**Comment by rhijmans** [comment]
See `?levels` on how to create categorical rasters. There is no `as.factor` method for SpatRaster. Perhaps it should be there for the case when you want to use (integer) values as labels; to be clear that they are categories?

**Comment by rhijmans** [comment]
I have added `as.factor` 

```
library(terra)
set.seed(0)
r <- rast(nrow=10, ncol=10)
values(r) <- runif(ncell(r)) * 10
r <- round(r)
f <- as.factor(r)
is.factor(f)
#[1] TRUE
levels(f)
#[[1]]
# [1]  0  1  2  3  4  5  6  7  8  9 10
```

**Comment by zzw0034** [comment]
thank you for your reply.
if I have a raster layer with attribute table. I use rast convert it to SpatRaster, it will lost the attribute table.
So to use attribute table, I should stick with raster? do I understand right?

thank you so much.

**Comment by rhijmans** [comment]
On the contrary, `terra` is much better than `raster` in handling categorical data. When I use `rast` (with the development version of terra) the categories are not lost

```

library(raster)
library(terra)
r <- raster(nrow=10, ncol=10)
values(r) = 1
r[51:100] = 2
r[3:6, 1:5] = 3
r <- ratify(r)

rat <- levels(r)[[1]]
rat$landcover <- c("Pine", "Oak", "Meadow")
rat$code <- c(12,25,30)
levels(r) <- rat

rast(r)
#class       : SpatRaster 
#dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#resolution  : 36, 18  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : memory 
#categories  : landcover, code 
#name        : landcover 
#min value   :    Meadow 
#max value   :      Pine 
```

**Comment by zzw0034** [comment]
Thank you so much.
however, the rast(r) only have attribute landcover, it lost the ID and code.

**Comment by rhijmans** [comment]
That is not correct, see below:

```
x <- rast(r)
cats(x)
#[[1]]
#  ID landcover code
#1  0      <NA>   NA
#2  1      Pine   12
#3  2       Oak   25
#4  3    Meadow   30

activeCat(x) <- 2
x
#class       : SpatRaster 
#dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#resolution  : 36, 18  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : memory 
#categories  : landcover, code 
#name        : code 
#min value   :   12 
#max value   :   30 
```

**Comment by zzw0034** [comment]
thanks you so much!
I didn't use cats(x), activeCat(x). Now I understand better.
have a great day sir!

**Comment by zzw0034** [comment]
Hi sir,
i was so confused by mean in terra.
a <- mean(r,s,10)

r <- rast(ncol=5, nrow=5)
values(r) <- 1
a <- mean(r,s,10)

this is from https://rspatial.org/spatial-terra/8-rastermanip.html#raster-algebra

> a
class       : SpatRaster 
dimensions  : 5, 5, 1  (nrow, ncol, nlyr)
resolution  : 72, 36  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
source      : memory 
name        : lyr.1 
min value   :   5.5 
max value   :   5.5 

why is 5.5. how do this mean work?

thank you!
