### ISSUE TITLE
Error in rats(r) : could not find function "rats"

### ISSUE THREAD

**Issue by zzw0034** [rspatial/terra#401]
> set.seed(0)
> r <- rast(nrow=10, ncol=10)
> terra::values(r) <- runif(ncell(r)) * 10
> is.factor(r)
[1] FALSE
> r <- round(r)
> f <- terra::as.factor(r)
Error in unique.default(x, nmax = nmax) : 
  unique() applies only to vectors
> rats(r)
Error in rats(r) : could not find function "rats"

**Comment by rhijmans** [comment]
`rats` existed in an early version of terra, but was removed a while ago.
