### ISSUE TITLE
parallele computing with tapp on large rasters

### ISSUE THREAD

**Issue by treebreeder** [rspatial/terra#405]
Dear Robert,

I am processing very large rasters with daily temperature and precipitation on 1x1km.

class       : SpatRaster 
dimensions  : 6030, 13920, 365  (nrow, ncol, nlyr)
resolution  : 0.008333333, 0.008333333  (x, y)
extent      : -40.5, 75.5, 25.25, 75.5  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : DownscaledPrcp1950_cogeo.tif 
names       : Dow_1, Dow_2, Dow_3, Dow_4, Dow_5, Dow_6, ... 

I want to get new rasters with monthly sums and max values which I am doing with tapp.

dt<-as.data.frame(as.Date(seq(as.Date('1950-01-01'), as.Date('1950-12-31'), by = "day")))
dt<-format(dt,format="%m")
indices<-dt[,1]
r_monthly<- tapp(r, index=indices, fun = sum,filename="Prec_1950")

However, since rasters are so huge things go only very slowly. I saw that there is no "core" argument for tapp.
Do you have any solution to do things in parallele though or how to speed things up?

Many thanks for your help

**Comment by rhijmans** [comment]
`tapp` now has an argument `cores=1`
