### ISSUE TITLE
CRAN Package Check Results

### ISSUE THREAD

**Issue by mhesselbarth** [rspatial/terra#407]
Hey, 

Thanks for providing this amazing package to the community. 

Currently, the CRAN checks for [r-release-macos-x86_64](https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/terra-00install.html) result in an error which causes a few of my GitHub action workflows to fail as well. 

Are there any plans to fix the error in the nearer future? 

Thanks a lot,
Max

**Comment by rhijmans** [comment]
Hi, thanks for letting me know. That is a surprise as the CRAN code compiles for me on OSX with clang 12.0.5.  
The error is `no template named 'greater' in namespace 'std'; did you mean 'isgreater'`. I changed to code to use neither, but I cannot check if there are additional issues. That would seem unlikely, so I guess I will submit to CRAN later today hoping for the best.

**Comment by rhijmans** [comment]
Can you point me to the error in the github actions workflow you are seeing. I saw this one:
https://github.com/r-spatialecology/landscapemetrics/runs/4255557213?check_suite_focus=true
but that seems to be an unrelated problem (missing GDAL)?

**Comment by rhijmans** [comment]
Thanks for letting me know!
