### ISSUE TITLE
aggregate() returns no data with fun = sd and abnormal results with min or max

### ISSUE THREAD

**Issue by hrvg** [rspatial/terra#41]
As mentionned in #36 , I wanted to use of `terra::aggregate` in parallel and resorted to use `raster::aggregate` instead. However, with large rasters, my parallelization scheme partially fails because of memory allocation issues. This prompted me to experiment again with `terra::aggregate()`.

Using `terra::aggregate()` on this [resampled CA raster](https://github.com/rspatial/terra/files/4761179/CA_DEM_Lmax-resampled.zip) leads to no data with sd, and abnormal results with min and max.

```
library("terra")
r <- rast("CA_DEM_Lmax-resampled.tif")
aggregate(r, fact = 2, fun = sd) # returns a raster with no cell values
aggregate(r, fact = 2, fun = min) # returns a raster with max values of 1.79...e308
aggregate(r, fact = 2, fun = max) # returns a raster with min values of -1.79...e308
aggregate(r, fact = 2, fun = modeest::mfv1) # returns a raster with no cell values
````

I guess no data values is returned because sd is not implemented (is this why it is not mentioned in the documentation?). I tested with a mode estimation function (`modeest::mfv1`) which also returns no data. 

1.79...e308 is machine precision for floating point number.

**Comment by rhijmans** [comment]
Some of this was already fixed in the devel version, but not all. I think it all works again (but not very fast; need to work on that).  See below. Note that in all cases you may want to use `na.rm=TRUE`

```
library("terra")
r <- rast(nrow=13, ncol=11, xmin=-124.5352, xmax=-114.3541, ymin=31.31056, ymax=43.34278)
values(r) <- c(83, 928, 1733, 1755, 1538, NA, NA, NA, NA, NA, NA, 140, 1330, 1109, 1395, 1434, NA, NA, NA, NA, NA, NA, 160, 1266, 523, 1007, 1960, NA, NA, NA, NA, NA, NA, 531, 1633, 92, 1641, 1940, NA, NA, NA, NA, NA, NA, 0, 356, 35, 269, 1786, NA, NA, NA, NA, NA, NA, NA, 0, 338, 16, 1262, 2969, 2197, 1600, 1776, 1464, 1703, NA, 0, 531, 564, 65, 1989, 1793, 1804, 1751, 1540, 1630, NA, NA, 0, 55, 157, 85, 3154, 1438, 928, 2059, 781, NA, NA, NA, 0, 484, 81, 1242, 1028, 1288, 1073, 756, NA, NA, NA, NA, 244, 1248, 572, 950, 1040, 186, 474, NA, NA, NA, NA, NA, 0, 0, 326, 1854, 592, 180, NA, NA, NA, NA, NA, NA, 0, 0, 537, 25, 61, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)

aggregate(r, fact = 2, fun = sd)
#min values  :      163 
#max values  : 944.1603 

aggregate(r, fact = 2, fun = min)
#min values  :     0 
#max values  :  1438 

aggregate(r, fact = 2, fun = max)
#min values  :   326 
#max values  :  3154 

aggregate(r, fact = 2, fun = modeest::mfv1)
#min values  :     0 
#max values  :  1438 
```

As an aside, I compared `modeest::mfv1` and `raster::modal`. They give the same results when using `ties="lowest" with raster::modal. The manual of modeest::mfv1 says it takes the "first" modal value if there are ties, whereas it actually takes the lowest.

```
a <- aggregate(r, fact = 2, fun = modeest::mfv1, na_rm=T)
b <- aggregate(r, fact = 2, fun = raster::modal, ties="lowest", na.rm=T)
plot(a,b)
```
