### ISSUE TITLE
stoi: no conversion

### ISSUE THREAD

**Issue by lime-n** [rspatial/terra#411]
I'm getting the following error when loading ```.nc``` file formats with `terra` using `rast()`
>Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  stoi: no conversion

I have tried reading the file either as:
```
file <- "SWSmm19870701000000213SCPOS01UD.nc"
rast(file)
```
or
```
rast('NETCDF:"SWSmm19870701000000213SCPOS01UD.nc"')
```

However I still get the error. I've tried loading the file with the older `raster` package, and I have no problems:
```
raster::raster(file)
#Loading required namespace: ncdf4
class      : RasterLayer 
dimensions : 100, 218, 21800  (nrow, ncol, ncell)
resolution : 0.5, 0.5  (x, y)
extent     : -44.5, 64.5, 22, 72  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : SWSmm19870701000000213SCPOS01UD.nc 
names      : Windspeed.at.10m 
z-value    : 1987-07-01 
zvar       : wind 
```
 
Here's a link to access the file: https://github.com/lime-n/Test-Stuff-with-R/blob/main/SWSmm19870701000000213SCPOS01UD.nc

**Comment by rhijmans** [comment]
I cannot reproduce that, and I assume that while you get an error *message* you do not really get an *error* as the code runs as expected? Please confirm.

The occasional emittance of error *messages* is an [old problem](https://github.com/rspatial/terra/issues/30) that perhaps needs a fresh look.

**Comment by lime-n** [comment]
Hi, the code does not run and it just produces an error; here's a screenshot for confirmation: - 
<img width="1598" alt="Screenshot 2021-11-24 at 11 41 26" src="https://user-images.githubusercontent.com/68914515/143232134-a3a0709a-8504-4400-99db-427fb3a1aad9.png">

**Comment by rhijmans** [comment]
From what I can see now, you may not be using an older version of terra (or even a corrupted one?). What is your version of `terra`?

It is good practice to show all your simplified code needed to reproduce the error, and all the messages you get (please do not use screenshots) in the order as they appear.  And mention your OS and R and terra version (or better include `sessionInfo()`.

**Comment by lime-n** [comment]
The errors appears as the code above, I simply just read the file and get the error.
Here's my session info:
```
>  library(terra)
terra version 1.4.11
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 12.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.4-11

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7       raster_3.5-2     magrittr_2.0.1   hms_1.1.0        tidyselect_1.1.1 lattice_0.20-44 
 [7] R6_2.5.0         rlang_0.4.11     fansi_0.5.0      dplyr_1.0.7      tools_4.1.0      rgdal_1.5-27    
[13] grid_4.1.0       utf8_1.2.1       DBI_1.1.1        ellipsis_0.3.2   assertthat_0.2.1 tibble_3.1.2    
[19] lifecycle_1.0.0  crayon_1.4.1     purrr_0.3.4      readr_1.4.0      vctrs_0.3.8      codetools_0.2-18
[25] glue_1.4.2       sp_1.4-5         compiler_4.1.0   pillar_1.6.1     generics_0.1.0   pkgconfig_2.0.3 
```

**Comment by lime-n** [comment]
I managed to fix the issue!
The problem was the recent MacOS update to Monterey. It meant that I had to re-install many of the dependencies like Proj, and gdal-config.
