### ISSUE TITLE
R crashes when using buffer on a rast with no values

### ISSUE THREAD

**Issue by STBrinkmann** [rspatial/terra#416]
R crashes when I applyed the buffer function on an empty rast object:

    library(terra)
    
    # Create a SpatRaster from scratch
    x <- rast(nrows=108, ncols=21, xmin=0, xmax=10, res = 1)
    buffer(x, 1)

This behaviour does not appear when initializing x with values:

    x <- rast(nrows=108, ncols=21, xmin=0, xmax=10, res = 1, vals = 1)
    buffer(x, 1)

I see that there is no reason to apply buffer on an empty raster. In that case could a error message be returned?

**Comment by rhijmans** [comment]
Thank you very much. I now get 

```
library(terra)
#terra version 1.5.0
x <- rast(nrows=108, ncols=21, xmin=0, xmax=10, res = 1)
buffer(x, 1)
#Error: [buffer] SpatRaster has no values
```
