### ISSUE TITLE
quantile in raster vs terra

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#423]
I've found that `raster::quantile` and `terra::quantile` do different things. `terra::quantile` is used to "compute quantiles for each cell across the layers of a SpatRaster." while `raster::quantile` is used to "compute quantiles for the cell values of a RasterLayer." In the `raster::quantile` documentation it states "If you want to compute quantiles for each cell across a number of layers, you can use calc(x, fun=quantile)" which is what `terra::quantile` does. It may be useful to add to `terra::quantile` something along the lines of "if you'd like to compute quantiles for the cell values of a SpatRaster, you can use `global(x, fun=quantile)`. It also might be nice to have `terra::global` get names from the used funtion rather than call each column "global_number."
```

library(raster)
library(terra)

r<- c(rast(volcano), rast(volcano)*2)

terra::quantile(r)
# class       : SpatRaster 
# dimensions  : 87, 61, 5  (nrow, ncol, nlyr)
# resolution  : 0.01639344, 0.01149425  (x, y)
# extent      : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
# coord. ref. :  
#   source      : memory 
# names       :     q0,  q0.25,   q0.5,  q0.75,     q1 
# min values  :   94.0,  117.5,  141.0,  164.5,  188.0 
# max values  : 195.00, 243.75, 292.50, 341.25, 390.00 

raster::calc(stack(r), fun= quantile)
# class      : RasterBrick 
# dimensions : 87, 61, 5307, 5  (nrow, ncol, ncell, nlayers)
# resolution : 0.01639344, 0.01149425  (x, y)
# extent     : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
# crs        : NA 
# source     : memory
# names      :    X0.,   X25.,   X50.,   X75.,  X100. 
# min values :   94.0,  117.5,  141.0,  164.5,  188.0 
# max values : 195.00, 243.75, 292.50, 341.25, 390.00 

raster::quantile(stack(r))
# 0% 25% 50% 75% 100%
# lyr.1.1  94 108 124 150  195
# lyr.1.2 188 216 248 300  390

terra::global(r, fun=quantile)
# global_1 global_2 global_3 global_4 global_5
# lyr.1         94      108      124      150      195
# lyr.1.1      188      216      248      300      390
```

**Comment by rhijmans** [comment]
Thanks, made both changes
