### ISSUE TITLE
Can't control plot title in density plot

### ISSUE THREAD

**Issue by dvictori** [rspatial/terra#424]
I'm using the `density` function to look at data distribution for a raster dataset. I just found out that the `main` parameter does not seems to work when plotting the density for a single layer.

Here goes a reprex:

------------------------------

``` r
library(terra)
#> terra version 1.4.22
logo <- rast(system.file("ex/logo.tif", package="terra"))

# uses layer names as plot main
density(logo)
```

![](https://i.imgur.com/v6BkCeD.png)

``` r
# I can change the title
density(logo, main = 'test')
```

![](https://i.imgur.com/fsj6669.png)

``` r
# when working with one layer, it breaks
b1 <- logo[[1]]

# I can't control the plot title
density(b1, main = 'test')

# And it's not using layer name as title
names(b1)
#> [1] "red"
density(b1)
```

![](https://i.imgur.com/azqSXm4.png)

<sup>Created on 2021-12-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thank you very much for reporting. This now works as expected, at least for the example below

```
library(terra)
logo <- rast(system.file("ex/logo.tif", package="terra"))
density(logo, main=paste("test", 1:3))

density(logo[[2]], main="test", xlab="You name it")
```
