### ISSUE TITLE
mean function in terra

### ISSUE THREAD

**Issue by zzw0034** [rspatial/terra#426]
Hi sir,
I was so confused by mean function in terra.

From https://rspatial.org/spatial-terra/8-rastermanip.html#raster-algebra

r <- rast(ncol=5, nrow=5)
values(r) <- 1
s <- c(r, r+1)

a <- mean(r,s,10)

a
class : SpatRaster
dimensions : 5, 5, 1 (nrow, ncol, nlyr)
resolution : 72, 36 (x, y)
extent : -180, 180, -90, 90 (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84
source : memory
name : lyr.1
min value : 5.5
max value : 5.5

why is 5.5. how do this mean function work?

thank you!

**Comment by rhijmans** [comment]
Thank you very much for reporting this. That is an ugly bug that happens if you do math with multiple SpatRasters *and* a number. Fixed now:

```
library(terra)
r <- rast(ncol=5, nrow=5)
values(r) <- 1
s <- c(r, r+1)
mean(r,s,10)
#class       : SpatRaster 
#dimensions  : 5, 5, 2  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#names       :     lyr1,     lyr2 
#min values  : 4.000000, 4.333333 
#max values  : 4.000000, 4.333333 

#as expected:
c(mean(c(1,1,10)), mean(c(1,2,10)))
#[1] 4.000000 4.333333
```

**Comment by zzw0034** [comment]
Thank you for your quick reply! Thank you so much! I was so confused by this.
