### ISSUE TITLE
Does terra has funciton like corLocal: Local correlation coefficient in raster?

### ISSUE THREAD

**Issue by zzw0034** [rspatial/terra#427]
I am curious to ask if  terra has funciton like corLocal: Local correlation coefficient in raster?
I have two rast, i want to see the correlation between them. I expect to have a rastlayer with r value. 

Thank you Dr. Robert J. Hijmans!
Thank you everyone!

**Comment by rhijmans** [comment]
There is now, called `focalLyr`  for now; but I may call it `focalCor` instead.  Thank you for the suggestion!

**Comment by rhijmans** [comment]
I renamed it to `focalCor`

**Comment by zzw0034** [comment]
Hello sir,
good morning!
I have one question about focalCor. If I have one layer SOC and I want to get r between my one layer SOC with another dataset also as one layer(for example, HWSD dataset SOC). Then focalCor will use a 3*3 window to compare two datasets and get r values. DO I understand right?
thank you for your help!
Hope you have a great day!

**Comment by rhijmans** [comment]
That is correct if you do `focalCor(x, w=3, fun=cor)` 
And you can always compare with `raster::corLocal`

**Comment by zzw0034** [comment]
Hi Professor Hijmans,
May I ask a question about ggplot a rast layer.
I am trying to plot US SOC with 0.0083333 resolution. I first rast read the .tif file, then use as.data.frame() covert the tif file to the data frame. At last, i use ggplot()+geom_tile() to plot it. However, the data frame is very large because of the fine resolution of the raster layer. 
I can wait to plot it, but I want to know if you have a better and fast way to plot it with ggplot2?

thank you so much!
Zhuonan Wang

**Comment by rhijmans** [comment]
I do not know, but you can try the `tmap` package, or `rasterVis::gplot` (there was a bug so you may need the development version).

**Comment by rhijmans** [comment]
A general approach would be to first take a regular sample: `x <- spatSample(r, 100000, "regular", as.raster=TRUE)` or `aggregate`

**Comment by zzw0034** [comment]
Thank you, Professor Hijmans. I use aggregate to make the plot. By the way, now I am a post-doc at Emory University working on predicting spatial soil organic carbon stock. 
It is my great honor to ask you questions and learn with you. Thank you for your always timely answer. Nice to meet you here.

thank you!
