### ISSUE TITLE
writeRaster fails for relative path

### ISSUE THREAD

**Issue by ani-ghosh** [rspatial/terra#43]
`terra::writeRaster` fails if output filename contain relative path. Please add a check on the filename for writing using `terra:::.fullFilename`

**Comment by rhijmans** [comment]
I do not see that (at least in the development version).  Please provide an example

```
library(terra)
This is terra version 0.6.13 (alpha-release)
dir.create("test")
r = rast()
values(r) = 1:ncell(r)
writeRaster(r, "test/abc.tif")
#class       : SpatRaster 
#dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#data source : test/abc.tif 
#names       : lyr.1 
#min values  :     1 
#max values  : 64800 
```

**Comment by ani-ghosh** [comment]
Thanks Robert. The above example works as long as the `test` is created within the working directory. But if it is specified with reference/relative to home, writing fails. Example below:
> library(terra)
This is terra version 0.6.10 (alpha-release)
> dir.create("test/test1", recursive = TRUE)
> 
> r = rast()
> values(r) = 1:ncell(r)
> 
> #now try changing working directory
> setwd("test")
> #will not work 
> writeRaster(r, "test/test1/abc2.tif")
Error: (writeRaster) path does not exist
> 
> #but following will work irrespective of working directory
> writeRaster(r, terra:::.fullFilename("../test/test1/abc3.tif"))
class       : SpatRaster 
dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
data source : ../test/test1/abc3.tif 
names       : lyr.1 
min values  :     1 
max values  : 64800

It might be possible that I got caught up in a very specific case and perhaps this not how the `filename` should be provided, or it could follow the same logic as `rast(filename)`.

**Comment by rhijmans** [comment]
You are comparing two different paths. Perhaps  `../test/test1/' exists, whereas `/test/test1/` does not?

Either way, your suggestion is good, because `terra` should convert relative paths to absolute paths. Otherwise objects degenerate when the working directory is changed.
