### ISSUE TITLE
Cannot set extent of raster using xmin,xmax,ymin,ymax

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#431]
Currently `rast` has the arguments xmin, xmax, ymin, ymax, but using them instead of the extent argument results in an error.

```
library(terra)
#terra version 1.5.1

r<- rast(volcano, xmin=0, xmax=ncol(volcano)*10, ymin=0, ymax=nrow(volcano)*10)
# Error in .local(x, ...) : 
#   unused arguments (xmin = 0, xmax = 610, ymin = 0, ymax = 870)

my_ext<- ext(0, ncol(volcano)*10, 0, nrow(volcano)*10)
r<- rast(volcano, extent=my_ext)
```

**Comment by Rapsodia86** [comment]
You could do like this:
r<- rast(volcano, extent=c(xmin=0, xmax=ncol(volcano)*10, ymin=0, ymax=nrow(volcano)*10))

**Comment by ailich** [comment]
Thanks, @Rapsodia86, just pointing out that these arguments are in the documentation but don't seem to be implemented.

**Comment by Rapsodia86** [comment]
Not exactly. When you create a raster you can define ncols or nrows  OR/AND  xy min/max like here:
x <- rast(nrows=100, ncols=20, xmin=0, xmax=10,ymin=10,ymax=30)

But you already have a raster (volcano). So, in this case, you need to define the new extent not to assign xy min/max like you were creating an new object.
However, that might be indeed  confusing, so maybe it should be more detailed explained in the documentation.

**Comment by ailich** [comment]
@Rapsodia86, gotcha thanks for the clarification on when those arguments can be used.

**Comment by rhijmans** [comment]
`rast` is a method (generic function) with different "signatures" for its first argument `x`. So you have to carefully look at the documentation to see which version applies to your case.

If `x` is missing you have
```
## S4 method for signature 'missing'
rast(x, nrows=180, ncols=360, nlyrs=1, xmin=-180, xmax=180, 
          ymin=-90, ymax=90, crs, extent, resolution, vals, names, time, units)
``` 

Since `volcano` is a `matrix`, in this case, you have

```
## S4 method for signature 'matrix'
rast(x, type="", crs="", digits=6, extent=NULL)
```
