### ISSUE TITLE
`is.lonlat()` for data without CRS

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#434]
This is a rather tiny thing, but maybe worth discussing. `is.lonlat()` returns `FALSE` for data without CRS. However, in these cases, I would think a better approach should be to return `NA` -- as we do not know if the data is in "lonlat".

``` r
library(terra)
r = rast()
is.lonlat(r)
#> [1] TRUE

crs(r) = ""
is.lonlat(r)
#> [1] FALSE

# compare to sf
library(sf)
library(spData)
st_is_longlat(world)
#> [1] TRUE

st_crs(world) = ""
st_is_longlat(world)
#> [1] NA
```

<sup>Created on 2021-12-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ailich** [comment]
@Nowosad,, you can use `perhaps=TRUE` if you want to know if it might be lon/lat.

```
library(terra)
r = rast()
is.lonlat(r)
#> [1] TRUE

crs(r) = ""
is.lonlat(r)
#> [1] FALSE

is.lonlat(r, perhaps=TRUE, warn=FALSE)
#> [1] TRUE
```

**Comment by rhijmans** [comment]
I think that makes sense. You just need to use `is.lonlat(x, perhaps=TRUE)`  or `isTRUE(is.lonlat(x))` when used in an `if` statement.  I now get

```
library(terra)
r <- rast()

is.lonlat(r)
#[1] TRUE

is.lonlat(r, perhaps=T)
#[1] TRUE

crs(r) = ""

is.lonlat(r)
#[1] NA

is.lonlat(r, perhaps=T)
#[1] TRUE
#Warning message:
#[is.lonlat] assuming lon/lat crs 

is.lonlat(r, perhaps=T, warn=F)
#[1] TRUE
```

**Comment by Nowosad** [comment]
Thank you
