### ISSUE TITLE
pad option in terra::focal [question/enhancement]

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#436]
I've noticed that setting `na.rm=TRUE` in `terra::focal` is equivalent to setting both `na.rm=TRUE` and `pad=TRUE` in `raster::focal`. Generally I set both options to `TRUE`, so there is an added simplicity of just having one argument, but `pad` does allow the user to explicitly state how they want to handle edge effects, so it may be nice to have. Just bringing this up as I wasn't sure if `pad`'s omission from `terra::focal` was intentional or not.

**Comment by rhijmans** [comment]
It is intentional, because it makes the code less complex and I can't think of a situation where you would want `pad=F` and `na.rm=T` . However if someone could make a reasonable case for that option, I would resurrect the `pad` argument
