### ISSUE TITLE
`crop()` performance

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#437]
`crop()` is about 3 times faster in `{terra}` than in `{raster}`, but I'm just wondering if any other modification could be made to make it even faster?

```r
library(terra)

# xmin, xmax, ymin, ymax
area = ext(598500, 727500, 5682100, 5781000)
rasters = list.files("data/LC08_L1TP_190024_20200418_20200822_02_T1/",
                     pattern = "\\.TIF$", full.names = TRUE)
ras = rast(rasters) * 1

### terra::crop
system.time(ras_crop <- crop(ras, area, snap = "out"))
#>  user  system elapsed
#> 2.314   2.438   4.759

### base::array
arr = as.array(ras)

## input rasters are 'unit16' so using integer datatype
## makes this operation even a little faster
# storage.mode(arr) = "integer"

system.time({
  colmin = colFromX(ras, area$xmin)
  colmax = colFromX(ras, area$xmax)
  rowmin = rowFromY(ras, area$ymax)
  rowmax = rowFromY(ras, area$ymin)
  arr_crop = arr[rowmin:rowmax, colmin:colmax, ]
  })
#>  user  system elapsed
#> 1.383   0.412   1.796

ras_crop_arr = as.array(ras_crop)
identical(ras_crop_arr, arr_crop)
#> [1] TRUE
```

**Comment by rhijmans** [comment]
Using the data you used in another issue, I get:

```

url = "https://landsat.usgs.gov/sites/default/files/C2_Sample_Data/LE07_L1TP_042027_20050927_20200914_02_T1.zip"
if (!file.exists(basename(url))) {
	download.file(url, basename(url), mode="wb")
	unzip(basename(url))
}

path = "LE07_L1TP_042027_20050927_20200914_02_T1"
ff = list.files(path, ".+B[1234578]+\\.TIF$", full.names = TRUE)
					 
library(terra)

test <- function(x, e, inmem = FALSE) {
	if (inmem) {
		x <- x * 1
        arr <- as.array(x)
		m <- as.matrix(x)
    } else {
        arr <- NULL
        m <- NULL
    }
	print(system.time(r_crop <- crop(x,e)))

	if (is.null(m)) {
		print(system.time(as.matrix(x)[cellFromRowColCombine(x, rowFromY(x, e$ymax):rowFromY(x, e$ymin), colFromX(x, e$xmin):colFromX(x, e$xmax)), ]))
	} else {
		print(system.time(m[cellFromRowColCombine(x, rowFromY(x, e$ymax):rowFromY(x, e$ymin), colFromX(x, e$xmin):colFromX(x, e$xmax)), ]))	
	}
	
	system.time({
		if (is.null(arr)) arr = as.array(x)
		colmin = colFromX(x, e$xmin)
		colmax = colFromX(x, e$xmax)
		rowmin = rowFromY(x, e$ymax)
		rowmax = rowFromY(x, e$ymin)
		arr_crop = arr[rowmin:rowmax, colmin:colmax, ]
	})
}


e <- ext(550000, 600000, 5200000, 5300000)
r <- rast(ff[1])
test(r, e)
#   user  system elapsed 
#   0.08    0.03    0.11 
#  user  system elapsed 
#   0.91    0.39    1.30 
#   user  system elapsed 
#   1.72    0.64    2.38 
test(r, e, inmem=TRUE)
#   user  system elapsed 
#   0.06    0.00    0.06 
#   user  system elapsed 
#   0.42    0.01    0.44 
#   user  system elapsed 
#   0.02    0.03    0.05 
 
r <- rast(ff[1:5])
test(r, e)
#   user  system elapsed 
#   0.44    0.18    0.61 
#   user  system elapsed 
#   3.44    2.37    5.83 
#   user  system elapsed 
#   9.52    4.59   14.11 
test(r, e, inmem=TRUE)
#   user  system elapsed 
#   0.18    0.17    0.36 
#   user  system elapsed 
#   0.55    0.02    0.57 
#   user  system elapsed 
#   0.18    0.00    0.17 

```

So it looks like `crop` is more efficient when starting with a file,  but `as.array` could probably be faster (and having a matrix may be more practical). When you have all values in an array that you subset, that will be always faster then crop, but then all you have is an array.  The relative time difference I get is not as much for me as for you. That could be related to your files and the size of the extent; and to the memory needed (if terra decides to go to disk there will be a speed penalty). Still, there is no question that `crop` *could* be faster; but right now it does not look like a priority.

**Comment by kadyb** [comment]
Thanks for your detailed response! For reference, in my orginal post I used Landsat 8 scene (link [here](https://drive.google.com/uc?id=1lzglfQJqlQh9OWT_-czc5L0hQ1AhoR8M&export=download) on Google Drive).

Practically, I used the example with a subset of the array because it seems to me (but I may be wrong) that this is how `{stars}` and `{velox}` work, which are faster. However, these speed differences may be because the code is already strong optimized in base R. The same is probably true for Python packages which are based on `{numpy}` / `{xarray}`. I was surprised how fast is `{rioxarray}` (`{terra}`: 4.7 s, `{rioxarray}`: 0.3 s). I wonder if this is because the cropping is done in-place ([code](https://github.com/corteva/rioxarray/blob/34800bbb3cc4416919068cccc333cf4ab5a5aa3b/rioxarray/raster_dataset.py#L226))?

> Still, there is no question that crop could be faster; but I do not see anything obvious. That is, it would probably require a lot of code specifically for one function. I try to avoid that unless it is really warranted. Right now it does not look like a priority.

I fully understand it. If it requires a huge amount of work, for little benefit, then there is no point. Thanks for the information!

**Comment by rhijmans** [comment]
`terra` always considers that a SpatRaster may consist of data in memory and on disk, it does not change values in-place as that does not fit with R, and it has more overhead as it needs to keep track of more than just the array.  I assume I can speed things up a bit by considering special cases (e.g. one data source, in memory); but there would b a cost in code clarity and maintenance. 

Be that as it may, I was able to speed things up. When I looked again at the timings above, one thing that stands out is that `crop` with values in memory was fast enough for one layer, but not for multiple layers. This is now gone and I see (with your example): 

```
 system.time(ras_crop <- crop(ras, area, snap = "out"))
 #  user  system elapsed 
 #  0.83    0.23    1.07 
 
arr = as.array(ras)
system.time({
   colmin = colFromX(ras, area$xmin)
   colmax = colFromX(ras, area$xmax)
   rowmin = rowFromY(ras, area$ymax)
   rowmax = rowFromY(ras, area$ymin)
   arr_crop = arr[rowmin:rowmax, colmin:colmax, ]
   })
#   user  system elapsed 
#   0.95    0.06    1.01 
```
Not quite python speed, but much better. Thank you for pushing me on this!

**Comment by kadyb** [comment]
For me these timings are a bit different, but the improvement is indeed noticeable! Thank you very much!

```
### BEFORE (v. 1.4.22)
#> expression      min median `itr/sec`
#> 1 terra_file    7.27s  7.28s     0.137
#> 2 terra_memory  4.56s   4.6s     0.215
#> 3 array         1.79s   1.8s     0.538

### THIS PR (v. 1.5.2)
#> expression      min median `itr/sec`
#> 1 terra_file       6s  6.01s     0.166
#> 2 terra_memory  2.91s  2.93s     0.327
#> 3 array         1.79s   1.8s     0.538
```
