### ISSUE TITLE
invalid 'times' argument` in aggregate(fun = sd) when fact > 1000 

### ISSUE THREAD

**Issue by hrvg** [rspatial/terra#44]
```
library(terra)
r <- rast(nrow=1E4, ncol=1E4)
values(r) <- runif(n = ncell(r))
terra::aggregate(r, fact = 1000, fun = sd) # works
terra::aggregate(r, fact = 1001, fun = sd) # does not work
terra::aggregate(r, fact = 1001, fun = mean) # works
```
When selecting a factor > 1,000, aggregate fails because the code below from `aggregate` leads to `nr = 0`, leading to an error in `rep`.

```
b <- x@ptr$getBlockSize(4)
nr <- floor(b$nrows[1] / fact[1]) * fact[1]
nrs <- rep(nr, floor(nrow(x)/nr))
```
I guess the 1,000 threshold is linked to the chunking process. 

An easy fix seems to be:
`nr <- min(1, floor(b$nrows[1] / fact[1]) * fact[1])`

**Comment by rhijmans** [comment]
Good one, thanks!  I did this 

`nr <- max(1, floor(b$nrows[1] / fact[1])) * fact[1]
`

**Comment by hrvg** [comment]
Thanks for the fix! And catching my mistake with `min`.
