### ISSUE TITLE
"Error: [rast] layer number for R, G, B, cannot exceed the number of layers" when reading in multiband raster

### ISSUE THREAD

**Issue by sm-potter** [rspatial/terra#440]
I have a raster file which has three bands.  I want to read in only band 1 which I am reading in like this on a windows computer:

`library(terra)`

`test  = rast("/path_to_ras/test_ras.tif")[[1]]`

This works fine on windows but I also want to do the same thing on linux.  Due to the nature of my computing resource I need to run R through anaconda, which may be the issue, but when I try to read in the raster the exact same way as described above I get the following error:

`Error: [rast] layer number for R, G, B, cannot exceed the number of layers`

Apologies for the non-reproducible example.

**Comment by rhijmans** [comment]
I suspect you are using an old version of `terra` on your linux system and that the error will go away of you update the package.

**Comment by sm-potter** [comment]
Ah yes thank you, and yes not RGB, just multiband of my own "stacking"
