### ISSUE TITLE
NaN min and max values following terra::project

### ISSUE THREAD

**Issue by MarianaDevault** [rspatial/terra#445]
Hi,

I have been able to successfully import a .tif raster into R by using the _rast_ function in _terra_. However, as I try to project this newly imported SpatRaster layer to Eckert IV, the min value and max value become NaN. Could anyone advise on what I am doing wrong and how I could solve this problem?

I am using the R version 4.1.2 and have installed the _terra_ package as follow: 
install.packages('terra', repos='https://rspatial.r-universe.dev')

![terra_project](https://user-images.githubusercontent.com/51536173/146087080-c1a80c59-8f0d-47b0-a6af-4b280a05b870.png)

**Comment by rhijmans** [comment]
Thank you very much for reporting this. Please never include screenshots, but rather include the text (code and R responses, including error messages). That saves us a lot of time. 

I see that indeed this does not work with `mask=TRUE` 

```
library(terra)
r <- rast(ymin=-64.41, res=1/12)
w = geodata::world(path=".")
r = rasterize(w, r)
x <- project(r, "+proj=eck4")
# Ok, but with some areas duplicated
plot(x)
```
![eck](https://user-images.githubusercontent.com/11481397/146089108-8395aa30-cb0f-4d70-82b9-175e213d138d.png)


`mask=TRUE` should take care of that, but something goes does not work

```
x <- project(r, "+proj=eck4", mask=T)
# empty plot
plot(x)
```

**Comment by rhijmans** [comment]
It now works again, at least for my example: 

```
x <- project(r, "+proj=eck4", mask=T)
plot(x)
``` 

![eckfixed](https://user-images.githubusercontent.com/11481397/146105858-fda55d8e-817a-4826-915c-9a13c49109fa.png)

You can try for yourself by installing the development version with  `install.packages('terra', repos='https://rspatial.r-universe.dev')`   but note that it can take a couple of hours before that has been updated

**Comment by MarianaDevault** [comment]
Many thanks @rhijmans! It works perfectly now.
