### ISSUE TITLE
making type integer stick when reading/writing

### ISSUE THREAD

**Issue by LDalby** [rspatial/terra#446]
Hi

While debugging a datatype issue in my code I ran into two things I don't quite understand. 
First, creating a spatRaster with integer values does not make it of type int (according to `is.int`). However you can call `round` on the spatRaster object does make it integer. Is that not a bit odd?

Second, I noticed that I could not get the integer type stick to the object if written to disk and read in again. Even using `datatype = "INT1U"`. 

Is there a way to ensure that the spatRaster object gets the type of the tiff file being read?

``` r
library(terra)
#> terra version 1.5.2
is.integer(1:100)
#> [1] TRUE
r <- rast(nrows=10, ncols=10, vals=1:100)
is.int(r)
#> [1] FALSE
rint <- round(r)
is.int(rint)
#> [1] TRUE
# Writing and reading makes it loose it type
tmp <- tempfile(fileext = ".tif")
writeRaster(rint, filename = tmp, datatype = "INT1U")
rread <- rast(tmp)
is.int(rread)
#> [1] FALSE
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Ubuntu 20.04.3 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language en_US:en
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Copenhagen
#>  date     2021-12-15
#>  pandoc   2.11.4 @ /usr/lib/rstudio/bin/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  backports     1.4.1   2021-12-13 [1] CRAN (R 4.1.2)
#>  cli           3.1.0   2021-10-27 [3] CRAN (R 4.1.1)
#>  codetools     0.2-18  2020-11-04 [4] CRAN (R 4.0.3)
#>  crayon        1.4.2   2021-10-29 [3] CRAN (R 4.1.1)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.1.2)
#>  ellipsis      0.3.2   2021-04-29 [3] CRAN (R 4.0.5)
#>  evaluate      0.14    2019-05-28 [3] CRAN (R 4.0.0)
#>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
#>  fastmap       1.1.0   2021-01-25 [3] CRAN (R 4.0.3)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
#>  glue          1.5.1   2021-11-30 [1] CRAN (R 4.1.2)
#>  highr         0.9     2021-04-16 [3] CRAN (R 4.0.5)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
#>  knitr         1.36    2021-09-29 [3] CRAN (R 4.1.1)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.1   2020-11-17 [3] CRAN (R 4.0.3)
#>  pillar        1.6.4   2021-10-18 [1] CRAN (R 4.1.1)
#>  pkgconfig     2.0.3   2019-09-22 [3] CRAN (R 4.0.0)
#>  purrr         0.3.4   2020-04-17 [3] CRAN (R 4.0.0)
#>  R.cache       0.15.0  2021-04-30 [1] CRAN (R 4.1.0)
#>  R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.1.0)
#>  R.oo          1.24.0  2020-08-26 [1] CRAN (R 4.1.0)
#>  R.utils       2.11.0  2021-09-26 [1] CRAN (R 4.1.1)
#>  Rcpp          1.0.7   2021-07-07 [1] CRAN (R 4.1.0)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.0)
#>  rlang         0.4.12  2021-10-18 [3] CRAN (R 4.1.1)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13    2020-11-12 [3] CRAN (R 4.0.3)
#>  sessioninfo   1.2.2   2021-12-06 [3] CRAN (R 4.1.2)
#>  stringi       1.7.6   2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr       1.4.0   2019-02-10 [3] CRAN (R 4.0.0)
#>  styler        1.6.2   2021-09-23 [1] CRAN (R 4.1.1)
#>  terra       * 1.5-2   2021-12-15 [1] Github (rspatial/terra@4dbe623)
#>  tibble        3.1.6   2021-11-07 [1] CRAN (R 4.1.2)
#>  utf8          1.2.2   2021-07-24 [3] CRAN (R 4.1.0)
#>  vctrs         0.3.8   2021-04-29 [3] CRAN (R 4.0.5)
#>  withr         2.4.3   2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29    2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.1   2020-02-01 [3] CRAN (R 4.0.0)
#> 
#>  [1] /home/au206907/R/x86_64-pc-linux-gnu-library/4.1
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by kadyb** [comment]
I have wondered about that too, but in the context of new feature. Doesn't `{terra}` always return double datatype, even though the input is e.g. byte or integer? Would it be possible to return integer in R if the data is not floating number?

```r
library("terra")

tif = system.file("ex/elev.tif", package = "terra")
ras = rast(tif)
val = values(ras, mat = FALSE)
typeof(val)
#> [1] "double"

system(paste("gdalinfo", tif))
#> Band 1 Block=95x43 Type=Int16, ColorInterp=Gray
```

**Comment by rhijmans** [comment]
Thank you. The explicit support for `bool` and `int` datatypes was introduced in the current development version, but still incomplete, so the issue you raised is very timely. 

With the changes I just made, `is.int(x)` is `TRUE` if you assign integers or read from a file with integers. 

```
library(terra)
#terra version 1.5.2
r <- rast(ncol=10, nrow=10, vals=1:100)
is.int(r)
#[1] TRUE
 
writeRaster(r, "test.tif", overwrite=T, datatype="INT2S")
x <- rast("test.tif")
is.int(x)
#[1] TRUE
 
writeRaster(r, "test.tif", overwrite=T, datatype="INT1U")
x <- rast("test.tif")
is.int(x)
#[1] TRUE
 
writeRaster(r, "test.tif", overwrite=T)
x <- rast("test.tif")
is.int(x)
#[1] FALSE
```

So there is no automatic choice of int datatype when writing. I am considering that, but not sure about it.

As for @kadyb's request. That is a feature that existed, but only when you request a `data.frame`

```
x = rast(system.file("ex/elev.tif", package = "terra"))
v = values(r)
typeof(v)
#[1] "double"

v = values(r, dataframe=TRUE)
sapply(v, typeof)
#    lyr.1 
#"integer" 
``` 

So `values` gives you the raw numbers, whereas the data.frame could give you a combination of numeric, integer, bool or factor (each layer can be different). 
I am afraid that if values start returning different data types (especially factors) a lot of code may break; but then again, perhaps that is what should happen. Also, there would be a little performance cost to coerce to bool or int, and in most cases users might not care. Again, I am undecided.

**Comment by LDalby** [comment]
Ahh OK, I was not aware that this was a brand new feature. I had simply not been looking for this functionality before. 

Thanks a lot!

**Comment by kadyb** [comment]
Thanks, Robert. I didn't know about that. Maybe it would be reasonable to mention it in the documentation? Something like:

`values(x, dataframe=TRUE)` and `as.data.frame(x)` return the corresponding datatype (factor, integer, double) as opposed to `values(x)`, `as.matrix(x)`, `as.vector()`, which always return double?

**Comment by kadyb** [comment]
Has it stopped working? Previously, `is.int(x)` was `TRUE`. 

```r
library("terra")
#> terra 1.5.18 (c255b93 commit)
x = rast(system.file("ex/elev.tif", package = "terra"))
is.int(x)
#> [1] FALSE
```

**Comment by rhijmans** [comment]
I get `TRUE` and  

```
f <- system.file("ex/elev.tif", package = "terra")
describe(f)[33]
[1] "Band 1 Block=95x43 Type=Int16, ColorInterp=Gray"
```
Is that what you see?

**Comment by kadyb** [comment]
Yes. This seems to work on Windows, but not on Linux. I was able to reproduce this on Google Colab with stable (CRAN) version.

<details>
<summary><b>Session Info</b></summary>

R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] terra_1.5-18

loaded via a namespace (and not attached):
[1] compiler_4.1.2   tools_4.1.2      Rcpp_1.0.8      
[4] codetools_0.2-18

</details>

**Comment by rhijmans** [comment]
That is really intriguing. On my computer I get 

```
packageVersion("terra")
#[1] ‘1.5.17’
x = rast(system.file("ex/elev.tif", package = "terra"))
is.int(x)
#[1] TRUE
sessionInfo()
#R version 4.1.2 (2021-11-01)
#Platform: x86_64-pc-linux-gnu (64-bit)
#Running under: Ubuntu 20.04.3 LTS
```

Colab has the save OS and R and terra, but there it returns `FALSE`.

**Comment by kadyb** [comment]
In terra 1.5.12 it works fine:

```r
url = "https://cran.r-project.org/src/contrib/Archive/terra/terra_1.5-12.tar.gz"
install.packages(url, repos = NULL, type = "source")
library("terra")
#> terra 1.5.12
x = rast(system.file("ex/elev.tif", package = "terra"))
is.int(x)
#> [1] TRUE
```

**Comment by rhijmans** [comment]
The change I made is to only set `is.int` to TRUE if the file does not have a scale/offset (in that case the values may be stored as integers, but after applying the scale and offset they would normally be real numbers; See https://github.com/rspatial/terra/issues/509).
 
For some reason on some systems, a scale/offset is reported for this file, even if there is not one. It does not change the results because the offset is zero and the scale is 1, so the adjustment made is `v = v * 1 + 0`.  

That case is now caught and the scale/offset ignored.  And `is.int` now returns `TRUE` on colab:

```
remotes::install_github("rspatial/terra")
library(terra)
f = system.file("ex/elev.tif", package="terra")
r = rast(f)
is.int(r)
#TRUE
```

**Comment by kadyb** [comment]
Works on my PC too! I see that it was a complicated problem and hard to reproduce. Thank you so much!
