### ISSUE TITLE
Edit to improve clarity

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/terra#449]
https://github.com/rspatial/terra/blob/d0dd3cf38d124b985cb5548f8fbc5be1d6cacf61/man/expanse.Rd#L36

Replace "numeric. The sum of the size of the cells that are not NA" with "numeric. The total of the cells (square meters, square kilometers, or hectares) that are not NA" of something similar. The logic of the edit is that hectare is a measure of area whereas m or km are treasures of distance.

**Comment by rhijmans** [comment]
Thanks!
