### ISSUE TITLE
Blurred areas on edge of reprojected grids

### ISSUE THREAD

**Issue by phytoclast** [rspatial/terra#453]
I have an extensive set of global climatic and dem derivative grids that I developed in unprojected lat-long, which I then reprojected to an azumuthal equal area projection centered on North America, 
However, the area around Alaska becomes blurred, as for example this 5 km resolution DEM where the mountains near the top of the map are smeared while the mountains below are well defined:
![image](https://user-images.githubusercontent.com/34171749/147312330-8ad3e210-ca6f-41f1-8af1-57b85817e345.png)

When I crop it down to an area more local to Alaska before projecting, the effect is not as bad:
![image](https://user-images.githubusercontent.com/34171749/147312415-c318430f-4d6b-413c-bb3a-2e8d4ee1a3ba.png)

But if I use the raster package, the mountains show up very sharply even when projecting the entire extent of North America:
![image](https://user-images.githubusercontent.com/34171749/147312552-2848e895-fff1-4989-b5f4-fef5367766b1.png)

Full extent of destination projection:
extent(elev.n)
class      : Extent 
xmin       : -5863550 
xmax       : 4436450 
ymin       : -3959298 
ymax       : 4840702 
![image](https://user-images.githubusercontent.com/34171749/147312769-a17515d9-452a-49ed-a977-63ae5757e492.png)

This is the destination projection:
> crs(elev.n)
Coordinate Reference System:
Deprecated Proj.4 representation:
 +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
WKT2 2019 representation:
PROJCRS["unknown",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Lambert Azimuthal Equal Area",
        METHOD["Lambert Azimuthal Equal Area",
            ID["EPSG",9820]],
        PARAMETER["Latitude of natural origin",45,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-100,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]]]

sample code:
elev.n <- project(Elev, newgrid, method='bilinear', filename = 'nam5k/elev.tif', overwrite=T) 

I am less familiar with the stars package, but managed to get similar blurring resampling effect when using the st_warp function.
I have terra version 1.4-22

**Comment by rhijmans** [comment]
What you see may be a mapping phenomenon, not a data quality issue.
Here is a way, perhaps, to reproduce what you do:

```
library(geodata)
e <- elevation_global(2.5, ".")
e <- crop(e, c(-180, -20, 0, 90))
x <- rast(ext(-4200000, 3500000, -4133529, 4658380 ), res=5000, crs="+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m")
z <- project(e, x)
plot(z, col= gray(0:255 / 255)) 
``` 
But now zoom in 

```
plot(z, ext=ext(-3180495, -916167, 1957169, 4152181),  col=gray(0:255 / 255))
plot(z, ext=ext(-2396403, -1386565, 2889234, 3798804), col=gray(0:255 / 255))
```

![alaska](https://user-images.githubusercontent.com/11481397/147331320-54a2f1d2-d4ca-4b0e-a19b-5d0143eb1af5.png)

That does not look bad? 

You can use plot(z, `maxcell=Inf`) for the entire region to avoid sampling and get the best resolution

**Comment by phytoclast** [comment]
It is nice to know that there is a way of calling upon the elevation layers online to provide a working example.
What I didn't mention that my screenshots had been rendered in QGIS so that I could be more casual about zooming in without cropping and didn't need to set the maxcell.

With your example I saved the output to file, and displayed again in QGIS. The blurring happens to a lesser extent if I crop to North America, first. Projecting from the full global extent of the DEM to the empty raster x you provided resulted in more blurring, but This time the blurring started in the northern portion of the Lower 48. Nearest neighbor didn't have any unexpected blurring, while using the raster package with bilinear also didn't have the blurring. Clearly there is a zone where the pixels are being averaged over a larger area than necessary when a resampling method is used other than nearest neighbor.

library(geodata)
library(raster)
e0 <- elevation_global(2.5, ".")
e <- crop(e0, c(-180, -125, 55, 70))
x <- rast(ext(-4200000, 3500000, -4133529, 4658380 ), res=5000, crs="+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m")
x1 <- rast(ext(-2600000, -2200000, 2700000, 3000000 ), res=5000, crs="+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m")

#project from full extent
z <- project(e0, x, method = 'bilinear')
plot(z, ext=ext(-2600000, -2200000, 2700000, 3000000),  col=gray(0:255 / 255), maxcell=Inf)
![image](https://user-images.githubusercontent.com/34171749/147368163-39322702-631d-435d-a96b-b6d6068c8f25.png)

#project from full extent to a cropped extent
z <- project(e0, x1, method = 'bilinear')
plot(z, ext=ext(-2600000, -2200000, 2700000, 3000000),  col=gray(0:255 / 255), maxcell=Inf)
![image](https://user-images.githubusercontent.com/34171749/147368175-8e05749b-2889-4d88-abe4-10d35f6bc7f7.png)


#project from a cropped extent
z <- project(e, x, method = 'bilinear')
plot(z, ext=ext(-2600000, -2200000, 2700000, 3000000),  col=gray(0:255 / 255), maxcell=Inf)
![image](https://user-images.githubusercontent.com/34171749/147368183-2a5a81ef-2451-483e-bcfa-32c82e4cfb9d.png)


#project using the raster package
z <- projectRaster(raster(e0), raster(x), method = 'bilinear')
z1 <- rast(z)
plot(z1, ext=ext(-2600000, -2200000, 2700000, 3000000),  col=gray(0:255 / 255), maxcell=Inf)
![image](https://user-images.githubusercontent.com/34171749/147368200-3fee9fd4-a535-49c3-a520-d0c71b0d67ee.png)

#project using the nearest neighbor resampling
z <- project(e0, x, method = 'near')
plot(z, ext=ext(-2600000, -2200000, 2700000, 3000000),  col=gray(0:255 / 255), maxcell=Inf)
![image](https://user-images.githubusercontent.com/34171749/147368358-e6ecc03b-aa29-430a-a423-80ffbf113833.png)

#zoom to another extent showing better detail south of mount hood
z <- project(e0, x, method = 'bilinear')
plot(z, ext=ext(-1800000, -1500000, 120000, 500000),  col=gray(0:255 / 255), maxcell=Inf)
![image](https://user-images.githubusercontent.com/34171749/147368543-391f74fb-6264-4a37-9a8f-3d31908231dc.png)

#zoom to another extent near mount hood using the raster package
z <- projectRaster(raster(e0), raster(x), method = 'bilinear')
z1 <- rast(z)
plot(z1, ext=ext(-1800000, -1500000, 120000, 500000),  col=gray(0:255 / 255), maxcell=Inf)
![image](https://user-images.githubusercontent.com/34171749/147368549-d870dd12-e0b2-4f51-bb39-00af2637fdc2.png)

**Comment by rhijmans** [comment]
You would expect most blurring at high latitudes because, in this example, the original cells are much smaller than the new cells. When using nearest-neighbor the data remain "sharp", but surely less accurate. 

Nevertheless, there is more going on here. What you uncovered is puzzling. That is, the result of resample depends on the extent of the input data:

````
library(geodata)
library(raster)
e0 <- elevation_global(2.5, ".")
e <- crop(e0, c(-180, -125, 55, 70))
x <- rast(ext(-4200000, 3500000, -4133529, 4658380 ), res=5000, crs="+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m")
z <- project(e0, x, method = 'bilinear')
z1 <- crop(z, ext(-2600000, -2200000, 2700000, 3000000))
z <- project(e, x, method = 'bilinear')
z2 <- crop(z, ext(-2600000, -2200000, 2700000, 3000000))
d <- z1 - z2 
minmax(d)
#     wc2.1_2.5m_elev
#[1,]       -323.6619
#[2,]        309.5325
``` 

Even for very small differences. Adding one row and col to `x2`
``` 
x3 <- extend(x2, 1)
z3 <- crop(project(e2, x3, method = 'bilinear'), x2)
minmax(z3-z2)
#     wc2.1_2.5m_elev
#[1,]       -6.561035
#[2,]       10.135742
``` 

`terra` uses GDAL for this whereas `raster` has its own algorithm. I need to have a new look at what GDAL does to understand whether this is a feature, a bug, or neither, and if it can be avoided.  If need be, I can of course re-implement the raster algorithm as an alternative path.

**Comment by rhijmans** [comment]
This appears to be a known and somewhat complex to solve issue: https://github.com/OSGeo/gdal/issues/2810

**Comment by rhijmans** [comment]
I have added an new argument `gdal=FALSE` to use the equivalent of the algorithm in `raster`. This is not sensitive to the output extent:

```
library(geodata)
#Loading required package: terra
#terra 1.5.8
e1 <- elevation_global(2.5, ".")
e2 <- crop(e1, c(-180, -125, 55, 70))
x1 <- rast(ext(-4200000, 3500000, -4133529, 4658380 ), res=5000, crs="+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m")
x2 <- crop(x1, ext(-2600000, -2200000, 2700000, 3000000))
 
z1 <- project(e1, x2, method = 'bilinear', gdal=FALSE)
z2 <- project(e2, x2, method = 'bilinear', gdal=FALSE)
round(minmax(z1 - z2), 5)
#     wc2.1_2.5m_elev
#[1,]               0
#[2,]               0
 
z1 <- project(e1, x1, method = 'bilinear', gdal=FALSE) |> crop(x2)
z2 <- project(e1, x2, method = 'bilinear', gdal=FALSE)
minmax(z1 - z2 )
#     wc2.1_2.5m_elev
#[1,]               0
#[2,]               0
 
x3 <- extend(x2, 1)
z3 <- project(e2, x3, method = 'bilinear', gdal=FALSE)  |> crop(x2)
round(minmax(z3-z2), 5)
#     wc2.1_2.5m_elev
#[1,]               0
#[2,]               0
```
