### ISSUE TITLE
terra::focal calculations involving more than one layer?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#454]
I need to perform focal calculations based on multiple layers (four). Is there a way to efficiently conduct such 4D-convolutions in a `terra` raster? The `focal` function is only applicable layer by layer, as I understand it. I know I can apply the `focalValues` function on each layer separately, and then do the necessary matrix calculations. But I was wondering if there are some other ways.

**Comment by rhijmans** [comment]
The development version has `focal3D` for that. With 3D referring to ("row", "column", "layer").
