### ISSUE TITLE
'inset' 'border' argument impedes 'border' being passed to 'plot'

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#456]
Hello,
'inset' has a useful '...' for additional arguments to be passed to 'plot', but 'border' cannot be used for inset polygons, because 'inset' already has its own 'border' argument (for the border of the inset itself):
```
v <- vect(system.file("ex/lux.shp", package = "terra"))
x <- v[v$NAME_2 == "Diekirch", ]
plot(x)
inset(v, col = "brown", border = "lightgrey")

```
Could the inset 'border' argument be renamed (to 'iborder', 'inset.border' or something similar) to avoid this conflict?

**Comment by rhijmans** [comment]
Thank you very much. I renamed `border` to `perimeter`, and added an argument `pper` to allow changing the line properties (color, width, type). I renamed `pbx` to `pbox` for clarity. 

```
library(terra)
v <- vect(system.file("ex/lux.shp", package = "terra"))
x <- v[v$NAME_2 == "Diekirch", ]
plot(x)
inset(v, col = "brown", border = "lightgrey", perimeter=TRUE, pper=list(col="orange", lwd=3, lty=2), 
              box=ext(x), pbox=list(col="blue", lwd=2))
``` 

![inset](https://user-images.githubusercontent.com/11481397/147497784-bb092deb-beb7-471c-962c-2a76a4c6e243.png)
