### ISSUE TITLE
warning against updated system requirements

### ISSUE THREAD

**Issue by edzer** [rspatial/terra#459]
Ubuntugis unstable just updated all its libraries; this means I should recompile terra. If I don't, I see for instance
```r
> library(terra)
terra version 1.5.2
> q()
double free or corruption (out)
Aborted (core dumped)
```
Library `sf` for instance warned me:
```r
> library(sf)
Linking to GEOS 3.10.1, GDAL 3.3.2, PROJ 7.2.1; sf_use_s2() is TRUE
WARNING: different compile-time and runtime versions for GEOS found:
Linked against: 3.10.1-CAPI-1.16.0 compiled against: 3.9.1-CAPI-1.14.2
It is probably a good idea to reinstall sf, and maybe rgeos and rgdal too
```
Maybe it is an idea to include such a warning in `terra` as well.

**Comment by rhijmans** [comment]
Yes, of course. Thank you very much!

**Comment by rhijmans** [comment]
And I see that the versions have changed like this:

```
GDAL 2.2.3 -> 3.4.0
PROJ 4.9.3 -> 8.2.0
GEOS 3.6.2 -> 3.10.1
```

That is a great (and early) start for 2022!

**Comment by edzer** [comment]
Yes, it is! The check we now have in terra/sf/rgdal/rgeos/lwgeom is afaics only sensitive to GEOS versions; will let you know when we manage the same for PROJ and/or GDAL.
