### ISSUE TITLE
`writeVector()` performance

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#460]
I noticed that `terra::writeVector()` is slower than `sf::write_sf()` on my PC.

```r
library(sf)
library(terra) # 1.4.22

n = 100000
df = data.frame(x = runif(n, 171000, 861000), y = runif(n, 133000, 775000))

### points ###
pts_terra = vect(df, geom = c("x", "y"), crs = "epsg:2180")
pts_terra = pts_terra[, -(1:2)]
pts_sf = st_as_sf(df, coords = c("x", "y"), crs = "epsg:2180")

tmp1 = tempfile(fileext = ".gpkg")
tmp2 = tempfile(fileext = ".gpkg")

## sf
system.time(write_sf(pts_sf, tmp1))
#> user  system elapsed
#> 4.36    0.71    5.06

## terra
system.time(writeVector(pts_terra, tmp2))
#>  user  system elapsed
#> 14.54   89.76  106.46

### polygons ###
buff_terra = buffer(pts_terra, 100, quadsegs = 10)
buff_sf = st_buffer(pts_sf, 100, nQuadSegs = 10)

tmp1 = tempfile(fileext = ".gpkg")
tmp2 = tempfile(fileext = ".gpkg")

## sf
system.time(write_sf(buff_sf, tmp1))
#> user  system elapsed
#> 5.25    0.84    6.08

## terra
system.time(writeVector(buff_terra, tmp2))
#>  user  system elapsed
#> 22.92  106.59  130.55
```

**Comment by kadyb** [comment]
BTW: I wonder if `terra::vect(df, geom = c("x", "y"), crs = "epsg:2180")` should not return 0 attributes/fields by default like `sf::st_as_sf(df, coords = c("x", "y"), crs = "epsg:2180")`? Now we have to remove them manually to make the saved files identical.

```r
pts_terra = vect(df, geom = c("x", "y"), crs = "epsg:2180")
#> dimensions  : 1e+05, 2  (geometries, attributes)

pts_sf = st_as_sf(df, coords = c("x", "y"), crs = "epsg:2180")
#> Simple feature collection with 100000 features and 0 fields
```

**Comment by rhijmans** [comment]
I agree that adding the x/y as attributes is wasteful, so they are now removed. 
I also note that the write speeds are about the same for `.shp`. terra loops over the geometries when writing. I assume that with gpkg it may be possible to do a single insert query instead, and that terra is doing an insert query for each records instead.  I need to have a close look at this.

**Comment by rhijmans** [comment]
It turned out that it is indeed possible to create the data structure and then do one write. I need to do some more testing, but the slowness is gone. Thanks, that was very useful.

**Comment by kadyb** [comment]
The improvement is huge (especially on the HDD). The `{sf}` and `{terra}` timings are now similar for the gpkg format. Thank you so much!

```r
## sf points
system.time(write_sf(pts_sf, tmp1))
#> user  system elapsed
#> 4.43    0.68    5.20

## terra points
system.time(writeVector(pts_terra, tmp2))
#>  user  system elapsed
#>  4.25    0.53    4.78

## sf polygons
system.time(write_sf(buff_sf, tmp1))
#> user  system elapsed
#> 5.16    0.95    6.11

## terra polygons
system.time(writeVector(buff_terra, tmp2))
#>  user  system elapsed
#>  5.42    1.00    6.40
```
