### ISSUE TITLE
add north arrow

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#461]
Hi! Is there a chance of including a function for adding a north arrow to a map? We already have the scale bar and inset map, and it's quite a bit of overhead (for students especially) to install another package (like 'cartography' or 'GISTools') just to plot a north arrow  :)

**Comment by rhijmans** [comment]
You can now use `arrow()` for that 

```

library(terra)
par(mar=c(0,0,0,0))
xy = cbind(c(0,8), c(1,6)); plot(xy, type="n", xlab="", ylab="", axes=FALSE)
for (i in 1:7) {
	arrow(xy=cbind(i,5), type=i)
}
for (i in 1:7) {
	arrow(xy=cbind(i,4), angle=45, type=i)
}
for (i in 1:7) {
	arrow(xy=cbind(i,2), cex=1.5, type=i, col=rainbow(7)[i])
}
```

![arrows](https://user-images.githubusercontent.com/11481397/147863898-71dc8c2a-48e6-4533-ad75-358373663d52.png)

They may come out strange in particular situations, especially the alignment of the arrow and the label (default = "N"). Please let me know if you encounter a bad case; but you can suppress the label and then use `text()` to do that manually if need be.  

`type=1` should always work. The others may depend on the presence of a particular font on your computer.

**Comment by AMBarbosa** [comment]
Awesome, thanks so much!

**Comment by ashokkrish** [comment]
I am getting a warning 

`Warning: [arrow] "arrow" will be removed. It has been renamed to "north"`. 

Can I replace the `arrow()` wherever it appears to `north()`?

**Comment by rhijmans** [comment]
Yes. The reason for this name change is to avoid confusion with ggplot2::arrow
