### ISSUE TITLE
missing 'direction' function

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#462]
Hi, is there a plan to include the 'terra' equivalent of the 'raster' `direction` function? It is mentioned here https://rspatial.org/terra/pkg/5-methods.html#distance, but I can't find it in the package (version 1.5-8). Cheers!

**Comment by rhijmans** [comment]
Thanks, that was the last one on the list to take from raster to terra (there might be more others that escaped my attention). And I will comb through rspatial/terra to make sure it actually matches terra.
