### ISSUE TITLE
'distance' type for projected vs. unprojected points

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#465]
Calculating a matrix of distances for an unprojected points map of world cities, I get the same result with `as.matrix(distance(cities))` as with `geosphere::distm(as(cities, "Spatial"), fun = distGeo)` (and also with `fun = distVincentyEllipsoid`, though this one takes visibly longer to compute). This is a good thing of course, and I think it would be worth to mention it more clearly in `?distance` (under "_If x is a SpatVector: If y is missing_"), as many users (including myself previously) are under the impression that distances are generally Euclidean by default. Also, it would be useful to state (as is done in `?expanse` and `?perim`) whether results are more/less accurate for projected or for unprojected maps: I get a mean relative difference of 0.1537776 if I instead run `as.matrix(distance(project(cities, "+proj=aeqd")))`. Cheers!
PS: I know the title of the function is "Geographic distance", which should be obvious enough... but for the layperson it isn't ;)

**Comment by rhijmans** [comment]
Thanks very much, very helpful.
