### ISSUE TITLE
patches( ) in terra 1.5-6 fails with "Error in x@ptr$patches(directions[1], zeroAsNA[1], opt) : std::bad_alloc" for directions=8

### ISSUE THREAD

**Issue by hirscht** [rspatial/terra#466]
I´m using terra1.5-6 development version to test the fixes in patches( ) and centroids( ) for the dateline problem described in: https://github.com/rspatial/terra/issues/366

The fixes work just fine for the most part of my dataset but interestingly, there are some data fields, where patches( ) now fails with the error message: "**Error in x@ptr$patches(directions[1], zeroAsNA[1], opt) : std::bad_alloc**"  When it fails, patches( ) seems to struggle for some time with the memory used going up from about 50% to about 95% and finally it comes to "std::bad_alloc".
As said, this occurs only for some data fields and also, not always even for these fields. When I applied patches( ) for a given data field, I got the following:

```
patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=8, zeroAsNA=TRUE)
#class       : SpatRaster 
#dimensions  : 361, 720, 1  (nrow, ncol, nlyr)
#resolution  : 0.5, 0.498615  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        :       patches 
#min value   : 2.052269e-289 
#max value   :            10 

patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=8, zeroAsNA=TRUE)
#**_Error in x@ptr$patches(directions[1], zeroAsNA[1], opt) : std::bad_alloc_**

patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=8, zeroAsNA=TRUE)
#**_Error in x@ptr$patches(directions[1], zeroAsNA[1], opt) : std::bad_alloc_**

patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=8, zeroAsNA=TRUE)
#**_Error in x@ptr$patches(directions[1], zeroAsNA[1], opt) : std::bad_alloc_**
```
First, patches( ) was running with no error. However, calling it for the same SpatRaster several times again, it was always giving the mentioned error. 
This never occurred in my large dataset with the release version terra 1.2-10 and the latest release version 1.4-22 doesn´t seem to show this error either. So this could be an issue due to the changes since the last release version. Maybe caused by the fixes for https://github.com/rspatial/terra/issues/366 or https://github.com/rspatial/terra/issues/451?

When I set directions to 4 instead of 8 in the argument of patches, I don´t seem to have the error with terra 1.5-6 either (still needs to be tested on more cases). For the same data field, which caused the problem with directions=8, I get the following with directions set to 4:

```
patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=4, zeroAsNA=TRUE)
#class       : SpatRaster 
#dimensions  : 361, 720, 1  (nrow, ncol, nlyr)
#resolution  : 0.5, 0.498615  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : patches 
#min value   :       1 
#max value   :      12 

patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=4, zeroAsNA=TRUE)
#class       : SpatRaster 
#dimensions  : 361, 720, 1  (nrow, ncol, nlyr)
#resolution  : 0.5, 0.498615  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : patches 
#min value   :       1 
#max value   :      12 

patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=4, zeroAsNA=TRUE)
#class       : SpatRaster 
#dimensions  : 361, 720, 1  (nrow, ncol, nlyr)
#resolution  : 0.5, 0.498615  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : patches 
#min value   :       1 
#max value   :      12 

patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=4, zeroAsNA=TRUE)
#class       : SpatRaster 
#dimensions  : 361, 720, 1  (nrow, ncol, nlyr)
#resolution  : 0.5, 0.498615  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : patches 
#min value   :       1 
#max value   :      12 

patches(matrix_to_sprast(stabmapSL[,,s,pn]), directions=4, zeroAsNA=TRUE)
#class       : SpatRaster 
#dimensions  : 361, 720, 1  (nrow, ncol, nlyr)
#resolution  : 0.5, 0.498615  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : patches 
#min value   :       1 
#max value   :      12 
```

**Comment by rhijmans** [comment]
Thank you. I believe this has now been fixed. Can you please check? If the problem persists, can you then you please share the values of `matrix_to_sprast(stabmapSL[,,s,pn]`, either here or via email?
