### ISSUE TITLE
Numerical legend in incorrect order

### ISSUE THREAD

**Issue by jdoody1** [rspatial/terra#469]
I've been using `terra` to produce geospatial plots in `R`, and the `master` branch seems to have changed the way the legends are produced. When using `terra_1.4-22` to produce plots, I get the following output (note the legend is in numerical order):
![image](https://user-images.githubusercontent.com/70544686/148464275-4c2bdc14-0aae-47ee-9b7d-1df7edff82b7.png)
...and then when using `terra` built from `master`, I get the following plot (note the legend is in lexicographic order):
![image](https://user-images.githubusercontent.com/70544686/148472348-af99e4a3-d44e-4885-9d88-6a20491b18ff.png)
Is this a bug, or an intended change in the way `terra` handles legends? I can create some minimal source code later if need be; our source code is just a little complicated right now so it's a bit of a hassle to create a self-contained example. The only difference between those two images was updating the `terra` package and nothing else.

**Comment by rhijmans** [comment]
Thank you. That is an unintended consequence of (by default) sorting the legend for categorical variables. That works fine, I think for, e.g. land cover names. But not for categories that we read as numbers and should be in numeric order. I reproduce it here, showing that you can use `sort=FALSE`.  I need to think about the best way to avoid the need for that.

```
library(terra)
r <- rast(ncols=10, nrows=10, xmin=0)
values(r) <- (0:99)/99
rc <- classify(r, c(0, 0.25, 0.5, 1), include.lowest=TRUE, brackets=TRUE)
par(mfrow=c(1,2))
plot(rc)
plot(rc, sort=FALSE)
```

![sort](https://user-images.githubusercontent.com/11481397/148474566-2db83762-3099-4a5e-97a9-5b4a917494c2.png)

**Comment by rhijmans** [comment]
(completely unrelated, but for these maps you might do `plot(x,   legend="topright", mar=c(1.5, 1.5, 1.5, 1.5))` )

**Comment by rhijmans** [comment]
The default is now `sort=FALSE` and the argument is now documented.

**Comment by rhijmans** [comment]
The other difference is the presence of brackets to show whether an interval is open or closed. That is optional:

```
library(terra)
r <- rast(ncols=10, nrows=10, xmin=0)
values(r) <- (0:99)/99
rc1 <- classify(r, c(0, 0.25, 0.5, 1), include.lowest=TRUE, brackets=TRUE)
rc2 <- classify(r, c(0, 0.25, 0.5, 1), include.lowest=TRUE, brackets=FALSE)
par(mfrow=c(1,2))
plot(rc1)
plot(rc2)
```

![brackets](https://user-images.githubusercontent.com/11481397/148476310-9c420765-058c-4afa-a3b0-81cc955de754.png)
