### ISSUE TITLE
Consider implementing bilinear extraction using polygons?

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#47]
This extraction method would be equivalent to converting the polygon to many points spread out randomly within the polygon then running bilinear extraction using those points and averaging. 

I can draw a picture if that would help.

**Comment by rhijmans** [comment]
Hi --- sorry that I never even replied to this. I am trying to catch up with some of the older open issues. Can you provide a bit more context. I think I am missing the point of what you propose. I think I understand the idea of random points and then using extract; but why would you do that? It matters in the sense that if this is very obscure you can do it in two steps (spatSample, extract) and it would perhaps not merit its own method?

**Comment by kendonB** [comment]
This would be the method one would use when:

1) The underlying raster data are point data for the centroids of the cells.

2) The user is happy to assume that bilinear interpolation is appropriate for any given point in space.

3) The user want the average across space of these point interpolations.

A real-life example where this would apply is when aggregating raster weather data products to polygons, especially when the polygons are small relative to the weather grid cells.

The raster weather data are point estimates for weather at the centroids of each cell, bilinear interpolation is probably the best one can do for estimates of weather at any other point, and the user is after an average across space.

In math, this is just a 2d integral:

\int_{A} f(x, y) dA

Where A is the polygon and f is the bilinear interpolation function.
