### ISSUE TITLE
Stratified sampling via spatSample on SpatRaster s?

### ISSUE THREAD

**Issue by mikemahoney218** [rspatial/terra#470]
Apologies if this is already possible and I just missed it, I'm just starting to migrate new code to {terra} so don't entirely have my feet under me.

I notice that `spatSample` has an argument `strata` for `SpatVector` objects, but no such argument for `SpatRaster`. Is there an equivalent to `raster::sampleStratified` in `terra` for `SpatRaster` objects?

As part of trying to find a solution, I also noticed a few small documentation bugs in `spatSample`:

* `x` is documented as `SpatRaster` when there are also `SpatVector` and `SpatExtent` methods
* `Value` is documented as `numeric or SpatRaster` when I believe it may be a `SpatRaster`, `data.frame`, numeric matrix, or `SpatVector`

Thanks for the package -- I'm already seeing incredible performance benefits from switching over.

**Comment by rhijmans** [comment]
Thanks, I had overlooked that; and also for the helpful reporting of documentation  errors.

You can now do:

```

library(terra)
rr <- rast(ncol=10, nrow=10, xmin=0, names="stratum")
set.seed(1)
values(rr) <- round(runif(ncell(rr), 1, 3))
s <- spatSample(rr, 5, "stratified", as.points=TRUE)
plot(rr, plg=list(title="raster"))
plot(s, "stratum", add=TRUE, plg=list(x=185, y=1, title="points"))
```

![stratified](https://user-images.githubusercontent.com/11481397/148628393-e293b1c6-73e7-4f98-b801-5824e2006b09.png)

**Comment by ejeronimus** [comment]
Is there a way to create random stratified points for a SpatRaster object?
