### ISSUE TITLE
Missing codec for ZSTD (GDAL error 1) by writeRaster in a GeoTiff Format with ZSTD compress 

### ISSUE THREAD

**Issue by Hallo951** [rspatial/terra#473]
Hello,

I have a problem with saving raster files in GeoTiff format with compression "ZSTD". The error message is the following:

```
Error: [writeRaster] failed writing GTiff file
In addition: Warning message: Cannot create TIFF file due to missing codec for ZSTD. (GDAL error 1)
```

I installed the latest Terra version using "remotes::install_github("rspatial/terra")" and after the gdal() function it is up to date. The raster storage with another compression works without problems but not with the ZSTD compression.

According to the error report the driver or the library for the ZSTD compression is missing.  How can I fix this error?

 Here is a minimal example:

```
remotes::install_github("rspatial/terra")

gdal()
# gdal    proj    geos
# "3.2.1" "7.2.1" "3.9.1"

test_raster <- rast(ncol = 10000,
                    nrow = 10000,
                    xmin = 0,
                    xmax = 100,
                    ymin = 0,
                    ymax = 100)

setwd("path")

# Write out to geotiff format
terra::writeRaster(x = test_raster,
                     filename = "test.tif",
                     gdal=c("COMPRESS=ZSTD",
                                  "PREDICTOR=3"
                                  "ZLEVEL=9",
                                  "TFW=NO",  
                                  "NUM_THREADS=ALL_CPUS",
                                  "of=COG"),
                     datatype='FLT4S',
                     progress=T,
                     overwrite=T)

# Error: [writeRaster] failed writing GTiff file
# In addition: Warning message: Cannot create TIFF file due to missing codec for ZSTD. (GDAL error 1)
```

**Comment by rhijmans** [comment]
That is a matter of the GDAL library and how it was build to provide support for GeoTiff (see [here](https://gdal.org/drivers/raster/gtiff.html) and [here](https://gis.stackexchange.com/questions/357801/zstd-support-for-gdal-geotiffs-with-ubuntugis). So it depends on your GDAL installation.

It is supported by the current ubuntugis-unstable packages

```
sessionInfo()$running
#[1] "Ubuntu 20.04.3 LTS"

library(terra)
#terra 1.5.9
gdal()
#    gdal     proj     geos
# "3.4.0"  "8.2.0" "3.10.1"

r <- rast()
values(r) = runif(ncell(r))
x <- writeRaster(r, "test.tif", overwrite=TRUE, gdal=c("COMPRESS=ZSTD", "PREDICTOR=3", "ZLEVEL=3"))

describe("test.tif")[24:27]
#[1] "Image Structure Metadata:" "  COMPRESSION=ZSTD"
#[3] "  INTERLEAVE=BAND"         "  PREDICTOR=3"

```

**Comment by rhijmans** [comment]
It now see that it also works on windows with R-devel  / UCRT,  with RTools42. This is the development version that will become R 4.2.0: 

```
library(terra)
#terra 1.5.9
gdal()
#   gdal    proj    geos 
#"3.3.2" "7.2.1" "3.9.1" 
r <- rast()
values(r) = runif(ncell(r))
x <- writeRaster(r, "test.tif", overwrite=TRUE, gdal=c("COMPRESS=ZSTD", "PREDICTOR=3", "ZLEVEL=3"))

> describe("test.tif")[24:27]
#[1] "Image Structure Metadata:" "  COMPRESSION=ZSTD"       
#[3] "  INTERLEAVE=BAND"         "  PREDICTOR=3"   

sessionInfo()
#R Under development (unstable) (2022-01-07 r81458 ucrt)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows 10 x64 (build 19043)
```

**Comment by Hallo951** [comment]
Thanks for your message. Does this mean that I only have to update my R to the R-devel / UCRT version and additionally install RTools42 and then the whole thing runs with Windows?

Does the update of R and RTools cause problems with all the other packages or do they all run normally?

What about using the ZSTD compressed tiff files on older R systems (e.g. the current stable R version)? Can I read in the created tiff files as raster with this R version and process them further or is the corresponding driver missing there as well? I ask because I will use the tiff files afterwards on computers with only stable R versions on which I have no administrator rights?

Translated with www.DeepL.com/Translator (free version)

**Comment by rhijmans** [comment]
> Does the update of R and RTools cause problems with all the other packages or do they all run normally?

In my experience they all run normally

> What about using the ZSTD compressed tiff files on older R systems (e.g. the current stable R version)? 

You will **not** be able to read them.
