### ISSUE TITLE
stretch argument stopped working correctly

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#475]
Dear @rhijmans -- `stretch = "lin"` worked fine a few months ago in the example below, but now I got a black image:

``` r
library(terra)
#> terra version1.5.4
raster_filepath2 = system.file("raster/landsat.tif", package = "spDataLarge")
new_raster2 = rast(raster_filepath2)

plotRGB(new_raster2, r = 3, g = 2, b = 1)
```

![](https://i.imgur.com/PsV8u7s.png)

``` r
plotRGB(new_raster2, r = 3, g = 2, b = 1, stretch = "lin")
```

![](https://i.imgur.com/VkqEziv.png)

``` r
plotRGB(new_raster2, r = 3, g = 2, b = 1, stretch = "hist")
```

![](https://i.imgur.com/cLbtxyh.png)

<sup>Created on 2022-01-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thanks very much. I changed the code to make it more generic and perhaps faster by using `terra::stretch` rather then stretch functions just used by `plotRGB`; but I only tested it with the example file that has values between 0 and 255
