### ISSUE TITLE
grid distance with cells that cannot be traversed

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#477]
It would be useful to add an example with `grid=TRUE` to the `distance` help file, showing how it works and specifying how the traversable and non-traversable cells can be defined. In `raster::gridDistance`, we had the 'origin' and 'omit' arguments; the latter was important (e.g. to enable computing distance for fish within a lake, avoiding land pixels) and I don't see how to set that with `terra::distance`. And if I just use `grid=TRUE` with all else default, I get zero distance in all pixels:
```
r <- rast(ncols=36, nrows=18)
r[500] <- 1
d <- distance(r, grid=TRUE)
```
![image](https://user-images.githubusercontent.com/12085508/148794240-486d3259-c4c0-4660-a9b4-95b988929c1e.png)

**Comment by rhijmans** [comment]
Thanks very much. It worked for rasters with a planar crs, but if it was lonlat, all values were multiplied with zero. This has now been fixed. I have also added support for global lonlat rasters.

I am closing this issue as the bug has been solved However, I agree that `omit=`  is important. I think of it as a special case of cost-distance (where, in this binary case, certain cells have Infinite cost). cost-distance is on my to-do list (but feel free to open another issue for that).

**Comment by rhijmans** [comment]
I now notice that the results are the same between terra and raster for planar data, but not for lon/lat data. The difference is big enough to worry about, and so far raster looks correct.

**Comment by AMBarbosa** [comment]
Many thanks for the heads up! Actually my only use of grid distance so far has been for situations like the one I mentioned where there are non-traversable (NA) cells, so I'll just hold the migration from `raster::gridDistance` until `terra` includes a similar possibility. And thanks again for your relentless work on this amazing package!

**Comment by rhijmans** [comment]
I have added `gridDistance`; for now simply by using the raster code adapted for terra. 
And thank you for all your help.

**Comment by hugh-allan** [comment]
Hey Robert, it looks like `gridDistance` in `terra 1.5-34` has changed a bit and doesn't include `omit` and `origin` any more. According to `?terra::gridDistance`, we should "see `terra:::.oldGridDistance` for the previous version of this method (will be removed in a future version)", but I can't seem to find that either. 

Is there a current way to calculate distance from an origin without traversing certain cells?

**Comment by rhijmans** [comment]
The cells that are `NA` are omitted. All other cells are `origin` except if they are `target`.
