### ISSUE TITLE
Potential clipping and tiling issue with focalCpp for large rasters on Linux

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#479]
I believe there may be an issue occurring in `terra::focalCpp` for data too large to fit in memory (potentially specific to Linux systems). While I get the correct result on a Windows computer with 16GB of RAM and another user is getting correct results on a Linux computer with 128GB of RAM, their Linux computer with 16 GB of RAM is providing clipped/offset/striped outputs from the call to `focalCpp` and on an Ubuntu VM with ~10GB of RAM I'm getting clipped/offset results on two different functions that use `focalCpp` internally. When I overlay the original data with a single layer of the output you can see the two do not match up. Additionally, on Windows `focalCpp` for the second example results in a memory exhausted error. For more details see ailich/GLCMTextures#12. The data set is available [here](https://drive.google.com/file/d/1qn0OK_tL0MTT4nJ0CTq-oKYIKeQO0OCC/view?usp=sharing) .

# GLCMTextures Example
Using the function `glcm_textures` from the `GLCMTextures` package.

Overlay of the original data and a single layer of intermediate surface calculated with `focalCpp` plotted from debug mode on 10GB Linux VM
![r_overlay](https://user-images.githubusercontent.com/28163862/148831218-355add57-0e91-4931-b082-3aa8b24238e3.png)

Intermediate surface calculated with `focalCpp` plotted from debug mode on 16GB Linux Computer
![148659660-999fec9b-aa38-4f32-9a74-21bab4ca8a99](https://user-images.githubusercontent.com/28163862/148831705-c40da330-78f6-4327-9278-2a88030f9101.png)

Surfaces from a 16GB Windows Computer (correct)
 ![148409431-4df258c9-6318-496d-bd42-32504114b280](https://user-images.githubusercontent.com/28163862/148831889-1834617e-ace3-46b2-8a03-95b13c501709.png)

# MultiscaleDEM Examples
Using the function `Qfit` from the `MultiscaleDEM` package

Overlay of a single layer of the output onto the original data from the 10GB Linux VM
![qfit_overlay](https://user-images.githubusercontent.com/28163862/148833100-e3777829-a7bb-49e9-88e7-cf819053a65f.png)

Windows 16GB Computer
Error: memory exhausted (limit reached?)

**Comment by rhijmans** [comment]
Closing because this is the same as #519  (fixed but awaiting confirmation)
