### ISSUE TITLE
Consider adding bilinear option to `disaggregate`

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#48]
Rather than the disaggregated raster having the same value as the parent raster it would have values interpolated using the "bilinear" method.

**Comment by rhijmans** [comment]
Fair enough, but note that you can already do that with resample.  So I am not sure if I should implement this as a one-step option too.

```
library(terra)
x <- rast(nrow=10, ncol=10, xmin=0, xmax=10, ymin=0, ymax=10)
values(x) = 1:100
d <- disaggregate(rast(x), 10)
r <- resample(x, d, method="bilinear")
plot(r)
```

**Comment by kendonB** [comment]
given that there is already a way to do it, implementing this as a one-step option is low benefit, but also very low cost looks like

**Comment by rhijmans** [comment]
Yes, low cost, so implemented. Thank you for suggesting.
