### ISSUE TITLE
plot() ext arg not working

### ISSUE THREAD

**Issue by dncarpenter** [rspatial/terra#482]
Just installed `terra` 1.5.11 and the `ext` argument of `plot()` does not appear to be working:
```
library(terra)
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
par(mfrow=c(1,2))
plot(r)
e <- c(5.9, 6.4, 49.4, 49.7)
plot(r, ext=e)

```
![image](https://user-images.githubusercontent.com/14809525/148969971-8fc7c443-1c57-4d93-9e3f-7660acc9f737.png)
Same plot created w/ or w/o `ext=e`
By contrast, with `raster` (and the current CRAN release of `terra` 1.4.22):
```
r2 <- raster::raster(r)
raster::plot(r2)
raster::plot(r2, ext=e)
```
![image](https://user-images.githubusercontent.com/14809525/148970256-5b74e61f-b843-4a39-9dd9-715f7d2b88ca.png)
`ext` creates a zoomed in plot as expected.

**Comment by rhijmans** [comment]
Thanks, I made `ext` a formal argument so that it appears in the documentation; but that broke it. All good now, I think.
