### ISSUE TITLE
warning: multiple methods tables found

### ISSUE THREAD

**Issue by dholstius** [rspatial/terra#485]
## Summary

Loading a package that lists both `terra` and `raster` in the `Imports:` section of the `DESCRIPTION` results in two warnings:

```r
1: multiple methods tables found for ‘direction’ 
2: multiple methods tables found for ‘gridDistance’ 
```

Not sure with whom this is appropriately filed: `raster` devs, `terra` devs, or both?

## Notes

- `direction()` is defined by both the `raster` and `terra` packages 
- `gridDirection()` is defined by both the `raster` and `terra` packages 

## Reprex

Minimal package `libfail` hosted at https://github.com/dholstius/libfail. (Only the `DESCRIPTION` is of interest.)

## Related

- https://github.com/isciences/exactextractr/issues/67

**Comment by dholstius** [comment]
Update: [this looks like it's purely an issue with the `raster` package](https://github.com/isciences/exactextractr/issues/67#issuecomment-1012462104). Closing.

**Comment by rhijmans** [comment]
These messages go away if you (re-) install `raster` *after* installing `terra`. 

The reason is that the new version of terra exports these methods (that `raster` already had).
