### ISSUE TITLE
help page of terraOptions not agree with terraOptions()

### ISSUE THREAD

**Issue by jszhao** [rspatial/terra#486]
Hi,

I have updated `terra` to `1.5.12`, and I notice that the help page of `terraOptions` gives:
```
     memmax - the maximum amount of RAM (in GB) that terra can use when
     processing a raster dataset. Should be less than what is detected
     (see ‘link{mem_info}’, and higher values are ignored. Set it to a
     negative number or NA to ignore this value).
```
which is the option that added recently, and I knew it from #476 

However, the output of `terraOptions()` does not include it:
```
> terraOptions()
memfrac   : 0.6
tempdir   : /tmp/RtmpgXqS0O
datatype  : FLT4S
progress  : 3
todisk    : FALSE
verbose   : FALSE
tolerance : 0.1
```
And the option `tolerance` is not mentioned in the help page in the `1.5.12` version, and also not in the `1.4.22` version.

**Comment by jszhao** [comment]
I just notice that when `memmax` is set to `NA` then it is dropped from `terraOptions()`.

**Comment by rhijmans** [comment]
Thanks, indeed `memmax`  is only shown if it is set. The manual now says that. 
I do not consider `tolerance` as a session option.
