### ISSUE TITLE
Is terra version 1.5 incompatible with PROJ 8.1? 

### ISSUE THREAD

**Issue by gilbertocamara** [rspatial/terra#488]
Dear Rob, 
I have installed the latest version of PROJ (8.1) and failed to install terra version 1.5-12 from source on Mac OS. The problem appears in the terra installation script. The script fails when trying to test access to the "proj.db" database. The script expects that the "geodetic_crs" table contains a column named "area_of_use_auth_name". This column has been removed in the PROJ 8.1 version. 

```{r}
checking GDAL: checking whether PROJ is available fur running:... 

ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: 

no such column: area_of_use_auth_name
```

What happens is that the "proj.db" database distributed together with PROJ 8.1 does not include the column "area_of_use_auth_name" in the "geodetic_crs" table, as follows:

```{r}
library(RSQLite)
proj <- dbConnect(RSQLite::SQLite(), "/usr/local/share/proj/proj.db")
dbGetQuery(proj, "SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs")

Error: no such column: area_of_use_auth_name
```
Is there a way to fix this problem?

**Comment by rhijmans** [comment]
Hi Gilberto, 

I do not think there is an incompatibility with `PROJ 8`, as I see this on Ubuntu

```
library(terra)
#terra 1.5.12
gdal(lib="all")
#    gdal     proj     geos
# "3.4.0"  "8.2.0" "3.10.1"
```
Although this is `8.2`, not `8.1`.

Are you able to install `sf` and `rgdal` (and if so, how). If you can, then it would specific to `terra` and it should be possible to fix that. If you cannot it is probably because you have multiple installations of PROJ (and GDAL, or an incompatible GDAL (?)). It seems that that is the most common cause of installation troubles.

**Comment by gilbertocamara** [comment]
Hi Rob, 

Indeed, I am able to install sf and GDAL. As I said, the problem appears when trying to install `terra` from the source code. Could you please check if your installation script includes the following call to RSQLite

```
SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs 
```
This is the source of the problem. The `area_of_use_auth_name` does not exist in `proj.db` as of version 8.1.

**Comment by rhijmans** [comment]
Sorry, my question is whether you can you install sf and gdal from source code, not from CRAN.

**Comment by rhijmans** [comment]
But to answer your question. The does not do that SQL query. What happens at that step is that the program below is compiled and run: 

```
#include <gdal.h>
#include <ogr_srs_api.h>
#include <ogr_spatialref.h>
int main(int argc, char *argv[]) {
	OGRSpatialReference *dest = new OGRSpatialReference;
	OGRSpatialReference *src = new OGRSpatialReference;
    src->importFromEPSG(4326);
    dest->importFromEPSG(3857);
	OGRCoordinateTransformation *ct = OGRCreateCoordinateTransformation(src, dest);
	return(ct == NULL); // signals PROJ is not available through gdal
}
```

That should not give an error, but in your case it does, suggesting a faulty installation

**Comment by gilbertocamara** [comment]
You are correct, I also cannot install `sf` from source. However, I have installed PROJ and GDAL according to the `sf` specification. I must have done something wrong, but need to retrace my steps carefully. 
Meanwhile, I installed the binary MacOS version from CRAN.
```
terra::gdal(lib = "all")
gdal    proj    geos 
"3.4.0" "8.1.1" "3.9.1"
```
Thanks!
Gilberto
