### ISSUE TITLE
option to use a precomputed extraction_info object in extract?

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#49]
When extracting many-layer rasters (weather or satellite data), users may want to precompute the extraction indices to extract the data in chunks without repeating the expensive spatial intersection stage.

A nice way to do this might be to add a new class (e.g. `extraction_info`) and associated method for the y argument of `extract`. The `extraction_info` object would contain all the spatial intersection information (IDs + cell indices) and the user could then use the extraction_info object to directly extract from the raster without the intersection step being done.

The `extraction_info` object could be generated using a logical flag to `extract` or with another function like `get_extraction_info`.

`extract(x, y)` would be equivalent to `extract(x, get_extraction_info(x, y))`

**Comment by mdsumner** [comment]
I like this, I use my own tricks for caching cells against objects - the thing that troubles me is the lack of linkage between the extraction info object and the shape of the grid - but I suppose this object could ensure that `extent,crs,dim` were all aligned with the object being extracted from (though crs checking is a pain as ever and getting worse). 

 I've tried a lot of different things, including classed columns that know they are a raster-grid ... but always I've just used a data frame of object ID and cell number, in workflows where the linkage is controlled. 

fwiw if you want to explore there is `tabularaster::cellnumbers()` specifically designed to use fasterize for cell classification (terra is probably as fast now), and to abstract over query type.  The biggest problem with fasterize is a huge grid actually needs to be instantiated with data just to get out these cell numbers, so it'd be great to have a more core support for this and I would love to contribute.

**Comment by rhijmans** [comment]
How about adding a `cellnumbers=TRUE` argument to extract, as in `raster`?  

That could also return the object IDs and numbers for an empty SpatRaster (an object with no cell values).

Alternatively, that is what you get back when the SpatRaster has no values? That is, without using another argument. Perhaps that is cute, but too unexpected?

**Comment by kendonB** [comment]
For bilinear points extraction, you would also want to collect the weights, right?

`cellnumbers=TRUE` would be a fine solution. 

> Alternatively, that is what you get back when the SpatRaster has no values? That is, without using another argument. Perhaps that is cute, but too unexpected?

Are you saying this is what happens now? I think this would be a bit of a confusing interface but if it's well documented (including an example) I think that would be fine.

One thing I do like is the idea of using the output of this operation as the `y` argument of `extract`, rather than using a different function like e.g. `getValuesCell`.

**Comment by mdsumner** [comment]
oh right, that is a bit unexpected - I definitely like  the `cellnumbers = TRUE` approach if you can get the IDs as well in a data frame (or matrix). I think giving cell numbers when there's no values is a bit "special-case" and better to error. 

But, this is a great power of raster - what about having a `cellnumbers()` function to really highlight it? Always return a dataframe (or matrix), while extract returns values or list of values as before.    

I had also meant to ask, there's no `cellFromPolygon/Line/Extent` in terra, I wouldn't miss them though with a general type-agnostic approach with extract()/cellnumbers.

**Comment by rhijmans** [comment]
> Are you saying this is what happens now?
No, currently there is no such thing. 

> you would also want to collect the weights, right?
Yes, also for polygons to capture partially covered cells

As you say, tou can extract values by cell number:.

```
library(terra)
r <- rast(ncol=5, nrow=5, xmin=0, xmax=5, ymin=0, ymax=5)
values(r) <- 1:25
extract(r, 3:5)
#     lyr.1
#[1,]     3
#[2,]     4
#[3,]     5

# or like this
r[3:5]
#     lyr.1
#[1,]     3
#[2,]     4
#[3,]     5
```
or with a 2-column matrix of coordinates that now does some checking for the correct colnames (lat/lon, etc). 
 
```
exinfo <- cbind(ID=1:3, cell=3:5, weights=1)
extract(r, exinfo)
     ID lyr.1
[1,]  1    12
[2,]  2     8
[3,]  3     4
Warning message:
coordinate names not recognized. Expecting lon/lat, x/y, or easting/northing 
```
This fails 

```
exinfo <- cbind(ID=1:3, cell=3:5, weights=1)
extract(r, exinfo)
#Error in extract(r, exinfo) : 
#  extract expects a 2 column matrix of x and y coordinates 
``` 

So there are options:
1) just use the cellnumbers column (perhaps my preference); but then you would have to apply any weights yourself
2) create a class (overkill?)
3) check the number of columns (2 or 3) and colnames (could be; but I fear confusion)
4) another method extractCells (not so nice)
5) ...

I will start with implementing the cellnumbers option; and I am intrigued by the idea of a `cellnumbers` method; and certainly nicer than cellFrom*

**Comment by mdsumner** [comment]
For `extract()` I much prefer just the cells themselves. I think a class is overkill *if it doesn't also encode the raster extent and dimension* as a validity check. I don't see any problem with downstream handling of ID, values, weights - at that level there's nothing particularly "raster" about it so why not leverage existing tools.

**Comment by kendonB** [comment]
> For extract() I much prefer just the cells themselves. I think a class is overkill if it doesn't also encode the raster extent and dimension as a validity check. I don't see any problem with downstream handling of ID, values, weights - at that level there's nothing particularly "raster" about it so why not leverage existing tools.

I wouldn't underestimate the ability of users to mess stuff up without knowing it, so I think that a class with validity checks is a great idea.

On @rhijmans' option 1, if I'm understanding correctly, for bilinear extraction the user would have to apply the weights after calling `extract`, increasing the memory requirement potentially 4x? I think that preserving the post-intersection performance benefits for each type of `extract` should be a goal here so I would recommend option 2 or 3. I think that 3 is a fine option but a bit more error-prone than 2.

**Comment by rhijmans** [comment]
The `cells` method now does some of this. It does not do weights yet.

**Comment by mdsumner** [comment]
cool thanks @rhijmans !

I am exploring timings now, but one question while it's fresh: I assume that `cells(x, y)` does no data-specific work if x has no values in memory? I.e. this is all entirely about the grid-specification within `x` as it is for the cell functions in raster? 

Another aspect to this is that it means these cells could be then arranged by scan-line (or tile) for extraction, and the `extract(x, cell)` could handle that internally - whereas in raster (I think) you don't have any optimization for that afaik without doing block-aligned tasks explicitly. 

(I'm sure you've thought of this, it's something I'll explore).

**Comment by rhijmans** [comment]
You are right, `cells(x, y)` never reads cell values of `x`, whether from memory or disk. 

Right now, extraction by cell is as simple as it can be (loop over cells in the order that they appear). In raster I think there is some optimization (read duplicates only once, and by block). That should be improved in `terra`; but I am still mostly focused on getting things to work, rather than getting them to work fast.

**Comment by rhijmans** [comment]
I have closed this now that `cells` also works for points with `method="bilinear"`. In that case it returns the four nearest cells and their weights.
