### ISSUE TITLE
feature requests: values & patches

### ISSUE THREAD

**Issue by carbonmetrics** [rspatial/terra#490]
I have two feature requests:

1
Can `values` gain an argument to filter out NA and NaN?
E.g. code below produces a stream of NaN.
```
f=system.file("ex/elev.tif", package="terra")
r=rast(f)
values(r)
```

2
Can `patches` gain an argument to produce the patch _sizes_?
Currently _patches_ returns patch ID's, calculating the patch size and filtering is not straightforward (see https://gis.stackexchange.com/questions/421257/plot-filtered-patch-sizes-in-r-terra/421291#421291).

**Comment by kadyb** [comment]
> Can `values` gain an argument to filter out NA and NaN?
> E.g. code below produces a stream of NaN.

Why not to use `na.omit()` or `complete.cases()` in next step?

```r
val = values(r)

cs = complete.cases(val)
val2 = val[cs, ]
anyNA(val2)
#> [1] FALSE

val3 = na.omit(val)
anyNA(val3)
#> [1] FALSE
```

**Comment by carbonmetrics** [comment]
Indeed. Since you would almost never want to have a bunch of NA's you might as well add set the option to remove NAs as default in `values(r, na.rm=T)`.

**Comment by rhijmans** [comment]
Thanks for that. I have answered the stackexchange question and added the example to the `?patches`. 

`values` now has a new argument `na.rm=FALSE`.
