### ISSUE TITLE
NAs from 'extract' sometimes become -9.223372e+18 when added as new column to SpatVector

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#491]
This doesn't happen always, but under some circumstances, appending the results of 'extract' to the attribute table of a SpatVector turns NAs into a very low value. Here's an example where this happens:
```
elev <- geodata::elevation_global(res = 10, path = tempdir())
x <- c(33.086040, 40.646160, 143.250000, 151.910004, 45.180000, -7.534092)
y <- c(68.96355, 64.52067, 59.33000, -33.00000, 12.86116, 33.54441)
pts <- terra::vect(cbind(x, y))
extr <- terra::extract(elev, pts)
extr  # some NAs
pts$extr <- extr[,2]
pts$extr  # NAs are now -9.223372e+18
```
I also have examples where NAs also exist and this doesn't happen -- let me know if you need code for that too. Cheers!

**Comment by rhijmans** [comment]
I saw this on Ubuntu and OSX, but not on Windows (am I correct in assuming you did not use windows?). It happened because of variations between the range of values a "long int" can have on these platforms.

**Comment by AMBarbosa** [comment]
Yes, sorry, I forgot to mention I'm on Linux (Mint), and I had yet to try this with my old Windows laptop. All fixed now, thanks a lot!

**Comment by rhijmans** [comment]
Thanks, I was not asking you try it on different systems, but I wanted to confirm my understanding.
