### ISSUE TITLE
SpatRaster updated by reference

### ISSUE THREAD

**Issue by Jean-Romain** [rspatial/terra#493]
The behaviour of `SpatRaster` (an maybe `SpatVector`) does not matches classical rules of copy-on-modify semantic. I spotted that when one of my unit test started to fail so I'm wondering if it is a new bug introduced in the last update. The only package doing that is `data.table` and it has a special and explicit syntax to update by reference and everything is documented in depth. Consequently I think this is not a behaviour that should be observed in `terra`.

Regards

Minimal reproducible example with `terra 1.5-12`

``` r
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)

test <- function(input) {
  input[1] = 1000
  names(input) <- c("test")
  return(0)
}

r
#> class       : SpatRaster 
#> dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
#> resolution  : 0.008333333, 0.008333333  (x, y)
#> extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#> source      : elev.tif 
#> name        : elevation 
#> min value   :       141 
#> max value   :       547
test(r)
#> [1] 0
r
#> class       : SpatRaster 
#> dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
#> resolution  : 0.008333333, 0.008333333  (x, y)
#> extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#> source      : memory 
#> varname     : elev 
#> name        : test 
#> min value   :  141 
#> max value   : 1000
```

<sup>Created on 2022-01-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
The intention is to avoid this type of behavior but I had not considered the use of replacement functions inside a function. 
This has now been fixed for your example (but there are other cases, and I still need to look for these)

```
library(terra)
#terra 1.5.13
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
 
test <- function(input) {
   input[1] = 1000
   names(input) <- c("test")
   return(0)
 }
 
r
#class       : SpatRaster 
#dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : elev.tif 
#name        : elevation 
#min value   :       141 
#max value   :       547 
``` 

But this has a downside. Copying is probably rarely needed as in most cases names will be set to a *new* SpatRaster inside of the function. So one could argue that the default should be to not copy, as that is efficient and covers most cases. Inside a function you could use `r <- deepcopy(r)` first.

The current solution still leaves this case 
```
x <- r 
names(x) = "abc"
names(r)
[1] "abc"
```
That could be avoided by always making a copy on assignment, but provide a mechanism to avoid that. That would lead to few surprises, at the expense of efficiency.

**Comment by Jean-Romain** [comment]
I really think you should respect the R way of copying when modifying an object with more than one reference. I do agree it is inefficient in some circumstances but it is the how R works. The current behaviour lead to unexpected and inconstant behaviours that are difficult to debug especially for casual users. Your example is particularly problematic

```r
x <- r 
names(x) = "abc"
names(r)
[1] "abc"
```

First, `x <- r` followed by `x[y] <- ` is the way we are making copies in R.  Here you are breaking some fundamental R behaviour that everybody knows. Second with your fix this behaviour is now inconsistent because we must learn that `terra` does not respect the classical R mechanisms but we must also remember that inside a function it actually does. 

As a developer I'm able the use of `deepcopy()` and remember the special behaviour of `Spat*` objects because I know and I understand the underlying programming concept involved. I'll deal with it an fix my code no problem. But for the 99% of other users I thinks you should find a way for `Spat*` objects to behave like any other R objects. Or document it extensively with examples, vignettes and put safeguards.

**Comment by rhijmans** [comment]
I have opted for a "no surprises" copy-on-change approach as you suggested.  There may be performance penalties, but these can be solved by doing things in the right order, or by using explicit in-place replacement functions (there are a few now, all starting with `set.`)
