### ISSUE TITLE
saving to RDS does not work

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#50]
``` r
library(terra)
#> This is terra version 0.6.12 (alpha-release)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
saveRDS(v, "v.rds")
v <- readRDS("v.rds")
v
#> Error in x@ptr$extent(): external pointer is not valid
```

<sup>Created on 2020-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rhijmans** [comment]
That is correct. That cannot be done. What you can do is 

library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
saveRDS(pack(v), "p.rds")
p <- readRDS("p.rds")
x <- vect(p)

**Comment by kendonB** [comment]
documented here https://github.com/rspatial/terra/blob/master/man/pack.Rd

**Comment by pat-s** [comment]
When coercing to a class `pack` I get this error when saving a list of `SpatVector` objects with {drake} as a "target". 

Current workaround is to read with {sf} and then coerce within a function to `SpatVector` and continue.

**Comment by rhijmans** [comment]
I do not understand this comment. What is class `pack` (presumably `PackedSpatVector`), but what is `{drake}` or "target"? And what is "this error"? Can you provide an example?

**Comment by pat-s** [comment]
I assumed that there might be a class `pack` which might not be the case.

Anyhow, [{drake}](https://cran.r-project.org/web/packages/drake/index.html) is a make-DSL for R which serializes objects at some point into a cache directory.
This fails with the error above, even when "packing" the `SpatVector` beforehand.

I don't have an example at hand and reverted back to using {raster} for now, which works as expected.

**Comment by rCarto** [comment]
For future reference `pack()` has been renamed to `wrap()` since version 1.2-5. 
https://rspatial.github.io/terra/reference/wrap.html

**Comment by gferraz29** [comment]
> That is correct. That cannot be done. What you can do is
> 
> ```
> library(terra)
> f <- system.file("ex/lux.shp", package="terra")
> v <- vect(f)
> saveRDS(pack(v), "p.rds")
> p <- readRDS("p.rds")
> x <- vect(p)
> ```

Is it really necessary to use 'x <- vect(p)' after 'p<-readRDS("p.rds")'? I get a 'p' object that is aready a SpatVector, right after the readRDS command. (I did replace 'pack' with 'wrap', following comment here.)
