### ISSUE TITLE
issues with layer names from multilayer.tif

### ISSUE THREAD

**Issue by chrishaak** [rspatial/terra#500]
Hi,

First I want to say thanks for making terra; the speed improvements over raster are incredible.

I'm using terra::rast to read and combine several different multi-layer .tifs into a single stack (where the files themselves represent different years, and the layers are different weeks of the year, from 1-52).  The names of the tif files include their respective years (i.e., "XXXX_sst_2011.tif")

When I do this using raster::stack, the individual layer names that are created include the full name of the .tif file, as well as the layer number, which corresponds to the week of the year, so that every layer of the stack has a unique layer name (i.e., "XXXX_sst_2011.52") .  However, when I read/combine the same set of .tif files with terra::rast, the layer names that are generated are abbreviated, such that they drop the year information from the filename and show only the week (i.e., "XXXX_52"). Thus, I have the same exact layer names repeating several times throughout the stack (because it contains multiple years).

Is there any way to force terra::rast to name layers with the same convention as raster::stack (or at least not to drop the year information from the layer name?)?  

Thanks for your help!
Chris

**Comment by rhijmans** [comment]
Can you show me what you see, using code like this:

``` 
filenames
library(terra)
x <- rast(filenames)
names(x)
```

**Comment by chrishaak** [comment]
Hi Robert,

Thanks for the quick response; I've attached an HTML markdown of the above
- let me know if I can do anything else to help clarify.
C

**Comment by rhijmans** [comment]
That does not work. Can you copy and paste the relevant bit into a text box on the website?

**Comment by chrishaak** [comment]
Certainly - see below:

`filenames`

#  [1] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_00.tif"
##  [2] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_01.tif"
##  [3] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_02.tif"
##  [4] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_03.tif"
##  [5] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_04.tif"
##  [6] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_05.tif"
##  [7] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_06.tif"
##  [8] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_07.tif"
##  [9] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_08.tif"
## [10] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_09.tif"
## [11] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_10.tif"
## [12] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_11.tif"
## [13] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_12.tif"
## [14] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_13.tif"
## [15] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_14.tif"
## [16] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_15.tif"
## [17] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_16.tif"
## [18] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_17.tif"
## [19] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_18.tif"
## [20] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_19.tif"
## [21] "SST_FRONTS/sst_metrics_rbricks/fprob/b_ww_fprob_sst_20.tif"

`library(terra)`

## terra version 1.4.22

```
`x<-terra::rast(filenames)`
names(x)
```
##    [1] "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8" 
##    [9] "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16"
##   [17] "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24"
##   [25] "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32"
##   [33] "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40"
##   [41] "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_1"  "b_w_2"  "b_w_3" 
##   [49] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##   [57] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##   [65] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##   [73] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##   [81] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##   [89] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##   [97] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [105] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [113] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [121] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [129] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [137] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [145] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [153] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [161] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [169] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [177] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [185] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [193] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [201] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [209] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [217] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [225] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [233] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [241] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [249] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [257] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [265] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [273] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [281] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [289] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [297] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [305] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [313] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [321] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [329] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [337] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [345] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [353] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [361] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [369] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [377] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [385] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [393] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [401] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [409] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [417] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [425] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [433] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [441] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [449] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [457] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [465] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [473] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [481] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [489] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [497] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [505] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [513] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [521] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [529] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [537] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [545] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [553] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [561] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [569] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [577] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [585] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [593] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [601] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [609] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [617] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [625] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [633] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [641] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [649] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [657] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [665] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [673] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [681] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [689] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [697] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [705] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [713] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [721] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [729] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [737] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [745] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [753] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [761] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [769] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [777] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [785] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [793] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [801] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [809] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [817] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [825] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [833] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [841] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [849] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [857] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [865] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [873] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [881] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [889] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
##  [897] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
##  [905] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
##  [913] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
##  [921] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
##  [929] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
##  [937] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
##  [945] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
##  [953] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
##  [961] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
##  [969] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
##  [977] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52" "b_w_1"  "b_w_2"  "b_w_3" 
##  [985] "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7"  "b_w_8"  "b_w_9"  "b_w_10" "b_w_11"
##  [993] "b_w_12" "b_w_13" "b_w_14" "b_w_15" "b_w_16" "b_w_17" "b_w_18" "b_w_19"
## [1001] "b_w_20" "b_w_21" "b_w_22" "b_w_23" "b_w_24" "b_w_25" "b_w_26" "b_w_27"
## [1009] "b_w_28" "b_w_29" "b_w_30" "b_w_31" "b_w_32" "b_w_33" "b_w_34" "b_w_35"
## [1017] "b_w_36" "b_w_37" "b_w_38" "b_w_39" "b_w_40" "b_w_41" "b_w_42" "b_w_43"
## [1025] "b_w_44" "b_w_45" "b_w_46" "b_w_47" "b_w_48" "b_w_49" "b_w_50" "b_w_51"
## [1033] "b_w_52" "b_w_1"  "b_w_2"  "b_w_3"  "b_w_4"  "b_w_5"  "b_w_6"  "b_w_7" 
## [1041] "b_w_8"  "b_w_9"  "b_w_10" "b_w_11" "b_w_12" "b_w_13" "b_w_14" "b_w_15"
## [1049] "b_w_16" "b_w_17" "b_w_18" "b_w_19" "b_w_20" "b_w_21" "b_w_22" "b_w_23"
## [1057] "b_w_24" "b_w_25" "b_w_26" "b_w_27" "b_w_28" "b_w_29" "b_w_30" "b_w_31"
## [1065] "b_w_32" "b_w_33" "b_w_34" "b_w_35" "b_w_36" "b_w_37" "b_w_38" "b_w_39"
## [1073] "b_w_40" "b_w_41" "b_w_42" "b_w_43" "b_w_44" "b_w_45" "b_w_46" "b_w_47"
## [1081] "b_w_48" "b_w_49" "b_w_50" "b_w_51" "b_w_52"

**Comment by rhijmans** [comment]
Thanks, I did not see that with the example I created, but now I know where to look.

**Comment by chrishaak** [comment]
anytime - thank you!  I don't know if it's relevant but I'm using R 4.1.2 on ubuntu 20.04....

**Comment by rhijmans** [comment]
I still cannot reproduce this or find where this would happen. One reason could be that these names are actually stored in the file, but then `raster::brick(filename)` or `raster::stack(filename)`  should also show them.  Can you send me one of these files (e.g. share a link via email or point me to their source)?

**Comment by chrishaak** [comment]
Huh - weird.  Maybe there's something wonky about my files.  Here's a link
to a couple of files:

https://drive.google.com/drive/folders/1xi7OK5KrisRiYYa2AeuULBu1wSV-Z0Er?usp=sharing

**Comment by rhijmans** [comment]
This is what I see:

```
library(terra)
#terra 1.5.13
f0 <- "b_ww_fprob_sst_00.tif"
f1 <- "b_ww_fprob_sst_01.tif"
rast(c(f0, f1)) |> names() |> head(15)
# [1] "b_ww_fprob_sst_00_1"  "b_ww_fprob_sst_00_2"  "b_ww_fprob_sst_00_3"  "b_ww_fprob_sst_00_4"  "b_ww_fprob_sst_00_5" 
# [6] "b_ww_fprob_sst_00_6"  "b_ww_fprob_sst_00_7"  "b_ww_fprob_sst_00_8"  "b_ww_fprob_sst_00_9"  "b_ww_fprob_sst_00_10"
#[11] "b_ww_fprob_sst_00_11" "b_ww_fprob_sst_00_12" "b_ww_fprob_sst_00_13" "b_ww_fprob_sst_00_14" "b_ww_fprob_sst_00_15"
 
library(raster)
stack(f0, f1) |> names() |> head(15)
# [1] "b_ww_fprob_sst_00.1"  "b_ww_fprob_sst_00.2"  "b_ww_fprob_sst_00.3"  "b_ww_fprob_sst_00.4"  "b_ww_fprob_sst_00.5" 
# [6] "b_ww_fprob_sst_00.6"  "b_ww_fprob_sst_00.7"  "b_ww_fprob_sst_00.8"  "b_ww_fprob_sst_00.9"  "b_ww_fprob_sst_00.10"
#[11] "b_ww_fprob_sst_00.11" "b_ww_fprob_sst_00.12" "b_ww_fprob_sst_00.13" "b_ww_fprob_sst_00.14" "b_ww_fprob_sst_00.15"
```

So there is an underscore instead of a dot, but that is a stylistic difference. I do not recall changing this (at least not recently). Are you using an old version of `terra`?

**Comment by chrishaak** [comment]
Argh!  I was using 1.4.22 but updated to the latest version late last night
(to get the "gridDistance" function; as my earlier version didn't have it).

I just ran the code in the updated version, and it gives me the same output
that you have above;  so somewhere along the line you must have addressed
this (perhaps unknowingly).

Forgive me for sending you on a wild goose chase - my deepest apologies!

**Comment by rhijmans** [comment]
No worries, I am glad it has been resolved.
