### ISSUE TITLE
Crash from `setCats` followed by `crop`

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/terra#501]
Using a file from https://s3-us-west-2.amazonaws.com/mrlc/nlcd_2016_land_cover_l48_20210604.zip :

```
library(terra)
land.cover = rast("nlcd_2016_land_cover_l48_20210604.img")
# Drop color and histogram categories.
setCats(land.cover, 1, cats(land.cover)[[1]][,
    c("value", "NLCD Land Cover Class")])
# Crop.
land.cover = crop(land.cover, snap = "out",
    ext(c(952744, 2304888, 2086109, 2659552)))
```

The output is

```
terra 1.5.12
corrupted size vs. prev_size
```

I'm running R 4.0.4 on Ubuntu 20.04.

**Comment by rhijmans** [comment]
Thank you. The bug was in writing the color table. I believe this has now been fixed.

**Comment by Kodiologist** [comment]
I installed c35f4d99df75025704e5f8e3ba1f6c78c67fbbeb, and there's now a deprecation warning for `setCats`, but replacing it with `set.cats` works like a charm in both this example and my original code. Thanks a lot, my man.
