### ISSUE TITLE
app() cores > 1 taking time before going parallel

### ISSUE THREAD

**Issue by daniel-althoff** [rspatial/terra#502]
I was comparing the terra "app" against "ClusterR" and noticed a weird interaction for "app"

It seems that it was running part of the operations in the current session before going parallel, thus, taking longer to execute the function.

```
system.time({
   beginCluster(12)
     test <- clusterR(cpc_list_avg %>% raster::stack(), calc, args=list(calc_ascT))
     endCluster()
 })
user  system elapsed 
   2.32    0.76  229.81

system.time({
    test2 <- app(x = cpc_list_avg, fun = function(x, ff) {ff(x)}, cores = 12, ff = calc_ascT)
 })
...
(prints random messages from calc_ascT function, then becomes quiet)
...
 user  system elapsed 
  43.92    0.19  263.09 
```

The calc_ascT function has an optimization function which prints messages.
It is not supposed to print messages on the console when it goes parallel.. however, when using app(), it does print messages from the function for some time.. then stops.. and then I can see the CPU usage increasing because it is going parallel.
I just don't understand why it is running this function alone in the session before going parallel and just wasting time (user time: 43.92).

Can someone please help?

**Comment by rhijmans** [comment]
`app` first runs `fun` on a single row of data to test it, to find out what type of object it returns, how many values are returned per cell, does the output need to be transposed, ...   Here is the code: https://github.com/rspatial/terra/blob/fc18fd852db2334c5eb833a8d940be4b69ee3303/R/app.R#L48-L96 

I think I could make the test smaller (no need for an entire row). 

I could also imagine a rawer interface, where the responsibility resides with the user, as a separate method. That could be especially useful for use in other packages.

**Comment by daniel-althoff** [comment]
I see.

It can really be useful, but in the case of a large dataset, a single row can take a lot of time.
An optional argument for single-row test (T/F) would be great.

Thank you

**Comment by rhijmans** [comment]
I have reduced the checking to 13 cells (or fewer if `ncol()` is smaller.
