### ISSUE TITLE
gridDistance outputs only a single layer when applied to a stack...

### ISSUE THREAD

**Issue by chrishaak** [rspatial/terra#503]
As I've been working with terra I've found that the raster manipulation functions tend to be "smart" and recognize when a raster is multi-layer (i.e., a stack or brick) and correspondingly output objects with the same # of layers.  However when I apply gridDistance to an object with more than one layer, the output is always just a single layer.  

Interestingly, if I specify a certain layer via indexing (i.e., gridDistance(myraster[[3]]) then the output is based on the specified layer.   But if I apply it to the whole stack (i.e., gridDistance(myraster) then the output is based on just the first layer [[1]].

It would be nice to have its behavior be consistent with the other functions, applying to each layer of the stack and outputting a stack...

Thanks!

**Comment by rhijmans** [comment]
Thanks. This was the case for a few more methods (distance, direction, patches). These methods now process all layers.

**Comment by chrishaak** [comment]
Awesome - thanks!
