### ISSUE TITLE
crds replicates rows of SpatVector polygon?

### ISSUE THREAD

**Issue by MurrayEfford** [rspatial/terra#504]
I'm puzzled by the behaviour below - why should crds() replicate the coordinates of a simple polygon?
Murray

> v <- vect(matrix(c(0,1,0,0,0,1), ncol=2), type="polygons")
> v
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 1, 0  (geometries, attributes)
 extent      : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
 coord. ref. :  
> crds(v)
      x y
 [1,] 0 0
 [2,] 1 0
 [3,] 0 1
 [4,] 0 0
 [5,] 0 0
 [6,] 1 0
 [7,] 0 1
 [8,] 0 0
 [9,] 0 0
[10,] 1 0
[11,] 0 1
[12,] 0 0
[13,] 0 0
[14,] 1 0
[15,] 0 1
[16,] 0 0
> packageVersion('terra')
[1] ‘1.5.12’

**Comment by rhijmans** [comment]
Ouch. I now get:

```
crds(v)
#     x y
#[1,] 0 0
#[2,] 1 0
#[3,] 0 1
#[4,] 0 0
```

**Comment by MurrayEfford** [comment]
Thanks - I look forward to seeing 1.5-14 on CRAN!

**Comment by rhijmans** [comment]
My plan is to send it there a week from now.
