### ISSUE TITLE
as.polygons creates WGS84 by default

### ISSUE THREAD

**Issue by herryATcsiro** [rspatial/terra#506]
Hi there,
r=raster(ncol=100,nrow=100,extent(0,100,0,100))
values(r)<-runif(ncell(r))
p<-as.polygons(rast(r))
creates a wgs84 crs:
crs(p)
and as.polygons(rast(r), crs="") results in
Error in .local(x, ...) : unused argument (crs = "")
It would be helpful if the default crs was "" when creating polygons from a raster without crs. Also, maybe remove the crs entry from the as.polygons helpfile?
Cheers
Herry

**Comment by rhijmans** [comment]
Hi, I do not see that:

```
library(terra)
rast(ncol=100, nrow=100, ext(0,100,0,100))  |> as.polygons() |> crs()
#[1] ""
 
library(raster)
raster(ncol=100, nrow=100, extent(0,100,0,100))  |> rast() |> as.polygons() |> crs()
#[1] ""
 
rast()  |> as.polygons() |> crs(proj=TRUE)
#[1] "+proj=longlat +datum=WGS84 +no_defs"
 
rast(crs="+proj=utm +zone=1")  |> as.polygons() |> crs(proj=TRUE)
#[1] "+proj=utm +zone=1 +datum=WGS84 +units=m +no_defs"
``` 

The documentation shows that `as.polygons<SpatExtent>`  has an argument `crs`, but `as.polygons<SpatRaster>`  does not.

**Comment by herryATcsiro** [comment]
Weird,
I get  r=raster(ncol=100,nrow=100,extent(0,100,0,100))
> values(r)<-runif(ncell(r))
> p<-as.polygons(rast(r))
> p
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 2, 1  (geometries, attributes)
 extent      : 0, 100, 0, 100  (xmin, xmax, ymin, ymax)
 coord. ref. : +proj=longlat +datum=WGS84 
 names       : layer
 type        : <num>
 values      :     0
                   1
> r
class      : RasterLayer 
dimensions : 100, 100, 10000  (nrow, ncol, ncell)
resolution : 1, 1  (x, y)
extent     : 0, 100, 0, 100  (xmin, xmax, ymin, ymax)
crs        : NA 
source     : memory
names      : layer 
values     : 0.0000007664785, 0.9999851  (min, max)

Though, I am still running r 4.1.0. I'll upgrade and see what happens...

**Comment by rhijmans** [comment]
You are probably using an older version of `terra`
