### ISSUE TITLE
Dedicated function to load data into memory

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#507]
We have `readAll()` function in `{raster}`, but its equivalent is missing in `{terra}`. Now we need to do something like this `raster = raster * 1` to load data explicitly into memory. Would it be a good idea to add such a dedicated function?

**Comment by rhijmans** [comment]
Loading data explicitly into memory seems wasteful as it will happen anyway once you compute something. I suppose it could avoid reading in chunks, but if that happens you are probably creating problems in other ways. So I did not add it because it might lead people onto a path of inefficiency. Are there other reasons for it, beyond performance testing?

**Comment by rhijmans** [comment]
You can now do this in place with `set.values()` 

```
library(terra)
#terra 1.5.14
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
set.values(r)
r
#class       : SpatRaster 
#dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : memory 
#varname     : elev 
#name        : elevation 
#min value   :       141 
#max value   :       547 
```

**Comment by rhijmans** [comment]
You can now do this in place with `set.values()` 

```
library(terra)
#terra 1.5.14
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
set.values(r)
r
#class       : SpatRaster 
#dimensions  : 90, 95, 1  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : memory 
#varname     : elev 
#name        : elevation 
#min value   :       141 
#max value   :       547 
```

**Comment by kongdd** [comment]
Does it mean that I can save a memory sourced `rast` into R data?

**Comment by kadyb** [comment]
Not sure if I understand correctly, but you have always been able to convert a raster to R data.

```r
library("terra")
f = system.file("ex/elev.tif", package = "terra")
raster = rast(f)

vec = values(raster)
df = as.data.frame(raster)
mat = as.matrix(raster, wide = TRUE)

pack = wrap(raster)
saveRDS(pack, file = "raster.rds")
raster_rds = rast(readRDS("raster.rds"))
```

**Comment by kongdd** [comment]
@kadyb Thanks for your solution. This is just what I want.
