### ISSUE TITLE
Error using vect() to create points

### ISSUE THREAD

**Issue by jwkelley** [rspatial/terra#508]
Hi I am trying to use the function vect() to spatialize some data and keep getting the error message "Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'isTRUE': comparison (1) is possible only for atomic and list types"

It will work if I pass just a single point, but continues to generate this error with more than one point.

Ex:
df <- data.frame(Point = c(1,2,3), Long = c(-128.550,-128.433,-128.650), Lat = c(54.417, 54.533, 54.050))
coords <- cbind(df$Long, df$Lat) 
crs <- crs("+init=epsg:4326") 
Points <- vect(coords, crs = crs)
*Returns above error*

 x <- -128.550
y <- 54.417
coords <- cbind(x, y)
crs <- crs("+init=epsg:4326") 
point <- vect(coords, crs = crs)
works without error

Thanks for any help.

**Comment by rhijmans** [comment]
You can do 

```
library(terra)
df <- data.frame(Point = c(1,2,3), Long = c(-128.550,-128.433,-128.650), Lat = c(54.417, 54.533, 54.050))
coords <- cbind(df$Long, df$Lat)
crs <- "+init=epsg:4326"
Points <- vect(coords, crs = crs)
``` 
or 

```
library(terra)
df <- data.frame(Point = c(1,2,3), Long = c(-128.550,-128.433,-128.650), Lat = c(54.417, 54.533, 54.050))
coords <- cbind(df$Long, df$Lat)
Points <- vect(coords, crs = "epsg:4326")
``` 

You are using `raster::crs` to create a "CRS" object as defined by `sp`. terra does not know about these. 
The difference between the two cases is that the second case uses a matrix, and that does `as.character(crs)` whereas the `data.frame` method does not.  I will add a check to the data.frame method.

**Comment by kadyb** [comment]
Maybe it will work that way?

```r
library(terra) # 1.5.14
df <- data.frame(Point = 1:3,
                 Long = c(-128.550, -128.433, -128.650),
                 Lat = c(54.417, 54.533, 54.050))
coords <- cbind(df$Long, df$Lat)
points_from_matrix <- vect(coords, crs = "epsg:4326")
points_from_df <- vect(df, crs = "epsg:4326", geom = c("Long", "Lat"))
```

**Comment by jwkelley** [comment]
Thanks both. Recently moved over from rgdal and still getting used to the differences.
Cheers!

**Comment by rhijmans** [comment]
With the development version, both examples now work, but with a warning:

```
df <- data.frame(Point = c(1,2,3), Long = c(-128.550,-128.433,-128.650), Lat = c(54.417, 54.533, 54.050))
coords <- cbind(df$Long, df$Lat)
crs <- CRS("+init=epsg:4326")
Points <- vect(df, geom=c("Long", "Lat"), crs = crs)
#Warning message:
#[vect] argument 'crs' should be a character value 
```
