### ISSUE TITLE
terra::extract produces incorrect values in some cases...

### ISSUE THREAD

**Issue by chrishaak** [rspatial/terra#513]
I've run terra::extract (using a multipoint spatvector and a vector of corresponding layer ids) on two identically structured raster stacks (spatrasters).  The two spatrasters have been generated from netcdfs, and have the same dimensions/domains, etc., but represent different variables (we'll call them stack A and B).

Using the default (i.e. "simple") method to extract from stack A produces the correct values, but on the identically-structured stack B, it produces incorrect values, returning all "0"s (with the exception of the NAs).

Repeating this comparison with the method set to "bilinear" produces the correct values from both stacks... so the issue only seems to arise using "simple".

The only difference I can see between the two stacks is that the cell values in stack A (the one that is working fine) are only positive numbers, while the values in stack B are both positive and negative numbers.

The files I'm working with are huge but I will try to subset them and provide examples if you need them... but maybe this is enough to get you started!

Thanks!

**Comment by rhijmans** [comment]
It is possible (but unlikely if you created the files) that this is because of rounding. Are the values all very small? That is, would they round to zero? If so, can you do this with the development version?  `install.packages('terra', repos='https://rspatial.r-universe.dev')`

Otherwise, I would need an example. You could select one offending point and crop a small area round it for the the first two layers of A and B.

**Comment by chrishaak** [comment]
I just installed from github a day or so ago; so I'm thinking that is the dev version? (it includes a fix that you made a couple days ago).  The extracted values (when pulled using method="bilinear" are nicely distributed across a range from -1.1 to near-zero... (~4 orders of magnitude) so I wouldn't think rounding would be a problem?  I'll work on cropping some bits for you tonight...

**Comment by rhijmans** [comment]
Please do if you can.

**Comment by chrishaak** [comment]
Sorry - I had to wrap some things up first.  In putting together an example for you, I may have found a hint at what the problem is.  When I tried to recreate the issue using a subset of the original netcdf that was written out from terra (via writeCDF), I could not recreate it.  But when I subsetted the original netcdf from a command line without bringing it into R,  using CDO (climate data operators), the error still occurs.   So it's possible the problem may have something to do with the formatting/fields of the original netcdf file itself?  

I've attached a zip with the netcdf below....
```
#read in CDF to layered brick
library(terra)
SSH_brick<-terra::rast("SSH_subset.nc")
SSH_brick
summary(SSH_brick)# values ~ -1 and 1...

#make some sample coordinates
samplelocsX<-runif(n=10, min=-77, max=-59)
samplelocsY<-runif(n=10, min=33, max=51)
samplelocs<-vect(cbind(samplelocsX,samplelocsY), crs=crs(SSH_brick))

#make a vector of layers
samplelayers<-sample.int(n=10, size=10, replace=TRUE)
samplelayers  

#extract values
extracted<-terra::extract(SSH_brick, y=samplelocs, layer=samplelayers)
extracted   #these are not correct
extracted_bilin<-terra::extract(SSH_brick, y=samplelocs, layer=samplelayers, method="bilinear")
extracted_bilin  #these are correct
  
#now write the suspect file back to a netcdf using terra  
writeCDF(SSH_brick, filename="SSH_test.nc")
#read in what you just wrote...
SSH_brick2<-terra::rast("SSH_test.nc")
extracted2<-terra::extract(SSH_brick2, y=samplelocs, layer=samplelayers)
extracted2 #these are correct

#compare the two bricks
SSH_brick
SSH_brick2 #note that some fields are different or not there at all... could the problem be related to these fields in the original file?
``
If the "bilinear" method didn't work just fine, I would assume the error was due to something wonky in that specific netcdf file.  However, the fact that it works with one method but not the other suggests that something weird is also happening on the terra side of things?

Hope this helps,
C

[SSH_subset.zip](https://github.com/rspatial/terra/files/7964733/SSH_subset.zip)
`

**Comment by rhijmans** [comment]
Thank your for your efforts. This works fine for me. I think because this issue was solved earlier this week: https://github.com/rspatial/terra/issues/509   
Can you try with the development version?
