### ISSUE TITLE
Issues with raster package on Windows

### ISSUE THREAD

**Issue by GeoMapperJo** [rspatial/terra#514]
Hello,

I'm having difficulty using the raster package on windows - it appears that it is looking for terra v 1.5-12:

> library(raster)
Loading required package: sp
Error: package or namespace load failed for ‘raster’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘terra’ 1.4-22 is being loaded, but >= 1.5.12 is required

Is terra v 1.5.12 going to be available for Windows soon? 

I've tried installing the development version for Windows, however, this causes R to crash when calling the raster library.

I'm using R version 4.12 in RStudio v2021.09.2 Build 382.

Thanks!

**Comment by kadyb** [comment]
CRAN has not yet updated [terra](https://cran.r-project.org/web/packages/terra/index.html) to 1.5-12 for R 4.1.2 (since two weeks it is still the previous version).

Did you install the developer version from source or R-universe? I installed `{raster}` from CRAN and `{terra}` from R-universe and work fine to me on Windows 8.1.

**Comment by GeoMapperJo** [comment]
I've installed terra from R-universe as well and it has worked now on Windows 10 as well! Thanks so much!

For future reference my code was:

install.packages("raster")
# Enable universe(s) by geocompr
options(repos = c(
  geocompr = 'https://geocompr.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('terra')

**Comment by rhijmans** [comment]
I will send a new version to CRAN this weekend, hopefully it will get build for windows. What happens is that `raster` is dependent on that version of terra (or later), so you should *first* do

`install.packages('terra', repos='https://rspatial.r-universe.dev')` 

and then 

`install.packages(raster)`
