### ISSUE TITLE
combine tiles after makeTiles

### ISSUE THREAD

**Issue by LDalby** [rspatial/terra#515]
I'm running some processing across a large number of rasters and have tiled them to be able to fit them all in memory when doing the calculations. However the calculations ends with only one layers which I would like to combine back into its original form (i.e. as before calling `makeTiles`). I've used `stars::mosaic` for this and that works fine, but currently I only use the stars package for this one function, so it would be nice to have a similar functionality in terra.

So I guess my question boils down to: Is there a function in terra that would let me go back from `makeTiles`?

**Comment by kadyb** [comment]
You can create a virtual raster using [vrt](https://rspatial.github.io/terra/reference/vrt.html) (just like in `stars::st_mosaic`) and then save it to .tif.

Maybe in the `makeTiles()` documentation there should be a reference to `vrt()`?

**Comment by LDalby** [comment]
Right, I think that would make sense to include in the documentation. 
Thanks for your reply!
