### ISSUE TITLE
rast() and raster storage on disk vs RAM

### ISSUE THREAD

**Issue by VincentGodard** [rspatial/terra#516]
Hi,

I apologize if this is trivial or has been reported/solved already. 
I've experienced a situation where rasters generated manually with `rast` are not stored on disk when RAM availability is limited, eventually crashing my session.
For example, on my system, the following code will generate a number of large rasters, stored in RAM until it fills up completely.

```
library("terra")
n = 10000
m1 = matrix(1:n^2,nrow=n)

f1 <- function(m1){
  a = rast(m1,crs="EPSG:2154",ext=c(0,nrow(m1),0,ncol(m1)))
  return(a)
}


for(i in 1:40){
  print(i)
  assign(paste("rst",i, sep=""),f1(m1))
}

```

- terra version 1.4.22
- R version 3.6.3
- Ubuntu 20.04.3

Interestingly using the following function  (where `a=rast(....)*1`) instead, results in the expected behavior (rasters stored on disk depending on available memory).

```
f2 <- function(m1){
  a = rast(m1,crs="EPSG:2154",ext=c(0,nrow(m1),0,ncol(m1)))*1 # just multiply by 1
  return(a)
}
```

Best,
Vincent

**Comment by rhijmans** [comment]
There is no safeguard to you explicitly creating large objects in memory.  When you multiply with 1 the output will be written to disk if RAM is low. There are several ways other to avoid this. A much more canonical approach would be to do something like this:  

Create a single layer
```
library("terra")
n = 10
m1 = matrix(1:n^2,nrow=n)

a = rast(m1, crs="EPSG:2154",ext=c(0,nrow(m1),0,ncol(m1)))
a = writeRaster(a, filename="test.tif", overwrite=T)

# or even better, perhaps
r = rast(crs="EPSG:2154", ext=c(0,n,0,n))
a = trans( init ( r, "cell"), filename="test.tif", overwrite=T)
``` 

And replicated that to get a list

```
b <- replicate(40, a)
names(b) <- paste0("rst", 1:40)
```

And now use this list, or create a new SpatRaster

```
b <- rast(b)
```

Although I cannot think if a situation where it would be useful to have the same values 40 times. 

Also, you should *never* use `assign`. Instead use a list of a multi-layered `SpatRaster`; but that is not related to memory issues.

**Comment by VincentGodard** [comment]
Ok, thanks. 

The reason I was generating those 40 rasters was just to replicate and isolate a behavior I was experiencing with `rast` in another context, in a simpler way. 

I actually have a function which is sending a raster for processing to a GRASS session through `rgrass7` and I am reading back several output rasters into my R session using `rast` with something like that :

```
out1= terra::rast(raster::raster(rgrass7::readRAST(c(name1))))
out2= terra::rast(raster::raster(rgrass7::readRAST(c(name2))))
...
```
When my input raster is small everything is fine in RAM, but for large input rasters  the RAM is filled until saturation when reading back the (large) output rasters and nothing is written to tempdir.

> When you multiply with 1 the output will be written to disk if RAM is low. 

So that's what was not clear to me :  why `rast(....)` alone does not seem to be  aware of available memory in this context, whereas  `rast(....)*1`  is and will store outputs on disk in tempdir when needed (which seems to have solved my problem with large rasters).

**Comment by rhijmans** [comment]
Thanks for the clarification --- I assumed the worst because you are using `assign`. 
I think I would have a loop in  which I would do something like this:

```
infile <- paste0("input", 1:40, ".tif")
outfile <- paste0("output_", 1:40, ".tif")
rlist <- list()
for (i in 1:40) {
   out= terra::rast(raster::raster( rgrass7::readRAST( input[i] ))
   rlst[[i]] <- writRaster(out, output[i])
}

r <- rast(rlst)
```
