### ISSUE TITLE
extract has memory inefficiency

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#52]
I was seeing extract use a lot more memory than the final object used and saw that this line:

https://github.com/rspatial/terra/blob/c8966459e3862affd296aba2b4ef3ae84dae628d/R/extract.R#L32

which creates a list that then gets converted to a matrix here:

https://github.com/rspatial/terra/blob/c8966459e3862affd296aba2b4ef3ae84dae628d/R/extract.R#L42-L44

After the first chunk I see the memory used in my case is 7GB but 3GB after the matrixifying step
```r
Browse[3]> n
debug: r <- x@ptr$extractVector(y@ptr, touches[1], method[1])
...
Browse[4]> pryr::mem_used()
7.93 GB
...
debug: r <- lapply(1:length(r), function(i) cbind(ID = i, matrix(unlist(r[[i]]), 
    ncol = length(r[[i]]))))
Browse[4]> class(r)
[1] "list"
Browse[4]> n
debug: r <- do.call(rbind, r)
Browse[4]> pryr::mem_used()
3.22 GB
```
Is it feasible to go straight to the matrix output in the C++? https://github.com/rspatial/terra/blob/master/src/extract.cpp

**Comment by Robinlovelace** [comment]
Not sure if this is related but, in case it's useful, `terra::extract()` seems slower than `raster::extract()` in recently updated benchmark results presented here: https://github.com/ITSLeeds/slopes#performance

**Comment by kadyb** [comment]
I think it can be related. I noticed that sequential `terra:extract()` runs take more and more time in the case of extract by polygons. I did not notice such trend for points.

```r
library("terra")

points = vect("points.gpkg") # 50000
buffers = vect("buffers.gpkg") # 1000
rasters = list.files("rasters/", pattern = "\\.TIF$", full.names = TRUE)
ras = rast(rasters) # [7871, 7771, 10]

# run extract by points 20 times
system.time(extract(ras, points))
#> 7.35 7.49 7.52 6.94 6.86 7.08 6.83 6.80 6.81 6.81 6.80 6.84 6.78
#> 6.83 6.83 6.80 6.75 6.73 6.79 6.87
# times are similar 

# run extract by polygons 20 times
system.time(extract(ras, buffers, fun = mean))
#> 21.34 21.66 21.79 21.97 22.17 22.52 22.81 23.08 23.50 23.87
#> 24.50 25.00 25.28 25.73 26.13 26.20 26.53 26.96 27.31 27.67
# time increases each run
```

![Rplot](https://user-images.githubusercontent.com/35004826/106204143-c9a96580-61bc-11eb-8dd1-a3660fcc2afb.png)

**Comment by rhijmans** [comment]
Thank you all for your comments. I have implemented what Kendon suggested; C++ now returns a vector that R turns into a matrix. Before C++ returned a doubly nested list (geoms, layers, cells) that was flattened by R. That is probably faster. I have also partly separated the code for points (which can be simpler) from the code for lines and polygons.  On Robin's test with point extraction, terra and raster now have the same speed. That is good enough for now. raster does a few more tricks to speed up the process for points. terra is much faster for lines and polygons. There might still be work to do, so if you encounter something please start a new issue, if possible with a repex.

**Comment by kadyb** [comment]
I can confirm that in the new version it works faster and next iterations do not take longer. I tested the above example again, but on worse hardware (8 GB RAM). For the record, here are the results (in seconds):

```
terra 1.1-17:
34.44, 33.85, 34.11, 33.72, 34.12, 33.89, 34.14, 39.83, 34.46, 34.34 

terra 1.0-10:
41.77, 41.86, 42.37, 43.56, 44.7, 53.03, 53.82, 54.26, 55.47, 56.48 
```

Thank you very much!
