### ISSUE TITLE
How to retrieve data using WCS?

### ISSUE THREAD

**Issue by abdelkrim-bsr** [rspatial/terra#521]
There's any function that allows to retrieve data using WCS protocol such as rgdal::gdal_translate()? 

The following example explains how to do it using rgdal at this link: https://git.wur.nl/isric/soilgrids/soilgrids.notebooks/-/blob/master/markdown/wcs_from_R.md.

**Comment by brownag** [comment]
I have an example of downloading SoilGrids data from WCS with {terra} at this gist: https://gist.github.com/brownag/59a0927d97398bf1aa3ec73bb326cdc8

Would welcome any comments/criticism on the code!

**Comment by rhijmans** [comment]
You can use different protocols to read data over an Internet connection. You can then create a SpatRaster with such a connection and then use the terra functions. 

You can find another example in the `geodata` package. See  `?geodata::soil_world_vsi`

**Comment by brownag** [comment]
I have an example using `sf::gdal_utils()` with the raster manipulation in terra

https://gist.github.com/brownag/59a0927d97398bf1aa3ec73bb326cdc8

Open on any suggestions to make it more terra-oriented

**Comment by rhijmans** [comment]
Both approaches use VSI instead of WCS. VSI appears to be much simpler to implement. For soilgrids, also see `geodata::soil_world`

**Comment by abdelkrim-bsr** [comment]
`geodata::soil_world` allows to get raster at 1k of resolution. I am
wondering if there is an alternative (generic function) that allows to
access to any WCS service other than SoilGrid.
