### ISSUE TITLE
Support to read 

### ISSUE THREAD

**Issue by bniebuhr** [rspatial/terra#524]
I would like to request/suggest a method for transforming `SpatialGridDataFrame` objects into `SpatRaster` objects, as there is for the `raster` package.

Among other contexts, it would help the integration of R and GRASS GIS (see the issue here: https://github.com/rsbivand/rgrass/issues/42#issue-1122491809).

**Comment by rhijmans** [comment]
With SpatialGridDataFrame `x`, you can now do `rast(x)` .
