### ISSUE TITLE
Wrong use of "xlim" when plotting a SpatVector

### ISSUE THREAD

**Issue by hirscht** [rspatial/terra#525]
I´m  trying to plot SpatVectors containing one or more polygons using:

```
 plot(polySR, "corr", ylim = c(-90,90), xlim = c(-180, 180), col=colors_curr, lwd=0.5, main="")
```

On the resulting plots, the value set for ylim is always used appropriately, however, **I get problems with xlim**. For most of the plots, the result is more or less different from that set for xlim as an argument of plot( ).  In the most extreme cases, I get an interval of "-2000, +2000" instead of "-180,+180", see e.g. here:

![grafik](https://user-images.githubusercontent.com/92745862/152346556-78c38b3c-6b64-41f6-9a5e-c52ca8ae4e25.png)

Interestingly, changing the setting of ylim (while leaving the setting of xlim the same) has a huge effect on the x interval used for the plot, which of course shouldn´t be the case. E.g. by reducing ylim, the x interval used on the plot becomes smaller:

![grafik](https://user-images.githubusercontent.com/92745862/152347792-31a7eb47-e1a8-4927-9d27-34356e9cd3a6.png)
![grafik](https://user-images.githubusercontent.com/92745862/152347952-0313f862-f2f4-418e-8d02-ccaeb76fdb10.png)

I´m using **terra1.5-18.** All the SpatVectors I´d like to plot are generated in terra from standard gridded fields, converted into SpatRasters, followed by applying patches( ), as.polygons( ), make_valid( ) and finally intersect( ) to obtain the right polygons as SpatVectors. I also tried using "ext" in the argument of plot( ) instead of  "xlim, ylim" but it had no effect on the result.

The SpatVector for the extreme plot above looks like this:

```
> polySR
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 1, 1  (geometries, attributes)
 extent      : -138, 20.5, 80.0277, 89.50139  (xmin, xmax, ymin, ymax)
 coord. ref. : lon/lat WGS 84 
 names       :  corr
 type        : <num>
 values      :   0.4
```

Have you got an idea what could go wrong here?

**Comment by hirscht** [comment]
The shape file for polySR used for the plots above:
[polySR.zip](https://github.com/rspatial/terra/files/7995207/polySR.zip)

**Comment by rhijmans** [comment]
I think there are two things are going on here. First, `xlim,` and `ylim`  assure that the specified range is included, but if there is more space on the canvas, one of the axes may go beyond that range. You can deal with this by adjusting the size of the canvas. Second, because this is a map, the aspect (x, y ratio) is enforced. You can turn that off with `aspect=NA` or overwrite that with `aspect=1` (or another number)  as in `plot(polySR, aspect=NA)`

**Comment by hirscht** [comment]
Thank you for your reply!

```
> plot(polySR, "corr", aspect=NA, ylim = c(-90,90), xlim = c(-180, 180))
Warning:
In graphics::polypath(a[, 3:4], col = out$main_cols[i], rule = "evenodd",  :
  "aspect" is no graphic parameter
```

I´ll have a look at plot( ) to find an available arguement to set this.

**Comment by hirscht** [comment]
The parameter I was looking for is "asp". Setting it to NA in plot( )as suggested provides a good result:

![grafik](https://user-images.githubusercontent.com/92745862/152523885-823a1aed-553f-4dec-9824-8e372f6f3db4.png)

I´ll test my whole range of cases. A huge thanks once again, I thought it might be something with the SpatVectors I´m creating but it´s only the way these are displayed  👍

**Comment by rhijmans** [comment]
Sorry about suggesting the use of `aspect` instead of `asp` (I edited my comment to avoid confusion by future readers).
