### ISSUE TITLE
error message when reading large points SpatVector

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#53]
https://www.dropbox.com/s/3ecle2fbfxzdlyo/tmp.zip?dl=0

```
> library(terra)
This is terra version 0.7.1 (alpha-release)
> vect(readRDS("tmp.rds"))
Error in (function (x)  : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
class       : SpatVector 
geometry    : points 
elements    : 4048535
extent      : 166.4384, 178.5495, -47.27409, -34.40156  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=intl +no_defs 
names       : MB2006_V1_ 
```

The error messages don't actually throw proper R errors so the code still runs apparently correctly

**Comment by rhijmans** [comment]
This is the same as [#30](https://github.com/rspatial/terra/issues/30)

Also some discussion [here](https://stackoverflow.com/questions/61598340/why-does-rastertopoints-generate-an-error-on-first-call-but-not-second)
