### ISSUE TITLE
The zonal() function freezes R for some datasets

### ISSUE THREAD

**Issue by jguelat** [rspatial/terra#533]
The following code is running fine using raster::zonal, but it freezes R if I use terra (version 1.5-17).

```
library(terra)
vals <- rast("values.tif")
zones <- rast("zones.tif")
results <- zonal(vals, zones, fun = sum, na.rm = TRUE) # same problem if I use "sum" instead of sum
```

The dataset is available there:
[testdata.zip](https://github.com/rspatial/terra/files/8025335/testdata.zip)
 
<details>
<summary>Session info:</summary>
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.5-17

loaded via a namespace (and not attached):
[1] compiler_4.1.1   Rcpp_1.0.8       codetools_0.2-18
</details>

**Comment by rhijmans** [comment]
Here is a work-around --- for if you can load the rasters into memory: 

```
x = zonal(r, z, \(i) sum(i, na.rm=T))
```

**Comment by rhijmans** [comment]
It took me a while, but this is now much faster:

```
library(terra)
vals <- rast("values.tif")
zones <- rast("zones.tif")
results <- zonal(vals, zones, fun = sum, na.rm = TRUE) 

system.time(results <- zonal(vals, zones, fun = sum, na.rm = TRUE) )
#   user  system elapsed 
#   0.67    0.06    0.73 
```

Also see https://github.com/rspatial/terra/issues/595
