### ISSUE TITLE
`terra::categories()` not exported

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#534]
I noticed that the generic for `categories()` is defined and usage is covered in the categorical raster documentation file, but it is not exported in NAMESPACE.

Is this to avoid name conflicts with other packages or an unintended omission?
https://github.com/rspatial/terra/blob/af3363380d3d533f28d0c47796de4d882f6c8de2/NAMESPACE#L5

**Comment by rhijmans** [comment]
Thanks. That indeed was an unintended omission.
