### ISSUE TITLE
as.matrix method for terra objects (feature request)

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#535]
Would it be possible to add an `as.matrix` method for `terra` objects that preserves the row/column dimensions like in `raster`? It's not really essential but nice if you're working with data small enough to fit in memory and testing things out or using a non-terra function that takes a matrix as an input.

```
library(raster)
library(terra)

r_raster<- raster(matrix(1:9,nrow=3))
as.matrix(r_raster)
# [,1] [,2] [,3]
# [1,]    1    4    7
# [2,]    2    5    8
# [3,]    3    6    9
r_terra<- rast(matrix(1:9,nrow=3))
as.matrix(r_terra)
# lyr.1
# [1,]     1
# [2,]     4
# [3,]     7
# [4,]     2
# [5,]     5
# [6,]     8
# [7,]     3
# [8,]     6
# [9,]     9
```

**Comment by Nowosad** [comment]
Have you tried `as.matrix(r_raster, wide=TRUE)`?

**Comment by ailich** [comment]
@Nowosad, thanks. I was not aware of that argument!
