### ISSUE TITLE
Reading Met Office UKCP18 raster stacks from netcdf

### ISSUE THREAD

**Issue by danbebber** [rspatial/terra#539]
I'm having trouble importing a raster stack from the Met Office UKCP18 data in netcdf format.
The issue is that the CRS and extent aren't read, so the extent is assumed to be (0,1,0,1).

pr2020 <- rast("~/Documents/Data/Climate/UKCP18/pr_rcp85_land-cpm_uk_2.2km_01_mon_202012-202111.nc")

class       : SpatRaster 
dimensions  : 606, 484, 12  (nrow, ncol, nlyr)
resolution  : 0.002066116, 0.001650165  (x, y)
extent      : 0, 1, 0, 1  (xmin, xmax, ymin, ymax)
coord. ref. : NA 
source      : pr_rcp85_land-cpm_uk_2.2km_01_mon_202012-202111.nc 
varname     : pr (Precipitation rate) 
names       : pr_en~r=1_1, pr_en~r=1_2, pr_en~r=1_3, pr_en~r=1_4, pr_en~r=1_5, pr_en~r=1_6, ... 
unit        :      mm/day,      mm/day,      mm/day,      mm/day,      mm/day,      mm/day, ... 
time        : 2020-03-24 to 2021-02-17

Using ncdf4 to open the netcdf allows me to access the grid cell coordinates (in degrees). Somehow these are not being correctly read by rast(). Possibly the CRS is improperly specified. I'm afraid my understanding of netcdf and CRS is rather limited.
I've uploaded a zipped version of the file:
[pr_rcp85_land-cpm_uk_2.2km_01_mon_202012-202111.nc.zip](https://github.com/rspatial/terra/files/8047787/pr_rcp85_land-cpm_uk_2.2km_01_mon_202012-202111.nc.zip)

**Comment by rhijmans** [comment]
The data are not on a regular grid. You can force them into that with 

```
library(raster)
b <- brick("pr_rcp85_land-cpm_uk_2.2km_01_mon_202012-202111.nc", stopIfNotEqualSpaced=FALSE)
```

I plan to eventually do something like this, or better, for terra, but that may take a while.
