### ISSUE TITLE
Confirm mosaic() functionality

### ISSUE THREAD

**Issue by benjaminmisiuk** [rspatial/terra#540]
Documentation for the `mosaic()` function currently states that:

```
\details{
The SpatRaster objects must have the same origin and spatial resolution. In areas where the SpatRaster objects overlap, the values of the SpatRaster that is last in the sequence of arguments will be retained. 
}
```

I believe that the behavior at the area of overlap as actually controlled by the `fun` argument, with the default being `mean`. Can you confirm? 

``` 
library(terra)

x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, ncols=30, nrows=30)
y <- rast(xmin=-85, xmax=-55, ymax=60, ymin=30, ncols=30, nrows=30)
values(x) <- 1:ncell(x)
values(y) <- 1:ncell(y)

m1 <- mosaic(x, y)

plot(m1)
```

![image](https://user-images.githubusercontent.com/59960867/154315812-ff6963d6-4e24-452c-b6d3-c1a7f1f28b9b.png)

Thank you.

**Comment by rhijmans** [comment]
Thanks!
