### ISSUE TITLE
rast does not error with invalid value for nrows

### ISSUE THREAD

**Issue by dbaston** [rspatial/terra#544]
I would expect an error here:

```
terra::rast(nrows =-4, ncols = 4, xmin = 0, xmax = 10, ymin = 0, ymax = 10)
```
(note the negative value of `nrows`)
but I get

```
class       : SpatRaster 
dimensions  : 4294967292, 4, 1  (nrow, ncol, nlyr)
resolution  : 2.5, 2.328306e-09  (x, y)
extent      : 0, 10, 0, 10  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
```

**Comment by Rapsodia86** [comment]
A detail here. When both are negative (or zero), it only informs about ncols < 1
> library(terra)
terra 1.5.22
> terra::rast(nrows =-4, ncols=-4, xmin = 0, xmax = 10, ymin = 0, ymax = 10)
Error: [rast] ncols < 1
> terra::rast(nrows =-4, ncols=4, xmin = 0, xmax = 10, ymin = 0, ymax = 10)
Error: [rast] nrows < 1
> terra::rast(nrows =-4, ncols=-4, xmin = 0, xmax = 10, ymin = 0, ymax = 10)
Error: [rast] ncols < 1

**Comment by rhijmans** [comment]
It is common practice to stop on the first error encountered and to report that error.

**Comment by Rapsodia86** [comment]
Ok, thank you for the explanation.
