### ISSUE TITLE
SpatRaster readValues inconsistent with [ operator

### ISSUE THREAD

**Issue by dbaston** [rspatial/terra#546]
I am using the `readValues` method to read blocks of data from a `SpatRaster` without loading the entire raster into memory. I have been given a case where the return values of `readValues` are inconsistent with the values returned by the `[` operator. Am I using `readValues` incorrectly?

The test file is from https://github.com/isciences/exactextractr/issues/70#issuecomment-1046007052
```
r <- rast("rr_annual_1995-2021.2000.img")
readStart(r)

mean(readValues(r, row = 1, nrows = 1), na.rm = TRUE)
# 27.645

mean(r[1, ][[1]], na.rm = TRUE)
# NaN

# last row with [ operator matches first row with readValues
mean(r[nrow(r), ][[1]], na.rm = TRUE)
# 27.645
```

**Comment by rhijmans** [comment]
Ay, that is ugly. `terra` reads flipped rasters, such that there is no need to first flip them, but there obviously was a bug that I think is now fixed. 

library(terra)
r <- rast("rr_annual_1995-2021.2000.img")
readStart(r)
v <- readValues(r, row = 1, nrows = 10)
readStop(r)
 
mean(v, na.rm = TRUE)
#[1] 699.5718
mean(r[1:10, ][[1]], na.rm = TRUE)
#[1] 699.5718
```

**Comment by dbaston** [comment]
Thank you for the fix!
