### ISSUE TITLE
Inconsistent plot with plotRGB(..., stretch="linear") and plot(stretch())

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#550]
Using
https://www.dropbox.com/s/5z1uqd019ic0j74/LC08mini.tif

I get inconsistent display with the strectch
option in plotRGB() and with stretch():

```
require(terra)
LC08 <- rast("LC08mini.tif")
colort=gray.colors(32,start=0,end=1,gamma=1.0)
par(mfrow=c(2,3))
plotRGB(LC08,r=5, g=5, b=5,stretch="linear")
a <- terra::stretch(LC08[[5]],minq=0.02, maxq=0.98)
plot(a,legend=FALSE,axes=FALSE,col=colort)
plotRGB(a,r=1, g=1, b=1)

v <- stats::quantile(LC08[[5]], c(0.02, 0.98), na.rm = TRUE)
temp <- (255 * (LC08[[5]] - v[1]))/(v[2] - v[1])
temp[temp < 0] <- 0
temp[temp > 255] <- 255
plotRGB(temp,r=1, g=1, b=1)
plot(temp,legend=FALSE,axes=FALSE,col=colort)
summary(LC08[[5]])

```

![plot_zoom](https://user-images.githubusercontent.com/6074054/158343137-0b3a60bf-f640-441b-b244-886e03b914df.jpeg)

What stretching options is actually using strectch="linear" ?
It looks like the problem is in stretch(), but could not find this function in the github code.

**Comment by rhijmans** [comment]
Thanks; indeed this was an issue with `stretch`.

**Comment by aloboa** [comment]
ok, thanks. I confirm it works much better now, but there is still a difference between
`plotRGB(LC08,r=1, g=1, b=1,stretch="linear")`
and both
```
a <- terra::stretch(LC08[[1]],minq=0.02, maxq=0.98)
plotRGB(a,r=1, g=1, b=1)
```
and
```
v <- stats::quantile(LC08[[5]], c(0.02, 0.98), na.rm = TRUE)
temp <- (255 * (LC08[[5]] - v[1]))/(v[2] - v[1])
temp[temp < 0] <- 0
temp[temp > 255] <- 255
plotRGB(temp,r=1, g=1, b=1)

```
why?
