### ISSUE TITLE
layerCor temp files filling all available diskspace

### ISSUE THREAD

**Issue by Canderson156** [rspatial/terra#551]
I'm trying to analyze a subset of the Woldclim bioclimatic data (19 raster layers) that covers the Canadian Arctic. I'd like to see how correlated the layers are. When using the layerCor function, I keep getting the following error message: 

cor_present_temp <- layerCor(bioclim_present, "pearson", na.rm = TRUE)

Error in h(simpleError(msg, call)) : 
Error in evaluating the argument ‘x’ in selecting a method for function ‘global’: [[is.na](http://is.na/)] insufficient disk space (perhaps from temporary files?)

I tried splitting the layers into two groups but am still having the same issue. I'm currently running a test with only two layers.

After trying to run this code, my entire hard drive become full. I have to go into user/AppData and delete the temporary files.

Is there anything I'm doing incorrectly when using this function? What could I do to get this to work? 

and shouldn't R delete these temporary files when I close the program? This hasn't been happening, I've been having to do it manually

**Comment by Canderson156** [comment]
After further testing, R does seem to delete the temporary files when I shut the program down now. I've discovered I can analyze up to 6 layers before I get this error.

So, I tried splitting the dataset into 4 groups of 5-6 layers. However, when I try to run this analysis, I still get the error message when running the second dataset. Shouldn't the temporary files be gone once the analyses is complete? Can I erase them within R so that I don't have to open and close R to run the full analysis?

**Comment by rhijmans** [comment]
I have improved the algorithm such that no temporary files should be created.  You can try the development version (should be available in a couple of hours at the R-Universe)

As for the temp files, yes they are removed at the end of the session (unless R crashes). You can also remove them with `terra::tmpFiles` . It would seem that your temp folder has very little disk space. You can set it to another place (for terra) with `terraOptions(tempdir="path")`. But then the temp files are not removed (I will change that).
