### ISSUE TITLE
rasterize(..., fun=count, touches=TRUE) not counting polygons within grid cells?

### ISSUE THREAD

**Issue by jasonbmackenzie** [rspatial/terra#553]
hi robert. i am trying to use rasterize() to count the number of polygons overlapping individual raster cells (code below). the polygons are buildings (assigned 'value'=1), and the raster is my area of interest. some grid cells (250m) contain multiple buildings, so the raster output should include a range of values (e.g., 0-n). however, my output is binary (i.e., 0 | 1), so it would seem the 'sum' function is not working properly? 

is the problem with my code (below), my approach, or the function?  

```
library(sf)
library(terra)

sf <- st_read(dsn=D:/vars.gdb, layer="buildings")
v  <- vect(sf)

e <- rast("D:/extent.tif")
crs(e) -> "epsg:3577"
r <- classify(e, cbind(1, 0))         # reclass raster values from 1 to 0

x <- rasterize(v, r, field="value", fun=sum, touches=TRUE)
c <- cover(x,r)                       # replace extent values (0) with building values (1-n)

```

**Comment by jasonbmackenzie** [comment]
i also tried the 'count' function below, but the output is the same as above - i.e., a binary raster with only 0s and 1s - rather than a sum or count of polygon numbers

`x  <- rasterize(v, r, fun=count, touches=TRUE)`

**Comment by rhijmans** [comment]
Hi Jason, Sorry for the slow response --- great to see a sign of life from you! Robert

When summing values associated with points, you can use `fun=sum`. For polygons, you need to use `sum=TRUE`. Yeah, that is not so obvious. With that, summing polygons when rasterizing works for me in this example:

``` 
# example data 
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
h <- convHull(v, "NAME_1") |> buffer(10000)
r <- rast(h, res=.1)

# sum "1"s
x <- rasterize(h, r,  sum=TRUE)

# sum values associated with the polygons
h$value <- 10:12
y <- rasterize(h, r, "value", sum=TRUE)
```
You can then use `ifel` or `classify` to set the zeros to `NA`

With this toy example, you can also do 

```
u <- union(h)
u$sum <- rowSums(data.frame(u))
z <- rasterize(u, r, "sum")
```
But that can easily fail with complex polygons if invalid polygons arise from the intersections.

**Comment by jasonbmackenzie** [comment]
hi robert! great to hear from you, and thanks for the clarifications  )

all variations of rasterize() below count polygons, with output values ranging from 0:2. i suspect only polygons that overlap cell centroids are considered. when using 'sum=TRUE', 'type=*' (below) appears to be ignored, and 'touches=TRUE' returns the error 'cannot use add and touches at the same time'. is there an argument for considering all polygons that touch or overlap any part of a grid cell?
 
```
s1 <- rasterize(v, r, sum=TRUE)
s2 <- rasterize(v, r, "value", sum=TRUE)
s3 <- rasterize(v, r, sum=TRUE, type="touches")
s4 <- rasterize(v, r, sum=TRUE, type="intersects")
```

e.g., this zoom of my raster lattice and building footprints shows expected counts are >2 in urban areas. 
![fishnet](https://user-images.githubusercontent.com/50162077/161459580-cecb0d5d-0704-4b14-b1fd-afdb0a2e4c7d.png)

**Comment by rhijmans** [comment]
That is interesting, you want to count how many (small, not overlapping) polygons there are in a much larger raster cell. That probably merits a new method.  Here are some initial notes/thoughts:

```
# example data 
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
values(v) <- NULL
set.seed(44)
s <- spatSample(v, 100)
b <- buffer(s, 1000)

r <- rast(v, res=.1)
plot(b, col="red")
lines(r)
``` 

You could approximate this using the centroids

```
x <- centroids(b)
p1 <- rasterize(x, r, fun=length)
``` 

More exact, using polygon intersection --- but that may not scale to your dataset 

```
values(r) <- 1:ncell(r)
names(r) <- "cell"
z <- as.polygons(r)
u = intersect(z, b)
tab <- table(u$cell)
tab <- cbind(as.integer(names(tab)), tab)

p2 <- setValues(r, 0)
p2[tab[,1]] <- tab[,2]
```

**Comment by jasonbmackenzie** [comment]
thanks again, robert. i tried converting my grid cells to individual polygons (below) for polygon intersection, but the process hangs. i tried doing the same in arcpro (i.e., 'create fishnet', followed by 'feature to polygon'), but same story... polygonise hangs. i considered approximating with building centroids, but prefer an exact solution, if possible.

`p<- as.polygons(r, trunc=FALSE, dissolve=FALSE, values=FALSE, na.rm=TRUE, extent=TRUE)`

as an alternative, dan baston suggested I call exact_extract() with include_cell=TRUE (below), then combine the resulting data frames and sum how many times each cell number appears. 

`x <- exactextractr::exact_extract(r, v, include_cell=TRUE)`

**Comment by rhijmans** [comment]
Yes, that could work. There are variations with terra::extract, either extract as polygons with the weights or exact options (as Dan suggested, but slower); or alternatively, extract with cell=TRUE (but that only works if no polygon covers an entire cell, as seems to be the case for you. With the example data from above, you can then do:

```
b$id = 1:nrow(b)
p = as.points(b)
values(r) = 0
e = extract(r, p, cell=T)
tab <- tapply(e$cell, p$id, unique) |> unlist() |> table()
tab <- cbind(as.integer(names(tab)), tab)
r[tab[,1]] <- tab[,2]
```

This simple approach also seems to work (extract with polygons), and that surprises me:

```
e2 = extract(r, b, cell=T)[, c(1,3)]  |> unique()
tab2 <- table(e2[,2])
tab2 <- cbind(as.integer(names(tab2)), tab2)
r[tab2[,1]] <- tab2[,2]
```

**Comment by jasonbmackenzie** [comment]
thanks, robert! no surprise your solutions were a lot more elegant than mine (below), but extracting cellNumbers to table was definitely the way to go. much appreciated, and awesome job on the raster/terra packages   )

```
f_db <- "D:/covariates.gdb"
f_e  <- "D:/extent.tif"
f_bd <- "D:/buildingDensity.tif"

bf  <- st_read(dsn=f_db,layer="buildingFootprints")

e <- rast(f_e)
values(e) = 0
 
x <- exactextractr::exact_extract(e, bf, include_cell=TRUE)

c <- as.data.frame(cells(e)) 
names(c) <- "cell"

df <- bind_rows(x, .id = "id") %>% 
      as_tibble() 
df.g <- df %>% group_by(cell) %>% 
               mutate (value = ifelse((value == 0), 1, value)) %>% 
               summarize(counts = sum(value, na.rm=TRUE)) 
m  <- c %>% left_join(df.g, by="cell") %>%
            mutate(counts = replace_na(counts, 0))

e[m[,1]] <- m[,2]
writeRaster(e, f_bd, overwrite=TRUE)
```

**Comment by rhijmans** [comment]
Here is that approach with the reproducible example and simple R 

Example data 

```
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
values(v) <- NULL
set.seed(44)
s <- spatSample(v, 100)
b <- buffer(s, 1000)
r <- rast(v, res=.1)
``` 

Solution 

```
cells <- setValues(r, 1:ncell(r))
e <- extract(cells, b, exact=TRUE)
x <- aggregate(e[,1], e[,2,drop=FALSE], function(i) length(unique(i) ) )
values(r) <- 0
r[x[,1]] <- x[,2]	
plot(r)
lines(b)
```

![polcnt](https://user-images.githubusercontent.com/11481397/162793538-8b172d9f-345c-4625-865a-aa8ede28f806.png)

**Comment by rhijmans** [comment]
Reopening because this merits its own method

**Comment by rhijmans** [comment]
The new `rasterizeGeom` method can now take care of this

Example data 

```
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
set.seed(44)
s <- spatSample(v, 100)
b <- buffer(s, 1000)
r <- rast(v, res=.1)
```

Solution

```
x <- rasterizeGeom(b, r, fun="count")
```

**Comment by jasonbmackenzie** [comment]
thanks again, robert!  ))

**Comment by SDavies98** [comment]
I have a Shapefile of habitat type across Great Britain - I have split this large Shapefile into smaller categories by filtering in R. 

For each of these smaller categories I used the coverage_fraction (method here: https://gis.stackexchange.com/questions/359277/rasterization-of-polygons-calculation-of-the-area-covered) to convert to a raster and work out the ha of each habitat category in my Great Britain grid cells (1km2 / 100 ha cells). For each habitat the range of ha is always between 0 and 100 - which is correct. 

My issue is when I look at the sum of the habitats the total ha often exceeds 100 ha value - which is incorrect. 

I have checked the resolution / extent are fine. I have also tried different methods e.g. rasterize / rasterizeGeom. I have also considered the issue may arise when splitting my shapefiles - I have looked at tools in ArcMap such the dissolve tool - but I am still running into this issue. 

If anyone has any advice to help resolve this issue please let me know.
