### ISSUE TITLE
spatSample() error using projected data when "cells = TRUE"

### ISSUE THREAD

**Issue by benjaminmisiuk** [rspatial/terra#554]
Hello,

I've noticed that spatSample() fails to subsample a SpatRaster when it has been projected and `cells = TRUE`, for multiple datasets. It seems to work for unprojected data.
```
library(terra)

f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)

n_vals <- sum(!is.na(values(r)))
spatSample(r, n_vals*0.5, as.df = TRUE, na.rm = TRUE, cells = TRUE)
``` 

It works well for projected data too if the cell numbers are not returned.
```
r_prj <- project(r, y = "epsg:32632")

n_vals <- sum(!is.na(values(r_prj)))
spatSample(r_prj, n_vals*0.5, as.df = TRUE, na.rm = TRUE, cells = FALSE)
```

But it's failing if `cells = TRUE`.
```
spatSample(r_prj, n_vals*0.5, as.df = TRUE, na.rm = TRUE, cells = TRUE)
#Error in sample.int(x, size, replace, prob) : 
#  cannot take a sample larger than the population when 'replace = FALSE'
```

If we reduce the sample size it works.
```
spatSample(r_prj, n_vals*0.25, as.df = TRUE, na.rm = TRUE, cells = TRUE)
```

Apologies, but I couldn't find the reason for the error in your sample.R code. The error only showing up for projected data had me stumped.

Hope it's an easy fix!
Ben

**Comment by rhijmans** [comment]
Thank you for the helpful example. I believe this has now been fixed.
