### ISSUE TITLE
Using sum with lapp?

### ISSUE THREAD

**Issue by JimShady** [rspatial/terra#555]
Hello,

Thanks for the excellent package.

I am trying to use my own fairly complex function on a set of 12 large rasters. It keeps breaking. I have managed to reduce the issue down to a small reprex which I'm hoping someone could explain why it won't work / recommend a solution?

```
library(terra)

r <- rast(nrows=5, ncols=5, xmin=0, xmax=1, ymin=0, ymax=1)
values(r) <- c(1:24, NA)

p <- rast(nrows=5, ncols=5, xmin=0, xmax=1, ymin=0, ymax=1)
values(p) <- c(1:24, NA)

test <- function(x,y) {
   a <- sum(x*0.3, y*0.4, na.rm=T)
   return(a)
}

lapp(c(r,p),
    fun = test)

Error: [lapp] I do not like 'fun' :(
```

Thanks for any guidance.

**Comment by rhijmans** [comment]
What you want is a function that does (x + y). The problem is that `sum(x, y)`  is not vectorized like that. 

```
library(terra)
r <- rast(nrows=5, ncols=5, xmin=0, xmax=1, ymin=0, ymax=1)
values(r) <- c(1:24, NA)
p <- rast(nrows=5, ncols=5, xmin=0, xmax=1, ymin=0, ymax=1)
values(p) <- c(1:24, NA)

# without na.rm
test <- function(x,y) {
   x*0.3 + y*0.4
}

lapp(c(r,p), fun = test)

# for na.rm you would need apply or some such
test2 <- function(x,y) {
   apply(cbind(x*0.3, y*0.4), 1, sum, na.rm=TRUE)
}

lapp(c(r,p), fun = test2)
```

Instead of using apply, it *might* be faster to do call `sum`  or `app(x, sum)` after `lapp`

**Comment by JimShady** [comment]
Thank you for the help. Will do some tests and see which is more performant.
