### ISSUE TITLE
app v lapp performance?

### ISSUE THREAD

**Issue by JimShady** [rspatial/terra#556]
Afternoon,

I have been doing some tests on whether it is more performant to use lapp or app when doing calculations on a number of raster layers. I found the results quite interesting. Unless I am mistaken (?) these two functions are achieving the same result, but lapp is much faster. Grateful for any comments or thoughts?

Thanks.

```
library(terra)
library(microbenchmark)

r <- rast(nrows=500, ncols=500, xmin=0, xmax=1, ymin=0, ymax=1)
values(r) <- c(1:250000)


p <- rast(nrows=500, ncols=500, xmin=0, xmax=1, ymin=0, ymax=1)
values(p) <- c(1:250000)


app_fun <- function(x) {
   a <- sum(x[[1]]*0.3, x[[2]]*0.4, na.rm=TRUE)
   return(a)
}


lapp_fun <- function(x,y) {
    a <- x*0.3
    b <- y*0.4
    a <- ifelse(is.na(a), 0, a)
    b <- ifelse(is.na(b), 0, b)
    c <- ifelse(test = (a+b == 0), yes = NA, no = a+b)
    return(c)
}


microbenchmark( app = app(c(r,p),   fun = app_fun), 
                lapp = lapp(c(r,p), fun = lapp_fun),
                times = 20)

Unit: milliseconds
 expr      min       lq     mean    median        uq      max neval
  app 659.1653 724.8601 792.7342 785.99755 836.65680 991.9264    20
 lapp  36.1786  39.7143  67.4657  44.44995  86.55815 201.3421    20
```

**Comment by rhijmans** [comment]
I think this is because `app` uses `apply` whereas `lapp` is vectorized. Here is another function for lapp, that is twice as fast as yours in my tests 

```
lapp_fun2 <- function(x,y) {
    rowSums(cbind(x*0.3, y*0.4), na.rm=TRUE)
}
```

**Comment by JimShady** [comment]
Interesting. Thank you again. I'll give this a go, because I'm writing functions which can take 10-15 minutes per raster set at the moment, and I need to do it many times. So saving even 10-15% of time will be a great speed boost.
