### ISSUE TITLE
raster rasterize v. terra rasterize

### ISSUE THREAD

**Issue by JimShady** [rspatial/terra#558]
Hi there.

Unless I am missing something in the documentation, some of the features of the {raster} function 'rasterize' are missing from the {terra} version. For example this does not seem possible in {terra}. Am I correct? Any suggested work-around please?

```
raster::rasterize(x = polygons_data,
                          y = template_raster,
                          update = TRUE,
                          updateValue = '!NA')
```

What I am trying to do here is to update all of the non-NA values in my template_raster with values from the corresponding polygons. I'm doing this on a large high resolution raster, so when running it in anger I'll also specific an output filename and datatype etc.

Thanks!

**Comment by jldupouey** [comment]
You are right, there is not `updateValue` parameter in `terra::rasterize`. But adding a masking step should give you the result you are looking for:

```
UpdtRast <- terra::rasterize(x = polygons_data,
                             y = template_raster,
                             update = TRUE)
mask(UpdtRast,template_raster)
```

**Comment by rhijmans** [comment]
`updateValue` in raster::rasterize has three possible values: "all", "NA", "!NA".  In `terra` (and raster), "all" is default. With terra, you can use `cover` after rasterize for `updateValue="NA"` and `mask` for `updateValue='!NA"`

```

library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)[1:3,]

f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
r[10:30,] <- NA

# updateValue = all
z <- rasterize(v, r, 500, update=T)

# updateValue = 'NA'
a <- cover(r, z)

# updateValue = '!NA'
b <- mask(z, r)
```
