### ISSUE TITLE
tmp files not compressed

### ISSUE THREAD

**Issue by LDalby** [rspatial/terra#559]
I'm often struggling with my disk filling up with temporary files. I do work with fairly large high res raster so they do take up some space. Compression is very effective though. However it seems like the temporary tif files generated when computing on them are written uncompressed. The default in `writeRaster` is stated to be `compression=LZW`. This is the case when writing using `writeRaster`, but it does not appear to be default when temporary files are written. 

Was the temporary files not supposed to also be written compressed?

**Comment by rhijmans** [comment]
> Was the temporary files not supposed to also be written compressed?

It was not, for better performance. But a full disk is worse performance. I may add an option to not compress temp files.

When working with very large files, I generally take more control and name intermediate files (that I cannot avoid) and then delete them when no longer needed.

**Comment by LDalby** [comment]
Thanks! 
Yes, making compression optional is probably a good idea.

**Comment by DavorJ** [comment]
I have been looking at your fix (https://github.com/rspatial/terra/commit/9aa57831f5775c40d6cc7ebf7b1388d1a2d02d26) and wondering how to set a custom default temp file compression level, bypassing the terra default `COMPRESS=LZW`.

After running `terra::terraOptions()` which will setup the package-internal `.terra_environment$options@pntr` one can then inject custom options like `assign("gdal_options", envir = terra:::.terra_environment$options@pntr, value = c("COMPRESS=ZSTD", "ZSTD_LEVEL=22"))`.

In this case, temporary files will be saved using `ZSTD` with highest (very slow) compression. I don't think there is a "less hackish" way to do this.

A quick & dirty comparison in speed and temporary GeoTIFF size: InMemory: 15sec (~10Gb), LZW: 38sec (1411Mb), ZSTD@5: 29sec (992Mb), ZSTD@9: 48sec (986Mb), ZSTD@22: 446sec (852Mb). May be interesting if slow disks are a bottleneck.
