### ISSUE TITLE
How to ignore values outside the mask when calculating `distance`

### ISSUE THREAD

**Issue by bniebuhr** [rspatial/terra#560]
Hi,

I am calculating the distance from non-forest cells to the closest forest cell in a raster of forests in a municipality. Below is the code to reproduce it.

```r
# packages
library(dplyr)
library(sf)
library(terra)
library(geobr) # for downloading vector of the study area

# options
options(timeout = 600)

# download raster
download.file(url = "https://storage.googleapis.com/mapbiomas-public/brasil/collection-6/lclu/coverage/brasil_coverage_2020.tif",
              destfile = "brasil_coverage_2020.tif", mode = "wb")

# import raster
mapbiomas <- terra::rast("brasil_coverage_2020.tif")
mapbiomas

# rio claro municipality - vector
rc <- geobr::read_municipality(code_muni = 3543907, year = 2020) %>%
    sf::st_transform(4326) %>%
    terra::vect()
rc

# plot
# plot(mapbiomas, col = viridis::viridis(20))
# plot(rc, col = "red", add = TRUE)

# crop and mask
mapbiomas_rc <- mapbiomas %>%
    terra::crop(rc) %>%
    terra::mask(rc)

# forest
forest <- mapbiomas_rc == 3
plot(forest)
```

![image](https://user-images.githubusercontent.com/8031905/156341121-801d76ea-a729-4fdb-870d-046c64eabf03.png)

Here is the plot of the forest areas (class 3 in the original land use map, reclassified as 1) against non-forest areas (reclassified as 0) after masking out all pixels outside the municipality I am interested in (these pixels are now NA outside the mask). I am interested in calculating the distance of all non-forest pixels (class 0) to the nearest forest pixel (class 1). To do so, I need to transform the class 0 into NA, since the `terra::distance()` function works like this.

```r
# forest na
forest_na <- forest
values(forest_na) <- ifelse(values(forest_na) == 1, 1, NA)
plot(forest_na)
```

![image](https://user-images.githubusercontent.com/8031905/156340268-de67dac3-c59e-4bc9-add1-7f37c8917589.png)

The last command produces a map with 1 for forest areas and NA for non-forest areas. There is no difference, however, between the NA cells that represent non-forest within the municipality limits (that were 0 in the first map) and the NA cells masked out - so that `terra::distance()` tries to calculate the distance from all those NA pixels (even those masked out) to the closest non-NULL and this takes ages - it di not run in my personal computer.

Is there a way to really mask out - i.e. disconsider these NA pixels that were masked out in the calculation - so that the procedure is performed only for NA cells within the mask?
In any case, it seems this process is time consuming, at least for a landscape of this size - 1144 rows per 1126 cols.

**Comment by bniebuhr** [comment]
Hi @DjanerEmin thanks for the suggestions. The map is not big, though, so this should not be a problem of memory, I believe.

**Comment by rhijmans** [comment]
Thank you for suggestion. It is now possible to ignore cells. 

```
library(terra)
library(geobr)
options(timeout = 600)
url = "https://storage.googleapis.com/mapbiomas-public/brasil/collection-6/lclu/coverage/brasil_coverage_2020.tif"
fname <- basename(url)
if (!file.exists(fname)) { download.file(url, fname, mode = "wb") }

mapbiomas <- terra::rast("brasil_coverage_2020.tif")
rc <- vect(geobr::read_municipality(code_muni = 3543907, year = 2020))
rc <- project(rc, "epsg:4326")

mapbiomas_rc <- mapbiomas |>  terra::crop(rc, mask=T)
forest <- mapbiomas_rc == 3

## aggregating to speed up the example
forest <- aggregate(forest, 10, "modal")

forest_na <- classify(forest, cbind(c(NA, 0), c(-99, NA)))
# note the argument -99 for the cells to be ignored
d <- distance(forest_na, -99)
dd <- mask(d, forest)
plot(dd)
```
![forest](https://user-images.githubusercontent.com/11481397/188527336-9ca1b5d5-84fe-4714-957e-82cde262ef2f.png)

- This can indeed save a lot of time; but `distance` is still much slower than it should be; so it is another goal to improve that.
- Given this change, it might make more sense to just have NA cells ignored, and the user sets the value of the cells for which the distance needs to be computed. I need to look into that to see if I can make the change without breaking existing code.

**Comment by bniebuhr** [comment]
Great, thanks, @rhijmans !
