### ISSUE TITLE
unique() drops NA values?

### ISSUE THREAD

**Issue by MatthieuStigler** [rspatial/terra#561]
I notice that the function `unique()" drop NA values? In general, it can be useful to see the full values, including the presence of masked pixels. Now one can do it with `unique(values(r))` but I assume this is left efficient than the native `unique(r)`?  Would it then be possible to have an argument in `unique` keeping those (`na.rm`?)? 

Thanks!

``` r
library(terra)
#> terra 1.5.21
r <- rast(ncols=10, nrows=10)
m <- rast(ncols=10, nrows=10)
values(r) <- rep(1:5, 20)
set.seed(1965)
x <- round(3 * runif(ncell(r)))
x[x==0] <- NA
values(m) <- x
mr <- mask(r, m)

unique(values(mr))
#>      lyr.1
#> [1,]     1
#> [2,]     2
#> [3,]     3
#> [4,]    NA
#> [5,]     4
#> [6,]     5
unique(mr)
#>   lyr.1
#> 1     1
#> 2     2
#> 3     3
#> 4     4
#> 5     5
```

<sup>Created on 2022-03-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Hi Matthieu, 

I have [added](https://github.com/rspatial/terra/commit/88dd41e5468c8012818ac5391b5a51d427b5bdc2) an argument `na.rm` and tentatively set it to `TRUE` --- this changes the default behavior and I may need to switch this back if it breaks things in other packages. 

unique(mr)
#  lyr.1
#1     1
#2     2
#3     3
#4     4
#5     5

unique(mr, na.rm=T)
>  lyr.1
>1     1
>2     2
>3     3
>4     4
>5     5

**Comment by MatthieuStigler** [comment]
great, thanks Robert!

**Comment by DavorJ** [comment]
Don't want to reopen this, just to add some observations that are not clear from the documentation:

1. If `as.raster = TRUE` then `na.rm = TRUE` has no effect.
2. If `x` has multiple layers and `incomparables = FALSE` (default), then only the combination of layers that have NAs in every layer will be excluded with `na.rm = TRUE`. Example building on the given example:

```r
# terra 1.8-70
mr2 <- mr
mr2[5, 5] <- NA

terra::unique(c(mr, mr2), na.rm = TRUE)
#  lyr.1 lyr.1
#2     1     1
#3     2     2
#4     3     3
#5     4     4
#6     5   NaN
#7     5     5

terra::unique(c(mr, mr2), na.rm = FALSE)
#  lyr.1 lyr.1
#1   NaN   NaN
#2     1     1
#3     2     2
#4     3     3
#5     4     4
#6     5   NaN
#7     5     5
```

Note: it could maybe be sensible to make `na.rm = TRUE` discard layer combinations that have at least one NA in them. This would then also have an effect when `as.raster = TRUE`: in that case there would be no classes with partial NAs in it.
