### ISSUE TITLE
Changing order of dims when saving nc files

### ISSUE THREAD

**Issue by BackwoodsBoomtree** [rspatial/terra#564]
I am wondering how to change the order of the XYZ dimensions when saving to NC with writeCDF. For instance, saving it as Z,Y,X or Y, X, Z or X, Y, Z - or for instance saving it as lat,lon,time or lon,lat,time, etc. I can get the data in the correct shape I need using trans(), flip(), and rotate(), but when writing out to CDF it assumes a fixed order.

**Comment by rhijmans** [comment]
That is not supported. It would be a lot of work to implement that option. It does not seem important enough to work on that. If you want that level of control you could use the `ncdf` package. Or argue why it would be important for many users.
