### ISSUE TITLE
terra::distance with signature 'SpatRaster,SpatVector' does not work properly

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#567]
I used `terra::distance` before, and it worked fine. It seems that this is no longer the case, at least for the `SpatRaster`,`SpatVector` signature. In the example below (the one given in the help page), the distance between the raster cells and the points is calculated for only one of the 3 points. Maybe something has changed? Or did I miss something?

```
library(terra)
#>terra 1.5.23

r <- rast(ncols=36, nrows=18, crs="+proj=utm +zone=1 +datum=WGS84")
r[500] <- 1
p1 <- vect(rbind(c(0,0), c(90,30), c(-90,-30)), crs="+proj=longlat +datum=WGS84")
dp <- distance(r, p1)
plot(dp)
plot(p1,add=T)
```
![Image1](https://user-images.githubusercontent.com/42430070/157526121-d0d978b4-a883-4c80-a452-2331ebbbe92a.png)

It should give a similar result to the former raster::distanceFromPoints, which works correctly, as shown below :
```
library(raster)
#>Loading required package: sp
#>Attaching package: ‘raster’

#>The following objects are masked from ‘package:terra’:
#>    direction, gridDistance

#>Warning messages:
#>1: multiple methods tables found for ‘direction’ 
#>2: multiple methods tables found for ‘gridDistance’ 

dp2 <- distanceFromPoints(raster(r),as(p1,"Spatial"))
plot(dp2)
plot(p1,add=T)
```
![Image2](https://user-images.githubusercontent.com/42430070/157526655-f9b70401-f699-410f-880a-1c101f0421c6.png)

**Comment by rhijmans** [comment]
Thanks, the main issue here was the two different CRSs: utm and longlat. You now get an error message with this example:

`Error: [distance] CRS does not match` 

And it seems to work well if the CRSs are matched.

**Comment by jldupouey** [comment]
Thanks, it works fine now and the error message is handy. I just made this error again and the message allowed me to correct it immediately. 
But would it be something possible to add support for sf vector layer input in the distance function, at least for the signature 'SpatRaster, SpatVector'?
