### ISSUE TITLE
makeTiles(): Error: [] number of rows and/or columns do not match

### ISSUE THREAD

**Issue by DavidDHofmann** [rspatial/terra#568]
I'm experiencing a pretty strange issue using the `makeTiles()` function. I used the `sen2r` package to download several Sentinel 2 files that I now need to process. For this, I'm using the `makeTiles()` function to split pairs of Sentinel 2 vrts into multiple tiles. Each pair of vrts contains (1) Sentinel 2 reflectance bands and (2) an associated quality band (or mask). Because in some cases the quality band has a different resolution than the reflectance bands, I'm running a check with the `compareGeom()` function and disaggregate the quality band if needed. Oddly, this step triggers an error message when running the `makeTiles()` function on the reflectance bands: _Error: [] number of rows and/or columns do not match_. What's even more strange is that the error usually disappears when calling `makeTiles()` again.

Below is a reproducible example of the error (Sentinel 2 file here: https://drive.switch.ch/index.php/s/s8UvGlieBWbPRr9). Removing the line `same <- compareGeom()` resolves the issue, yet I do not understand why. Anyways, I can avoid the error by comparing resolutions using `all(res(r) == res(m))`.

```r
# Load packages
library(sen2r)
library(terra)

# Link to file
file <- "S2A_MSIL2A_20151218T082342_N0201_R121_T34KGD_20151218T084413.SAFE"

# Prepare vrts
band <- s2_translate(file, tempdir())
mask <- s2_translate(file, prod_type = "SCL", outdir = tempdir())

# Load vrts
r <- rast(band)
m <- rast(mask)

# Make sure the mask has the same resolution as the bands
same <- compareGeom(r, m, stopOnError = F)
if (!same) {
  m <- disagg(m, fact = 2)
}

# Prepare grid according to which we want to split our rasters
t <- rast(nrows = 5, ncols = 5, extent = ext(r), crs = crs(r))

# Split rasters into multiple tiles
tiled_band <- makeTiles(r, t, tempfile(fileext = ".tif"), overwrite = T)   # Throws error
tiled_mask <- makeTiles(m, t, tempfile(fileext = ".tif"), overwrite = T)

```

**Comment by rhijmans** [comment]
Thanks, the problem was that 

`compareGeom(r, m, stopOnError = FALSE)` did not remove the error messages stored in `r`.
