### ISSUE TITLE
Table mapping raster functions to terra functions?

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#57]
Does a Table mapping raster functions to terra functions exist? This would facilitate transitioning.
If this table does not exist, perhaps it could be set as a collaborative document so that users fill it
and somebody orders and structures it from time to time.
I would follow the order in the "Overview of the functions in the raster package" document.

**Comment by rhijmans** [comment]
Did you see the tables in `?terra`. Is that sufficient?

**Comment by aloboa** [comment]
oops!
