### ISSUE TITLE
R crashes when a second raster is added to an existing geopackage

### ISSUE THREAD

**Issue by sgvignali** [rspatial/terra#571]
This is something similar to #300 but using vector layers instead.

![r-crashes](https://user-images.githubusercontent.com/22011122/158184886-324ae417-fcba-4c1a-918e-2feef67a0d2e.png)

Here is a minimal example to reproduce the problem:

```
x <- data.frame(long = rnorm(10), lat = rnorm(10))
  |> as.matrix()

terra::vect(x, type = "lines", crs = "epsg:4326") |> 
  terra::writeVector(filename = "test.gpkg", filetype = "GPKG",
                     layer = "line")

terra::vect(x, type = "points", crs = "epsg:4326") |> 
  terra::writeVector(filename = "test.gpkg", filetype = "GPKG",
                     layer = "points", insert = TRUE)
```

Even if R crashes, the geopackage is correctly created.

This is my session info:
```
sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_CH.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C        
![r-crashes](https://user-images.githubusercontent.com/22011122/158184856-5efa2bb1-729c-401a-b5fd-0004f42dd757.png)
          LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2    renv_0.15.4   
```

Thanks and all the best

**Comment by rhijmans** [comment]
This works fine for me on Ubuntu and Windows. What version of `terra` are you using?

**Comment by sgvignali** [comment]
Strange, I think I have the last version:

```
packageVersion("terra")
[1] ‘1.5.21’
```

What could it be then, any idea?

**Comment by rhijmans** [comment]
Then it is probably because of an older version of GDAL. For me it works with 

```
gdal()
#[1] "3.4.0"
```

But crashes with 

```
gdal()
#[1] "2.2.3"
```

**Comment by sgvignali** [comment]
Thank you, indeed I had gdal version 2.2.3.
It crashes also with version 2.4.2

Now I've installed version 3.4.0 and all works fine. Maybe it is worth to update the system requirements in the DESCRIPTION file.

**Comment by rhijmans** [comment]
I won't change the system requirements for one feature. But with your example you now get:

`Error: [writeVector] GDAL version 3 required for inserting layers into an existing file`

**Comment by sgvignali** [comment]
Ok, thank you for adding the error message!
