### ISSUE TITLE
Warnings when compiling with intel cpp compiler

### ISSUE THREAD

**Issue by gareth-d-ga** [rspatial/terra#573]
In a few locations the terra c++ code re-uses a loop iteration variable 'i' within a nested loop, such as [at this line of the inner loop](https://github.com/rspatial/terra/blob/f3ee59a0ede69c0efe0f1a70e5aee438b30f6b82/src/arith.cpp#L704). 

I understand [this is allowed](https://stackoverflow.com/questions/2393458/why-does-using-the-same-count-variable-name-in-nested-for-loops-work) in the c++ standard (the inner loop masks the outer loop variable). 

But it leads to the following compiler warnings with intel, which flag the relevant file(line) :
```
arith.cpp(711): warning #823: reference is to variable "i" (declared at line 698) -- under old for-init scoping rules it would have been variable "i" (declared at line 704)
  		if (!out.writeBlock(d, i)) return out;

gdal_algs.cpp(523): warning #823: reference is to variable "i" (declared at line 472) -- under old for-init scoping rules it would have been variable "i" (declared at line 483)
  		if (!out.writeBlock(v, i)) return out;

raster_methods.cpp(1892): warning #823: reference is to variable "i" (declared at line 1873) -- under old for-init scoping rules it would have been variable "i" (declared at line 1878)
  			if (!out.writeBlock(v, i)) return out;

spatSources.cpp(424): warning #823: reference is to variable "i" (declared at line 416) -- under old for-init scoping rules it would have been variable "i" (declared at line 423)
              slyr = { lyrs[i] - offset } ;

```
Given the potential for confusion, you could consider using a different loop variable in the inner loop.

**Comment by rhijmans** [comment]
Thanks, I agree that it is better to have distinct loop variables, and nicer not to have warnings.
