### ISSUE TITLE
more explanation for the error caused by test$nl < 1

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/terra#579]
https://github.com/rspatial/terra/blob/86707840625f71bf5cb8757914107e56bb005b1d/R/lapp.R#L148

There are several places where some variation of 
     if (test$nl < 1) error("lapp", "cannot use 'fun'")
is used. Would it be possible to add a bit more description of what might be causing this?

**Comment by rhijmans** [comment]
not a whole lot I can easily say, but I hope it it is a bit more clear now.
