### ISSUE TITLE
app function crashing R for large raster

### ISSUE THREAD

**Issue by laurencehawker** [rspatial/terra#58]
I am trying to multiple all values in a raster layer by a numerical constant. As I am working with a range of raster sizes (as large as 50k x 50k pixels), I want to use a memory safe function. Thus I planned to use  terra::app in much the same way as raster::calc.
On my local Windows machine (16GB RAM), the terra::app function crashes R when I test on a raster of 1500 x 1500 pixels. It works on smaller rasters (1000*1000 example below). I also tried to workaround with terra::init and terra::lapp (also fails for larger rasters).
Perhaps I am using the functions incorrectly but thought I would report just in case.
````
library(raster)
library(terra)
pgrid <- rast(ncol=1000, nrow=1000)
set.seed(1)
values(pgrid) <- sample(ncell(pgrid))

valmulti <- 10
funurb <- function(x) { x * valmulti }
funmulti <- function(x,y){return(x*y)} 
ops <- list(gdal=c("COMPRESS=DEFLATE"))

mem_unsafe <- funurb(pgrid)
z1 <- terra::app(pgrid, fun=funurb, filename = 'test.tif', overwrite=TRUE, wopt=ops)

initras <- terra::init(pgrid, fun=valmulti,filename = 'initras.tif', overwrite=TRUE, wopt=ops)

z2 <- c(pgrid, initras) 
res <- terra::lapp(z2, fun=funmulti, filename = 'resras.tif', overwrite=TRUE, wopt=ops)


###Sessioninfo
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] microbenchmark_1.4-7 terra_0.7-11         raster_3.3-7        
[4] sp_1.4-2            

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     mvtnorm_1.1-1    lattice_0.20-41  codetools_0.2-16
 [5] zoo_1.8-8        MASS_7.3-51.6    grid_4.0.2       magrittr_1.5    
 [9] stringi_1.4.6    multcomp_1.4-13  pryr_0.1.4       Matrix_1.2-18   
[13] sandwich_2.5-1   TH.data_1.0-10   splines_4.0.2    tools_4.0.2     
[17] stringr_1.4.0    tinytex_0.24     survival_3.2-3   xfun_0.15       
[21] compiler_4.0.2

**Comment by rhijmans** [comment]
In principle all functions are memory-safe, including the basic algebraic functions. I have used terra with rasters of 128032 rows and 150533 columns. You should be able to do:  

`x <- pgrid * 10`

(and the other approaches as well). So perhaps you found a bug. I simplified your code a bit (the micro-benchmark stuff made it hard to read and does not tell us anything about why something may crash; and you do not provide `pop_per_urb_cell`). 

This may be a corner-case with the RAM available. Which version of `terra` are you using? With the development version you can add an option `verbose=TRUE` ; as in `list(gdal=c("COMPRESS=DEFLATE"), verbose=TRUE)` and you check the estimated RAM available and needed with this `terra:::.mem_info(pgrid)`. It would be great if you can report that.

**Comment by laurencehawker** [comment]
Thank you for tidying up the example (I corrected the pop_per-urb_cell) which should have been valmulti.
I was using terra 0.7.11 (but have now upgraded to the development version 0.7.12)

````
terra:::.mem_info(pgrid) (changed to a 5000 x 5000 SpatRaster)

----------------------
available (GB): 1.77
allowed (60%) : 1.06
needed        : 0.02
----------------------
nr chunks     : 4

Basic Algebraic function
x2 <- pgrid * 10 #<1 second

valmulti <- 10
funurb <- function(x) { x * valmulti }
ops <- list(gdal=c("COMPRESS=DEFLATE"),verbose=TRUE)
z1 <- terra::app(pgrid, fun=funurb, filename = 'test.tif', overwrite=TRUE, wopt=ops) #Runs but took 3 minutes
blocks: 4

For the biggest SpatRaster in my analysis (66954 rows 68614 columns)
----------------------
available (GB): 0.76
allowed (60%) : 0.46
needed        : 0.28
----------------------
nr chunks     : 75

R crashes with the error for x2 <- pgrid * 10 :
ERROR 3: Free disk space available is 15211356160 bytes, whereas 18375927024 are at least necessary. 
You can disable this check by defining the CHECK_DISK_FREE_SPACE configuration option to false.

Here I'm a bit puzzled as according to terra:::.mem_info() the needed memory is within the allowed so 
there is no need to write to a tmpdir? I can run when I free up some space on my harddrive 
but sure enough 18GB of files are created. T
his seems a lot considering the input file is 61MB. I guess CHECK_DISK_FREE_SPACE comes from gdal?

The third terra::init option crashes R for me (for 5000 x 5000 SpatRaster).

**Comment by rhijmans** [comment]
Thanks. I now also see problems with rasters with 65534 rows/columns or more; due to an integer overflow. Fixing it...

**Comment by rhijmans** [comment]
I believe this is now fixed,  I get 

```
library(terra)
terraOptions(verbose=TRUE)
r <- rast(nrow=66954, ncol=68614)
terra:::.mem_info(r, 4)

#----------------------
#available (GB): 52.79
#allowed (60%) : 31.67
#needed        : 136.91
#----------------------
#proc in memory: FALSE
#nr chunks     : 7

x <- init(r, "cell", overwrite=T)
#filename       RtmpKwNq9g/spat_BLAv7bpmVfrPyr1.tif
#disk available 334 GB
#disk needed    34 GB
#blocks: 7

y <- x * 10
#filename         RtmpKwNq9g/spat_XRcNk1wxAbcZJDl.tif
#disk available 317 GB
#disk needed    34 GB
#blocks: 7

```

CHECK_DISK_FREE_SPACE indeed comes from gdal. `terra` now checks for the available disk space, and should stop cleanly if there is not enough.  If your default temp directory is relatively small, you can set it to another place with `terraOptions(tempdir="a path")`

The reported needed memory was wrong  because an integer overflow.

**Comment by rhijmans** [comment]
You also note that `app` is slow. It is expected to be slower because it uses `apply`, when you provide your own formula and not, say, "sum" or "min"; whereas the direct arithmetic approach is all in C. But it seems that it is much slower than need be; I need to look at that at some point.

**Comment by laurencehawker** [comment]
Thanks for the fixes. I have not been able to test it as there is an expected } in terraOptions.Rd line 35 (see below) when installing the development version (looks like from your very latest commit)
** R
** inst
** byte-compile and prepare package for lazy loading
in method for 'coerce' with signature '"sf","SpatVector"': no definition for class "sf"
in method for 'show' with signature '"Rcpp_SpatCategories"': no definition for class "Rcpp_SpatCategories"
in method for 'show' with signature '"Rcpp_SpatDataFrame"': no definition for class "Rcpp_SpatDataFrame"
in method for 'vect' with signature 'x="sf"': no definition for class "sf"
** help
Error : (converted from warning) C:/Users/*****/AppData/Local/Temp/RtmpW8rVyP/R.INSTALL15e45bf5418b/terra/man/terraOptions.Rd:35: unexpected '}'
ERROR: installing Rd objects failed for package 'terra'

**Comment by rhijmans** [comment]
Oops, fixed.
