### ISSUE TITLE
spatSample cannot return cells when there is a categorical raster

### ISSUE THREAD

**Issue by AndreMBellve** [rspatial/terra#580]
I wrote some code awhile ago to sample these rasters randomly using `spatSample `and it had previously worked (although I am not sure what version I had (sorry!). I revisited this code and tried to get it to run but I was getting the following error from `spatSample`:
```
 Error in `[[<-.data.frame`(`*tmp*`, i, value = integer(0)) : 
  replacement has 0 rows, data has 1000
```
This is a reproducible example of the problem using two rasters (the elev.tif in the terra package, and a categorised version of it).
```
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
rCmat <- matrix(c(0, 200, 1,
                  201, 400, 2,
                  401, 550, 3), ncol = 3, byrow = T)

rC <- classify(r, rCmat, include.lowest=TRUE, others = NaN)
levels(rC) <- data.frame(ID = c(1:3), category = c("L", "M", "H"))
rAll <- c(r, rC)

spatSample(rAll, size = 1000, na.rm = TRUE, cells = TRUE)
```
If I set `cells = FALSE` the call returns a dataframe with the values as expected. I have tried updating to the stable release on CRAN, as well as trying the GitHub version with no success. The issue seems to be stemming from the fact that I have a categorical raster because if I remove this, then the cell call doesn't seem to have any problems.

Here is my session info in case it helps:

R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] viridis_0.6.2          viridisLite_0.4.0      doSNOW_1.0.20         
 [4] snow_0.4-4             iterators_1.0.14       foreach_1.5.2         
 [7] ecospat_3.2.1          gbm_2.1.8              ape_5.6-2             
[10] ade4_1.7-18            caret_6.0-91           ggplot2_3.3.5         
[13] PresenceAbsence_1.1.10 dismo_1.3-5            blockCV_2.1.4         
[16] rasterVis_0.51.2       lattice_0.20-45        terra_1.5-24          
[19] raster_3.5-15          sp_1.4-6               sf_1.0-7              
[22] stringr_1.4.0          janitor_2.1.0          tidyr_1.2.0           
[25] dplyr_1.0.8

**Comment by rhijmans** [comment]
Thank you. I believe this now works again. I have added support for categories in steps, and sometimes error creep in.

**Comment by AndreMBellve** [comment]
Hi Robert, I just tried re-installing the development version from here (1.5-24) and running the code again but it has hit the same error. Has your fix been pushed or am I doing something wrong?
