### ISSUE TITLE
Install failure on GDAL 2.2.4 and c++ 11.2.1

### ISSUE THREAD

**Issue by rsbivand** [rspatial/terra#581]
I cannot check **terra** HEAD including the changes to raster files on PROJ 5.2.0 and GDAL 2.2.4:
[00install.out.txt](https://github.com/rspatial/terra/files/8332210/00install.out.txt)

**Comment by rhijmans** [comment]
Perhaps fixed now? I added `#include <stdexcept>`

**Comment by rsbivand** [comment]
Thanks! Installs with your commit. One test error because for  GDAL < 2.3, RRASTER cannot be written, PR https://github.com/rspatial/terra/pull/582
