### ISSUE TITLE
geometry columns now disappear from table when converting to vect()

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#586]
Hello,
If I recall correctly, this used to happen with 'sp', then with 'terra' it didn't happen at first, but with more recent versions it does. When we convert a dataframe of point coordinates to a SpatVector of points, the columns that we specify as geometry (i.e., the coordinates) are no longer included in the attribute table of the points map:

```
# (my df was originally imported from a .csv, but I used 'dput' here)

my_coords <- structure(list(species = c("Canis simensis", "Canis simensis", "Canis simensis", "Canis simensis", "Canis simensis"), longitude = c(39.601177, 39.963869, 39.943939, 39.925582, 39.984023), latitude = c(6.830201, 6.800052, 6.817087, 6.937708, 6.966574), country = c("Ethiopia", "Ethiopia", "Ethiopia", "Ethiopia", "Ethiopia")), row.names = c(NA, 5L), class = "data.frame")

my_coords
#          species longitude latitude  country
# 1 Canis simensis  39.60118 6.830201 Ethiopia
# 2 Canis simensis  39.96387 6.800052 Ethiopia
# 3 Canis simensis  39.94394 6.817087 Ethiopia
# 4 Canis simensis  39.92558 6.937708 Ethiopia
# 5 Canis simensis  39.98402 6.966574 Ethiopia

my_points <- vect(my_coords, geom = c("longitude", "latitude"))

head(my_points)
#          species  country
# 1 Canis simensis Ethiopia
# 2 Canis simensis Ethiopia
# 3 Canis simensis Ethiopia
# 4 Canis simensis Ethiopia
# 5 Canis simensis Ethiopia

```
Is there a reason for the coordinates to be removed from the attribute table? We often need to add columns to this table based on spatial operations, and then save the updated table again as .csv, but we need the original coordinate columns to remain there. I know I can add them with something like:

`values(my_points) <- data.frame(values(my_points), crds(my_points))`

... but this is quite a bit of extra code (across all scripts), and the coordinate columns will now be named "x" and "y" instead of the original names they had in the original dataframe ("longitude", "lon", "decimalLongitude", etc.), causing problems downstream, or requiring yet more code to convert back to their original names.

If this is desired behaviour, could you include an option to keep these columns as an additional argument to `vect()`?

Cheers!

**Comment by kadyb** [comment]
> Is there a reason for the coordinates to be removed from the attribute table?

I asked Robert to remove the coordinates from the attributes by default, because in my projects they are always duplicate, so it makes no sense to keep them (https://github.com/rspatial/terra/issues/460#issuecomment-1003378145).

There is also a way to write SpatVector as csv with geometry, but the column names are also changed.

```r
writeVector(my_points, "my_points.csv", filetype = "CSV", options = "GEOMETRY=AS_XY")
```

**Comment by rhijmans** [comment]
I believe this is the desired behavior --- considering that I would like the behavior to be the same for points, lines and polygons. 

I have added argument `keepgeom=FALSE` to the `vect<data.frame>` method, such that you can do 

```
my_points <- vect(my_coords, geom = c("longitude", "latitude"), keep=TRUE)
head(my_points)
#         species longitude latitude  country
#1 Canis simensis  39.60118 6.830201 Ethiopia
#2 Canis simensis  39.96387 6.800052 Ethiopia
#3 Canis simensis  39.94394 6.817087 Ethiopia
#4 Canis simensis  39.92558 6.937708 Ethiopia
#5 Canis simensis  39.98402 6.966574 Ethiopia
``` 

You can also do 

```
v <- as.data.frame(my_points, geom="XY")
v
#         species  country        x        y
#1 Canis simensis Ethiopia 39.60118 6.830201
#2 Canis simensis Ethiopia 39.96387 6.800052
#3 Canis simensis Ethiopia 39.94394 6.817087
#4 Canis simensis Ethiopia 39.92558 6.937708
#5 Canis simensis Ethiopia 39.98402 6.966574
```
 
But that does change the names.
