### ISSUE TITLE
`simplifyGeom` with topology preserve

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#587]
Hi,
`terra::simplifyGeom` is better than `rgeos::gSimplify` in that it preserves the attribute table, but it's worse in that it doesn't have an option for preserving topology. Any chance this could be included?
Cheers!

**Comment by rhijmans** [comment]
In fact it is the other way around. That is, the option is hard-coded, because I could not think of a situation where I would *not* want that. Am I wrong? See:

```
> getMethod("simplifyGeom", "SpatVector")
Method Definition:

function (x, ...) 
{
    .local <- function (x, tolerance = 0.1) 
    {
        preserveTopology <- TRUE
        x@ptr <- x@ptr$simplify(tolerance, preserveTopology)
        messages(x, "simplifyGeom")
    }
    .local(x, ...)
}
```

**Comment by AMBarbosa** [comment]
Excellent point ;) I actually meant that `rgeos::gSimplify` (with `topologyPreserve = TRUE`) apparently prevents adjacent polygons from overlapping. But I notice now that it also does some strange things to some of the polygons (e.g. bottom right in the image below):
```
v <- vect(system.file("ex/lux.shp", package="terra"))

v1 <- terra::simplifyGeom(v, tolerance = 0.2)
v2 <- rgeos::gSimplify(as(v, "Spatial"), tol = 0.2, topologyPreserve = TRUE)

par(mfrow = c(1, 2))
plot(v1, main = "simplifyGeom")
plot(v, border = "darkgrey", add = TRUE)
plot(v2, main = "gSimplify")
plot(v, border = "darkgrey", add = TRUE)
```
![image](https://user-images.githubusercontent.com/12085508/161560381-e94146ad-3065-4552-a242-a134da289306.png)

And a closer look reveals there are still some overlaps there as well:
```
par(mfrow = c(1, 1))
plot(v2, main = "gSimplify", xlim = c(6, 6.2), ylim = c(49.5, 49.8), col = 1:length(v2), alpha = 0.5)
plot(v, border = "darkgrey", add = TRUE)
```
![image](https://user-images.githubusercontent.com/12085508/161563341-2b7965bd-0a99-415b-a406-1c135da6b347.png)

So it seems we're actually better off with `terra::simplifyGeom` overall :)

**Comment by rhijmans** [comment]
Thanks. I have also added argument `preserveTopology=TRUE` so that you can set it to FALSE for when that is useful (e.g. remove  small polygons)
