### ISSUE TITLE
terra::project altering minimum values and raster names post projection.

### ISSUE THREAD

**Issue by AndreMBellve** [rspatial/terra#59]
I am reading a collection of rasters in using `rast()` and subsequently trying to alter their projection to match another model raster. The projection appears to be working (although it takes considerable amounts of time ~3 hours for an area the size of New Zealand), but a couple of issues arise post-projection:

1. any of the rasters in the collection that were numeric seemed to have the value  -3.4 × e+38  introduced in place of the NA's. I can use classify to remove these on a case by case basis but I was wondering why it happens and if there is a way to avoid this coercion, and;

2.   the names of all my rasters are being altered into things like "lyr.1" or long strings of seemingly random characters when I feed project a collection of rasters. I would provide an example of the latter, but it takes several hours for project to run over these rasters.

I am converting rasters from NZGD49 to NZGD2000 using the following work flow for an example of reprojecting one raster:

```
#Listing file names in raster folder
rasterFiles <- list.files("./data/Raster/Contemporary", pattern = ".tif", full.names =  TRUE) 

#Reading in all rasters - I subset this to a single raster later.
predRast <- rast(rasterFiles)

#Raster to be converted (NZGD49) 
predRast[[1]]

class       : SpatRaster 
dimensions  : 14900, 10200, 1  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : 1990000, 3010000, 5300000, 6790000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +towgs84=59.47,-5.04,187.44,0.47,-0.1,1.024,-4.59929999996334 +units=m +no_defs 
data source : C:/Users/abel122/Dropbox (Uni of Auckland)/Andre_Bellve_PhD/Uni/André (PhD)/fossilSeabirds/data/Raster/Contemporary/aspect_eastness.tif 
names       : aspect_eastness 
min values  :              -1 
max values  :               1 

#Model raster with NZGD2000 projection  (slope raster downloaded from the LRIS portal)
modelRast <- rast("./data/Raster/modelCRS/Slope.tif")
modelRast

class       : SpatRaster 
dimensions  : 59684, 40827, 1  (nrow, ncol, nlyr)
resolution  : 25, 25  (x, y)
extent      : 1079625, 2100300, 4737300, 6229400  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
data source : ./data/Raster/modelCRS/Slope.tif 
names       : Slope 

#Altering projection of first two rasters to match that of the model raster
test <- terra::project(predRast[[1]], terra::crs(modelRast)) # Same thing happens when I set the method = 'near'
test

class       : SpatRaster 
dimensions  : 14952, 10228, 1  (nrow, ncol, nlyr)
resolution  : 99.79131, 99.79131  (x, y)
extent      : 1079648, 2100314, 4737317, 6229396  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
data source : memory 
**names       :    lyr.1 
min values  : -3.4e+38** 
max values  :        1 
```

Here is my session info:

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
[3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] viridis_0.5.1       viridisLite_0.3.0   dismo_1.1-4         blockCV_2.1.1      
 [5] rasterVis_0.47      latticeExtra_0.6-29 lattice_0.20-41     raster_3.1-5       
 [9] sp_1.4-2            terra_0.6-9         sf_0.9-3            forcats_0.5.0      
[13] stringr_1.4.0       dplyr_1.0.0         purrr_0.3.4         readr_1.3.1        
[17] tidyr_1.1.0         tibble_3.0.1        ggplot2_3.3.0       tidyverse_1.3.0  
```

**Comment by rhijmans** [comment]
Thank you for your report. You are using a very old (relative to the package's age and development rate) version of terra (`terra_0.6-9`) --- can you please try with at least the current CRAN version or (even better) the github version?

**Comment by AndreMBellve** [comment]
Thank you for the rapid reply! Updating to 0.7-12 has resolved the worst of the (admittedly minor) issues; however, the function still changes the name of all the rasters in my SpatRast object, relabelling them as  Spa_1, Spa_2, ..., Spa_n. I have corrected this for my work with `names(test) <- names(predRast)`, but figured I would mention it. Thank you for the help!

**Comment by rhijmans** [comment]
Both issues are important to me. I did not spot the names problem because it only happens with large files. I believe I have now fixed that as illustrated (with a small example file by forcing it to disk) below --- this did not keep the names before; but please let me know if you still encounter this problem.  Note that not all file formats can store layer names (but geotiff can). I also note that projecting large rasters like yours is rather slow; and I need to look into that in the future.

```
library(terra)
terraOptions(todisk=TRUE)
f <- system.file("ex/test.tif", package="terra")
r <- rast(f)
r <- c(r, r*3)
names(r) = c("blue", "jay")
x <- project(r, crs(rast()))
names(x)
```
