### ISSUE TITLE
No res argument in terra::project

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#596]
Hi, I was wondering if there's a plan to add the the `res` argument to `terra::project` like in `raster::projectRaster`?

For example, below `terra` automatically projects the raster to be about 52 m cell size which seems to be a compromise between the latitudinal and longitudinal resolution (about 82 m and 41 m respectively). However, sometimes it's just nice to have a clean number (e.g. 50 m) or be a bit more conservative and just do something towards the coarser end (e.g. 80 m). 

```
library(terra)

r<- rast(nrow=2296, ncol= 4645, crs="EPSG:4326", xmin=211.22962962963, xmax=214.67037036693, ymin=59.64962962963,ymax=61.35037036867)

values(r)<- rnorm(ncell(r))

yres(r)*111139 #82.32519
xres(r)*111139*cos(60*pi/180) #41.16259


r_reproj<- project(r, y = "EPSG:32606", method= "bilinear")
res(r_reproj)
#51.63357 51.63357

project(r, y = "EPSG:32606", method= "bilinear", res=80)
#Error: [write] unknown option(s): res

library(raster)
r_rast<- raster(r)
r_reproj2<- projectRaster(r_rast, res = 80, crs = crs(r_reproj, proj=TRUE)) 
res(r_reproj2)
# [1] 80 80
```

**Comment by rhijmans** [comment]
I can of course that, but this omission was not an oversight. I want to discourage the approach to projecting raster data as if it were vector data (where there is one solution and the data can be back-projected to get the original data). Or even discourage projecting raster data at all (often it is done to match the CRS of vector data, but in that case the vector data should be projected instead).

To me, the canonical way to project a raster is by providing a template, such that you control the extent and resolution. In most workflows you can use an existing raster that you want your data to match. If that is not the case, you can first create a template and use it, e.g. like this: 

```
library(terra)
r <- rast(nrow=2296, ncol= 4645, crs="EPSG:4326", xmin=211, xmax=214,ymin=59,ymax=61)
values(r) <- rnorm(ncell(r))

template <- project(rast(r),  y="EPSG:32606", method= "bilinear")
res(template) <- 80

r_reproj <- project(r, template, method= "bilinear")
res(r_reproj)
#[1] 80 80
```

But if there are cases where you care about the resolution, but not about the extent, then I should not make life more difficult then it needs to be.

**Comment by ailich** [comment]
@rhijmans, thanks for the advice. I wasn't exactly sure how to create the template since I didn't know what the new extent would be and didn't realize that changing the resolution would automatically change the dimensions and extent accordingly for me. I do think it's a bit confusing though as you first need to reproject to an empty raster of unknown resolution and be aware that updating `res` will adjust the other parameters. I understand the hesitation as people sometimes project raster data instead of the vector data when they have the option, but that can still be done as long as you don't specify res users may still do it, and there is sometimes good reason to reproject raster data (e.g. you need to conduct mathematical analyses that are only valid for projected data or match the resolution of different raster data sets so that they are comparable). Also, it is also mentioned in the details section that it is preferable to project vector over raster data so users have been warned. If it's a big concern though maybe it could be more prominently displayed (e.g. towards the top of the details section or in the description of the function).

**Comment by ailich** [comment]
I may be getting a bit off topic here, but some other convenience things related to reprojecting could be adding an `origin` argument to `terra::project` so rasters can be easily aligned. Additionally perhaps having it also having `terra::project` handle `SpatExtent` objects much like how `raster` has `raster::projectExtent`. That could simplify the template creation.
For example, something like:
```
r <- rast(nrow=2296, ncol= 4645, crs="EPSG:4326", xmin=211, xmax=214,ymin=59,ymax=61, origin=0)
projected_ext<- project(ext(r), y="EPSG:32606", res=80, origin=c(0,0))
template <- rast(extent=projected_ext, crs="EPSG:32606", res=80, origin=c(0,0))
r_reproj <- project(r, template, method= "bilinear")
```
Or it could be all in one step in `terra::project` in one step like:
```
r_reproj <- project(r, y="EPSG:32606", res=80, origin=c(0,0), method= "bilinear")
```

I see the template option being optimal if you have several rasters that you need to reproject each to the same template (i.e. reusing the same object many times) whereas the second option being more useful if each needs to be reprojected to a different template as this would cut down on clutter related to intermediate variables (the templates) that are only being used once.

**Comment by rhijmans** [comment]
As suggested, you can now do:

**Comment by ailich** [comment]
Awesome. Thank you!
