### ISSUE TITLE
Projecting a map to different '+lon_0' changes axis coordinates

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#597]
Hello,
Plotting regions around longitude 180 can be cumbersome with default options -- e.g. some New Zealand polygons appear very far apart on the map:
```
countries <- geodata::world(path = tempdir())
nz <- subset(countries, countries$NAME_0 == "New Zealand")
plot(nz)  # some islands on the other side of the 180-degrees meridian
```
![image](https://user-images.githubusercontent.com/12085508/160884412-e9ceb94a-d383-4aa7-8d25-208bc21060db.png)

I can `plot(nz, xlim = c(160, 180))`, but I lose the islands on the far left of the above map; and `plot(nz, xlim = c(160, -140))` returns a blank map. I've tried projecting the map with a different centre / origin longitude, i.e. a different 'lon_0' parameter:
```
nz <- project(nz, "+proj=longlat +lat_0=0 +lon_0=160")
plot(nz)
```
![image](https://user-images.githubusercontent.com/12085508/160884805-29e1b932-37cd-4676-b75a-54d3f071cd6c.png)

The polygons now do appear together, but the x axis shows the re-centered coordinates (i.e. with 0 at meridian 160), rather than the actual longitude. Is this unexpected behaviour, or am I doing something I shouldn't?
Cheers!

**Comment by rhijmans** [comment]
I do not really know, but that seems correct to me given `+lon_0=160` 
You could run `nz <- shift(nz, 160) `  to get the normal longitudes, if you do not mind having longitudes > 180.
