### ISSUE TITLE
compile problem size_t not defined in recycle.h

### ISSUE THREAD

**Issue by KlausVigo** [rspatial/terra#6]
Dear Robert, 

I run into a problem installing `terra` on Debian GNU/Linux 9.6 (stretch) with gcc 6.3.0. 
In the file recycle.h `size_t` was not defined, so I added a header `#include <stddef.h>` 
and this fixed the problem. 
cpprefernce tells me that size_t is defined in any of these headers:
Defined in header <stddef.h>
Defined in header <stdio.h>
Defined in header <string.h>
Defined in header <time.h>

So you may have another order of compilation etc. I was installing the terra on another machine (UBUNTU) and it compiled fine out of the box.

I used already a functions of terra and it super fast, thanks for your continuous effort to improve the raster / terra package. I also like your use of the Rppp modules. I have not seen them first time in a larger package and I started to fiddle around with it too so it is nice to see and learn from a bigger project.  

Kind regards, 
Klaus

**Comment by rhijmans** [comment]
Dear Klaus, 
Thank you very much for reporting this problem and solution. Someone else later reported it for Ubuntu (where I did not see it either). I have implemented your solution. 
Also good to know that you are already using terra! 
Robert
