### ISSUE TITLE
converting SpatVector to Spatial requires 'raster' 

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#600]
We often need to convert 'terra' vector maps to "Spatial" class, as it's still required input by many packages (e.g. leaflet, adehabitatHR). However, the following fails with a slightly obscure error message if we don't run `library(raster)` too (and even if we load `library(sp)`):
```
library(terra)
v <- vect(system.file("ex/lux.shp", package="terra"))
as(v, "Spatial")
# Error in (function (classes, fdef, mtable)  : 
#  unable to find an inherited method for function ‘geom’ for signature ‘"data.frame"’
```
Could / should the method for this be provided by 'terra'? Or is it generally still good (or necessary) to have 'raster' loaded?

**Comment by rhijmans** [comment]
I think the best way to avoid this situation would be to implement this coercion in the `sp` package. I will look into that.

**Comment by rhijmans** [comment]
This is now fixed in the sense that you get a clear message:

library(terra)
terra 1.5.48
v <- system.file("ex/lux.shp", package="terra") |> vect()
s <- as(v, "Spatial")
#Error: [coerce] to coerce a SpatVector to a Spatial object you need to first load the raster package with 'library(raster)' 

library(raster)
s <- as(v, "Spatial")
```

It would be better to have the code for this in `sp`, but I do not want to pursue that at this time. Maybe later. Or maybe someone else will.

**Comment by AMBarbosa** [comment]
Great, this solves the problem of the previous error message leaving users unsure about what to do. Actually my understanding is that `sp` is now more trouble than benefit to keep maintaining, so I'd just leave it like this, at least if it's future-proof. Cheers!
