### ISSUE TITLE
Apply function to each layer of a rast object: SpatDataSet?

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#61]
We can read in ?app    
"Use a SpatDataSet to apply fun by layer."
Could you elaborate on this with an example?

**Comment by rhijmans** [comment]
Thanks, I added an example.

**Comment by aloboa** [comment]
In case the multi-layer rast object already exists,
```
r <- rast(ncols=10, nrows=10)
values(r) <- 1:ncell(r)
r <- c(r, r*2, r/2)
```
is there  way to convert to sds?
An abridged way to do:
`s <- sds(r[[1]],r[[2]],r[[3]])`
because
`s2 <- sds(r)`
is not equivalent (as far as I understand)

**Comment by rhijmans** [comment]
There is not, and I will think about one. But in this context, why would you?  With `app` you could just used the multi-layer object.  If you wanted to do the parallel mean for say every n layers, say 12 months (1:12, 13:24, 25:36) or satellite bands, you can use tapp instead.

**Comment by aloboa** [comment]
Maybe I've not interpreted the note ""Use a SpatDataSet to apply fun by layer" correctly.  What I need to do is a linear stretching for each band and I assumed I had to do it with a SpatDataSet object.

**Comment by rhijmans** [comment]
If you want to apply a function to each band, then you do no not need *app. You just apply the function to the object. stretch is but more complicated because you need to compute global values (min/max or quantiles).

```
x <- rast(system.file("ex/logo.tif", package="terra"))   
x <- x / c(1,10,100)
# tricky if data set is large
#v <- t(apply(values(x), 2, function(i) quantile(i, c(0.02, 0.98), na.rm = TRUE)))
# should always work:
v <- global(x, range)
s <- (255 * (x - v[,1]))/(v[,2] - v[,1])
s <- clamp(s, 0, 255)
```

I shall also implement `stretch` in `terra` as in `raster`

**Comment by aloboa** [comment]
Works fine and fast!
I'd be curious about knowing in which cases using a SpatDataSet is advisable.
