### ISSUE TITLE
Memory allocation error (std::bad_alloc) when running focal with expand = TRUE

### ISSUE THREAD

**Issue by nelliott13** [rspatial/terra#610]
I'm getting a memory allocation error (std::bad_alloc) when using the focal command with expand = TRUE. Removing the 'expand' argument in the following example causes the code to complete successfully.  Smaller buffer sizes work as well, but this is running on a server with 96GB of RAM, so I don't think it's actually running out of memory.

Full error message:
```
Error in x@ptr$focal(w, m, fillvalue, narm, na.only, na.omit, txtfun,  : 
  std::bad_alloc
```

Reproducible example:
```
# Load package
library(terra)

# Create raster
rst <- rast(xmin = 563865, xmax = 584415, ymin = 4396400, ymax = 4408190, 
            res = 30, crs = "EPSG:32610", vals = 1)

# Build weight matrix
fwm <- focalMat(rst, 5000, type = "circle")

# Run focal stats
fcl_rst <- focal(rst, fwm, fun = sum, na.rm = TRUE, na.policy = "omit", expand = TRUE)

```

Running on
Windows Server 2012 R2
R 4.1.2
terra 1.5-21
96 GB RAM

EDIT: typo in windows version

**Comment by rhijmans** [comment]
Thanks, this has now been fixed. I am very sorry that it took me so long.
