### ISSUE TITLE
writeRaster() "insufficient disk space" even when temp file on a 6 TB disk?

### ISSUE THREAD

**Issue by MatthieuStigler** [rspatial/terra#612]
Trying to write on disk a big raster, I face immediately the message:

> insufficient disk space (perhaps from temporary files?)

This is very similar to issue #425, which has unfortunately been closed. In that issue, it is suggested to change `terraOptions(tempdir="d:/temp")`. I did that, setting it to a disk with 6 TB free disk. It seems, however, that this is not enough, and one needs also to set the `filename` to another disk? This is surprising, as there is plenty of space even in the original disk (500 GB)? See reprex below, where:

- Setting `terraOptions(tempdir)` AND `filename` to 6 TB disk will work
- Setting only `terraOptions(tempdir)` 6 TB disk will not work, even if final disk has 500 GB >> 7 GB (final output) : _Error: [writeRaster] insufficient disk space (perhaps from temporary files?)_

Furthermore, is it possible to make the error message more informative? It would be great to be able to understand if the problem comes from the temp file or the `filename` location?

Here is a reprex (need to change location of external disk). 

Thanks!!

```
library(terra)

n_C <- 40000#170739
n_R <- 50000#55823
r <- terra::rast(nrow=n_R, ncol = n_C)
ncell(r)>.Machine$integer.max
r[] <-rep(1L:10L, size = n_C*n_R)

tmp <- paste0(tempfile(), ".tif")

writeRaster(r, tmp, overwrite=TRUE)
system(paste("ls -lh ", tmp))
rm(r)

## duplicates
files <- sapply(as.list(1:21), \(x) gsub("\\.tif", paste0("_", x, ".tif"), tmp))
res_hide <- lapply(files, \(x) file.copy(tmp, x))
list.files(dirname(tmp))

## read
r_stack <- rast(files)
tmp_2 <- gsub("\\.tif", "_merged.tif", tmp)

terraOptions(tempdir="/mnt/drive8tb/mstigler/temp/temp_terra/terra_reprex")
system("df -h /mnt/drive8tb/mstigler/temp/temp_terra/terra_reprex") # Avail: 5.2 T
system(paste("df -h ", dirname(tmp_2))) # Avail: 110 G

writeRaster(r_stack, "/mnt/drive8tb/mstigler/temp/temp_terra/terra_reprex/final_save.tif", overwrite=TRUE)
writeRaster(r_stack, tmp_2, overwrite=TRUE)

file.remove(tmp)
file.remove(tmp_2)
```

**Comment by rhijmans** [comment]
I do not think that the temp dir plays a role here. All that matters is the disk space for the output file. That still does not explain  why you get that message. Could you run this with `terraOptions(verbose=TRUE)` (or with `verbose=TRUE` as argument to `writeRaster`)? I get:


```
library(terra)
n_C <- 40000
n_R <- 50000
r <- terra::rast(nrow=n_R, ncol = n_C)
tmp <- paste0(tempfile(), ".tif")
r <- init(r, "cell", filename=tmp)

files <- sapply(as.list(1:21), \(x) gsub("\\.tif", paste0("_", x, ".tif"), tmp))
res_hide <- lapply(files, \(x) file.copy(tmp, x))

r_stack <- rast(files)
tmp_2 <- gsub("\\.tif", "_merged.tif", tmp)

terraOptions(verbose=TRUE)
writeRaster(r_stack, tmp_2, overwrite=TRUE)


#filename      : /tmp/RtmphioPJ7/file5b3a2b183212_merged.tif
#compute stats : 1, GDAL: 0, minmax: 0, approx: 1
#driver        : GTiff
#disk available: 194.9 GB
#disk needed   : 156.5 GB
#memory avail. : 47.85 GB
#memory allow. : 28.71 GB
#memory needed : 625.849 GB  (2 copies)
#in memory     : false
#block size    : 1376 rows
#n blocks      : 37
#pb            : 1
```

**Comment by MatthieuStigler** [comment]
thanks Robert for following-up on this! 

Unfortunately, using `terraOptions(verbose=TRUE)` won't help so much since the _insufficient disk space (perhaps from temporary files?)_ stop message occurs before the verbose message. I suspect you might be able to reproduce my case if you just create a 40 GB temp file on your disk, or run code twice? Do you have a larger drive to test as tempdir?

Is it possible `disk needed` looks at the file where `filename` is, not `tempdir`? In my setup, `filename` does not have indeed enough space, but `tempdir` does. My intuition was that `disk needed` referred to some temp file (the final output file is around 7GB?, so it seems here `disk needed_temp` is 156 GB but `disk needed_final` is 7GB?), so that setting just tempdir to a big enough drive would be enough? 

Pseudo code for output, verbose only works when i have both `tempdir` and `filename` to big drive:

```
terraOptions(verbose=TRUE)
> writeRaster(r_stack, tmp_2, overwrite=TRUE, verbose = TRUE)
Error: [writeRaster] insufficient disk space (perhaps from temporary files?)
> terraOptions(tempdir="/mnt/path_to_big_drive")
> writeRaster(r_stack, tmp_2, overwrite=TRUE, verbose = TRUE)
Error: [writeRaster] insufficient disk space (perhaps from temporary files?)
> writeRaster(r_stack, "/mnt/path_to_big_drive/write_temp.tif", overwrite=TRUE, verbose = TRUE)
filename      : /mnt/path_to_big_drive/write_temp.tif
compute stats : 1, GDAL: 0, minmax: 0, approx: 1
driver        : GTiff
disk available: 6093.7 GB
disk needed   : 156.5 GB
memory avail. : 157.55 GB
memory allow. : 94.53 GB
memory needed : 625.849 GB  (2 copies)
in memory     : false
block size    : 4531 rows
n blocks      : 12
pb            : 1
```
Thanks!!

**Comment by rhijmans** [comment]
> Is it possible disk needed looks at the file where filename is, not tempdir? 

That is indeed the case. tempdir plays no role here. It is not used by writeRaster. The message you get is generic; the write function does not check whether the folder written to is the temp folder (but it could).

> so it seems here disk needed_temp is 156 GB but disk needed_final is 7GB?)

The estimated file size is 156 GB, but the actual size is generally smaller. The default setting for GTiff uses compression, and apparently, your file is highly compressible. I suppose I could give a warning instead of an error, but this is a bit of a corner case.

**Comment by MatthieuStigler** [comment]
okay, thanks for the clarification! 

So it means the _(perhaps from the temp file)_ part of the message can be ruled out, since `writeRaster` won't look at the tempfile disk? 

And does the answer for `writeRaster` differ from those with `mosaic` and `merge` discussed in #425 ? It seems there on the other side, the determining folder is the temp one, not the filename one?

Thanks!

**Comment by rhijmans** [comment]
> So it means the (perhaps from the temp file) part of the message can be ruled out, since writeRaster won't look at the tempfile disk?

Yes 

> And does the answer for writeRaster differ from those with mosaic and merge discussed in https://github.com/rspatial/terra/issues/425 ? It seems there on the other side, the determining folder is the temp one, not the filename one?

Yes, because the `filename` argument is not used, a temp file is written to hold the data. It is a common mistake (or at least inefficiency) to use a method with the default `filename=""` and to then call `writeRaster` after that.
