### ISSUE TITLE
Setting window on one raster object affects other variables

### ISSUE THREAD

**Issue by darunabas** [rspatial/terra#613]
In attempting to set a window or crop a raster object based on extent, function terra::window<- seems to crop out other raster objects as well. Would using terra::crop instead be a better option than window?
For example, see below:

```  
library(terra)
f <- system.file("ex/elev.tif", package="terra") 
r1 <- rast(f) # original raster layer
preds <- r1 # a copy o
e <- ext(c(5.9, 6,49.95, 50))

window(preds) <- e

par(mfrow=c(1,2))
plot(r1)
plot(preds)
# the output of both are exactly the same! I would want r1 to remain as the original raster and preds to be the pruned version.
# Any suggestions?
```

**Comment by Rapsodia86** [comment]
You would have to use deepcopy() function to create preds
library(terra)
f <- system.file("ex/elev.tif", package="terra") 
r1 <- rast(f) # original raster layer
preds <- deepcopy(r1) # deepcopy()
e <- ext(c(5.9, 6,49.95, 50))

window(preds) <- e

par(mfrow=c(1,2))
plot(r1)
plot(preds)

![image](https://user-images.githubusercontent.com/55965799/164764681-96f02b6f-078a-4e32-9917-703f7e66571a.png)

**Comment by brownag** [comment]
This syntax works too, but just noticed using `r1[[1]]` seems to be slower/less efficient than `deepcopy(r1)` (not sure why)

``` r
library(terra)
f <- system.file("ex/elev.tif", package="terra") 
r1 <- rast(f) # original raster layer
preds <- r1[[1]]
e <- ext(c(5.9, 6,49.95, 50))

window(preds) <- e

par(mfrow=c(1,2))
plot(r1)
plot(preds)
```

![](https://i.imgur.com/KLPz6zg.png)

``` r
library(terra)
library(microbenchmark)
f <- system.file("ex/elev.tif", package="terra") 
r1 <- rast(f) # original raster layer

microbenchmark(preds <- r1[[1]])
#> Unit: microseconds
#>              expr     min      lq     mean  median       uq     max neval
#>  preds <- r1[[1]] 884.001 925.951 1100.113 979.501 1027.352 11098.2   100

microbenchmark(preds <- deepcopy(r1))
#> Unit: microseconds
#>                   expr   min       lq     mean   median      uq     max neval
#>  preds <- deepcopy(r1) 276.8 513.8505 532.4539 566.8015 580.901 990.601   100
```

**Comment by darunabas** [comment]
Thanks @brownag and @Rapsodia86
