### ISSUE TITLE
Argument "green" is missing

### ISSUE THREAD

**Issue by AGeographer** [rspatial/terra#618]
Hi,
I came across a weird error message, which might be generated by `terra`'s `coltab()` function which seems to be called within `tm_raster()` from the `tmap` package. I have created a categorical raster dataset called _clutter_ and wanted to draw a map with the `tmap` package. This same code has worked last October without problems. However, with the latest version of the `terra` and `tmap` package I get the error message below running the following code:  
```
library(tmap)
tm_shape(clutter) +
  tm_raster(# we set the classification to categorical
            style = "cat",
            # we delete empty labels
            labels = labels[labels != ""],
            # and use our custom colors
            palette = clutter.colors)
```
`Error in rgb(terra::coltab(.x)[[1]], maxColorValue = 255) : 
  argument "green" is missing, with no default`
In `tm_raster()` the following is used: 
```
 labels[labels != ""]
[1] "water"             "coniferous forest" "open land"         "airport"          
[5] "industrial"        "urban"             "dense urban"       "wetland"  
```
and
```
clutter.colors
[1] "blue"      "darkgreen" "grey"      "yellow"    "black"     "red"       "darkred"  
[8] "limegreen"
```
and, of course:
```
clutter
class       : SpatRaster 
dimensions  : 403, 448, 1  (nrow, ncol, nlyr)
resolution  : 90, 90  (x, y)
extent      : 578475, 618795, 5026455, 5062725  (xmin, xmax, ymin, ymax)
coord. ref. : NAD83(CSRS) / UTM zone 18N (EPSG:2959) 
source      : memory 
name        : landuse 
min value   : airport 
max value   : wetland 
```
Any idea what's going on here?
Thanks.
Tim

**Comment by rhijmans** [comment]
I cannot reproduce this (I do not know where you get `clutter`), but it looks like a bug in `tmap` where it tries to get colors from a color-table where none exists (ping @mtennekes)

```
library(terra)
x = rast()
coltab(x)[[1]]
NULL
rgb(NULL)
Error in rgb(NULL) : argument "green" is missing, with no default
```

**Comment by AGeographer** [comment]
Thanks for looking into this. Unfortunately, I cannot share _clutter_ due to licensing. I will post my problem at `tmap` and link if the issue will be resolved there. Thanks for your great work on the `terra` package!
