### ISSUE TITLE
Raster GDAL NoData and GeoPackage data_null metadata

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#622]
Hello!

I noticed some small inconsistencies when writing a raster grid to GeoPackage with terra v.s. sf/gdal_translate equivalent. The `data_null` metadata does not get set for the grid, which means that displaying the file in e.g. QGIS may not work if custom NAflag has been set.

When writing a grid that has NaN values in it, GDAL gives this warning: A NaN nodata value cannot be recorded in gpkg_2d_gridded_coverage_ancillary table. I also noticed that the grid_cell_encoding differs in the below two example geopackages created from the same TIFF

``` r
library(terra)
#> terra 1.5.29

r0 <- rast(system.file("ex/elev.tif", package = "terra")) 
r <- classify(r0, matrix(c(NaN, 1), ncol = 2))

# warning 
writeRaster(r0, "test2.gpkg", overwrite = TRUE)
#> Warning message:
#> In x@ptr$writeRaster(opt) :
#>  GDAL Message 6: A NaN nodata value cannot be recorded in gpkg_2d_gridded_coverage_ancillary table
  
# write reclassified raster to TIFF with custom NA flag
writeRaster(r, "test.tif", NAflag = 1, datatype = "FLT4S", overwrite = TRUE)

# write TIFF to GPKG (as FLT4S TIFF)
writeRaster(rast("test.tif"), "test.gpkg", overwrite = TRUE)

# read GPKG written with writeRaster()
r2 <- rast("test.gpkg")

# no NoData value specified in metadata
cat(tail(describe(sources(r2)), 2), sep = "\n")
#> Band 1 Block=256x256 Type=Float32, ColorInterp=Undefined
#>   Description = Height
```

Here I manually set the metadata in the gpkg_2d_gridded_coverage_ancillary table, which seems to do the trick.
```r
library(RSQLite)
# manual fix
con <- dbConnect(SQLite(), "test.gpkg")
dbGetQuery(con, "SELECT * FROM gpkg_2d_gridded_coverage_ancillary")
#>   id tile_matrix_set_name datatype scale offset precision data_null
#> 1  1                 test    float     1      0         1        NA
#>     grid_cell_encoding  uom field_name quantity_definition
#> 1 grid-value-is-center <NA>     Height              Height
dbExecute(con, "UPDATE gpkg_2d_gridded_coverage_ancillary SET data_null = 1 WHERE id = 1")
#> [1] 1
dbDisconnect(con)

# inspect fix
cat(tail(describe(sources(r2)), 7), sep = "\n")
#> Band 1 Block=256x256 Type=Float32, ColorInterp=Undefined
#>   Description = Height
#>   Min=141.000 Max=547.000 
#>   NoData Value=1
#>   Metadata:
#>     STATISTICS_MAXIMUM=547
#>     STATISTICS_MINIMUM=141
```

Calling gdal_translate via sf seems to get the NoData populated correctly:

```r
# compare to gdal_translate via sf
sf::gdal_utils("translate", "test.tif", "test2.gpkg")
r3 <- rast("test2.gpkg")
cat(tail(describe(sources(r3)), 7), sep = "\n")
#> Band 1 Block=256x256 Type=Float32, ColorInterp=Undefined
#>   Description = Height
#>   Min=141.000 Max=547.000 
#>   NoData Value=1
#>   Metadata:
#>     STATISTICS_MAXIMUM=547
#>     STATISTICS_MINIMUM=141
```

**Comment by rhijmans** [comment]
I do not see this R-warning or QGIS problem. Perhaps you use an older GDAL than I do? 

```
gdal()
#[1] "3.3.2"

```

**Comment by brownag** [comment]
I am getting the warning intermittently with 3.4.1 and I didn't get it when I tested on another machine with 3.3.1. 
![image](https://user-images.githubusercontent.com/20842828/166167562-13e5c36a-b3ca-4c71-8bd8-d75af7bd817a.png)

The warning led me to think something could be wrong, but wasn't my specific concern. I did think it was odd that NaN wouldn't be allowed since per the GDAL spec NoData in TIFF and data_null GPKG are supposed to be compatible; but I am not sure whether that is intended to include NaN or not. 

The display "issue" would occur if `NAflag=1` is not set when writing out "test.tif"--more a symptom of me tinkering around with not being able to set/transfer a _specific_ value of NoData to a GPKG. I am not getting display problems in QGIS when the NoData are written out as NaN, but I guess I expected that they would be written equivalently to how they are (should be?) in the source TIFF: with  `1`  in all the NoData areas and a `1` `data_null` entry.

In my above example I write out a raster "test.tif" with all NaN reclassified to `1` and set `NAflag=1`. When I call `values(rast("test.tif"))` I see that the `1` values return as `NaN` and that `NAflag(rast("test.tif"))` returns `NaN`. I see why converting flagged non-NA values to NA is helpful for general R usage and I am used to it, but I guess I was expecting the original values and metadata to be preserved when "translated" from TIFF to GPKG. I realize there may not be a distinction there. Does this work the same if the file doesn't fit in memory?

It appears the metadata of "test.tif" are what I expected--they show a minimum of 1 and a NoData=1. But when it is in the GPKG it seems that it has been converted to NaN with no NoData entry. I tried specifying other options to modify this behavior but didn't succeed with terra, whereas sf (I think) did what I expected when going from  "test.tif"  to "test2.gpkg"

I realize this is minutia about a limited format for storing gridded data, and I may be seriously misunderstanding something, so sorry for the long winded response. 

``` r
library(terra)
library(RSQLite)
r0 <- rast(system.file("ex/elev.tif", package = "terra")) 
r <- classify(r0, matrix(c(NaN, 1), ncol = 2))
r <- writeRaster(r, "test.tif", NAflag = 1, datatype = "FLT4S", overwrite = TRUE)
cat(tail(describe(sources(r)), 7), sep = "\n")
#>   Minimum=1.000, Maximum=547.000, Mean=-9999.000, StdDev=-9999.000
#>   NoData Value=1
#>   Metadata:
#>     STATISTICS_MAXIMUM=547
#>     STATISTICS_MEAN=-9999
#>     STATISTICS_MINIMUM=1
#>     STATISTICS_STDDEV=-9999

sf::gdal_utils("translate", "test.tif", "test2.gpkg")
r3 <- rast("test2.gpkg")
cat(tail(describe(sources(r3)), 7), sep = "\n")
#> Band 1 Block=256x256 Type=Float32, ColorInterp=Undefined
#>   Description = Height
#>   Min=141.000 Max=547.000 
#>   NoData Value=1
#>   Metadata:
#>     STATISTICS_MAXIMUM=547
#>     STATISTICS_MINIMUM=141

con <- dbConnect(SQLite(), "test2.gpkg")
dbGetQuery(con, "SELECT * FROM gpkg_2d_gridded_coverage_ancillary")
#>   id tile_matrix_set_name datatype scale offset precision data_null
#> 1  1                test2    float     1      0         1         1
#>   grid_cell_encoding  uom field_name quantity_definition
#> 1 grid-value-is-area <NA>     Height              Height
```

What if I want the NoData areas to be a _specific_ non-NaN value, have the metadata reflect that in the GPKG, and have other tools recognize that specific value as NoData? Is that possible with terra?

Also, the differences in the grid_cell_encoding; minor, but lead me to think there could be other differences in how source file metadata are transferred by the terra v.s sf implementations. With terra the gpkg grid has the `grid-value-is-center` encoding, whereas with sf it is `grid-value-is-area`. Since the source TIFF file is identical, I don't know what causes this difference.

**Comment by rhijmans** [comment]
`writeRaster` is indeed different from GDAL-translate; it uses its own defaults, and it does not try to keep those from the input. This is because the raster may be in memory, or consist of multiple raster files, each possibly with different data types, no data flags, etc.

What is perhaps unexpected is that if you set the NAflag to some value,  say -99, that does not change the values of NAN to -99. So if there are NANs in the file, in effect there will be the "true" missing values (NAN), and "flagged" missing values (coded as -99).  So, as-is, you would have to first do `x <- classify(r, cbind(NA, -99))

I could perhaps add a `copyRaster` method that would allow you to provide an input raster filename to change the file format, but keep all other settings (if supported by the output format).

I have never paid any attention to "grid-value-is-center" vs "grid-value-is-area". Not because the difference is not important, but because I do not think the software can do much with that (it is up to you to decide what your values represent); I do not think it has any direct bearing on this issue.

Does this answer your questions? Does it suggest to you that some code needs to be changed or added?

**Comment by brownag** [comment]
> `writeRaster` is indeed different from GDAL-translate; it uses its own defaults, and it does not try to keep those from the input. This is because the raster may be in memory, or consist of multiple raster files, each possibly with different data types, no data flags, etc.

That makes sense to me. The more I dug into it I could see why expecting them to behave identically was where I was going wrong :)

> What is perhaps unexpected is that if you set the NAflag to some value, say -99, that does not change the values of NAN to -99. So if there are NANs in the file, in effect there will be the "true" missing values (NAN), and "flagged" missing values (coded as -99). So, as-is, you would have to first do something like `x <- classify(r, cbind(NA, -99))` if you wanted to avoid that.

Yes, this is a good explanation of what I saw going on. Using `classify()` as you mention is essentially how I worked around this for the case that led to me making this issue. 

> I could perhaps add a `copyRaster` method that would allow you to provide an input raster filename to change the file format, but keep all other settings (if supported by the output format).

This would be useful, I think!

> I have never paid any attention to "grid-value-is-center" vs "grid-value-is-area". Not because the difference is not important, but because I do not think the software can do much with that (it is up to you to decide what your values represent); I do not think it has any direct bearing on this issue.

Sure, this makes sense to me. I only noticed that it was different and at first I wondered why. At any rate I now realize this can easily be set by the user if needed by supplying the GDAL GeoPackage [creation option](https://gdal.org/drivers/raster/gpkg.html#creation-options) `GRID_CELL_ENCODING` in `writeRaster` . e.g.
```r
library(terra)
library(RSQLite)
dem <- system.file("ex", "elev.tif", package = "terra")
writeRaster(rast(dem), "test.gpkg", gdal = c("GRID_CELL_ENCODING=grid-value-is-corner"), overwrite =TRUE)
describe("test.gpkg")
con <- dbConnect(SQLite(), "test.gpkg")
dbGetQuery(con, "SELECT * FROM gpkg_2d_gridded_coverage_ancillary")
```

> Does this answer your questions? Does it suggest to you that some code needs to be changed or added?

Yes, thanks much for following up. I hadn't quite pulled my thoughts together on this to come back and close the issue. It is now clear to me why my expectations for writeRaster default were a bit off.

I think the `copyRaster` method as you proposed it would have allowed me to do what I "wanted" to do. I started packaging up a few routines  to try and better understand what was going on and make creation of geopackages I want to make a bit easier. I was hoping to use terra for handling the read/write of the grids, so think the `copyRaster` method as you proposed it would have allowed me to do what I wanted to do and perhaps more faithfully emulate a "translation" directly from a file. That said I currently am making `writeRaster` work as I needed, so perhaps not a huge priority. Again, thanks!!
