### ISSUE TITLE
terra::rast fails to convert RasterLayers from multi-band files

### ISSUE THREAD

**Issue by mikemahoney218** [rspatial/terra#623]
Not sure if I should open this issue here or on {raster} -- apologies if I guessed wrong!

`terra::rast()` appears to fail when converting `RasterLayer` objects with multiple bands (potentially only when the bands are not named). 

For instance, using the file `merge_rasters_test.tif` attached:

[merge_rasters_test.zip](https://github.com/rspatial/terra/files/8595110/merge_rasters_test.zip)

The following fails:
```r
tmp_raster <- raster::raster("merge_rasters_test.tif")
terra::rast(tmp_raster)
# Error: [names<-] incorrect number of names

tmp_raster <- raster::raster("merge_rasters_test.tif")
terra::rast(raster::stack(tmp_raster))
# Error: [names<-] incorrect number of names
```

The following work as desired:
```r
terra::rast("merge_rasters_test.tif")

terra::rast(raster::stack("merge_rasters_test.tif"))
```

**Comment by rhijmans** [comment]
I think this works with the development version of raster; can you confirm that? You can install that version with
`install.packages('raster', repos='https://rspatial.r-universe.dev')`

**Comment by mikemahoney218** [comment]
Can confirm, fixed in the development version of raster. Thanks!
