### ISSUE TITLE
Virtual Raster Tiles only saves one file?

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#629]
Hello,
I wanted to create a virtual raster stack, but after reading back the *.vrt it only shows me one layer. 
Here is an example:

```
library(terra)
#terra 1.5.29
#Warning message:
#package ‘terra’ was built under R version 4.1.3 
 
x = 10
y <- rast(nrow=x, ncol=x, res=1, vals = 1:100)
writeRaster(y, "y.tif", overwrite = TRUE)
r.list <- rep("y.tif", 4)
v <- vrt(r.list)
m <- writeRaster(v, "out.tif")
vv <- rast(r.list)
m2 <- writeRaster(vv, "out2.tif")

rast("out.tif")
#class       : SpatRaster 
#dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : out.tif 
#name        : spat_wWzyDnkMM8P9f7W_18636 
#min value   :                          1 
#max value   :                        100 

rast("out2.tif")
#class       : SpatRaster 
#dimensions  : 180, 360, 4  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : out2.tif 
#names       : lyr.1, lyr.1, lyr.1, lyr.1 
#min values  :     1,     1,     1,     1 
#max values  :   100,   100,   100,   100 
```

**Comment by kadyb** [comment]
Have you tried to save raster with 4 layers and then load it as vrt? It seems `vrt()` only loads unique paths (without stacking).

BTW: I don't know what your goal is, but `{terra}` doesn't load data into memory by default (see `inMemory()`). If the raster requires a lot of RAM, it will be automatically processed in blocks.

**Comment by Rapsodia86** [comment]
I do have a lot rasters, so I would prefer to create a virtual raster stack (as a pointer) (instead of saving a raster with many layers) for further data extraction. I used to create vrt using GDAL python or julia to do this. Then, I saw that terra might have that capability but maybe I just misunderstood the terra vrt function. 
I also created three testing rasters, saved them on the drive, then save them as vrt, but after reading back with rast() (or vrt()) it only shows me one layer. 

> x = 10
> y <- rast(nrow=x, ncol=x, res=1, vals = 1:100)

> writeRaster(y,"y.tif",overwrite=TRUE)
> writeRaster(y, "y1.tif", overwrite = TRUE)
> writeRaster(y, "y2.tif", overwrite = TRUE)
> 
> r.list <- c("y.tif","y1.tif","y2.tif")
> 
> vrt(r.list,"test.vrt")
class       : SpatRaster 
dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : test.vrt 
name        : test 
min value   :    1 
max value   :  100 
> r <- rast("test.vrt")
> r
class       : SpatRaster 
dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : test.vrt 
name        : test 
min value   :    1 
max value   :  100

Again, maybe I am wrong about the function itself.

**Comment by kadyb** [comment]
I personally used vrt to create mosaics from small blocks, and probably stacking is not currently supported. I suppose `terra:vrt()` needs the `separate` argument to handle multiple layers, but Robert will know best. It works using `buildvrt` from `sf::gdal_utils()`:

```r
library("sf")
library("terra")

y = rast(nrow = 10, ncol = 10, vals = 1:100)
writeRaster(y, "y.tif", overwrite = TRUE)

gdal_utils(
  util = "buildvrt",
  source = rep("y.tif", 4),
  destination = "test.vrt",
  options = "-separate"
  )

v = vrt("test.vrt")
nlyr(v)
#> 4
```

**Comment by Rapsodia86** [comment]
Yes, indeed! The "separate' argument is what I am looking for. Thank you for the example with the sf::gdal_utils(). That is exactly what I have been looking for in the terra::vrt(). Maybe Robert would be interested to add the stacking option unless it is already out there and I am just not aware of it.
Thanks again!
