### ISSUE TITLE
zonal() delivers unexpected output

### ISSUE THREAD

**Issue by goergen95** [rspatial/terra#633]
Based on a discussion started at mapme-initiative/mapme.biodiversity#65 I found some unexpected behavior of `zonal()` at the current main branch head. Current CRAN release yields:

``` r
library(terra)
#> terra 1.5.21
dem <- rast(system.file("ex/elev.tif", package = "terra"))
myzone <- dem
index_valid <- which(!is.na(values(dem)))
myzone[index_valid] <- 1
zonal(dem, myzone, mean)
#>   elevation elevation
#> 1         1  348.3366
```

<sup>Created on 2022-05-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

whereas the current head yields:

``` r
library(terra)
#> terra 1.5.29
dem <- rast(system.file("ex/elev.tif", package = "terra"))
myzone <- dem
index_valid <- which(!is.na(values(dem)))
myzone[index_valid] <- 1
zonal(dem, myzone, mean)
#>   elevation elevation
#> 1         1  348.3366
#> 2       NaN       NaN
```

<sup>Created on 2022-05-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If this is intended behavior I do not fully understand the rationale and a hint in the documentation could be useful.

**Comment by rhijmans** [comment]
Thanks, that was not intentional.
