### ISSUE TITLE
Match categorical raster values in terra

### ISSUE THREAD

**Issue by darunabas** [rspatial/terra#635]
I have the following script to use match categorical values using terra. While this is straightforward with raster package, I would like to achieve same with terra. Here's my code:
```
library(raster)
library(terra)
d <- data.frame(grids=paste0("v", seq_len(8550)), trait=rnorm(8550))
f <- system.file("ex/elev.tif", package="terra")
r <- raster(f)

# 1. USING RASTER
r1 <- r
r1[1:ncell(r1)] <- paste0("v", seq_len(ncell(r1)))
ind1 <- match(values(r1), d$grids)
z1 <- setValues(r1, d$trait[ind1])

# 2. USING TERRA
r2 <- r
values(r2) <- paste0("v", seq_len(ncell(r2)))
ind2 <- match(values(r2), d$grids)
z2 <- setValues(r2, d$trait[ind2])
```
Any thoughts on what the equivalent functions are in terra?

**Comment by rhijmans** [comment]
With terra, `values` returns the numeric representation of a factor. To get the "label", you can use `as.data.frame`. You can do 

```
r2 <- rast(f)
values(r2) <- paste0("v", seq_len(ncell(r2)))
ind2 <- match(as.data.frame(r2)[[1]], d$grids)
z2 <- setValues(r2, d$trait[ind2])
```

This may not be a good approach (see ?cats), but that is hard to say without context.

**Comment by darunabas** [comment]
Thanks a lot @rhijmans
This works for my purpose. The goal is to be able to match the values from the dataframe based on pixel identity for mapping it.
