### ISSUE TITLE
Let `mem_info` return the values

### ISSUE THREAD

**Issue by LLeiSong** [rspatial/terra#637]
Hi folks, I recently used the `mem_info` function to check the avail/need RAM and found there is a tiny issue. It just prints out the info. I am sorry If I misunderstand the design of this function. But I kind of feel this is a tiny bug. I believe it might be more convenient to return these values by the function. Otherwise, we have to call `spatOptions` which is not exported. 

Adding a return after this line would make it.
https://github.com/rspatial/terra/blob/e62b42e2d74ec41db9e935f4bddbfe1c75fc7e9d/R/messages.R#L62

**Comment by rhijmans** [comment]
It just prints, because I do not see a use for it beyond debugging. What would want you do with the returned information?

**Comment by LLeiSong** [comment]
@rhijmans thanks for the response. I am dealing with a huge raster for the RAM of my PC that can easily crash R if using some `terra` functions. Then I want to cut into tiles and do parallel calculation. The RAM info is helpful to decide how many tiles to split to. I think you are right that it would lead pepple the wrong way.

**Comment by rhijmans** [comment]
> I am dealing with a huge raster for the RAM of my PC that can easily crash R if using some terra functions.

The design philosophy of terra is that large rasters are processed in chunks such that there are no crashes. There is automatic  "tiling" (processing by chunk). That does not mean that everything works perfectly and if there is a particular method that causes crashes I would like to hear about it. 

You can also use the `terraOptions` to lower the allowed RAM use. This can be particularly helpful on clusters with RAM shared  between nodes.

**Comment by rhijmans** [comment]
`mem_info` now returns the values invisibly.
