### ISSUE TITLE
Unexpected results from subst

### ISSUE THREAD

**Issue by waternumbers** [rspatial/terra#639]
In the minimal example below I was expecting the values 5 and 3 in the original rast to be replaced by 3 and 5 respectively. 

Instead subst seems to apply the changes sequentially - that is convert all 5's to 3's then all 3's (including those just generated) to 5's, leaving no 3's

I can see why you might want to do substitution that way but it doesn't match my reading of the help file.

```
library(terra)
# terra 1.5.34

r <- rast(ncols=5, nrows=5, xmin=0, xmax=1, ymin=0, ymax=1, crs="")
r <- init(r, 1:6); x11(); plot(r)
x <- subst(r, c(5,3), c(3,5)); x11(); plot(x)
```

CRAN version of terra produces the same result.

**Comment by rhijmans** [comment]
Thank you very much. Fixed now.
