### ISSUE TITLE
writeRaster crashing RStudio session when writing collection of SpatRast objects to disk

### ISSUE THREAD

**Issue by AndreMBellve** [rspatial/terra#64]
Sorry to be bothering you again, butI have hit another wall. RStudio is crashing whenever I try to use `writeRaster()` on a collection of SpatRast rasters.  The rasters files in question around mostly about 17 mb, although one of them is ~600 mb. The same thing happens when I try to `writeRaster()` on a collection that has not been reprojected. It does work however, when I use it on a single raster (even the big one).

In an attempt to get around this, I wrote a `for` loop to do them one at a time but it still crashes after a few minutes. I have run through every iteration of my `for` loop, and none of them throw errors individually and appear to be executing correctly. I could just brute force it, but I need to do the same operation for four different projects and would prefer to avoid it.

I have also tried running the same code in base R, but when it gets to the `writeRaster(...)` line, it runs for an inordinately long time ~ current iteration has been running for 2 hours with no end; even though individual rasters take about 5 - 10 seconds to process.

Here is my workflow (sorry I can't figure out a good way of supplying my rasters - suggestions are welcome if it would help!):
```
# Libraries ---------------------------------------------------------------
library(terra)

# Predictor Prep ------------------------------------------------------------
#Listing file names in raster folder
rasterCat <- list.files("./data/Raster/Contemporary/categorical", pattern = ".tif", full.names =  TRUE) 
rasterNum <- list.files("./data/Raster/Contemporary/numeric", pattern = ".tif", full.names =  TRUE) 

#Reading in all rasters
#reading categorical rasters
catRast <- rast(rasterCat)

#reading numeric rasters
numRast <- rast(rasterNum)

#Reading in a raster with the model projection and datum
modelRast <- rast("./data/Raster/modelCRS/Slope.tif")

#Changing all rasters to have NZGD2000 datum and NZTM projection
#Reprojecting categorical rasters
catRast2000 <- terra::project(catRast, terra::crs(modelRast), method = "near")

#Reprojecting numeric rasters
numRast2000 <- terra::project(numRast, terra::crs(modelRast), method = "bilinear")

#for loop writing reprojected rasters to disk
allRast <- c(catRast2000, numRast2000)

for(i in 1:length(allRast)){
  terra::writeRaster(allRast[[i]], 
                     paste("./data/Raster/Contemporary/NZGD2000/",  names(allRast[[i]]), ".tif", sep = ""), 
                     overwrite = TRUE)
}
```

and here is my session info:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252 
[2] LC_CTYPE=English_New Zealand.1252   
[3] LC_MONETARY=English_New Zealand.1252
[4] LC_NUMERIC=C                        
[5] LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] viridis_0.5.1       viridisLite_0.3.0   dismo_1.1-4        
 [4] blockCV_2.1.1       rasterVis_0.48      latticeExtra_0.6-29
 [7] lattice_0.20-41     raster_3.3-7        sp_1.4-2           
[10] terra_0.8-01        sf_0.9-4            forcats_0.5.0      
[13] stringr_1.4.0       dplyr_1.0.0         purrr_0.3.4        
[16] readr_1.3.1         tidyr_1.1.0         tibble_3.0.1       
[19] ggplot2_3.3.2       tidyverse_1.3.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         lubridate_1.7.9    prettyunits_1.1.1 
 [4] zoo_1.8-8          png_0.1-7          class_7.3-17      
 [7] assertthat_0.2.1   packrat_0.5.0      R6_2.4.1          
[10] wesanderson_0.3.6  cellranger_1.1.0   backports_1.1.8   
[13] reprex_0.3.0       e1071_1.7-3        httr_1.4.1        
[16] pillar_1.4.4       progress_1.2.2     rlang_0.4.6       
[19] readxl_1.3.1       rstudioapi_0.11    hexbin_1.28.1     
[22] blob_1.2.1         munsell_0.5.0      broom_0.5.6       
[25] compiler_4.0.2     modelr_0.1.8       pkgconfig_2.0.3   
[28] tidyselect_1.1.0   gridExtra_2.3      codetools_0.2-16  
[31] fansi_0.4.1        crayon_1.3.4       dbplyr_1.4.4      
[34] withr_2.2.0        grid_4.0.2         nlme_3.1-148      
[37] jsonlite_1.7.0     gtable_0.3.0       lifecycle_0.2.0   
[40] DBI_1.1.0          magrittr_1.5       units_0.6-7       
[43] scales_1.1.1       KernSmooth_2.23-17 cli_2.0.2         
[46] stringi_1.4.6      fs_1.4.2           xml2_1.3.2        
[49] ellipsis_0.3.1     generics_0.0.2     vctrs_0.3.1       
[52] RColorBrewer_1.1-2 tools_4.0.2        glue_1.4.1        
[55] hms_0.5.3          jpeg_0.1-8.1       parallel_4.0.2    
[58] colorspace_1.4-1   classInt_0.4-3     rvest_0.3.5       
[61] haven_2.3.1  
```

when running it through an RStudio GUI I am using version 1.3.959. I have also tried running it with a clean session to no avail.

**Comment by rhijmans** [comment]
Very odd. Perhaps (hopefully) this is a problem that has already be solved; I have been working on writing and you have pulled an unlucky version. Can you try with the current version? Also, it would be helpful if you showed `show(numRast)` (and perhaps others) so that I can recreate a similar data set.

**Comment by AndreMBellve** [comment]
It appears to be working now; thank you Robert! I will double check with the reprojected rasters (I can't see why it wouldn't work though), and let you know if any issues arise. In future I will be sure to use `show`, sorry I didn't include it for these!

**Comment by AndreMBellve** [comment]
Thank you! I had actually only let it run for a few iterations to see if it
crashed in RStudio (and it didn't) but I would have hit that stumbling
block when I ran it for real and tried to write 151980000 rasters to my
disk... My initial instinct was to actually just give `writeRaster` a
collection like:

```
#say numrast is a SpatRast with 11 rasters
writeRaster(numRast, "./data/rasters/NZGD2000/")
```
which doesn't work. I assume this is because it does not have a name/suffix
with which to save the object. I don't know if this would be possible, but
maybe in future `writeRaster` could take a SpatRast collection and then
save the layers using the character string produced by `names(numRast)`,
and taking an argument like `suffix = ".tif"` to specify the file type? Or
are these kinds of amendments to come and included under the "not yet
implemented" clause you mention in the function help file?

Thank you for the extremely prompt responses! I really appreciate the help
on all these issues.

**Comment by rhijmans** [comment]
That is a good idea. The raster package has that option for a `RasterStack` (`bylayer=TRUE`) and that can be improved upon. It could take the filenames from `names(x)`  as you suggest. But it might be better (more flexible and explicit) to allow for `filename` to be a vector of filenames of the same *length* as `nlyr(x)`.

**Comment by rhijmans** [comment]
>> I really appreciate the help on all these issues.

You are welcome & your early feedback is invaluable, and many others will benefit from it.

**Comment by rhijmans** [comment]
I have now implemented writing to single layer files with writeRaster 

```
library(terra)
setwd(tempdir())
s <- rast(system.file("ex/logo.tif", package="terra"))   
fnames <- paste0(names(s), ".tif")
z <- writeRaster(s, fnames, overwrite=TRUE)
z
#class       : SpatRaster 
#dimensions  : 77, 101, 3  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#source(s)   : red.tif  
#              green.tif  
#              blue.tif  
#names       : red, green, blue 
#min values  :   0,     0,    0 
#max values  : 255,   255,  255 

```

**Comment by mcoghill** [comment]
Sorry to add to a closed topic, but do you think it would be possible to add this functionality to other commands as well? For example: 

`z <- project(s, "epsg:3005", filename=fnames, overwrite=TRUE)`

Running this will only output a single multiband file currently, but it would be nice to have that same functionality that you have given to the writeRaster() function too. Let me know if I should open up a separate issue for this or if it's alright keeping it here too.
