### ISSUE TITLE
`terra::as.points()` matches factor-labels incorrectly to point-geometries

### ISSUE THREAD

**Issue by a-benini** [rspatial/terra#640]
If a SpatRaster layer is a factor with categories, which are stored as
indices not belonging to a sequence of integers starting with 0 ranging up
to n - 1 (where n is the number of categories), then `terra::as.points()`
doesn’t match the associated labels (levels) correctly to the generated
point-geometries. In contrast `terra::as.polygons()` does match the levels
correctly to the returned geometries.

Here’s simple example of such a SpatRaster layer illustrating the different
(mis)matching behavior of `as.points()` and `as.polygons()`:

``` r
library(terra)
#> terra 1.5.21
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 8.1.1; sf_use_s2() is TRUE

r <- rast(ncols = 3, nrows = 3, xmin = 0, xmax = 3, ymin = 0, ymax = 3, val = 1:9)
levels(r) <- data.frame(id = 1:9, level = LETTERS[1:9])
is.factor(r)
#> [1] TRUE

color <- RColorBrewer::brewer.pal(9, "Set3")
plot(r, col = color)
text(r)
```

![](https://i.imgur.com/ZPLmkAV.png)

``` r
data.frame(
  cats(r)[[1]],
  as.points = as.points(r)$level,
  as.polygons = as.polygons(r, dissolve = FALSE)$level
  )
#>   id level as.points as.polygons
#> 1  1     A         B           A
#> 2  2     B         C           B
#> 3  3     C         D           C
#> 4  4     D         E           D
#> 5  5     E         F           E
#> 6  6     F         G           F
#> 7  7     G         H           G
#> 8  8     H         I           H
#> 9  9     I      <NA>           I

as.points(r) %>% sf::st_as_sf() %>% plot(cex = 3, pch = 19, extent = r)
```

![](https://i.imgur.com/6MOngMj.png)

``` r
as.polygons(r) %>% sf::st_as_sf() %>% plot()
```

![](https://i.imgur.com/g3sqc7L.png)

Combining `as.polygons()` and `terra::centroids()` bypasses this malfunction
of `as.points()`:

``` r
as.polygons(r, dissolve = FALSE) %>% centroids() %>% .$level
#> [1] "A" "B" "C" "D" "E" "F" "G" "H" "I"
as.polygons(r, dissolve = FALSE) %>% centroids() %>% sf::st_as_sf() %>% plot(cex = 3, pch = 19, extent = r)
```

![](https://i.imgur.com/LpHYggi.png)

But that’s probable not how things should ideally work.

If a SpatRaster layer is a factor with categories, which are stored as
indices being completely outside of the range 0 to n - 1 (n = number of
categories), then `terra::as.points()` doesn’t match any associated labels
(levels) to the returned geometries:

``` r
set.seed(0)
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(3, ncell(r), replace = TRUE) + 10
(d <- data.frame(id = 11:13, cover = c("forest", "water", "urban")))
#>   id  cover
#> 1 11 forest
#> 2 12  water
#> 3 13  urban
levels(r) <- d
summary(r)
#>     cover   
#>  forest:32  
#>  water :38  
#>  urban :30
as.points(r)$cover %>% table(useNA = "always")
#> .
#> <NA> 
#>  100
as.polygons(r)$cover %>% table(useNA = "always")
#> .
#> forest  urban  water   <NA> 
#>      1      1      1      0
as.polygons(r, dissolve = FALSE) %>% centroids() %>% .$cover %>% table(useNA = "always")
#> .
#> forest  urban  water   <NA> 
#>     32     30     38      0
```

Is it possible to modify / fix `terra::as.points()` so that it matches the
factor-labels correctly to the returned geometries in the same way that
`terra::as.polygons()` does?

<sup>Created on 2022-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thank you. I believe this is fixed, as I now get:

```
library(terra)
#terra 1.5.35
r <- rast(ncols = 3, nrows = 3, xmin = 0, xmax = 3, ymin = 0, ymax = 3, val = 1:9)
levels(r) <- data.frame(id = 1:9, level = LETTERS[1:9])
 
data.frame(
   cats(r)[[1]],
   as.points = as.points(r)$level,
   as.polygons = as.polygons(r, dissolve = FALSE)$level
)
#  id level as.points as.polygons
#1  1     A         A           A
#2  2     B         B           B
#3  3     C         C           C
#4  4     D         D           D
#5  5     E         E           E
#6  6     F         F           F
#7  7     G         G           G
#8  8     H         H           H
#9  9     I         I           I
```

**Comment by a-benini** [comment]
I’m sorry to say, although I’ve now installed the latest `terra` version, for
me nothing has changed. So I can’t reproduce your example:

``` r
# install.packages('terra', repos='https://rspatial.r-universe.dev')
library(terra)
#> terra 1.5.35
r <- rast(ncols = 3, nrows = 3, xmin = 0, xmax = 3, ymin = 0, ymax = 3, val = 1:9)
levels(r) <- data.frame(id = 1:9, level = LETTERS[1:9])

data.frame(
  cats(r)[[1]],
  as.points = as.points(r)$level,
  as.polygons = as.polygons(r, dissolve = FALSE)$level
)
#>   id level as.points as.polygons
#> 1  1     A         B           A
#> 2  2     B         C           B
#> 3  3     C         D           C
#> 4  4     D         E           D
#> 5  5     E         F           E
#> 6  6     F         G           F
#> 7  7     G         H           G
#> 8  8     H         I           H
#> 9  9     I      <NA>           I
```

Would any further information from my side be helpful?

<sup>Created on 2022-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
R-universe does not build on each push to the repo. So you do not have the latest version. You may have to wait for a couple of hours. See https://r-universe.dev/organizations/ and  https://rspatial.r-universe.dev/ui#packages for timestamps.

**Comment by a-benini** [comment]
Meanwhile it works! Thank you.
