### ISSUE TITLE
Read a raster file without any data layers

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/terra#654]
Let me know if this isn't the right place to post this, but it seems like there's no way to read the cell coordinates and metadata of a raster file without getting any of the data layers. `rast(…, lyrs = 0)` and `rast(…, lyrs = integer())` are perhaps the most obvious things to try, but they yield `Error: [subset] no (valid) layer references`. I also can't figure out how to subset a `SpatRaster` down to zero layers. The best I can do, for both reading and subsetting, is to get only one layer, although it's clear that `SpatRaster` allows rasters with no data because that's what you get with e.g. `rast(nrow = 5, ncol = 5)`

**Comment by rhijmans** [comment]
It is not clear what `_` refers to. But if you have a `SpatRaster` you can create a template (empty raster) from it using `rast`. 

```
r <- rast(system.file("ex/elev.tif", package = "terra"))
x <- rast(r)
```

`r` will have at least one layer (SpatRasters must have a positive number of rows, columns, and layers) --- but I do not think that matters?
