### ISSUE TITLE
Terra reading rasters incorrectly in R 4.2

### ISSUE THREAD

**Issue by LMurphy186232** [rspatial/terra#656]
In R 4.2, terra appears to read rasters upside down.

I have a script that I ran with R 4.1.3, terra 1.5.21. I ran the same script in R 4.2.0 (terra still 1.5.21) and I got a different result. When I read the same raster in both versions and plotted it using plot(), it plotted as expected in R 4.1.3, but plotted upside down in R 4.2.0. Spatial analyses came out incorrectly as well.

**Comment by rhijmans** [comment]
Not much I can say or do based on this. Perhaps you can isolate the problem a bit more, and perhaps share the offending file (I am assuming this is associated with a particular file)?

**Comment by AlicePidd** [comment]
Hiya! Any luck with fixing this issue? I'm experiencing the same thing and it is driving me insane!
