### ISSUE TITLE
Legend with special characters doesn't display in R 4.2

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#658]
I believe this is more of Windows and character encoding issue (I use polish locale CP-1250) than the package itself, but maybe someone will encounter the same problem.

```r
library("terra") # terra 1.5.21
r = rast(nrow = 2, ncols = 1, vals = 1:2)
df = data.frame(ID = 1:2, label = c("ą", "ł"))
levels(r) = df
plot(r)
r
#> Error in nchar(minv) : invalid multibyte string, element 1
#> In addition: Warning messages:
#> 1: In doTryCatch(return(expr), name, parentenv, handler) :
#>   invalid input 'ą' in 'utf8towcs'
#> 2: In doTryCatch(return(expr), name, parentenv, handler) :
#>   invalid input 'ą' in 'utf8towcs'
```

![Rplot](https://user-images.githubusercontent.com/35004826/171617114-00602eda-5984-4ed0-b399-2e095b8895d5.png)

In my case, this can be fixed by using the `enc2utf8()` function:

```r
df = data.frame(ID = 1:2, label = enc2utf8(c("ą", "ł")))
```

**Comment by rhijmans** [comment]
I have made a change that may solve this. (I cannot tell, as I cannot reproduce the problem on US Windows).
