### ISSUE TITLE
Suggested feature: Give users the ability to change directory for temporary files

### ISSUE THREAD

**Issue by Jo-Schie** [rspatial/terra#659]
`Terra` package creates temporary files when an output SpatRaster may be too large to store in memory (RAM). This can happen when no filename is provided to a function and when using functions where you cannot provide a filename. 

It happens to me at times, that I run out of memory if I work on serveral rasters in a loop. This also happend with the `raster` package before. I wondered if it was possible to create a small function that would handle where `terra` writes tempfiles to. So instead of defaulting to `/tmp/Rdfkwnwwd-something` folder from the Rsession, the user could also provide a custom path to e.g. an external disc where temporary files would be stored. 

Why not do this on the system level? I searched around and tried a lot of different options for changing the tempfolder on unix systems, bot none really seems to work satisfying and smoothly for me. AFAIK there is also no up-to-date package that would provide this functionality. There is e.g. a way described [here](https://github.com/r-lib/callr/issues/172#issuecomment-710700559) but currently it did not work for me well together with `terra`.

**Comment by rhijmans** [comment]
You can do this with

```
terraOptions(tempdir="this/is/my/path")
```

**Comment by Jo-Schie** [comment]
oh! Nice, you thought of it all. Thanks for the information. I'll try that feature. Great work with `terra`!
