### ISSUE TITLE
Installing from R-Universe requires compilation

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#660]
Not sure if this is intentional or not, but previously installing from R-Universe did not require compilation (only from github did). The ReadMe page still indicates that Rtools should only be needed if you want to install from github, but when I run `install.packages('terra', repos='https://rspatial.r-universe.dev')` it requires me to build from source. I've also experienced the same for `raster`. My computer runs Windows 10 with R 4.0.4

**Comment by edzer** [comment]
Have you tried updating R to the released version, 4.2.0?

**Comment by brownag** [comment]
It looks like R universe only has Windows builds for terra_1.5-40.zip (r-4.3) terra_1.5-40.zip (r-4.2) terra_1.5-40.zip (r-4.1)

So you'll need at least 4.1.x I think

**Comment by ailich** [comment]
Thanks, with a newer version of R it installs without compilation!
