### ISSUE TITLE
values(r[[1]]) does not work for single layer SpatRaster

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#661]
When using `values(r[[1]])` on a single layer SpatRast I get `Error: [subset] undefined layer(s) selected: NA`. Since it's a single layer it is equivalent to just do `values(r)`, but it's nice to have syntax that works the same for multiband and single band objects, and is the same across functions (e.g. `plot(r[[1]])` is valid for a single band object).

```
library(terra) # ‘1.5.40’

r<- rast(nrow=100, ncol=100)
set.seed(5)
values(r[[1]])<- sample(1:7, size = ncell(r), replace = TRUE)
# Error: [subset] undefined layer(s) selected: NA

values(r)<- sample(1:7, size = ncell(r), replace = TRUE) #Works
plot(r[[1]])
```
![pr 1](https://user-images.githubusercontent.com/28163862/172217380-2c0d10f7-ace5-4376-9325-bf6227e97014.png)

**Comment by rhijmans** [comment]
Thank you. Fixed with https://github.com/rspatial/terra/commit/d10e5882f804105579ada64137c57cd2f68f3243
