### ISSUE TITLE
How to drop a layer on a terra object

### ISSUE THREAD

**Issue by daniel-valentins** [rspatial/terra#664]
Hi, I'm working with an object that has multiple bands, and I want to drop just one. My current flow consists in convert this object to `raster` package, use the function `raster::dropLayer` and then convert back to `terra` package.

This is because in the documentation of `terra` says that the equivalent function to `raster::dropLayer `is the `terra::subset`, but I still don't understand how it works. I'll leave a reproducible example here, because maybe it's possible to do this and I don't understand it, or maybe the `terra::subset` function doesn't really remove bands.

Thank you in advance for your attention and help!

```
r1 <- r2 <- r3 <- terra::rast(nrow = 10, ncol = 10)

terra::values(r1) <- runif(terra::ncell(r1))
terra::values(r2) <- runif(terra::ncell(r2))
terra::values(r3) <- runif(terra::ncell(r3))

s <- c(r1, r2, r3)
names(s) <- c("layer_1", "layer_2", "layer_3")
```

To subset bands:
```
terra::subset(s, "layer_3")
terra::subset(s, c("layer_2", "layer_3"))
```
But how to remove one band?

**Comment by kadyb** [comment]
You can do this by using square brackets and indexes:

```r
new <- s[[-1]]
new <- s[[-c(1, 2)]]
```

**Comment by brownag** [comment]
IMO it would be nice if this worked:

```r
s[[1]] <- NULL
```

I think if the `[[` replace methods were to handle NULL `value` by returning `x[[-i]]` (where `i` is `integer`) it would work

**Comment by daniel-valentins** [comment]
First, thanks for your reply!

Sorry for not making the context clear. The number of bands varies between different rasters _(depending on the source providing the data)_, so I would need to remove the band by name _(which is the same regardless of the source)_ rather than by position.

This works:
```
s[[c("layer_3")]]
```

but this don't:
```
s[[-c("layer_3")]]
```
Is this possible through this function (or some other function that I don't know about) ?

**Comment by Rapsodia86** [comment]
That might be a way around:
s2 <- s[[-(match("layer_3",names(s)))]]

Or in two steps:
drop_b <- match("layer_3",names(s))
s2 <- s[[-(drop_b)]]

**Comment by rhijmans** [comment]
You can now do:

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
s$green = NULL
s

s <- rast(system.file("ex/logo.tif", package="terra"))   
s[["green"]] = NULL
s

s <- rast(system.file("ex/logo.tif", package="terra"))   
subset(s, -green, TRUE)
```

does that cover it?

**Comment by daniel-valentins** [comment]
Worked perfectly! Thank you so much Monika for the idea and Robert for the implementation in the package, you guys are great!

**Comment by ailich** [comment]
@rhijmans, perhaps fixing #670 broke this, but with the latest development version your example no longer runs.

``` r
library(terra)
#> terra 1.5.41
s <- rast(system.file("ex/logo.tif", package="terra"))   
s$green = NULL
#> Error: [subset] no (valid) layer references

s <- rast(system.file("ex/logo.tif", package="terra"))   
s[["green"]] = NULL
#> Error: [subset] no (valid) layer references

s <- rast(system.file("ex/logo.tif", package="terra"))   
subset(s, -green, TRUE)
#> Error: [subset] no (valid) layer references
```

<sup>Created on 2022-06-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Oops, fixed again!
