### ISSUE TITLE
na.rm argument for spatSample() as in raster::sampleRandom

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#67]
The na.rm argument in raster::sampleRandom() is not present in terra::spatSample(), which eventually returns NA values and makes it difficult to set a given meaningful size. Could a na.rm argument be included in terra::spatSample() ?

**Comment by rhijmans** [comment]
It took me a while, but I now get:

```
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)

set.seed(21)
spatSample(r, 5, "random")
#  elevation
#1       457
#2       313
#3       NaN
#4       270
#5       NaN

spatSample(r, 5, "random", na.rm=TRUE)
#  elevation
#1       340
#2       398
#3       490
#4       308
#5       285 
```
