### ISSUE TITLE
Order of color on a raster plot

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#673]
When a SpatRaster object has many layers with categorical values, colors are not consistent across plot panels:

``` r
library(terra)

x = rast(nrows = 10, ncols = 10)
x[] = 1
x2 = x
x2[] = c(rep(1, 50), rep(2, 50))

plot(c(x, x2), col = c("red", "blue"))
```

![](https://i.imgur.com/9wsXugx.png)

**Comment by rhijmans** [comment]
I think this points to the need for a new argument to plot. Something like `shared_legend=TRUE`

**Comment by ailich** [comment]
I think that a `shared_ legend` argument would be useful in general (e.g. even in continuous variables sometimes it's useful to have them all on the same scale for comparison or saving space by only having one legend), but perhaps for categorical rasters all levels should be displayed by default (which is the behavior of tmap).

``` r
library(terra)
#> terra 1.5.43
library(tmap)

x = rast(nrows = 10, ncols = 10)
x[] = 1
x2 = x
x2[] = c(rep(1, 50), rep(2, 50))

levels(x)<- data.frame(ID=c(1,2), class=c("c1", "c2"))
levels(x2)<- data.frame(ID=c(1,2), class=c("c1", "c2"))

plot(c(x, x2), col = c("red", "blue"))
```

![](https://i.imgur.com/8JeVj9a.png)

``` r

tm_shape(x)+
  tm_raster(style = "cat", palette = c("red", "blue"))+
  tm_layout(legend.outside = TRUE)
```

![](https://i.imgur.com/GpM9sb4.png)

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
This now works better for rasters that are truly categorical and have the same levels (whether present or not): 

```
library(terra)
x = rast(nrows = 2, ncols = 2, vals=1)
y = rast(nrows = 2, ncols = 2, vals=c(1,2,2,1))

cats <- data.frame(ID=1:2, label=c("a", "b"))
levels(x) <- cats
levels(y) <- cats

plot(x, col=rainbow(2))
plot(y, col=rainbow(2))
```

**Comment by rhijmans** [comment]
You can now create a fixed legend in different ways. 

For a "classes" legend (as in the original question)

```
library(terra)
#terra 1.5.50
x = rast(nrows = 2, ncols = 2, vals=1)
y = rast(nrows = 2, ncols = 2, vals=c(1,2,2,1))

cols = data.frame(id=1:2, col=c("red", "blue"))
plot(c(x,y), col=cols)
```
![mapleg](https://user-images.githubusercontent.com/11481397/177014107-6e270a8b-9a70-4cc3-af1b-9a22956e6003.png)

For an "interval" legend 

```
a = rast(nrows=10, ncols=10, vals=1:100)
b = rast(nrows=10, ncols=10, vals=sample(100))
dr = data.frame(from=c(5,33,66,150), to=c(33, 66, 95,200), col=rainbow(4))
plot(c(a, b), col=dr, mar=c(1.5,1.5,1.5,4), plg=list(cex=.6))
```

![mapsleg2](https://user-images.githubusercontent.com/11481397/177014279-797c57fa-8f06-4703-aaa9-bd467e20ac44.png)

For an "continuous" legend  this was available all along:

```
plot(c(a, b), range=c(-10,90))
```

![mapsleg3](https://user-images.githubusercontent.com/11481397/177014311-96425697-833b-4901-8cc5-811bf3e72b13.png)

And for categorical rasters see my post above. 

Argument `legend` is now been vectorized such that you can do: 

```
plot(c(a, b), range=c(-10,90), legend=c(T,F))
```
![shared](https://user-images.githubusercontent.com/11481397/177014837-9d9dac47-3b24-473a-a7e5-5067051cad16.png)

While better support for a "shared legend" remains on the to-do list, that was not part of the original issue. For now there is also `ggplot` (perhaps via "tidyterra") and `raster::spplot(c(a,b))`; and you can DIY it with calls to plot(x, legend=F) and then use "legend( )"

**Comment by Jadamso** [comment]
The solution does not yet work for factor data.
```
library(terra)
x = as.factor(rast(nrows = 2, ncols = 2, vals=1))
y = as.factor(rast(nrows = 2, ncols = 2, vals=c(1,2,2,1)))

cols = data.frame(id=1:2, col=c("red", "blue"))
plot(c(x,y), col=cols)
```

**Comment by ailich** [comment]
@Jadamso you are correct the code there doesn't work if it is a factor. I'm not sure why that is the case, but if you just supply `col` as a vector it appears to work.

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.3.2
#> terra 1.7.71

# Set up
x = rast(nrows = 2, ncols = 2, vals=1)
y = rast(nrows = 2, ncols = 2, vals=c(1,2,2,1))

cols = data.frame(id=1:2, col=c("red", "blue"))

# Plot when not a factor
plot(c(x,y), col=cols)
```

![](https://i.imgur.com/hNvLtBL.png)

``` r

# Make factor with martching levels
levels(x)<- data.frame(id=c(1,2), group= c("a", "b"))
levels(x)
#> [[1]]
#>   id group
#> 1  1     a
#> 2  2     b
levels(y)<- data.frame(id=c(1,2), group= c("a", "b"))
levels(y)
#> [[1]]
#>   id group
#> 1  1     a
#> 2  2     b

# Try plotting when is a factor
plot(c(x,y), col=cols) # Error
#> Error in matrix(z, nrow = nrow(x), ncol = ncol(x), byrow = TRUE): 'data' must be of a vector type, was 'NULL'

plot(c(x,y), col=c("red", "blue"))
```

![](https://i.imgur.com/NFRE0UP.png)

<sup>Created on 2024-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
