### ISSUE TITLE
Cannot subset layers with character vector

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#674]
Providing the names of the layers in a character vector used to work for subsetting, but this no longer works on the development version (It works on the CRAN version 1.5.34).

``` r
library(terra)
#> terra 1.5.43
s <- rast(system.file("ex/logo.tif", package="terra"))   
names(s)
#> [1] "red"   "green" "blue"

subset(s, c("green", "blue"))
#> Error in positive_indices(i, nlyr(x), "subset"): is.numeric(i) is not TRUE
```

<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
I think this was fixed for https://github.com/rspatial/terra/issues/664 and/or https://github.com/rspatial/terra/issues/670

**Comment by ailich** [comment]
@rhijmans, for some reason subsetting does not work properly when contained within a function when using the development version.

``` r
library(terra)
#> terra 1.5.43
bandratios<- function(red, green, blue, metrics){
  rg<- red/green
  names(rg)<- "red_green"
  rb<- red/blue
  names(rb)<- "red_blue"
  
  gr<- green/red
  names(gr)<- "green_red"
  gb<- green/blue
  names(gb)<- "green_blue"
  
  br<- blue/red
  names(br)<- "blue_red"
  bg<- blue/green
  names(bg)<- "blue_green"
  
  out<- c(rg, rb, gr, gb, br, bg)
  out<- subset(out, metrics)
  return(out)
}

s <- rast(system.file("ex/logo.tif", package="terra"))   
bandratios(s$red, s$green, s$blue, metrics = c("green_red", "blue_green"))
#> Error in eval(substitute(subset), nl, parent.frame()): object 'metrics' not found
```

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Rapsodia86** [comment]
Works for me. Maybe rerun on a clean Rsession? 
> library(terra)
terra 1.5.34
 bandratios<- function(red, green, blue, metrics){
   rg<- red/green
   names(rg)<- "red_green"
   rb<- red/blue
   names(rb)<- "red_blue"
   gr<- green/red
   names(gr)<- "green_red"
   gb<- green/blue
   names(gb)<- "green_blue"
      br<- blue/red
   names(br)<- "blue_red"
   bg<- blue/green
   names(bg)<- "blue_green"
     out<- c(rg, rb, gr, gb, br, bg)
   out<- subset(out, metrics)
   return(out)
 }
 s <- rast(system.file("ex/logo.tif", package="terra"))   
bandratios(s$red, s$green, s$blue, metrics = c("green_red", "blue_green"))
class       : SpatRaster 
dimensions  : 77, 101, 2  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
sources     : memory  
              memory  
names       : green_red, blue_green 
min values  :         0,          0 
max values  :       Inf,        Inf

**Comment by Rapsodia86** [comment]
Ah right, though I do have the development version terra 1.5.34.
Updated to dev 1.5.43 works when you define 'metrics' outside the function. But, indeed it does not work when 'metrics' defined within the function, like previously. Sorry for jumping in without checking the version!

**Comment by rhijmans** [comment]
Inside a function you need to use `NSE=FALSE`: 

```
out<- subset(out, metrics, NSE=FALSE)
```

**Comment by ailich** [comment]
@rhijmans, perhaps it makes sense to have `NSE=FALSE` by default to preserve backwards compatibility? For example, I have functions that use this syntax, but since `NSE` doesn't exists as an argument in earlier versions of `terra`, I can have them work in either old or new versions, but not both (though I can always look for where I use `subset` and update it to use `[[`). Also having `NSE=TRUE` can lead to some unexpected results due to the scoping of variables. For example if there is a variable in the global environment with the same name, it'll grab that instead of throwing an error.

``` r
library(terra)
#> terra 1.5.43

bandratios<- function(red, green, blue, metrics){
  rg<- red/green
  names(rg)<- "red_green"
  rb<- red/blue
  names(rb)<- "red_blue"
  
  gr<- green/red
  names(gr)<- "green_red"
  gb<- green/blue
  names(gb)<- "green_blue"
  
  br<- blue/red
  names(br)<- "blue_red"
  bg<- blue/green
  names(bg)<- "blue_green"
  
  out<- c(rg, rb, gr, gb, br, bg)
  out<- subset(out, metrics)
  return(out)
}

s <- rast(system.file("ex/logo.tif", package="terra"))   

bandratios(s$red, s$green, s$blue, metrics = c("green_red", "blue_green"))
#> Error in eval(substitute(subset), nl, parent.frame()): object 'metrics' not found

metrics<- "red_blue" # varaible named metrics in global environment

bandratios(s$red, s$green, s$blue, metrics = c("green_red", "blue_green")) #expecting "green_red" and "blue_green" but will get "red_blue"
#> class       : SpatRaster 
#> dimensions  : 77, 101, 1  (nrow, ncol, nlyr)
#> resolution  : 1, 1  (x, y)
#> extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#> source      : memory 
#> name        : red_blue 
#> min value   :        0 
#> max value   :      Inf
```

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
I agree and have made that change. NSE is not that helpful anyway in `subset<SpatRaster>` and the example where a variable is taken from the global environment is horrible that I now wonder if I should remove it altogether.

**Comment by ailich** [comment]
Thanks, I would say the one nice feature of NSE is the ability to remove specific layers. That could alternatively be done though like in raster with a `dropLayer` function or by adding an argument to indicate that you want the opposite of the subset you specified (e.g. a `negate` argument). 

``` r
library(terra)
#> terra 1.5.44

subset2<- function(x, subset, negate=FALSE){
  if(negate){
    subset<- names(s)[!(names(s) %in% subset)]
    }
  return(subset(x,subset))
  }

s <- rast(system.file("ex/logo.tif", package="terra"))

subset2(s, subset = c("red", "blue"))
#> class       : SpatRaster 
#> dimensions  : 77, 101, 2  (nrow, ncol, nlyr)
#> resolution  : 1, 1  (x, y)
#> extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#> source      : logo.tif 
#> names       : red, blue 
#> min values  :   0,    0 
#> max values  : 255,  255

subset2(s, subset = c("red", "blue"), negate=TRUE)
#> class       : SpatRaster 
#> dimensions  : 77, 101, 1  (nrow, ncol, nlyr)
#> resolution  : 1, 1  (x, y)
#> extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#> source      : logo.tif 
#> name        : green 
#> min value   :     0 
#> max value   :   255
```

<sup>Created on 2022-06-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
