### ISSUE TITLE
Saving merged rasters within the merge call does not save all data if datatype is INT2U

### ISSUE THREAD

**Issue by emuise** [rspatial/terra#675]
When merging multiple rasters and trying to save within the merge call, if the datatype is INT2U it only writes the data from the first raster. Workaround is to merge and save separately, but with large rasters this involves multiple writes as it saves to the temp file I believe? 

Reprex. If you change the datatype to FLT4S it will save properly.
```
library(terra)
x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, ncols=30, nrows=30)
z <- rast(xmin=-80, xmax=-50, ymin=40, ymax=70, ncols=30, nrows=30)
values(x) <- (1:ncell(x) + rnorm(ncell(x), mean = 500, sd = 20))
values(z) <- (1:ncell(z) + rnorm(ncell(z), mean = 20, sd = 20))

# single band raster
save_path_single <- "save_single_pipe.dat"
save_path_single_not_pipe <- "save_single_not_pipe.dat"

s <- sprc(x, z) 
merge(s, filename = save_path_single,   datatype = "INT2U",   filetype = "ENVI",    overwrite = T)
rast(save_path_single) |> plot()

merged_single <-  merge(s)
plot(merged_single)

writeRaster(merged_single,  save_path_single_not_pipe, datatype = "INT2U",  filetype = "ENVI",  overwrite = T)
plot(rast(save_path_single_not_pipe))
```

**Comment by kadyb** [comment]
What is your `{terra}` version? It looks like saving is working in 1.5-34. However, you are losing precision by writing floating point numbers as integers.

![Rplot](https://user-images.githubusercontent.com/35004826/174137788-33add864-c06d-49cc-af9d-33227593c3d0.png)

**Comment by rhijmans** [comment]
I do not see this problem either, so I suppose @kadyb may be right in assuming you are using an older version of `terra`

**Comment by emuise** [comment]
I was on version 1.5-21. Thanks.

**Comment by rhijmans** [comment]
Thanks for confirming, good to know.
