### ISSUE TITLE
Generating tiles from multiple rasters with terra

### ISSUE THREAD

**Issue by mixiangcheng** [rspatial/terra#678]
I have about 20 large raster files with overlapping part between raster files.  I am trying to generate tiles of the whole region from these raster files. It is hard to mosiac these raster files into a very large raster file.  I have tried to generate tiles from SpatRasterCollection of these large rasters, but failed. Do I have to generate tiles with raster files one by one according to the coordinates? Or do you have some functions like catalog_retile() for LAScatalog-class in lidR?
Any help would be much appreciated!

**Comment by rhijmans** [comment]
Have you tried `makeTiles` with a SpatVector or (template) SpatRaster that covers the entire region?

**Comment by mixiangcheng** [comment]
Thanks for your quick reponse.  I am very new to terra. Could you give me more details?

**Comment by rhijmans** [comment]
This site is report bugs or ask for new features. This is not really the place for "how to" questions. You can try at stackoverflow.com or gis.stackexchange.com instead, but you would have to ask a more complete question (including a minimal, self-contained, reproducible example)

**Comment by mixiangcheng** [comment]
Thanks a lot for your kind message. I am trying using your methods. I will try at stackoverflow.com or gis.stackexchange.com.

 

发件人: ***@***.*** ***@***.***> 代表 Robert Hijmans
发送时间: 2022年6月21日 17:15
收件人: rspatial/terra ***@***.***>
抄送: mixiangcheng ***@***.***>; Author ***@***.***>
主题: Re: [rspatial/terra] Generating tiles from multiple rasters with terra (Issue #678)

 

This site is report bugs or ask for new features. This is not really the place for "how to" questions. You can try at stackoverflow.com or gis.stackexchange.com instead, but you would have to ask a more complete question (including a minimal, self-contained, reproducible example)
