### ISSUE TITLE
terra consuming huge amounts of space on my hard drive when using writeRaster

### ISSUE THREAD

**Issue by AndreMBellve** [rspatial/terra#68]
I have been trying to use `project` and `writeRaster` in my work flow. Initially I recieved an error from the following line:

```
#Reprojecting numeric rasters
numRast2000 <- terra::project(numRast, terra::crs(modelRast), method = "bilinear")
ERROR 3: Free disk space available is 3720503296 bytes, whereas 5505446016 are at least necessary. You can disable this check by defining the CHECK_DISK_FREE_SPACE configuration option to FALSE.
Error: [project] cannot create output dataset
```

I didn't think too much of it, although I was a little surprised that I had managed to use up 500 GB of hard drive space given this is a work laptop and I don't tend to install extraneous programs on it or duplicate files. Anyhow, I dismissed this and cleared off about 50 GB of space and assumed that would be enough for me to keep working.

I also decided to implement a `for` loop for the `project` function so that I check for any problematic rasters. Sure enough, I got part way through the reprojections and I started to hit errors:

```
#Reprojecting numeric rasters
for(i in 1:nlyr(numRast)){
  if(i == 1){
    numRast2000 <- terra::project(numRast[[i]], terra::crs(modelRast), method = "bilinear")
     }else{
      xx <- terra::project(numRast[[i]], terra::crs(modelRast), method = "bilinear")
      numRast2000 <- c(numRast2000, xx)
   }
print(i)
 }
[1] 1
[1] 2
[1] 3
[1] 4
Error in x@ptr$collapse_sources() : std::bad_alloc
```
I thought this was odd, and I checked the raster in question and then tried to reproject just that raster:
```
numRast[[5]]
class       : SpatRaster 
dimensions  : 14900, 10200, 1  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : 1990000, 3010000, 5300000, 6790000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +towgs84=59.47,-5.04,187.44,0.47,-0.1,1.024,-4.59929999996334 +units=m +no_defs 
data source : precip_driestQtr.tif 
names       : precip_driestQtr 
min values  :               51 
max values  :             2408 

#reprojecting single raster
test <- terra::project(numRast[[5]], terra::crs(modelRast), method = "bilinear")
```

and it worked... So I bound `test` to my collection and reprojected the next in line. However, when I tried to bind the 6th onto the collection I again got `Error in x@ptr$collapse_sources() : std::bad_alloc`. I decided it was time to post the issue and thought I would write the projected rasters I had so far to file so as to save some time as it takes roughly an hour to do 9 rasters. I managed to get part way through `writeRaster` before I hit this: `Error: [writeRaster] insufficient disk space (perhaps from temporary file)` - I thought this was odd since the total file space of all the rasters I am dealing with only amounts to 1.2 GB.

I checked my storage space and my temporary files account for 121 GB of space; and has completely maxed out my drive again. Of that 121, <3gb are my downloads, thumbnails and old windows update files. It is unclear how much of the 121 GB are down to terra as I can't find where terra's temproary files are stored but I suspect a lot of it (at least 50 GB) must be. 

I am not sure if these two issues are linked, but since I hit them in tandem I thought I would post them as such.

Is there a way to trim the temporary file size down? 
Where are these being stored on a Windows 10 X64 machine, and can I delete them?

Here is my session info:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
[3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] viridis_0.5.1       viridisLite_0.3.0   dismo_1.1-4         blockCV_2.1.1      
 [5] rasterVis_0.48      latticeExtra_0.6-29 lattice_0.20-41     raster_3.3-7       
 [9] sp_1.4-2            terra_0.8-2         sf_0.9-4            forcats_0.5.0      
[13] stringr_1.4.0       dplyr_1.0.0         purrr_0.3.4         readr_1.3.1        
[17] tidyr_1.1.0         tibble_3.0.1        ggplot2_3.3.2       tidyverse_1.3.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         lubridate_1.7.9    prettyunits_1.1.1  zoo_1.8-8         
 [5] png_0.1-7          class_7.3-17       assertthat_0.2.1   packrat_0.5.0     
 [9] R6_2.4.1           wesanderson_0.3.6  cellranger_1.1.0   backports_1.1.8   
[13] reprex_0.3.0       e1071_1.7-3        httr_1.4.1         pillar_1.4.4      
[17] progress_1.2.2     rlang_0.4.6        readxl_1.3.1       rstudioapi_0.11   
[21] hexbin_1.28.1      blob_1.2.1         munsell_0.5.0      broom_0.5.6       
[25] compiler_4.0.2     modelr_0.1.8       pkgconfig_2.0.3    tidyselect_1.1.0  
[29] gridExtra_2.3      codetools_0.2-16   fansi_0.4.1        crayon_1.3.4      
[33] dbplyr_1.4.4       withr_2.2.0        grid_4.0.2         nlme_3.1-148      
[37] jsonlite_1.7.0     gtable_0.3.0       lifecycle_0.2.0    DBI_1.1.0         
[41] magrittr_1.5       units_0.6-7        scales_1.1.1       KernSmooth_2.23-17
[45] cli_2.0.2          stringi_1.4.6      fs_1.4.2           xml2_1.3.2        
[49] ellipsis_0.3.1     generics_0.0.2     vctrs_0.3.1        RColorBrewer_1.1-2
[53] tools_4.0.2        glue_1.4.1         hms_0.5.3          jpeg_0.1-8.1      
[57] parallel_4.0.2     colorspace_1.4-1   classInt_0.4-3     rvest_0.3.5       
[61] haven_2.3.1      
```

**Comment by AndreMBellve** [comment]
I don't know if this helps, but my `writeRaster` loop quite out after writing just 2 rasters of 6, claiming hard drive space as the reason. I cleared some more space just now to see about writing a few more rasters and it immediately threw this:

```
Error in (function (cond)  : 
  error in evaluating the argument 'filename' in selecting a method for function 'writeRaster': std::bad_alloc
```

This is my `for` loop for `writeRaster`:
```
for(i in 1:nlyr(numRast2000)){
  terra::writeRaster(numRast2000[[i]], 
                     paste("./data/Raster/Contemporary/NZGD2000/",  
                           names(numRast2000[[i]]), ".tif", sep = ""), 
                     overwrite = TRUE)
  print(i)
}
```

**Comment by rhijmans** [comment]
There is a lot there that I need to chew on. Here are two quick points 

1) you can avoid temp files by adding filename arguments to methods. In stead of 

`terra::project(numRast[[i]], terra::crs(modelRast), method = "bilinear") `

You can do

`terra::project(numRast[[i]], terra::crs(modelRast), method = "bilinear", filename="myfile.tif")`

2) tempfiles are in the R temp folder. See ` tempdir()` for the tempdir in your current session. They are normally deleted when you exit R. But if R crashes they are not removed; that is what may have happened. They are easy to spot as they have similar names to that of the current `tempdir()`

You can find old `terra` temp files with

`ff <- tmpFiles(old=TRUE)`

and remove them with 

`tmpFiles(old=TRUE, remove=TRUE)`

**Comment by AndreMBellve** [comment]
Just thought I would update you quicky - the code you supplied for removing the temporary files managed to clear up a full ~120 gb of space! I will update my `project` calls as you have suggested! Thanks for the help Robert!

**Comment by rhijmans** [comment]
Great. Then I will  close this issue. Please let me know if you see `Error in x@ptr$collapse_sources() : std::bad_alloc` again. I am not sure if that is related to disk size of another problem.

**Comment by AndreMBellve** [comment]
I am afraid I don't have access to all my scripts as I am wearing a different hat today, and don't have access to my PhD files. However, after I cleared the temporary files and rewrote my project calls, I hit the same error message (`Error in x@ptr$collapse_sources() : std::bad_alloc`) when I tried to bind the newly projected raster to the old collection.

I will try and supply more details tomorrow. Would you like me to open it as a separate issue and rewrite it focussing on that particular issue?

**Comment by rhijmans** [comment]
Thanks, we can just continue here. That error suggests that you have very large datasets in memory (but my understanding is that they are on disk). I added some code to stop that, maybe a fix. To understand what is happening, perhaps you can create a list in your loop.   

```
x <- list()
for(i in 1:nlyr(numRast)){
    print(i); flush.console()
    x[[i]] <- terra::project(numRast[[i]], terra::crs(modelRast), method = "bilinear")
 }
```
And then do `c` calls step by step,  or `do.call(c, x)`,  or `rast(x)`  when it is done.

**Comment by rhijmans** [comment]
Are you using 32 bit R?

**Comment by AndreMBellve** [comment]
No, 64 bit R (x86_64-w64-mingw32/x64 (64-bit))

**Comment by AndreMBellve** [comment]
I have run the loop that you suggested, along with the subsquent `rast` binding and it all worked. However, I did notice that all the files that `project` wrote to my directory are rather large and all identical sizes:

![image](https://user-images.githubusercontent.com/43392206/87606317-cda8f500-c74e-11ea-8a19-8d5c7296a02e.png)

even though the original files are no where near that size:

![image](https://user-images.githubusercontent.com/43392206/87606452-1bbdf880-c74f-11ea-8a5f-3abf7c8ea9ab.png)

**Comment by mdsumner** [comment]
I wanted to ask earlier, but you aren't using a *target grid* in project(x, y) for `y`  - only a crs, so the process has to figure out the re-projected extent and guess at a reasonable resolution - I'd guess that's where the extra size is coming in. Not all transformations can result in equivalent sizes, though, but better to be explicit so you know what you get. Can you show the printed output of `numRast2000` and `numRast[[1]]`?

**Comment by AndreMBellve** [comment]
Sure can! Sorry, I am quite new to spatial data and still learning the ropes unfortunately. Also, RStudio has crashed since I last sorted all my files, so I don't have the complete collection. I can run the full complement of projections again tonight if it helps but here is just the output of the first raster in the collection pre- and post-projection (note `project` using a `crs` call took <5-10 minutes for a single raster):
```
numRast[[1]]
class       : SpatRaster 
dimensions  : 14900, 10200, 1  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : 1990000, 3010000, 5300000, 6790000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +towgs84=59.47,-5.04,187.44,0.47,-0.1,1.024,-4.59929999996334 +units=m +no_defs 
data source : aspect_eastness.tif 
names       : aspect_eastness 
min values  :              -1 
max values  :               1 


numRast2000
class       : SpatRaster 
dimensions  : 14952, 10228, 1  (nrow, ncol, nlyr)
resolution  : 99.79131, 99.79131  (x, y)
extent      : 1079648, 2100314, 4737317, 6229396  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
data source : test.tif 
names       : aspect_eastness 
min values  :              -1 
max values  :               1 
```
I didn't actually notice previously but I see now that it has changed my resolution and extent.... Is there any other way of maintaining the resolution? I also ran the same `project` line but using a model raster, rather than just pulling it's CRS  using:

`numRast2000 <-  terra::project(numRast[[1]], modelRast, filename = f[1], method = "bilinear", overwrite = TRUE)`

Is that what you meant by using a target grid? If so, it is taking much much longer to run, as it has already been running for close to an hour (and is yet to finish) for a single raster, and the file it is producing is at ~14gb and counting, from the original 0.07gb.

I will post what the object prints as soon as it is done!

**Comment by rhijmans** [comment]
The first question I would ask is do you have to project your large data?  If it is to combine it with vector data, it is better to transform the vector data. But if you different raster data sources there is often no choice. 

If you need to do it, you want to carefully choose your target grid, such that is has the extension and resolution you want. I also make sure I have round numbers for the extent so that you do not get nasty problems where things don't match because of floating point imprecision. 

Here is how you can make a template  target grid for your data

```
library(terra)
crs <- "+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80"
r <- rast(xmin=1079600, xmax=2100400, ymin=4737300, ymax=6229300, res=100, crs=crs)
r
#class       : SpatRaster 
#dimensions  : 14920, 10208, 1  (nrow, ncol, nlyr)
#resolution  : 100, 100  (x, y)
#extent      : 1079600, 2100400, 4737300, 6229300  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +units=m +no_defs 
```

If yours is running a long time, I am guessing that either the resolution is too high, or the extent too large. 

As for file size, try using compression. That can take off 70% of the file size. You can do this:

`project(x, y, filename="file.tif", wopt=list(gdal="COMPRESS=LZW"))`

I believe `LZW` compresses well, without a huge speed penalty.

**Comment by AndreMBellve** [comment]
Thank you! I will give that a try now, and I really appreciate the rapid help!

**Comment by rhijmans** [comment]
You could also save 1/3 of disk space by using separate rasters for the North and South islands --- but that makes your workflow more complex.

**Comment by rhijmans** [comment]
Closing this now, but feel free to reopen or restart if need be.
