### ISSUE TITLE
terra::mask() and terra::project() not working

### ISSUE THREAD

**Issue by trishagopalakrishna** [rspatial/terra#680]
I am reruning some scripts I had written about a year ago. The first few lines include simple crop() and mask() of raster 2 with a shapefile, after the shapefile was transformed using st_transform() to match crs of raster 2. The crop() runs fine, but the mask() ends after 2-3 min with the error 

`Error: [project] file exists. You can use 'overwrite=TRUE' to overwrite it.`

I then decided to crop and mask raster 1 with shapefile in QGIS. Then I proceeded with the rest of the code which includes projecting raster 1 to match crs, pixel size, extent etc of raster 2. The project() also fails after a couple of minutes with the same error.

The details of the raster 1 that I am projecting to match crs, extent and cell size of raster 2 are below. The shapefile I am using to crop both rasters is after-

Raster 1
class       : SpatRaster 
dimensions  : 288, 293, 1  (nrow, ncol, nlyr)
resolution  : 0.1, 0.1  (x, y)
extent      : 68.15, 97.45, 6.75, 35.55  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : <<<<<< tif name on file>>>>>>>
name        : pred 
min value   :    1 
max value   :    1 

Raster 2
class       : SpatRaster 
dimensions  : 33303, 32539, 1  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : 7590400, 10844300, 902000, 4232300  (xmin, xmax, ymin, ymax)
coord. ref. : WGS 84 / Pseudo-Mercator (EPSG:3857) 
source      : <<< name on file>>>>>>
color table : 1 
name        : discrete_classification 
min value   :                      20 
max value   :                     200 

Shapefile
Simple feature collection with 1 feature and 1 field
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 68.18625 ymin: 8.076526 xmax: 97.41516 ymax: 35.50133
Geodetic CRS:  WGS 84
  FID                       geometry
1   0 MULTIPOLYGON (((80.1918 13....

I have used following terraOptions
`terraOptions(memfrac=0.7, tempdir = "C://Users//myname//OneDrive - Nexus365//Paper3//Scratch",todisk= TRUE, progress=10)`. I am using the latest CRAN version of terra 1.5-34.

And the scratch folder is empty apart from the files that are created when running crop(), mask(), project()

**Comment by rhijmans** [comment]
Can you please show your script (at least the part that matters), and the output (error messages), where it happens? Also, you use an "sf" object (that you refer to as "shapefile", but that is not correct); to work with terra you would use a SpatVector instead.  Also, what happens (in a clean session) if you do not set the `terraOptions`?

**Comment by trishagopalakrishna** [comment]
Here is the script for cropping and masking raster 2 with an sf object, which I specify as a spatvector when using it

`Sys.time();copernicus_lulc_crop<- terra::crop(copernicus_lulc, vect(national_shp_proj), mask= T)
copernicus_lulc_mask<- terra::crop(copernicus_lulc_crop, vect(national_shp_proj), maskvalues=0, updatevalue= NA)
Sys.time()`

The error after running the first line is
`Error: [crop] file exists. You can use 'overwrite=TRUE' to overwrite it`.

As of yesterday, the crop line at least worked. And then when I ran the second line, I got the error
`Error: [mask] file exists. You can use 'overwrite=TRUE' to overwrite it`.

But now even the crop has stopped working and giving me the overwrite error. 

I have rerun the above lines in a frehs script without the specifying the terraOptions(), same error. 

Same error using terra::project() as well as mentioned in my first comment

**Comment by rhijmans** [comment]
Please show the exact and more complete script and output from the R console. Also please include sessionInfo()
Something like 

```
library(terra)
#terra 1.5.44
copernicus_lulc <- rast("filename.tif")
copernicus_lulc
#
#
v <- vect(national_shp_proj)
v
#
#
copernicus_lulc_crop<- terra::crop(copernicus_lulc, v, mask=T)
#Error: [crop] file exists. You can use 'overwrite=TRUE' to overwrite it.

sessionInfo()
# ...
```

**Comment by trishagopalakrishna** [comment]
Chunk 1
````{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
````
Chunk 2
````{r echo=FALSE, include=FALSE}
library(RColorBrewer)

library(tidyverse)
library(raster)

library(ggplot2)
library(sf)

library(tmap)
library(RColorBrewer)
library(viridis)

library(terra)


terraOptions(memfrac=0.7, tempdir = "C://Users//Trisha_Gopalakrishna//OneDrive - Nexus365//Paper3//Scratch",todisk= TRUE, progress=10, overwrite= T)
rasterOptions(overwrite = TRUE, tmpdir = "C://Users//Trisha_Gopalakrishna//OneDrive - Nexus365//Paper3//Scratch",tmptime = 2, progress="window", timer = TRUE,chunksize = 2e+07, maxmemory = 1e+09)

````

Chunk 3
````
state_shp_noislands<- st_read("C://Users//Trisha_Gopalakrishna//OneDrive - Nexus365//Paper3//Data//Admin//subjur_boundaries.shp")
plot(state_shp_noislands)
national_shp<-state_shp_noislands %>% st_union()
forpresence<-rast("C://Users//Trisha_Gopalakrishna//OneDrive - Nexus365//Paper3//Outputs//BiophysicalEnvelope//rfpred_threshold_forestpresence_1only.tif")
forpresence #0.1 deg, WGS 1984`
copernicus_lulc<-rast("C://Users//Trisha_Gopalakrishna//OneDrive - Nexus365//Paper3//Data//Admin//Copernicus_LULC//India_LULC_native.tif")
copernicus_lulc #100m WGS 1984 Mercator Projection

national_shp_proj<-st_transform(national_shp, crs = st_crs(copernicus_lulc))

Sys.time();copernicus_lulc_crop<- terra::crop(copernicus_lulc, vect(national_shp_proj), mask= T); Sys.time()
Sys.time();copernicus_lulc_mask<- terra::crop(copernicus_lulc_crop, vect(national_shp_proj), maskvalues=0, updatevalue= NA); Sys.time()
Sys.time();forpresence_proj<-terra::project(forpresence, copernicus_lulc_studyarea, method="near", mask=TRUE); Sys.time()
forpresence_proj
````

Error on running 3rd last line in previous chunk
`Error: [crop] file exists. You can use 'overwrite=TRUE' to overwrite it`

SessionInfo()
````
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] terra_1.5-34       viridis_0.6.2      viridisLite_0.4.0  tmap_3.3-3         sf_1.0-7          
 [6] raster_3.5-15      sp_1.5-0           forcats_0.5.1      stringr_1.4.0      dplyr_1.0.9       
[11] purrr_0.3.4        readr_2.1.2        tidyr_1.2.0        tibble_3.1.7       ggplot2_3.3.6     
[16] tidyverse_1.3.1    RColorBrewer_1.1-3

loaded via a namespace (and not attached):
 [1] fs_1.5.2           lubridate_1.8.0    httr_1.4.3         tools_4.2.0        backports_1.4.1   
 [6] utf8_1.2.2         rgdal_1.5-32       R6_2.5.1           KernSmooth_2.23-20 DBI_1.1.2         
[11] colorspace_2.0-3   withr_2.5.0        gridExtra_2.3      tidyselect_1.1.2   leaflet_2.1.1     
[16] compiler_4.2.0     leafem_0.2.0       cli_3.3.0          rvest_1.0.2        xml2_1.3.3        
[21] scales_1.2.0       classInt_0.4-7     proxy_0.4-27       digest_0.6.29      rmarkdown_2.14    
[26] base64enc_0.1-3    dichromat_2.0-0.1  pkgconfig_2.0.3    htmltools_0.5.2    dbplyr_2.2.0      
[31] fastmap_1.1.0      htmlwidgets_1.5.4  rlang_1.0.2        readxl_1.4.0       rstudioapi_0.13   
[36] generics_0.1.2     jsonlite_1.8.0     crosstalk_1.2.0    car_3.1-0          magrittr_2.0.3    
[41] Matrix_1.4-1       Rcpp_1.0.8.3       munsell_0.5.0      fansi_1.0.3        abind_1.4-5       
[46] lifecycle_1.0.1    stringi_1.7.6      leafsync_0.1.0     yaml_2.3.5         carData_3.0-5     
[51] tmaptools_3.1-1    grid_4.2.0         parallel_4.2.0     crayon_1.5.1       lattice_0.20-45   
[56] haven_2.5.0        stars_0.5-5        hms_1.1.1          knitr_1.39         pillar_1.7.0      
[61] ggpubr_0.4.0       ggsignif_0.6.3     codetools_0.2-18   reprex_2.0.1       XML_3.99-0.10     
[66] glue_1.6.2         evaluate_0.15      modelr_0.1.8       png_0.1-7          vctrs_0.4.1       
[71] tzdb_0.3.0         cellranger_1.1.0   gtable_0.3.0       assertthat_0.2.1   xfun_0.31         
[76] lwgeom_0.2-8       broom_0.8.0        e1071_1.7-11       rstatix_0.7.0      class_7.3-20      
[81] units_0.8-0        ellipsis_0.3.2    

````

**Comment by rhijmans** [comment]
And can you also try this with the development version?  I think the problem goes away with that version. Alternatively, do not use `mask=TRUE`.

**Comment by trishagopalakrishna** [comment]
> Can you please run this, in a clean session, and show what you see in the console?
> 
> ```
> library(terra)
> setwd("C://Users//Trisha_Gopalakrishna//OneDrive - Nexus365//Paper3/Data/Admin")
> v <- vect("subjur_boundaries.shp")
> v
> r <- rast("Copernicus_LULC//India_LULC_native.tif")
> r
> vp <- project(v, crs = crs(v))
> vp
> rvp <- crop(r, vp, mask= TRUE)
> #Error: [crop] file exists. You can use 'overwrite=TRUE' to overwrite it
> 
> SessionInfo()
> ```

I open a clean R script (without a project specified). 
I ran the above lines until vp <- project(v, crs = crs(v)).  Instead, I ran
`vp<- project(v, crs=crs(r))` because I want to match the CRS of the shapefile (WGS 1984) to that of the Copernicus data which is WGS 1985 and Mercator projection. 

This is the error I get now
`Error in .local(x, ...) : 
  unused arguments (crs = "PROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        DATUM[\"World Geodetic System 1984\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"unnamed\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    `

**Comment by rhijmans** [comment]
Thanks, it should be 

        vp <- project(v, crs(r))

But I think you found a bug that has been solved in the development version.

**Comment by trishagopalakrishna** [comment]
> Thanks, it should be
> 
> ```
>     vp <- project(v, crs(r))
> ```
> 
> But I think you found a bug that has been solved in the development version.

I reran using the above line of code. 
Then I ran the line rvp <- crop(r, vp, mask= TRUE). And I got the same error
`Error: [crop] file exists. You can use 'overwrite=TRUE' to overwrite it`

Then I reran rvp <- crop(r, vp) i.e. without the mask=T parameter and then it has run successfully. 
I then ran rvp_mask<- mask(rvp, vp) and now get the same error.
`Error: [mask] file exists. You can use 'overwrite=TRUE' to overwrite it`

I am currently using the CRAN version of terra. Please advise how to proceed with mask()

**Comment by trishagopalakrishna** [comment]
Ok I installed the development version and crop(), mask() and project() have successfully worked without the error. Thank you very much!
