### ISSUE TITLE
spatSample could benefit from an equivalent to sampleStratified's `exp` argument

### ISSUE THREAD

**Issue by mikemahoney218** [rspatial/terra#683]
When using `raster::sampleStratified()`, it was possible to control the number of points used as the initial sample through the `exp` argument:

``` r
library(raster)
#> Loading required package: sp
rr <- raster(ncol=100, nrow=100)
set.seed(1)
values(rr) <- round(runif(ncell(rr), 1, 3))
sampleStratified(rr, 1, exp = 100)
#>      cell layer
#> [1,] 1551     1
#> [2,] 4548     2
#> [3,] 8899     3
```

<sup>Created on 2022-06-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I don't _believe_ there's an equivalent for when using `spatSample(method = "stratified")`. A workaround is to sample many more cells than desired, and then filter down to the targeted number of cells, but I think it would be beneficial if the number of cells searched could be controlled directly in `spatSample`.

**Comment by rhijmans** [comment]
Thanks, I have added that argument.
