### ISSUE TITLE
freq function omitting label column

### ISSUE THREAD

**Issue by rojaff** [rspatial/terra#687]
When using the freq function on a categorical (land cover) raster containing labels, the value column shows values or labels depending on the bylayers argument:

`terra::freq(r, bylayer=FALSE) `
   value  count
1     11  52438
2     21  29632
3     22  29452
4     23  30113
5     24  21151
6     31   2649
7     41  81107
8     42 104817
9     43  71406
10    52   5128
11    71   4260
12    81  38510
13    82  21150
14    90  42879
15    95   664

`terra::freq(r)`
layer                        value  count
1      1                   Open Water  52438
2      1        Developed, Open Space  29632
3      1     Developed, Low Intensity  29452
4      1  Developed, Medium Intensity  30113
5      1    Developed, High Intensity  21151
6      1                  Barren Land   2649
7      1             Deciduous Forest  81107
8      1             Evergreen Forest 104817
9      1                 Mixed Forest  71406
10     1                  Shrub/Scrub   5128
11     1                   Herbaceous   4260
12     1                  Hay/Pasture  38510
13     1             Cultivated Crops  21150
14     1               Woody Wetlands  42879
15     1 Emergent Herbaceous Wetlands   6642

 I believe the label column is missing, according to your help: "If any of the layers of x is categorical, there is an additional column (label)."

**Comment by rhijmans** [comment]
Thank you. That was intentional, but the manual was not clear. I have simplified the situation such that you always get the labels. Also, the object returned is always a `data.frame` (not sometimes a `matrix`).
