### ISSUE TITLE
Support for 'yearmon' in time attribute recently lost

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#690]
Dear Robert and all developers,

I just realised that the last version of terra (terra 1.5.34) does not have support for [`yearmon`](https://www.rdocumentation.org/packages/zoo/versions/1.8-10/topics/yearmon) (month and year only, from `zoo` package) to be used in the time attribute.

I know that the documentation of the `time` function has never mentioned some support for `yearmon` objects. However, until recently I was using `yearmon` without problemas with previous versions of the terra package.

Considering that there are a plethora of variables where using a monthly time scale for analysis is quite common (e.g., precipitation, air temperature, evapotranspiration), would it be possible to restore the support for `yearmon` objects in the next versions of the terra package? 

If necessary, I would be happy to contribute with it, but I'm not expert in S4 classes.

**Comment by rhijmans** [comment]
Indeed, there never was support for that, but I think that "time" used to be stored as numeric, and now it is an integer, such that you lose the months (the decimal part of the year, in a yearmon object)?  I have made some changes, and now I get the below. 

```
library(zoo)
library(terra)
x <- rast(ncol=5, nrow=5, nlyr=12)
time(x) <- yearmon(2000 + (0:11)/12)
x
#class       : SpatRaster 
#dimensions  : 5, 5, 12  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#time (ymnts): 2000-Jan to 2000-Dec 

time(x)
# [1] 2000.000 2000.083 2000.167 2000.250 2000.333 2000.417 2000.500 2000.583
# [9] 2000.667 2000.750 2000.833 2000.917
yearmon(time(x))
# [1] "Jan 2000" "Feb 2000" "Mar 2000" "Apr 2000" "May 2000" "Jun 2000"
# [7] "Jul 2000" "Aug 2000" "Sep 2000" "Oct 2000" "Nov 2000" "Dec 2000"
``` 

`time(x)` does not return a `yearmon` object, because that would require a dependency on "zoo". But that must have been the same in earlier versions.

In contrast, `time(x)` does return `Date` and `POSIX` objects where appropriate. 

Other time steps that are available: 

```
time(x, tstep="years") <- 2000 + 0:11
x
#class       : SpatRaster 
#dimensions  : 5, 5, 12  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#time (years): 2000 to 2011 
 
time(x, tstep="months") <- 1:12
x
#class       : SpatRaster 
#dimensions  : 5, 5, 12  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#time (mnts) : Jan to Dec 
 
time(x) <- as.Date("2001-01-01") + 0:11
x
#class       : SpatRaster 
#dimensions  : 5, 5, 12  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#time (days) : 2001-01-01 to 2001-01-12 
 
time(x) <- as.POSIXlt(as.Date("2001-01-01") + 0:11)
x
#class       : SpatRaster 
#dimensions  : 5, 5, 12  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#time        : 2001-01-01 to 2001-01-12 UTC 
 
time(x) <- as.POSIXlt(Sys.time(), "America/New_York") + 0:11
x
#class       : SpatRaster 
#dimensions  : 5, 5, 12  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#time        : 2022-06-25 18:07:32 to 2022-06-25 18:07:43 EDT 
```
