### ISSUE TITLE
Spatvector conversion issue

### ISSUE THREAD

**Issue by bernorev** [rspatial/terra#71]
Hi,

I'm having trouble converting spatvectors to sp/sf objects.

I have 5 class tiff's that I need to convert to polygons. Reading and plotting gives : 
```
r <- rast("E2.tif")    
plot(r)
```
![image](https://user-images.githubusercontent.com/57282983/87870244-5ec5d900-c9a6-11ea-9bab-2dd48cdc9f76.png)

Converting to polygons works very well 
`plot(as.polygons(r))`
![image](https://user-images.githubusercontent.com/57282983/87870305-cb40d800-c9a6-11ea-9424-e349f550ebcb.png)

Trying to convert it to SpatialPolygonsDataFrame breaks the polygons

`plot(as(poly,"Spatial"))
`
![image](https://user-images.githubusercontent.com/57282983/87870335-2b377e80-c9a7-11ea-9606-6b2734b9fc13.png)

This is also the same as trying to plot the spatvector directly with spplot(). At the moment my workaround is to save the spatvector to a tempfile as a shp, then reading back in with sf.

```
tmpf2 <- tempfile()
writeVector(poly, tmpf2, overwrite=TRUE)
s<- st_read(tmpf2)
plot(s)
```

![image](https://user-images.githubusercontent.com/57282983/87870356-7a7daf00-c9a7-11ea-85c8-0cf8efdd5375.png)

**Comment by rhijmans** [comment]
Thanks for pointing this out.  I fixed this in `raster` and if you install the development version of that [package](https://github.com/rspatial/raster) (version >= 3.3-14) the below will work as expected

```
library(terra)
f <- system.file("ex/test.tif", package="terra") 
r <- rast(f)
x <- classify(r, c(0,400,600,2000))
v <- as.polygons(x)

library(raster)
s <- as(v, "Spatial")
plot(s)
```

**Comment by BernoGreyling** [comment]
Awesome! Thanks so much for the quick response
