### ISSUE TITLE
plot (for SpatVector) attributes from external data frame

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#711]
Hello! It woud be quite useful to map columns of a data frame without necessarily merging it with a SpatVector (e.g. when we're running a long analysis that produces many intermediate data frames and we want to map some of their columns on the way, without making the SpatVector huge or creating multiple ones). It could be with something like `plot(x = mySpatVector, y = myTable$myColumn, idx = "site", idy = "site_code")` (the latter 2 would be new arguments in `terra::plot` specifying which column contains the common identifier in x and y, respectively). Regards,

**Comment by rhijmans** [comment]
You can now use argument `values` in two ways 

1) provide a vector of values that is in the correct order (as the rows of the SpatVector)

```
library(terra)
v <- vect(system.file("ex/lux.shp", package="terra"))
plot(v, values=10:21, breaks=seq(10,22,2))
text(v, 10:21)
``` 

2) Provide a `data.frame` with two columns. The first column name and values must match a variable in `x`  (but the order does not matter)

```
d <- unique(data.frame(NAME_1 = v$NAME_1, abb=substr(v$NAME_1, 1, 3)))
d <- d[3:1, ]
plot(v, values=d)
``` 

Does that work for you?

**Comment by AMBarbosa** [comment]
It does indeed, thanks!
