### ISSUE TITLE
terra cant find values that raster can in some files

### ISSUE THREAD

**Issue by mikejohnson51** [rspatial/terra#714]
Hi @rhijmans,

First, a sincere thank you for this package.

On very rare occasion I have found datasets that `raster` can read values from but that `terra` cannot. 

Here is one example from an HDF file containing LAI values.

``` r
library(terra)
#> terra 1.6.1
library(raster)
#> Loading required package: sp
library(httr)

GET('http://www.glass.umd.edu/LAI/MODIS/250m/2012/001/GLASS01D01.V60.A2012001.h11v05.2022012.hdf', write_disk("tmp.hdf"))
#> Response [http://www.glass.umd.edu/LAI/MODIS/250m/2012/001/GLASS01D01.V60.A2012001.h11v05.2022012.hdf]
#>   Date: 2022-07-14 22:11
#>   Status: 200
#>   Content-Type: application/x-hdf
#>   Size: 6.21 MB
#> <ON DISK>  tmp.hdf

r = raster("tmp.hdf")
plot(r)
```

![](https://i.imgur.com/CPGvDDM.png)

``` r

t  = rast('tmp.hdf')
plot(t)
#> Warning: [plot] SpatRaster has no cell values
```

![](https://i.imgur.com/1Lr0mUm.png)

``` r

unlink('tmp.hdf')
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I can certainly get by using raster, but it would be great if terra was able to recognize these values as well. 

Thanks again for everything you do for this community. 

Mike

**Comment by rhijmans** [comment]
Thanks, it worked for me with the CRAN version, and it now also works with the dev version again. Glad you caught this before releasing the next version to CRAN.

**Comment by mikejohnson51** [comment]
Thanks for the quick response!! I am likely getting the dev version from the wrong spot - if so please ignore - but I am still seeing the same:

``` r
# remove.packages('terra')
# install.packages('terra', repos='https://rspatial.r-universe.dev', force = TRUE)

library(terra)
#> terra 1.6.1

library(httr)

GET('http://www.glass.umd.edu/LAI/MODIS/250m/2012/001/GLASS01D01.V60.A2012001.h11v05.2022012.hdf', write_disk("tmp.hdf"))
#> Response [http://www.glass.umd.edu/LAI/MODIS/250m/2012/001/GLASS01D01.V60.A2012001.h11v05.2022012.hdf]
#>   Date: 2022-07-15 01:20
#>   Status: 200
#>   Content-Type: application/x-hdf
#>   Size: 6.21 MB
#> <ON DISK>  tmp.hdf

t = rast("tmp.hdf")
plot(t)
#> Warning: [plot] SpatRaster has no cell values
```

![](https://i.imgur.com/iu6GJUI.png)

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kadyb** [comment]
@mikejohnson51, I saw that there were some problems with building the new version on R-universe (https://github.com/r-universe/rspatial/actions/runs/2673962088), so you probably downloaded the old one. Please try again.

**Comment by mikejohnson51** [comment]
@kadyb sorry that server went down and I forgot to respond! Yes, v1.6.3 from R-universe works for me. Thanks for the help!
