### ISSUE TITLE
Applying rast() to .grib2 files results in spurious error message

### ISSUE THREAD

**Issue by BlueGrisGris** [rspatial/terra#715]
Hi!

When reading in .grib2 files with `rast()` I receive the message: 

```
Warning: Inside GRIB2Inventory, Message # 2  
ERROR: Couldn't find 'GRIB' or 'TDLP'
```
However, the command seems to work as intended.  R itself does not `stop()` and the resulting SpatRaster has all the information I would expect.  I googled these error messages and not much came up- perhaps it has to do with a .xml file.  

Some of the .grib2 files in question are HRRR downloaded from AWS using the [herbie](https://github.com/blaylockbk/Herbie) python package if that is helpful.

Thanks!

**Comment by rhijmans** [comment]
This is probably something that would need to be looked at by the GDAL folks. But to get started: do you have an example file?

**Comment by BlueGrisGris** [comment]
Thanks for the response!
Sorry for the missing detail.  Here is a grib2 file of HRRR photosynthetically available radiation that is mostly zero because it is nighttime.  rast() results in the above error message, but otherwise everything seems fine.  

It wouldn't be an issue, except when applying rast() to say, a year's worth of these files, the cluster I am on runs out of memory, despite setting `terraOptions(memmax)` to be less than the amount of memory I have requested from slurm.

[grib2_example.zip](https://github.com/rspatial/terra/files/9143273/grib2_example.zip)

**Comment by kadyb** [comment]
For confirmation, these error messages come from GDAL, not `{terra}`:

```r
path = "./grib2_example/subset_5e796e48332af4142b10ca0f86e65d9bfdb05884__hrrr.t00z.wrfsfcf06.grib2"
system(paste("gdalinfo", path))
#> Warning: Inside GRIB2Inventory, Message # 2
#> ERROR: Couldn't find 'GRIB' or 'TDLP'
```

**Comment by BlueGrisGris** [comment]
> For confirmation, these error messages come from GDAL, not `{terra}`:

Thanks!  Do you know how to reproduce the error with GDAL so I can open an issue over there, if you want to close out this issue?

**Comment by kadyb** [comment]
I think the easiest way is to use `gdalinfo` from [command line](https://gdal.org/programs/gdalinfo.html) or [QGIS](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/gdal/rastermiscellaneous.html#gdalgdalinfo) and upload sample data. However, it seems to me that the memory problems are related to `{terra}` or computing cluster.

**Comment by BlueGrisGris** [comment]
Thank you.  `gdalinfo` from command line also results in the error.  Why do you think that the memory issue is `{terra}` or the cluster?

I have also had the [issue](https://gis.stackexchange.com/questions/436491/why-is-terraresample-failing-on-this-remote-environment-but-working-on-my-la) I posted on GIS stackexchange on the cluster, but not my laptop.  Could these issues be related?

**Comment by kadyb** [comment]
> Why do you think that the memory issue is `{terra}` or the cluster?

I just don't think the memory problems are related to the file format and the GDAL messages.

> Could these issues be related?

If you can process `.grib2` on your laptop in this case, but it doesn't work on the cluster, then I think the problem is with the cluster. If you prepare some reproducible examples, I can check it on my PC.

**Comment by BlueGrisGris** [comment]
>I just don't think the memory problems are related to the file format and the GDAL messages.

Got it thanks!  I think I have sidestepped the memory issue by processing 1 month at a time where possible.  I will pursue it further on the cluster side and report back anything relevant to `terra`.  Thanks for the package and the help!
