### ISSUE TITLE
Keep the Spatvec values while using extract()  

### ISSUE THREAD

**Issue by cscarpon** [rspatial/terra#718]
I am trying to generate training data using the extract() with point data. The point data have my labels and x, and y information. I want to extract values from rasters.  When I use the extract() it drops the labels and x,y data of the point data.

Is there an arg that I can input that will keep both the values of the original point data, while extracting values from the raster?

I have a workaround which adds the original data back, but it is a few extra lines and quite messy.

Thanks!

**Comment by rhijmans** [comment]
There is no argument. I do not think it is necessary, but people *do* ask for it a lot, so I should probably add it.  Until then, below I show a one (or two) liner solution 


```
# Example data 
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
xy <- spatSample(r, 100, as.points=TRUE, na.rm=TRUE)
names(xy) <- "sample"

# solution
v <- cbind(xy, extract(r, xy))

#or 
v <- cbind(xy, extract(r, xy)[,-1,drop=FALSE])
```

**Comment by rhijmans** [comment]
With the data from above, you can now also do:

```
extract(r, xy, as.spatvector=TRUE)
# class       : SpatVector 
# geometry    : points 
# dimensions  : 100, 2  (geometries, attributes)
# extent      : 5.8125, 6.454167, 49.49583, 50.12917  (xmin, xmax, ymin, ymax)
# coord. ref. : lon/lat WGS 84 (EPSG:4326) 
# names       : sample elevation
# type        :  <int>     <int>
# values      :    267       267
#                  320       320
#                  372       372
```

**Comment by cscarpon** [comment]
Awesome, thanks RHijmans!
