### ISSUE TITLE
Potential C++ dependency?

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#72]
This claims to work and be very fast https://github.com/isciences/exactextract/

**Comment by rhijmans** [comment]
And there a R package exactextractr --- I have not compared performance. The "exact" extraction in interesting. `raster` has an approximation.

**Comment by rhijmans** [comment]
In `terra` you can now also use the `weights=TRUE` argument, like in `raster`. For more precise estimations the exactextractr package is available. In the future I might implement something similar.
