### ISSUE TITLE
Installation failed (dev. version): input error in zonal.R

### ISSUE THREAD

**Issue by amarbler** [rspatial/terra#725]
Hi,

installing the latest dev version of terra fails for me due to an unexpected input error in zonal.R:

```
library(devtools)
install_github("rspatial/terra", configure.args="--with-proj-lib=/home/alm/.local/lib")

** R
Error in parse(outFile) :
  /home/alm/temp/RtmpstNDJC/R.INSTALL2970aa3975da17/terra/R/zonal.R:72:42: unexpected input
71:                         r <- !relate(x, z, "disjoint")
72:                         i <- apply(r, 1, \
                                             ^
ERROR: unable to collate and parse R files for package ‘terra’
* removing ‘/nas/home/alm/R/x86_64-pc-linux-gnu-library/4.0/terra’
* restoring previous ‘/nas/home/alm/R/x86_64-pc-linux-gnu-library/4.0/terra’
Warning message:
In i.p(...) :
  installation of package ‘/home/alm/temp/Rtmpj5x7TC/file296f875fd93072/terra_1.6-3.tar.gz’ had non-zero exit status
```

**Comment by rhijmans** [comment]
Thanks, fixed now. That is because you are using an older version of R that does not understand `\(x)` to be equivalent to `function(x)`

**Comment by amarbler** [comment]
Thank you for the quick fix! I can confirm that it works now.

**Comment by GreatEmerald** [comment]
This problem made it into CRAN 1.6-3, which makes `terra` not installable from CRAN on older versions of R. Would be good to have a CRAN update for this.

**Comment by rhijmans** [comment]
Yes, unfortunately, I send terra to CRAN just before this was fixed. They are on vacation now, but I will send a new version to CRAN in early August.
