### ISSUE TITLE
from version 1.5.21 to .34 the function as.factor works differently

### ISSUE THREAD

**Issue by strevisani** [rspatial/terra#726]
Hi,

moving from version 1.5.21 to 1.5.34 this command does not work anymore (same raster obviously). It seems that it is no more able to manage NAs.

landCover<-as.factor(rast("landCover.tif"))
Error: [set.cats] you cannot associate a category with NA

**Comment by rhijmans** [comment]
It looks like this works again in the development version:
```
library(terra)
#terra 1.6.4
r <- rast(ncol=3, nrow=3, vals=rep(1:3,3))
r[2,] <- NA
as.factor(r)
#class       : SpatRaster 
#dimensions  : 3, 3, 1  (nrow, ncol, nlyr)
#resolution  : 120, 60  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : lyr.1 
#min value   :     1 
#max value   :     3 
```

And here is a work-around for the CRAN version 

```
u <- unique(r)
u <- cbind(u, u)
names(u) <- c("value", "label")
levels(r) <- u
```

**Comment by strevisani** [comment]
Thank you Robert!

Sebastiano


*      Sebastiano Trevisani, Ph.D.*
*            Associate Professor*
*Applied and Environmental Geology*


*  https://orcid.org/0000-0001-8436-7798
<https://orcid.org/0000-0001-8436-7798>*
*IUAV University of Venice: www.iuav.it <http://www.iuav.it/>*

*Address: Dorsoduro 2206,  Venice 30123, Italy Tel:    +39. 041. 257
1299Mail:    ***@***.*** ***@***.***> *
*"Le opinioni espresse sono riferibili esclusivamente all'autore e non *
* riflettono in alcun modo una posizione ufficiale dello IUAV "*
*"The views expressed are purely those of the writer and may not in
any circumstances be regarded as stating an official position of the IUAV."*
