### ISSUE TITLE
passing arguments to a user function in the fun option of terra::focal

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#727]
I have some difficulties to implement my own user-defined function in the parameter `fun=` of the function `focal`. With the following code:

```
library(terra)
# terra 1.6.4
r <- rast(ncols=3, nrows=3, nlyrs=2, vals=rep(1:9,2),xmin=0,xmax=3,ymin=0,ymax=3)
 
MyMean <- function(x) mean(x, na.rm=TRUE) 
 
values(focal(r, w=3, fun=MyMean))
#       lyr.1 lyr.2
#  [1,]   3.0   5.0
#  [2,]   3.0   5.5
#  [3,]   3.5   5.5
#  [4,]   3.5   6.0
#  [5,]   4.0   6.0
#  [6,]   4.0   6.5
#  [7,]   4.5   6.5
#  [8,]   4.5   7.0
#  [9,]   5.0   7.0

values(focal(r, w=3, fun=mean, na.rm=T))
#       lyr.1 lyr.2
#  [1,]   3.0   3.0
#  [2,]   3.5   3.5
#  [3,]   4.0   4.0
#  [4,]   4.5   4.5
#  [5,]   5.0   5.0
#  [6,]   5.5   5.5
#  [7,]   6.0   6.0
#  [8,]   6.5   6.5
#  [9,]   7.0   7.0
```

I don't understand why the result is different with my user-defined function, `MyMean`, compared to a call to the build-in `mean `function.

Moreover, because the two layers of the r raster are the same, they should give the same focal layers. This is the case with the built-in `mean `function, but not with my user-defined function. Why?

I suppose it is a question of the arguments passed to the `focal `function. The documentation of the function tells that it "takes multiple numbers". But what are these numbers exactly?

**Comment by rhijmans** [comment]
I am puzzled about how this could be so wrong (the numbers are the same, but they are in the wrong order (row vs column wise). I believe it works now. 

"these numbers" are the focal values of a single cell.

**Comment by jldupouey** [comment]
Thanks, it works. A bit of a worrying bug, indeed. I'm working on a script in which I want to do 3d focal calculations (focal3d) on large rasters. I hope the extra dimension is handled well.
