### ISSUE TITLE
Extracting both weights and xy coordinates mixes values

### ISSUE THREAD

**Issue by lime-n** [rspatial/terra#729]
When I try the following on my spatial data:

```
extract(raster_data, vect_data, weights=TRUE, xy=TRUE)
```
I find that the values returned for the `weights` and `xy` get mixed up and I do not get the correct values.

I have tried this with some sample data:

```
r <- rast(ncols=5, nrows=5, xmin=0, xmax=5, ymin=0, ymax=5)
xy <- rbind(c(0.5,0.5), c(2.5,2.5))
p <- vect(xy, crs="+proj=longlat +datum=WGS84")

extract(r, p, weights=TRUE, xy=TRUE)
```
Which I think counts as minimal reproducible code to reproduce my issue. This also produces different `x,y` values mixed up with the `weights`.

**Comment by rhijmans** [comment]
That was indeed wrong. But "weights" are only available for polygons and you now get: 

```
library(terra)
r <- rast(ncols=5, nrows=5, xmin=0, xmax=5, ymin=0, ymax=5, vals=1:25)
xy <- rbind(c(0.5,0.5), c(2.5,2.5))
p <- vect(xy, crs="+proj=longlat +datum=WGS84")
extract(r, p, weights=TRUE, xy=TRUE)

#  ID lyr.1   x   y
#1  1    21 0.5 0.5
#2  2    13 2.5 2.5
#Warning message:
#[weights are ignored for point and lines data]  
```

'weights' ought to also work for "lines", but that is a different matter.
