### ISSUE TITLE
zonal() crashes R when using multiple large SpatRasters

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#73]
I have been trying to debug the issues that I've been having with the zonal() function - essentially, I wanted to compute zonal statistics on a set of input layers. The zonal() function runs fine when it is run on a single input layer; however, it caused R to crash when using multiple layers. It seems to have this issue when the input layers are greater than some defined size, as I couldn't replicate this problem with the example in the ?zonal help page. Here is some code that should replicate the issue:

```
library(terra)

# Load multilayer raster
r <- rast(system.file("ex/logo.tif", package = "terra")) 

# Create zonal raster layer 
z <- r[[1]]
values(z) <- rep(1:4, each = ncell(r) / 4, len = ncell(r))

# Run the zonal() function. This will crash R
zonal(r, z, "sum", na.rm = TRUE)

```

Another issue that I found with this function comes when duplicating the input data in the example from ?zonal. Using the following code will not produce the correct results for the second input layer:

```
library(terra)

# Create individual raster layers, and a combined layer
r1 <- rast(ncols = 10, nrows = 10)
values(r1) <- 1:ncell(r1)
r2 <- rast(ncols = 10, nrows = 10)
values(r2) <- seq(2, by = 2, length.out = ncell(r2))
r <- c(r1, r2)

# Create a zonal layer
z <- rast(r1)
values(z) <- rep(1:4, each = ncell(z) / 4)

# Run zonal statistics together - this will succeed (won't crash R), but the result is incorrect
zonal(r, z, "sum", na.rm = TRUE)

# Run zonal statistics individually - this will succeed with the correct results
zonal(r[[1]], z, "sum", na.rm = TRUE)
zonal(r[[2]], z, "sum", na.rm = TRUE)
```

For now, the work around seems to be to generate data frames for each input layer for a given zonal statistic and then merge them afterwards, though it would be nice to have this function not crash R when called with multiple input layers. In case it's needed, I'm using R 4.0.2, terra version 0.7.11, and using a 4-core Windows 10 64-bit machine with 8GB of RAM.

**Comment by rhijmans** [comment]
Thank you very much for reporting this and for the very good examples. This has been fixed now. I plan to send a new version to CRAN this week.
