### ISSUE TITLE
[enhancement] writeRaster: add 'bylayer' argument instead of using a vector of filenames (after #320)

### ISSUE THREAD

**Issue by hzambran** [rspatial/terra#731]
In #320 I asked whether it would be possible to add the bylayer argument to the `writeRaster` function, similarly to the same function in the `raster` package.

In the kind answer of @rhijmans when closing that issue, it was mentioned that a similar functionality could be obtained with the `writeRaster` function of the `terra` package using a vector of filenames with the same length as the number of layers in the SpatRaster:

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
ff <- paste0(names(s), ".tif")
z <- writeRaster(s, ff, overwrite=T)
z

#class       : SpatRaster 
#dimensions  : 77, 101, 3  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0, 101, 0, 77  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
#sources     : red.tif  
#              green.tif  
#              blue.tif  
#names       : red, green, blue 
#min values  :   0,     0,    0 
#max values  : 255,   255,  255 
```

That workaround works fine for hundreds or a few thousands of files. However, I realised that when the SpatRater object has ~two hundred thousand or more files the aforementioned procedure is way slower than using `raster::writeRaster` with the `bylayer` argument.

Is the previous behaviour due to some C optimisation in the way files are written when using `raster::writeRaster` with the `bylayer` argument?

Would it be possible to add the bylayer argument to the `writeRaster` function, similarly to the same function in the `raster` package?

**Comment by rhijmans** [comment]
I did some work on this a while ago, but did not get around to testing it. The below suggests to me that there is no degradation of writing speed (anymore).  Am I correct?

```
library(terra)
r <- rast(system.file("ex/elev.tif", package="terra"))

f <- function(n) {
	x <- rep(r, n)
	outf <- paste0(tempdir(), "/test", 1:n, ".tif")
	suppressWarnings(file.remove(outf))
	system.time(writeRaster(x, outf))[3]
	file.remove(outf)
}

steps <- c(1:5, 10,50,100,250,500,750,1000,5000,10000)
m <- sapply(steps, f)

round(m/steps, 3)
#elapsed elapsed elapsed elapsed elapsed elapsed elapsed elapsed elapsed 
#  0.040   0.030   0.027   0.023   0.026   0.023   0.025   0.022   0.021 
#elapsed elapsed elapsed elapsed elapsed 
#  0.022   0.022   0.022   0.023   0.025 

plot(steps, m)
abline(lm(m~steps))
```

**Comment by rhijmans** [comment]
As I haven't heard back I assume that this now works ok; if not we can reopen the issue.
