### ISSUE TITLE
Compiler warnings with icc

### ISSUE THREAD

**Issue by gareth-d-ga** [rspatial/terra#733]
When trying to compile with icc I found a warning, whereby a variable `i` is used in a loop, that is inside another loop, that already uses `i`: https://github.com/rspatial/terra/blob/ec9f977c230e54c1e6125299006e127149206e3d/src/raster_methods.cpp#L2055

The warning is: 
```
raster_methods.cpp(2055): warning #823: reference is to variable "i" (declared at line 2036) -- under old for-init scoping rules it would have been variable "i" (declared at line 2041)
  			if (!out.writeBlock(v, i)) return out;
```

I believe this is legal C++, but the meaning has changed over the years. So it might be worth distinguishing the loop variables.

**Comment by rhijmans** [comment]
Thank you for reporting this. Fixed.
