### ISSUE TITLE
error: ‘GEOSGeom_setPrecision_r’ was not declared in this scope

### ISSUE THREAD

**Issue by AragornSteiger** [rspatial/terra#734]
Hello,
I am attempting an install of terra 1.6-4 in R 4.1.0. Currently I am receiving this error:

g++ -std=gnu++11 -I"/wsu/el7/gnu7/R/R-4.1.0/lib64/R/include" -DNDEBUG -I/wsu/el7/gnu7/gdal/3.0.1/include -I/usr/include -I'/wsu/el7/gnu7/R/R-4.1.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c geos_methods.cpp -o geos_methods.o
geos_methods.cpp: In member function ‘SpatVector SpatVector::set_precision(double)’:
geos_methods.cpp:220:21: error: ‘GEOSGeom_setPrecision_r’ was not declared in this scope
   GEOSGeometry* r = GEOSGeom_setPrecision_r(hGEOSCtxt, g[i].get(), gridSize, 0);
                     ^~~~~~~~~~~~~~~~~~~~~~~
geos_methods.cpp:220:21: note: suggested alternative: ‘GEOSGeom_getDimensions_r’
   GEOSGeometry* r = GEOSGeom_setPrecision_r(hGEOSCtxt, g[i].get(), gridSize, 0);
                     ^~~~~~~~~~~~~~~~~~~~~~~
                     GEOSGeom_getDimensions_r
make: *** [geos_methods.o] Error 1
ERROR: compilation failed for package ‘terra’
* removing ‘/wsu/el7/gnu7/R/R-4.1.0/lib64/R/library/terra’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmpn3dbFf/file608774d052a2/terra_1.6-4.tar.gz’ had non-zero exit status

In case this helps, I have the configure info here:
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /wsu/el7/gnu7/gdal/3.0.1/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.0.1
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /wsu/el7/gnu7/gdal/3.0.1/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.0.1
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:    -I/wsu/el7/gnu7/gdal/3.0.1/include -I/usr/include
configure: Package LIBS: -lproj     -L/wsu/el7/gnu7/gdal/3.0.1/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars

I appreciate any assistance.
Thank you,
Aragorn.

**Comment by rhijmans** [comment]
Sorry about that. Should work now.
