### ISSUE TITLE
Better explain in man when an ID column is returned by extract

### ISSUE THREAD

**Issue by frousseu** [rspatial/terra#736]
Hello! 

It would be nice to better explain under what circumstances and `ID` column is returned by `extract`. For example, I would expect the first `extract` here to have an `ID` column like the second, but it doesn't. Unless the first `extract` should also have an `ID` column even though it may not be as useful as in the second case? This is with terra_1.6-3.

```r
library(terra)
r <- rast(ncols=5, nrows=5, xmin=0, xmax=5, ymin=0, ymax=5)
values(r) <- 1:25
xy <- rbind(c(0.5,0.5), c(2.5,2.5))
p <- vect(xy, crs="+proj=longlat +datum=WGS84")

extract(r, xy)
##   lyr.1
## 1    21
## 2    13
extract(r, p)
##   ID lyr.1
## 1  1    21
## 2  2    13
```

**Comment by rhijmans** [comment]
The CRAN version says 

> When argument y is a SpatVector, and list=FALSE, the first column has the ID (record number) of the SpatVector used.

The dev version says 

> When argument y is a SpatVector the first column has the ID (record number) of the SpatVector used (unless you set ID=FALSE).

So there is no ID if `y`  is not a SpatVector. The reason for this, perhaps unfortunate, difference is that if `y` is not a SpatVector it represents points (or cell numbers), making an ID redundant as there is a one-to-one relationship between input and output. 

Of course if `y` is a SpatVector of *points* that is also the case, but an ID *is* returned.

**Comment by frousseu** [comment]
I think I went over the description section a bit too quickly and I was expecting raster-like behaviour. The new version is enough I think and is nice because it mentions how to get rid of the ID column. Thanks!
