### ISSUE TITLE
focal changes order of values when fun = modal

### ISSUE THREAD

**Issue by frousseu** [rspatial/terra#737]
Hi!

When `fun = modal`, the ordering of values is changed by `focal`. This happens both for `na.policy = "all"` and `"only"`. Here are examples. The second layer should always be 0's. Does not seem to happen with `mean`, `min` or `max`. This is with terra 1.6-3. Thanks!

```r
library(terra)
ras1 <- rast(nrows=10, ncols=10)
values(ras1) <- 1:ncell(ras1)
ras2 <- ras1
values(ras2) <- rep(0, ncell(ras2))
ras <- c(ras1, ras2)
plot(ras)
r1 <- focal(ras, w=3, fun=modal, na.policy="all", na.rm=T)
plot(r1)
r2 <- focal(ras, w=3, fun=modal, na.policy="only", na.rm=T)
plot(r2)
```

**Comment by rhijmans** [comment]
Thanks, the problem arises when using a SpatRaster with multiple layers and a "custom" function instead of a built-in function like "mean". This was fixed in https://github.com/rspatial/terra/issues/727 . 

So you can either do this layer by layer, or use the development version instead.

**Comment by frousseu** [comment]
Works fine with the dev. version.
