### ISSUE TITLE
when plotting raster, `legend = FALSE` doesn't work

### ISSUE THREAD

**Issue by gsapijaszko** [rspatial/terra#738]
Hi Robert,

after upgrade I have realized that `legend` switch in `plot` isn't recognized:

``` r
devtools::install_version("terra", version = "1.6.3")
#> Downloading package from url: https://cloud.r-project.org/src/contrib/terra_1.6-3.tar.gz
#> Installing package into '/home/sapi/R/x86_64-pc-linux-gnu-library/4.1'
#> (as 'lib' is unspecified)
library(terra)
#> terra 1.6.3
utils::packageVersion("terra")
#> [1] '1.6.3'
r <- terra::rast(system.file("ex/elev.tif", package="terra"))
terra::plot(r, legend = FALSE)
```

![](https://i.imgur.com/0NKSSTz.png)

<sup>Created on 2022-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

After downgrading it to 1.5.xx, it works as expected:

``` r
devtools::install_version("terra", version = "1.5.34")
#> Downloading package from url: https://cloud.r-project.org/src/contrib/Archive/terra/terra_1.5-34.tar.gz
#> Installing package into '/home/sapi/R/x86_64-pc-linux-gnu-library/4.1'
#> (as 'lib' is unspecified)
library(terra)
#> terra 1.5.34
utils::packageVersion("terra")
#> [1] '1.5.34'
r <- terra::rast(system.file("ex/elev.tif", package="terra"))
terra::plot(r, legend = FALSE)
```

![](https://i.imgur.com/gwSF5ZL.png)

<sup>Created on 2022-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I got the same result with 1.6.5 from github

Regards,
Grzegorz

**Comment by rhijmans** [comment]
Thank you very much for reporting this. It works again.

**Comment by gsapijaszko** [comment]
Thanks :).

**Comment by wiesehahn** [comment]
I am using `terra 1.7.18` and get the same error

```plot(r, 1, legend = FALSE)``` works
```plot(r, legend = FALSE)``` does not
