### ISSUE TITLE
Where to find cellSize source code?

### ISSUE THREAD

**Issue by ahmoreira** [rspatial/terra#739]
Hi, thank you a lot for this amazing package! I am searching for the source code of the cellSize function. I looked the files in the repository, but I could not find it. Could please indicate where to find the source code of cellSize?
Thanks in advance!

**Comment by Nowosad** [comment]
See https://github.com/rspatial/terra/blob/7a4a9fb34e0951304e306d15c5b1cee3353c3134/R/generics.R#L126 and https://github.com/rspatial/terra/blob/f711178c6fe80c7737f27d88faff8b23c52ee4a0/src/distRaster.cpp#L2147

**Comment by ahmoreira** [comment]
> See
> 
> https://github.com/rspatial/terra/blob/7a4a9fb34e0951304e306d15c5b1cee3353c3134/R/generics.R#L126
> and
> 
> https://github.com/rspatial/terra/blob/f711178c6fe80c7737f27d88faff8b23c52ee4a0/src/distRaster.cpp#L2147

Thanks!!!
