### ISSUE TITLE
Differences in regular sampling of rast vs extent(rast)

### ISSUE THREAD

**Issue by gareth-d-ga** [rspatial/terra#744]
This is a follow-up to a recent bug fix [here](https://github.com/rspatial/terra/issues/732) 

With the aforementioned update, regular sampling of `ext(rast)` leads to results that differ in a surprising way from regular sampling of `rast`. 
* Regular sampling of `rast` seems sensible.
* Regular sampling of `ext(rast)` leads to the left/right columns having only half the number of points as all other columns. It also causes points to be sampled on part of the left/right boundaries, but not the north/south boundaries.
 
Reproducer below. IMO it might be nice for both methods to give the same points, corresponding to the results of sampling a `rast`.:
```r
library(terra)

# Raster with uniform cell-size in lon/lat coords
rast_lonlat = rast(nrows=12541, ncols=12826, xmin=114.4576, xmax=115.7772, ymin=-32.78539, ymax=-31.49516, vals=1)

# Method 1: Sample the rast -- this looks good
pts_1 = spatSample(rast_lonlat, size=100, method='regular', xy=TRUE, values=TRUE)

# Method 2: Sample the rast ext
# For some reason the most easterly/westerly columns only cover half the raster
pts_2 = spatSample(ext(rast_lonlat), size=100, method='regular', lonlat=TRUE)

# Show the difference
plot(ext(rast_lonlat), border='green', lty='dashed', asp=1/cos(32/180*pi), main='Differing results with regular sampling. \n Sampling ext(rast) leads to missing points in the east/west columns. \n Sampling rast produces more intuitive results.')
points(pts_1[,1:2], col='black')
points(pts_2[,1:2], col='red')
legend('topright', c('spatSample(rast)', 'spatSample( ext(rast) )'), pch=c(1,1), col=c('black', 'red'), bg='white', cex=2)
```

Thanks!

**Comment by rhijmans** [comment]
Thanks, I made a number of changes and I think the results are better now.
