### ISSUE TITLE
Problem controlling resolution of vrt

### ISSUE THREAD

**Issue by gareth-d-ga** [rspatial/terra#747]
I often use the vrt format to combine rasters with different resolutions, while specifying that the result should have the highest resolution.

In `gdalbuildvrt` this is achieved with the argument `-resolution highest` - or alternatively by specifying the resolution with `-tr resx resy`. 

In `terra::vrt` I have not been able to specify the resolution -- it seems to use the average resolution (default GDAL behaviour) regardless of the options. See reproducible example below.

```r
# Create the files (using a stars example)
library(stars)
x = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))

# Subset with 2x coarser [ resolution = 57 ]
x1 = st_downsample(x[,100:200,100:200,1], n=1)
# Different subset with native resolution [ resolution = 28.5 ]
x2 = x[,150:300,150:300,1]

write_stars(x1, dsn='x1.tif', options=c('COMPRESS=DEFLATE'))
write_stars(x2, dsn='x2.tif', options=c('COMPRESS=DEFLATE'))

# ONLY USE TERRA BELOW HERE
library(terra)
combined_rast = rast(vrt(c('x1.tif', 'x2.tif'), options='-resolution highest'))
# This does not have the "highest" resolution (28.5) -- it uses the average (42.75) which is the default behaviour of gdalbuildvrt.
```

It would be great if we could use the  `-resolution`  and `-tr` arguments to control this.

**Comment by kadyb** [comment]
Try this as workaround:

```r
r = vrt(c('x1.tif', 'x2.tif'), options = c('-resolution', 'highest'))
r = vrt(c('x1.tif', 'x2.tif'), options = c('-tr', 50, 50))
```

**Comment by gareth-d-ga** [comment]
I tried that just now, but it didn't change the result. 

However I note the notation you suggest is required for `stars::st_mosaic`.

**Comment by kadyb** [comment]
I see this in terra 1.6.3:

```r
combined_rast = rast(vrt(c('x1.tif', 'x2.tif'), options = c('-resolution', 'highest')))
res(combined_rast)
#> [1] 28.5 28.5
```

**Comment by rhijmans** [comment]
I also believe this works (I removed the warning message which was incorrect). Here is another example: 

```
library(terra)
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
x <- shift(r*1, 1)
x <- aggregate(x,5, filename= paste0(tempfile(), ".tif"))
r <- writeRaster(r, filename= paste0(tempfile(), ".tif"))
ff <- c(sources(r), sources(x))

vrt(ff, options=c('-resolution', 'highest'))  |> res()
#[1] 0.008333333 0.008333333
vrt(ff)  |> res()
#[1] 0.025 0.025
vrt(ff, options=c('-resolution', 'lowest'))  |> res()
#[1] 0.04166667 0.04166667
```

**Comment by gareth-d-ga** [comment]
Thanks -- I tried again this morning and indeed it does work -- I must have mistyped, apologies.
