### ISSUE TITLE
`ID` argument ignored when an `sf` object is passed to `extract`

### ISSUE THREAD

**Issue by GreatEmerald** [rspatial/terra#755]
Very simple issue probably caused by a typo: when `extract()` is called with an `sf` object as an input, the `ID` argument is ignored and is hardcoded to `TRUE` here:

https://github.com/rspatial/terra/blob/5f06a2855db44e0a4f9b882cf56d1935f097b342/R/extract.R#L365

This should probably read `ID = ID` and not `ID = TRUE`.

**Comment by rhijmans** [comment]
Thanks very much. Fixed now.
