### ISSUE TITLE
configuration error 'terra'. Load failed .

### ISSUE THREAD

**Issue by jenmunoz** [rspatial/terra#758]
When trying  to install 'terra', I am getting: 

```
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
```

**Comment by rhijmans** [comment]
It looks like you are trying to install "terra" from source. Can't you instead install the compiled version from CRAN?

**Comment by kadyb** [comment]
The [README](https://github.com/rspatial/terra/blob/master/README.md) contains information on how to install `{terra}` on various systems.

**Comment by jenmunoz** [comment]
Thanks, it seems that I just needed to update my R version to be able to install it from CRAN.
