### ISSUE TITLE
Error in x@ptr$writeStart(opt): could not find valid method when using UDF in terra::app

### ISSUE THREAD

**Issue by goergen95** [rspatial/terra#761]
With the latest head ([42201b4](https://github.com/rspatial/terra/commit/42201b40279d0caba112022fbc7497d43b5e8a26)) I get above mentioned error message when supplying an UDF to app. Here's a reprex:

``` r
library(terra)
#> terra 1.6.8
r <- rast(ncols=10, nrows=10)
values(r) <- 1:ncell(r)
testfun <- function(i) { 2 * sqrt(i) }
test <- app(r, fun=testfun, cores =1)
#> Error in x@ptr$writeStart(opt): could not find valid method
```

<sup>Created on 2022-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thanks, this was caused by the (incomplete) fix for #760. Should be good now.
