### ISSUE TITLE
extract() does not return a SpatVector when bind = TRUE

### ISSUE THREAD

**Issue by cscarpon** [rspatial/terra#762]
Hi,

When using the extract() function, the arg, bind = TRUE is supposed to return the SpatVector that was used for the extraction (or so I think), but it only returns a data frame. Additionally, xy =TRUE does not return the XY values of the cell.

```
r <- rast(ncols=10, nrows=10, xmin=-10, xmax=10, ymin=-10, ymax=10)
values(r) <- 1:100

v <- vect("POLYGON ((0 -5, 10 0, 10 -10, 0 -5))")

plot(r)
polys(v)

testVect <- extract(r, v, fun= max, bind = TRUE, xy = TRUE)
str(testVect)
```

Although there are IDs created for the extractions, is there a way to know which polygon was used for the extraction?

Thanks!

**Comment by rhijmans** [comment]
I am guessing that you are using an older version of "terra" but referring to the manual for the current version. 
Here with the development version:

```
library(terra)
#terra 1.6.8
r <- rast(ncols=10, nrows=10, xmin=-10, xmax=10, ymin=-10, ymax=10)
values(r) <- 1:100
v <- vect("POLYGON ((0 -5, 10 0, 10 -10, 0 -5))")
extract(r, v, fun= max, bind = TRUE, xy = TRUE)

# class       : SpatVector 
# geometry    : polygons 
# dimensions  : 1, 1  (geometries, attributes)
# extent      : 0, 10, -10, 0  (xmin, xmax, ymin, ymax)
# coord. ref. :  
# names       : lyr.1
# type        : <num>
# values      :   100
```
