### ISSUE TITLE
Datatype stability in raster arithmetic

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#763]
I noticed that math operations on integer return double. Shouldn't they return integer?

```r
library("terra")
f = system.file("ex/elev.tif", package = "terra")
r = rast(f)
is.int(r)
#> [1] TRUE
is.int(r + 1L)
#> [1] FALSE
is.int(r * 1L)
#> [1] FALSE
```

**Comment by rhijmans** [comment]
Yes, that is better. Internally everything is a double, for simplicity, so that took some additional work.

**Comment by kadyb** [comment]
Thank you!

> Internally everything is a double, for simplicity, so that took some additional work.

Does this also mean that if `is.int(r) = TRUE`, the raster is stored in memory as double?

**Comment by kadyb** [comment]
Thanks for the explanation! I mistakenly thought that `is.int(r) = TRUE` meant that the data was stored as integer in R. Now I wonder if the function `as.int()` is needed if the data is really of double type?

**Comment by rhijmans** [comment]
`as.int` is the same as `floor` and in that sense it can be useful. It also returns a SpatRaster that `is.int` and that can be useful. e.g. for the algebra just implemented and for writing files. It does not reduce the memory footprint.

**Comment by rhijmans** [comment]
And there is this:

```
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
is.int(r)
#[1] TRUE
class(r[1][[1]])
#[1] "integer"
class((r/2)[1][[1]])
#[1] "numeric"
```
