### ISSUE TITLE
Weird buffer behaviour on lines

### ISSUE THREAD

**Issue by zoeschindler** [rspatial/terra#765]
When trying to make a buffer around a line, starting from a certain buffer width it does not work anymore correctly. Here my code for creating the line and the polygon:

```
  # line coordinates
  ch_crd <- structure(
    c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3.50850510439515, 3.34156954142671, 
      2.87898194958676, 2.72374630132234, 2.2922345396554, 2.29312419890067, 
      2.32261681738335, 2.49720251348322, 3.19886481773371, 3.50850510439515, 
      1.62424111363924, 1.64507013529592, 1.71055495856562, 1.8867890234822, 
      2.38801074041958, 2.91005134572971, 3.22939872710867, 3.25684154033292, 
      2.97375702861173, 1.62424111363924), dim = c(10L, 3L), dimnames = list(
        NULL, c("id", "x", "y")))
  
  # create line object
  ch_lin <- vect(ch_crd, "lines", crs = CRS("EPSG:25832")@projargs)
  
  # create 2m buffer around object
  ch_buff <- buffer(ch_lin, 2)
  
  # plot buffer per section
  plot(ch_buff, col = "lightblue")
  plot(ch_lin, add = T)
```

This is the output for a buffer with 2m width:

![grafik](https://user-images.githubusercontent.com/59600387/184808121-f3bf92f7-84ec-48a7-bb9d-58d359a62fb7.png)

And this is the output for a buffer with 1m width:

![grafik](https://user-images.githubusercontent.com/59600387/184808214-17cf4f4f-d4c5-47bd-b1cf-98ca8a72811b.png)

I don't know if I did something wrong or whether I found a bug?

**Comment by kadyb** [comment]
You have low values for X and Y coordinates, so instead of a 2 m wide buffer, maybe you should use a smaller value like 0.1 m?

I tested this code in `{sf}` and the result is identical:

```r
library("sf")
ll = st_linestring(ch_crd[, 2:3])
ll = st_sfc(ll, crs = "epsg:25832")
buff = st_buffer(ll, 2)
```

**Comment by zoeschindler** [comment]
It's weird that with `sf` the same happens. But I don't think it's necessarily about small coordinates. When multiplying the coordinates and the buffer both with 100, which takes away decimal points, this still happens.

I need exactly two meters though ...

**Comment by kadyb** [comment]
The buffer from the line is routed outwards and inwards, so I think you need to properly choose the width of the buffer to not change the geometry of the output polygon. If you multiply the XY coordinates by 100, and set the buffer to 2 m, it should be OK. In general, shouldn't these coordinates be in the range of the EPSG:25832 CRS? This is: `-1877994.66, 3932281.56,
804418.76, 9494203.2`.

**Comment by zoeschindler** [comment]
The coordinates are in such a form, because during processing they were position relative to somewhere. Even if I add an appropriate offset to where the data is approximately from, it does not work:

```
ch_crd[,"x"] <- ch_crd[,"x"] + 413700
ch_crd[,"y"] <- ch_crd[,"y"] + 5316500
```

Additionally, if I multiply the coordinates by 100, but the buffer not, then my buffer would be equivalent to 0.02m, which is not what I need.

**Comment by rhijmans** [comment]
Thanks, I believe this works better now:

```
library(terra)
ch_crd <- cbind(id = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 
	x = c(3.5085, 3.34156, 2.87898, 2.72375, 2.29223, 2.29312, 2.32262, 2.4972, 3.19886, 3.5085), 
	y = c(1.62424,1.64507, 1.71055, 1.88678, 2.38801, 2.91005, 3.22939, 3.25684,2.97375, 1.6242)
  )
ch_lin <- vect(ch_crd, "lines", crs="EPSG:25832")
ch_buff <- buffer(ch_lin, 2) 
plot(ch_buff, col = "lightblue")
lines(ch_lin, col="red", lwd=2)
```  
 
![buf](https://user-images.githubusercontent.com/11481397/185109773-0bea47fa-d7a7-4511-ba40-e5411487903b.png)

**Comment by rhijmans** [comment]
Sorry, that was not a good solution (it worked for this case, but would be wrong in other cases)

**Comment by rhijmans** [comment]
The problem with the odd hole when buffering a line like this needs to be solved in GEOS --- although I could provide an alternative algorithm if need be. This does not happen with using lon/lat: 

```
library(terra)
ch_crd <- cbind(id = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 
	x = c(3.5085, 3.34156, 2.87898, 2.72375, 2.29223, 2.29312, 2.32262, 2.4972, 3.19886, 3.5085), 
	y = c(1.62424,1.64507, 1.71055, 1.88678, 2.38801, 2.91005, 3.22939, 3.25684,2.97375, 1.6242)
  )

p <- vect(ch_crd, "lines", crs="+proj=longlat")
b <- buffer(p, 60000)
plot(b)
```

But for your use-case, it makes more sense to use polygons with a negative buffer. I understand that the problem you had is that this gives an error when the negative buffer is so large such that it is empty. With the CRAN version you could use `try` to catch these errors:

```
p <- vect(ch_crd, "polygons", crs="EPSG:25832")
b <- try(buffer(p, -2), silent=TRUE)
if (inherits(b, "try-error") {
}
``` 

With the current development version that is not needed:

```
p <- vect(ch_crd, "polygons", crs="EPSG:25832")
b <- buffer(p, -2)
#Warning message:
#[buffer] empty SpatVector
```

**Comment by zoeschindler** [comment]
Thank you for fixing! This solves my issue :)
