### ISSUE TITLE
Does `terra:vect()` work the same as `sf::read_sf()`?

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#767]
One more question from me. I noticed that `terra:vect()` is significantly faster than `sf::read_sf()` in loading vector data. Is this because `{terra}` doesn't load all vector data into memory at once? Any data being loaded on demand later?

**Comment by rhijmans** [comment]
> Any data being loaded on demand later?

No, unless you use `proxy=TRUE`.

I do not know why it would be noticeably faster. Differences in loading include that "sf" creates an R object while "terra" keeps everything as a C++ object (within a small R object) and that the geometries are represented differently.

**Comment by kadyb** [comment]
Here is a simple example (`{terra}` is twice as fast in this case):

```r
library("sf")
library("terra")

set.seed(1)
n = 500000
df = data.frame(x = runif(n), y = runif(n))
points = st_as_sf(df, coords = c("x", "y"), crs = "epsg:4326")
tmp = tempfile(fileext = ".gpkg")
write_sf(points, tmp)

t = bench::mark(
  iterations = 10, check = FALSE, memory = FALSE,
  read_sf(tmp),
  vect(tmp)
)
t[, 1:4]
#>   expression        min   median `itr/sec`
#> 1 read_sf(tmp)    2.41s     2.7s     0.364
#> 2 vect(tmp)       1.33s    1.35s     0.736
```

**Comment by kadyb** [comment]
> Differences in loading include that "sf" creates an R object while "terra" keeps everything as a C++ object (within a small R object) and that the geometries are represented differently.

It makes a lot of sense, and I think that's the reason.

I am currently doing [vector benchmarks](https://github.com/kadyb/vector-benchmark/tree/main/terra) and after each operation in `{terra}` I use `geom()` to load the data into the internal R structure (i.e. data frame). Here are examples:

- `geom(buffer(vec, 100, quadsegs = 30))`
- `geom(vect(vec))`
- `geom(project(vec, "epsg:4326"))`

From your perspective, is such comparison with `{sf}` and `{geopandas}` fair? This increases the execution time of operations in `{terra}`, but the other packages use the internal structures of the languages. What do you think?

**Comment by rhijmans** [comment]
A SpatVector is an R object. Having the geometries at the C++ side may be an advantage or not, depending on what you want to do next.  But when it is an advantage, I see no reason to penalize for that. You could evaluate other operations where the terra approach may be a disadvantage.  I do not think `geom` is commonly used in workflows, so adding that seems artificial.

**Comment by kadyb** [comment]
Thanks, I will revisit this in the future and now add a note to the README.
