### ISSUE TITLE
terra::merge documentation with respect to priority in overlaps isn't clear

### ISSUE THREAD

**Issue by lucas-johnson** [rspatial/terra#768]
The current docs [here](https://rdrr.io/cran/terra/man/merge.html) are confusing with respect to which rasters have priority in areas of overlap. Specifically: 

> If objects overlap, the values get priority in the same order as the arguments. The SpatRasters must have the same origin and spatial resolution. In areas where the SpatRaster objects overlap, the values of the SpatRaster that is last in the sequence of arguments will be retained.

seems to be contradictory with the first sentence indicating that first place takes precedent, whereas the last sentence indicates that last place takes precedent.

A quick experiment shows that priority is indeed given to the first place (or earlier place in the arguments) as documented in the first sentence. 

``` r
library(terra)
#> terra 1.6.7
a <- rast(
  xmin=0,
  xmax = 10,
  ymin=0,
  ymax = 10,
  names="a",
  resolution = 1,
  crs = 'EPSG:26918'
)
values(a) <- c(rep(1, 100))
b <- rast(
  xmin=5,
  xmax = 15,
  ymin=0,
  ymax = 10,
  names="b",
  resolution = 1,
  crs = 'EPSG:26918'
)
values(b) <- c(rep(2, 100))
c <- rast(
  xmin=10,
  xmax = 20,
  ymin=0,
  ymax = 10,
  names="c",
  resolution = 1,
  crs = 'EPSG:26918'
)
values(c) <- c(rep(3, 100))
merged <- do.call(terra::merge, list(a, b, c))
plot(merged)
```

![](https://i.imgur.com/Ca9nVgU.png)

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I think it might also be helpful to document that the order passed to `terra::sprc` is maintained in the [sprc](https://rdrr.io/github/rspatial/terra/man/src.html) docs: 

``` r
library(terra)
#> terra 1.6.7
a <- rast(
  xmin=0,
  xmax = 10,
  ymin=0,
  ymax = 10,
  names="a",
  resolution = 1,
  crs = 'EPSG:26918'
)
values(a) <- c(rep(1, 100))
b <- rast(
  xmin=5,
  xmax = 15,
  ymin=0,
  ymax = 10,
  names="b",
  resolution = 1,
  crs = 'EPSG:26918'
)
values(b) <- c(rep(2, 100))
c <- rast(
  xmin=10,
  xmax = 20,
  ymin=0,
  ymax = 10,
  names="c",
  resolution = 1,
  crs = 'EPSG:26918'
)
values(c) <- c(rep(3, 100))
merged <- terra::merge(terra::sprc(list(a, b, c)))
plot(merged)
```

![](https://i.imgur.com/IvTezeI.png)

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rhijmans** [comment]
Thanks, that documentation was rather mysterious

**Comment by lucas-johnson** [comment]
Thank you!
