### ISSUE TITLE
using levels() <- witha tibble will return error: Error: [set.cats] duplicate values (IDs) supplied

### ISSUE THREAD

**Issue by MatthieuStigler** [rspatial/terra#771]
It seems `levels(raster) <- `  will not work if the dataset is a tibble instead of data.frame? It returns a quite confusing error message:

> Error: [set.cats] duplicate values (IDs) supplied

although the problem seems to be just about the tibble, the data having no duplicates!

``` r
library(terra)
#> terra 1.6.7

set.seed(0)
r <- rast(nrows=10, ncols=10)
values(r) <- sample(3, ncell(r), replace=TRUE)

cls <- data.frame(id=1:3, cover=c("forest", "water", "urban"))
cls_tibble <- tibble::as_tibble(cls)

## data.frame: works
levels(r) <- cls

## tibble: does not
levels(r) <- cls_tibble
#> Error: [set.cats] duplicate values (IDs) supplied
```

<sup>Created on 2022-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thanks for reporting! This happened because the default for a data.frame is `drop=TRUE` whereas a tibble (apparently) has `drop=FALSE` (which would make sense because the data.frame default causes a lot of errors; but now the inverse problem can arise if you expect a data.frame and get a tibble).

**Comment by MatthieuStigler** [comment]
great, thanks for the quick reply and resolution! And yes, glad that `drop=FALSE` becomes the default, `drop=TRUE` created so many mistakes!
