### ISSUE TITLE
`SpatVect` plotting performance

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#774]
I compared the performance of drawing plots in `{terra}` and `{sf}` and there are significant differences.

Case 1: Points

```r
library("sf")
library("terra")

n = 100000
x = rnorm(n) * 100
y = rnorm(n) * 100

pts1 = vect(data.frame(x, y), geom = c("x", "y"), crs = "epsg:2180")
pts2 = st_geometry(st_as_sf(pts1))

## default SpatVect plot
system.time(plot(pts1))
#> 3.62 s

## plot SpatVect with pch = 16
system.time(plot(pts1, pch = 16, cex = 0.7))
#> 1.73 s

## plot matrix
system.time(plot(crds(pts1), asp = 1, pch = 16, cex = 0.7, xlab = NA, ylab = NA, cex.axis = 0.7))
#> 1.26 s

## plot sf (it uses pch = 1)
system.time(plot(pts2, axes = TRUE))
#> 2.05 s
```

This is strange, but it seems that simply changing the default `pch = 20` to `pch = 16` results in a double speedup. I think it's worth changing. **Edit:** After checking, I see that the points with `pch = 16` [look worse](https://user-images.githubusercontent.com/35004826/185786192-291f0ab3-4730-48de-b1bf-64674ca6f424.png) on the default Linux graphics device, on Windows they look fine.

There is still some overhead in plotting SpatVect compared to the matrix, but these differences are small.

**Comment by kadyb** [comment]
Case 2: Lines

```r
library("sf")
library("terra")

tmp = tempfile(fileext = ".gpkg")
url = "https://github.com/paleolimbot/geoarrow-data/releases/download/v0.0.1/nshn_water_line.gpkg"
download.file(url, tmp, mode = "wb") # 760.0 MB

## terra
v1 = vect(tmp)[1:10000, ]
system.time(plot(v1, axes = FALSE))
#> 9.43

## sf
v2 = st_geometry(read_sf(tmp)[1:10000, ])
system.time(plot(v2))
#> 2.07
```

For line drawing, this difference is almost five times.

**Comment by rhijmans** [comment]
I changed the default for points to pch=16. pch=1 would be another option, but I like the visibility of the filled dots.

**Comment by kadyb** [comment]
Did you also notice that `pch = 16` looks worse on Linux (probably because of the anti-aliasing)? I suspect that some users may be dissatisfied with the lower quality of the figures. Maybe we should also add a note to `plot()` documentation?

> Points with the shape \code{pch = 16} (default) can be displayed the fastest, however anti-aliasing issues may occur on some graphical devices.

`{ggplot2}` uses `pch = 19` as the default shape but drawing takes a little more time than `pch = 20`.

**Comment by rhijmans** [comment]
Points now uses "pch=16", and there is some documentation saying that "pch=20" can be smoother:

```
library("sf")
library("terra")

n = 100000
x = rnorm(n) * 100
y = rnorm(n) * 100

pts1 = vect(data.frame(x, y), geom = c("x", "y"), crs = "epsg:2180")
pts2 = st_geometry(st_as_sf(pts1))

## default SpatVect plot (pch=16)
system.time(plot(pts1))
#   user  system elapsed 
#   0.39    1.92    2.32 

## plot sf (it uses pch = 1)
#system.time(plot(pts2, axes = TRUE))
#   user  system elapsed 
#   0.32    2.20    2.53 
``` 

Plotting of lines is now much faster (thanks for pointing out the opportunity to do so)

```
url = "https://github.com/paleolimbot/geoarrow-data/releases/download/v0.0.1/nshn_water_line.gpkg"
tmp = basename(url)
if (!file.exists(tmp)) download.file(url, tmp, mode = "wb")
n = seq_len(10000)

## terra
library("terra")
v1 = vect(tmp)[n, ]
system.time(plot(v1, axes = FALSE))
#   user  system elapsed 
#   0.42    1.01    1.43 

## sf
library("sf")
v2 = st_geometry(st_as_sf(v1))
system.time(plot(v2))
#   user  system elapsed 
#   0.94    1.07    2.01 
```

**Comment by kadyb** [comment]
Thank you very much Robert!

**Comment by kadyb** [comment]
Sorry Robert for bothering you again, but I now checked the case for polygons and probably something could be improved as well.

```r
url = "https://geodata.ucdavis.edu/gadm/gadm4.1/gpkg/gadm41_USA.gpkg"
tmp = tempfile(fileext = ".gpkg")
download.file(url, tmp, mode = "wb")

## sf
library("sf")
x = read_sf(tmp, layer = "ADM_ADM_2")
system.time({plot(st_geometry(x))})
#> user  system elapsed
#> 0.70    1.70    2.44

## terra
library("terra")
y = vect(tmp, layer = "ADM_ADM_2")
system.time({plot(y, axes = FALSE)})
#>  user  system elapsed
#> 10.54    2.01   12.58
```

**Comment by rhijmans** [comment]
I knew that was coming :) --- should be much better now

**Comment by kadyb** [comment]
> I knew that was coming :)

😄 

I see that with this commit it is ~6 times faster:

```r
system.time({plot(y, axes = FALSE)})
#>  user  system elapsed
#> 0.33    1.61    1.97
```

Thank you again!
