### ISSUE TITLE
ERROR 4: complication failed on Ubuntu 18.04 R 4.2.1

### ISSUE THREAD

**Issue by rix133** [rspatial/terra#778]
So I followed the installation procedure on the Readme page but I get internal compiler error:

>/usr/lib/R/etc/Makeconf:177: recipe for target 'RcppModule.o' failed
>make: *** [RcppModule.o] Error 4
>ERROR: compilation failed for package ‘terra’

Any ideas what I can do to solve it. "sf" installed successfully.

`sessionInfo()`
>R version 4.2.1 (2022-06-23)
>Platform: x86_64-pc-linux-gnu (64-bit)
>Running under: Ubuntu 18.04.6 LTS

>Matrix products: default
>BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
>LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

>locale:
> [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
> [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
> [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
>[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base

>loaded via a namespace (and not attached):
>[1] BiocManager_1.30.18 compiler_4.2.1      tools_4.2.1
>[4] curl_4.3.2          remotes_2.4.2

Full output:

` remotes::install_github("rspatial/terra")`
>Downloading GitHub repo rspatial/terra@HEAD
>Running `R CMD build`...
>* checking for file ‘/tmp/RtmpfO0u7m/remotes61df22eb6e9d/rspatial-terra-104159a/DESCRIPON’ ... OK
>* preparing ‘terra’:
>* checking DESCRIPTION meta-information ... OK
>* cleaning src
>* running ‘cleanup’
>* checking for LF line-endings in source and make files and shell scripts
>* checking for empty or unneeded directories
>* building ‘terra_1.6-10.tar.gz’
>Installing package into ‘/usr/local/lib/R/site-library’
>(as ‘lib’ is unspecified)
>* installing *source* package ‘terra’ ...
>** using staged installation
>configure: CC: gcc
>configure: CXX: g++ -std=gnu++11
>checking for gdal-config... /usr/bin/gdal-config
>checking gdal-config usability... yes
>configure: GDAL: 3.0.4
>checking GDAL version >= 2.0.1... yes
>checking for gcc... gcc
>checking whether the C compiler works... yes
>checking for C compiler default output file name... a.out
>checking for suffix of executables...
>checking whether we are cross compiling... no
>checking for suffix of object files... o
>checking whether we are using the GNU C compiler... yes
>checking whether gcc accepts -g... yes
>checking for gcc option to accept ISO C89... none needed
>checking how to run the C preprocessor... gcc -E
>checking for grep that handles long lines and -e... /bin/grep
>checking for egrep... /bin/grep -E
>checking for ANSI C header files... yes
>checking for sys/types.h... yes
>checking for sys/stat.h... yes
>checking for stdlib.h... yes
>checking for string.h... yes
>checking for memory.h... yes
>checking for strings.h... yes
>checking for inttypes.h... yes
>checking for stdint.h... yes
>checking for unistd.h... yes
>checking gdal.h usability... yes
>checking gdal.h presence... yes
>checking for gdal.h... yes
>checking GDAL: linking with --libs only... yes
>checking GDAL: /usr/share/gdal/pcs.csv readable... no
>checking GDAL: checking whether PROJ is available for linking:... yes
>checking GDAL: checking whether PROJ is available fur running:... yes
>configure: GDAL: 3.0.4
>checking proj.h usability... yes
>checking proj.h presence... yes
>checking for proj.h... yes
>checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
>checking for geos-config... /usr/bin/geos-config
>checking geos-config usability... yes
>configure: GEOS: 3.8.0
>checking GEOS version >= 3.4.0... yes
>checking geos_c.h usability... yes
>checking geos_c.h presence... yes
>checking for geos_c.h... yes
>checking geos: linking with -L/usr/lib/x86_64-linux-gnu -lgeos_c... yes
>configure: Package CPP flags:   -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include
<configure: Package LIBS:  -L/usr/lib -lgdal -lproj  -L/usr/lib -lgdal -L/usr/lib/x86_64inux-gnu -lgeos_c
>configure: creating ./config.status
>config.status: creating src/Makevars
>** libs
>g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -Isr/include -I'/usr/local/lib/R/site->library/Rcpp/include'    -fpic  -g -O2 -fdebug-pref-map=/build/r-base-j8qPcu/r-base-4.2.1=. -fstack-protector-strong -Wformat ->Werror=form-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports.cpp -o RcppExports.o
>g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -Isr/include -I'/usr/local/lib/R/site->library/Rcpp/include'    -fpic  -g -O2 -fdebug-pref-map=/build/r-base-j8qPcu/r-base-4.2.1=. -fstack-protector-strong -Wformat ->Werror=form-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppFunctions.cpp -o RcppFunctions.o
>g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -Isr/include -I'/usr/local/lib/R/site->library/Rcpp/include'    -fpic  -g -O2 -fdebug-pref-map=/build/r-base-j8qPcu/r-base-4.2.1=. -fstack-protector-strong -Wformat ->Werror=form-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppModule.cpp -o RcppModule.o
>g++: internal compiler error: Killed (program cc1plus)
>Please submit a full bug report,
>with preprocessed source if appropriate.
>See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
>/usr/lib/R/etc/Makeconf:177: recipe for target 'RcppModule.o' failed
>make: *** [RcppModule.o] Error 4
>ERROR: compilation failed for package ‘terra’
>* removing ‘/usr/local/lib/R/site-library/terra’
>Warning message:
>In i.p(...) :
>  installation of package ‘/tmp/RtmpfO0u7m/file61df5a370522/terra_1.6-10.tar.gz’ had nozero exit status

`gcc -version` gives me:
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by rhijmans** [comment]
This works for me. Given that the error is triggered when compiling `RcppModule.cpp` I wonder if you have enough RAM available.

**Comment by rix133** [comment]
> This works for me. Given that the error is triggered when compiling `RcppModule.cpp` I wonder if you have enough RAM available.
It's a virtual machine with a total of 2 GB of RAM. If it works for you this might be the problem indeed.

**Comment by rhijmans** [comment]
I do not think I can easily change that file. Perhaps you can install a binary version from https://eddelbuettel.github.io/r2u/ ?

**Comment by rix133** [comment]
Yes, I was thinking of compiling on a separate machine but maybe the r2u has 18.04 binaries as well. Thanks for the help.
