### ISSUE TITLE
cells function - polygons that cross the dateline

### ISSUE THREAD

**Issue by jt-tbc** [rspatial/terra#779]
Hi Robert (and others),

Thanks for all your work on this package. I was wondering what the best way to be able to use the "cells" function with polygons that cross the international dateline (180 degrees). I currently get the error of:

Error in x@ptr$vectCells(y@ptr, touches[1], method[1], weights[1], exact[1],  : 
  std::bad_alloc

Similar errors arise from the exactextracr package.

Any help would be greatly appreciated.

**Comment by rhijmans** [comment]
I do not see that error

```
library(terra)
#terra 1.6.10
set.seed(0)
r <- rast(nrows=10, ncols=10)
p <- vect("POLYGON ((120 10, 230 75, 230 -75, 120 10))")

cells(r, p)
#     ID cell
#[1,]  1   40
#[2,]  1   49
#[3,]  1   50
#[4,]  1   60
```

I have added a new method, `normalize_longitude` that allows you to do:

```
x <- normalize_longitude(p)
cells(r, x)
#      ID cell
# [1,]  1   21
# [2,]  1   31
# [3,]  1   40
# [4,]  1   41
# [5,]  1   49
# [6,]  1   50
# [7,]  1   51
# [8,]  1   60
# [9,]  1   61
#[10,]  1   71
```

**Comment by jt-tbc** [comment]
Hi Robert,

Sorry I forgot to reply, that seems to work great, thank you so much!

Seem to have some issues with memory but that's a hardware issue, thanks again for building this package, absolute life saver.

Kind regards,

Joe

Joe Turner PhD
Principal Specialist: Data Analytics

The Biodiversity Consultancy Ltd
3E King's Parade, Cambridge, CB2 1SJ
Mobile: +44 (0)7969533606
***@***.******@***.***>
www.thebiodiversityconsultancy.com<http://www.thebiodiversityconsultancy.com/>
To keep in touch with TBC's business and biodiversity bulletins, news and job vacancies sign up to our mailing list at www.thebiodiversityconsultancy.com/contact/<http://www.thebiodiversityconsultancy.com/contact/>. We take a selective approach and only release occasional updates. We respect your privacy and will not share your email address with any third party.
This email (including all attachments) is the sole property of The Biodiversity Consultancy Limited and may be confidential. If you are not the intended recipient, you must not use or forward the information contained in it. This message may not be reproduced or otherwise republished without the written consent of the sender. If you have received this message in error, please delete the e-mail and notify the sender.
