### ISSUE TITLE
writeRaster dataformat INT1U

### ISSUE THREAD

**Issue by herryATcsiro** [rspatial/terra#78]
Hi there,

I would like to write GTIF in INT1U for use in outside R software. WriteRaster documentation says: "Values for datatype are "INT2U", "INT2S", "INT4U", "INT4S", "FLT4S", "FLT8S"..."

would it be possible to add INT1U to this?

Thanks
Herry

**Comment by aloboa** [comment]
"INT1U" does work, it is a problem in the documentation.
(BTW, edit the title of the thread from INT4U to INT1U)
r <- rast(ncol=512,nrow=512)
r[] <- 255
writeRaster(r,"delme.tif",wopt=list(datatype="INT1U",
                                    filtype="GTiff"))
require(rgdal)
describe("delme.tif")
#note "Band 1 Block=512x16 Type=Byte, ColorInterp=Gray"
