### ISSUE TITLE
vrt function - issue creating a virutual dataset fro many tiles

### ISSUE THREAD

**Issue by 8Ginette8** [rspatial/terra#780]
Hi there,

Currently using the terra package and its related function "vrt" I just wanted to report a bug...It seems that past 1020 tiles, the function cannot be used, as a message error pops up, e.g. based on the vrt example of the terra documentation:

```
# Initializing the tiles example
r <- rast(ncols=100, nrows=100)
values(r) <- 1:ncell(r)
x <- rast(ncols=100, nrows=100)
filename <- paste0(tempfile(), "_.tif")
ff <- makeTiles(r, x, filename)

# Creating the VRT 
vrtfile <- paste0(tempfile(), ".vrt")
v <- vrt(ff, vrtfile, options = c("-tr", 5, 5))
Error: [vrt] cannot open /tmp/RtmpSHF4Y2/file69bd6bd7d1ce_1021.tif

# Extracting which tile is this
 which(ff=="/tmp/RtmpSHF4Y2/file69bd6bd7d1ce_1021.tif")
1021
```

It really seems like a minor problem, eager to use again the function when this is solved...!

Thanks,
Yohann

**Comment by rhijmans** [comment]
This is probably related to the number of files that can be opened at the same time on your system. See https://github.com/rspatial/terra/issues/231 
Your example works for me on windows.

**Comment by 8Ginette8** [comment]
Interesting...The system I am using is a HPC (so Linux) and it seems that their limit is set to 1000. I don't have the rights so nothing I can do unfortunately, however, using gdalbuildvrt() from the gdalUtils R package has worked...Odd.

Thanks Robert, this is good to know
Best,
Yohann

**Comment by rhijmans** [comment]
I believe this has now been fixed.
