### ISSUE TITLE
Session aborted after a while when using crop() and mask()

### ISSUE THREAD

**Issue by ggrittz** [rspatial/terra#781]
Hello,

I am using the package to crop a raster to an extent and then mask it to the shapefile from where I extracted the extent. It works for a time (some outputs are generated normally) but then the R session crashes. 

I'm using terra's package version 1.6-10, R version 4.2.1, and RStudio version 2022.7.1.554.

As rasters, I'm using CHELSA climate data (If necessary I can provide the paths to download via wget) and an ordinary shapefile (attached below).

Here's my function:

```

#remotes::install_github("rspatial/terra")
library(terra)

#input filenames
inf <- list.files("data/rasters", pattern="tif$", full.names=TRUE)
#create output filenames and folder
outf <- gsub("data/rasters", "output", inf)
dir.create("output", FALSE, FALSE)

#Shapefile and the extent to crop
sc_shp <- vect("data/polygons/sc.shp")
new_crs <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
sc_shp <- project(sc_shp, new_crs)
sc_shp_ext <- ext(sc_shp)

for (i in 1:length(inf)) {
     b <- rast(inf[i])
          crop(mask(x = b, mask = sc_shp), sc_shp_ext, filename = outf[i])
     }

```
**Shapefile:** [sc.zip](https://github.com/rspatial/terra/files/9433145/sc.zip)

At the moment I'm running the same loop using {raster} package, so I'll update here when finished (it does start returning

**Error in x$.self$finalize() : attempt to apply a non-function
Error in (function (x) : attempt to apply a non-function**
) but the script is still running so far.

Cheers,

**Comment by rhijmans** [comment]
It would be useful for me to download to have the exact same input files as you use to track this down, so please do provide the URLs if you can.  By the way, with "terra" you could simplify crop/mask like this 

     crop(b, sc_shp, mask=TRUE, filename = outf[i])

**Comment by ggrittz** [comment]
> 

I recently read you implemented the crop(mask() and forgot to code it haha

Paths attached
[envidatS3paths.txt](https://github.com/rspatial/terra/files/9433317/envidatS3paths.txt)

**Comment by ggrittz** [comment]
Some update @rhijmans:

I re-ran the analysis using your suggestion (`crop(b, sc_shp, mask=TRUE, filename = outf[i])`) and it worked wonders. Absolutely fast and did not result in session aborted.
