### ISSUE TITLE
'crop' unexpected result for lines

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#782]
Hi, I think 'crop' is producing strange results when `y` is a SpatVector of lines, as the result (in blue in the image below) is not really cropped by the border (nor by the extent) of the cropping polygon:

```
lux <- vect(system.file("ex/lux.shp", package="terra"))
diek <- subset(lux, lux$NAME_1 == "Diekirch")

roads <- geodata::osm("LUX", "highways", path = tempdir())
roads2 <- subset(roads, roads$highway == "secondary")

plot(lux, col = "wheat", border = "white")
plot(diek, col = "tan", border = "white", add = TRUE)
plot(ext(diek), add = TRUE)
plot(roads2, col = "red", add = TRUE)
plot(crop(roads2, diek), col = "blue", lwd = 2, add = TRUE)
```

![image](https://user-images.githubusercontent.com/12085508/187195066-924b6f4a-0352-44f5-a0f1-25cd1fbbe9e4.png)

When `y` is a SpatVector of polygons, the result looks fine. Cheers!

**Comment by AMBarbosa** [comment]
I just noticed that 'crop' goes overboard also for points:

```
my_points <- centroids(lux)

plot(lux, col = "wheat", border = "white")
plot(diek, col = "tan", border = "white", add = TRUE)
plot(my_points, add = TRUE)
plot(crop(my_points, diek), col = "blue", cex = 2, add = TRUE)
```
![image](https://user-images.githubusercontent.com/12085508/187244488-58bd954f-4836-4133-9577-8986927c64d0.png)

I know I can get the desired result just selecting by location with `my_points[diek, ]`, but still. Cheers!

**Comment by rhijmans** [comment]
Hi & thanks! Should work as expected now.
