### ISSUE TITLE
where() min,max fails on floating point type

### ISSUE THREAD

**Issue by mdsumner** [rspatial/terra#783]
There's a bug in where.min and where.max, they return the input raster rather than the query at

https://github.com/rspatial/terra/blob/b33a9116a1d5d2f0edf2a159d38cd5d67da382b1/R/Arith_generics.R#L465

and

https://github.com/rspatial/terra/blob/b33a9116a1d5d2f0edf2a159d38cd5d67da382b1/R/Arith_generics.R#L481

but, even with those fixed the query output is empty `numeric(0)` for a floating point type  - presume it's a floating point comparison problem, because the stored `range_min` and `range_max()` are compared to `val` in 

https://github.com/rspatial/terra/blob/b33a9116a1d5d2f0edf2a159d38cd5d67da382b1/src/arith.cpp#L1359

but, it's too deep for me to investigate further I'm afraid. 

Here's a reprex, from a private slack discussion with Jacob Wujciak-Jens. 

```R
library(terra)
dm <- c(3, 4, 2)
set.seed(1)
## no problem if we as.integer(vals)
r <- rast(nrows = dm[2], ncols = dm[1], nlyrs = dm[3], crs = "EPSG:4326", vals = runif(prod(dm), 0, 100))
r <- writeRaster(r, tf <- tempfile(fileext = ".tif"))

## error
where.max(rast(tf))
# Error in dimnames(x) <- dn :
#   length of 'dimnames' [2] not equal to array extent

## if I patch where.min and where.max to return list output
where.max(rast(tf), list = TRUE)
# [[1]]
# numeric(0)
# 
# [[2]]
# numeric(0)
# 


```

**Comment by assignUser** [comment]
@mdsumner Thanks for looking into this!

**Comment by rhijmans** [comment]
Thanks, seems to work well now.

**Comment by mdsumner** [comment]
excellent, thank you
