### ISSUE TITLE
`freq` ignores `bylayer=FALSE` for a single-layer SpatRaster

### ISSUE THREAD

**Issue by johnbaums** [rspatial/terra#785]
For a SpatRaster with a single layer, `freq` ignores `bylayer=FALSE`:

```R
r <- rast(matrix(sample(10, size=100, replace=TRUE), 10))
freq(r, bylayer=FALSE)

#    layer value count
# 1      1     1    11
# 2      1     2     9
# 3      1     3    14
# 4      1     4     3
# 5      1     5     9
# 6      1     6    10
# 7      1     7     8
# 8      1     8    17
# 9      1     9     7
# 10     1    10    12
```

It seems like replacing https://github.com/rspatial/terra/blob/2fd1da0ed1a61f1049b70993459674be032af924/R/generics.R#L630-L632 with

```R
if (!bylayer) {
    v <- v[, c("value", "count")]
}
```

would do the trick, noting that the freq method already does the aggregation across layers (I think).

**Comment by rhijmans** [comment]
Thanks!
