### ISSUE TITLE
Missing NoData value after writing raster with terra::writeRaster()

### ISSUE THREAD

**Issue by chrisschuerz** [rspatial/terra#786]
This issue is likely related to issues #74 and #622.

## Sessioninfo:
```r
sessionInfo()
#>> R version 4.2.1 (2022-06-23 ucrt)
#>> Platform: x86_64-w64-mingw32/x64 (64-bit)
#>> Running under: Windows 10 x64 (build 19044)

#>> other attached packages:
#>> [1] whitebox_2.1.5 terra_1.6-3 

gdal()
#>> [1] "3.4.3"
```

## Issue
Reading a raster and writing the same raster with `terra::writeRaster()` changes the `NoData Value = nan`. As a consequence this also affects the raster value statistics, as shown in the minimum example below. While this change does not really affect a workflow when again reading the raster layer again into R and performing any operations in R it corrupts raster oparations which are e.g. performed with functions from `whitebox`. 

Reading and writing the raster and again reading the written raster results in the following layer information:

```r
library(terra)
dem_path <- system.file("ex/elev.tif", package = "terra")
dem <- rast(dem_path) 
dem_out_path <- paste(tempdir(), 'dem_out.tif', sep = '/')
writeRaster(dem, dem_out_path, overwrite = TRUE)
dem_out <- rast(dem_out_path)
```

Information for original layer:

```r
cat(tail(describe(sources(dem))), sep = "\n")

#>>  Metadata:
#>>    STATISTICS_MAXIMUM=547
#>>    STATISTICS_MEAN=348.33658854167
#>>    STATISTICS_MINIMUM=141
#>>    STATISTICS_STDDEV=80.210158192407
#>>    STATISTICS_VALID_PERCENT=53.89
```

while the Information for the written layer is as follows:

```r
cat(tail(describe(sources(dem_out))), sep = "\n")

#>>  NoData Value=nan
#>>  Metadata:
#>>    STATISTICS_MAXIMUM=547
#>>    STATISTICS_MEAN=-9999
#>>    STATISTICS_MINIMUM=141
#>>    STATISTICS_STDDEV=-9999
```

## Use case of these layers with `whitebox`

The simple example below breaches the both elevation layers: 

```r
library(whitebox)

dem_breach_path <- paste(tempdir(), 'dem_breach.tif', sep = '/')
dem_out_breach_path <- paste(tempdir(), 'dem_out_breach.tif', sep = '/')

wbt_breach_depressions(dem_path, dem_breach_path)
wbt_breach_depressions(dem_out_path, dem_out_breach_path)
```

Loading the breached layers and calculating the differences shows that pixel values can differ substantially:

```r
dem_breach <- rast(dem_breach_path)
dem_out_breach <- rast(dem_out_breach_path)
summary(dem_out_breach - dem_breach)

#>> dem_out_breach    
#>> Min.   :-222.010  
#>> 1st Qu.:   0.000  
#>> Median :   0.000  
#>> Mean   :  -9.559  
#>> 3rd Qu.:   0.000  
#>> Max.   :  35.006  
#>> NA's   :3942
```

I tried a few things (also based on the related issues) to fix this for my specific cases and failed. Is there a general way to maintain the NoData value from the initial layer?

**Comment by kadyb** [comment]
Did you try to set the NA flag when saving?

```r
writeRaster(x, y, NAflag = -32768)
```

**Comment by brownag** [comment]
> Did you try to set the NA flag when saving?
> 
> ```r
> writeRaster(x, y, NAflag = -32768)
> ```


I think to get this to work, there also needs to be a `dem <- classify(dem, cbind(NA, -32768))` step or similar to convert the NaN to whatever the desired flag is:

``` r
library(terra)
dem_path <- system.file("ex/elev.tif", package = "terra")
dem <- rast(dem_path)
dem <- classify(dem, cbind(NA, -32768))
dem_out_path <- paste(tempdir(), 'dem_out.tif', sep = '/')
writeRaster(dem, dem_out_path, NAflag = -32768, overwrite = TRUE)
dem_out <- rast(dem_out_path)

library(whitebox)

dem_breach_path <- paste(tempdir(), 'dem_breach.tif', sep = '/')
dem_out_breach_path <- paste(tempdir(), 'dem_out_breach.tif', sep = '/')

wbt_breach_depressions(dem_path, dem_breach_path)
wbt_breach_depressions(dem_out_path, dem_out_breach_path)

dem_breach <- rast(dem_breach_path)
dem_out_breach <- rast(dem_out_breach_path)
summary(dem_out_breach - dem_breach)
#>  dem_out_breach
#>  Min.   :0     
#>  1st Qu.:0     
#>  Median :0     
#>  Mean   :0     
#>  3rd Qu.:0     
#>  Max.   :0     
#>  NA's   :3942
```

**Comment by chrisschuerz** [comment]
@brownag, @kadyb thanks! It also worked without `dem <- classify(dem, cbind(NA, -32768))`. I tried the `NAflag` of the initial layer, which did not work. But "guessing" the `NAflag` might not be a very general solution. Further processing with `whitebox` works now. But the statistics are still the following:

```r
cat(tail(describe(sources(dem_out))), sep = "\n")

#>>  NoData Value=nan
#>>  Metadata:
#>>    STATISTICS_MAXIMUM=547
#>>    STATISTICS_MEAN=-9999
#>>    STATISTICS_MINIMUM=141
#>>    STATISTICS_STDDEV=-9999
```

I do not know if this affects any other data processing?

A workaround that fixed the layer for me was to perform a reclass, where I only reclass a dummy value range:

```r
whitbox::wbt_reclass(dem_out_path, dem_out_path,  reclass_vals = "0;99999;99999")
```

Maybe a naive thought; but shouldn't I expect as a user when I read > write new > read new with default input arguments of the respective functions that the initial and the new layer are identical?

**Comment by brownag** [comment]
>  But the statistics are still the following: ... I do not know if this affects any other data processing?

I don't think the metadata affect other data processing per se, but they are definitely confusing to interpret when non-NaN NAflag values are (potentially) included in the statistics. 

> A workaround that fixed the layer for me was to perform a reclass, where I only reclass a dummy value range:
> 
> ```r
> whitbox::wbt_reclass(dem_out_path, dem_out_path,  reclass_vals = "0;99999;99999")
> ```

I think the net effect of this is it removes the erroneous statistics in the new GeoTIFF output. Analogous to:

```r
system(paste("gdal_edit.py -unsetstats", dem_out_path))
```

> Maybe a naive thought; but shouldn't I expect as a user when I read > write new > read new with default input arguments of the respective functions that the initial and the new layer are identical?

This is similar to the thought I was having in #622--though more generic than just the GPKG case I was looking at.

**Comment by rhijmans** [comment]
Is the issue that whitebox cannot use NaN as missing value (perhaps because it uses equality to check for it)? If so, then perhaps that ought to be fixed there.

If you want to set the NAflag manually, you can do as @kadyb suggested, I think, 

```
library(terra)
r = rast(nrow=10, ncol=10)
values(r) = c(NA, 1)
x = writeRaster(r, "test.tif", NAflag=-9, overwrite=T)
describe("test.tif")[37]
#[1] "  NoData Value=-9"
```

Maintaining the NA-flag across files would be tricky. A good value is data-type specific; they can differ between files that are combined in a single SpatRaster; and, in the example above, what if you did `r - 10`?

I do not think this is related to the statistics in the Metadata. I consider the mean and stdev metadata as optional, and not worth it (too expensive) to compute. There actually is an "unsupported" option to get them:

```
values(x) <- 1:ncell(x)
y = writeRaster(x, "test2.tif", overwrite=TRUE, statistics=3)
describe("test2.tif") |> tail()
#[1] "  Metadata:"                          
#[2] "    STATISTICS_MAXIMUM=100"           
#[3] "    STATISTICS_MEAN=50.5"             
#[4] "    STATISTICS_MINIMUM=1"             
#[5] "    STATISTICS_STDDEV=28.866070047722"
#[6] "    STATISTICS_VALID_PERCENT=100"     
```

**Comment by brownag** [comment]
> Is the issue that whitebox cannot use NaN as missing value (perhaps because it uses equality to check for it)? If so, then perhaps that ought to be fixed there.

Yes, this is indeed the case--at least for how the BreachDepressions tool is written. 
 https://github.com/jblindsay/whitebox-tools/blob/master/whitebox-tools-app/src/tools/hydro_analysis/breach_depressions.rs 

Generally, WhiteboxTools expects the value used to encode NA to be the value that is stated in the NA flag--not NaN.
I believe by default in Rust comparisons with NaN are not equal. There are several equalities used in that tool alone... to make this change generally across the 500+ whitebox tools would be a significant undertaking.

**Comment by rhijmans** [comment]
> to make this change generally across the 500+ whitebox tools would be a significant undertaking.

I would hope that this can be fixed in the file I/O functions that are used by all tools? E.g. if the NoData value is nan, replace the nans with another flag value, and use that flag value to check for equality in the algorithms. Not pretty, but doable. 

I conclude that for now whitebox users will need to set the NAflag manually, e.g., when writing (the default) FLT4S datatype, to the lowest double value : -1.79769E+308. Unless there is other najor software out there that cannot deal with `NoData Value=nan` I would like to keep using that as it is the most efficient (no need for translation).
