### ISSUE TITLE
`subst()`: values replaced w/ unexpected behavior of categories in result object

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#787]
Here I assign categories to a raster of group ID numbers. The group IDs are discontinuous sequence and start at value greater than 1. I illustrate some changes in behavior of `subst()` between versions of terra (1.5-34 v.s 1.6.11) and implications for plotting with rasterVis

``` r
library(terra)
#> terra 1.6.11
cls <- data.frame(ID =    c(12345,   12346,   12350),
                  cover = c("forest", "water", "urban"))
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(cls$ID, ncell(r), replace = TRUE)
levels(r) <- cls
r
#> class       : SpatRaster 
#> dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#> resolution  : 36, 18  (x, y)
#> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 
#> source      : memory 
#> categories  : cover 
#> name        :  cover 
#> min value   : forest 
#> max value   :  urban

subst(r, cls$ID, 1:3)
#> class       : SpatRaster 
#> dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#> resolution  : 36, 18  (x, y)
#> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 
#> source      : memory 
#> categories  : cover 
#> name        : cover 
#> min value   :    NA 
#> max value   :    NA
```

I think this breaks `rasterVis::levelplot()` for these categorical rasters as the internal call to `subst()` returns an all NA result (after attempting to match labels using wrong values?). Note that in the sample 10x10 raster there should be no missing values

```r
# trace("subst", browser, signature = "SpatRaster")

library(rasterVis)
#> Loading required package: lattice
levelplot(r)
#> Error in Summary.factor(structure(c(NA_integer_, NA_integer_, NA_integer_, : 'range' not meaningful for factors
```

The inputs to `subst()` seem valid, but something is getting messed up with the result categories. I think some of the accounting is off in this case where the numeric ID column is not consecutive nor a character data type?

Whereas with terra 1.5-34 I get:

``` r
# install.packages("https://cran.r-project.org/src/contrib/Archive/terra/terra_1.5-34.tar.gz", repos=NULL)
library(terra)
#> terra 1.5.34
library(rasterVis)
#> Loading required package: lattice
cls <- data.frame(ID = c(12345, 12346, 12350), cover = c("forest", "water", "urban"))
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(cls$ID, ncell(r), replace = TRUE)
levels(r) <- cls
r
#> class       : SpatRaster 
#> dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#> resolution  : 36, 18  (x, y)
#> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 
#> source      : memory 
#> name        :  cover 
#> min value   : forest 
#> max value   :  urban

subst(r, cls$ID, 1:3)
#> class       : SpatRaster 
#> dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#> resolution  : 36, 18  (x, y)
#> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 
#> source      : memory 
#> name        : cover 
#> min value   :     1 
#> max value   :     3 
levelplot(r)
```

![](https://i.imgur.com/yr2ZeYk.png)

**Comment by rhijmans** [comment]
What version `terra 1.5-34` does is not supported anymore, because the values are set by "cover" not by "ID". If you want to drop the levels, you can first set them to NULL and then use `subst` 

```
library(terra)
cls <- data.frame(ID =    c(12345,   12346,   12350),
                  cover = c("forest", "water", "urban"))
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(cls$ID, ncell(r), replace = TRUE)
levels(r) <- cls
```

You can do 

```
x <- r
levels(x) <- NULL
subst(x, cls$ID, 1:3)
``` 

Or change the levels like this

```
x <- r
v <- levels(x)[[1]]
v[,2] <- 1:nrow(v)
levels(x) <- v
x
```

You can now also do 

```
x <- r
z <- subst(x, cls$ID, 1:3)
# note 
levels(z)[[1]]
#     ID  cover
#1 12345 forest
#2 12346  water
#3 12350  urban
#4 12351      1
#5 12352      2
#6 12353      3
``` 

This now also works --- because if "from" does not match the actual values, it checks if it matches the IDs (I am not sure if this is a good idea)

```
x <- r
z <- subst(x, cls$ID, 1:3)
# note 
levels(z)
#[[1]]
#     ID  cover
#1 12345 forest
#2 12346  water
#3 12350  urban
#4 12351      1
#5 12352      2
#6 12353      3
```
And that is not what you had in mind.

**Comment by brownag** [comment]
Thanks for your quick response, I appreciate your willingness to sort this out despite the desired behavior seemingly being out of scope.

> What version `terra 1.5-34` does is not supported anymore, because the values are set by "cover" not by "ID". If you want to drop the levels, you can first set them to NULL and then use `subst`

I am going to need to consider this lack of support as it could cause some problems / require changes for some of our terra usage. Basically we return arbitrary extent grids where the numeric values represent e.g. unique keys in a relational database. So the assumption of continuity of the numeric ID doesn't work in general. While one can recode the values for a particular grid as an increasing continuous integer vector, this loses the relation to the database keys, which then requires extra steps to convert results back to the key values when several of these grids may be used at once. 

I will also need to think about what this means for rasterVis/levelplot() and submit an issue or PR over there, as these fixes resolve the problem with subst() and show()... but not levelplot()-- which I think relies on the "old" behavior of `subst()` working on a raster with levels set. I *think* for purposes of `levelplot()` would be OK to drop the levels before calling subst() on the resampled SpatRaster (assuming any relevant information needed for labeling etc. were extracted first). 

> This now also works --- because if "from" does not match the actual values, it checks if it matches the IDs (I am not sure if this is a good idea)
> 
> ```
> x <- r
> z <- subst(x, cls$ID, 1:3)
> # note 
> levels(z)
> #[[1]]
> #     ID  cover
> #1 12345 forest
> #2 12346  water
> #3 12350  urban
> #4 12351      1
> #5 12352      2
> #6 12353      3
> ```

Hm. I am also not sure this is a good idea. Its not clear to me what the benefit of the additional IDs/new levels of `cover` are when 1) those don't exist in the source data, and 2) were intended to replace the original `cover` values. For my use case I also worry this could possibly lead to spurious collisions in ID -- as for instance 12351/12352/12353 might be keys for some other `"cover"` group that happens to not exist in the extent of `x`

I will get back to you more specifically on this after some more testing

**Comment by rhijmans** [comment]
I have now added an argument `raw=FALSE`. I think that with `raw=TRUE` you get the behavior of prior versions, except that the levels are not removed. See below. 

```
library(terra)
cls <- data.frame(ID =    c(12345,   12346,   12350),
                  cover = c("forest", "water", "urban"))
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(cls$ID, ncell(r), replace = TRUE)
levels(r) <- cls

x <- subst(r, cls$ID, 1:3, raw=TRUE)
x
#class       : SpatRaster 
#dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#resolution  : 36, 18  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#categories  : cover 
#name        : cover 
#min value   :    NA 
#max value   :    NA 

levels(x)[[1]]
#     ID  cover
#1 12345 forest
#2 12346  water
#3 12350  urban

levels(x) <- NULL
x
#class       : SpatRaster 
#dimensions  : 10, 10, 1  (nrow, ncol, nlyr)
#resolution  : 36, 18  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : cover 
#min value   :     1 
#max value   :     3 
```

 I do not think that removing the levels would be the good default behavior, but there could be another option for that. Although you could currently do 

```
x <- classify(r, cbind(cls$ID, 1:3))
``` 

I have not thought this through, but that may need to change too (also get an argument `raw`), as it ignores the fact `r` is categorical.

**Comment by brownag** [comment]
OK, thanks so much for this! I tested this out, and `subst(..., raw=TRUE)` does the trick, and now I understand what was going on with show method returning NA when the categories have not been updated: setting levels to NULL _or_ updating the ID in cats accordingly would "fix" that. So that is great in general case. 

In `levelplot()`, using `subst(..., raw=TRUE)` with `levels(objectSample) <- NULL` OR `objectSample <- classify(objectSample, cbind(ratID, seq_along(ratID)))` both work equally well, but the latter would be more backward compatible, I think? Unless the default would become `classify(..., raw=FALSE)`... in which case that might break in a future version?

**Comment by rhijmans** [comment]
for rasterVis I would recommend extracting the levels and then setting them to NULL to avoid future clashes.

**Comment by rhijmans** [comment]
I have decided that `classify` will only do "raw".  The only condition where "raw=FALSE" would be meaningful is with a "from-to" matrix, but for that case you can use `subst`.

**Comment by brownag** [comment]
This makes sense to me, thanks again Robert!
