### ISSUE TITLE
`subst()`: zero-length `to` argument crashes R (floating point exception)

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#788]
I stumbled across this while looking into #787

```r
library(terra)
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(3, ncell(r), replace = TRUE)
```

`to=numeric(0)` or similar crashes R w/ message "Floating point exception (core dumped)"

```r
subst(r, from = 1:3, to = numeric(0))
```

When `to` is calculated from something else / referencing non-existent object zero-length can happen, so I suppose the suggestion here is to just handle the possibility to avoid crashing.

When `to` is actually NULL, R does not crash, it gives the following error, which makes sense.

```r
subst(r, from = 1:3, to = NULL)
#> Error in x@ptr$replaceValues(from, to, 0, keepcats, opt) : 
#>  Not compatible with requested type: [type=NULL; target=double].
```

**Comment by rhijmans** [comment]
Thanks, that is an easy one. I now get:

```
library(terra)
#terra 1.6.11
r <- rast(nrows = 10, ncols = 10)
values(r) <- sample(3, ncell(r), replace = TRUE)
subst(r, from = 1:3, to = numeric(0))
#Error: [subst] argument 'to' cannot be empty
```
