### ISSUE TITLE
resample method = "med" error 

### ISSUE THREAD

**Issue by Canderson156** [rspatial/terra#789]
I've been trying to resample a raster, and I get an error message when I try to use median as the resample method. I've tried using both "med" as stated in the help file, and "median". The same code works fine with all of the other simple descriptive statistics listed together (i.e. average, mode, min, max etc)

I'm using the development version of terra (1.6-12)

r <- rast(nrows=3, ncols=3, xmin=0, xmax=10, ymin=0, ymax=10)
values(r) <- 1:ncell(r)
s <- rast(nrows=25, ncols=30, xmin=1, xmax=11, ymin=-1, ymax=11)
x <- terra::resample(r, s, method="med")
Error: [resample] 

x <- terra::resample(r, s, method="median")
Error: [resample] not a valid warp method

**Comment by rhijmans** [comment]
Thank you for reporting this. I now get:

```
x <- resample(r, s, method="med")
x
#class       : SpatRaster 
#dimensions  : 25, 30, 1  (nrow, ncol, nlyr)
#resolution  : 0.3333333, 0.48  (x, y)
#extent      : 1, 11, -1, 11  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 
#source      : memory 
#name        : lyr.1 
#min value   :     1 
#max value   :     9 
```
