### ISSUE TITLE
Attempting to overwrite raster files currently open causes R to crash

### ISSUE THREAD

**Issue by mcoghill** [rspatial/terra#79]
I often need to overwrite raster files for my work, but I've noticed that if the raster is open in a session as an SpatRaster object and then I try to overwrite it, my session crashes. Here is a reproducible example:

```
library(terra)

r <- terra::rast(ncols=10, nrows=10)
values(r) <- 1:ncell(r)

# Save raster as a file
r <- terra::writeRaster(r, filename = file.path(tempdir(), "temp.tif"), overwrite = TRUE)

# When overwriting a file currently loaded into your R session, R will crash (at least in RStudio)
r <- terra::writeRaster(r, filename = file.path(tempdir(), "temp.tif"), overwrite = TRUE)
```

I think I understand why this happens, but would it be possible to instead include a check before writing the raster file to see if any SpatRaster objects in the R session are already saved in the file path specified, and then throw an error if the file exists and is loaded into your R session currently? Hopefully that makes sense!

**Comment by rhijmans** [comment]
The problem was that you were reading from and writing to the same filename `file.path(tempdir(), "temp.tif")`. I have now disallowed that. Now I get 

```
library(terra)
r <- terra::rast(ncols=10, nrows=10)
values(r) <- 1:ncell(r)
f <- file.path(tempdir(), "temp.tif")
x <- terra::writeRaster(r, f, overwrite = TRUE)
y <- terra::writeRaster(x, f, overwrite = TRUE)
#Error: [writeRaster] source and target filename cannot be the same
```

**Comment by mcoghill** [comment]
That is what I expected was happening. Thank you so much!

**Comment by mosscoder** [comment]
Sorry to resurrect, but does there exist any method to add a band to an extant .tif without loading it into memory?

**Comment by rhijmans** [comment]
That is not related to this issue. But for what you want you can use `writeRaster(x, "file.tif", gdal="APPEND_SUBDATASET=YES")`
`

**Comment by mosscoder** [comment]
Thanks for responding. The gdal argument is not working for me. Here is the specific scenario I'm having trouble with:
1) Read raster from disk
2) Add a band to it
3) Overwrite file from 1)

I cannot get writeRaster to do this job, but come up with a hack as illustrated here:
```
library(terra)

writeRaster2 <- function(x, fname){
  tf <- tempfile(fileext = '.tif')
  terra::writeRaster(x, tf)
  new_x <- terra::rast(tf)
  file.remove(fname)
  terra::writeRaster(new_x, fname)
}

rast_1 <- rast_2 <- rast(ncol = 5, nrow = 5)
values(rast_1) <- values(rast_2) <- 1:25

writeRaster(rast_1, 'write_test.tif')
rm(rast_1)

rast_1 <- rast('write_test.tif')

add(rast_1) <- rast_2

writeRaster(rast_1, 'write_test.tif', overwrite = T) #Nope
writeRaster(rast_1, 'write_test.tif', gdal="APPEND_SUBDATASET=YES") #Nope

writeRaster2(rast_1, 'write_test.tif') #Hacky, but yes

rast('write_test.tif')
```
