### ISSUE TITLE
terra not reading .tif file properly 

### ISSUE THREAD

**Issue by flottsam** [rspatial/terra#790]
I've a [raster (.tif) file](https://drive.google.com/file/d/19daTbc2DIG4eqjBTxvXQ_WJLevA0gh-X/view?usp=sharing) that has values between 0 and 6. 
With raster, reading the file looks like this:
`(rat <- raster::raster(here("burn_severity/fl_rx/mtbs/2010/fl2567008105120100422_20100616_nbr6.tif")))`
![image](https://user-images.githubusercontent.com/7258443/188193271-5ea55d5e-9aed-4bb2-80d4-0f9764829481.png)
However, reading the same file with terra provides "Histogram" values that out of range of the data. 
 
`(rat <- terra::rast(here("burn_severity/fl_rx/mtbs/2010/fl2567008105120100422_20100616_nbr6.tif")))
`
![image](https://user-images.githubusercontent.com/7258443/188193520-456c18c9-fb9d-4ea6-a9df-5feab8e0b3fd.png)

Any ideas as to what is going on?

**Comment by flottsam** [comment]
*Added file link to OP

**Comment by rhijmans** [comment]
Can you also upload the sidecar file(s)? There probably is a file called  "fl2567008105120100422_20100616_nbr6.tif.xml"  or "*.vat.dbf"

**Comment by flottsam** [comment]
* added .aux and .rrd files, but did not see a .tif.xml or .vat.dbf. 
* Also added basic metadata (xml) describing the processing.

**Comment by flottsam** [comment]
Woops, sorry about that. 
Link to folder:
https://drive.google.com/drive/folders/1z742sNEIyD8hsuNfppramOFwJXSvqsMG?usp=sharing

**Comment by rhijmans** [comment]
What you see with terra is that the file has an attribute table with one variable "Histogram"
```
library(terra)
f <- "fl2567008105120100422_20100616_nbr6.tif"
r <- rast(f)
r
#class       : SpatRaster 
#dimensions  : 680, 617, 1  (nrow, ncol, nlyr)
#resolution  : 30, 30  (x, y)
#extent      : 1500075, 1518585, 402945, 423345  (xmin, xmax, ymin, ymax)
#coord. ref. : Albers Conical Equal Area 
#source      : fl2567008105120100422_20100616_nbr6.tif 
#color table : 1 
#categories  : Histogram 
#name        : Histogram 
#min value   :    357457 
#max value   :      3612 
``` 

You can get rid of it like this:

```
levels(r) <- NULL
r
#class       : SpatRaster 
#dimensions  : 680, 617, 1  (nrow, ncol, nlyr)
#resolution  : 30, 30  (x, y)
#extent      : 1500075, 1518585, 402945, 423345  (xmin, xmax, ymin, ymax)
#coord. ref. : Albers Conical Equal Area 
#source      : fl2567008105120100422_20100616_nbr6.tif 
#color table : 1 
#name        : Histogram 
#min value   :         0 
#max value   :         6 
``` 

However, since this is a degenerate case  (histogram is not really an attribute like, for example, land cover class names would be), I now suppress this case and with the development version I get:

```
r <- rast(f)
r
#class       : SpatRaster 
#dimensions  : 680, 617, 1  (nrow, ncol, nlyr)
#resolution  : 30, 30  (x, y)
#extent      : 1500075, 1518585, 402945, 423345  (xmin, xmax, ymin, ymax)
#coord. ref. : Albers Conical Equal Area 
#source      : fl2567008105120100422_20100616_nbr6.tif 
#color table : 1 
#name        : Layer_1 
#min value   :       0 
#max value   :       6 
```
