### ISSUE TITLE
`lapp` does not accept `usenames` argument when using a `SpatRasterDataset`

### ISSUE THREAD

**Issue by colinbrust** [rspatial/terra#793]
When using the `lapp` function on a `SpatRasterDataset` arguments can only be passed by order. In the example below, the lapp function fails on an `sds` when the usenames argument is supplied:

```r
library(terra)

s <- rast(system.file("ex/logo.tif", package="terra")) + 1  

# Named Function
fvi2 <- function(red, green){ (red - green ) / (red + green) } 

# Works as Expected
x1 <- lapp(s[[1:2]], fvi2, usenames=TRUE)

sds_example <- sds(s[[1]], s[[2]])

# Works, output is equal to x1.
lapp(sds_example, fvi2)

# Throws an error.
lapp(sds_example, fvi2, usenames = TRUE)

# Throws the same error.
names(sds_example) <- c("red", "green")
lapp(sds_example, fvi2, usenames = TRUE)
```

When using the `usenames` argument, the following error is raised:
```
Error in (function (red, green)  : unused argument (usenames = TRUE)
Error: [lapp] cannot use 'fun'. The number of values returned is less than the number of input cells. (returning: 1, expecting: 101)
Perhaps the function is not properly vectorized.
```

Looking through the source code, it appears the implementation of `lapp` for a `SpatRasterDataset` does not accept a `usenames` argument, meaning `usenames` just gets passed to `fun`. Is there any reason the argument isn't implemented for this class? 

I would be happy to work on a PR that either adds the argument to the function or adds documentation explaining why it can't be used for the `SpatRasterDataset` class.

**Comment by rhijmans** [comment]
Thanks, your examples work now. 

As an aside:; you say that:

> Looking through the source code, it appears the implementation of lapp for a SpatRasterDataset does not accept a usenames argument

That should have been clear from the the Usage section: 

```
## S4 method for signature 'SpatRasterDataset'
lapp(x, fun, ..., recycle=FALSE, filename="", overwrite=FALSE, wopt=list())
```

But there was no reason for not having the argument, so thanks again.

**Comment by colinbrust** [comment]
Oops, I missed that in the Usage section. Thanks for you work on this!
