### ISSUE TITLE
Reading Zarr files using terra

### ISSUE THREAD

**Issue by zavud** [rspatial/terra#799]
As far as I know, Zarr files currently cannot be read using terra (please correct me if I am wrong). Is this functionality expected in terra?

**Comment by rhijmans** [comment]
I believe that it is available *if* your version of "terra" was built against GDAL > 3.4. That is the case with the current CRAN windows binary release. I do not know which OS and version of GDAL you use. See `gdal()`

**Comment by rhijmans** [comment]
Also see 

```
library(terra)
d <- gdal(drivers=TRUE)
d[d$name == "Zarr", ]
#    name   type        can  vsi long.name
#144 Zarr raster read/write TRUE      Zarr
``` 

And there is more info here:  https://gdal.org/drivers/raster/zarr.html

**Comment by kadyb** [comment]
One more interesting question. Does `{terra}` support [multidimensional array API](https://gdal.org/api/index.html#multi-dimensional-array-api)?

Here is recent blogpost from Edzer Pebesma about Zarr files support in `{stars}`: https://r-spatial.org/r/2022/09/13/zarr.html. The main limitation of the GDAL driver is that the time dimension cannot be loaded.

**Comment by rhijmans** [comment]
I did implement the multidimensional array here:  https://github.com/rspatial/terra/blob/master/src/gdal_multidimensional.cpp
But it is not being used as I did not see any benefits when using NetCDF.  I had assumed it would be much faster but it wasn't. Not sure if there is any functionality benefit.  I should have a look at it again with Zarr files.
