### ISSUE TITLE
handling NetCDF files

### ISSUE THREAD

**Issue by fabeit** [rspatial/terra#80]
I see that in terra some of the options have changed as far as handling netcdf. There is a previous issue in which it is explained that terra uses rgdal for ncdf files.

In my case I try to use the "names" wopt to write the layer names but when I load the raster the layer names are just band1, band2, etc.. Also it seems in terra "varname" cannot be specified when reading and writing? And writeRaster in terra doesn't include options such as varunits?

So are the functionalities for ncdfs' rather different between the two packages?

Also, when I try to set names after mystack=rast("my file.nc") I get the following error
```
[mystack@ptr$names=mynames
Error in (new("activeBindingFunction", .Data = function (x)  : 
  property is read only]
```

**Comment by fabeit** [comment]
Solved the names problem by using this command names(mystack)=mynames

**Comment by rhijmans** [comment]
> in terra "varname" cannot be specified when reading and writing? 

When reading you can specify it, except that it now called `subds` (for "subdataset")

> And writeRaster in terra doesn't include options such as varunits?

Not yet. ncdf writing is rather different than other formats, so it will take a little to add all the options. I am currently working on extracting more metadata (dates, band names).

> So are the functionalities for ncdfs' rather different between the two packages?

Yes. But terra will catch up. And in some ways it can do more, e.g. read multiple subdatasets with `sds`, or combine them all with `rast`.

**Comment by fabeit** [comment]
I guess we can start with something simple. I have file with 100k time steps but when I use rast or sds I get "Warning 1: Limiting number of bands to 32768 instead of 1095000"

**Comment by rhijmans** [comment]
> "Warning 1: Limiting number of bands to 32768 instead of 1095000"

This is now gone. You can now get up to 9999999 layers.

> how do I "unlock" files

This seems to be happening with ncdf files only. And I only see it with GDAL 3.0.4 (on Windows) but not with GDAL 2.2.3 (Linux) nor with GDAL 3.2.0 (Mac Catalina). So it seems like a bug in GDAL, but not sure if it is related to a particular version, or to the windows OS.

> writeRaster in terra doesn't include options such as varunits?

There now is `writeCDF` method that has that and more options (and let me know if more need to be added). This does not use GDAL.

**Comment by rhijmans** [comment]
After some more testing, I have changed terra such that netcdf writing is always done with writeCDF, not with GDAL. This will likely change when I start developing against GDAL 3.2; and I can use the new GDAL multidimensional array structure that matches the ncdf data model. Therefore, `wopt=list(ncdfcopy=FALSE)` is ignored.

**Comment by fabeit** [comment]
I would like to test this but if I try to install from source using rtools 4.0 I get his error

Error in setMethod("median", signature(x = "SpatRaster"), function(x,  : 
  no existing definition for function 'median'
Error: package or namespace load failed for 'terra':
 unable to load R code in package 'terra'
Execution halted
ERROR: lazy loading failed for package 'terra'

Any idea why? When do you think you will release the latest compiled package?

**Comment by rhijmans** [comment]
How exactly do you install? Do yo use  R CMD INSTALL, or from an R session (Rgui, Rstudio?) with `remotes::install_github`  or `devtools::install_github`, or ...?   R 4.0.3?

That is the first I have heard of that message, but I did make a change that may have fixed it --- it is hard to know as I did not see the error in the first place.  Can you try once more?

I want to send a version to CRAN very soon (this week), but it can sometimes take a while before it actually gets posted there.

**Comment by jkjkjij22** [comment]
> Read multiple subdatasets with `sds`

To confirm, if we know a file has multiple layers, should we use `sds` to import rather than `rast`?
When I import an `nc` file with `rast`, the layer names are lost. For example, when I run the following code, `s2` lists the `names(s2)` as `"temp_1"  "temp_2"` ... `"prec_9"  "prec_10"` instead of `"temp" "prec"`

```
# create rast
a <- rast(ncols=5, nrows=5, nlyrs=10)
values(a) <- 1:prod(dim(a))
b <- sqrt(a)
s <- sds(a, b)
names(s) <- c("temp", "prec")
# save rast
fname <- "foo.nc"
s1 <- writeCDF(s, fname, overwrite=TRUE)
# import rast
s2 <- rast(fname)
s3 <- sds(fname)
```

**Comment by rhijmans** [comment]
In a NCDF file, there is one name per (sub-) dataset, the "layers" are time-steps or such. With `terra` you can write the variable name like this

```
writeCDF(a, fname, overwrite=TRUE, varname="prec")
rast(fname)
#class       : SpatRaster 
#dimensions  : 5, 5, 2  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : a.nc 
#varname     : prec 
#names       : prec_1, prec_2 
```

If you want multiple datasets, you need to make a `SpatRasterDataSet` 

```
sd <- sds(c(a[[1]],a[[1]]/2), c(a[[2]], a[[2]]/2))
names(sd) <- c("prec", "temp")
writeCDF(sd, fname, overwrite=TRUE, )
rast(fname)
#class       : SpatRaster 
#dimensions  : 5, 5, 4  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#sources     : a.nc:prec  (2 layers) 
#              a.nc:temp  (2 layers) 
#varnames    : prec 
#              temp 
#names       : prec_1, prec_2, temp_1, temp_2 
```

There was a bug when requesting a subdataset, now fixed, and --- if there are subdatsets --- you can do 

````
rast(fname, "temp")
#class       : SpatRaster 
#dimensions  : 5, 5, 2  (nrow, ncol, nlyr)
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source      : a.nc:temp 
#varname     : temp 
#names       : temp_1, temp_2 
```
Or you can read the file with `sds`

```
sds(fname)
#class       : SpatRasterDataset 
#subdatasets : 2 
#dimensions  : 5, 5 (nrow, ncol)
#nlyr        : 2, 2 
#resolution  : 72, 36  (x, y)
#extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
#source(s)   : a.nc 
#names       : prec, temp 
```

**Comment by jkjkjij22** [comment]
Thanks for the quick response. 
that makes sense. So layers should be reserved for time, while multiple datasets should be handled using `sds`.
My error was to combine multiple distinct rasters using `c` rather than `sds`. The correct way to execute my example would be: 
```
# create raster
library(terra)
a <- rast(ncols=5, nrows=5, nlyrs=2)
values(a) <- 1:prod(dim(a))
b <- a^2
r <- sds(a,b)
names(r) <- c("temp", "prec")
# save raster
fname <- "a.nc"
writeCDF(r, fname, overwrite=TRUE)
# import raster using sds
r_read <- sds(fname)
```

**Comment by rhijmans** [comment]
Just some comments:  in a case like this you can use `sds(fname)` or `rast(fname)`. It depends on the file contents and your goals what makes most sense.  Sometimes the subdatasets are really just "layers", e.g. bands in a remote sensing image in which case `rast` may be more convenient. `sds` can open subdatasets with different resolutions.
