### ISSUE TITLE
spatSample with na.rm=TRUE returns Error: negative probability

### ISSUE THREAD

**Issue by dramanica** [rspatial/terra#800]
When sampling certain rasters with `spatSample`, adding `na.rm=T` gives a "negative probability" error. The same operation on those rasters worked fine a couple of month ago, so this issue is linked to a recent change to `spatSample`. I can replicated the behaviour on both Linux and Windows, using the CRAN version as well as the `dev` version from GitHub. 
Strangely, using the examples from the function help, I can't replicate the error. I can't spot anything obviously different in the offending rasters. So I created a small raster that reproduces the problem, and can be downloaded from [here](https://drive.google.com/drive/folders/1FD2K2gduHgcdV8-PfG3NmK2pCTLL3X7L?usp=sharing). Then, if I run:
```
library(terra)
foo <- rast("terra_sample_crash.tiff")
spatSample(foo, 100, na.rm = TRUE)
```
I get:
```
Error in sample.int(nrow(v), min(size, nrow(v)), prob = v[, 2], replace = replace) : 
  negative probability
```
Note that, if I don't set `na.rm=TRUE`, the sampling is successful.
`sessionInfo()` on my Linux machine gives:
```
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.6-18

loaded via a namespace (and not attached):
[1] compiler_4.2.1   tools_4.2.1      Rcpp_1.0.9       codetools_0.2-18
```

**Comment by rhijmans** [comment]
I cannot reproduce this. For example, this works for me:
```
library(terra)
r = rast(c(f, f, f))
s = spatSample(r, 100, na.rm = TRUE)
``` 
Can you share the file with me, or at least  `show(foo)`

**Comment by dramanica** [comment]
@rhijmans thanks for looking into this. Does the link in the message above not work for you? It's a public folder on a google drive, but let me know if you there is a better way to share the file. Anyway, I repaste the link here for convenience: [https://drive.google.com/drive/folders/1FD2K2gduHgcdV8-PfG3NmK2pCTLL3X7L?usp=sharing](https://drive.google.com/drive/folders/1FD2K2gduHgcdV8-PfG3NmK2pCTLL3X7L?usp=sharing)

**Comment by rhijmans** [comment]
I am sorry, I somehow overlooked the link. That is an ugly bug that has now been fixed.

**Comment by dramanica** [comment]
Brilliant, thank you!

**Comment by rhijmans** [comment]
I will send a new version to CRAN later this week.

**Comment by sgvignali** [comment]
Perfect, thank you @rhijmans
