### ISSUE TITLE
Dimension error in setMethod("rast", signature(x="list")

### ISSUE THREAD

**Issue by BastienFR** [rspatial/terra#804]
I got a weird warning while aggregating a list of `spatRaster` into one big `spatRaster` 

```
Warning message:
In rnms[lnms != ""] <- lnms[lnms != ""] :
  number of items to replace is not a multiple of replacement length
```

This error happens when you are aggregating two or more rasters with a total odd number of layers.

Reproducible example:
```
library(terra)

ras1 <- rast(nrows=108, ncols=21, xmin=0, xmax=10,nlyrs = 3)
ras1[] <- sample(1:20, 108*21*3, replace=T)
names(ras1) <- paste0("ras1_layer", 1:3) 

ras2 <- rast(nrows=108, ncols=21, xmin=0, xmax=10,nlyrs = 2)
ras2[] <- sample(1:20, 108*21*2, replace=T)
names(ras2) <- paste0("ras2_layer", 1:2) 

ll <- list(ras1, ras2)
names(ll) <- c("ras1", "ras2")
rast(ll)
```

The aggregation occurs but the layer names make no sense.

```
class       : SpatRaster 
dimensions  : 108, 21, 5  (nrow, ncol, nlyr)
resolution  : 0.4761905, 1.666667  (x, y)
extent      : 0, 10, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
sources     : memory  (3 layers) 
              memory  (2 layers) 
names       : ras1, ras2, ras1, ras2, ras1 
min values  :    1,    1,    1,    1,    1 
max values  :   20,   20,   20,   20,   20 
```

This error happens only when the list is named.  If I use a list with no name I get no warning and perfect naming:

```
ll <- list(ras1, ras2)
rast(ll)
class       : SpatRaster 
dimensions  : 108, 21, 5  (nrow, ncol, nlyr)
resolution  : 0.4761905, 1.666667  (x, y)
extent      : 0, 10, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
sources     : memory  (3 layers) 
              memory  (2 layers) 
names       : ras1_layer1, ras1_layer2, ras1_layer3, ras2_layer1, ras2_layer2 
min values  :           1,           1,           1,           1,           1 
max values  :          20,          20,          20,          20,          20 
```

In the source code, the problem comes from line 90 to 96 of `rast.R` file:

```
lnms <- names(x)
  i <- lnms != ""
  if (any(i)) {
    rnms <- names(out)
    rnms[lnms != ""] <- lnms[lnms != ""]
    names(out) <- rnms
  }
```

 I don't quite get why those lines of code are there, the naming works well without them.  What are they suppose to do?  `rnms` and `lnms` are not suppose to be the same length so the substitution :

`rnms[lnms != ""] <- lnms[lnms != ""]`

isn't suppose to ever make sense...

Am I missing anything?

**Comment by rhijmans** [comment]
Thanks. The idea is that if a list is named these names are used as layer names. However, that can only work if all list elements are SpatRasters with a single layer, and there now is a check for that.

**Comment by BastienFR** [comment]
Thanks for your quick response, however I was thinking about my problem and I was wondering if we could not program something that combine the both the name of the list element and the name of the layers.  I was thinking of something like:

```
  lnms <- names(x)
  i <- lnms != ""
  if (any(i)) {
    names(out) <- paste0(rep(lnms, sapply(x, nlyr)), "_", names(out))
  }
```

I can easily imagine situation where this is useful, for example a list of raster where each element of the list represent a year and each layers a month.  Combining them without renaming would duplicates the layer names.

Could it work or would it breaks the code somewhere else?

**Comment by rhijmans** [comment]
What I have done now is always assign a new name if all list elements have a name. Instead of combining with the old name, I have used "_1", "_2", ... when there are multiple layers. That it seemed cleaner.  I am not sure if it is better. That would probably depend on the context.

**Comment by BastienFR** [comment]
I've tested you fix and I think it's perfect.  Using indexes instead of names works.  It allows the user to understand the way the aggregation is done and after that, nothing stops him to change the names again.  At least now the names mean something.  Thanks for your quick fix.
