### ISSUE TITLE
Export classes

### ISSUE THREAD

**Issue by andrewmarx** [rspatial/terra#807]
Would it be possible to export the classes (e.g., SpatRaster)?

I'm updating my package to support terra, but need to be able to import the SpatRaster class via `importClassesFrom("terra", "SpatRaster")` in my NAMESPACE file.

```
1: class "SpatRaster" is not exported by 'namespace:terra' 
2: class "SpatRaster" is defined (with package slot ‘terra’) but no metadata object found to revise superClass information---not imported?  Making a copy in package ‘samc’ 
```

**Comment by rhijmans** [comment]
Thanks, I think this should work now.
