### ISSUE TITLE
Raster values under a polygon won't convert to NA

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#809]
I'm trying to convert raster values that overlap a given polygon to NA, but they are converted to 1 instead:

```
elev <- geodata::elevation_30s("LUX", path = tempdir())

lux <- vect(system.file("ex/lux.shp", package="terra"))
rem <- subset(lux, lux$NAME_2 == "Remich")

# attempt to convert values in Remich to NA:
elev[rem] <- NA
unique(elev[rem])  # values are 1 instead

# convert values in Remich to a number:
elev[rem] <- 200
unique(elev[rem])  # ok
```
It works if I first convert them to a given number, and then reclassify that number to NA:
```
elev[rem] <- 100000
elev[elev == 100000] <- NA
unique(elev[rem])  # ok
```
But it would be good to avoid this extra step. Cheers!

**Comment by rhijmans** [comment]
Ha, I fixed that yesterday! So this works with the development version...
