### ISSUE TITLE
Function to cut a raster up into individual tiles to ease memory usage issues?

### ISSUE THREAD

**Issue by AndreMBellve** [rspatial/terra#81]
Hi again,

First off, if you think this is better placed on stack.gis, then let me know and I will close it and migrate it over there.

I was wondering if there are any plans to write a function to cut a large raster up into many small tiles? I am running into some significant memory issues when I am trying to `extract` large volumes of data from my rasters for modelling and creating new surfaces, since `terra` hasn't (yet) been integrated into some of the R modelling packages I use.

One aspect of my current work involves modelling a variable across the extent of NZ to a resolution of 100 × 100m cells and creating a new surface from this. I have managed to `extract` the data from my predictive rasters, and construct a model of the variable using some real world observations, but I would now like to use said model to make predictions of the variable over the entirety of NZ. The above worked as I was only extracting ~40,000 data points.

The model I have built is a boosted regression tree in `caret`. I would like to be able to `extract` all the data in my rasters (i.e. every cell), along with the respective lat-long coordinates, feed this into `predict` with my model to get estimates of the variable for every cell in NZ and then create a new raster based on these predictions. 

However, currently if I try to `extract` these data from my raster (unsurprisingly) I hit memory issues as it needs approximately 30 gb of RAM, as the dataframe is comprised of 152,303,360 × 16 points. The only work around I can think of is to snip my raster up into a bunch of individual tiles, `extract` from each and then `predict` the value of interest and then turn the resulting dataframe into a raster somehow.

I have seen some useful functions for doing this for objects form the `raster` package ([see `SpaDES::splitRaster` function](https://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/splitRaster)), but I can't find anything in the `terra` package. I can snip my rasters piecemeal using the `crop` function but it would be great to have something that let me parse it into convienent tiles to make processing more managable.

Alternatively, is there a better way to do this? I am going to need to do something like this for several of my work streams but I am somewhat stuck about how to do this efficiently.... Currently all I can think of are some rather janky `for` loops using crop to cut the raster up.

**Comment by rhijmans** [comment]
I think you should be able to use the `interpolate` (to automatically pass lon/lat to the model) or `predict`  methods

**Comment by AndreMBellve** [comment]
Thank you! I had tried `terra::predict` and I think I have puzzled out why it didn't work originally. 

The model that I fed it needed some of the predictive layers I have to be converted to categorical variables. Since the `as.factor` function doesn't seem to be working still, I converted the variables after the `terra::extract()` call. However, this causes issues down stream when I try to use `predict` because the model is expecting to be fed factors, but all of my categorical rasters are still being stored as numeric. 

I have tried using 

`predRast[['basic_ecosystems']] <- as.factor(predRast[['basic_ecosystems']])`

which executes but then when I plot the raster and print out its information it appears to remain unchanged.

Here is an example of this:
```
#Listing file names in raster folder
rasterFiles <- list.files("./data/Rasters/NZGD2000", pattern = ".tif", full.names =  TRUE) 

#Reading in all rasters
predRast <- rast(rasterFiles)  

#Altering single raster 
predRast[['basic_ecosystems']] <- as.factor(predRast[['basic_ecosystems']])

#printing
predRast[['basic_ecosystems']]
class       : SpatRaster 
dimensions  : 14920, 10208, 1  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : 1079600, 2100400, 4737300, 6229300  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +units=m +no_defs 
data source : basic_ecosystems.tif 
names       : basic_ecosystems 
min values  :                0 
max values  :               17 

plot(predRast[['basic_ecosystems']])
```
![image](https://user-images.githubusercontent.com/43392206/90203221-3e1d6180-de34-11ea-9200-5cbf5358ccc5.png)

Any ideas on how to get around the factor issue?

**Comment by rhijmans** [comment]
I closed this because I added a `tiles` method that does what was requested --- even though it should not be necessary to use it for this purpose. As for the `factors`. As there is no reproducible example, I cannot say whether it now works or not. But I would expect that it does work now.
