### ISSUE TITLE
Read .grd files from dismo package

### ISSUE THREAD

**Issue by sgvignali** [rspatial/terra#811]
Hi, is there a way to read the ".grd" files included in `dismo` using `terra`?

I've tried with the following but it doesn't work:

```R
files <- list.files(path = file.path(system.file(package = "dismo"), "ex"),
                    pattern = "grd", full.names = TRUE)

predictors <- terra::rast(files)
```

I'm planning to move from `raster` to `terra` in my package `SDMtune` but I have many code examples that use these files, it would be great to read them with `terra`.

Sergio

**Comment by kadyb** [comment]
> Error: [rast] cannot open this file as a SpatRaster: C:/Users/Krzysztof/AppData/Local/R/win-library/4.2/dismo/ex/bio1.grd
> In addition: Warning message:
> Unhandled datatype=INT2S  (GDAL error 1) 

You received the above error because GDAL cannot parse this file properly, so `{terra}` cannot read it. These files have the data type written incorrectly with the space `INT2S `. It would be best to make PR with the corrected data directly in `{dismo}`.

As workaround, you can overwrite these files on disk:

```r
files = list.files(path = system.file("ex", package = "dismo"),
                   pattern = "grd", full.names = TRUE)

for (f in files) {
  txt = readLines(f)
  txt[13] = "datatype=INT2S"
  writeLines(txt, f)
}
```

**Comment by rhijmans** [comment]
I will fix that in dismo, but the problem is more widespread.  A more general version of @kadyb's solution

```
files = list.files(path = system.file("ex", package = "dismo"),  pattern = "grd", full.names = TRUE)
for (f in files) {
  txt = readLines(f)
  writeLines(trimws(txt), f)
}
``` 

You can also read them via "raster" 

You can also read them via "raster"  like this by forcing the values into memory

```
r <- rast(raster::stack(files) * 1)
```

**Comment by kadyb** [comment]
@rhijmans, I just wrote this code to overwrite these files in `{raster}`. Will you accept PR from me or will you do it yourself?

```r
library("raster")

files = list.files("inst/ex/", pattern = "grd", full.names = TRUE)

output = file.path("inst", "ex2")
dir.create(output)

for (f in files) {
  r = raster(f)
  dt = dataType(r)
  writeRaster(r, file.path(output, basename(f)), datatype = dt)
}
```

**Comment by kadyb** [comment]
/\ out of date: https://github.com/rspatial/dismo/commit/a3cb88f0ec7b1e1f9de9729cea2fc71879a47c81 😄

**Comment by rhijmans** [comment]
Yes, beat you to it. Fixed it in dismo and raster

**Comment by sgvignali** [comment]
Thank you @rhijmans, when will you release the new version of `dismo` on CRAN?

**Comment by rhijmans** [comment]
I can send it to CRAN whenever you tell me to do so,

**Comment by sgvignali** [comment]
If you are ready to submit the new version it would be great to have it on CRAN as soon as possible

**Comment by rhijmans** [comment]
It is on CRAN now.
