### ISSUE TITLE
Layers with different CRS intended behavior?

### ISSUE THREAD

**Issue by andrewmarx** [rspatial/terra#818]
It's possible to combine rasters with different projections:

```
r1 <- rast(system.file("ex/elev.tif", package="terra"))
r2 <- r1
crs(r2) <- "epsg:25831"
both <- c(r1, r2)
crs(both) # Returns the CRS of layer 1
crs(both[[2]]) # The CRS of layer 2 is still there
```
Is this intended behavior? Or should there be a CRS check when they are combined to make sure they are the same?

**Comment by rhijmans** [comment]
I now get 

```
library(terra)
#terra 1.6.21
r1 <- rast(system.file("ex/elev.tif", package="terra"))
r2 <- r1
crs(r2) <- "epsg:25831"
both <- c(r1, r2)
#Warning message:
#[rast] SRS do not match
``` 

The crs of the first data source is used for the SpatRaster. I think my reasoning for now warning was that if the extent and resolution are the same, then it is highly unlikely that the crs's are truly different. Although it could be in the details, e.g. the datum. A warning is now given. That will likely lead to false positives, but perhaps not too many. Thanks!
