### ISSUE TITLE
issue with stackApply

### ISSUE THREAD

**Issue by apmonr** [rspatial/terra#82]
I very much appreciate working with terra. However, following the Spatial data with terra tutorial, I think I have run into an issue with using stackApply on a RasterStack from class SpatRaster. According to [here](https://rspatial.org/terra/spatial/8-rastermanip.html), I can create a RasterStack by combining multiple SpatRasters with c() (although the class is still SpatRaster). Further down the tutorial says stackApply can be used to compute summary layers for subsets of a RasterStack, but when I try with the stack of SpatRasters I get an error:

`library(terra)`
`library(raster)`

`set.seed(12)`

`r1 <- r2 <- r3 <- r4 <- r5 <- rast(nrow=10, ncol=10)`
`values(r1) <- runif(ncell(r1)) # Assign random cell values`
`values(r2) <- runif(ncell(r2))`
`values(r3) <- runif(ncell(r3))`
`values(r4) <- runif(ncell(r4))`
`values(r5) <- runif(ncell(r5))`

`index <- c(1, 1, 2, 3, 3)`
`r_stack <- c(r1, r2, r3, r4, r5)`
`r_combine <- stackApply(r_stack, indices = index, fun = sum)`

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘nlayers’ for signature ‘"SpatRaster"’

My guess is the stackApply function can't access the number of layers via nlyr(). Is there a way around this? I am using terra version 0.8-6.

Thank you for your time,
Adrian

**Comment by sm-potter** [comment]
stackApply is not a terra package, you need tapp.  A list of raster to terra packages is in the documentation.

**Comment by apmonr** [comment]
Thank you, I see that now.

Adrian
