### ISSUE TITLE
extract() with vector of cell numbers returns SpatRaster

### ISSUE THREAD

**Issue by p-schaefer** [rspatial/terra#821]
There seems to have been a change in the most recent versions of terra to return a ```SpatRaster``` from ```extract()``` when y is given as a vector of cell numbers, i.e.:
```
library(terra)

f <- system.file("ex/meuse.tif", package="terra")
r <- rast(f)

xy <- cbind(179000, 330000)
xy <- rbind(xy-100, xy, xy+1000)

extract(r, xy) # a data.frame
extract(r, cellFromXY(r,xy)) # a SpatRaster
```

Was this intentional? and will it be permanent?

Thanks!

**Comment by rhijmans** [comment]
That was a bug. Thanks very much for reporting!
