### ISSUE TITLE
Different behaviour of `crop` with new terra version

### ISSUE THREAD

**Issue by TamsinWoodman** [rspatial/terra#826]
The behaviour of `crop` seems to have changed in the latest version of terra compared to an older version that I've been using. When using terra 1.6-17, a `SpatRaster` with 220 non-NA cells is returned when I crop a grid of 0.5 degree resolution cells with an outline of the UK:

```r
library("terra")
library("rnaturalearth")

UK_outline <- ne_countries(country = "united kingdom", scale = "large", returnclass = "sf")
UK_polygon <- vect(UK_outline)

UK_cells <- rast(xmin = -14, xmax = 2, ymin = 49.5, ymax = 61, resolution = 0.5)
values(UK_cells) <- 1

UK_cells <- crop(UK_cells, UK_polygon, snap = "in", mask = TRUE)
length(cells(UK_cells))
#>[1] 220
```

Only 136 non-NA cells are returned when I run the same code using terra 1.5-21. Could you let me know if this change is expected behaviour? Thank you!

**Comment by rhijmans** [comment]
I think this is because I added the argument `touches=TRUE` and, apparently, changed the default from `FALSE` to `TRUE`.  

Here with the low res UK boundary to avoid installing another package

```
library("terra")
library("rnaturalearth")
ukp <- ne_countries(country = "united kingdom", returnclass = "sf")
ukp <- vect(ukp)
r <- rast(xmin = -14, xmax = 2, ymin = 49.5, ymax = 61, resolution = 0.5, vals=1)

x <- crop(r, ukp, snap="in", mask=TRUE)
global(x, "notNA")
#      notNA
#lyr.1   182

x <- crop(r, ukp, snap="in", mask=TRUE, touches=FALSE)
global(x, "notNA")
#      notNA
#lyr.1   133
```
