### ISSUE TITLE
Manipulating values from terra SpatRaster using brackets

### ISSUE THREAD

**Issue by tucker-furniss** [rspatial/terra#832]
In the raster package, it was possible to select values from a raster layer using brackets. For example, to select NA cells from raster layer r, you could use: r[is.na(r)], and this would return the cell value of all NA cells. This also worked with values, so one could run: r[r>1 & r<5], and it would return the values of cells that matched the conditions in the bracket. This made it quick and easy to select raster values; indexing behavior worked just like with a data.frame. But with terra, this throws an error (or crashes R). The error is:

Error in object@ptr$cellFromRowColCombine(row - 1, col - 1) :  std::bad_alloc

A similar (possibly related) issue is that in raster, one could use a binary mask to select values from a raster layer. For example, r[mask] would return the values of r where mask == 1. But this also does not work with terra (same error as above). 

I'm not sure if this is a bug or an intentional change, but it is terribly annoying. I can see the purpose of forcing people to use ifel() and mask() functions, but the simple indexing functionality of raster was really intuitive. If at all possible, it would be great to restore this functionality to terra SpatRasters. It would make the transition from raster to terra _much_ easier!

Thanks in advance for considering it!

**Comment by rhijmans** [comment]
I now get:

```
library(terra)
x <- rast(ncol=3, nrow=3, vals=1:9)
y <- rast(ncol=3, nrow=3, vals=1:9)
y[2,] <- NA
x[is.na(y)]
#[1] 4 5 6
 
x[y<5]
#[1] 1 2 3
 
x[y]
#lyr.1 
#    1 
```

**Comment by tucker-furniss** [comment]
Thank you very much for the quick fix, I just updated my packages and it's working great. I should have posted my package versions before but I didn't think to record them before updating, sorry about that. I'm now running terra_1.6-17 and raster_3.6-3. 

The only persistent issue I'm getting is when I run:
y[y>5 & !is.na(y)] 

I get: 
NA NA NA  7  8  9

This isn't a huge problem, but it seems like there may be a small bug. Again, thanks for getting to this so fast!

**Comment by rhijmans** [comment]
I get, with the development version (1.6.28) 

```
y[y>5 & !is.na(y)]
#     lyr.1
#[1,]     7
#[2,]     8
#[3,]     9
```

**Comment by tucker-furniss** [comment]
Perfect, thank you!
