### ISSUE TITLE
Conversion of `RasterLayer` to `SpatRaster` is failing

### ISSUE THREAD

**Issue by ymutua** [rspatial/terra#833]
```
r <- raster(system.file("external/test.grd", package="raster"))
r_rast <- rast(r) 
```

```
Error in methods::as(x, "SpatRaster") : 
  no method or default for coercing “RasterLayer” to “SpatRaster”
```

**Comment by kadyb** [comment]
It works for me in stable (1.6.17) and dev (1.6.28) versions. What is your version?

**Comment by rhijmans** [comment]
This should work if you update "raster" and "terra" to the current version on CRAN. If not, let us know, but please more information such as `sessionInfo()` from a fresh session where this fails.
