### ISSUE TITLE
Change in behavior of categorical variable plots

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#835]
This is the follow up from changes made RE: #830. I noticed that there are instances where the raster only contains a subset of the possible category value:label from the RAT that the plot does not look correct. 

In the images below there should be only 2 vertical black (NoData) bars, and they should be in the 5th and 10th position (left to right)

With latest terra off GitHub (4 black bars)
``` r
library(terra)
#> terra 1.6.28
n <- 10
r <- rast(nrow = n, ncol = n)
rat <- data.frame(lyr.1 = 1:n, group = LETTERS[1:n])
values(r) <- rep(c(2,4,6,8,NA), 20)
levels(r) <- rat
activeCat(r) <- "group"
par(bg='black', fg="white")
plot(r)
```

![](https://i.imgur.com/4DyDstp.png)

With latest CRAN version (2 black bars)
``` r
library(terra)
#> terra 1.6.17
n <- 10
r <- rast(nrow = n, ncol = n)
rat <- data.frame(lyr.1 = 1:n, group = LETTERS[1:n])
values(r) <- rep(c(2,4,6,8,NA), 20)
levels(r) <- rat
activeCat(r) <- "group"
par(bg='black', fg="white")
plot(r)
```

![](https://i.imgur.com/wrZ75kd.png)

**Comment by rhijmans** [comment]
You were right (in #830) and this is now fixed as suggested.  Thanks for all your help!
