### ISSUE TITLE
Possible memory leak in distance()

### ISSUE THREAD

**Issue by andrewmarx** [rspatial/terra#836]
Just reporting that when using the distance() function with matrices for x and y I'm seeing multiple GB of memory being allocated (which is not surprising), but when the function has finished and I follow up with a gc(), most of that memory remains allocated even thought the final vector is only a small fraction of that size. It occurs whether `pairwise` is true or false.

When `n = 1000`, my memory monitor shows about a 3-4 GB permanent increase in memory usage after running distance()

When `n = 2000`, my memory monitor shows about a 14 GB permanent increase in memory usage after running distance()

Running the distance() function repeatedly doesn't seem to cause a cumulative effect, though, indicating that the allocated memory is being reused somehow on subsequent runs.

Tested using a fresh source install of terra at the time of posting. R version 4.2.1. Linux Mint Cinnamon 20.1 (which is based on Ubuntu 20.04)

```
n = 1000
res_data <- matrix(runif(n^2)*10 + 1, nrow = n)

resistance = terra::rast(res_data, extent = terra::ext(0.5, n + 0.5, 0.5, n + 0.5), crs = "local")

cell_nums = terra::cells(resistance)
adj = terra::adjacent(resistance, cells = cell_nums, pairs = TRUE, directions = 4)

coords <- cbind(terra::xyFromCell(resistance, adj[, 1]),
                terra::xyFromCell(resistance, adj[, 2]))

dist <- terra::distance(coords[, 1:2],
                        coords[, 3:4],
                        lonlat = terra::is.lonlat(resistance),
                        pairwise = TRUE)
```

**Comment by rhijmans** [comment]
Thank you for your report. I think that in the end you already concluded yourself that there was no leak. 

If you install valgrind, you can check for memory leaks like this (where `test.R` has the script that is run):

```
R -d valgrind -f test.R
 
> library(terra)
terra 1.6.28
>
> n = 100
> res_data <- matrix(runif(n^2)*10 + 1, nrow = n)
>
> resistance = terra::rast(res_data, extent = terra::ext(0.5, n + 0.5, 0.5, n + 0.5), crs = "local")
>
> cell_nums = terra::cells(resistance)
> adj = terra::adjacent(resistance, cells = cell_nums, pairs = TRUE, directions = 4)
>
> coords <- cbind(terra::xyFromCell(resistance, adj[, 1]),
+                 terra::xyFromCell(resistance, adj[, 2]))
>
> dist <- terra::distance(coords[, 1:2],
+                         coords[, 3:4],
+                         lonlat = terra::is.lonlat(resistance),
+                         pairwise = TRUE)
>
>
>
==100==
==100== HEAP SUMMARY:
==100==     in use at exit: 115,884,361 bytes in 265,013 blocks
==100==   total heap usage: 1,440,364 allocs, 1,175,351 frees, 379,176,075 bytes allocated
==100==
==100== LEAK SUMMARY:
==100==    definitely lost: 0 bytes in 0 blocks
==100==    indirectly lost: 0 bytes in 0 blocks
==100==      possibly lost: 0 bytes in 0 blocks
==100==    still reachable: 115,884,361 bytes in 265,013 blocks
==100==                       of which reachable via heuristic:
==100==                         newarray           : 4,264 bytes in 1 blocks
==100==                         multipleinheritance: 480 bytes in 4 blocks
==100==         suppressed: 0 bytes in 0 blocks
==100== Reachable blocks (those to which a pointer was found) are not shown.
==100== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==100==
==100== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

This confirms that there is no memory leak. What you see is that memory has been freed but that garbage has not been collected. If you run `gc()` after `terra::distance` the monitor should show you that all RAM is back (except for what is now occupied by `dist`).

The better news is that you made me look at that method and I was able to reduce its memory footprint and speed it up considerably (~ 50x for your data). So thanks for making me look!
