### ISSUE TITLE
rast() Error in x$.self$finalize() : attempt to apply non-function

### ISSUE THREAD

**Issue by andrewmarx** [rspatial/terra#837]
Sometimes when creating SpatRaster objects from large matrices I'm getting the error _Error in x$.self$finalize() : attempt to apply non-function_. It doesn't actually seem to cause the function to fail, and it only occurs once until I restart the R session. Same behavior with the plot() function. It'll report the same error, but appears to work otherwise, and subsequent runs don't report the error until a session restart. Reducing the size of `n` causes the issue to go away.

Tested using a fresh source install of terra at the time of posting. R version 4.2.1. Linux Mint Cinnamon 20.1 (which is based on Ubuntu 20.04)

```
> n = 2000
> res_data <- matrix(runif(n^2)*10 + 1, nrow = n)
> resistance = terra::rast(res_data, extent = terra::ext(0.5, n + 0.5, 0.5, n + 0.5), crs = "local")
Error in x$.self$finalize() : attempt to apply non-function
> terra::plot(resistance)
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
```

**Comment by Nowosad** [comment]
@andrewmarx see https://github.com/rspatial/terra/issues/30

**Comment by rhijmans** [comment]
These messages are sometimes emitted when an object is destroyed. There are very annoying. Thankfully, Kevin Ushey has made a change in Rcpp that makes this go away. We will just have to wait for the next version of Rcpp to come out, which is expected to happen in January 2023.  Or you can install the development version of Rcpp:

```
install.packages("Rcpp", repos="https://rcppcore.github.io/drat")
```

**Comment by Nowosad** [comment]
The new Rcpp version is now on CRAN: https://cran.r-project.org/package=Rcpp

**Comment by rhijmans** [comment]
Hooray!
