### ISSUE TITLE
why abs() returns 0 but plot is OK

### ISSUE THREAD

**Issue by tigerwang1998** [rspatial/terra#838]
```
library(terra)
a <- rast(nrows=3,
          ncols=3,
          nlyrs=3,
          vals=runif(27,min=-1,max=0))
b <- abs(a)
plot(a)
plot(b)
b[1,1]
```

![Rplot](https://user-images.githubusercontent.com/50581765/194772729-7da5dbe3-fc60-4db5-bbdb-e729e8ce9dfb.png)
![Rplot01](https://user-images.githubusercontent.com/50581765/194772734-544b3f86-51b7-4d33-8e62-9a6eb8413c2a.png)
![cdf9ad3a79953f00e89f6f38135a8e2](https://user-images.githubusercontent.com/50581765/194772743-37f2059f-ead9-49cd-aed9-18aef1b5bcfe.jpg)

**Comment by rhijmans** [comment]
Thanks very much for reporting this. When using `abs` the values were incorrectly returned as integers.
