### ISSUE TITLE
Error with runif when creating spatraster

### ISSUE THREAD

**Issue by tigerwang1998** [rspatial/terra#840]
It seems like similar with issuse #838.

```
library(terra)
r <- rast(nrows=2,ncols=2,vals=runif(4))
plot(r)
```
![image](https://user-images.githubusercontent.com/50581765/194816507-abbfbcbf-3b93-40d9-b2a1-2e86f5c7f56c.png)

But `r <- rast(nrows=2,ncols=2,vals=sample(4))` is OK

**Comment by kadyb** [comment]
BTW: If you don't want the decimal data to show as categories in this case, you can change the scale to continuous.

```r
plot(r, type = "continuous")
```

**Comment by tigerwang1998** [comment]
> BTW: If you don't want the decimal data to show as categories in this case, you can change the scale to continuous.
> 
> ```r
> plot(r, type = "continuous")
> ```

You reminded me! Is it possible to omit the number after the decimal point?

**Comment by kadyb** [comment]
You can use `trunc()` or `signif()`.

```r
v <- runif(4) * 10
r <- rast(nrows = 2, ncols = 2, vals = v)
vv <- trunc(v)
plot(r, plg = list(legend = vv))
```

**Comment by rhijmans** [comment]
The classes legend round all numbers to integers. They are now rounded to a number of decimals depending on the data. Perhaps another improvement would be to add an option to set the number of decimals desired in the legend (whether classes, range, or continuous)
