### ISSUE TITLE
Extend the update function?

### ISSUE THREAD

**Issue by JimShady** [rspatial/terra#845]
Hi Robert,

Thanks for the new update function in 1.6-28 for updating layer names.

It made me wonder whether other attributes could take advantage of this?  For example making the extent of a raster larger (filling the new cells with NA). Though maybe this is something that *has* to be read in, then write out?

Thanks.

**Comment by rhijmans** [comment]
I have added the option to update the 'crs' and 'extent', but I do not think I can do what you are after.

**Comment by JimShady** [comment]
Cheers!
