### ISSUE TITLE
rasterize fills background with `NaN` instead of `NA`

### ISSUE THREAD

**Issue by johnbaums** [rspatial/terra#849]
`terra::rasterize()` assigns `NaN` to cells with no overlapping features when `background=NA`.  However, the expected behaviour is observed when some other value is used for `background`.

I've noticed the use of NaN elsewhere in terra (e.g. the value used to fill `terra::rast()`) so there's probably some design motivation for using this value as a default.

However, this can cause problems when functions are applied that treat NaN differently to NA, such as in the `INDEX` of `tapply`:

```r
tapply(X=1:3, INDEX=c(NA, NaN, 1), FUN=sum)
#>  1 NaN 
#>  3   2 
```

``` r
library(terra)
#> terra 1.6.32
v <- vect(system.file("ex/lux.shp", package="terra"))
r <- rast(v, ncols=75, nrows=100)

z <- rasterize(v, r, "ID_2", background=NA)
z[1]
#>   ID_2
#> 1  NaN

## Works as expected with `background=123`
z2 <- rasterize(v, r, "ID_2", background=123)
z2[1]
#>   ID_2
#> 1  123
```

<sup>Created on 2022-10-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23)
#>  os       macOS Big Sur ... 10.16
#>  system   x86_64, darwin17.0
#>  ui       X11
#>  language (EN)
#>  collate  en_AU.UTF-8
#>  ctype    en_AU.UTF-8
#>  tz       Australia/Melbourne
#>  date     2022-10-17
#>  pandoc   2.18 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.4.0   2022-09-08 [1] CRAN (R 4.2.0)
#>  codetools     0.2-18  2020-11-04 [1] CRAN (R 4.2.1)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.2.0)
#>  evaluate      0.16    2022-08-09 [1] CRAN (R 4.2.0)
#>  fansi         1.0.3   2022-03-24 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.0)
#>  knitr         1.40    2022-08-24 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.2   2022-09-09 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
#>  pillar        1.8.1   2022-08-19 [1] CRAN (R 4.2.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.0  2022-06-28 [1] CRAN (R 4.2.0)
#>  Rcpp          1.0.9   2022-07-08 [1] CRAN (R 4.2.0)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.0)
#>  rlang         1.0.5   2022-08-31 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.16    2022-08-24 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.0)
#>  stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.0)
#>  styler        1.7.0   2022-03-13 [1] CRAN (R 4.2.0)
#>  terra       * 1.6-32  2022-10-17 [1] Github (rspatial/terra@6fe9f8d)
#>  tibble        3.1.8   2022-07-22 [1] CRAN (R 4.2.0)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.0)
#>  vctrs         0.4.1   2022-04-13 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.33    2022-09-12 [1] CRAN (R 4.2.0)
#>  yaml          2.3.5   2022-02-21 [1] CRAN (R 4.2.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by rhijmans** [comment]
That is correct, terra uses `NaN` for missing values. This is because that is a numeric (floating point) value in C++. The R `NA` is a more complex construct. It would be possible to change NaN to NA when returning values in R. I have not done that because it seemed costly for something that hardly ever makes a difference.  I have not seen a very compelling case. I should admit that I have not analyzed the cost of doing so either. Perhaps it is not that bad; and `NA` would be better in R, just for consistency.

**Comment by johnbaums** [comment]
You're probably right that it rarely makes a difference - it only arose because I migrated some code from raster to terra, which used tapply to sum values of a human population raster for unique values of a [subset of a] zone raster that included NA (now NaN) values. 

```r
tapply(pop[cells][[1]], zones[cells][[1]], sum)
```

I see now that stats::aggregate ignores NaN in the grouping elements, so I'll see how that goes.

If using NaN is more performant and more natural for use in C++, then it would probably be logical to keep it as is.

Thanks!

**Comment by rhijmans** [comment]
You could use `terra::zonal` for that? 

I made a change such that NaN is replaced with NA if you do `as.data.frame` 

```
library(terra)
r = rast(ncol=2, nrow=2, nlyr=3, names=letters[1:3])
values(r) = (1:size(r)) / 2
r[1] = NA
x <- writeRaster(r, "test.tif", overwrite=TRUE)

values(x)
values(x)
#       a   b   c
#[1,] NaN NaN NaN
#[2,] 1.0 3.0 5.0
#[3,] 1.5 3.5 5.5
#[4,] 2.0 4.0 6.0
 
values(x, dataframe=TRUE)
#    a   b   c
#1  NA  NA  NA
#2 1.0 3.0 5.0
#3 1.5 3.5 5.5
#4 2.0 4.0 6.0
 
as.data.frame(x, na.rm=F)
#    a   b   c
#1  NA  NA  NA
#2 1.0 3.0 5.0
#3 1.5 3.5 5.5
#4 2.0 4.0 6.0
```

That makes sense to me because `as.data.frame` also takes care of factor and integer values, whereas `values(x)` returns raw values. That should propagate to `extract` as well.

**Comment by johnbaums** [comment]
Thanks, that looks good.

I'd considered `zonal`, but I only wanted to aggregate (within zones) a subset of raster cells. I guess to get zonal to work I would first need to mask the zone raster to that subset, to exclude the cells I'm not interest in.
