### ISSUE TITLE
plotRGB():  main argument does not work

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#85]
I miss the title here:
```
b <- rast(system.file("ex/logo.tif", package="terra"))   
plotRGB(b,main="IMAGE")
```

as in :
`plot(b[[1]],main="IMAGE")
`

**Comment by rhijmans** [comment]
Thanks, this works now.

**Comment by aloboa** [comment]
Thanks, I confirm it works with v. 0.9.5

**Comment by Rapsodia86** [comment]
Main and axes do not work again. 
I have a dev version: terra 1.5.14 
b <- rast(system.file("ex/logo.tif", package="terra"))   
plotRGB(b,main="IMAGE",axes=TRUE)
and it plots me RGB but no title and no axes.
