### ISSUE TITLE
Problem when changing the centering of a raster from Pacific centered to prime meridian centered

### ISSUE THREAD

**Issue by MiikkaT** [rspatial/terra#850]
Hi,

This might be just an user-side error, but anyway: I came across the following weird problem when trying to change the projection of a global raster that was originally Pacific centered to be centered on the prime meridian. The  problem is that the resulting raster has a huge round hole in the center. The weird thing is that when I do this in my laptop that has an older version version of terra package (1.6-7) everything goes fine, whereas with the current version of terra in my desktop, the problem appears. However, I’m not sure if this truly is a problem in terra or is there something else going on. (In both cases `rotate`, which I assume to be the prime solution, does not really work, as most of Europe and Africa will be cut out). 
Where is this problem coming from and is there a way to fix it on all setups?
Below you will find session info for both unsuccessful and successful attempts as well as the code for reproducing (or not) the problem.

Best wishes,
Miikka 

Setup with problematic result:
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] geodata_0.4-11 terra_1.6-17  

Setup without problems:
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] geodata_0.4-6 terra_1.6-7  

The code for reproducing the problem:
```

library(terra)
library(geodata)

## Global raster for a template
bioclims <- worldclim_global(var="bio", res=10, path=tempdir())
bio1 <- bioclims[[1]]

## template and mask raster
maskR <- bio1

## Our focal raster, which is Pacific-centered.
## Extracting data on diversity of marine mammals with small ranges
## from BiodiversityMapping.org
URL <- "https://datadryad.org/stash/downloads/file_stream/71542"
wd <- getwd()
td <- tempdir()
setwd(td)
temp <- tempfile(fileext = ".zip")
download.file(URL, temp, mode='wb', cacheOK=FALSE)
unzip(temp)
mardiv_small <- rast("./GeoTIFFs_dryad/FigA2_marine_mammals.tif")
unlink(dir(td))
setwd(wd)

## plotting the original Pacific-centered raster
plot(mardiv_small)

## Change of projection
mardiv_small2 <- project(mardiv_small, maskR)
plot(mardiv_small2)

## Some fine-tuning
## Mask the mammaldiversity using the mask raster
maskR[!is.na(maskR)] <- 1
mardiv_smallR <- mask(mardiv_small2, maskR, maskvalues=1)

## Plotting the re-centered and -projected raster
plot(mardiv_smallR)
```
Raster with a hole
![raster_with_hole](https://user-images.githubusercontent.com/10044772/196433418-2225a74e-626c-4b94-9a11-515e751fb2ac.png)

Raster without hole
![raster_without_hole](https://user-images.githubusercontent.com/10044772/196433429-2724facb-fbb1-4287-b7e2-1902a7c5de72.png)

**Comment by rhijmans** [comment]
It appears that this is a bug in older versions of PROJ (or GDAL). 

```
library(terra)
#terra 1.6.17

f <- file.path(tempdir(), "FigA2_marine_mammals.tif")
if (!file.exists(f)) {
	URL <- "https://datadryad.org/stash/downloads/file_stream/71542"
	temp <- tempfile(fileext = ".zip")
	download.file(URL, temp, mode='wb', cacheOK=FALSE)
	unzip(temp, junkpaths=TRUE, exdir=tempdir())
}

m <- rast(f)
r <- rast(res=1/6)
mp <- project(m, r)
plot(mp)
```

![mam](https://user-images.githubusercontent.com/11481397/196522120-05e852b4-d54a-425b-ab45-dc5de601ce0c.png)

This works on Ubuntu and Windows with the CRAN version of terra (1.6.17) and with the development version (1.6.31) and the following versions of the GDAL and PROJ libraries 

```
gdal(lib="")
#   gdal    proj    geos 
#"3.4.3" "7.2.1" "3.9.1" 
#"3.4.0"  "8.2.0" "3.10.1"
#"3.5.2" "8.2.1" "3.9.3" 
```

But I have an Ubuntu with older GDAL/PROJ and there I see

```
> library(terra)
terra 1.6.31

gdal(lib="")
#   gdal    proj    geos
#"2.2.3" "4.9.3" "3.6.2"

plot(mp)
```

![test2](https://user-images.githubusercontent.com/11481397/196523562-123c5cc1-d583-401e-b984-fd96c360763f.png)

This suggests that you have older GDAL/PROJ versions on the computer with Ubuntu 20.04; and that this problem goes away if you update the libraries to a more recent version and reinstall terra.

**Comment by rhijmans** [comment]
Two more things while we are here:

`rotate` seems to "work"

![rotate](https://user-images.githubusercontent.com/11481397/196525776-8fdcf881-c8d8-49bb-babf-6160673e7bba.png)

But it is really only meaningful with lon/lat data, in which case you have an arbitrary rotation of the globe. That is not the case for other CRSs.

And instead of 

```
maskR[!is.na(maskR)] <- 1
mardiv_smallR <- mask(mardiv_small2, maskR, maskvalues=1)
```

You can do (with the unaltered `maskR`)

```
mardiv_smallR <- mask(mardiv_small2, maskR, inverse=TRUE)
```

**Comment by MiikkaT** [comment]
Thanks for the solution! I'll investigate GDAL/PROJ versions as soon as I get to my desktop. And thanks for the mask tip as well!
