### ISSUE TITLE
Unexpected behaviour in R Notebook

### ISSUE THREAD

**Issue by aloboa** [rspatial/terra#853]
In this little R Notebook:

```
---
title: "R Notebook"
output: html_notebook
---

```{r}
require(terra)
b <- rast(system.file("ex/logo.tif", package="terra"))   
v <- as.polygons(b)
plotRGB(b)
plot(v, add=TRUE)
```
```
```
If I run the code line by line within the notebook, I get

```
Show in New Window
 Error in graphics::plot.xy(g, type = "l", lty = lty, col = col, lwd = lwd, : 
plot.new has not been called yet
```

but runs ok if I run the whole chunk with the "Run Current Chunk" button.
Not sure if this is to be expected, I was confused for a while looking for an error in my code.

**Comment by kadyb** [comment]
This is not problem with `{terra}`, but with RStudio / RMarkdown.

```r
```{r}
# run line by line
plot(0, 0)
abline(0, 1)
#> Error in int_abline(a = a, b = b, h = h, v = v, untf = untf, ...) : 
#>   plot.new has not been called yet
```

To fix this, you can add to the YAML header:

```
editor_options: 
  chunk_output_type: inline
```

Or write the code in this way: 

```r
plot(0, 0); abline(0, 1)
```

**Comment by aloboa** [comment]
Clarified, thanks
