### ISSUE TITLE
distance function seems much slower than gdal proximity

### ISSUE THREAD

**Issue by cyrilmory** [rspatial/terra#854]
I'm trying to use the distance function to compute the distance from anywhere on an island to the shoreline, and it seems much slower than the gdal implementation. On my computer, it took 509s to compute the raster of distances from most pixels to shoreline pixels on a 360x360 spatRaster, while I have done this with QGIS using gdal_proximity and got the result in a matter of seconds. Are there differences that explain this (e.g. higher accurary in Terra, I don't know) ? Can you think of a way to speed it up ? I can spare some time to help, since I do need that tool and I'm unwilling to write files and use rgdal everytime.

**Comment by brownag** [comment]
Which version of {terra} are you using? 

The development version should have some [improvements](https://github.com/rspatial/terra/issues/836#issuecomment-1272386178) to `distance()` that may affect your results compared to the version on CRAN.

**Comment by cyrilmory** [comment]
Switching to the development version did bring a 20x improvement, thanks a lot for that. Yet I think it still isn't fast enough for what I need to do. Does the current implementation use some kind of hierarchical tree ? If not, would you be interested in trying to make it hierarchical ? I think it is feasible, and could draft some pseudo-code, as a start (and then I could also help with the C++ implementation/modification if you want).

**Comment by rhijmans** [comment]
Thank you for your offer to help. The dev version of `distance<SpatRaster>` should be much faster than before for planar data (simple Euclidean distances). I assume that is what you are using? If so, can you provide a simple bench-mark test case? I am asking, because I see, with a raster of similar dimensions:

```
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
x <- project(r, "EPSG:2169")
x <- disagg(x, 4)
dim(x)
system.time(d <- distance(x))
#   user  system elapsed 
#   0.02    0.00    0.02 
```

That would be 25,000 times faster than what you report 

Or are you using lon/lat data? That is also faster than before, but still under development.

**Comment by cyrilmory** [comment]
Test done : it is much faster indeed with a projected CRS. Thanks !
