### ISSUE TITLE
ext() method for sf bbox objects

### ISSUE THREAD

**Issue by GreatEmerald** [rspatial/terra#858]
There is currently no method in `ext()` to handle objects of type `bbox` from the `sf` package. It can be worked around with something like this:
```r
ext(bbox$xmin, bbox$xmax, bbox$ymin, bbox$ymax)
```
...but it does not carry over the CRS of the `bbox`, and is error-prone (because the order of the coordinates is different in the `bbox` object). It would be nice to have a native method in `terra::ext()` to convert these objects, like there is for raster `extent` objects. Also note that the reverse operation from `SpatExtent` to `bbox` is already available in `st_bbox()`.

**Comment by kadyb** [comment]
As workaround, you can also convert `bbox` to `sfc` and then to `vect` (but this way is verbose).

```r
library("sf")
library("terra")
nc = read_sf(system.file("shape/nc.shp", package = "sf"))
vect(st_as_sfc(st_bbox(nc)))
```

**Comment by rhijmans** [comment]
I think there is such as method, as I see (with the development version of terra)

```
library("sf")
#Linking to GEOS 3.9.1, GDAL 3.4.3, PROJ 7.2.1; sf_use_s2() is TRUE
library("terra")
#terra 1.6.33
nc = read_sf(system.file("shape/nc.shp", package = "sf"))

ext(nc)
#SpatExtent : -84.3238525390625, -75.4569778442383, 33.8819923400879, 36.5896492004395 (xmin, xmax, ymin, ymax)

ext(st_bbox(nc))
#SpatExtent : -84.3238525390625, -75.4569778442383, 33.8819923400879, 36.5896492004395 (xmin, xmax, ymin, ymax)
``` 

A SpatExtent does not have a CRS (but see @kadyb's suggestion)
