### ISSUE TITLE
Analogous to raster::addLayer

### ISSUE THREAD

**Issue by lbusett** [rspatial/terra#86]
Hi, 

  while trying to convert a project from `raster` to `terra` usage, I stumbled on the fact that it is apparently not possible to "grow" a terra spatrast by adding layers. I used to do: 

```
  stack <- raster::stack(rast, band)
```

but this fails: 
```
  stack <- terra:rast(rast, band)
```

also, there not seem to exist a `addLayer` function similar to what available in raster. 

Am I missing something' is it possible in any way to add a layer to an existing spatRast object ? 

   thanks in advance, 

Lorenzo

**Comment by rhijmans** [comment]
Hi Lorenzo, 
You can use the `c` method to do that, as in `x <- c(x, r)` 
Thanks for trying to convert and please let me know if there are more obstacles on the way. 
Robert

**Comment by lbusett** [comment]
Thanks for the answer. While testing, however, I noticed that the `c` approach in `terra` appears much slower and apparently leaks memory. The code below is very fast on `raster` but slows down strongly in `terra` after a few layers are added, and leads to very large memory occupation: 

``` r
# on `raster`
r <- raster(ncol = 1200, nrow = 1200)
r <- raster::setValues(r, runif(1200*1200))
s <- stack(r)

for (i in 1:100) {
    print(i)
    s <- stack(s, r)
}

# on `terra`
r1 <- terra::rast(ncol = 1200, nrow = 1200)
r1 <- terra::setValues(r1, runif(1200*1200))
s <- r1
for (i in 1:100) {
    print(i)
    s <- c(s, r1)
}
```

Apparently, the `c` approach on `terra` seems to be trying to create a very large raster all in memory, which does not seem to appen with the `raster` approach. 

 Am I doing something wrong, here? 

  HTH, 

Lorenzo

**Comment by lbusett** [comment]
Hi @rhijmans 

  was wondering if you noticed this update and were able to have a look if you see the same behaviour. 
Interested because this is currently stopping my "conversion attempt" towards `terra`. 

  thanks in advance, 

Lorenzo

**Comment by rhijmans** [comment]
I had already changed to the code to make `c` perform better, but forgot to let you know. I have now also added two new methods, `add` and `collapse`

library(raster)
library(terra)
r <- raster(ncol = 1200, nrow = 1200, vals=(1:(1200*1200)))
s <- stack(r)
ss <- rr <- rast(r)
 
#system.time(for (i in 1:50) s <- stack(s, r))
#   user  system elapsed 
#   1.42    0.00    1.42 

#system.time(for (i in 1:50) ss <- c(ss, rr))
#   user  system elapsed 
#   4.28    2.61    6.89 
 
That is not as bad anymore. But it is faster like this, using `add`:

```
x <- rast(r)
system.time(for (i in 1:50) add(x) <- rr)
#   user  system elapsed 
#   0.61    0.17    0.79 
```

Perhaps followed by (to collapse all memory sources into one, which could make processing faster --- although it would happen anyway when the data gets processed)

```
system.time(y <- collapse(x))
#   user  system elapsed 
#   0.42    0.36    0.78 
```

**Comment by lbusett** [comment]
Thanks! I'll have a look soon by installing from github.

**Comment by lbusett** [comment]
@rhijmans 

this is now much better, thanks. However: 

  1) I noticed that `add` still takes up more memory than `stack` on raster. On your example, I notice I spike of about half a GB on `terra`, while on `raster` memory occupation doesn't practically change;
  2) On issuing `collapse` there is a even larger memory spike (~1GB), and often I get a `Error in x@ptr$collapse_sources() : std::bad_alloc` error

(Working on Win10, R4.02)

HTH. 

Lorenzo

**Comment by MatthieuStigler** [comment]
Looks like from version 1.2-5, `collapse` became `tighten`? What about `add`? Thanks!

**Comment by kadyb** [comment]
Looks like `add` is unchanged: https://rspatial.github.io/terra/reference/add.html (v. 1.5-23).

**Comment by rhijmans** [comment]
And it may be most efficient to make a list `x`, and then, when you have all layers, use `rast(x)`

**Comment by MatthieuStigler** [comment]
I am confused, looking at version `1.5.22`, it seems it is not there? Was it re-introduced in `1.5.23`?

``` r
library(terra)
#> terra 1.5.22
packageVersion("terra")
#> [1] '1.5.22'
terra::add
#> Error: 'add' is not an exported object from 'namespace:terra'
```

**Comment by MatthieuStigler** [comment]
Ok, I guess it's more of a documentation issue, the function works, even if one can't access it/its help! 

``` r
library(terra)
#> terra 1.5.21
packageVersion("terra")
#> [1] '1.5.21'

r <- rast(nrows=5, ncols=9, vals=1:45)
x <- c(r, r*2)
add(x) <- r*3
x
#> class       : SpatRaster 
#> dimensions  : 5, 9, 3  (nrow, ncol, nlyr)
#> resolution  : 40, 36  (x, y)
#> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 
#> sources     : memory  
#>               memory  
#>               memory  
#> names       : lyr.1, lyr.1, lyr.1 
#> min values  :     1,     2,     3 
#> max values  :    45,    90,   135
add
#> Error in eval(expr, envir, enclos): object 'add' not found
```

<sup>Created on 2022-03-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kadyb** [comment]
You should access the documentation like this:

```r
?`add<-`
```

**Comment by lucas-johnson** [comment]
After reading this thread I'm still a bit confused on the most memory efficient way to make a raster stack. 

Is it something like: 
```r
x <- lapply(list.files('<path_to_my_dir>', full.names = TRUE, pattern = '*.tiff'), terra::rast)
stack <- terra::rast(x)
```

Our should I be looking to `c`, `add()`, or `collapse()`/`tighten()`?

Thank you!

**Comment by rhijmans** [comment]
@lucas-johnson: in your case you can make a SpatRaster in a single step, and that is what should be most efficient:

```
ff <- list.files('<path_to_my_dir>', full.names = TRUE, pattern = '*.tiff')
x <- terra::rast(ff)
```
