### ISSUE TITLE
increase limits to histograms in hist.r

### ISSUE THREAD

**Issue by GeraldCNelson** [rspatial/terra#860]
The current version of hist creates histograms and return values for the first 16 layers. Could this be relaxed? A couple of options would be to make the layer option take multiple values and if nothing specified do just the first layer. Another would be to do all layers if plot = FALSE. 

Somewhat related to this, it seems that the name variable in the output is always (maybe) v. Could this be changed so it uses the name of the layer as main does?

**Comment by rhijmans** [comment]
You got it:

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
a = hist(s, maxnl=1)
#Warning message:
#[hist only the first 1 layers are used (see argument maxnl)]  
str(a)
#List of 1
# $ :List of 6
#  ..$ breaks  : num [1:14] 0 20 40 60 80 100 120 140 160 180 ...
#  ..$ counts  : int [1:13] 240 212 209 220 366 423 647 729 515 414 ...
#  ..$ density : num [1:13] 0.00154 0.00136 0.00134 0.00141 0.00235 ...
#  ..$ mids    : num [1:13] 10 30 50 70 90 110 130 150 170 190 ...
#  ..$ xname   : chr "red"
#  ..$ equidist: logi TRUE
#  ..- attr(*, "class")= chr "histogram"
```

**Comment by GeraldCNelson** [comment]
Thanks!

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

From: Robert Hijmans ***@***.***>
Reply-To: rspatial/terra ***@***.***>
Date: Thursday, October 27, 2022 at 1:33 PM
To: rspatial/terra ***@***.***>
Cc: Gerald Nelson ***@***.***>, Author ***@***.***>
Subject: Re: [rspatial/terra] increase limits to histograms in hist.r (Issue #860)


You got it:

library(terra)

s <- rast(system.file("ex/logo.tif", package="terra"))

a = hist(s, maxnl=1)

#Warning message:

#[hist only the first 1 layers are used (see argument maxnl)]

str(a)

#List of 1

# $ :List of 6

#  ..$ breaks  : num [1:14] 0 20 40 60 80 100 120 140 160 180 ...

#  ..$ counts  : int [1:13] 240 212 209 220 366 423 647 729 515 414 ...

#  ..$ density : num [1:13] 0.00154 0.00136 0.00134 0.00141 0.00235 ...

#  ..$ mids    : num [1:13] 10 30 50 70 90 110 130 150 170 190 ...

#  ..$ xname   : chr "red"

#  ..$ equidist: logi TRUE

#  ..- attr(*, "class")= chr "histogram"
