### ISSUE TITLE
`terra::subst()` using data.frame?

### ISSUE THREAD

**Issue by oharac** [rspatial/terra#862]
I am a big fan of `terra`, but I miss a feature from `raster`:  `raster::subs()` allowed substitution of values in a raster based on a data.frame, which was convenient for large substitution sets (e.g., cell IDs translated to cell values in a dataframe).  

I can basically do the same with `terra::subst()`, accessing columns in the dataframe using the `$` operator, but missing values are neither replaced nor dropped as they are by default with `raster::subs()`, and there doesn't seem to be an option to do so.  

Would it be possible to add data.frame functionality to subst(), or perhaps an argument like `subsWithNA=TRUE` as in `raster::subs()`?  thanks!

``` r
library(raster)
#> Loading required package: sp
library(terra)
#> terra 1.5.21

### replacement df, x = id, y = value, some NAs introduced
repl_df <- data.frame(x = 1:100, y = log(1:100))
repl_df <- repl_df[sample(1:100, size = 80), ]

### raster version using subs() drops NA cells by default
r1 <- raster(nrows = 10, ncols = 10, vals = 1:100)
r2 <- raster::subs(r1, repl_df, by = 'x', which = 'y')

plot(r2)
```

![](https://i.imgur.com/QHhRWHa.png)

``` r

### terra version using subst() does not seem to have an
### option to drop missing values.
t1 <- rast(nrows = 10, ncols = 10, vals = 1:100)
t2 <- terra::subst(t1, from = repl_df$x, to = repl_df$y)
plot(t2)
```

![](https://i.imgur.com/tFFkJAO.png)

<sup>Created on 2022-10-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
That option (`others=NA`) already exists in the development version 

You can do 

```
library(terra)
t1 <- rast(nrows = 10, ncols = 10, vals = 1:100)
repl_df <- data.frame(x = 1:100, y = log(1:100))
set.seed(1)
repl_df <- repl_df[sample(1:100, size = 80), ]
t2 <- terra::subst(t1, from = repl_df$x, to = repl_df$y, others=NA)
plot(t2)
```

**Comment by oharac** [comment]
Perfect, thanks!  I should have thought to see if there was a development version available...
