### ISSUE TITLE
Merging changes layer datatypes

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/terra#866]
```
> r1 = terra::rast(nrows = 2, ncols = 2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
> r1$v = 1L
Warning: [rast] the first raster was empty and ignored

> str(r1$v[1])
'data.frame':   1 obs. of  1 variable:
 $ v: int 1
> r2 = terra::rast(nrows = 2, ncols = 2, xmin = 1, xmax = 2, ymin = 0, ymax = 1)
> r2$v = 2L
Warning: [rast] the first raster was empty and ignored

> str(r2$v[1])
'data.frame':   1 obs. of  1 variable:
 $ v: int 2
> r3 = terra::merge(r1, r2)
> str(r3$v[1])
'data.frame':   1 obs. of  1 variable:
 $ v: num 1
```

This might be intentional, on the philosophy that a `merge` may have to create new cells (if the aggregate of the inputs isn't a rectangle), `NaN` should be used for those cell values, and there is no integer `NaN`. But I think that `NA` should be used in such cases instead.

**Comment by rhijmans** [comment]
Thank you, I now get 

```
library(terra)
r1 = rast(nrows = 2, ncols = 2, xmin = 0, xmax = 1, ymin = 0, ymax = 1)
r1$v = 1L
r2 = rast(nrows = 2, ncols = 2, xmin = 1, xmax = 2, ymin = 0, ymax = 1)
r2$v = 2L
r3 = merge(r1, r2)
is.int(r3)
#[1] TRUE
```

The default behavior of all methods is the return (floating point) numerics. I have been adding tests for cases where e.g. integers could be kept, such as with `crop`. Now `merge` will also keep the input datatype if all input layers have the same data type.
