### ISSUE TITLE
gridDistance

### ISSUE THREAD

**Issue by babaknaimi** [rspatial/terra#867]
Hi there!

In the terra package (1.6-17), the outcome of gridDistance is not consistent with the equivalent function in the raster package for a layer with geographic crs. It seems that the calculated distance should be doubled to have a correct measure:

r <- rast(ncol=10,nrow=10, vals=1)
r[48] <- 0
r[66:68] <- NA
d <- terra::gridDistance(r,target=0,scale=1000) 
plot(d)
text(d)
#---------
r2 <- raster(ncol=10,nrow=10, vals=1)
r2[48] <- 0
r2[66:68] <- NA
d2 <- raster::gridDistance(r2,0) / 1000
plot(d2)
text(d2)

Any idea?

Cheers,
Babak

**Comment by rhijmans** [comment]
Hi Babak, 
Thank you very much for catching that. I now get 

```
library(terra)
r1 <- rast(ncol=10,nrow=10, vals=1)
r1[48] <- 0
r1[66:68] <- NA
d1 <- gridDist(r1,target=0, scale=1000)

library(raster)
r2 <- raster(r1)
d2 <- rast(gridDistance(r2,0, omit=NA)/ 1000)

plot(d1, d2)
abline(0,1)
```

![dist](https://user-images.githubusercontent.com/11481397/199122135-26035d10-909f-4e2a-93b1-84f415943b64.png)


The minor variation is because terra::gridDist better accounts for connections at the poles.
