### ISSUE TITLE
CRS in vect()

### ISSUE THREAD

**Issue by MatMatt** [rspatial/terra#87]
Hi,
While CRS is assigned to rast() it is not assigned to vect(), but maybe it should?

```S
library(terra)
#terra version 0.8.6 (beta-release)
x <- rast()
x
isLonLat(x)
x <- vect()
x
isLonLat(x)
```

**Comment by rhijmans** [comment]
Done as suggested. I am not sure how useful this is --- right now there is not much you can do with an empty `SpatVector`, but that may change in the future.
