### ISSUE TITLE
reduction in memory allowed

### ISSUE THREAD

**Issue by sm2607** [rspatial/terra#871]
I have noticed there is significant decrease in memory available and memory allowed after each raster process. There are almost 32 Gb ram available , still its showing memory available 0.5 Gb and Memory allowed 0.3 Gb, in earlier step it was 18 and 12 respectively. is there any way to increase this or prevent it to decrease after each step ? I tried gc(), after each step still no improvement

```
driver        : GTiff
disk available: 72.7 GB
disk needed   : 8 GB
memory avail. : 0.5 GB
memory allow. : 0.3 GB
memory needed : 32.009 GB  (2 copies)
in memory     : false
block size    : 2316 rows
n blocks      : 29
pb            : 1
```

**Comment by rhijmans** [comment]
Did you create large in-memory rasters, thus reducing the memory available?

**Comment by sm2607** [comment]
actually to prevent large raster  to write in-memory, I have kept the `terraOption(todisk=T)` 

I also got another issue with function `trim()` , I have 2 raster one is very large but with lots of NA, I used `trim()` and its reduced the raster and increased the raster processing, thanks for this wonderful function. But another raster which does not have 'NA' , its got hanged.
 I wrote a code in such a way that firstly it will trim raster and then apply other processing because I am automating a process and will not be aware that which raster will have NA values or no

**Comment by rhijmans** [comment]
I would not recommend setting `terraOption(todisk=T)`. There generally should be no need for it. 
As for `trim` --- that is a different topic, but there is not much I can do without a reproducible example that shows the problem, or something very close to that. If you can provide such an example, please start a new issue.
