### ISSUE TITLE
Can't merge SpatExtent objects

### ISSUE THREAD

**Issue by see24** [rspatial/terra#874]
When I try to merge to SpatExtents I get this error message 

> Error in as.data.frame.default(x) : 
>   cannot coerce class ‘structure("SpatExtent", package = "terra")’ to a data.frame

The docs for `terra::merge` say that you should be able to merge extents and it worked in `raster::merge`

```r
library(terra)

x <- rast(xmin=-110, xmax=-80, ymin=40, ymax=70, res=1, vals=1)
y <- rast(xmin=-85, xmax=-55, ymax=60, ymin=30, res=1, vals=2)

terra::merge(ext(x), ext(y))
```

**Comment by rhijmans** [comment]
Thanks. That is a documentation error (fixed with https://github.com/rspatial/terra/commit/c3957ae176d11dd373257d87422e86b169b64530). 
You can use `union` instead 

```
union(ext(x), ext(y))
#SpatExtent : -110, -55, 30, 70 (xmin, xmax, ymin, ymax)
```
