### ISSUE TITLE
Warning message when setting crs

### ISSUE THREAD

**Issue by mjwestgate** [rspatial/terra#875]
Hi! I'm working on the EcoCommons project, we've been getting the following warning from GDAL via `terra`:
```
Warning message:
In x@ptr$set_crs(value) :
  GDAL Message 1: +init=epsg:XXXX syntax is deprecated. It might return a CRS with a non-EPSG compliant axis order.
```
The warning seems to be generated from one of 4 places in `crs.R`, the first of which is [here](https://github.com/rspatial/terra/blob/05ecc1544f04f0c0fdf77fabbe4a58898e3ba469/R/crs.R#L156). This isn't preventing any code from running, so it isn't urgent; but I thought it was best to pass this on in case others had seen it, or in case GDAL decide to convert this from a warning to an error in future.

**Comment by rhijmans** [comment]
Can you please provide an example that produces this error, and tell me what `gdal(lib="all")` returns, and what OS you are using?

**Comment by rhijmans** [comment]
From the error message, it would seem that the problem would go away if instead of 

```
crs(x) <- "+init=epsg:XXXX"
```

you would use 

```
crs(x) <- "EPSG:XXXX"
```

**Comment by rhijmans** [comment]
Without knowing how to trigger this warning, I cannot fix it. So please let me know if you can provide information about that.
