### ISSUE TITLE
trim function not working

### ISSUE THREAD

**Issue by sm2607** [rspatial/terra#876]
Hi, I am using attached raster with trim function, but its got hanged and not able to create a new raster Below are my raster details and code. raster size is more than 100Mb so not able to upload raster here.

` 
>raster2=rast('test_sample1.tif')
>raster2
class       : SpatRaster 
dimensions  : 43259, 59540, 1  (nrow, ncol, nlyr)
resolution  : 4.5e-05, 4.5e-05  (x, y)
extent      : 5.078326, 7.757626, 49.76668, 51.71333  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : test_sample1.tif 
name        :         test 
min value   : 3.433228e-05 
max value   : 4.000000e+00 

>raster=terra::trim(raster1,filename="asd.tif")
`

**Comment by kadyb** [comment]
Here is some repex. Generally it works for smaller rasters (fit in memory), but for larger rasters I'm not sure. The example below was running over 30 min on my PC and didn't finish.

```r
library("terra")

r = rast(nrows = 20000, ncols = 20000, xmin = 5.078326, xmax = 7.757626,
         ymin = 49.76668, ymax = 51.71333, crs = "EPSG:4326")

vals = rnorm(ncell(r))
vals = matrix(vals, nrow(r), ncol(r), byrow = TRUE)
vals[18000:20000, ] = NA
vals[, 18000:20000] = NA
vals = as.vector(vals)

rr = init(r, vals, "test.tif", datatype = "FLT4S", gdal = "COMPRESS=LZW")
trim(rr, filename = "trimmed.tif")
```

**Comment by rhijmans** [comment]
This works for me in under a minute. But I have changed the algorithm. It is now a little faster for me, but not that much. Can you try it? (terra >= 1.6-38)

**Comment by kadyb** [comment]
For me after update, the above example was done in 9 seconds. But is the result correct? As NA, I marked 2000 columns and 2000 rows, but the result is 17999 columns and 5867 rows with values.
```r
system.time(trim(rr, filename = "trimmed.tif"))
#>   user  system elapsed 
#>   7.92    0.94    8.86 

class       : SpatRaster 
dimensions  : 5867, 17999, 1  (nrow, ncol, nlyr)
resolution  : 0.000133965, 9.73325e-05  (x, y)
extent      : 5.078326, 7.489562, 51.14228, 51.71333  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : trimmed.tif 
name        :     lyr.1 
min value   : -6.040875 
max value   :  5.691354 
```

**Comment by rhijmans** [comment]
Thank you! Should work better now.

**Comment by kadyb** [comment]
Thanks!

```r
class       : SpatRaster 
dimensions  : 17999, 17999, 1  (nrow, ncol, nlyr)
resolution  : 0.000133965, 9.73325e-05  (x, y)
extent      : 5.078326, 7.489562, 49.96144, 51.71333  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : trimmed.tif 
name        :     lyr.1 
min value   : -5.836152 
max value   :  6.018805 
```

**Comment by rhijmans** [comment]
What about the timing for you? I see:

```
library("terra")
terra 1.6.38
rr <- rast("test.tif")
system.time(x <- trim(rr))
#   user  system elapsed 
#  19.22    5.13   24.39 
system.time(x <- trim(rr, filename="trimmed.tif", overwrite=TRUE))
#   user  system elapsed 
#  40.51    7.02   47.69 
```

**Comment by kadyb** [comment]
Much better now. I see:

```r
## both processed in chunks
system.time(x <- trim(rr))
#   user  system elapsed 
#  28.42    2.31   30.81
system.time(x <- trim(rr, filename="trimmed.tif", overwrite=TRUE))
#   user  system elapsed 
#  28.33    2.22   30.58
```
