### ISSUE TITLE
crop() removing datatype of raster

### ISSUE THREAD

**Issue by mwalimaa** [rspatial/terra#877]
I have a large raster dataset (LANDFIRE BpS 2.2.0) geotif of the US and am attempting to crop() the raster using the extent from a shapefile of Michigan. Apologies that this is not reproducible without downloading the data. I'll provide links to the data below.

```
library(sf)
library(terra)

r <- rast("filepath/LANDFIRE/LF2020_BPS_220_CONUS/Tif/LC20_BPS_220.tif") # to SpatRaster
crs(r) # epsg 5070
str(r) # dataType: INT2S

v <- st_read(filepath/michigan.shp) %>%
        st_transform(5070) %>%
        vect() # to SpatVector

r_crop <- terra::crop(r, ext(v))

Warning message:
[crop] could not write the color table
detected values outside of the limits of datatype INT1U
detected values outside of the limits of datatype INT1U
detected values outside of the limits of datatype INT1U
detected values outside of the limits of datatype INT1U
detected values outside of the limits of datatype INT1U
```

That's the error code I get, and when I run str(r_crop) the dataType field is now blank. Any suggestions?
I even tried running crop(x, y, datatype = "INT2S") and the same error appeared.

I am using terra 1.6-17 . My associate tried it on his older computer with terra 1.6-3 and this code worked smoothly, so I am thinking something is wrong with the update?

LANDFIRE: https://landfire.gov/version_download.php
Michigan: https://catalog.data.gov/dataset/tiger-line-shapefile-2019-state-michigan-current-place-state-based

**Comment by rhijmans** [comment]
Thanks for reporting this. I think this happens when writing a temporary file, so probably related to RAM available at any given moment and not the version of terra. The issue was related to the color-table (and a work-around would be to remove it with `coltab(x) <- NULL`. 

But that should not be necessary anymore as the below runs for me without error or other messages.

```
library(terra)
r <- rast("LF2020_BPS_220_CONUS/Tif/LC20_BPS_220.tif")
v <- geodata::gadm("USA", level=1, path=".")
v <- v[v$NAME_1 == "Michigan", ]  |> project(r)

x <- terra::crop(r, v, filename="test2.tif", overwrite=TRUE)

activeCat(x) <- "GROUPVEG"
plot(x)
```

**Comment by mwalimaa** [comment]
@kadyb I will eventually need to pull in the attributes back in, but I have a few ideas on how to do that. It did work though!

@rhijmans This worked well, actually. I still got the same error without using `coltab(r) <- NULL` but was able to workaround by doing this
```
library(terra)
r <- rast("LF2020_BPS_220_CONUS/Tif/LC20_BPS_220.tif")
v <- geodata::gadm("USA", level=1, path=".")
v <- v[v$NAME_1 == "Michigan", ]  |> project(r)

cols <- coltab(r)
coltab(r) <- NULL

x <- terra::crop(r, v, filename="test2.tif", overwrite=TRUE)

coltab(x) <- cols

plot(x)
```

I tried it without writing the .tif to the directory `x <- terra::crop(r, v)` and it worked as well, as more processing will occur before ready to write it for analysis.

Thanks to you both!

**Comment by kadyb** [comment]
@mwalimaa, did you update `{terra}` to dev version (not CRAN)? The latest updates are in the dev version.

```r
install.packages('terra', repos='https://rspatial.r-universe.dev')
```

**Comment by mwalimaa** [comment]
@kadyb This worked perfectly. I still had some problems with the workarounds mentioned above (good to know I can do these things though), but updating to the dev version worked perfect. Thanks guys
