### ISSUE TITLE
Error in `terra:::.as.raster.factor()` when value(s) in raster that are not in levels 

### ISSUE THREAD

**Issue by brownag** [rspatial/terra#879]
The following gives a helpful warning (`[plot] value(s) in raster that is/are not in levels`), but also an error--probably related to  another case that was not considered from #830 

I think my expectation would be that if there are values in the raster not in levels they would display as `NA` (with a warning), but I could understand why it might be an error.

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.2.2
#> terra 1.6.38
r <- rast(nrow = 10, ncol = 10)
rat <- data.frame(lyr.1 = 1:2, group = c("A", "B"))
values(r) <- round(runif(100, 1, 3))
levels(r) <- rat
activeCat(r) <- "group"
plot(r)
#> Warning: [plot] value(s) in raster that is/are not in levels
#> Error in data.frame(id = out$levels, lab = out$cats[ilevels, 2], stringsAsFactors = FALSE): arguments imply differing number of rows: 3, 2
```

**Comment by rhijmans** [comment]
Thank you. This works now. The underlying function needs to be overhauled, but until that day...
