### ISSUE TITLE
sliding window function

### ISSUE THREAD

**Issue by athammad** [rspatial/terra#882]
Hi,

I have recently started using this great library but I am struggling to find a way to apply a function over a sliding window of layers where each layer is a month. `tapp` seems to be very close to what I want but I cannot find a way to specify a sliding index. 
So let's say I have 120 layers, corresponding to 120 months, I would like to run a function over a year (12 layers window) moving forward by one month (one layer).  Is this something currently possible?

Thank you.

Best wishes,
Ahmed

**Comment by rhijmans** [comment]
You can use `app` and a moving window function. But this is not the place for asking "how to" questions. I recommend StackOverflow.com for that.
