### ISSUE TITLE
8-bit ints coming to GDAL rasters

### ISSUE THREAD

**Issue by rsbivand** [rspatial/terra#885]
Heads-up: https://github.com/r-spatial/sf/issues/2033

**Comment by rhijmans** [comment]
Thanks very much for letting me know. 

Just to clarify: this adds support (in GDAL version 3.7) for the *signed* Byte data type (-128 - 127), "INT1S" in terra/raster speak. This comes in addition to the *unsigned* Byte data type (0 - 256, "INT1U") that already was available in GDAL.

**Comment by rsbivand** [comment]
Yes, of course you are right, sorry for the confusion. The ML threads indicate that confusion is a bit general: https://lists.osgeo.org/pipermail/gdal-dev/2022-November/056378.html, https://lists.osgeo.org/pipermail/gdal-dev/2022-November/056381.html. Also, the RFC still has to be accepted, so there is no easy way to test yet. So far only the draft RFC lives in rouault/rfc87: https://github.com/OSGeo/gdal/compare/master...rouault:gdal:rfc87
