### ISSUE TITLE
Does minmax estimate the values? (incorrectly?)

### ISSUE THREAD

**Issue by JimShady** [rspatial/terra#886]
I'm having issues using the minmax function.

If I load my raster file in QGIS, it looks like this (though I note I have to use the Actual (Slower) function to load them)

![image](https://user-images.githubusercontent.com/2901470/200815939-94940516-402f-4174-b7fe-4839ec65b908.png)

![image](https://user-images.githubusercontent.com/2901470/200815228-b0a8d16c-ee09-4508-b7d5-5291056ba786.png)

However when I use the minmax function in {terra} I get this:

![image](https://user-images.githubusercontent.com/2901470/200815607-1f4d4fbf-ea2c-472d-8b86-254c123149d5.png)

File is here:

https://github.com/JimShady/scratch/raw/main/test.tif

If minmax is estimating values, maybe it should have an option to not do that? i.e. `minmax(x, estimate = FALSE)` ?

**Comment by JimShady** [comment]
For info, the vapour package seems to get the info correctly.

![image](https://user-images.githubusercontent.com/2901470/200819597-d28cb9d7-c6b9-4a1b-a1fb-1f691e47c48b.png)

**Comment by barryrowlingson** [comment]
Often raster sources will keep an updated min and max in metadata to save software from having to scan all the pixels which might be slow.

Your sample raster doesn't have a metadata min/max, which you can test:

```
> r = rast("~/Downloads/test.tif")
> hasMinMax(r)
[1] FALSE
```

You can use `setMinMax` to work out the minmax:
```
> setMinMax(r)
> minmax(r)
      test
min 0.2000
max 6.1711
```
If you have a source that `hasMinMax(r)==TRUE` but the minmax metadata are incorrect (not sure how you'd tell without finding out in the first place) you can use `setMinMax(r, force=TRUE)` to recompute.

So I don't think its estimating, rather it initially says "I don't know the minmax, try +/- Infinity" unless minmax metadata are in the source, in which case it returns those, which you can set or force reset.

**Comment by JimShady** [comment]
Thanks for the excellent explanation as always @barryrowlingson  .

I'll close this now, though given choice I think it would be nice to be able to do this:

`minmax(x, force = TRUE)`

But I'll leave that to @rhijmans to consider.

**Comment by rhijmans** [comment]
Thanks, you can now do 

```
minmax(x, compute = TRUE)
```

Where `compute` is ignored if the values are available.
