### ISSUE TITLE
'crop' fails for some SpatVectors

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#889]
Hi,
Lately, `crop()` fails for some SpatVectors, claiming a "TopologyException" that doesn't seem to be there. Here's one example where that happens:

```
download.file("https://github.com/AMBarbosa/files/raw/main/mypoints.gpkg", destfile = "mypoints.gpkg")
download.file("https://github.com/AMBarbosa/files/raw/main/mypolys.gpkg", destfile = "mypolys.gpkg")

library(terra)
mypoints <- vect("mypoints.gpkg")
mypolys <- vect("mypolys.gpkg")

crop(mypoints, mypolys)
crop(mypoints, makeValid(mypolys))
# Error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 11.909361408115405 -17.199596163715462 at 11.909361408115405 -17.199596163715462
```

**Comment by kadyb** [comment]
This example works for me on GEOS 3.9.1. You can also try this:

```r
rel = relate(mypoints, mypolys, "intersects")
rel = apply(rel, 1, any)
idx = which(rel)
sel = mypoints[idx]
```

**Comment by kadyb** [comment]
This works for me too. What version of GEOS do you have (`gdal(lib = "")`)? The new engine OverlayNG for geometry operations was introduced in 3.9.

**Comment by AMBarbosa** [comment]
```
gdal(lib = "")
#     gdal    proj    geos 
#  "3.0.4" "7.0.0" "3.8.0" 
```
Not sure how to update it, though... and to get all students to update it as well! ;)

The error also ocurs when using `simplifyGeom` instead of `makeValid`.

Cheers!

**Comment by rhijmans** [comment]
Strange, but it all works for me with the windows release on CRAN ( GEOS 3.9.1) and the R-universe version (GEOS 3.9.3), and also on Ubuntu (GEOS 3.10.1) that was installed with 

```
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get install libgdal-dev libgeos-dev libproj-dev 
```

I do get errors with GEOS version 3.6.2 

It also seems that `intersect` works better with that version

```
x <- intersect(grid_eur, countries_eur)
```

**Comment by AMBarbosa** [comment]
Thanks. I ran the above commands in the Linux terminal, but for some reason my GDAL is not updated and the 'crop' problem persists. The same thing is now happening to an online student I have this week, who's also on Linux. Maybe we need to update our Linux versions, it's not really a 'terra' problem. On Windows we don't get this error.

**Comment by kadyb** [comment]
I think updating the system is the best option. In the ubuntugis-unstable repository the GEOS version is `3.8.0-1~bionic0` for Ubuntu 18.04 (Linux Mint 19.3). On Windows, GEOS from CRAN has got version 3.9.1.

**Comment by rhijmans** [comment]
I will this issue then, as the problem only occurs with older versions of GEOS.
