### ISSUE TITLE
Error in if (prj != "") { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by athammad** [rspatial/terra#890]
In trying to save a couple of large rasters in one single nc file. I got the following error.

```
multiRaster<-sds(Mraster)
writeCDF(multiRaster, "./NCfiles/multiRaste.nc",overwrite=TRUE)

Error in if (prj != "") { : missing value where TRUE/FALSE needed
```
I went to check the `crs` of the single files but everything looks fine. 

**Update**
It seems the issue is with  `tapp`. Here is a simple way to reproduce the error

```
r <- rast(ncols=10, nrows=10)
values(r) <- 1:ncell(r)
s <- c(r, r, r, r, r, r)
s <- s * 1:6
b1 <- tapp(s, index=c(1,1,1,2,2,2), fun=mean)
writeCDF(b1, "xxx.nc", overwrite=TRUE)
```

**Comment by kadyb** [comment]
This looks like regressions because it works in 1.6.17. Maybe it's related to #797. Have you tried to set up some CRS?

**Comment by rhijmans** [comment]
Thanks. This was introduced because of a change that makes writeCDF also write the EPSG code of the crs to the file. This failed for cases when there was no EPSG code; I tested for it be `""` where the test should be for `NA` in this case.
