### ISSUE TITLE
na.rm behaviour in predict when redundan bands are present...

### ISSUE THREAD

**Issue by h-a-graham** [rspatial/terra#891]
When using terra::predict, If the SpatRaster object contains additional bands (not used in the model) the presence of NA values in these bands is considered when na.rm=TRUE is used. I'm not necessarily suggesting this is the wrong choice (I can see why this might be desired), but perhaps a warning might be useful to help diagnose missing values in the predicted model... 

Here is an example: 

``` r
library(terra)
#> terra 1.6.14
logo <- rast(system.file("ex/logo.tif", package="terra"))   
names(logo) <- c("red", "green", "blue")

red <- matrix(c(48, 48, 48, 53, 50, 46, 54, 70, 84, 85, 74, 84, 95, 85, 
                66, 42, 26, 4, 19, 17, 7, 14, 26, 29, 39, 45, 51, 56, 46, 38, 31, 
                22, 34, 60, 70, 73, 63, 46, 43, 28), ncol=2)

green <- matrix(c(22, 33, 64, 85, 92, 94, 59, 27, 30, 64, 60, 33, 31, 9,
                  99, 67, 15, 5, 4, 30, 8, 37, 42, 27, 19, 69, 60, 73, 3, 5, 21,
                  37, 52, 70, 74, 9, 13, 4, 17, 47), ncol=2)

xy <- rbind(cbind(1, red), cbind(0, green))
# extract predictor values for points
e <- extract(logo, xy[,2:3])
# combine with response (excluding the ID column)
v <- data.frame(cbind(pa=xy[,1], e))
#build a model, here with glm 
model <- glm(formula=blue~red+green, data=v, na.action = na.omit)

#predict to a raster
r1 <- predict(logo, model)
plot(r1)
```

![](https://i.imgur.com/jlk6HbC.png)

``` r

logo2 <- logo[[c("red", "green")]]
logo2$hasNA <- logo$red
logo2$hasNA[logo2$hasNA>150] <- NA
plot(logo2)
```

![](https://i.imgur.com/EClmDUd.png)

``` r

r2 <- predict(logo2, model, na.rm=TRUE)
plot(r2)
```

![](https://i.imgur.com/c9fClCX.png)

<sup>Created on 2022-11-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So basially even though the 'hasNA' band is not relevant to the model, the NA values are still removed. perhaps in this case, there should be a warning to flag the possibility that some values are missing which perhaps don't need to be. Or should the SpatRaster be filtered before applying the model to consider only the required bands, maybe? 

In this case the identification of NA bands is trivial but when working with highly dimensional data, it's not always easy to catch which bands are causing the problem. 

Many thanks and really appreciate the this package and your work on it!

**Comment by rhijmans** [comment]
I do not think there is a general method to extract the variable names from a model. If there was a way to do that I could use it in `predict` to subset the SpatRaster to the corresponding layers. 

I would also note that the `na.rm` argument is already a bit of a hack to deal with the diversity of models in R. You would think that all models would take NA as inputs (and return NA or whatever else is appropriate). But some `model.predict` methods fail when given NA as input.

**Comment by h-a-graham** [comment]
Yeah that is completely fair and indeed I have simply subset the SpatRaster before fitting the model, it just took me a little while to grok why I was getting large holes in my model predictions and was wondering if there was a simple way to warn anyone in the future not to fall into the same trap as me! 

I also take your point about the subsetting needing to be generic - your solution of adding to the documentation is great - thanks so much for the quick response. 

Have a great weekend!
