### ISSUE TITLE
Terra package version for R 3.6.3

### ISSUE THREAD

**Issue by Gonzalo1985** [rspatial/terra#892]
Hello,

I am having an issue when I want to install last version of raster package for R 3.6.3. I got the next message:

geos_methods.cpp:2813:73: error: no ‘SpatVector SpatVector::nearest_feature(SpatVector, std::__cxx11::string)’ member function declared in class ‘SpatVector’
 SpatVector SpatVector::nearest_feature(SpatVector v, std::string distfun) {
                                                                         ^
/usr/lib/R/etc/Makeconf:177: recipe for target 'geos_methods.o' failed
make: *** [geos_methods.o] Error 1
ERROR: compilation failed for package ‘terra’
* removing ‘/data/R-libs/x86_64-pc-linux-gnu-library/3.6/terra’
* restoring previous ‘/data/R-libs/x86_64-pc-linux-gnu-library/3.6/terra’
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
* installing *source* package ‘raster’ ...
** package ‘raster’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RasterModule.cpp -o RasterModule.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c aggregate.cpp -o aggregate.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bilinear.cpp -o bilinear.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c broom.cpp -o broom.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c cellRowCol.cpp -o cellRowCol.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c clamp.cpp -o clamp.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c distance.cpp -o distance.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c edge.cpp -o edge.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c focal_fun.cpp -o focal_fun.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c focal_get.cpp -o focal_get.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c focal_sum.cpp -o focal_sum.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c geodesic.c -o geodesic.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c getPolygons.cpp -o getPolygons.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c layerize.cpp -o layerize.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c memory.cpp -o memory.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c modal.cpp -o modal.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ppmin.cpp -o ppmin.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c raster_aggregate.cpp -o raster_aggregate.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c raster_distance.cpp -o raster_distance.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rasterize.cpp -o rasterize.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c reclass.cpp -o reclass.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c terrain.cpp -o terrain.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c util.cpp -o util.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/data/R-libs/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c xyCell.cpp -o xyCell.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o raster.so RasterModule.o RcppExports.o aggregate.o bilinear.o broom.o cellRowCol.o clamp.o distance.o edge.o focal_fun.o focal_get.o focal_sum.o geodesic.o getPolygons.o layerize.o memory.o modal.o ppmin.o raster_aggregate.o raster_distance.o rasterize.o reclass.o terrain.o util.o xyCell.o -L/usr/lib/R/lib -lR
installing to /data/R-libs/x86_64-pc-linux-gnu-library/3.6/00LOCK-raster/00new/raster/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘terra’ 1.5-21 is being loaded, but >= 1.6.16 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘raster’
* removing ‘/data/R-libs/x86_64-pc-linux-gnu-library/3.6/raster’
* restoring previous ‘/data/R-libs/x86_64-pc-linux-gnu-library/3.6/raster’
Warning in install.packages :
  installation of package ‘raster’ had non-zero exit status

The downloaded source packages are in
	‘/data/tmp/RtmpibLVr5/downloaded_packages’

I think is a problem with terra package, but when I try to install last version of terra package I can't do it and if I go to CRAN to look for the 1.6.16 version is not available to download.

Could you help me to solve this problem?? Thank you!

Kind regards,
Gonzalo

**Comment by rhijmans** [comment]
Can you try to install the development version instead? You should not get this error with that version.

**Comment by Gonzalo1985** [comment]
The problem is that I am trying to install https://github.com/RS-eco/processNC

And this package have some requires, like:

Downloading GitHub repo RS-eco/processNC@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: terra  (1.5-21 -> 1.6-17) [CRAN]
5: raster (3.5-15 -> 3.6-3 ) [CRAN]

Is there no chance to install these new versions of terra and raster in an R 3.6.3? GEOS is a OS package?

Thank you very much for your answer!

**Comment by rhijmans** [comment]
I already provided the solution: install the development version of terra. For example with remotes::install_github`, or with `install.packages('terra', repos='https://rspatial.r-universe.dev')`.   

But the easiest approach would be to choose "None" in the update dialog you are showing.

**Comment by Gonzalo1985** [comment]
Thank you! But when I choose None I get:

Running `R CMD build`...
* checking for file ‘/data/tmp/RtmpibLVr5/remotes428b2a0ac9f3/RS-eco-processNC-f285e45/DESCRIPTION’ ... OK
* preparing ‘processNC’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘processNC_0.0.1.tar.gz’
Installing package into ‘/data/R-libs/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
ERROR: this R is version 3.6.3, package 'processNC' requires R >= 4.0
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpibLVr5/file428b2a5a5776/processNC_0.0.1.tar.gz’ had non-zero exit status
  
  But I used to use this package in R 3.4.4 so it is strange the message I get. I am not sure what is the problem
  
  Thank you!

**Comment by rhijmans** [comment]
I think this message is pretty clear:

```
ERROR: this R is version 3.6.3, package 'processNC' requires R >= 4.0
```

I would also note that you can directly use "terra" for these things. 

The `processNC` repo README says that with raster or terra "the entire file is read into memory and so memory limits are reached quickly when trying to load large NetCDF files.".  I have no idea why they would suggest that; that is not true at all.

**Comment by Gonzalo1985** [comment]
Thank you very much, I'll see what I can do.
