### ISSUE TITLE
terra::focalMat( , d = "circle") results in wrong Matrix dimensions;

### ISSUE THREAD

**Issue by Quartaer** [rspatial/terra#894]
Goal: I wanted to create a circular, equally weighted matrix (as a kernel) for about 1 ha!

Whether I entered the diameter or the radius for the parameter 'd', a new raster was output with dimensions that were inexplicable or wrong to me. I manually developed the value of diameter-23 that was suitable in my case. I also cannot explain why the 23 comes about.

I use the terra package 1.6-17 and R 4.2.2 under windows.
Same issue with raster::focalWeight(, d= "circle")

```
r <-  raster::raster(ncols= 113,  nrow=113,   xmn=0,   crs="+proj=utm +zone=34")
W <-   terra::focalMat(r,   d = 113,  type = "circle",   fillNA = F)           
dim(W)
#[1] 141 141
```

**Comment by rhijmans** [comment]
stackoverflow.com is a better place to ask questions like this. 

The radius of a 1 ha circle is 

```
rad <- sqrt(10000 / pi)
```

So you can do 

```
library(terra)
x <-  rast(ncols= 113,  nrow=113,   xmin=0,   crs="+proj=utm +zone=34")
w <-  terra::focalMat(x,  d = rad,  type = "circle")           
dim(w)
#[1] 71 71
prod(res(x)) * sum(w>0)
#[1] 10010.02
```

**Comment by Quartaer** [comment]
Thank you very much for addressing the problem. But I think that the algorithm for "circle" somehow uses a fraction (0.55) of the radius, maybe something similar to sigma (about 0.68). That would explain the (strange) reduced dimensioning of the matrix from, say, 100*100 input grid (x) at radius 50 (d) to 55 * 55 in the output matrix (w). As a user, I would assume that the parameter x= specifies the grid on which the weights are projected with the resolution of x. That is, output (w) should again be 100 * 100 if I choose radius (d=) 50 with an input of 100 * 100 (x). But instead, I get a matrix (w) of 55 * 55!? 

I need this matrix as a moving window for another analysis.  In my 1 ha case, I need a grid with a 1-meter resolution of 2 * (r=) 56.4m ... pi*r² = 1 ha --> 113 * 113 cells matrix and not 71 * 71.

Or I don't understand the idea behind the function!
I hope my English is not rude! Thanks!

**Comment by rhijmans** [comment]
Again, please use stackoverflow.com, but I think you are not considering the resolution of SpatRaster `x`. It is 1.6 m but you seem to assume that it is 1 m. Note that. 

```
113 / res(x)[1]
#[1] 70.93889
```
