### ISSUE TITLE
disagg and resample crash

### ISSUE THREAD

**Issue by fabeit** [rspatial/terra#896]
I am trying to change the resolution of the following raster https://ufile.io/lktl9yyx
```
class       : SpatRaster 
dimensions  : 143, 144, 1  (nrow, ncol, nlyr)
resolution  : 2.5, 1.2676  (x, y)
extent      : -1.25, 358.75, -90.634, 90.634  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
source      : srad_4c.nc 
name        : srad.mean.period 
```
to this
dimensions  : 1080, 2160, 19  (nrow, ncol, nlyr)
resolution  : 0.16667, 0.16667  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)

but both disagg and resample make my R session crash
```
srad4.aggregate <- disagg(srad4.pred.mean, fact=12,method='bilinear')
s <- rast(nrows=360, ncols=720, xmin=-180, xmax=180, ymin=-90, ymax=90)
srad4.aggregate <- terra::resample(srad4.pred.mean,s)
```
However if I user the raster package everything works fine.

This also works in terra but not sure if it's ideal

srad4.aggregate <- disagg(srad4.pred.mean, fact=c(2,5))
srad4.aggregate <- terra::resample(srad4.aggregate, mytarget.raster)

**Comment by kadyb** [comment]
For me this example works in `{terra}`.

<details>
  <summary>Session info</summary>

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] terra_1.6-17

loaded via a namespace (and not attached):
[1] compiler_4.2.1   tools_4.2.1      Rcpp_1.0.9.3    
[4] codetools_0.2-18 ncdf4_1.19

   gdal    proj    geos
"3.4.3" "7.2.1" "3.9.1"
```

</details>

**Comment by fabeit** [comment]
@kadyb thanks for the feedback, I have updated all my packages and will try again.

**Comment by rhijmans** [comment]
I believe this works fine. Another thing to check is that you are not loading an old session when starting up R.
