### ISSUE TITLE
warn when assigning CRS

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#897]
No matter how much I explain it, I constantly see students assigning the (wrong) CRS to their layers (e.g. `crs(mylayer) <- "epsg:4326"`), when what they want to do is `project(mylayer, "epsg:4326")`. Might it be a good idea to emit at least a warning when a CRS is assigned to a layer that already had a valid CRS, i.e. not an empty text string? Cheers

**Comment by rhijmans** [comment]
I very well aware of this problem. I have tried with "you can write 'car' on your bicycle, but that won't change it into a car". That did not help. I have added the warning. I hope it won't be too annoying for cases where using `crs<-` is intentional.

**Comment by brownag** [comment]
I think this is a good change, I've seen this happen a bunch too.

> I hope it won't be too annoying for cases where using `crs<-` is intentional.

Just an idea: perhaps `crs<-` could take a `warn=TRUE` argument by default, allowing folks to explicitly suppress this specific warning (with e.g. `crs(x, warn=FALSE) <- "epsg:4326"`) if they are deliberately resetting an existing CRS, without having to use `suppressWarnings()`

**Comment by kadyb** [comment]
A similar warning is returned in `{sf}` (but not `{stars}`). Maybe it would be better to return a message instead of warning?

```r
library("sf")
f = system.file("shape/nc.shp", package = "sf")
nc = read_sf(f)
st_crs(nc) = "EPSG:4326"
#> Warning message:
#> st_crs<- : replacing crs does not reproject data; use st_transform for that 
```

**Comment by rhijmans** [comment]
Thanks, there now is a `warn` argument. 
I suppose a "message" is better than a "warning" because from a software perspective nothing unexpected is happening?

**Comment by kadyb** [comment]
I believe the "message" is less harmful. If we suddenly change it to a "warning", I suspect that there may be some problems on CI or CRAN. But it should be fine in the long run.
