### ISSUE TITLE
sapp fails to accept any additional argument!

### ISSUE THREAD

**Issue by babaknaimi** [rspatial/terra#898]
Dear Robert,

As far as I understood, sapp applies a function over each layer in a SpatRaster (so the whole layer would be the input to the function) and return a new SpatRaster with the same number of layers to each of which the user-specified function is applied (the same as applying the function over a loop to each layer). If this is true, I think it would not pass the additional argument required by the function to the function. Here is a toy example to reproduce the issue:

```
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
ff <- function(x,n,...) x / n # function
rr <- sapp(c(r,r), fun=ff, n=10, na.rm=T)
# Error in fun(r, ...) : argument "n" is missing, with no default
```

Any advice?

Cheers,
Babak

**Comment by rhijmans** [comment]
Thanks Babak, that was indeed broken. I now get: 


```
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
ff <- function(x,n,...) x / n # function
sapp(c(r,r), fun=ff, n=10, na.rm=T)

#class       : SpatRaster 
#dimensions  : 90, 95, 2  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source(s)   : memory
#names       : elevation, elevation 
#min values  :      14.1,      14.1 
#max values  :      54.7,      54.7 
```
