### ISSUE TITLE
"No applicable method 'predict' " when using 'interpolate' function with 'cores' argument

### ISSUE THREAD

**Issue by NicholasBerryman** [rspatial/terra#899]
When using the interpolate function on a gstat object, I receive the attached error if the cores argument is used.
The interpolate function works fine if the cores argument is left unused.

A relevant code snippet is also attached.

### Code
![image](https://user-images.githubusercontent.com/3523408/202611792-1298c277-8a0e-4d8b-bffc-11a5f1547dc8.png)

### Error
![image](https://user-images.githubusercontent.com/3523408/202611938-9f281aa3-e909-4388-86f4-bb1210f2d72f.png)

**Comment by NicholasBerryman** [comment]
I've since managed to resolve this issue with a manual call to `parallel::ClusterEvalQ(cl,{library('gstat')}

**Comment by rhijmans** [comment]
You need to use argument `cpkgs="gstat"` see below. 

```
library(terra)
library(gstat)
library(sp)
data(meuse)

r <- rast(system.file("ex/meuse.tif", package="terra"))
mg <- gstat(id = "zinc", formula = zinc~1, locations = ~x+y, data=meuse, 
            nmax=7, set=list(idp = .5))
z <- interpolate(r, mg, debug.level=0, index=1, cores=2, )
```

Please do not include screenshots. Instead include the actual code (of a reproducible example) and messages you got.
