### ISSUE TITLE
New MacOS installation instructions

### ISSUE THREAD

**Issue by GuiAlDuS** [rspatial/terra#9]
Homebrew's PROJ.4, GDAL and GEOS libraries changed in the last months so the steps in the main readme don't work.

In my case the error says that `libproj.13.dylib` doesn't exist, and it happened after I updated PROJ.4 (now osgeo-proj ). I tried both with osgeo4mac and the main versions, also reinstalling terra, but I still got the same error.

I had also some issues with the `sf` library but I solved it by symlinking the osgeo-proj directory as proj, didn't work for terra, sadly.

Any workaround for these issues?

**Comment by rhijmans** [comment]
I am no expert, but from the sf repo I see that it should be possible to simply do `brew install gdal` now...

**Comment by GuiAlDuS** [comment]
It now works fine.
Thanks Robert!
