### ISSUE TITLE
Terra equivalent to raster::getValuesBlock

### ISSUE THREAD

**Issue by gilbertocamara** [rspatial/terra#90]
I am trying to extract a block from a large Sentinel time series (70 time instances x 10,000 x 10,000 pixels). Using raster::getValuesBlock is quite slow. What is the terra equivalent to that function?

**Comment by rhijmans** [comment]
You should be able to use  
```
readStart(x)
v <- readValues(x, ...) 
readStop(x)
```

**Comment by gilbertocamara** [comment]
Dear Robert, thanks for the response. As per the documentation, terra::readValues  "returns all cell values of a SpatRaster", which will not fit into memory in the case of big EO data. I have been using terra::crop, but this is not the best solution, since the "crop" function depends on the extent, which in turn depends on the spatial resolution. Using raster::getValuesBlock allows breaking a big image into blocks and reading the values of the image on a block-by-block basis.

**Comment by gilbertocamara** [comment]
Sorry, I made a confusion between terra::values and terra::readValues. Apologies.

**Comment by rhijmans** [comment]
Hi Gilberto, 

There are a few methods in terra that use these functions (most other functions do something similar at the C level). The pattern is something like this (here taken from `app` and simplified)
  
```
	b <- writeStart(out, filename, overwrite, wopt)
	for (i in 1:b$n) {
		v <- readValues(x, b$row[i], b$nrows[i], 1, nc, TRUE)
		r <- apply(v, 1, fun, ...)
		writeValues(out, r, b$row[i], b$nrows[i])
	}
	writeStop(out)
```

i/o may be improved over time, e.g. by using file tiling structures and loop over tiles instead of rows.

**Comment by gilbertocamara** [comment]
Dear Robert

I have almost completed the transition in the SITS package (https://github.com/e-sensing/sits) from raster to terra. Thanks to your tips, it was a smooth conversion. There’s only one issue missing, which is not your responsibility. It concerns the “mapview” package which at present only supports “raster” object. Terra is really much faster than Raster.

Many thanks,
Gilberto

===========================
Prof Dr Gilberto Camara
Secretariat Director
GEO - Group on Earth Observations
7 bis, Avenue de La Paix
CH-1211 Geneva - Switzerland
Tel: +41227308480
www.earthobservations.org

**Comment by tim-salabim** [comment]
Hi @gilbertocamara I am currently planning to revamp all raster based processing in mapview to stars based processing and simply use their coercion method to go from raster -> stars or terra -> stars. I opted for stars internally, as it seems a little more flexible (e.g. no limit on domensions). This will take a while to implement though. Is sits using mapview internally? If so, could you please open an issue over at mapview, so we can keep track of this?
