### ISSUE TITLE
writeRaster increasing file size?

### ISSUE THREAD

**Issue by KyleTDavid** [rspatial/terra#900]
I am projecting and masking some large (~1 billion cells) rasters in an attempt to shrink the file size but the output files are much larger than expected. Even `writeRaster(rast(input.tif), 'output.tif')` gives me an output that is almost exactly 5x larger than the input. Is this the expected behavior? Any idea what might be going on?

**Comment by rhijmans** [comment]
File size depends on data type and compression. You can inspect the original with `describe("input.tif")` and you can set them for the output file, see ?writeRaster. The default data type after projection is FLT4S (4 byte float), perhaps the input was 1 or 2 bytes integer? (also see `datatype(rast(input.tif))`

**Comment by KyleTDavid** [comment]
Thanks for your quick and detailed response! I was able to shrink the output file size significantly by using the same compression as the input (with `gdal=c("COMPRESS=DEFLATE")`). However I am not able to find the data type. In my version (1.4-22) `datatype()` seems to only accept vectors, not rasters.

**Comment by rhijmans** [comment]
Oh, then perhaps you need a newer version. That info is also provided by `describe`, in lines like this:

```
"Band 1 Block=373x1 Type=Float32, ColorInterp=Gray"   
```

"Float32" == "FLT4S"

**Comment by KyleTDavid** [comment]
My input is file is:
>
>'Band 1 Block=43200x1 Type=UInt16, ColorInterp=Gray'
>
I assume this translates to "INT2U" but my cell values are definitely floats. I think this is accomplished with an offset, which 'describe()' tells me is -273.15, is there a way to provide an offset to the output with `writeRaster()` as well?

**Comment by rhijmans** [comment]
In this case. it could be simpler to round the values and write to "INT2S" without the offset. 

It was not possible to write scale and offset. But I have now added that capacity.  Here is an example. 

Create an example file with a scale and offset 
```
library(terra)
r <- rast(system.file("ex/meuse.tif", package="terra"))
x <- writeRaster(r, "test.tif", overwrite=TRUE, offset=100, scale=10)

minmax(r)
#    test
#min  138
#max 1736

minmax(x)
#     test
#min  1480
#max 17460

scoff(x)
#     scale offset
#[1,]    10    100
``` 

To write a new file with the same scale/offset, first remove them, to get the raw values (you can only remove the scale/offset from file-based layers).

```
scoff(x) <- NULL
minmax(x)
#    test
#min  138
#max 1736

y <- flip(x, "v",  offset=100, scale=10, filename="test2.tif", overwrite=TRUE)
#     test
#min  1480
#max 17460

scoff(y)
#     scale offset
#[1,]    10    100
```

Currently, the written scale/offset values cannot vary by layer.

**Comment by edzer** [comment]
I looked at the implementation of this (https://github.com/rspatial/terra/commit/600ecaa5bc1d7fa56fd437604c931cce3ca1b13f), and to the GDAL documentation [here](https://gdal.org/doxygen/classGDALRasterBand.html#a11e59146b02d52127c8427cccc37683d), and understand it that during writing you go from the units value (the one in the terra object) to the raw (the one on disc), so when units = raw * scale + offset, then raw = (units - offset) / scale is what you should write. The implementation seems to be the other way around, so when writing scale & offset this way, reading it e.g. [here](https://github.com/r-spatial/sf/blob/main/src/stars.cpp#L176) would not give the right value. I didn't try this, so might be totally wrong!

**Comment by edzer** [comment]
I tried it out on the stars side, where https://github.com/r-spatial/sf/blob/main/src/stars.cpp#L652 seems to roundtrip things the way GDAL documentation suggests.

**Comment by rhijmans** [comment]
Thanks @edzer. The way I had it implemented is that you *declare* the scale and offset, rather than request that it be computed.  I now changed that to the latter, which is simpler and more intuitive.
