### ISSUE TITLE
Error: [merge] internal error: path does not exist

### ISSUE THREAD

**Issue by fgoerlich** [rspatial/terra#902]
Hi,
Running an sript in one machine works perfect, but in a different one I get:
`Error: [merge] internal error: path does not exist`
Same version of `terra` on both machines: `1.6.17`.
It should be a configuration problem, but since it is an internal error I don´t know how to proceed.
Thanks a lot!

**Comment by fgoerlich** [comment]
Very usefull the warning!
I have installed version 1.6-17, since I have been unable to installed the last version on CRAN 1.6-41:
```r
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'terra'
* removing 'C:/Users/FJG/AppData/Local/R/win-library/4.2/terra'
* restoring previous 'C:/Users/FJG/AppData/Local/R/win-library/4.2/terra'
Warning in install.packages :
  installation of package ‘terra’ had non-zero exit status
```
I have an issue to see if still happens with the new version: https://github.com/r-spatial/stars/issues/588#issuecomment-1321109038
Thanks a lot!

**Comment by fgoerlich** [comment]
Instaling from CRAN, `install.packages("terra")`, does not work. I get the erro above.
Do you mean installing the development version `install.packages('terra', repos='https://rspatial.r-universe.dev')` o from source (I am on Windows)?

**Comment by rhijmans** [comment]
Installing from CRAN does work, but you should not choose to use a package that needs compilation (it will be available compiled in a few days from CRAN). Or, if you do, see the instructions (that is, install RTools).  In contrast, the r-universe install is easy, because it is compiled so you do not need to worry about that.
