### ISSUE TITLE
GDAL Message reading a tif file written with a previous version of terra

### ISSUE THREAD

**Issue by fgoerlich** [rspatial/terra#903]
After updating `terra` from version 1.6.17 (which uses gdal to `3.4.3`) to version 1.6-41 (which uses gdal to `3.5.2`) I get some GDAL messages:
```r
terra::rast("PNOA_MDT05_CodMuni_52001_buffer100.tif")
#> proj_create_from_database: datum not found
#> proj_create_from_database: ellipsoid not found
#> proj_create_from_database: prime meridian not found
#> class       : SpatRaster 
#> dimensions  : 1494, 1601, 1  (nrow, ncol, nlyr)
#> resolution  : 5, 5  (x, y)
#> extent      : 500497.5, 508502.5, 3901198, 3908668  (xmin, xmax, ymin, ymax)
#> coord. ref. : ETRS89 / UTM zone 30N (EPSG:25830) 
#> source      : PNOA_MDT05_CodMuni_52001_buffer100.tif 
#> name        : PNOA_MDT05_ETRS89_HU30_1111_COR 
#> min value   :                          -4.534 
#> max value   :                         362.375 
```
The file was written with version 1.6.17 and when read with that version no messages appears in `terra`, but they also appear in `stars`.

Full details and the file are in https://github.com/r-spatial/stars/issues/588.

Should I degrade to the previous version?

**Comment by rhijmans** [comment]
Let's keep the discussion in one place (at stars, where it started).
