### ISSUE TITLE
Redundant lines in autocor() function

### ISSUE THREAD

**Issue by fischer-fjd** [rspatial/terra#904]
Hi, I am currently looking at local spatial auto-correlation for a project and looked at the source code for the autocor() function, and I think I found a redundant line both in the local moran and local geary functions:

`n <- ncell(x) - unlist(global(is.na(x), "sum"))`

This is 183 and 194 in the current code on github, respectively. It is not used anywhere, as far as I can see, so everything should be correct, but it might add a little bit to the computational time.

**Comment by rhijmans** [comment]
Thanks!
