### ISSUE TITLE
`alpha` now failing for `plot(SpatVector)`

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#906]
Hi, the 'alpha' parameter was working alright for all maps, but lately it seems to be automatically changed to 0 for SpatVector points, lines, and polygon fills:
```
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
par(mfrow = c(1, 3))

c <- centroids(v)
plot(c)
plot(c, col = "blue")
plot(c, col = "blue", alpha = 0.7)
```
![image](https://user-images.githubusercontent.com/12085508/203524824-1c4ae13e-06bc-49f8-9040-954562f00815.png)

```
l <- as.lines(v)
plot(l)
plot(l, col = "blue")
plot(l, col = "blue", alpha = 0.7)
```
![image](https://user-images.githubusercontent.com/12085508/203524784-3fa97024-f5b3-46d0-b599-39211a93edc9.png)
```
plot(v)
plot(v, col = "blue")
plot(v, col = "blue", alpha = 0.7)
```
![image](https://user-images.githubusercontent.com/12085508/203524680-96cf4c85-3d47-4c19-8428-fe4eb491577b.png)

**Comment by rhijmans** [comment]
Thanks, looks like it works again.
