### ISSUE TITLE
focalCor / focalReg with custom weights matrix

### ISSUE THREAD

**Issue by fischer-fjd** [rspatial/terra#907]
Hi Robert,

thanks for all the great functionalities in terra! I was trying out the focalCor / focalReg functions today (terra version 1.6-41). As I generally tend to prefer circular windows for spatial operations, I tried to apply custom weights matrices within focalCor and focalReg, and I think I found two potential issues. However, some of the problems may also be down to documentation/my confusion, as I do not quite understand what happens in focalCor / focalReg with the weights. Will a 0 entry in a custom weights matrix be ignored when using Pearson's correlation in focalCor? Will an entry with 0.1 be downweighted compared to an entry with, say, 0.2, or simply be passed on, etc.? 

The two potential issues were:

**1/ Weights matrix with NAs fails completely**: I tried using a circular weights matrix with NAs instead of 0s. This was the option that would make most sense to me, as I would definitely know that the values outside of the circle would be ignored. But both focalCor and focalReg fail in this case. 

**2/ Edge effects**: When applying the focalCor function with a custom matrix, this generally seems to introduce a boundary NA layer in the resulting SpatRaster, i.e. the extent stays the same, but the outer rows and columns are NA. The size of this boundary layer seems related to the size of the custom weights matrix. 

Please find below a sample code based on your examples from the focalCor documentation: 

```
r <- rast(system.file("ex/logo.tif", package="terra"))
set.seed(0)
r[[1]] <- flip(r[[1]], "horizontal")
r[[2]] <- flip(r[[2]], "vertical") + init(rast(r,1), runif)
r[[3]] <- init(rast(r,1), runif)`

# works fine (but edges are removed in focalCor)
window_gaussian <- focalMat(r, d = 3,type = "Gauss")
x <- focalCor(r, w = window_gaussian, cor)
plot(x)

x2 <- focalReg(r, w = window_gaussian, na.rm = T)
plot(x2)

# works fine (but edges are removed in focalCor)
window_circle_nona <- focalMat(r, d = 10,type = "circle", fillNA = FALSE)
y <- focalCor(r, w = window_circle_nona, cor)
plot(y)

y2 <- focalReg(r, w = window_circle_nona, na.rm = T)
plot(y2)

# does not work
window_circle_na <- focalMat(r, d = 10,type = "circle", fillNA = TRUE)
z <- focalCor(r, w = window_circle_na, cor)
plot(z)

z <- focalReg(r, w = window_circle_na, na.rm = T)
plot(z2)
```

Best,

Fabian

**Comment by rhijmans** [comment]
Thanks --- that indeed needs fixing. Here is what it looks like now for `focalCor`

Example data 
```
library(terra)
#terra 1.6.44
r <- rast(system.file("ex/logo.tif", package="terra"))
set.seed(0)
r[[1]] <- flip(r[[1]], "horizontal")
r[[2]] <- flip(r[[2]], "vertical") + init(rast(r,1), runif)
r[[3]] <- init(rast(r,1), runif)
```

In the standard case you can only have window values that are 0, NA (both are ignored), or 1.  Other values are set to 1.

 ```
window_circle_nona <- focalMat(r, d = 10,type = "circle", fillNA = FALSE)
x <- focalCor(r, w = window_circle_nona, cor)
#Warning message:
#[focalCor] all weights that are not zero or NA are set to 1 
plot(x)
``` 

To not remove edges you need to provide a function that can handle NAs. In this example you can add an argument for that.

```
y <- focalCor(r, w = window_circle_nona, cor, use="complete.obs")
#Warning messages:
#1: [focalCor] all weights that are not zero or NA are set to 1 
#2: In fun(X[i, ], Y[i, ], ...) : the standard deviation is zero
#3: In fun(X[i, ], Y[i, ], ...) : the standard deviation is zero
#4: In fun(X[i, ], Y[i, ], ...) : the standard deviation is zero
plot(y)
```

The window can have NAs

``` 
window_circle_na <- focalMat(r, d = 10,type = "circle", fillNA = TRUE)
z <- focalCor(r, w = window_circle_na, cor, use="complete.obs")
#Warning messages:
#1: [focalCor] all weights that are not zero or NA are set to 1 
#2: In fun(X[i, ], Y[i, ], ...) : the standard deviation is zero
#3: In fun(X[i, ], Y[i, ], ...) : the standard deviation is zero
#4: In fun(X[i, ], Y[i, ], ...) : the standard deviation is zero
plot(z)
```

You can also use the window values as weights 

```
library(wCorr)
#wCorr v1.9.5
window_circle_nona <- focalMat(r, d = 10,type = "circle", fillNA = FALSE)
a <- focalCor(r, w = window_circle_na, weightedCorr, method="Pearson", weighted=TRUE)
```

Does this look good to you?

**Comment by rhijmans** [comment]
I have also updated `focalReg` 

```
library(terra)
r <- rast(system.file("ex/logo.tif", package="terra"))
set.seed(0)
r[[1]] <- flip(r[[1]], "horizontal")
r[[2]] <- flip(r[[2]], "vertical") + init(rast(r,1), runif)
r[[3]] <- init(rast(r,1), runif)

window_circle_nona <- focalMat(r, d = 10,type = "circle", fillNA = FALSE)
y2 <- focalReg(r, w = window_circle_nona, na.rm = T)
plot(y2)

window_gaussian <- focalMat(r, d = 3,type = "Gauss")
x2 <- focalReg(r, w = window_gaussian, na.rm = T)
plot(x2)

window_circle_na <- focalMat(r, d = 10,type = "circle", fillNA = TRUE)
z2 <- focalReg(r, w = window_circle_na, na.rm = T, weighted=T)
plot(z2)
```

**Comment by fischer-fjd** [comment]
Hi Robert,

that is perfect, and thanks for addressing this so quickly! 

I just tested both focalCor / focalReg out with the newest version 1.6-45, and it looks great, and yes, these functions now do what I would expect them to do (or warn me that they don't)! So from my side this can be regarded as resolved. 

In the long run, I was wondering whether it might make sense to automatically use the "weighted = T" as default in focalReg as soon as a user specifies a matrix with non-constant weight values (not counting any 0s/NAs)? But I recognize that this would be trickier with focalCor: it would also make sense to automatically do weighted correlation once a matrix with non-constant weights (excluding 0/NA) is provided, but then this would require wCorr, so maybe keeping both focalReg/focalCor as they are right now is conceptually clearer. Personally, I would also find it intuitive to use "complete.obs" or "pairwise.complete.obs" as default in focalCor once a weights matrix is used, but then this creates a deviation from the default for the R base function, which uses "everything", so not sure about this either. This is just to share my thinking about these defaults, but nothing crucial, and as I said, everything already works as I would anticipate! 

Best,

Fabian

**Comment by rhijmans** [comment]
Thanks, very good points. I like the idea of automatically using the weights. In focalCor it would then be up to the user to use a function that can handle weights.  I would just need to make sure that a clear error message is given when that is not the case. 

>  I would also find it intuitive to use "complete.obs" or "pairwise.complete.obs" as default in focalCor once a weights matrix is used,

This is not related to using a weights matrix or not. It is about what to to with NA cells, including virtual cells outside of the raster (if `fillvalue=NA`). But we do not know which function the user will supply as argument `fun`. It could be `cor`, but it could also be something else. So it is not known which additional arguments may or may not be available. And it would be odd to change defaults. I should add using the additional argument to the examples, though.

What I could also do is add some special options for `fun`, e.g. `fun = "pearson"` . That would be equivalent to `cor(x, y, 
 method = "pearson", use="pairwise.complete.obs" )`, and could perhaps be much faster as well. 

The name `focalCor` is perhaps too narrow; as you could also do `fun=\(x, y) mean(x) - mean(y)`). 
It is similar to `focal3D` but there all values (across layers) are combined as a single argument to `fun`.  Perhaps it should be called something like `focalLyrs`.

**Comment by fischer-fjd** [comment]
Yes, sorry, my comment about the "pairwise.complete.obs" was not really on point. To me, renaming focalCor into focalLyrs makes a lot of sense. It explains the underlying layer-by-layer calculation and why one can specify user-defined functions that calculate things other than correlation coefficients. It may also reduce a little bit the need for having a specific default for correlation functions, as it's clear that they are only one of many options. But I really like the idea of having an inbuilt (and faster) "pearson" correlation function that automatically deals with the NA problem.

**Comment by rhijmans** [comment]
I have changed `focalCor` to `focalLyr` and made the detection of weights automatic. There is a built-in function "pearson" that can do both the weighted and unweighted cor coeff.

I have done the same for `focalReg` and built-in function "ols". It is now also possible to supply other functions. That is, `focalLyr` is really "focal pair-wise layers" and `focalReg` is "focal one-to-multiple layers".  

Should we have  `focalLyrPairs` and `focalLyrMulti`? 

Anyway, currently the below appears to work:


```
library(terra)
#terra 1.6.44
r <- rast(system.file("ex/logo.tif", package="terra"))
set.seed(0)
r[[1]] <- flip(r[[1]], "horizontal")
r[[2]] <- flip(r[[2]], "vertical") + init(rast(r,1), runif)
r[[3]] <- init(rast(r,1), runif)

window_circle_nona <- focalMat(r, d = 10,type = "circle", fillNA = FALSE)
ww = window_circle_nona
ww[ww != 0] = 1
x <- focalLyr(r, w = ww, cor)
plot(x)


y <- focalLyr(r, w = ww, cor, use="complete.obs")
plot(y)

y <- focalLyr(r, w = ww, "pearson", na.rm=F)
plot(y)

y <- focalLyr(r, w = ww, "pearson", na.rm=TRUE)
plot(y)


window_circle_na <- focalMat(r, d = 10,type = "circle", fillNA = TRUE)
z <- focalLyr(r, w = window_circle_na, "pearson")
plot(z)

window_circle_na <- focalMat(r, d = 10,type = "circle", fillNA = TRUE)
z <- focalLyr(r, w = window_circle_na, "pearson", na.rm=TRUE)
plot(z)


y2 <- focalReg(r, w =ww, na.rm = T)
plot(y2)

window_gaussian <- focalMat(r, d = 3,type = "Gauss")
x2 <- focalReg(r, w = window_gaussian, na.rm = T)
plot(x2)

window_circle_na <- focalMat(r, d = 10,type = "circle", fillNA = TRUE)
z2 <- focalReg(r, w = window_circle_na, na.rm =T)
plot(z2)
```

**Comment by fischer-fjd** [comment]
Hi Robert, this is great - just tested it, and all the above works as I would imagine it to work - and making the functions more general, also makes a lot of sense. 

One question I had: Does

```
window_gaussian <- focalMat(r, d = 3,type = "Gauss")
x2 <- focalReg(r, w = window_gaussian, na.rm = T)
plot(x2)
```

do the automatic weighting at the moment? 

As for the naming: for conciseness, it could probably work to drop the `Lyr` and simply use something like `focalPairs` (or `focalPairwise`) and `focalMulti`? The only tricky thing is probably to differentiate them from focal3D in terms of naming convention. Another option might be something along the lines of `focal1to1` and `focal1toN` (`focal1toMulti`?). I'm not 100% sure, though, that they make the relationship with focal3D clearer.

**Comment by rhijmans** [comment]
`focalLyr` (formerly `focalCor`) is now called `focalPairs`

**Comment by rhijmans** [comment]
If there are remaining issues/requests, please start a new issue
