### ISSUE TITLE
Potential new feature: buffer width based on a column in SpatVector 

### ISSUE THREAD

**Issue by fischer-fjd** [rspatial/terra#909]
Hi Robert,

this is just an idea for a new feature, so low priority - and feel free to close this if you don't see its relevance. 

In our work (forest ecology), we often come across situations where it would make sense to buffer polygons not by a constant width, but by a width that depends on each polygon's properties. To give an example: To assess competition in a tree's neighborhood, it can make sense to delineate the tree crown as a polygon and then choose a buffer that is related to the crown's radius. In this case, the buffer would be equivalent to shrinking/enlarging each delineated polygon by a factor (which I don't think exists in terra, but correct me if I'm wrong). 

But it could also be that we would want to choose a feature other than the polygon's area (e.g. a tree's trunk diameter, or height), so ideally, what I would be looking for would be a buffer() function where the "width" argument would also accept a column name from the SpatVector. This way, one could create a dedicated buffer column for each object based on its properties. 

As stated, this is not urgent. Also, it's, of course already doable through for loops/apply operations. 

Best,

Fabian

**Comment by rhijmans** [comment]
The "width" argument was already vectorized 

Example data 

```
library(terra)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
pnts <- centroids(v)
pols <- buffer(pnts, 1000)
```

A varying buffer size around points

```
b <- buffer(pnts, 1000 * 1:nrow(pnts))
plot(b)
```

A varying buffer size around polygons (using a variable name)

```
pols$bufsize <- 1000 * 1:12
pb1 <- buffer(pols, pols$bufsize)
plot(pb1)
```

What I have now added, for elegance, is that you can do 

```
pb2 <- buffer(pols, "bufsize")
```

And I have now documented that argument "width" is vectorized.

**Comment by fischer-fjd** [comment]
This is amazing! I had not realized that this was already the case, and thanks a lot for the "elegance feature"!
