### ISSUE TITLE
New check problem (GDAL 3.6.0 ?) interpIDW()

### ISSUE THREAD

**Issue by rsbivand** [rspatial/terra#910]
With GDAL 3.6.0, I'm seeing: 
[00check.log](https://github.com/rspatial/terra/files/10091751/00check.log)

**Comment by rhijmans** [comment]
Thanks very much. That should be fixed now (with 
https://github.com/rspatial/terra/commit/231dcd10cd35e9e455843805d444b93a6aca3a9a)

**Comment by rsbivand** [comment]
I'll try to check tomorrow, thanks!

**Comment by rsbivand** [comment]
Seems to be fixed:
[00check.log](https://github.com/rspatial/terra/files/10095971/00check.log)

**Comment by rhijmans** [comment]
Excellent, thank you for confirming that.
