### ISSUE TITLE
saveRDS, readRDS not handling categorical layers appropriately

### ISSUE THREAD

**Issue by Canderson156** [rspatial/terra#912]
I upgraded to the development version of terra to fix the bugs we identified relating to reading SpatRasters as RDS files. 

I found today I'm getting some new weird behaviours. Hopefully they will be reproduced with the same file I provided before (https://drive.google.com/drive/folders/1w3OxiWh-7sZtx86aMbbAkSDIt_qVhR3J?usp=sharing)

When I try to save as RDS:

> saveRDS(stack_present, "R_objects/stack_present.RDS")
Warning message:
In all(v) : coercing argument of type 'double' to logical

When I read RDS, the names of categorical layers and their level names are all missing:

> stack_present <- readRDS("R_objects/stack_present_test.RDS")
> names(stack_present)
 [1] "value"                  "value"                  "mean_annual_temp"       "mean_temp_warmest_Q"   
 [5] "mean_temp_coldest_Q"    "annual_precip"          "precip_wettest_month"   "precip_driest_month"   
 [9] "precip_seasonality"     "precip_wettest_Q"       "precip_driest_Q"        "precip_warmest_Q"      
[13] "precip_coldest_Q"       "mean_diurnal_range"     "isothermality"          "temp_seasonality"      
[17] "max_temp_warmest_month" "min_temp_coldest_month" "temp_annual_range"      "mean_temp_wettest_Q"   
[21] "mean_temp_driest_Q"     "elevation"              "stdev_elevation"        "d2coast"               
> cats(stack_present$value)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'cats': [subset] you cannot select a layer with a name that is not unique
> levels(stack_present[[1]])
[[1]]
   value value.1
1      0       0
2      1       1
3      2       2
4      3       3
5      4       4
6      5       5
7      6       6
8      7       7
9      8       8
10     9       9
11    10      10
12    11      11
13    12      12
14    13      13
15    14      14
16    15      15
17    16      16
18    17      17
19    18      18
20    19      19
21    20      20
22    21      21
23    22      22
24    23      23

This is what the data looks like before I save and read as an RDS:

> names(stack_present)
 [1] "lc_class"               "substrate"              "mean_annual_temp"       "mean_temp_warmest_Q"   
 [5] "mean_temp_coldest_Q"    "annual_precip"          "precip_wettest_month"   "precip_driest_month"   
 [9] "precip_seasonality"     "precip_wettest_Q"       "precip_driest_Q"        "precip_warmest_Q"      
[13] "precip_coldest_Q"       "mean_diurnal_range"     "isothermality"          "temp_seasonality"      
[17] "max_temp_warmest_month" "min_temp_coldest_month" "temp_annual_range"      "mean_temp_wettest_Q"   
[21] "mean_temp_driest_Q"     "elevation"              "stdev_elevation"        "d2coast"               
> cats(stack_present[[1]])
[[1]]
   value                                      lc_class
1      0                                Not Applicable
2      1                        Cryptogam, herb barren
3      2            Rush/grass, forb, cryptogam tundra
4      3            Cryptogam barren complex (bedrock)
5      4            Prostrate dwarf-shrub, herb tundra
6      5 Graminoid, prostrate dwarf-shrub, forb tundra
7      6    Prostrate/Hemiprostrate dwarf-shrub tundra
8      7    Nontussock sedge, dwarf-shrub, moss tundra
9      8       Tussock-sedge, dwarf-shrub, moss tundra
10     9                      Erect dwarf-shrub tundra
11    10                              Low-shrub tundra
12    11             Missing (Cryprogram dwarf-shrub?)
13    12                     Sedge/grass, moss wetland
14    13              Sedge, moss, dwarf-shrub wetland
15    14                Sedge, moss, low-shrub wetland
16    15                 Noncarbonate mountain complex
17    16                    Carbonate mountain complex
18    17                               Nunatak complex
19    18                                      Glaciers
20    19                                         Water
21    20                                        Lagoon
22    21                              Non-Arctic areas
23    22                                    Tree cover
24    23                             Tree-cover mosaic

**Comment by rhijmans** [comment]
Thank you very much. I should have checked that yesterday. I can now do a round trip: 

```
library(terra)
r <- readRDS("stack_present.RDS")
#terra 1.6.45
x <- saveRDS(r, "test.rds")
z <- readRDS("test.rds")
z
#class       : SpatRaster 
#dimensions  : 614, 741, 24  (nrow, ncol, nlyr)
#resolution  : 5000, 5000  (x, y)
#extent      : 4222903, 7927903, 2358584, 5428584  (xmin, xmax, ymin, ymax)
#coord. ref. : NAD83 / Statistics Canada Lambert 
#source(s)   : memory
#names       : value, value, mean_~_temp, mean_~est_Q, mean_~est_Q, annua~recip, ... 
#min values  :     1,     2,  -27.118614,   -8.145844,  -42.773540,    62.19235, ... 
#max values  :    20,     9,   -1.187054,   12.149782,   -2.280292,   722.37830, ... 

#levels(z)[[1]] |> head()
#  value                                      lc_class
#1     0                                Not Applicable
#2     1                        Cryptogam, herb barren
#3     2            Rush/grass, forb, cryptogam tundra
#4     3            Cryptogam barren complex (bedrock)
#5     4            Prostrate dwarf-shrub, herb tundra
#6     5 Graminoid, prostrate dwarf-shrub, forb tundra
```
