### ISSUE TITLE
merge/mosaic dealing with NaN 

### ISSUE THREAD

**Issue by joaocarr** [rspatial/terra#913]
I have 2 rasters and set zero as NaN using:

NAflag(rast1) <- 0
NAflag(rast2) <- 0

However, when running merg12 <- merge(rast1,rast2) it fails to recognize 0 as NaN and generates this:

![image](https://user-images.githubusercontent.com/62659903/204277474-0dd53482-671d-4ffe-8d5f-9330057d36e5.png)

NAflag(merge12) returns NaN

I'm running terra dev 1.6-46

**Comment by joaocarr** [comment]
This is what I get:

class       : SpatRaster 
dimensions  : 2846, 1750, 10  (nrow, ncol, nlyr)
resolution  : 0.0002245788, 0.0002245788  (x, y)
extent      : 131.3342, 131.7272, -14.70148, -14.06232  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : ALPSRP020786900_Dsk_Cal_C3_VanZyl5_ML1-6_TC.tif 
names       : dbl_060615, vol_060615, sur_060615, hh_060615, hv_060615, vh_060615, ...

**Comment by rhijmans** [comment]
is that `rast1`? What about `rast2`?

**Comment by kadyb** [comment]
@joaocarr, you can test `vrt()` as a workaround and then save the result. This function requires file paths.

**Comment by rhijmans** [comment]
`vrt` would not be a workaround if the goal is to treat zeros as NA. You could do 

```
rast1 <- subst(rast1, 0, NA)
```

Assuming that you want the values that are currently NA to stay NA (that would not be an issue of the current NAflag is NAN)

**Comment by joaocarr** [comment]
It's still not working. Is it because it's stored in memory?

Running the following reproducible code will result in the same issue:

r1 <- rast(xmin = 0,  xmax = 66, ymin = 33, ymax = 99, res = 1, vals = NA) 
r2 <- rast(xmin = 33, xmax = 99, ymax = 66, ymin = 0, res = 1, vals = 2)
mos <- mosaic(r1, r2)

![image](https://user-images.githubusercontent.com/62659903/204491939-1005ce53-2bbc-4bd5-b016-e340ff372967.png)
![image](https://user-images.githubusercontent.com/62659903/204491998-0e853d27-dfad-464d-a01e-1d60f1fb8510.png)
![image](https://user-images.githubusercontent.com/62659903/204492069-a5841ae6-5f43-4ec5-81dc-61ece9dffdde.png)

**Comment by rhijmans** [comment]
OK, thanks, I will have a look

**Comment by rhijmans** [comment]
It appears to work better with more than 2 input rasters. This looks OK

```
mos <- mosaic(r1, r1, r2)
mos <- mosaic(r1, r2, r2)
```

**Comment by joaocarr** [comment]
Agree, works alright when I mosaic with at least 3 rasters

**Comment by rhijmans** [comment]
Thanks. This is fixed now, at least from the `mos <- mosaic(r1, r2)` case, but probably also for the original case.

**Comment by joaocarr** [comment]
Yes, also working alright in the original case
