### ISSUE TITLE
rast() read displays first attribute  not values when there is an esri style sidecar VAT

### ISSUE THREAD

**Issue by nevilamos** [rspatial/terra#915]
---
---
This is  covered in #790 however I thought it was worth posting with a more generic example ( nor relating to histogram).

Create TIF with and without sidecar
```{r}
library(terra)
library(foreign)

r<-rast(matrix(1:2,1,2))
writeRaster(r,"r.tif",datatype="INT1U",overwrite=T)
writeRaster(r,"r1.tif",datatype="INT1U",overwrite=T)

#VAT sidecar with one addtional column
VAT<-data.frame(Value =1:2,V2=c(20,30))
write.dbf(VAT,"r1.tif.vat.dbf")
```
If a Tif has a Value attribute table, the first category are displayed and plotted not the cell values
```{r}
r<-rast("r.tif")
r1<-rast("r1.tif")
plot(r,main="r")
plot(r1,main="r1")
```
Generally it may not be much of an issue, however when reading multiple tifs into a single raster as layers it can get confusing, since the categories are plotted though the values are still there.

```{r}
r.r1<-rast(c("r.tif","r1.tif"))
plot(r.r1)
values(r.r1)
```
Is there any way to use rast() to just read the values regardless of presence of a VAT? as it did in raster.  Wasnt clear to me from https://github.com/rspatial/terra/issues/790#issuecomment-1238416053

**Comment by nevilamos** [comment]
The confusion is particularly apparent when an extract is used
"Extract _values_ from a SpatRaster for a set of locations"
however  extract extracts the categories not the values
```{r}
values(r.r1)
terra::extract(r.r1,c(1,2))
```

**Comment by rhijmans** [comment]
I do not agree with your statement that "extract extracts the categories not the values". That is, the categories *are* the values.  To be able to represent these values we need a coding system (integers stored as cell values and a look-up table to translate them to the actual values. That is also how factors are implemented. 

```
f = factor(letters[1:5])
f[1:2]
#[1] a b
#Levels: a b c d e
as.integer(f[1:2])
#[1] 1 2
```

The "raw" integer values should generally not be of interest. If you need them, I wonder if there is something else that needs to be fixed, so that you don't need them. But I understand there might be cases.  

Right now, you can not avoid reading the categories, but it is easy to get rid of them with

```
levels(x) <- NULL 
``` 

I am inclined to think that this should suffice because it should be in unusual conditions only that you would want to ignore the categories.

`extract<SpatRaster,SpatVector>` has the argument `raw=FALSE` ; but that is currently not available for extracting with cell numbers as in your example.

**Comment by nevilamos** [comment]
In the case where the problem arose the second column of the .tif.vat.dbf was the area of each raster value - I think there may often be cases where  a raster is used that was created in esri software or elsewhere that has mutiple columns in the dbf the "raw" values and then various attributes assocaited with these values, for instace the names of the classes of a landcover represented by the integers, the area of each class etc etc.    In my case I only want the "raw" values. - in fact I am interested in the unique combinations of the raw integers across multiple layers of a multilayer raster - for cells extracted by their cell index
I saw the
```{r}
levels(x) <- NULL 
```
this only seems to work on a single layer raster

I tired it on my r.r1 raster and it did not fix the issue:
> levels(r.r1)<-NULL
> r.r1
class       : SpatRaster 
dimensions  : 1, 2, 2  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0, 2, 0, 1  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
sources     : r.tif  
              r1.tif  
names       : lyr.1, V2 
min values  :     1, 20 
max values  :     2, 30 

Thanks for clarifying that the argument  raw= FALSE does not currently work for extraction with cell numbers - I had also given that a try.

The main reason for this post was as an alert for others who may be moving between esri and R rasters and ecounter this issue if moving from raster::raster() to terra::rast()

Do you intend to make the raw=FALSE argument available for extraction by cell number in terra?

**Comment by kadyb** [comment]
I think if the raster has an value attribute table then it is expected to use the provided categories, not the raw values. As Robert wrote, the easiest way is to remove categories from the raster. For visualization you can do something like this without removing the categories:

```r
plot(as.int(r1)) # convert factor to integer
plot(r1, type = "classes", levels = levels(r1)[[1]][["Value"]])
```

If you don't want `values()` to return raw values, you can use the `dataframe = TRUE` argument:

```r
data.frame(r.r1)
```

**Comment by nevilamos** [comment]
Yes thanks to you both.  
I found that values(r.r1, dataframe = TRUE)  returns the provided catergories for lyaers where they exists as you mention.  this was a surprise and is not mentioned in the documentation. I expected that 
```r
identical(as.data.frame(values(r.r1)),values(r.r1,dataframe=TRUE))
```
would be TRUE.

**Comment by kadyb** [comment]
`as.data.frame(values(r.r1)` - in this case you first return a matrix with raw values and then convert that matrix to data frame
`values(r.r1, dataframe = TRUE)` - here you directly return a data frame with the appropriate datatype (category/factor)

There is this documentation in `values()`, but maybe there is room for improvement:

> By default all values returned are numeric. This is because a vector or matrix can only store one data type, and a SpatRaster may consist of multiple data types. However, with values(x, dataframe=TRUE) and as.data.frame(x) the values returned match the type of each layer, and can be numeric, logical, integer, or factor.

**Comment by rhijmans** [comment]
> In the case where the problem arose the second column of the .tif.vat.dbf was the area of each raster value - I think there may often be cases where a raster is used that was created in esri software or elsewhere that has multiple columns in the dbf the "raw" values and then various attributes associated with these values, 

That is correct. And you can select the variable of interest with `activeCat`. There are degenerate cases where there is only one attribute which is simply the cell count for each unique value, and I try to filter these out, as they are not true categories. 

You should ideally not use `values` or `data.frame` to compute with rasters; at least the design principle of "terra" is that you should not need to do that as it may not be memory safe. In your case, you should be able to use: 

```
unique(x, as.raster=TRUE)   
``` 

Perhaps preceded by `levels(x) <- NULL`. If that does not remove the levels for all layers you probably need to update the "terra" package to its current version (CRAN or github).

**Comment by nevilamos** [comment]
Thanks again
The reason I am using values or extract is because it is often a relatively
small proportion of the raster often non contiguous that I need to
calculate the unique combinations for. So it is faster to just get these
cells by index than doing the entire raster.
