### ISSUE TITLE
Unexpected output from sort()

### ISSUE THREAD

**Issue by jflowernet** [rspatial/terra#921]
My understanding is that the `sort()` function should sort the rasters in a stack according to the sum of cell values? This appears to be the outcome, but the names for each raster layer do not get re-ordered when sort is called, which I would have expected:

``` r
library(terra)
#> terra 1.6.17

#borrowing from the sort() help page
f <- system.file("ex/elev.tif", package="terra")
r <- rast(f)
r <- c(r, r/2, r*2)

#name the raster layers in order
names(r) <- c("one", "two", "three")

plot(r)
```

![](https://i.imgur.com/vf79J4T.png)

``` r

#sorting them re-orders the rasters, but not the names
plot(sort(r))
```

![](https://i.imgur.com/OwDopZv.png)

<sup>Created on 2022-12-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Sorting is done for each cell. There is no consideration of the other cells; nor of a layer-level statistic.
What you are after is something like:

```
g = global(r, mean, na.rm=T)
r[[order(g[,1])]]
#class       : SpatRaster 
#dimensions  : 90, 95, 3  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#sources     : memory  
#              elev.tif  
#              memory  
#names       :   two, one, three 
#min values  :  70.5, 141,   282 
#max values  : 273.5, 547,  1094 
```

**Comment by jflowernet** [comment]
@rhijmans My apologies, that is exactly what I was after. Thanks for your quick response, and for both `raster` and `terra`!
