### ISSUE TITLE
Should it be possible to save / read RDS for a list of SpatRasters?

### ISSUE THREAD

**Issue by Canderson156** [rspatial/terra#924]
Testing with the same SpatRaster as my previous issues:
https://drive.google.com/drive/folders/1w3OxiWh-7sZtx86aMbbAkSDIt_qVhR3J?usp=sharing

I'd like to save a list of SpatRasters. Ultimately I'm working with 17 SpatRasters, and a list seemed like the best way to do this. 

Currently trying to save a list of SpatRasters in an RDS results in the following error:

test <- list(A = stack_present,
              B = stack_present,
              C = stack_present)
 nlyr(test$A)
[1] 24
 
 saveRDS(test, "test.RDS")
 
 test2 <- readRDS("test.RDS")
 nlyr(test2$A)
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address

Is this a bug? or is saving a list of SpatRasters as an RDS unrealistic?

**Comment by rhijmans** [comment]
You can, but you have to `wrap` the SpatRasters before writing and `unwrap` them after reading 

```
saveRDS(lapply(test, wrap),  "test.RDS")
test2 <- readRDS("test.RDS") |> lapply(unwrap)
```
