### ISSUE TITLE
focalMat deletes pixels

### ISSUE THREAD

**Issue by nikosGeography** [rspatial/terra#925]
I am smoothing an image using a `type = Gauss` and then I resample the smoothed image. I noticed that as I increase the sigma in the `focalMat `function the output raster becomes smaller (i.e., the dimensions of the raster are becoming smaller). And that's the situation even if I specify the dimensions of the focal matrix (11x11 or 9x9 etc). Any idea why that might be? Is this normal?

For comparison, when I smooth the image using other packages ([gridkernel ](https://rdrr.io/github/ethanplunkett/gridkernel/man/gaussiansmooth.html)and [spatialEco](https://rdrr.io/cran/spatialEco/man/raster.gaussian.smooth.html)) I do not have that issue.

Below is an example of my problem.

<img width="987" alt="Screenshot 2022-12-01 221916" src="https://user-images.githubusercontent.com/45749751/205172003-d430a3e7-33ac-4a79-a00a-1132efad06a5.png">

You can clearly see the difference.

Here is my code:

```
library(terra)

# focal terra
tirs = rast("path/pop.tif")
ntl = rast("path/ntl.tif")

# fill null values
tirs = focal(tirs,
             w = 9,
             fun = mean,
             na.policy = "only",
             na.rm = TRUE)

# # check if raster has null values
# freq(is.na(r))

for (i in seq(from = 0.1, to = 2, by = 0.1)) {
  
  gf <- focalMat(tirs, i*400, "Gauss", 11)
  r_gf <- focal(tirs, w = gf)
  
  r_gf = resample(r_gf, ntl, method = "bilinear")
  
  stringedi = gsub("\\.", "", toString(format(i, nsmall = 2)))
  
  writeRaster(r_gf, 
              paste0("C:/Users/nikos/OneDrive/Desktop/psf/tirs", 
                                  stringedi, ".tif"))
}
```

And here are my rasters:
```
tirs = rast(ncols=407, nrows=343, nlyrs=1, xmin=509615.9028, xmax=550315.9028, ymin=161743.6035, ymax=196043.6035, names=c('pop'), crs='EPSG:27700')

ntl = rast(ncols=101, nrows=84, nlyrs=1, xmin=509634.6325, xmax=550034.6325, ymin=161998.158, ymax=195598.158, names=c('ntl'), crs='EPSG:27700')
```

**Comment by rhijmans** [comment]
Please include a self-contained minimal reproducible example when reporting that something does not work (as in the help files), That is, include some example data generated by code, and keep things simple (no loop, no additional manipulation like resample). You are also not showing that your conclusion ("deletes pixels") is correct. 

So I am in the dark here but I am assuming that what you see is NA values at the edges, but that is expected. See arguments `na.policy` and `fillvalue`
