### ISSUE TITLE
vect() fails when sf has no fields

### ISSUE THREAD

**Issue by BadgerOnABike** [rspatial/terra#93]
If an object is read in but has no fields (example attached) vect() is unable to parse. This can be fixed by assigning an arbitrary field. I have only encountered this with geopackages as shapefiles generate an FID making this scenario impossible.

```
aoi_poly <- st_read(dsn = "aoi.gpkg",
                              layer = "aoi_poly")
vect(aoi_poly)
```

Error received.
`Error in .subset2(x, i, exact = exact) : subscript out of bounds`

No issues after naming.

```
aoi_poly$name <- "nothingmatters"
vect(aoi_poly)
```

[aoi.zip](https://github.com/rspatial/terra/files/5320053/aoi.zip)

**Comment by rhijmans** [comment]
Thank you, this has been fixed.
