### ISSUE TITLE
Residuals of the focalReg

### ISSUE THREAD

**Issue by nikosGeography** [rspatial/terra#930]
Hi, I am trying to perform a `focalReg`. Using the built-in example:

```
r <- rast(ncols=10, nrows=10, ext(0, 10, 0, 10))
values(r) <- 1:ncell(r)
x <- c(r, init(r, runif) * r)
f <- focalReg(x, 3)
```

the output is a raster stack of the coefficients (_intercept_ and _slope_). I was wondering if there a way to include the _residuals_ as well. Hopefully this isn't a silly question.

**Comment by rhijmans** [comment]
Great question. I have made `focalReg` more flexible such that you can provide your own function. But that is not fully developed yet. 

The idea is that you could do 

```
library(terra)
r <- rast(ncols=10, nrows=10, ext(0, 10, 0, 10))
values(r) <- 1:ncell(r)
x <- c(r, init(r, runif) * r)

fres <- function(x, y) residuals(glm(y~.))

f <- focalReg(x, 3, fres)
```

But that currently fails. I will make this work, but I probably won't get to it until next week.

**Comment by nikosGeography** [comment]
No problem. Happy that my question was helpful.

**Comment by bobilong** [comment]
Did the residuals was fixed? And the p value?

**Comment by rhijmans** [comment]
Thanks, it was almost there, but it now seems to work. 

```
library(terra)
#terra 1.7.73
r <- rast(ncols=10, nrows=10, ext(0, 10, 0, 10))
values(r) <- 1:ncell(r)
x <- c(r, init(r, runif) * r)
fun = \(x, y) coefficients(lm(y~x))
 
f <- focalReg(x, 3, fun=fun)
f
#class       : SpatRaster 
#dimensions  : 10, 10, 2  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0, 10, 0, 10  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84) 
#source(s)   : memory
#names       : (Intercept),          x 
#min values  :  -0.3170137, -0.4094115 
#max values  : 112.7379157,  1.5862550 
```

**Comment by bobilong** [comment]
![image](https://github.com/rspatial/terra/assets/40789620/e34d1ce1-5f9a-427d-a09e-26edb54773a2)
I update the version of package, but still failed. object 'outnl' not found

**Comment by bobilong** [comment]
> ![image](https://private-user-images.githubusercontent.com/40789620/305700323-e34d1ce1-5f9a-427d-a09e-26edb54773a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDMwMzUsIm5iZiI6MTcwODMwMjczNSwicGF0aCI6Ii80MDc4OTYyMC8zMDU3MDAzMjMtZTM0ZDFjZTEtNWY5YS00MjdkLWEwOWUtMjZlZGI1NDc3M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAwMzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmZjNzM1NDdlMGFiZDFlZGJhZGRlZWQwMTJhNTNjOTFmNGEyN2NhMTdhY2NlYTM1NjQxNTQ1Y2YzOTQzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.do9wejoxm0PPh32ArAp0DmO64S4aTf2naawVTN8-2bw) I update the version of package, but still failed. object 'outnl' not found

Thanks for your work! I also update the version of R, and the focalReg is work.
