### ISSUE TITLE
Suggestion: makeTiles() using only rows and columns

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#931]
How about yet another option to use only a number of columns and rows to make tiles? A way without specifically creating/using another SpatRaster with a lower resolution? 
Something like: 
makeTIles(x, c(nx,ny), ...) where:
"nx" is a number of columns
"ny" is a number of rows

_Originally posted by @Rapsodia86 in https://github.com/rspatial/terra/issues/920#issuecomment-1335972230_

**Comment by kadyb** [comment]
If anyone is looking for this functionality, it is implemented in `{stars}`. See the example in [st_tile()](https://r-spatial.github.io/stars/reference/st_tile.html) function.

**Comment by Rapsodia86** [comment]
Ok, thanks for the information!

**Comment by rhijmans** [comment]
Thanks. It was already relatively easy to do like this

```
y <- aggregate(rast(x), c(nx,ny))
makeTIles(x, y, ...)
```

But now you can use the more elegant:

```
makeTIles(x, c(nx,ny), ...)
```

**Comment by Rapsodia86** [comment]
Thank you!
