### ISSUE TITLE
Buffer/expanse when crs is not defined

### ISSUE THREAD

**Issue by fischer-fjd** [rspatial/terra#932]
Hi Robert,

not a big/urgent point, but I noticed a slight inconsistency between buffer/expanse when the crs of a SpatVector is not set:

```
# sample vector
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
(expanse(v)) # works
(buffer(v, 50)) # works

# now without crs
crs(v) = NA
(expanse(v)) # works, but yields different results and gives out warning (good)
(buffer(v, 50)) # does not work 
```

I would find it more intuitive (and helpful) if buffer worked just like expanse, i.e. it would add a buffer even when the crs is not defined, but throw the same warning as expanse(). 

We work a lot with airborne lidar-derived rasters (typically with a UTM crs), and sometimes the crs is not set within the original data and has to be supplied later. From a processing perspective, it would be practical to still be able to add buffers to delineated features, even when the crs is not (yet) set. 

Best,

Fabian

**Comment by rhijmans** [comment]
Thanks, implemented as suggested.
