### ISSUE TITLE
mosaic: issue to make a 3x3 square

### ISSUE THREAD

**Issue by mgageo** [rspatial/terra#938]
I want to make a 3x3 square from 9 small squares. I use mosaic to add one by one the 8 small squares to the first small square. At the end the big square has only 5 small squares.
``` r
  library(terra)
#> terra 1.6.41
  par(mfrow=c(3, 3))
  i <- 0
  for (x in 357:359) {
    for (y in 6848:6850) {
      i <- i + 1
      sr <- rast(nrows = 10, ncols = 10, xmin = x * 1000, xmax = (x + 1) * 1000, ymin = y * 1000, ymax = (y + 1) * 1000)
      values(sr) <- i
      if (i == 1) {
        srs <- sr
      } else {
        srs <- mosaic(srs, sr)
      }
      plot(srs)
    }
  }
```

![](https://i.imgur.com/xsh6zEX.png)

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kadyb** [comment]
This code will work if you add blocks to the list and then create SpatRasterCollection, but I don't know why it doesn't work in a loop.

```r
i <- 0
list <- vector("list", 9)
for (x in 357:359) {
  for (y in 6848:6850) {
    i <- i + 1
    sr <- rast(nrows = 10, ncols = 10, xmin = x * 1000, xmax = (x + 1) * 1000, ymin = y * 1000, ymax = (y + 1) * 1000)
    values(sr) <- i
    list[[i]] <- sr
  }
}
r <- sprc(list)
r <- mosaic(r)
plot(r)
```

**Comment by kadyb** [comment]
Your code works fine in terra 1.6.47 (on CRAN).

**Comment by mgageo** [comment]
Thank you for your answers.
I have updated the package and it works perfectly even on my real data.
