### ISSUE TITLE
Incompatible netcdf formatting between terra and raster and constant crashes with multilayer rasters

### ISSUE THREAD

**Issue by fabeit** [rspatial/terra#94]
A RasterBrick netcdf file created by raster writeRaster cannot be imported using terra as it leads to the following message.

Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: dimension #0 (z) is not a Time or Vertical dimension.

And also the opposite does not work, a Raststack written to file cannot be opened with brick()
Warning messages:
1: In .varName(nc, varname, warn = warn) : varname used is: Band1
If that is not correct, you can set it to one of: Band1, Band2, Band3, Band4, Band5, Band6, Band7, Band8, Band9, Band10, Band11, Band12, Band13
2: In .getCRSfromGridMap4(atts) : cannot process these parts of the CRS:
long_name=CRS definition
spatial_ref=GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]
GeoTransform=-180 2 0 90 0 -2 
3: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
  Discarded datum unknown in CRS definition
4: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
  Discarded datum unknown in CRS definition

I am also forced to use terraOptions(todisk=TRUE) to avoid R crashing when working with rastbricks, the same code doesn't have any problems with the raster package. I think terra is not yet there for working with these kind of data structures and netcdf. I just end up transforming all the rasters in data frames or matrix to avoid these crashes.

**Comment by rhijmans** [comment]
netcdf writing by `raster` is very basic, perhaps best avoided. But that is not a terra issue. It would be useful have an example ncdf file and terra code that crashes.

**Comment by rhijmans** [comment]
These warnings can be ignored, I think:
```
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: dimension #0 (z) is not a Time or Vertical dimension.
```

Closing this now, but would happily look at a specific example.
