### ISSUE TITLE
terra vs raster for huge raster

### ISSUE THREAD

**Issue by HassanMasoomi** [rspatial/terra#942]
I have a huge raster of 45600 * 81600 (~5GB). (PS: my computer has a 256GB memory)

1- I tried to use `app()` function to apply an `approxfun()` to all cells (`app(my_rast, fun = rescale_fnc)`), but I am getting this error: "Error in matrix(v, ncol = nlyr(x)) : data is too long". But, when I changed everything to raster library equivalent it worked fine, fast, and with no error (`rast(raster::calc(raster::raster(my_rast), fun = rescale_fnc))`). 

2- Also, the command below, terra fails while it's a piece of cake in raster:
`perc_breaks <- global(my_rast, fun = quantile, probs = seq(0, 1, 0.01), na.rm = TRUE)`
`perc_breaks <- raster::quantile(raster::raster(my_rast), probs = seq(0, 1, 0.01), na.rm = TRUE)`

3- Regarding terra vs raster, also the `mosaic()` function in terra fails if you have a large number of rasters (~3k) with large sizes (in total ~6GB), while it's easily done in raster package with the same function.

**Note: (1) worked in terra version 1.5.17 but not version 1.6.7; (2) failed in both; didn't check (3) in version 1.5.17**

**Comment by kadyb** [comment]
Regarding 3, the performance of `mosaic()` has been improved in terra 1.6.41 (https://github.com/rspatial/terra/issues/577).

**Comment by HassanMasoomi** [comment]
Thanks, @kadyb. I checked (3) using terra v1.6.47 and I can confirm that it worked and the process time was less than that of raster with a factor of 5.

But, now, the final saved file using terra is ~5 times larger than the one saved with raster library (30GB VS 5GB)?!!

**Comment by kadyb** [comment]
> But, now, the final saved file using terra is ~5 times larger than the one saved with raster library (30GB VS 5GB)?!!

I don't see this problem. Maybe you are using different datatypes (integer vs float) or different types of compression?

```r
## terra
x <- rast(xmin=-110, xmax=-60, ymin=40, ymax=70, res=0.01, vals=1)
y <- rast(xmin=-95, xmax=-45, ymax=60, ymin=30, res=0.01, vals=2)
z <- rast(xmin=-80, xmax=-30, ymax=50, ymin=20, res=0.01, vals=3)

m1 <- mosaic(x, y, z, fun=mean)
writeRaster(m1, "test_terra.tif")
file.size("test_terra.tif") #> 6034724

## raster
x <- raster(xmn=-110, xmx=-60, ymn=40, ymx=70, resolution=0.01, vals=1)
y <- raster(xmn=-95, xmx=-45, ymx=60, ymn=30, resolution=0.01, vals=2)
z <- raster(xmn=-80, xmx=-30, ymx=50, ymn=20, resolution=0.01, vals=3)

m2 <- mosaic(x, y, z, fun=mean)
writeRaster(m2, "test_raster.tif")
file.size("test_raster.tif") #> 6044751
```

**Comment by rhijmans** [comment]
Thank you for your feedback. To be able to respond, I would need more details. And please raise one topic per issue (not three as in this case). 

For example, with 

```
app(my_rast, fun = rescale_fnc)
```
You need to `show(my_rast)` and show `rescale_fnc` as well. 

I do not understand this comparison as they are very different things:

```
perc_breaks <- global(my_rast, fun = quantile, probs = seq(0, 1, 0.01), na.rm = TRUE)
perc_breaks <- raster::quantile(raster::raster(my_rast), probs = seq(0, 1, 0.01), na.rm = TRUE)
``` 

The equivalent would be, I think: 

```
tbreaks <- terra::quantile(my_rast, probs = seq(0, 1, 0.01), na.rm = TRUE)
rbreaks <- raster::quantile(raster::raster(my_rast), probs = seq(0, 1, 0.01), na.rm = TRUE)
``` 

So I will close this issue but please do open new issues if you are still encountering bugs.

**Comment by rhijmans** [comment]
P.S.: if something does not work, always first try with the CRAN version, or, better still, with the development version of "terra"
