### ISSUE TITLE
installation in opensuse leap fails

### ISSUE THREAD

**Issue by fvalenduc** [rspatial/terra#945]
When I try to install the terra package in opensuse leap 15.4, configuration fails with this error:

checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... terminate called after throwing an instance of 'H5::DataSpaceIException'
./configure: line 3668: 14577 Aborted                 (core dumped) ./gdal_proj
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘terra’
* removing ‘/usr/lib64/R/library/terra’

Any idea on how to solve this ?
Thanks for your help.

**Comment by rhijmans** [comment]
My guess would be that you have multiple versions of the PROJ library.

**Comment by fvalenduc** [comment]
I indeed had libproj19 and libproj25 installed simultaneously. I removed libproj19. However, it still fails with the same error.

Any further ideas ?

**Comment by rhijmans** [comment]
Closing because of a lack of activity
