### ISSUE TITLE
Feature Request: na.rm option for extract(..., bilinear = TRUE)?

### ISSUE THREAD

**Issue by kendonB** [rspatial/terra#95]
It would be good to have the ability to keep data from around the edges of a raster - having a na.rm option for extract would enable the goal.

**Comment by rhijmans** [comment]
Thank you. `NA`s are now removed. There is no option --- as I do not think `na.rm=FALSE` makes much sense here.  The algorithm is a but clumsy, I need to revisit that some day; but it appears to work.
