### ISSUE TITLE
Layer names are lost after a merge

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/terra#951]
With `terra` b2639f03cc00dd4f883a9aa1a5c68fe7493cf7e0:

```R
> r1 = terra::rast(xmin = 0, xmax = 1); r1$x = 1; r1$y = 2
> r2 = terra::rast(xmin = 1, xmax = 2); r2$x = 3; r2$y = 4
> names(terra::merge(r1, r2))
[1] "lyr1" "lyr2"
```

This is a regression from a previous version. I really think you should add tests, even if all you do is add a test for each new bug you fix, rather than also going back and adding tests for features that currently work. This is a complicated library and regressions seem to happen reasonably often.

**Comment by rhijmans** [comment]
Thanks, fixed, test added,  and I agree that I should do that more often.

**Comment by Kodiologist** [comment]
Cool, thank you. I didn't notice that tests already existed because I was looking in the mostly empty `tests` instead of `inst/tinytest`.
