### ISSUE TITLE
Allow wrap to wrap sds objects

### ISSUE THREAD

**Issue by jscamac** [rspatial/terra#954]
Hi Rob,
I was wondering if we could expand `wrap` and `unwrap` to accept `SpatRasterDataset` objects.
Currently it only allows `SpatVect` and `SpatRaster` objects.

**Comment by rhijmans** [comment]
I have now implemented that for both SpatRasterDataset and SpatRasterCollection.. Thank you for the suggestion and sorry for taking so long.
