### ISSUE TITLE
`method` argument in `extract()` not working?

### ISSUE THREAD

**Issue by Robinlovelace** [rspatial/terra#956]
Split out from #46, seems like a separate issue. Reprex from there below...

``` r
remotes::install_github("rspatial/terra")
#> Skipping install of 'terra' from a github remote, the SHA1 (dfe4edd7) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(terra)
#> terra 1.6.49
r <- rast(ncol=5, nrow=5, xmin=0, xmax=5, ymin=0, ymax=5)
values(r) <- 1:25
xy <- rbind(c(0.7,0.7), c(2.2,2.2))
p <- vect(xy, crs="+proj=longlat +datum=WGS84")
plot(r); plot(p, add = TRUE)
```

![](https://i.imgur.com/kDGchED.png)

``` r

extract(r, xy, method = "bilinear")
#> Error in .local(x, y, ...): unused argument (method = "bilinear")
extract(r, xy, method = "simple")
#> Error in .local(x, y, ...): unused argument (method = "simple")
```

<sup>Created on 2022-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
And that is consistent with the manual; but perhaps not desirable. At some point, I removed the ellipses to have a simple interface for a matrix and keep the much richer interface for extraction with SpatVector. But I think I could add the "method" argument to the `extract<SpatRaster,matrix>` method.

**Comment by Robinlovelace** [comment]
> But I think I could add the "method" argument to the `extract<SpatRaster,matrix>` method.

Sounds reasonable. That would solve https://github.com/ropensci/slopes/issues/48 I believe.

**Comment by rhijmans** [comment]
Your example now works.

**Comment by Robinlovelace** [comment]
Many thanks!
