### ISSUE TITLE
error clusterR - serializable SpatRaster 

### ISSUE THREAD

**Issue by acocac** [rspatial/terra#96]
Wondered if you're considering to make the SpatRaster serializable, I've tried to run the ClusterR in combination with a SpatRaster object however it seems it doesn't work.

`Error in (function (classes, fdef, mtable)  (tests.R#307): unable to find an inherited method for function ‘nlayers’ for signature ‘"SpatRaster"’
Show stack trace
`
It would be great to make this particular object parallelize, in particular for prediction operations!

**Comment by rhijmans** [comment]
I do not think there will be a `clusterR` equivalent in `terra`. As most functions are implemented in C++ the clustering should happen there (and it will, eventually; as the facilities for doing this are more accessible in newer versions of C++ --- beyond where R is, at is this point). For R level clustering I am thinking of adding arguments like `nodes` in `app` (and this could become an environment setting). Predict does not have that, but you can provide a serialized predict function to the `fun` argument in `terra::predict`. Perhaps that is the preferable approach.

**Comment by acocac** [comment]
@rhijmans, thanks... I'll then try the preferable approach. It would be great to place an example of it at the documentation of the package. Congrats for the contribution with terra and luna packages, I just got noticed of it at the CGIAR Big Data convention! cheers

**Comment by rhijmans** [comment]
Here is an example of parallelization with `terra::predict`


Example data
```
logo <- rast(system.file("ex/logo.tif", package="terra"))   
names(logo) <- c("red", "green", "blue")
p <- matrix(c(48, 48, 48, 53, 50, 46, 54, 70, 84, 85, 74, 84, 95, 85,  66, 42, 26, 4, 19, 17, 7, 14, 26, 29, 39, 45, 51, 56, 46, 38, 31,    22, 34, 60, 70, 73, 63, 46, 43, 28), ncol=2)
a <- matrix(c(22, 33, 64, 85, 92, 94, 59, 27, 30, 64, 60, 33, 31, 9,  99, 67, 15, 5, 4, 30, 8, 37, 42, 27, 19, 69, 60, 73, 3, 5, 21,  37, 52, 70, 74, 9, 13, 4, 17, 47), ncol=2)
xy <- rbind(cbind(1, p), cbind(0, a))
e <- extract(logo, xy[,2:3])
v <- data.frame(cbind(pa=xy[,1], e[,-1]))
```

Model and standard predict 

```
model <- glm(formula=pa~., data=v)
r <- predict(logo, model)
```

Write a parallel predict function  (this is a quick example, I might refine it over time, or suggestions welcome)

```
library(foreach)
library(doSNOW)
library(itertools)

cl <- makeCluster(2)
registerDoSNOW(cl)  
num_splits = 10

predfun <- function(x, ...) {
	foreach(d=isplitRows(x, chunks=num_splits),
          .combine=c, .packages=c("stats")) %dopar% {
				predict(fit, newdata=d)
			}
}
``` 

Now use that function instead 

```
p <- predict(logo, model, predict=predfun)
```
```

**Comment by rhijmans** [comment]
You can now also do (with the example data above) 

`x <- predict(logo, model, cores=2)
`

**Comment by rhijmans** [comment]
Also see https://github.com/rspatial/terra/issues/36

**Comment by acocac** [comment]
Robert, awesome! thanks for sharing the example.

**Comment by rhijmans** [comment]
Also see https://github.com/rspatial/terra/issues/178
