### ISSUE TITLE
Terra predict makes predictions to cells with NA if na.rm=FALSE

### ISSUE THREAD

**Issue by ailich** [rspatial/terra#968]
`terra::predict` is making predictions in areas where there is no data available when `na.rm=FALSE` and then throws a warning saying there are issues with the matrix dimensions when plotting. `terra::predict` defaults to `na.rm=FALSE` and gives incorrect results with `NA`'s present, whereas `raster::predict` defaults to `na.rm=TRUE` and will throw an error if this is changed to be `na.rm=FALSE`

``` r
library(caret)
library(ranger)
library(terra)
#> terra 1.6.47
library(raster)
#> Loading required package: sp

data(iris)
m_train<- train(Species ~ ., data=iris, metric="Kappa", method="ranger", num.trees=1000, tuneGrid = data.frame(mtry=c(2,3), min.node.size=1, splitrule="gini"), keep.inbag = TRUE, scale.permutation.importance = FALSE, importance= "permutation", local.importance = TRUE, trControl=trainControl(method="cv", number = 5, classProbs = TRUE))

iris_terra<- terra::rast(nrow=100, ncol=100, nlyr=4)
names(iris_terra)<- names(iris)[1:4]

set.seed(5)
for (i in seq_along(names(iris_terra))) {
  values(iris_terra[[i]])<- rnorm(n = ncell(iris_terra), mean = mean(iris[,i]), sd= sd(iris[,i]))
  values(iris_terra[[i]])[1:1000]<- NA
}
iris_raster<- stack(iris_terra)
plot(is.na(iris_terra))
```

![](https://i.imgur.com/mRsuPaA.png)

``` r

y_terra<- terra::predict(iris_terra, m_train) # default is na.rm=FALSE
plot(y_terra)
#> Warning in matrix(z, nrow = nrow(x), ncol = ncol(x), byrow = TRUE): data length
#> differs from size of matrix: [9000 != 100 x 100]
plot(iris_terra[[1]], add=TRUE, col=grey.colors(100))
```

![](https://i.imgur.com/yd4Joi2.png)

``` r

y2_terra<- terra::predict(iris_terra, m_train, na.rm=TRUE)
plot(y2_terra)
plot(iris_terra[[1]], add=TRUE, col=grey.colors(100))
```

![](https://i.imgur.com/6SqM21n.png)

``` r

y_raster<- raster::predict(iris_raster, m_train) # default is na.rm=TRUE
plot(y_raster)
plot(iris_raster[[1]], add=TRUE, col=grey.colors(100))
```

![](https://i.imgur.com/oYRpciq.png)

``` r

y2_raster<- raster::predict(iris_raster, m_train, na.rm=FALSE)
#> Error in v[cells, ] <- predv: number of items to replace is not a multiple of replacement length
```

<sup>Created on 2023-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Hi Alex,

The underlying issue is a bug in `predict.ranger`. When the predictors are `NA`, nothing is returned (see below). `NA` should be returned in those cases.  This may be intentional, but if that is the case, then there clearly is a bug in the intention, because this breaks one of the most fundamental rules of R. There does not seem to be an argument in `predict.ranger` to fix this.
 
```
library(caret)
library(ranger)
data(iris)
m <- train(Species ~ ., data=iris, metric="Kappa", method="ranger", num.trees=1000, tuneGrid = data.frame(mtry=c(2,3), min.node.size=1, splitrule="gini"), keep.inbag = TRUE, scale.permutation.importance = FALSE, importance= "permutation", local.importance = TRUE, trControl=trainControl(method="cv", number = 5, classProbs = TRUE))

x <- iris[1:10,]
predict(m, x) |> length()
#[1] 10

### this is a bug 
x[1:5, ] <- NA
predict(m, x) |> length()
#[1] 5
```

In this case `terra::predict` did not catch that; and I have added an additional test for this. I now get: 

```
library(terra)
library(caret)
library(ranger)
data(iris)

m <- train(Species ~ ., data=iris, metric="Kappa", method="ranger", num.trees=1000, tuneGrid = data.frame(mtry=c(2,3), min.node.size=1, splitrule="gini"), keep.inbag = TRUE, scale.permutation.importance = FALSE, importance= "permutation", local.importance = TRUE, trControl=trainControl(method="cv", number = 5, classProbs = TRUE))

iris_terra<- terra::rast(nrow=100, ncol=100, nlyr=4)
names(iris_terra)<- names(iris)[1:4]
set.seed(5)
for (i in seq_along(names(iris_terra))) {
  values(iris_terra[[i]])<- rnorm(n = ncell(iris_terra), mean = mean(iris[,i]), sd= sd(iris[,i]))
  values(iris_terra[[i]])[1:1000]<- NA
}

y <- terra::predict(iris_terra, m) 
#Error: [predict] the number of values returned by the predict function does not match the input. Try na.rm=TRUE?
z <- terra::predict(iris_terra, m, na.rm=TRUE) 
```

**Comment by ailich** [comment]
Thanks for the fix! I think it actually may be a `caret` rather than a `ranger` issue though as I can reproduce the issue using other methods if the model was fit using `caret`, but not if I use the actual package for the method. `predict.ranger` though does not seem to have a built in way to handle `NA`'s which leads to an error, which is better than a wrong result but not as good as if it just returned a vector of the correct length containing `NA` where appropriate.

``` r
library(caret)
#> Warning: package 'caret' was built under R version 4.2.2
#> Loading required package: ggplot2
#> Loading required package: lattice
library(ranger)
#> Warning: package 'ranger' was built under R version 4.2.2
library(randomForest)
#> randomForest 4.7-1.1
#> Type rfNews() to see new features/changes/bug fixes.
#> 
#> Attaching package: 'randomForest'
#> The following object is masked from 'package:ranger':
#> 
#>     importance
#> The following object is masked from 'package:ggplot2':
#> 
#>     margin
library(MASS)


data(iris)


caret_ranger<- train(Species ~ ., data=iris, metric="Kappa", method="ranger", num.trees=1000, tuneGrid = data.frame(mtry=c(2,3), min.node.size=1, splitrule="gini"), trControl=trainControl(method="cv", number = 5)) #ranger

caret_rf <- train(Species ~ ., data=iris, metric="Kappa", method="rf", ntree=1000, tuneGrid = data.frame(mtry=c(2,3)), trControl=trainControl(method="cv", number = 5)) #randomForest

caret_lda <- train(Species ~ ., data=iris, method="lda", trControl=trainControl(method="cv", number = 5)) #MASS

ranger_model<- ranger(Species ~., data=iris)
rf_model<- randomForest(Species ~., data=iris)
lda_model<- lda(Species ~., data=iris)

x <- iris[1:10,]
x[1:5, ] <- NA

predict(caret_ranger, x) |> length()
#> [1] 5
predict(caret_rf, x) |> length()
#> [1] 5
predict(caret_lda, x) |> length()
#> [1] 5


predict(rf_model, x) |> length()
#> [1] 10
predict(lda_model, x)$posterior |> nrow()
#> Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning Inf
#> Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning Inf

#> Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning Inf

#> Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning Inf

#> Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning Inf
#> [1] 10
predict(ranger_model, x)
#> Error: Missing data in columns: Sepal.Length, Sepal.Width, Petal.Length, Petal.Width.
```

<sup>Created on 2023-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Yes, it makes sense that the problem is with "caret". Apparently, it solves a problem by removing the NA's when fitting a model but then makes things worse by also removing them when predicting.

The randomForest package has the same issue that it fails on NA input data when fitting a model, but that is, indeed, not as bad as `predict` not returning values for all cases.

**Comment by brownag** [comment]
Hello!

FYI since the fix for this in https://github.com/rspatial/terra/commit/4e6b9e8274e7e918dc4143b7a9b7fbb8c150dc40 I encountered some cases where regular "ranger" model prediction was failing (no "caret" involved). Could this be the result of extra data elements returned from `predict.ranger()`?

The following works without issue in CRAN version and current version from GitHub

``` r
library(terra)

data(meuse, package = "sp")
data(meuse.grid, package = "sp")

predictors <- rast(meuse.grid, crs = "EPSG:28992")
samples <- vect(meuse, geom = c("x", "y"), crs = "EPSG:28992")

m <- ranger::ranger(om ~ dist + soil, data = as.data.frame(samples[!is.na(samples$om),]))

mypredict <- function(model, data, ...) {
  data$soil <- factor(data$soil, levels = 1:3)
  predict(model, data, ...)$predictions
}

p1 <- predict(predictors, m, fun = mypredict, na.rm = TRUE)
i1 <- interpolate(predictors, m, fun = mypredict, na.rm = TRUE)

plot(p1)
```

![](https://i.imgur.com/z0Si7k7.png)

However, now on 1.6.51 I get warnings + error with the following (note result of `mypredict2()` no `$predictions`)

```r
mypredict2 <- function(model, data, ...) {
  data$soil <- factor(data$soil, levels = 1:3)
  predict(model, data, ...)
}

p2 <- predict(predictors, m, fun = mypredict2, na.rm = TRUE)
#> Warning in lapply(r, as.numeric): NAs introduced by coercion
#> Warning in lapply(r, as.numeric): NAs introduced by coercion
#> Error: [predict] the number of values returned by the predict function does not match the input.

i2 <- interpolate(predictors, m, fun = mypredict2, na.rm = TRUE)
#> Warning in lapply(r, as.numeric): NAs introduced by coercion
#> Warning in lapply(r, as.numeric): NAs introduced by coercion
#> Error: [writeValues] incorrect number of values (too few) for writing
```

Whereas with 1.6.47 just the warnings and the following result: 

``` r
plot(p2)
```

![](https://i.imgur.com/SVO2iuX.png)

**Comment by rhijmans** [comment]
Thanks @brownag . That indeed was because a newly introduced bug, and it now works again as before. 

I am not sure if this is desirable though. It seems to me that it would be better if `terra::predict` would drop the other variables as they are constants and not predicted values. They are dropped when you use  `as.data.frame` on the output of `predict.ranger`; and I think it makes sense to make use of that. 

I also notice that "treetype" is a character output and that could be handled better as well (as a factor), but I am not sure if it is worth the effort here, because I think it should be removed anyway.

Would you agree?

**Comment by brownag** [comment]
> Thanks @brownag . That indeed was because a newly introduced bug, and it now works again as before.
> 
> I am not sure if this is desirable though. It seems to me that it would be better if `terra::predict` would drop the other variables as they are constants and not predicted values. They are dropped when you use `as.data.frame` on the output of `predict.ranger`; and I think it makes sense to make use of that.
> 
> I also notice that "treetype" is a character output and that could be handled better as well (as a factor), but I am not sure if it is worth the effort here, because I think it should be removed anyway.
> 
> Would you agree?

Great! I thought there might have been a bug in there somewhere... but do agree that those extra outputs are not desirable! I also saw the issue with "treetype" too--I don't think the extra effort to handle it as a factor is warranted.

**Comment by rhijmans** [comment]
@brownag: this is now implemented. You now only get a layer with the actual predictions. I also note that you can do 

```
p3 <- predict(predictors, m, na.rm = TRUE)
``` 

That is, there seems to be no need for a custom predict function.

**Comment by brownag** [comment]
Excellent!

> there seems to be no need for a custom predict function.

Yes, you are right, I think that might just be a holdover from me comparing result with a different model i.e. `lm()` :

```r
m <- lm(om ~ dist + soil, data = as.data.frame(samples[!is.na(samples$om),]))
p1 <- predict(predictors, m,  na.rm = TRUE)
#> Error: variable 'soil' was fitted with type "factor" but type "numeric" was supplied
#> In addition: Warning message:
#> In model.frame.default(Terms, newdata, na.action = na.action, xlev = object$xlevels): variable 'soil' is not a factor
  ```

**Comment by rhijmans** [comment]
In that case you can do

```
levels(predictors$soil) <- data.frame(value=1:3, label=1:3)
p1 <- predict(predictors, m,  na.rm = TRUE)
```
