### ISSUE TITLE
Cannot install terra (R4.2.1) cannot find proj6 files

### ISSUE THREAD

**Issue by whositwhatnow** [rspatial/terra#971]
CentOS7, R 4.2.1, proj 6.0.0 installing terra via cran

I am gettting error:

Content type 'text/plain' length 751389 bytes (733 KB)
==================================================
downloaded 733 KB

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /cm/shared/apps/gdal/3.5.1/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.5.1
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /cm/shared/apps/gdal/3.5.1/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.5.1
checking for proj.h... no
checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.

system does not have proj 4.8 installed from yum repo.  I have compiled and install proj6.  

Using this syntax to install terra but its not working:

install.packages("terra", configure.args = c("--with-proj-include=/cm/shared/apps/proj6/6.0.0/include/", "--with-proj-lib=/cm/shared/apps/proj6/6.0.0/lib/"))

**Comment by rhijmans** [comment]
And you are sure that `proj_api.h ` is in the "with-proj-include=" folder (I think that is where it should be)?

**Comment by whositwhatnow** [comment]
yes 

 cd /cm/shared/apps/proj6/6.0.0/include/

drwxr-xr-x. 3 root root   205 Jan  6 13:41 .
drwxr-xr-x. 6 root root    76 Aug  4 12:35 ..
-rw-r--r--. 1 root root 44277 Jan  6 13:41 geodesic.h
-rw-r--r--. 1 root root  2960 Jan  6 13:41 org_proj4_PJ.h
drwxr-xr-x. 2 root root   179 Jan  6 13:41 proj
**-rw-r--r--. 1 root root  8346 Jan  6 13:41 proj_api.h**
-rw-r--r--. 1 root root 23206 Jan  6 13:41 proj_constants.h
-rw-r--r--. 1 root root 34185 Jan  6 13:41 proj_experimental.h
-rw-r--r--. 1 root root 42507 Jan  6 13:41 proj.h
-rw-r--r--. 1 root root 19796 Jan  6 13:41 proj_symbol_rename.h

**Comment by whositwhatnow** [comment]
got terra to install using

PKG_CONFIG_PATH=/cm/shared/apps/proj6/6.0.0/lib/pkgconfig/ R
Then  install.packages("terra", configure.args = c("--with-proj-lib=/cm/shared/apps/proj6/6.0.0/lib/"))

**Comment by rhijmans** [comment]
Thanks for reporting back the solution!
