### ISSUE TITLE
segfault reading and writing certain objects to/from disk

### ISSUE THREAD

**Issue by achubaty** [rspatial/terra#976]
I am recently getting consistent R session crashes trying to read a `raster`-created grd file from disk.

[sample_vtm.zip](https://github.com/rspatial/terra/files/10431833/sample_vtm.zip)

```r
> library(terra)
terra 1.6.47
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
      "3.10.2"        "3.4.3"        "8.2.0"         "true"         "true" 
          PROJ 
       "8.2.0" 
> f <- "sample_vtm.grd"
> r <- rast(f) ## CRASHES!!!

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: new_CppObject_xp(fields$.module, fields$.pointer, ...)
 2: Rcpp::cpp_object_initializer(.self, .refClassDef, ...)
 3: .Object$initialize(...)
 4: initialize(value, ...)
 5: initialize(value, ...)
 6: methods::new(def, ...)
 7: SpatRaster$new(f, subds - 1, "", FALSE, drivers, opts, 0[])
 8: .local(x, ...)
 9: rast(f)
10: rast(f)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
R is aborting now ...
Segmentation fault (core dumped)
```

Loading the data into memory (i.e., `r[] <- r[]`), converting to terra (`tr <- terra::rast(r)`) and attempting to `terra::writeRaster(tr)` also triggers a crash.

I've tried on several machines, using different versions of `Rcpp`, `terra`, and system geospatial libraries. I've also encountered this problem with some other remote sensed rasters (.tif), but I cannot share samples of these for a reprex.

<details closed>

```r

R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.6-47

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9         xml2_1.3.3         knitr_1.41         magrittr_2.0.3    
 [5] details_0.3.0      units_0.8-1        R6_2.5.1           rlang_1.0.6       
 [9] fastmap_1.1.0      httr_1.4.4         tools_4.2.2        grid_4.2.2        
[13] xfun_0.36          png_0.1-8          KernSmooth_2.23-20 cli_3.6.0         
[17] e1071_1.7-12       DBI_1.1.3          withr_2.5.0        clipr_0.8.0       
[21] htmltools_0.5.4    class_7.3-20       rprojroot_2.0.3    digest_0.6.31     
[25] sf_1.0-9           codetools_0.2-18   proxy_0.4-27       compiler_4.2.2    
[29] desc_1.4.2         classInt_0.4-8    

```

</details>

**Comment by achubaty** [comment]
note, I'm not sure if this is the same as #961

**Comment by kadyb** [comment]
It seems that this raster can be loaded if you delete the metadata file `sample_vtm.grd.aux.xml` (but the coordinate system and color table will be lost). It works fine in `{stars}` (so as workaround you can do `rast(read_stars("sample_vtm.grd"))`, but unfortunately the color table is lost too).

**Comment by achubaty** [comment]
Thanks, but at that point I'll stick to `raster` for these files for now. Manually keeping track of the RAT and trying to add it back in later in various points of my existing workflow would be a substantial amount of time.

The sample I shared was cropped manually using QGIS so it included the aux file rather than the typical R grd/gri pair.

**Comment by rhijmans** [comment]
With this change "terra" can read this file.  Note that this file is *not*, in any way, shape or form, a "typical grd/gri" file. It is something entirely different:

```
library(terra)
#terra 1.7.0
f <- "sample_vtm.grd"
describe(f)[1]
[1] "Driver: GSAG/Golden Software ASCII Grid (.grd)"
```

Is that what you get with QGIS when you use a file with extension ".grd"?

Whereas it seems that you think it is "RRASTER". Which is what you get when you use `writeRaster` and a file with extension ".grd"

```
rast(f)
x <- writeRaster(r, "test.grd")
describe("test.grd")[1]
#[1] "Driver: RRASTER/R Raster"
```

I would not use the "GSAG/Golden Software ASCII Grid (.grd)" format because it is an ASCII format (very inefficient). There also seems to be a bug in the writing of the attribute table. The attributes ID starts at 1, whereas the cell values start at 0. When exporting from QGIS it is probably best to use GTiff?

**Comment by achubaty** [comment]
Thank you! Yes, the code that produces the factor raster is old, from a time when raster couldn't reliably write factor geotiffs (attribute tables were lost), but I believe this is no longer an issue.

We are transitioning to terra though, so using geotiffs won't be a problem.
