### ISSUE TITLE
writeRaster error when filetype="COG"

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#977]
I'm trying to export a Cloud Optimized GeoTIFF (COG) file, but I get an error:

```
r <- rast(system.file("ex/elev.tif", package="terra"))
writeRaster(r, filename = "r.tif", filetype = "COG")
Error: [writeRaster] invalid driver
```
This `filetype` is among the GDAL driver names that the `writeRaster` help file points to, and this command is provided in https://geocompr.robinlovelace.net/read-write.html#raster-data-write, so I wasn't expecting this error.

Cheers

PS: I'm using the latest CRAN version of 'terra', on Linux Mint 19.3 Cinnamon

**Comment by Rapsodia86** [comment]
Works on dev version terra "1.6.48" with  gdal "3.5.2"

**Comment by rhijmans** [comment]
Perhaps your GDAL does not support it? I see 

```
library(terra)
# terra 1.7.0

g <- gdal(drivers=TRUE)
g[g$name=="COG", ]
#   name   type        can  vsi                         long.name
#18  COG raster read/write TRUE Cloud optimized GeoTIFF generator

x <- writeRaster(r, "test.tif", filetype="COG")
```

**Comment by Nowosad** [comment]
``` r
library(terra)
r <- rast(system.file("ex/elev.tif", package="terra"))
writeRaster(r, filename = "r.tif", filetype = "COG")
```

I think COG requires GDAL >= 3.1.

**Comment by Rapsodia86** [comment]
> ```r
> library(terra)
> r <- rast(system.file("ex/elev.tif", package="terra"))
> writeRaster(r, filename = "r.tif", filetype = "COG")
> ```
> 
> I think COG requires GDAL >= 3.1.

Indeed: "New in version 3.1." from  https://gdal.org/drivers/raster/cog.html

**Comment by rhijmans** [comment]
You can check if your GDAL version is older or not with `gdal()`
