### ISSUE TITLE
Problems classify raster

### ISSUE THREAD

**Issue by fabiolexcastro** [rspatial/terra#98]
Dear Hijmans, 

I need to change the values using a threshold, I read (page 91, replace section) the library and I tried with this:

```
library(terra)
r <- rast(ncols=10, nrows=10)
values(r) <- (0:99)/99
r[r > 0.2] <- 10
```
But I get this:

`_Error in r[r > 0.2] <- 1 : object of type 'S4' is not subsettable_
`
Could you help me to get any solution. 

Best regards from Cali, 

Fabio Castro

**Comment by rhijmans** [comment]
Fabio. That works in the development version --- which should be on CRAN soon (this week). But there are better alternatives that you can use with the current CRAN version

```
x <- classify(r, cbind(0.2, Inf, 10))
x <- ifel(r > 0.2, 10, r)
```
