### ISSUE TITLE
plet legend issues, wrong numbers and no legend values for spatRaster with non integer values

### ISSUE THREAD

**Issue by simonrolph** [rspatial/terra#983]
I am using leaflet version 2.1.1.9000 and terra version 1.7.2 (development version from r-spatial not CRAN) and R version 4.2.2

```
library(leaflet)
library(terra)
packageVersion("leaflet")
#[1] ‘2.1.1.9000’
packageVersion("terra")
#[1] ‘1.7.2’
# R.version              _                                
#platform       x86_64-w64-mingw32               
#version.string R version 4.2.2 (2022-10-31 ucrt)
 
#I create a spatRaster for reproducing the error. The values go from 1 to 9
test_rast <- rast(matrix(1:9,3,3),crs="epsg:4326")
test_rast
#class       : SpatRaster 
#dimensions  : 3, 3, 1  (nrow, ncol, nlyr)
#resolution  : 1, 1  (x, y)
#extent      : 0, 3, 0, 3  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source(s)   : memory
#name        : lyr.1 
#min value   :     1 
#max value   :     9 
 
#plots okay but numbers are wrong
test_rast %>% plet(tiles = "OpenTopoMap")

#there are no numbers in the legend
plet(test_rast/2,tiles = "OpenTopoMap")
 
```

Here's a screenshot of the first map with the wrong values which should go from 1-9:
![image](https://user-images.githubusercontent.com/17750766/214276366-0c3ad7ad-123a-45ad-bba9-186d6c9bc1f6.png)

And the second map with no values in the legend because I have divided all the values by 2 so there are decimal places
![image](https://user-images.githubusercontent.com/17750766/214276454-59e36dc3-440d-44eb-b954-188a785523ce.png)

**Comment by rhijmans** [comment]
Thanks very much for reporting. Fixed now.

**Comment by simonrolph** [comment]
Thanks @rhijmans much appreciated
