### ISSUE TITLE
Legend reversed by shrink

### ISSUE THREAD

**Issue by frousseu** [rspatial/terra#984]
I'm not sure what the `shrink` argument to `plg` is supposed to do and if it is documented yet, but it seems to be inverting the legend when it is used. Here is an example:

```r
library(terra)
r <- rast(matrix(1:25, ncol = 5))
par(mfrow = c(1, 2))
plot(r)
plot(r, plg = list(shrink = 1))
```
This is with the binary version 1.6-53. I wasn't able to install the latest source version.

**Comment by rhijmans** [comment]
The legend gets larger when shrink is negative. It gets smaller between 0 and 0.5, but with numbers larger than 0.5 the legend is flipped and gets larger again --- but the width is also affected. 
Perhaps it would make more sense if the legend would get smaller between 0 and 1 (and be gone thereafter), and that flipping would be done with another argument.

What we have now:

```
library(terra)
r <- rast(matrix(1:25, ncol = 5))
par(mfrow = c(3, 3))
s <- c(-0.3, -0.1, 0, 0.1, 0.25, 0.3, 0.7, 0.9, 1.2)
for (i in 1:9) {
	plot(r, plg=list(shrink=s[i]), main=s[i])
}
```
![shrink](https://user-images.githubusercontent.com/11481397/215010757-79fb8529-ad8e-49ee-8425-f0b7d904595a.png)

**Comment by frousseu** [comment]
Thank you for the detailed explanation. I should have checked with more values. I admit I don't find those behaviours very intuitive. I agree that having the flipping with an other argument (e.g. `flip = TRUE`) would be clearer. What I would find more intuitive is having a length 2 vector with the default value `c(1, 1)`. With `c(0.8, 1.5)`, the height could be reduced by 20% and the width increased by 50% for example. The flip could also be included with negative values. For example `c(-1.1, 1)` would increase the height by 10% and flip the legend while the width would stay the same. I know there is also an extent argument, but I think it would be easier to just adjust the size with these multipliers.

**Comment by rhijmans** [comment]
I believe I have implemented what you suggested. 

```
library(terra)
r <- rast(matrix(1:25, ncol = 5))
par(mfrow = c(3, 3))
s <- c(-1, -0.75, -0.5, 0.25, 0.5, 0.75, 1, 1.2)
for (i in 1:8) {
	plot(r, plg=list(size=s[i]), main=s[i])
}
plot(r, plg=list(size=c(0.8, 1.5)), main="c(0.8, 1.5)")
````



![leg](https://user-images.githubusercontent.com/11481397/218295937-bb295df1-e281-41cf-bc90-55e5ae3c4ee3.png)

**Comment by frousseu** [comment]
Thank you very much for the implementation. I haven't been successful in installing the latest developement version, but I will test it with the next release.

**Comment by frousseu** [comment]
Works nicely with 1.7-20!
