### ISSUE TITLE
Cannot save and load SpatVector or SpatRaster as rda

### ISSUE THREAD

**Issue by courtiol** [rspatial/terra#987]
I don't manage to save and reload a SpatVector (or SpatRaster) via an rda file even when the object has no value.
(This is problematic, since I want to include terra made objects as lazy loaded objects in a package.)

```r
packageVersion("terra")
# [1] ‘1.7.3’
foo <- terra::vect()
foo
# class       : SpatVector 
# geometry    : none 
# dimensions  : 0, 0  (geometries, attributes)
# extent      : 0, 0, 0, 0  (xmin, xmax, ymin, ymax)
# coord. ref. :  
save(foo, file = "foo.rda")
load("foo.rda")
# Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
#  NULL value passed as symbol address
```
Seems related to #164 although in that issue, but I am creating a separate issue since distinct problems were being discussed there.

**Comment by kadyb** [comment]
You can't save SpatRaster/SpatVector as R object because it is a pointer to object in C++. You should use `terra::wrap()` and `terra::unwrap()` for this:

```r
foo <- terra::vect()
foo <- terra::wrap(foo)
save(foo, file = "foo.rda")
load("foo.rda")
foo <- terra::unwrap(foo)
foo
```

**Comment by rhijmans** [comment]
This cannot be fixed. I think that the .RData format should be avoided. When you use `load` you add objects to your environment with unknown provenance. 

I suppose you want to use `data()` in your package.  Unfortunately, that function has not kept up with time as it does not deal with .rds files. So you could ask the R-core team to add that...  

The simplest solution would be to do something like this: 

```
library(terra)
thedata <- function() {
    f <- system.file("ex/elev.tif", package="terra")
    rast(f)
}
x <- thedata()
```

Which is much better than `data("thedata")`

**Comment by courtiol** [comment]
OK, I understand.

Perhaps a more explicit error message being generated than 'Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  :  NULL value passed as symbol address' could help?

For the lazy loading issue, I think I thus propose to process as follows:

1. store the shapefiles under extdata

2. create a function that load the files similarly to suggested above (but that loads in the pkg envir, here IsoriX):
```r
.build_internal_files <- function() {
  ## This function should not be called by the user.
  ## It performs the lazy loading of the data since terra cannot handle rda files
  assign("CountryBorders", terra::vect(system.file("extdata/CountryBorders.shp", package = "IsoriX")), envir = as.environment("package:IsoriX"))
  assign("OceanMask", terra::vect(system.file("extdata/OceanMask.shp", package = "IsoriX")), envir = as.environment("package:IsoriX"))
}
```

3. call that function automatically upon attach using `.onAttach()`:
```r
.onAttach <- function(libname, pkgname) {
    .build_internal_files() ## lazy loading of the internal data
}
```

It seems to work...

**Comment by rhijmans** [comment]
A better error message would be great, but I do not think I have control over that.  I do not know how to make an invalid object do what I want.

I suppose what you show works. But in my opinion, it is a bad idea to add data to a workspace like that,  That makes the provenance of the data unclear, and you could be overwriting existing data.

**Comment by rhijmans** [comment]
Also, for speed, and perhaps filesize, you may prefer using a `.rds` file instead of a `shp` file. That should load faster.

**Comment by courtiol** [comment]
Thanks,
lazy loading as cons but also pros, and I am trying to be backward compatible despite moving from raster to terra...
++

**Comment by rhijmans** [comment]
Thank you for moving to terra!

**Comment by brownag** [comment]
> A better error message would be great, but I do not think I have control over that. 

It appears that NULL `object@ptr` is treated the same as a "valid" Rcpp_SpatRaster pointer. https://github.com/rspatial/terra/blob/11166f4123e8ee7d2a023cc52e2fe178808a0ae4/R/Aclasses.R#L14-L19

I checked and it seems that if the validity method were to return FALSE for a NULL pointer you would get this message with the example in OP:
```
Error: external pointer is not valid
```

Rather than 
```
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>, :   NULL value passed as symbol address
```

I am not sure if there is anything else that depends on a NULL pointer in the S4 object being allowed... it seems like not much would work if that were the case. Changing as above at least gives a simpler message for these cases where the external pointer is not available.

**Comment by rhijmans** [comment]
This should perhaps be a different thread, but `object@ptr=NULL` is valid. What is not valid is `object@ptr=<something>` where `,something> is an invalid C++ pointer. 

With this problem case `r`

```
r <- rast(nrow=1, ncol=1, vals=1)
save(r, file="test.RData")
load("test.RData")
```

You get a clear error message in many cases; but not in all cases.  

```
r
#class       : SpatRaster 
#Error: external pointer is not valid
dim(r)
#Error: external pointer is not valid
r * 1
#Error: external pointer is not valid

str(r@ptr)
#Error in .Call(list(name = "CppField__get", address = <pointer: (nil)>,  : 
#  NULL value passed as symbol address
```

Note that 

```
is.null(r@ptr)
#[1] FALSE
```

And while this is arguably wrong 

```
#validObject(r)
[1] TRUE
```

That only matters when you actually check for it; which does not happen very often, if at all.
