### ISSUE TITLE
How to add longitude and latitude axis label units in terra::plot?

### ISSUE THREAD

**Issue by tigerwang1998** [rspatial/terra#989]
For example,
```
library(terra)
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
plot(r)
```
It only gives axis value. 
![image](https://user-images.githubusercontent.com/50581765/215248450-50e75ada-4c3f-49ee-9104-0ef1c5f229f0.png)

By the way, is there a way to move axis ticks to the inside of plot?
Just like this:
```
attach(mtcars)
plot(wt, mpg, tck = 0.02)
```
![image](https://user-images.githubusercontent.com/50581765/215250289-3723233a-81ac-4baf-a06d-ba8e28f05131.png)

**Comment by rhijmans** [comment]
You can use `pax=list(retro=TRUE, tcl=0.3))`, but that was broken for `retro`. Fixed with this commit, so that you can do

```
library(terra)
f <- system.file("ex/elev.tif", package="terra") 
r <- rast(f)
plot(r, pax=list(retro=TRUE, tcl=0.3))
```

![retro](https://user-images.githubusercontent.com/11481397/215257287-a1f87bf0-7595-48fa-8760-3e484af0dac9.png)
