### ISSUE TITLE
Building terra from source on an M1 mac (arm) fails

### ISSUE THREAD

**Issue by jebyrnes** [rspatial/terra#993]
I have tried both from CRAN and from the github repo, and both times as I attempt to compile, I get the following error before failure:

```
ld: warning: ignoring file /opt/homebrew/Cellar/gdal/3.6.2_2/lib/libgdal.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_GDALAllRegister", referenced from:
      _main in gdal_test-9f3242.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure: Install failure: compilation and/or linkage problems.
```

So, despite gdal 3.6.2 being installed via homebrew for an M1 mac....... terra is trying to building for macOS-x86_64.  Are there any arguments that can be supplied to get around this or any changes made?

**Comment by rhijmans** [comment]
The problem with the OSX install from CRAN is that the netCDF driver is not included. 

If you have the driver, you should see:

```
library(terra)
d <- gdal(drivers=T)
d[d$name=="netCDF", ]
#     name   type        can   vsi                  long.name
#88 netCDF raster read/write FALSE Network Common Data Format
``` 

The easiest solution might be  to get a binary install from the R-Universe. That one has the netCDF driver; but I do not know which OSX systems are supported. If yours is not supported it will ask you to install from source, and then you are back to square 1.

```
install.packages('terra', repos='https://rspatial.r-universe.dev') 
```

You can install from source with arguments like the below

```
install.packages("terra", configure.args = "--with-proj-lib=/opt/homebrew/Cellar/proj/9.1.0/lib/")
```

But I don't know if that would fix your situation. It looks like you have two installations of GDAL and that always creates trouble .

**Comment by jebyrnes** [comment]
Nope, same error regarding libgdal and x86 versus arm.

```
ld: warning: ignoring file /opt/homebrew/Cellar/gdal/3.6.2_2/lib/libgdal.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_GDALAllRegister", referenced from:
      _main in gdal_test-d47703.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jebyrnes** [comment]
OK, now I just feel like an idiot - for some reason, I had an x86 build of R installed - which I should not have. *sigh*

Reinstalling R and going from there......
